### ISSUE TITLE
Settings not loaded from .runsettings for custom adapter 

### ISSUE THREAD

**Issue by perfectphase** [Microsoft/vstest#1000]
## Description
I've built a custom test adapter that implements ITestDiscoverer and ITestExecutor, this works well and tests are discovered and executed.
I've added an ISettingsProvider with the SettingName attribute.  When I run vstest.console /testAdapterPath:c:\testAdapter /ListSettingsProviders my settings provider is listed.  
If I then add /Settings:mySettingsFile.xml I get the error

Error: Settings file provided does not conform to required format.

And my ISettingsProvider is never called.

I've also tried specifying the testAdapter via the runsettings file with the same issue.

The content of the runSettings file is

```
<RunSettings>
  <CustomAdapter>
    <MySetting>SomeTestData</MySetting>
  </CustomAdapter>
</RunSettings>
```

I've been following the instructions in the docs '0004 Adapter Extensibility'

## Environment
Microsoft (R) Test Execution Command Line Tool Version 15.0.26720.2
Window 10 1703
VS2017 15.3

**Comment by perfectphase** [comment]
Well, it just started working, no idea what I changed! I think I must have had something strange in the setting file.

**Comment by BWcc24** [comment]
I just had the same error message and it turned out that there where some not shown special characters in my settingsfile.
After removing them everything worked
