### ISSUE TITLE
Test Explore default message lingers around even after rebuilding solution

### ISSUE THREAD

**Issue by shahabhijeet** [Microsoft/vstest#1001]
By Default Test Explorer windows shows the following message
Build your solution to discover all available tests. Click "Run All" to build, discover, and run all tests in your solution.

After building my entire solution, the message still lingers around.
![resbuildingsolution_testexploremessage](https://user-images.githubusercontent.com/20732208/29390291-250cec7c-82a4-11e7-85ba-cbe9819569b1.PNG)

## Expected behavior
After rebuilding of the solution, the message should give some actionable message as to what to do next.

## Actual behavior
The default message indicates Rebuild never happened.

## Environment
Microsoft Visual Studio Professional 2017 Preview (2)
Version 15.3.0 Preview 7.1
VisualStudio.15.Preview/15.3.0-pre.7.1+26730.3
Microsoft .NET Framework
Version 4.7.02053
OS: Windows Server 2016

**Comment by Faizan2304** [comment]
Thanks @shahabhijeet for opening the issue with us. 
This bug is related to Test explorer experience . I have moved this to the TestExplorer team
Issue: https://devdiv.visualstudio.com/DevDiv/_workitems?id=480719&_a=edit 
(This is internal Microsoft link, you may not be able to access it)
