### ISSUE TITLE
Better isolation among tests.

### ISSUE THREAD

**Issue by AbhitejJohn** [Microsoft/vstest#1003]
## Description
Today, if there is a bad test(a test that throws a SO/AV which cannot be caught) vstest.console  aborts the entire run, not executing remaining tests in the suite. Can this experience be made more reliable (maybe at the cost of performance) to continue running other tests even if there are rogue tests?

**Comment by Faizan2304** [comment]
@pvlakshm

**Comment by pvlakshm** [comment]
Would be good to have.
