### ISSUE TITLE
Manual Binding Redirects necessary for tests on .NET Framework with indirect Test SDK dependency

### ISSUE THREAD

**Issue by nphmuller** [Microsoft/vstest#1004]
This is basically a follow up to #428.

My test project structure is this:
.Tests.Shared (referenced by the projects below)
.Tests.Unit
.Tests.Integration
.Tests.E2E

.Tests.Shared contains a reference to Microsoft.NET.Test.SDK 15.3.0. That means because of the fix for #428, my .Shared project now gets the binding redirects, but the projects that are actually ran (.Unit, .Integration and .E2E) still don't get any binding redirects.

**Comment by smadala** [comment]
The fix was in Microsoft.NET.Test.SDK which is meta package with prop and targets.  For details refer https://github.com/Microsoft/vstest/issues/515#issuecomment-347825351
