### ISSUE TITLE
No .NET Core tests found after upgrading to VS 2017 update 3.

### ISSUE THREAD

**Issue by smadala** [Microsoft/vstest#1005]
## Description
-  .NET Core tests won't get discovered with VS 2015 update 3, If the test project references `Microsoft.NET.Test.Sdk` < 15.0.0-preview-20170217-05 (Which doesn't have TestContainer project capability https://github.com/Microsoft/vstest/pull/440).

## Steps to reproduce
- Create .NET Core project with Microsoft.NET.Test.Sdk < 15.0.0-preview-20170217-05 package.

## Workaround
- Update Microsoft.NET.Test.Sdk package to a latest stable release (eg: 15.0.0, 15.3.0)

## More details
- For .NET Core project there was a performance improvement fix in VS 2017 Update 3, Test Explorer now only discovers tests for projects which have `TestContainer` project capability.

**Comment by shahabhijeet** [comment]
@smadala Updating to 15.0.0 (stable release) does not help .net core test projects that are multi-targeting.
@navin22 suggested another workaround is to switch the targeting framework to a certain order, netCore targets first and then full desktop targets (e.g. netcore1.1;net452), yes that works.
And finally if a test project is targeting only net452, it fails to discover tests, especially when on a clean machine the user nuget cache is empty (or someone who flushed global/user nuget cache) or a repo that takes dependency on < RestorePackagesPath > in their build system.
Please suggest if I am missing to do anything else.

**Comment by navin22** [comment]
@shahabhijeet: Yes the workaround suggested didn't work for dot net core test projects targeting the net452. As it will be blocked by the NuGet issue. Below workaround will work for dot net core test project targeting net452 in VS 15.3.
Workaround: Add a run settings file to your solution, with the test adapter paths mentioned. Below is the sample file. Go to **_“Test->Test Settings->Select Test Settings File”_** and select the run settings file.
[testrun.runsettings.txt](https://github.com/Microsoft/vstest/files/1238472/testrun.runsettings.txt)

**Comment by snkota** [comment]
This is being tracked external to this repo here:
https://developercommunity.visualstudio.com/content/problem/145900/no-net-core-tests-found-after-upgrading-to-vs-2017.html
