### ISSUE TITLE
[Enhancement] Test Multi-Targeted "Main" Library With Independently Multi-Targeted "Test" Project

### ISSUE THREAD

**Issue by airbreather** [microsoft/vstest#1013]
Copied from a [comment](https://github.com/Microsoft/vstest/issues/624#issuecomment-323541578) in #624, at @Faizan2304's request, and elaborated a bit.

#624 deals with the notion of multi-targeting a test project **itself** to test a multi-targeted "main" library, which would be great for what I assume to be an overwhelmingly common case, where the "main" library targets something like `net461;netstandard2.0`.

As an evolution of that idea, I'd also like some support for having the `TargetFramework` used **by the tests** to be detached from the `TargetFramework` for the project **being tested**.

The use case that I have in mind for this kind of feature, where I do not perceive #624 to be enough, is [NetTopologySuite](https://github.com/NetTopologySuite/NetTopologySuite).  That project still targets `net35-client` for much of its stuff, but it also uses a few nifty things that are only present in `net40` and above (and now `netstandard1.0` and `netstandard1.3` in many libraries).

I know I can have the `ProjectReference` say `Properties="TargetFramework=net35"` or whatever, but ideally I should be able to tell the framework to build and test all the combinations of:

| Framework for Project Under Test | Framework Used to Run Tests |
|-|-|
|`net20`|`net461`|
|`net35`|`net461`|
|`net461`|`net461`|
|`netstandard1.0`|`net461`|
|`netstandard1.0`|`netcoreapp1.0`|
|`netstandard1.0`|`netcoreapp1.1`|
|`netstandard2.0`|`net461`|
|`netstandard2.0`|`netcoreapp2.0`|

So if my multi-targeted library has some slight platform implementation differences in all of `net20`, `net35`, `net46`, `netstandard1.0`, and `netstandard2.0` I'd like to have just one test project that includes the shiny APIs from `net461`, while also making sure that the project being tested actually works on the .NET Core 1.0, 1.1, and 2.0 implementations of .NET Standard (as long as I only use APIs in my test project that are available in the intersection of `net461` + `netcoreapp1.0` + `netcoreapp1.1` + `netcoreapp2.0`, which absolutely does not seem like a burden).

From my perspective, this feels like the kind of use case that shouldn't require me to make a bunch of different .csproj files... ideally, it seems, I'd just have one Test .csproj file that specifies the above 8 (`<TargetFrameworks>net461;netcoreapp1.0;netcoreapp1.1;netcoreapp2.0</TargetFrameworks>` might be added to the top so that the normal build system makes sure to build all the different variants properly) and then just runs with it.

I understand that if the public API surface of the tested library differs between the different target frameworks that the library hits (e.g., if something in the library has a public method that returns `Task<int>`, which obviously isn't available in `net20` or `net35`), then this kind of idea would probably require SDK support to give this kind of matrix first-class support in the .csproj file... for the time being, it would suffice to either use reflection (e.g., a scarier-looking analog to [that](https://github.com/NetTopologySuite/NetTopologySuite/blob/04e8b844c52ca35c9e1db6a03a72fe55349cb2fd/NetTopologySuite.Tests.NUnit/IO/GML2/GMLReaderTest.cs#L76-L104)) or just have a few separate test projects to cover everything: one for the "lowest common denominator", and then one for each set of APIs that differ in availability.

I'm **perfectly content** with manually writing .csproj files for this kind of thing.  I do so anyway, most of the time, for most of the .csproj changes I make.

**Comment by drognanar** [comment]
Tagging @cvpoienaru

**Comment by kendrahavens** [comment]
I believe the multi-targeted test project support that we have today combined with compiler directives may be able to satisfy this issue. Let me know if I'm missing something.

Today, you can target multiple frameworks from a test project and tests will be discovered for every framework listed. For example, if your test project csproj has the target frameworks listed below:
`<TargetFrameworks>netcoreapp2.1;net472</TargetFrameworks>`

Tests will be discovered for both netcoreapp2.1 and net472 and you are able to run them separately either from the Visual Studio Test Explorer using the 'Target Framework' groupby for easily grouping them or from the command-line with:

```console
dotnet test --framework netcoreapp2.1
dotnet test --framework net472
```
If a particular test should only run on a particular framework such as net472, you can surround that test with compiler directives:
```csharp
#if NET472
	{ test method(s) }
# endif
```

Sample solution where a test project is testing a .NET Standard class library and is multi-targeted and uses a compiler directive to only run a certain test on net472: https://github.com/kendrahavens/NETStandardSampleTests

Is this the functionality you were looking for?

**Comment by airbreather** [comment]
> I believe the multi-targeted test project support that we have today combined with compiler directives may be able to satisfy this issue. Let me know if I'm missing something.
> 
> Today, you can target multiple frameworks from a test project and tests will be discovered for every framework listed. For example, if your test project csproj has the target frameworks listed below:
> `<TargetFrameworks>netcoreapp2.1;net472</TargetFrameworks>`

That was #624, which I called out in this issue's initial description as not being enough for the use cases I was interested in.

The critical difference is the fact that there's no convenient way to test both the (say) .NET Standard 1.3 and the .NET Standard 2.0 implementations of some API.  The best we can do by setting `TargetFrameworks` on the test project involves artificially limiting the APIs that can be used for writing the tests themselves, which is not great.

For another example that's a bit simpler than what I opened this with, suppose that I have the following code in a library that targets `<TargetFrameworks>netstandard1.3;netstandard2.0</TargetFrameworks>`:
```csharp
using System.Xml.Linq;

public class MyDataStuff
{
    public XElement Data { get; set; }

    public void SaveDataTo(string filename)
    {
#if NETSTANDARD2_0
        Data.Save(filename);
#else
        System.IO.File.WriteAllText(filename, Data.ToString());
#endif
    }
}
```

This library will (or should) behave identically for everybody who can use it, but as it isn't 2015 anymore, a vast majority of library consumers will be on a platform that supports .NET Standard 2.0, so I deem it worthwhile to give them a "special" build of the library that uses a built-in method that writes an `XElement` to a file much more nicely than what's available in .NET Standard 1.3.

When it comes time to actually write tests for this, however, there isn't a fantastic way for me to ensure that I'm covering both variants of this code.  One option is to make sure that my tests include either a .NET Core 1.x or .NET Framework 4.6 target, but that means that my tests **themselves** are limited to just the things that are available in those frameworks, which seems excessive if I'm OK with assuming that all platforms correctly implement their stated versions of .NET Standard.

Ideally, I should be able to ask the system to use .NET Core 3.1 (with all its shiny APIs) to run all my tests against both the .NET Standard 1.3 version **and** the .NET Standard 2.0 version of my library.

**Comment by airbreather** [comment]
> Ideally, I should be able to ask the system to use .NET Core 3.1 (with all its shiny APIs) to run all my tests against both the .NET Standard 1.3 version **and** the .NET Standard 2.0 version of my library.

My previous comment went into some details about why I would want to run two different versions of my library through tests on (what could be) the same version of the test framework.  To follow on from that (less important to me at the moment), I'll go into some detail about why I might be interested in doing it the other way around: same version of the library, different versions of the tests.  I should note that using `<TargetFrameworks>` for my test projects **would** be enough for this on its own.

Consider the following program:
```csharp
using System;
using System.Linq;

class StringMultiplier
{
    public double Val { get; set; }

    public string Multiply(string x)
    {
        return $"{double.Parse(x) * Val}";
    }

    static void Main(string[] args)
    {
        var multiplierByTwo = new StringMultiplier { Val = double.Parse(args[0]) };
        foreach (string arg in args.Skip(1))
        {
            Console.WriteLine(multiplierByTwo.Multiply(arg));
        }
    }
}
```

This code should, in theory, run on any platform that supports .NET Standard 2.0.  Of course, it requires a concrete application framework in order to actually run, so let's try it with two of them.

When I run this with `dotnet run --framework=netcoreapp3.1 2 0.84551240822557 0.84551240822557006`, I get:

```
1.69102481645114
1.6910248164511401
```

When I go to the `net472` version and run `mono ConsoleApp0.exe 2 0.84551240822557 0.84551240822557006`, I get:
```
1.69102481645114
1.69102481645114
```

(I don't have easy access to a Windows box to test with the official implementation of .NET Framework 4.7.2, but fortunately Mono does the same thing I was looking for here).

Same exact API, different observable behavior.

If I were to, say, [work around this issue with some really non-obvious code](https://github.com/NetTopologySuite/NetTopologySuite/blob/b95d69349418d784729d8c096ed8f321717197c4/src/NetTopologySuite/IO/OrdinateFormat.cs#L136-L155), then it would also be prudent for me to write some test cases that would exercise that code on all the different target frameworks that I care about supporting.

If the same library contained **both** this situation **and** the kind of situation that I identified in my previous comment, then I'd ideally want to see a solution where I could just give the system a list of (LibraryTargetFramework, TestTargetFramework) pairs for it to run.  I'd still have to limit the APIs in my TestTargetFrameworks to a least-common-denominator of a sort, but it wouldn't have to be nearly as limiting as solutions that exist today.

Admittedly, I'm not actively working on any libraries that multi-target like this anymore, so this issue isn't as big a deal for me as it used to be, but that's just my own situation.

**Comment by nohwnd** [comment]
> Ideally, I should be able to ask the system to use .NET Core 3.1 (with all its shiny APIs) to run all my tests against both the .NET Standard 1.3 version and the .NET Standard 2.0 version of my library.

Do you have any suggestion how to make this actually work? 🙂 To use .NET Core 3.1 we would have to run a .NET Core 3.1 compatible test project, and then we would have to run that project twice, once building with netstandard1.3 dependency and in the other case the netstandard2.0 dependency. This would still validate that it only works on netcoreapp3.1 and on the given platform (say Windows).

**Comment by airbreather** [comment]
> > Ideally, I should be able to ask the system to use .NET Core 3.1 (with all its shiny APIs) to run all my tests against both the .NET Standard 1.3 version and the .NET Standard 2.0 version of my library.
> 
> Do you have any suggestion how to make this actually work? :slightly_smiling_face: To use .NET Core 3.1 we would have to run a .NET Core 3.1 compatible test project, and then we would have to run that project twice, once building with netstandard1.3 dependency and in the other case the netstandard2.0 dependency.

A perfect solution would involve a bit of support built into the SDK, but when I opened this issue, I was entirely prepared to deal with some weird workarounds.

I created [MultiTargetDemo](https://github.com/airbreather/MultiTargetDemo) a few years back when trying to figure out what was already available at the time, where I ultimately ended up using multiple .csproj files that would use `net46` to run tests for all of `net20`, `net46`, `netstandard1.0`, `netstandard1.3`, and `portable40-net403+sl5+win8+wp8+wpa81` target frameworks, with just one test class that would validate that the API worked as expected ("`return 3;`") in a platform-agnostic way.

I haven't ever delved into the architecture of vstest before, but I imagine that one possible way to do this without strong SDK support would be to do something like this for people like me to achieve the same goal without having to do a lot of MSBuild tricks:
1. Look for a new property in the MSBuild project, something like "`VSTestPlatformMatrix`".
    - `VSTestPlatformMatrix` looks something like "`netstandard1.3|netcoreapp3.1;netstandard2.0|netcoreapp3.1`"
    - For a given `ReferenceTargetFramework|TestTargetFramework` pair, expect that `TestTargetFramework` can legally reference `ReferenceTargetFramework`.
    - Without strong SDK support, it probably helps to enforce that all distinct `TestTargetFramework` values are present in `<TargetFrameworks>`, since otherwise one risks hitting discovery-time errors that are hard to detect.
1. When "`VSTestPlatformMatrix`" is detected, one or more references has `Properties="VSTestIsMultiTargetTestable=True"`
    - Probably just `ProjectReference` or `PackageReference`, since I don't know what to do about `Reference`.
    - Expect all references flagged this way to directly expose a superset of the distinct values of `ReferenceTargetFramework`.
1. To run the tests, generate (or simulate generating) a new `.csproj` for each entry in `VSTestPlatformMatrix`:
    - It's a direct copy of the original project, but with `<TargetFramework>` replaced by the corresponding `TestTargetFramework` and with the `ProjectReference` or `PackageReference`'s `VSTestIsMultiTargetTestable="True"` property replaced by `TargetFramework="the actual ReferenceTargetFramework"`.

The csproj would look something like:
```xml
<?xml version="1.0" encoding="utf-8"?>
<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
      <TargetFrameworks>net48;netcoreapp3.1</TargetFrameworks>

      <VSTestPlatformMatrix>netstandard1.3|net48</VSTestPlatformMatrix>
      <VSTestPlatformMatrix>$(VSTestPlatformMatrix);netstandard2.0|net48</VSTestPlatformMatrix>
      <VSTestPlatformMatrix>$(VSTestPlatformMatrix);netstandard1.3|netcoreapp3.1</VSTestPlatformMatrix>
      <VSTestPlatformMatrix>$(VSTestPlatformMatrix);netstandard2.0|netcoreapp3.1</VSTestPlatformMatrix>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="$(SolutionDir)Lib1\Lib1.csproj" Properties='VSTestIsMultiTargetTestable="True"' />
    <PackageReference Include="SomeTestSpecificDependency_NetStandard2Only" Version="1.0.0" />
  </ItemGroup>
</Project>
```

That's the broad strokes for how I could see getting a foot in the door... with strong SDK support, we could perhaps see a project that looks something more like:
```xml
<?xml version="1.0" encoding="utf-8"?>
<Project Sdk="Microsoft.NET.Sdk.Test">
  <ItemGroup>
    <ProjectReference Include="$(SolutionDir)Lib1\Lib1.csproj">
      <!-- not sure if this is MSBuild-legal... if not, then it'll be one long string -->
      <TestMatrix>netstandard1.3|net48</TestMatrix>
      <TestMatrix>%(TestMatrix);netstandard2.0|net48</TestMatrix>
      <TestMatrix>%(TestMatrix);netstandard1.3|netcoreapp3.1</TestMatrix>
      <TestMatrix>%(TestMatrix);netstandard2.0|netcoreapp3.1</TestMatrix>
    </ProjectReference>

    <PackageReference Include="SomeTestSpecificDependency_NetStandard2Only" Version="1.0.0" />
  </ItemGroup>
</Project>
```

This would effectively do the same as the weird thing above, but with some more niceness:
1. easier to write, I think, and clearer
1. CLI support: `dotnet test` would directly "see" the full matrix and be able to run them
1. SDK would be able to populate the `<TargetFrameworks>` itself based on what I actually need
1. I think it would be possible to be a bit more flexible, e.g., if the referenced project has only `netstandard1.1` and `netstandard1.6` targets, then the `netstandard1.3|X` lines could hook into the same mechanism that the SDK (/ NuGet?) allows a `netstandard1.3` library to reference the `netstandard1.1` version (`netstandard2.0|X` --> `netstandard1.6`).
1. It could skip duplicate runs (with a warning) if multiple `TestMatrix` entries would ultimately just run the same exact thing in the exact same way (only really relevant when considering the previous bullet point).

----

> This would still validate that it only works on netcoreapp3.1 and on the given platform (say Windows).

The ideas above show how it could extend beyond `netcoreapp3.1`.

re: platform, we fundamentally can't solve this directly through our tooling, but multiple CI systems currently offer support for running a workflow on multiple different platforms.  We're currently doing that with GitHub Actions today: the most recent build [passed](https://github.com/NetTopologySuite/NetTopologySuite/actions/runs/208707604) on the latest versions of Ubuntu, MacOS, and Windows that the CI system offers us.

**Comment by nohwnd** [comment]
Thank you for all the analysis!

This is a new feature and won't be implemented, we are focusing on adding new features to Testing.Platform instead. https://aka.ms/testingplatform
