### ISSUE TITLE
TPv2 still in preview in VS 2017 Update 3

### ISSUE THREAD

**Issue by IvanAlekseev** [Microsoft/vstest#1014]
## Description
Looks like TPv2 is still in preview after updating to VS 2017 Update 3

## Steps to reproduce
Run this command:
```
C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\Common7\IDE\Extensions\TestPlatform\vstest.console.exe
```

## Expected behavior
To see release version in output, I assume it should be 15.3.0

## Actual behavior
```
Microsoft (R) Test Execution Command Line Tool Version 15.3.0-preview-20170628-02
```

## Environment
Windows Server 2016
Visual Studio Community 2017 15.3.2

**Comment by Faizan2304** [comment]
Thank you @IvanAlekseev for pointing this out.
15.3.0-preview-20170628-02 is the final version for 15.3 release (We missed to update version of Microsoft.NET.Test.Sdk with 15.3.0 in 15.3 release). We have uploaded 15.3.0 version to nuget out of band with same bits.
