### ISSUE TITLE
CodeCoverage not working for TargetFramework net452

### ISSUE THREAD

**Issue by hubuk** [Microsoft/vstest#1015]
## Description
Code Coverage is not being reported when the target framework is changed to `net452` from `netcoreapp1.1` as shown in https://github.com/Microsoft/vstest-docs/blob/master/docs/analyze.md#coverage

## Steps to reproduce
1. Create a new xUnit Test Project (.NET Core)
2. Change target framework to net452 in csproj file.
3. Add `<DebugType>Full</DebugType>` and `<PackageReference Include="Microsoft.CodeCoverage" Version="1.0.3" />` elements to the csproj file.
4. Run Code Coverage analysis.

## Expected behavior
Code coverage shall be reported the same as for netcoreapp1.1
1 blocks covered 1 blocks not covered.

## Actual behavior
Code coverage shows
0 blocks covered 0 blocks not covered.

## Environment
| Product | Version |
| -- | -- |
| OS | Windows 10 |
| Visual Studio Enterprise 2017 | 15.3.2 |
| vstest.console.exe | 15.3.0-preview-2017068-02 |

**Comment by harshjain2** [comment]
@hubuk Thanks for feedback.
You will not face this issue in latest Visual Studio 2017 15.5.0 Preview Release which can be downloaded from https://www.visualstudio.com/en-us/news/releasenotes/vs2017-Preview-relnotes

Please try the scenario using latest bits and let us know how it goes.
