### ISSUE TITLE
dotnet test on adding settings takes extremely long for netcoreapp2.0

### ISSUE THREAD

**Issue by RomanKernSW** [Microsoft/vstest#1017]
## Description
I'm currently trying to add Unit Test Task to CI Build but failing to process the test task itself. Until now I always canceled it after 5 minutes. Without the runsettings task whole procedure take around 50 seconds.

## Steps to reproduce
"C:\Program Files\dotnet\dotnet.exe" test C:\agent\_work\1\s\...\..UnitTest.csproj --configuration debug --settings C:\agent\_work\1\s\SourceFolder\CodeCoverage.runsettings --framework netcoreapp2.0

if verbosity added to execution pipeline, the browser stops working on ultimately long output. Guess there are alot of things processing

## Expected behavior
some actual steps even on smallest verbosity level and some response that the process is not "crashed"

## Actual behavior
Starting test execution, please wait...

Build was canceled by agent after 60 minutes

## Environment
Windows 10 Enterprise N, 1703
installations
.NET Core SDK 1.0.4 (64)
.NET Core SDK 1.1.0 (64)
Micrososft .NET Core SDK 2.0.0 (64)

Build Agent Capabilities

Agent.OSVersion | 10.0.15063
Agent.Version | 2.119.1
DotNetFramework | C:\Windows\Microsoft.NET\Framework64\v4.0.30319
DotNetFramework_4.6.2 | C:\Windows\Microsoft.NET\Framework\v4.0.30319
DotNetFramework_4.6.2_x64 | C:\Windows\Microsoft.NET\Framework64\v4.0.30319
MSBuild | C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\MSBuild\15.0\Bin\
MSBuild_15.0 | C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\MSBuild\15.0\Bin\
MSBuild_15.0_x64 | C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\MSBuild\15.0\Bin\amd64\
MSBuild_4.0 | C:\Windows\Microsoft.NET\Framework\v4.0.30319\
MSBuild_4.0_x64 | C:\Windows\Microsoft.NET\Framework64\v4.0.30319\
MSBuild_x64 | C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\MSBuild\15.0\Bin\amd64\

[CodeCoverage.zip](https://github.com/Microsoft/vstest/files/1245625/CodeCoverage.zip)

**Comment by smadala** [comment]
@RomanKernSW Share build logs and sample repro project.

**Comment by RomanKernSW** [comment]
Sorry for late reply.... here is the test project

Console command is:
dotnet test UnitTest.csproj -d diag.txt -s CodeCoverage.runsettings --collect Coverage -v diag
[Project and Logs are here](https://github.com/Microsoft/vstest/files/1283934/publish.zip)
You can find the logs under 

UnitTest/
- diag.txt Test diagnostics
- output.txt Verbosity output

**Comment by harshjain2** [comment]
@RomanKernSW I am able to repro this issue in a previous version of dotnet. 
I tried latest version and this issue is no more reproing. 

Product Information:
 Version:            2.1.0-preview1-007193
 Commit SHA-1 hash:  b925a30be2

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.14393
 OS Platform: Windows
 RID:         win10-x64

Microsoft .NET Core Shared Framework Host

  Version  : 2.1.0-preview2-25616-02
  Build    : 8aa34a95bad481e1b5e4c8286e5cb2d7cb6ed943

**Comment by harshjain2** [comment]
@RomanKernSW Please move to latest version of dotnet. 
Let us know how it goes.

**Comment by RomanKernSW** [comment]
the release date of the 2.1 Version is already fixed?
