### ISSUE TITLE
How to get fully-qualified test name in data collector?

### ISSUE THREAD

**Issue by AM5800** [Microsoft/vstest#1028]
## Description
> Describe the issue you've observed

Hi, I am trying to write my own data collector for .netcoreapp 2.0. I am using latest revision of this repository along with vstest/tools/dotnet/dotnet.exe (not system installed). So my datacollector works and I see events firing. But I can't get fully-qualified test name in TestCaseStart event handler. 
I suppose that TestCaseStartEventArgs.TestElement.FullyQualifiedName should contain this. But it is always null.

## Steps to reproduce
> What steps can reproduce the defect?
> Please share the setup, commandline for vstest.console, sample project, target
> framework etc.

1) Create data collector as described [here](https://github.com/Microsoft/vstest-docs/blob/master/docs/extensions/datacollector.md): 
2) Create mstest test project
3) Launch tests like this:

`C:\Work\vstest\tools\dotnet\dotnet.exe vstest out\DataCollectorTest.dll --collect:"collector" /testadapterpath:"<Path to .collector.dll directory>"`

## Expected behavior
> Share the expected output

I would expect that TestCaseStartEventArgs.TestElement.FullyQualifiedName would contain full test name

## Actual behavior
> What is the behavior observed?

... but it is null

## Environment
> Please share additional details about the test environment.
> Operating system, Build version of vstest.console
vstest:

Microsoft (R) Test Execution Command Line Tool Version 15.3.0-preview-20170601-03

dotnet --info:
.NET Command Line Tools (2.1.0-preview1-006329)

Product Information:
 Version:            2.1.0-preview1-006329
 Commit SHA-1 hash:  defa3c3973

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.15063
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Work\vstest\tools\dotnet\sdk\2.1.0-preview1-006329\

Microsoft .NET Core Shared Framework Host

  Version  : 2.0.0-preview2-25331-01
  Build    : 3e9713398d6ab98d29cc73dc689d5f4f4a09f7b0

vstest repository revision: 
711df17e3c14604df59abfed2ff16587e34944db

**Comment by harshjain2** [comment]
@AM5800 
This issue is already fixed. 
https://github.com/Microsoft/vstest/pull/879

But those changes haven't reached the latest dotnet cli. 

Here is what you can try to unblock yourself:

Instead of using dotnet vstest, use vstest.console.dll under artifacts folder.

>.\tools\dotnet\dotnet.exe vstest --collect:SampleDataCollector /testadapterpath:C:\code\github\harshjain2\vstest\test\TestAssets\OutOfProcDataCollector\bin\Debug\netcoreapp2.0\ C:\code\github\harshjain2\vstest\test\TestAssets\SimpleTestProject\bin\Debug\netcoreapp2.0\SimpleTestProject.dll /testadapterpath:C:\code\github\harshjain2\vstest\test\TestAssets\SimpleTestProject\bin\Debug\netcoreapp2.0\

![image](https://user-images.githubusercontent.com/13763032/29922274-8c2f605e-8e72-11e7-98b8-f9807745fea9.png)

Let us know how it goes.

**Comment by AM5800** [comment]
@harshjain2 thanks, it worked
