### ISSUE TITLE
dotnet test does not discover xUnit Test with asp.net core 2

### ISSUE THREAD

**Issue by darewreck54** [Microsoft/vstest#1034]
Dependencies
- Microsoft.AspNetCore 2.0.0
- Microsoft.NET.Test.sdk 15.3.0
- XUnit 2.2.0

When I run "dotnet test", it can't find the unit test as explain in https://docs.microsoft.com/en-us/dotnet/core/testing/unit-testing-with-dotnet-test

I know the paths are correct because if i install the dotnet xunit console 2.3 beta package "dotnet xunit" is able to find the test and execute them (https://xunit.github.io/docs/getting-started-dotnet-core).

I tried to also upload the 

xunit.runner.visualstudio 2.3.0-beta4-build3742 since 2.2 doesn't seem to support .net core 2.0 and got the following exception:

```
[xUnit.net 00:00:01.0748770] Proj.Tests: Catastrophic failure: System.TypeInitializationException: The type initializer for 'Xunit.DiaSession' threw an exception. ---> System.IO.FileLoadException: Could not load file or assembly 'System.Reflection.TypeExtensions, Version=4.1.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'. A device attached to the system is not functioning.
 (Exception from HRESULT: 0x8007001F)
   --- End of inner exception stack trace ---
   at Xunit.DiaSession..ctor(String assemblyFileName)
   at Xunit.DiaSessionWrapper..ctor(String assemblyFilename)
   at Xunit.XunitFrontController..ctor(AppDomainSupport appDomainSupport, String assemblyFileName, String configFileName, Boolean shadowCopy, String shadowCopyFolder, ISourceInformationProvider sourceInformationProvider, IMessageSink diagnosticMessageSink)
   at Xunit.Runner.VisualStudio.TestAdapter.VsTestRunner.RunTestsInAssembly(IRunContext runContext, IFrameworkHandle frameworkHandle, LoggerHelper logger, TestPlatformContext testPlatformContext, IMessageSinkWithTypes reporterMessageHandler, AssemblyRunInfo runInfo)
```

Question: Is dotnet test broken or is it not suppose to run xunit test?

Thanks,
Derek

**Comment by smadala** [comment]
Dup of https://github.com/Microsoft/vstest/issues/811

**Comment by Sankra** [comment]
I have this exact same problem on both macOS and Windows. Running the following package versions:

Microsoft.AspNetCore 2.0.0
Microsoft.NET.Test.sdk 15.3.0
XUnit 2.3.0
xunit.runner.visualstudio 2.3.0

Any advice @smadala ?

**Comment by smadala** [comment]
@Sankra Updating xunit packages to 2.3.0-beta4-*, Not solved issue for you? If so,  Can you share repro project?

**Comment by Sankra** [comment]
@smadala I've tried the 2.3.0 proper, the latest beta of 2.3.0 and 2.3.1-rc2-build3844. Same result as above every time. 

I'm trying this on this project: https://github.com/Sankra/ComicsService
