### ISSUE TITLE
Inconsistency with DiaSession between MSTest and xUnit.net (as well as VSTest vs. Microsoft Testing Platform)

### ISSUE THREAD

**Issue by bradwilson** [microsoft/vstest#10356]
Quick summary of the problem:

We use `DiaSession` to map types to source in `xunit.runner.visualstudio`:
https://github.com/xunit/visualstudio.xunit/blob/main/src/xunit.runner.visualstudio/Utility/DiaSessionWrapper.cs
https://github.com/xunit/visualstudio.xunit/blob/main/src/xunit.runner.visualstudio/Utility/DiaSessionWrapperHelper.cs

(You can safely ignore the AppDomain gymnastics, as the bug report is using .NET 8.)

We get no source information when a test method comes from a base class in another assembly. MSTest does not have this problem, and I glanced at the source to ensure that they too are relying on `DiaSession`, so this probably comes down to me not understanding how I'm supposed to be using it in this scenario.

Also worth noting that everything works fine when we are in Microsoft Testing Platform mode (rather than VSTest mode), because in that scenario we don't ever see or invoke `DiaSession`; I assume MTP is doing all the source mapping under the hood for us, so it's also doing the right thing.

Any hints what I'm doing wrong in this scenario? Should I be trying to recurse up through the base classes when I get back "no answer" for a type?

For reference, the user issue with a repro project: https://github.com/xunit/xunit/issues/3023

**Comment by nohwnd** [comment]
Tried to transfer, it is still being transferred, but this is imho TE issue https://github.com/microsoft/testfx/issues/3832#issuecomment-2367881369
