### ISSUE TITLE
[9.0] Source-build issue in stage 2 build

### ISSUE THREAD

**Issue by NikolaMilosavljevic** [microsoft/vstest#10364]
Originally created in source-build repo: https://github.com/dotnet/source-build/issues/4641

Stage 2 build is failing in `vstest` with the following error:

```
    /vmr/src/vstest/src/Microsoft.TestPlatform.PlatformAbstractions/common/Tracing/PlatformEqtTrace.cs(87,5): error IDE0032: Use auto property (https://learn.microsoft.com/dotnet/fundamentals/code-analysis/style-rules/ide0032) [/vmr/src/vstest/src/Microsoft.TestPlatform.PlatformAbstractions/Microsoft.TestPlatform.PlatformAbstractions.csproj::TargetFramework=net9.0]
```

Test build (internal link): https://dev.azure.com/dnceng/internal/_build/results?buildId=2550295&view=logs&j=3121c41d-6088-53a5-4ef6-9a86f3460fe9&t=334539f4-dcef-5cad-a240-02997b3146e7

This can be reproduced in `vstest` repo builds by updating SDK to the latest 9.0 build.

cc @nohwnd

**Comment by NikolaMilosavljevic** [comment]
There's another `vstest` issue: https://dev.azure.com/dnceng/internal/_build/results?buildId=2551180&view=logs&j=3121c41d-6088-53a5-4ef6-9a86f3460fe9&t=334539f4-dcef-5cad-a240-02997b3146e7

```
    /vmr/src/vstest/src/Microsoft.TestPlatform.CoreUtilities/Output/ConsoleOutput.cs(15,5): error IDE0032: Use auto property (https://learn.microsoft.com/dotnet/fundamentals/code-analysis/style-rules/ide0032) [/vmr/src/vstest/src/Microsoft.TestPlatform.CoreUtilities/Microsoft.TestPlatform.CoreUtilities.csproj::TargetFramework=net9.0]
```

I'm not sure why the build is only reporting some of them at the time.

@nohwnd

**Comment by nohwnd** [comment]
pushed fix for the other one as well. Please keep reporting them.
