### ISSUE TITLE
Can't import CppCheck xml result to SonarQube

### ISSUE THREAD

**Issue by uskuandeng** [Microsoft/vstest#1048]
## Description
> Everything I'm using is latest. I have successfully analyzed my pure C# project including Code-coverage; also successfully analyzed a C# and C/C++ project by using SonarCFamily scanner except the code coverage (code coverage is generated but can't get the result imported). Now I'm trying CppCheck, I got the following error:
"
  Bin directory: C:\Users\Administrator\bamboo-agent-home\xml-data\build-dir\SEPLC-SCPT-JOB1\.sonarqube\bin
build 07-Sep-2017 10:06:14	Config directory: C:\Users\Administrator\bamboo-agent-home\xml-data\build-dir\SEPLC-SCPT-JOB1\.sonarqube\conf
build 07-Sep-2017 10:06:14   Output directory: C:\Users\Administrator\bamboo-agent-home\xml-data\build-dir\SEPLC-SCPT-JOB1\.sonarqube\out
build 07-Sep-2017 10:06:14	Config file: C:\Users\Administrator\bamboo-agent-home\xml-data\build-dir\SEPLC-SCPT-JOB1\.sonarqube\conf\SonarQubeAnalysisConfig.xml
build 07-Sep-2017 10:06:14	Generating SonarQube project properties file to C:\Users\Administrator\bamboo-agent-home\xml-data\build-dir\SEPLC-SCPT-JOB1\.sonarqube\out\sonar-project.properties
error 07-Sep-2017 10:06:14	The SonarQube MSBuild integration failed: SonarQube was unable to collect the required information about your projects.
error 07-Sep-2017 10:06:14	Possible causes:
error 07-Sep-2017 10:06:14	1. The project has not been built - the project must be built in between the begin and end steps
error 07-Sep-2017 10:06:14	2. An unsupported version of MSBuild has been used to build the project. Currently MSBuild 14.0 upwards are supported
error 07-Sep-2017 10:06:14	3. The begin, build or end steps have not all been launched from the same folder
build 07-Sep-2017 10:06:14	Writing processing summary to C:\Users\Administrator\bamboo-agent-home\xml-data\build-dir\SEPLC-SCPT-JOB1\.sonarqube\out\ProjectInfo.log
build 07-Sep-2017 10:06:14	Generation of the sonar-properties file failed. Unable to complete SonarQube analysis
"
What I did is 3-steps:
    1. Pre_build
       C:\SonarQube\SonarQube.Scanner.MSBuild.exe begin   /k:"LC:MyCPPProject1" /n:"MyCPPProject1" /v:"1.0" /d:sonar.verbose=true  /d:sonar.cxx.cppcheck.reportPath=cppcheck.xml 

    2. Run CppCheck and generate the xml result (the xml file is generated)
        cppcheck.exe" --xml --xml-version=2 --enable=all %CDIR% 2> cppcheck-report.xml
   3. Post Build
       SonarQube.Scanner.MSBuild.exe end

It's Windows. VS 2015 Enterprise. Latest SonarQube and scanners.

**Comment by uskuandeng** [comment]
The problem is solved. The sonar-cfamily-plugin.*.jar and CppCheck plugin can not co-exist.

**Comment by pvlakshm** [comment]
@uskuandeng, in that case I will close this issue.
