### ISSUE TITLE
Allow [ExcludeFromCodeCoverageAttribute] to be used on assembly level 

### ISSUE THREAD

**Issue by abatishchev** [microsoft/vstest#1050]
(Migrated from https://github.com/Microsoft/testfx/issues/248, hope this is the right place to ask this time).

Since this attribute has the following signature:

```csharp
[AttributeUsageAttribute
    (AttributeTargets.Class |
     AttributeTargets.Struct |
     AttributeTargets.Constructor |
     AttributeTargets.Method |
     AttributeTargets.Property |
     AttributeTargets.Event,
     Inherited = false, AllowMultiple = false)]
public sealed class ExcludeFromCodeCoverageAttribute : Attribute
```
one can't use it to annotate whole assembly, effectively making it inconvenient and rarely used. And ends up messing up with Run Settings.

**Comment by pvlakshm** [comment]
Indeed, the attribute cannot be applied at the assembly level. That idea is being tracked here: [corefx #14488](https://github.com/dotnet/corefx/issues/14488).

You can already exclude assemblies from participating via a .runsettings file. See here for details: [MSDN: Customizing Code Coverage Analysis](https://msdn.microsoft.com/en-IN/library/jj159530.aspx).

**Comment by devlie** [comment]
@pvlakshm The attribute can now be specified at assembly level, but seems like VSTest still has not respected it yet. Is there any plan to enable that?

**Comment by Evangelink** [comment]
Reopening the issue as assembly level is not yet supported.
