### ISSUE TITLE
Ship JSON extractor as Visual Studio Web Test plugin

### ISSUE THREAD

**Issue by abatishchev** [Microsoft/vstest#1054]
(Migrated from Microsoft/testfx#247, hope this is the right place to ask this time).

Current set of the built-in plugins hadn't been update for a decade or so, since about VS2005. Currently it supports Plain Text starts/ends with, RegEx, HTML, XML. But not the language of modern Web - JSON.

Please ship one more built-in extractor - for JSON. And make it compatible with Application Insights availability tests.

**Comment by Faizan2304** [comment]
Hi @abatishchev, we owns test engine/platform which runs the test. Your issue seems related to web and load test. 
Please mail your concern on this (vsoloadtest@microsoft.com) email id. I am sure these guys will be able to help you :)

**Comment by codito** [comment]
Tagging @nigurr @acesiddhu for help

**Comment by abatishchev** [comment]
hi @nigurr @acesiddhu, do you have an idea here?

**Comment by abatishchev** [comment]
hi @nigurr @acesiddhu, do you have an idea here, please?

**Comment by acesiddhu** [comment]
Hi @abatishchev we don't track webtest question here. can you mail us at vsoloadtest AT Microsoft DOT com and someone will be able to help. Thanks

**Comment by abatishchev** [comment]
+ @RanjanarMS

**Comment by pvlakshm** [comment]
Outside the scope of this repo. Closing this.
