### ISSUE TITLE
listtests argument prints Discovery Starting and Discovered message twice for net46 test dll

### ISSUE THREAD

**Issue by navin22** [Microsoft/vstest#1057]
## Description
> vstest.console with /listtests argument prints the messages discovery starting and discovered message twice. As shown below.

##### At Start:
> NUnit Adapter 3.8.0.0: Test discovery starting
NUnit Adapter 3.8.0.0: Test discovery starting
Processing C:\Users\navb\source\repos\perfprojects\NunitAdapterPerfTestProject1K\bin\Debug\net452\NunitAdapterPerfTestProject1K.dll
Processing C:\Users\navb\source\repos\perfprojects\NunitAdapterPerfTestProject1K\bin\Debug\net452\NunitAdapterPerfTestProject1K.dll

##### At the End:
> Discovered 1000 test cases
Discovered 1000 test cases
NUnit Adapter 3.8.0.0: Test discovery complete
NUnit Adapter 3.8.0.0: Test discovery complete

## Steps to reproduce
* Latest vstest.console which discovers in inprocess.
* Try to Discover xunit or nunit tests

## Expected behavior
* Only one message of its kind.

## Actual behavior
* Observing two messages of the same kind.

**Comment by Faizan2304** [comment]
Not getting repro. I tried with latest vstest.console, its working fine.
