### ISSUE TITLE
How did I get myself into a place where Microsoft Testing Platform mode is always enabled with `dotnet test`?

### ISSUE THREAD

**Issue by bradwilson** [microsoft/vstest#10605]
I'm trying to reproduce a problem with xUnit.net v3 for someone who is using `dotnet test`, but since installing .NET SDK 8.0.404 (`dotnet test --version` reporting `17.11.9.46202`) it appears that there's no way to disable its recognition and usage of Microsoft.Testing.Platform-compatible test projects, so I'm unable to run tests the same way as users do (that is, through `xunit.runner.visualstudio` and the TPv2 APIs).

Another way to say this is: `<TestingPlatformDotnetTestSupport>true</TestingPlatformDotnetTestSupport>` is no longer required, and in fact, trying to set the value to `false` does not turn off MTP support.

Is there any way for me to get the old behavior back, short of creating a VM and installing an older SDK in it?

-----

This is actually about more than just me reproducing this one bug, though. Users will see `dotnet test --help` and _**virtually everything on that screen will be wrong**_ because those command line options do not apply when running a Microsoft.Testing.Platform project. How is the user to know this will be the case? How can they get an accurate set of command line options for `dotnet test` now?

-----

_**Edit: this turns out to be a local problem that I don't understand but I wouldn't mind help understanding anyways.**_

**Comment by bradwilson** [comment]
If it's useful information, we're currently linked against the 1.4.3 versions of the Microsoft Testing Platform libraries.

**Comment by bradwilson** [comment]
Okay, I'm even more confused now.

I tried installing 8.0.403 alongside 8.0.404 on Windows and I still see broken behavior even when sticking to 8.0.403:

![Image](https://github.com/user-attachments/assets/15a9d2f4-54f8-4e40-bd23-cb4a1dcdc3cf)

However, on 8.0.403 on Ubuntu 24.04 (without 8.0.404) everything is working as expected:

![Image](https://github.com/user-attachments/assets/018cc24f-37a4-4d4c-b5ad-cd8aa2e182ce)

It's not at all clear to me what's going on here.

**Comment by bradwilson** [comment]
Upgrading the Ubuntu box from 8.0.403 to 8.0.404 does _**not**_ break `dotnet test` as I'd expected it to, so now I feel like my Windows machine is in a weird state with MTP always forced on. Is that possible?

![Image](https://github.com/user-attachments/assets/6b1a2289-d622-47dc-970a-89f333a274c8)

**Comment by bradwilson** [comment]
Apparently there is something amiss in my stock test project that I use for reproducing issues. 🤦🏼 

Starting over with `dotnet new xunit3` and everything is working as expected, on 8.0.404 and 9.0.101:

![Image](https://github.com/user-attachments/assets/88220e19-87f3-47d2-a913-e07f1803daf4)

I would still love to know how my project got into this "MTP is always enabled" mode. I can package it up if you want to try to figure it out, because I'm at a bit of a loss.

**Comment by bradwilson** [comment]
Repro project: [vstest-10605-repro.zip](https://github.com/user-attachments/files/18016212/vstest-10605-repro.zip)

I was running `dotnet test` from the `cs` folder.

**Comment by Youssef1313** [comment]
In the repro, you have `<TestingPlatformDotnetTestSupport>true</TestingPlatformDotnetTestSupport>` in `cs.csproj`. Is that intended?

**Comment by bradwilson** [comment]
![Image](https://github.com/user-attachments/assets/76e22344-5672-467b-bf1c-ee3dc5d426e7)

I didn't know I'd put that there, and didn't even think to look there because I have everything like that stuffed into `empty.proj`. That's beyond embarrassing. 😂
