### ISSUE TITLE
Visual Studio fails to discover tests if PlatformTarget is x64

### ISSUE THREAD

**Issue by vcsjones** [Microsoft/vstest#1061]
## Description
I have a SDK-style .csproj project with a TargetFramework of `x64`. Using xunit, the Test Explorer in Visual Studio fails to show any of the tests. If I change the TargetFramework to `x86` or `anycpu`, then the Test Explorer shows all of the tests.

## Steps to reproduce

Sample project:

```xml
<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net462</TargetFramework>
    <PlatformTarget>x64</PlatformTarget>
    <IsPackable>false</IsPackable>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Microsoft.NET.Test.Sdk" Version="15.3.0" />
    <PackageReference Include="xunit" Version="2.2.0" />
    <PackageReference Include="xunit.runner.visualstudio" Version="2.2.0" />
  </ItemGroup>
  <ItemGroup>
  </ItemGroup>
</Project>
```

Create an xunit test:

```cs
using Xunit;

namespace Caturday.Tests
{
    public class UnitTest1
    {
        [Fact]
        public void Test1()
        {
        }
    }
}
```

## Expected behavior

The Test Explorer in Visual Studio 2017 shows `Test1` in the Test Explorer.

## Actual behavior

The Test Explorer in Visual Studio 2017 suggests I build to discover tests.

## Environment

See the samples for an example environment. Visual Studio 2017 Version is 15.3.1.

**Comment by vcsjones** [comment]
At the suggestion of @benaadams, changing the "Default Processor Architecture" in Visual Studio from x86 to x64 fixes it. I find that behavior a little odd. I would have expected the tests to at least be discovered, and that setting would have been ignored given the project specifies a platform.

**Comment by Faizan2304** [comment]
@vcsjones Thanks for your feedback. I have created a bug in TestExplorer for this.
@pvlakshm @AbhitejJohn 
Created a bug in [devdiv](https://devdiv.visualstudio.com/DevDiv/VS.in%20Agile%20Testing%20IDE/_queries?id=492859&fullScreen=false&_a=edit) (Its a microsoft internal link, outside people will not be able to access it) to track this.
