### ISSUE TITLE
CppCheck rules does not exist

### ISSUE THREAD

**Issue by uskuandeng** [Microsoft/vstest#1066]
## Description
> Having sonar-cfamily-plugin-4.11.0.8443 and sonar-cppcheck-plugin-1.0.jar co-exist causes the problem, see #1048 for the problem detail. After removing the "sonar-cfamily-plugin-4.11.0.8443 from ..\extensions\plugins folder (and restarted the server), CppCheck output (the xml result) is successfully imported to SonarQube server, but the SonarQube dashboard shows nothing but the CppCheck xml file! After looking around and found there is any C/C++ related rules can be used.
 
## Steps to reproduce
> Put two plugins in the SonarQube, restart server; run some tests; then manually remove the  sonar-cppcheck-plugin-1.0.jar from the ..\extensions\plugins folder, restart the Sonar. to check the C/C++ rules in the Server.

I'm using all latest components downloaded on-line 

## Expected behavior
> CppCheck rules should be seen.

## Actual behavior
> There is no any C/C++ rules available

## Environment
> Windows 7 for SonerQube server, MySQL (SonarQube and MySQL are in the same Win7); Win7 remote agent. Visual Studio 2015.

**Comment by codito** [comment]
@uskuandeng I looked at #1048 for repro steps, was not able to relate this issue to `vstest.console.exe`. I am afraid this may not be the right repo for issues with `cppcheck` and `sonarqube` integration.

**Comment by codito** [comment]
Closing this issue as not related. Kindly reopen with repro steps if you're observing an issue with `vstest.console.exe`. Sharing a command line or sample to repro the issue will help.
