### ISSUE TITLE
Any interest in a file logger?

### ISSUE THREAD

**Issue by jeffkl** [microsoft/vstest#10698]
The console output can be very verbose for large repositories so I generally turn it to quiet so that Azure DevOps or GitHub Actions UI isn't flooded with thousands of lines of output.  Every once in a while though, our tests encounter problems and I can see the output of stuff like long running test detection in xunit or the blame collector.

I thought it would be good to have a logger that writes all of the detailed output to a file and then if the test run fails, upload that in the hosted build environment for investigation.  Here's my prototype:

https://github.com/jeffkl/vstest-loggers/tree/main/src/File.TestLogger

Would this be something anyone else would want and maybe build directly into the VS test platform?

**Comment by nohwnd** [comment]
This is pretty much what we do in the new testing.platform. VStest is not adding any new features, but the logger extension point is still available, so you can ship you logger in a nuget, and you don't need any new cooperation from vstest to do that. See the TrxLogger for how  to implement: 

https://github.com/microsoft/vstest/blob/main/src/Microsoft.TestPlatform.Extensions.TrxLogger/TrxLogger.cs#L35
