### ISSUE TITLE
/UseVxisExtensions:true is not working.

### ISSUE THREAD

**Issue by harshjain2** [Microsoft/vstest#1078]
## Description
> /UseVsixExtensions:true is not working.

## Steps to reproduce
> Create a MSTest V1 test project.
> Temporarily delete Microsoft.VisualStudio.TestPlatform.Extensions.VSTestIntegration.dll under C:\Program Files (x86)\Microsoft Visual Studio\Preview\Enterprise\Common7\IDE\Extensions\TestPlatform\Extensions
> Run command `C:\Program Files (x86)\Microsoft Visual Studio\Preview\Enterprise\Common7\IDE\Extensions\TestPlatform\vstest.console.exe" test.dll /usevsixextensions:true

## Expected behavior
> Tests should run without error.

## Actual behavior
> Getting this error
>Failed to find the list of installed unit test extensions. Reason: Constructor on type 'Microsoft.VisualStudio.ExtensionManager.ExtensionManagerService' not found.

**Comment by singhsarab** [comment]
This was a bug with Extensibility team. They have fixed it now.
