### ISSUE TITLE
Engineering: break acceptance tests into multiple assemblies

### ISSUE THREAD

**Issue by codito** [microsoft/vstest#1080]
We're now running unit tests in parallel in PR/CI builds. Acceptance tests can also be broken into several assemblies for parallelism.

Suggested by @smadala in https://github.com/Microsoft/vstest/pull/1064#pullrequestreview-61772996

**Comment by Evangelink** [comment]
@nohwnd As per our recent discussions, I think this ticket could be closed.
cc @MarcoRossignoli
