### ISSUE TITLE
Passed test doesn't show up in console logs as it used to show up in TPv1

### ISSUE THREAD

**Issue by acesiddhu** [Microsoft/vstest#1092]
## Description
> Passed test doesn't show up in console logs as it used to show up in TPv1

## Steps to reproduce
Run test via vstest.console.exe with passing test.

## Expected behavior
> it should show passing test as well

## Actual behavior
> Shows only failing test

**Comment by pvlakshm** [comment]
To see passing tests as well, set console logger verbosity to "normal" using ``/logger:console;verbosity="normal"``
Allowed values for this verbosity are ``"quiet"``, ``"minimal"`` (default) and ``"normal"``.

**Comment by acesiddhu** [comment]
This should be the default behaviour. Existing vstest that is shipped doesn't pass this command line and customers need to know the status of their test run that is in progress.

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by gburghardt** [comment]
I tried setting the verbosity to normal and only  using the console logger, yet I don't see anything about tests passing. Just the summary at the end. As tests are completed I'd like to see the pass/fail/inconclusive message on a test by test basis.

**Comment by smadala** [comment]
Fixed here: https://github.com/Microsoft/vstest/pull/1162, @gburghardt If you are using powershell make sure you are using `;` in `"`. I have edited https://github.com/Microsoft/vstest/issues/1092#issuecomment-329692353 . If that doesn't help share your command and project.
