### ISSUE TITLE
Wierd warning printed in case mstestv1 tests are run with testsettings

### ISSUE THREAD

**Issue by acesiddhu** [Microsoft/vstest#1104]
## Description
> When mstestv1 test are run with testsettings with TPV2 package, some weird warning is printed on console

## Steps to reproduce
c:\tpv2\new\vstest.console.exe c:\test\Mstestv1\MstestV1.dll /settings:"C:\test\TestSettings1.testsettings"

## Expected behavior
should just run tests

## Actual behavior
The resolution path '' provided in the assembly resolution settings is not a valid path.
The resolution path '' provided in the assembly resolution settings is not a valid path.
The resolution path '' provided in the assembly resolution settings is not a valid path.

**Comment by singhsarab** [comment]
This seems to be fixed in the latest bits, unable to reproduce now.

**Comment by harshjain2** [comment]
This issue is reproducing with portable package (on machines where VS is not installed).

**Comment by acesiddhu** [comment]
this has been fixed in latest release
