### ISSUE TITLE
nunit adapter perf improvents for vstest runner

### ISSUE THREAD

**Issue by navin22** [Microsoft/vstest#1106]
## Description
When you compare the discovery and execution numbers of [nunit 10K](https://github.com/Microsoft/vstest/tree/master/test/TestAssets/NUnitAdapterPerfTestProject) project 
with vstest.console and nunit.console runner, NUnit discovery and execution is slower in vstest.console.
Below are the numbers.

For Discovery: 

Runner | Adapter Version | ElapsedTime(ms)
-- | -- | --
vstest.console | 3.8.0-dev-00498 | 5099.77
nunit.consolerunner |   | 1847.53

For Execution:

Runner | AdapterVersion | ElapsedTime(ms)
-- | -- | --
vstest.console | 3.8.0-dev-00498 | 47201.9
nunit.consolerunner |   | 43343.06

Perfview analysis of the vstest.console revealed the following as the top issues.
* Converting the test cases from xml test-case to ITestCase object 
* NUnit.Framework.Internal.Execution.TestFinishedEvent.Send  & NUnit.Framework.Internal.Execution.TestStartedEvent.Send methods are taking more time. (Especially cross-app domain calls.)
* RegexInterpreter

The perfview data has been uploaded in [onedrive](https://onedrive.live.com/?authkey=%21AE%2DDBNUufNvMAso&id=6DE122101B7DBF1D%21174&cid=6DE122101B7DBF1D)

## Environment
> Win 10 64 bit machine.
> RAM 16GB
> Latest VsTest.console.

**Comment by smadala** [comment]
Addressed by https://github.com/nunit/nunit3-vs-adapter/pulls?q=is%3Apr+author%3Anavin22+is%3Aclosed
