### ISSUE TITLE
C# Static CC is not working

### ISSUE THREAD

**Issue by sbaid** [Microsoft/vstest#112]
## Description

> C# Static CC is not working
## Steps to reproduce
1. Create a C# Unit Test Project.
2. Add a static code coverage file.
3. Run the test method
## Expected behavior
1. CC File should be generated.
## Actual behavior
1. Test did not get execute and no cc file is generated.
## Environment

It actually worked when set environment variable "TestingTools_DisableTestplatformV2" to 1.

**Comment by saikrishnav** [comment]
No longer an issue with VS 2017 RC3.
However, There is an ASYNC Bug in Visual Studio which has nothing to do with TPV2 - which you can still hit. Workaround is there to figure out that it is not TPV2 issue. 
See https://devdiv.visualstudio.com/DevDiv/_workitems/edit/379966
