### ISSUE TITLE
High CPU usage (~45%) during discovery of 10k tests

### ISSUE THREAD

**Issue by sbaid** [Microsoft/vstest#113]
## Description

> Describe the issue you've observed
## Steps to reproduce
1. Create a unit test project
2. Add the 10k tests ([10KTests.zip](https://github.com/Microsoft/vstest/files/491550/10KTests.zip))
3. Build
## Expected behavior

> Share the expected output
## Actual behavior

During discovery, vstest.console takes up to 50% of CPU. This will slow down other tasks like editing etc. while tests are getting discovered.
Same CPU usage is observed during execution of tests.
## Environment

> Please share additional details about the test environment.
> Operating system, Build version of vstest.console

**Comment by pvlakshm** [comment]
We have since made very robust progress on perf - refer the public releases: xUnit 2.3.0, and NUnit3 test adapter. Closing this issue.
