### ISSUE TITLE
Parallel for Nunit tests is not working as expected

### ISSUE THREAD

**Issue by sbaid** [Microsoft/vstest#114]
## Description

> Describe the issue you've observed
## Steps to reproduce
1. Use the Nunit project under \sasindesk\share\DifferentConfigs\NunitParallelTests1
2. Turn parallel on.
3. Run tests.
## Expected behavior

Test run should complete and report results.
## Actual behavior

The run does not complete.
## Environment

> Please share additional details about the test environment.
> Operating system, Build version of vstest.console

**Comment by pvlakshm** [comment]
Validated that it works in the VS 15.5 Preview 2 bits.
