### ISSUE TITLE
Assert.Inconclusive() fails on async Task test method

### ISSUE THREAD

**Issue by lioobayoyo** [Microsoft/vstest#1143]
## Description
Assert.Inconclusive results as a fail instead of skipped when used in an `async Task` method (instead of a void) 

## Steps to reproduce
Create a .NetCore class library project with the following files, build and start tests.

MyTestAssertProject.csproj :

```
<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>netcoreapp1.1</TargetFramework>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.NET.Test.Sdk" Version="15.3.0" />
    <PackageReference Include="MSTest.TestAdapter" Version="1.1.18" />
    <PackageReference Include="MSTest.TestFramework" Version="1.1.18" />
  </ItemGroup>

</Project>
```

MyTestAssertClass.cs :
```
using Microsoft.VisualStudio.TestTools.UnitTesting;
using System.Threading.Tasks;

namespace TestAssert
{
    [TestClass]
    public class MyTestAssertClass
    {
        [TestMethod]
        public void AssertInconclusive_InVoidMethod_ShouldBeInconclusive()
        {
            Assert.Inconclusive();
        }

        [TestMethod]
        public async Task AssertInconclusive_InAsyncTaskMethod_ShouldBeInconclusive()
        {
            await Task.Run(() => Assert.Inconclusive());
        }
    }
}

```
## Expected behavior
I expect both the tests to be skipped

## Actual behavior
The test in the `public void` test method is skipped, but not the test in the `public async Task` method 

## Environment

Windows 10 Version 1703 (OS 15063.608) 64bits
Visual Studio Professional 15.3.5

**Comment by lioobayoyo** [comment]
just noticed it is already reported here : https://github.com/Microsoft/testfx/issues/249

**Comment by AbhitejJohn** [comment]
Closing this in favor of the issue in testx.
