### ISSUE TITLE
Code Coverage does not work with netcoreapp2.0 projects (VS 2017 15.3.5)

### ISSUE THREAD

**Issue by daughey** [Microsoft/vstest#1152]
## Description
A class library and unit test project built as netcoreapp2.0 will not produce code coverage result files through the IDE or vstest.console.exe.

## Steps to reproduce

1. Create a new solution
2. Add a new Class Library (.NET Core) project to the solution
3. Add a method to Class1 that can be used from a unit test
4. Add a new Unit Test Project (.NET Core)
5. Add the nuget package Microsoft.CodeCoverage to the unit test project
6. Add unit test code to interact with Class1 in ClassLibrary1
7. Build the solution

For VS:
- From the Test menu -> Analyze Code Coverage -> All tests

For vstest.console
- Open a VS 2017 Developer Command Prompt
- change directory to the solution directory and run the command
`"%vsinstalldir%\Common7\IDE\Extensions\TestPlatform\vstest.console.exe" --framework:".NETCoreApp,Version=v2.0" --collect:"Code Coverage" UnitTestProject1\bin\Debug\netcoreapp2.0\UnitTestProject1.dll`
- Return to Visual Studio and open the results file created under the TestResults folder created in the solution directory.

## Expected behavior
A code coverage file should be produced and loaded into the Code Coverage Results view.

## Actual behavior
The Code Coverage results window will show "Empty results generated: No binaries were instrumented"

## Diagnostic logs
[log.datacollector.17-09-29_16-11-30_04570_4.txt](https://github.com/Microsoft/vstest/files/1344822/log.datacollector.17-09-29_16-11-30_04570_4.txt)
[log.host.17-09-29_16-11-32_09946_8.txt](https://github.com/Microsoft/vstest/files/1344823/log.host.17-09-29_16-11-32_09946_8.txt)
[log.txt](https://github.com/Microsoft/vstest/files/1344824/log.txt)

## Environment
Windows 10 Enterprise Version 1607 OS Build 14393.1715
Visual Studio 2017 15.3.5
vstest.console 15.3.0-preview-20170628-02

**Comment by Corniel** [comment]
I can confirm this. The solution I have also has a .NET 4.5 unit test project (using NUunit). Those tests show up in the code coverage report.

**Comment by Febiunz** [comment]
I also can confirm the above issue

**Comment by chunliu** [comment]
You will need to put <DebugType>Full</DebugType> in your .csproj in order for code coverage to work.

**Comment by harshjain2** [comment]
Thanks @chunliu 
This is documented here : https://github.com/Microsoft/vstest-docs/blob/master/docs/analyze.md#working-with-code-coverage

**Comment by prisar** [comment]
`<DebugType>Full</DebugType>`
worked for me
