### ISSUE TITLE
Unit Tests that that create UI controls fail with latest version of vstest.console.exe

### ISSUE THREAD

**Issue by abhishkk** [Microsoft/vstest#1164]
_From @santoorman on September 26, 2017 22:48_

using vstest.console.exe version as described here:

https://github.com/Microsoft/vsts-tasks/issues/5404#issuecomment-332210558

It now publishes properly but now we are getting exceptions with unit tests that create UI controls (running on TFS 2017 server):
System.InvalidOperationException: The calling thread must be STA, because many UI components require this.

These worked fine with the Built In version of vstest.console.exe.

Now am stuck - if I use version of vstest.console.exe that passes all tests (including these UI tests), then it can't publish it (issue 5404 above).  If I use version of vstest.console.exe that can publish properly, then some of the UI tests fail.

What to do?

_Copied from original issue: Microsoft/vsts-tasks#5476_

**Comment by abhishkk** [comment]
_From @santoorman on September 27, 2017 19:0_

just to make clearer 

This one fails on UI tests:
"C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\Common7\IDE\Extensions\TestPlatform\vstest.console.exe"
Version 15.0.0.0
System.InvalidOperationException: The calling thread must be STA, because many UI components require this.

When I use the “latest platform version” – I believe it uses the following?  This one doesn’t publish results:
"C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\Common7\IDE\CommonExtensions\Microsoft\TestWindow\vstest.console.exe"
Version 15.0.26720.2
Error: C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\Common7\IDE\CommonExtensions\Microsoft\TestWindow\vstest.console.exe failed with return code: 1 
2017-09-21T20:29:17.9532729Z ##[warning]Failed to publish test results: '�', hexadecimal value 0x10, is an invalid character. Line 10256, position 10.

**Comment by abhishkk** [comment]
_From @singhsarab on September 28, 2017 6:4_

@santoorman 
For the STA issue, can you please try setting the ExecutionThreadApartmentState
https://github.com/Microsoft/vstest-docs/blob/master/docs/configure.md#execution-thread-apartment-state

**Comment by abhishkk** [comment]
_From @santoorman on September 30, 2017 2:49_

thanks but no go:

2017-09-29T21:22:21.9246859Z Error: Invalid settings 'RunConfiguration'. Unexpected XmlElement: 'ExecutionThreadApartmentState'.
2017-09-29T21:22:21.9246859Z ##[warning]Vstest failed with error. Check logs for failures. There might be failed tests.

<?xml version="1.0" encoding="utf-8"?>
<RunSettings>
  
  <RunConfiguration>
    <ResultsDirectory>.\TestResults</ResultsDirectory>
    <TargetPlatform>x64</TargetPlatform>
    <TargetFrameworkVersion>Framework45</TargetFrameworkVersion>
	     
     
  </RunConfiguration>

also tried to add this in build definition (Override test run parameters):

RunConfiguration.ExecutionThreadApartmentState=STA

**Comment by singhsarab** [comment]
@santoorman As codito aslready mentioned in his reply on https://github.com/Microsoft/vstest/issues/683
 configuration for ExecutionThreadApartmentState will be available in VS 2017.5 releases.

**Comment by singhsarab** [comment]
@santoorman Are you hitting the issue with VS 2017 Update 5 bits ?

**Comment by AlShadi** [comment]
@singhsarab Same issue with VS 2017 15.4.5

**Comment by santoorman** [comment]
correct same issue with 15.4.5, 15.5 is not released yet... not showing up as an update in VS 2017

**Comment by cltshivash** [comment]
VS 2017.5 is available now. Can you please try and let us know if the issue persists ?

**Comment by AlShadi** [comment]
I started using Microsoft.VisualStudio.TestTools.UnitTesting.STAExtensions (https://github.com/saikrishnav/testfxSTAext).

**Comment by cltshivash** [comment]
MSTest tests now run in STA by default for dotnet full. Please use the below to verify

[TestClass]
    public class UnitTest1
    {
        [TestMethod]
        public void TestMethod1()
        {
            Console.WriteLine(Thread.CurrentThread.GetApartmentState());
        }
    }

For dotnet core, please use the STAExtension
