### ISSUE TITLE
Enable 'dotnet test' to be run on published output

### ISSUE THREAD

**Issue by livarcocc** [Microsoft/vstest#1176]
_From @kendrahavens on August 31, 2017 17:9_

## Steps to reproduce
After publishing users should be able to run tests on an already compiled executable.
Would address [dotnet/core #917](https://github.com/dotnet/core/issues/917)
This is more important with the development of IL Linker [#915](https://github.com/dotnet/core/issues/915). The [Linker Instructions](https://github.com/dotnet/core/blob/master/samples/linker-instructions.md) mention that the final executables need to be tested after linking.

## Expected  behavior
Be able to run 'dotnet test' on published output.

## Actual behavior
You can not today. (Or we need to add documentation if you can!)

@smalpani-msft

_Copied from original issue: dotnet/cli#7570_

**Comment by livarcocc** [comment]
_From @kendrahavens on September 6, 2017 16:46_

@pvlakshm Adding Pratap here for visibility.

Edit: Would you mind adding the 'dotnet-test' label?

**Comment by Petermarcu** [comment]
sounds good. I mainly want to make sure folks have a good answer because this is going to become more and more common.

**Comment by kendrahavens** [comment]
We now have a doc for this scenario: [https://docs.microsoft.com/en-us/dotnet/core/testing/unit-testing-published-output](https://docs.microsoft.com/en-us/dotnet/core/testing/unit-testing-published-output)

**Comment by codito** [comment]
Closing the issue since the behavior is now documented.

**Comment by giggio** [comment]
Using `dotnet vstest` does not work with [TestServer](https://docs.microsoft.com/en-us/aspnet/core/test/integration-tests?view=aspnetcore-3.1). Is there a work around that?
