### ISSUE TITLE
Tests that call Environment.FailFast do not fail immediately...

### ISSUE THREAD

**Issue by KevinH-MS** [Microsoft/vstest#1183]
## Description
> Tests that call Environment.FailFast do not fail immediately...

## Steps to reproduce
> Create a new Unit Test Project
> Add a simple test method
> Turn on Live Unit Testing
> See the test run and pass
> Add ```Environment.FailFast("test")``` to the test method

## Expected behavior
> Test should fail immediately and report a "not run" or "failed" result.

## Actual behavior
> Test times out after ~30 seconds with: 
```
System.IO.IOException: Unable to communicate with test host process.
   at Microsoft.VisualStudio.TestPlatform.CommunicationUtilities.TestRequestSender.TryReceiveRawMessage()
   at Microsoft.VisualStudio.TestPlatform.CommunicationUtilities.TestRequestSender.ListenAndReportTestResults(ITestRunEventsHandler testRunEventsHandler)
```

## Diagnostic logs
> Please share test platform diagnostics logs. Instructions to collect logs are [here](https://github.com/Microsoft/vstest-docs/blob/master/docs/diagnose.md#test-platform-diagnostics).  
> The logs may contain test assembly paths, kindly review and mask those before sharing.

## Environment
> Please share additional details about the test environment.
> Operating system, Build version of vstest.console

**Comment by smadala** [comment]
Fixed in https://github.com/Microsoft/vstest/commit/8d8d744c73cdf26aed0c9f64846c941204845590
