### ISSUE TITLE
NullReferenceException

### ISSUE THREAD

**Issue by Ed-Hill** [Microsoft/vstest#1185]
## Description
vstest\src\Microsoft.TestPlatform.Client\TestPlatform.cs

 var testHostManager = this.testHostProviderManager.GetTestHostManagerByRunConfiguration(testRunCriteria.TestRunSettings);
 testHostManager.Initialize(TestSessionMessageLogger.Instance, testRunCriteria.TestRunSettings);

vstest\src\microsoft.testplatform.common\hosting\testruntimeprovidermanager.cs
GetTestHostManagerByRunConfiguration can return null which will cause a NullReferenceException on the attempt to call Initialize.

**Comment by Ed-Hill** [comment]
Looks like this will be addressed in : 
https://github.com/Microsoft/vstest/pull/1198

**Comment by smadala** [comment]
@Ed-Hill Thanks for reporting issue. You are right #1198 will address it. Did you run into trouble because this?

**Comment by codito** [comment]
Closing since #1198 is merged.
