### ISSUE TITLE
/Listtests along with /testcasefilter should show warning.

### ISSUE THREAD

**Issue by khilan2goel** [Microsoft/vstest#1189]
## Description
> While using /listtests along with /testcasefilter warning should be shown because TestCaseFilter is not available in Discovery. 

## Steps to reproduce
Run Vstest.console.exe test.dll /listtests /testcasefilter:"Priority:1"

## Expected 
Warning should be displayed.

## Actual behavior
It works without showing any warning.

**Comment by harshjain2** [comment]
/cc : @pvlakshm, @sudiptadmsft 
Pratap, can you help us with the right behaviour and message to be displayed?

**Comment by pvlakshm** [comment]
There are several argument combinations that might not make sense to use together. Documenting all such combinations would not be useful, IMO. 
Rather, and in this case, we should clearly document that /listtests will list all available tests. This should be mentioned in the docs as well as in the descriptions emitted in the CLI.

**Comment by codito** [comment]
Here's the current help for `/listTests`:
```
-lt|--ListTests|/lt|/ListTests:<File Name>
      Lists discovered tests from the given test container.
```

Is this worded appropriately?

**Comment by AbhitejJohn** [comment]
As part of the Telemetry changes we also expose Filtering to the Discovery Tests protocol in Design mode. Do we want to show a warning if someone passes in a filter there too?

**Comment by pvlakshm** [comment]
How about the following:
```
-lt|--ListTests|/lt|/ListTests:<File Name>
      Lists all discovered tests from the given test container.
```

**Comment by singhsarab** [comment]
With https://github.com/Microsoft/vstest/pull/1074 and adapter changes, filtering is now supported on discovery as well.
