### ISSUE TITLE
dotnet test --blame is creating sequence.xml(attachment file) in "location-dotnet\sdk\version-folder\ResultsDirectory"

### ISSUE THREAD

**Issue by Faizan2304** [Microsoft/vstest#1207]
## Description
> dotnet test --blame is creating sequence.xml(attachment file) in "location-dotnet\sdk\version-folder\ResultsDirectory"

## Steps to reproduce
> create a test project with a test which will crash ( A test method with stackOverFlowException)
> run `dotnet test --blame`

## Expected behavior
> it should create attachment(`Sequence.xml`) in current working directory

## Actual behavior
> it tries to create file in dotnet folder

## Work Around
> Pass `ResultsDirectory` in commandLine or in runsettings

**Comment by Faizan2304** [comment]
## Work Around

Pass `ResultsDirectory` in commandLine or in runsettings

**Comment by harshjain2** [comment]
Fix : https://github.com/Microsoft/vstest/pull/1208
