### ISSUE TITLE
[Test] EventLogDataCollectorShoudCreateLogFileHavingEvents is failing in PR builds

### ISSUE THREAD

**Issue by Faizan2304** [Microsoft/vstest#1216]
## Description
https://ci.dot.net/job/Microsoft_vstest/job/master/job/Windows_NT_Debug_prtest/1451/consoleFull#15018181168943a369-e80c-4557-899a-c780301de2ed 

## Diagnostic logs
> ... .. . Total tests: 398. Passed: 381. Failed: 1. Skipped: 16.
06:17:33 ... .. . Failed tests:
06:17:33 ... .. . Failed tests:
06:17:33 ... .. .. . 1. Microsoft.TestPlatform.AcceptanceTests.EventLogCollectorTests.EventLogDataCollectorShoudCreateLogFileHavingEvents (RunnerFramework = net451, TargetFramework = net451, InIsolation)
06:17:33 ... .. .. .. .ErrorMessage: 
06:17:33 Assert.IsFalse failed. StdErrorOutput - [Data collector 'Event Log' message: Data collector caught an exception of type 'System.IndexOutOfRangeException': 'Index was outside the bounds of the array.'. More details: The 'Application' event log has encountered an exception, some events might get lost. Error : System.IndexOutOfRangeException: Index was outside the bounds of the array. at System.Diagnostics.EventLogInternal.IntFrom(Byte[] buf, Int32 offset) at System.Diagnostics.EventLogInternal.GetCachedEntryPos(Int32 entryIndex) at System.Diagnostics.EventLogInternal.GetEntryWithOldest(Int32 index) at System.Diagnostics.EventLogInternal.GetEntryAtNoThrow(Int32 index) at System.Diagnostics.EventLogInternal.GetEntryAt(Int32 index) at Microsoft.TestPlatform.Extensions.EventLogCollector.EventLogContainer.OnEventLogEntryWritten(Object source, EntryWrittenEventArgs e)..Test Run Failed.] did not contain expected string 'event log has encountered an exception, some events might get lost'
06:17:33 ... .. .. .. .StackTrace: 
06:17:33    at Microsoft.TestPlatform.TestUtilities.IntegrationTestBase.StdErrorDoesNotContains(String substring)
06:17:33    at Microsoft.TestPlatform.AcceptanceTests.EventLogCollectorTests.EventLogDataCollectorShoudCreateLogFileHavingEvents(RunnerInfo runnerInfo)
06:17:33 
06:17:33 ... .. .. .. .StdOut: 
06:17:33 IntegrationTestBase.Execute: Starting vstest.console.exe
06:17:33 IntegrationTestBase.Execute: Path = D:\j\workspace\Windows_NT_De---9fe03a42\artifacts\Debug\net451\win7-x64\vstest.console.exe
06:17:33 IntegrationTestBase.Execute: Arguments = "D:\j\workspace\Windows_NT_De---9fe03a42\test\TestAssets\EventLogUnitTestProject\bin\Debug\net451\EventLogUnitTestProject.dll" /testadapterpath:"D:\j\workspace\Windows_NT_De---9fe03a42\packages\MSTest.TestAdapter\1.2.0-beta\build\_common" /settings:"C:\Users\dotnet-bot\AppData\Local\Temp\test_368248b3-0830-479f-80bc-69d34750c012.runsettings" /logger:"console;verbosity=normal" /ResultsDirectory:C:\Users\dotnet-bot\AppData\Local\Temp\9ca6d6c9-1f3f-464d-a043-06ced1a1bc43
06:17:33 IntegrationTestBase.Execute: Stopped vstest.console.exe. Exit code = 1
06:17:33 ... .. Test: Complete (net451).
06:17:33 ... Invoke-Test: Complete. {00:26:51.4319874}
06:17:33 ... Test complete. {00:26:51.7877891}
06:17:34

**Comment by codito** [comment]
Fixed. Closing this issue.
