### ISSUE TITLE
Discover test methods failed on fresh new installation of VS2017 unit test project(target netcore 1.0)

### ISSUE THREAD

**Issue by JohnMasen** [Microsoft/vstest#1223]
## Description
> the unit test failed to discover the unit tests on a unit test project.
> This only happens on fresh new install of VS2017.  
> I tried manually install netcore 1.0 SDK, seems not helping.

## Steps to reproduce
>0.Perform a fresh new install of Windows 10(10.0.16299.15) and VS2017 (15.4.1)
>1.Create a new unit test project
>2.change the TargetFramework to ".Net core 1.0"
>3.Build the project
>4.check the test explorer

## Expected behavior
> "TestMethod1" should appear in test explorer

## Actual behavior
> test explorer is empy
> error message appears in output window
>[2017/10/25 10:01:06 Informational] ------ Discover test started ------
>[2017/10/25 10:02:06 Error] Testhost 进程已退出，并显示错误: It was not possible to find any compatible framework version
>The specified framework 'Microsoft.NETCore.App', version '1.0.5' was not found.
 > - Check application dependencies and target a framework version installed at:
 >     \
 > - Alternatively, install the framework version '1.0.5'.
>。
>[2017/10/25 10:02:06 Informational] ========== Discover test finished: 0 found (0:01:00.2364966) ==========

## Diagnostic logs
> NA as the test cannot even start

## Environment
> Fresh install of Windows 10(10.0.16299.15) and VS2017 (15.4.1)

**Comment by codito** [comment]
@JohnMasen can you please share the contents of `C:\Program Files\dotnet\shared\Microsoft.NETCore.App`?

Does the same error show up with `dotnet test` from `Developer Command Prompt`?

**Comment by JohnMasen** [comment]
1. Directory of C:\Program Files\dotnet\shared\Microsoft.NETCore.App
2017/10/25  09:51    <DIR>          .
2017/10/25  09:51    <DIR>          ..
2017/10/25  09:51    <DIR>          1.0.4
2017/10/25  09:51    <DIR>          1.1.1
2017/10/23  20:13    <DIR>          2.0.0


2. PS D:\MyGitHub\My Repro\ChakraCore.NET\source\ChakraCore.NET.UnitTest\bin\Debug\netcoreapp1.0> dotnet test ChakraCore.NE
T.UnitTest.dll
D:\MyGitHub\My Repro\ChakraCore.NET\source\ChakraCore.NET.UnitTest\bin\Debug\netcoreapp1.0\ChakraCore.NET.UnitTest.dll(1,1): error MSB4025: ?????????Data at the root level is invalid. Line 1, position 1.

**Comment by codito** [comment]
The `1.0.5` runtime is not installed on this machine. Can you install it from below link?

https://github.com/dotnet/core/blob/master/release-notes/download-archives/1.0.5-download.md (Just installing the **Runtime Installer** links on this page should suffice)

**Comment by JohnMasen** [comment]
Issue is fixed after install the 1.0.5 runtime.
