### ISSUE TITLE
Microsoft.TestPlatform.Portable as a DotnetCLIToolsReference

### ISSUE THREAD

**Issue by codito** [microsoft/vstest#1228]
## Description
Allow users to use `Microsoft.TestPlatform.Portable` as a dotnet CLI tools reference. See https://github.com/Microsoft/vstest/issues/1224#issuecomment-339376792 for context.

**Comment by singhsarab** [comment]
@ShreyasRmsft This seems related to the ask we got from the customer the other day. Right?

**Comment by ShreyasRmsft** [comment]
@singhsarab @codito yes seems similar to https://github.com/Microsoft/vstest/issues/1948

The reason is we don't have any default props file along with these packages that copies them to the output directories when added as a package ref.

**Comment by StipecMV** [comment]
any news about this?

**Comment by nohwnd** [comment]
This is a new feature and won't be implemented, we are focusing on adding new features to Testing.Platform instead. https://aka.ms/testingplatform
