### ISSUE TITLE
xUnit.net + Fall Creator's Update == Fail to discover tests

### ISSUE THREAD

**Issue by bradwilson** [Microsoft/vstest#1235]
## Description

When a developer is targeting the Fall Creator's Update with xUnit.net, tests cannot be discovered in Test Explorer.

## Steps to reproduce

The user creates a test project (roughly) following [the directions here](https://xunit.github.io/docs/getting-started-uwp.html), targeting the Fall Creator's Update.

A repro project can be found here: https://github.com/bradwilson/FallCreatorsUpdateXunitRepro This project contains a UWP class library (`ClassLibrary`1, for the "production" code), a VSTest project (`UnitTestProject1`), and an xUnit.net Device Runner project (`DeviceRunnerApp1`). The last is not strictly speaking necessary, but is provided to show that the device runner does continue to work as expected, and that the issue is limited to VSTest.

## Expected behavior

The user expects to see tests in Test Explorer that can then be run.

## Actual behavior

No tests show up in Test Explorer.

The Tests pane of the Output window shows this warning during discovery:

> Skipping: UnitTestProject1 (could not find dependent assembly 'System.Private.CoreLib, Version=4.0.0')

This behavior comes about because VSTest does UWP test discovery in the desktop CLR. While this has "worked" in the past (with significant caveats), this no longer functions correctly for FCU, presumably because the required dependencies are no longer cross-compatible with the desktop CLR. Please note that `System.Private.CoreLib` is not present in the `bin` folder of the compiled test project, nor is it in the GAC on my local machine.

The only realistic fix is for test discovery to happen in a UWP process. For now, xUnit.net users have no realistic workaround to get VSTest + FCU + xUnit.net to work; they must either downgrade their minimum Windows version, or use the device runner to run the tests. (You can see the device runner in action by setting `DeviceRunnerApp1` as the startup project, and then running it.)

## Environment

Windows 10 Fall Creator's Update
Visual Studio 2017 15.4.1

_Related: xunit/xunit#1530_

**Comment by mayankbansal018** [comment]
@bradwilson , This is a known issue, which comes when both Min/Max Target SDK's are set to Fall Creator Update.
We are working internally with UWP to fix this issue in VS 15.5 time frame.

**Comment by devsko** [comment]
Are there any news about this? xunit UWP Tests are still not discovered by VS 15.5 RTM. SDK MinVersion 16299 is required for using .NET Standard 2.0 which our tests depend on.

**Comment by mayankbansal018** [comment]
@devsko, Since the introduction of "Falls Creator Update" the UWP team has made significant changes in their support, due to we which our existing discovery mechanism (using reflection) is no longer supported.
The alternative solutions that we have are
- Launch UWP app, & do discovery inside it.
- Use Roslyn API's to do discovery.

@bradwilson, from xunit team is in talks with VS IDE team on how both the approaches will help resolve this issue for xunit.

**Comment by bradwilson** [comment]
@mayankbansal018 wrote:

> * Launch UWP app, & do discovery inside it.
> * Use Roslyn API's to do discovery.

These are not either/or.

You need a UWP container, whether you're doing source- or binary-based discovery. That extensibility code may be compiled against the target platform, and may rely on APIs that are only available inside UWP. So source-based discovery for UWP for xUnit.net means source-based discovery _**running inside a UWP container**_. There's simply no other way to do it correctly.

The same is true for .NET Core: source-based discovery of `netcoreapp` tests must be running inside of .NET Core, and not the desktop CLR.

**Comment by devsko** [comment]
@mayankbansal018 @bradwilson Thanks for your replies. I think i understand the problem.
What do you recommend? MSTest is working without any problem in this scenario. Or is there a chance for xunit to support this in the near future?

**Comment by bradwilson** [comment]
MSTest does not offer the extensibility points that xUnit.net does. They can do their work purely based on reflection, and without needing to run any user code.

These extensibility points are the heart of the design of xUnit.net. There is zero chance that they will be removed.

**Comment by devsko** [comment]
I agree. Hope the right people come together and find a solution for discovering/starting/debugging UWP tests inside VS and during server build. In the meantime we use xunit.runner.devices to manually run tests. We really try to use UWP for a pretty large application and sometimes its hard. Not having xunit makes it even harder.

**Comment by mayankbansal018** [comment]
@devsko , xUnit has modified their visualstudio runner, to work with latest Test platform. This issue will get resolved with next release of xUnit VS runner.
[PR](https://github.com/xunit/xunit/pull/1618)
