### ISSUE TITLE
Add Acceptance tests for TranslationLayer

### ISSUE THREAD

**Issue by smadala** [microsoft/vstest#1239]
## Description
- Add end to end tests for vstest.console APIs

## Scenarios
- [x] Discovery
- [x] Run
- [x] Run selected
- [x] Custom testhost (should mimic debugger)
- [x] LUT (MSTest, xUnit)
- [x] Source info( Testcase navigation)
- [x] Testcase filter and fast filter
- [x] Telemetry
- [x] Auto determine run configuration (platform, framework, testadapterpath)
- [ ] Code coverage
- [ ] Fakes
- [ ] Old ObjectModel
- [x] Multiple Frameworks (xunit, nunit, chutzpah)
- [x] Test configuration: runsettings w/ testsettings

**Comment by mayankbansal018** [comment]
Add Acceptance for parallel code coverage, & verifying merge results

**Comment by singhsarab** [comment]
@mayankbansal018 Is there anything we wish to track here ?

**Comment by mayankbansal018** [comment]
closing it
