### ISSUE TITLE
Microsoft.NET.Test.Sdk crashes Docker hosted .Net Core 2.0 App

### ISSUE THREAD

**Issue by szavoda** [Microsoft/vstest#1248]
## Description

Adding a unit test project with the Microsoft.NET.Test.Sdk dependency to a solution with a WebApi causes the WebApi app not to start.  This only happens when hosted within a docker container running the microsoft/aspnetcore image.

## Steps to reproduce

To reproduce, create a simple 2 project solution (WebApi and Unit Test) with .Net Core 2.0.  Build a docker image based on the solution.  Run the docker image and see that you will receive an error "terminate called after throwing an instance of 'EEFileLoadException*'.  Removing the dependency from the Test project allows the project to run as expected.  Github repo project can be found [https://github.com/szavoda/Microsoft.NET.Test.Sdk](https://github.com/szavoda/Microsoft.NET.Test.Sdk).

Build docker file from project root directory with command: build -f myservice/orchestration/dockerfile -t sdktestproblem .

Run Docker file with command: docker run -it --rm -p 8080:80 sdktestproblem

## Expected behavior

WebApi should run and listen on default port 80

## Actual behavior

Run the docker file with "".  Error occurs: terminate called after throwing an instance of 'EEFileLoadException*'

## Environment

Docker file build attempts have been made on several environments with the same result.  Docker is a Linux host.  Microsoft aspnetcore images are "latest".

**Comment by codito** [comment]
Thanks for reporting this @szavoda. I'm able to repro the issue. Marking it as a bug for triage.

**Comment by codito** [comment]
Some more information from investigation. `dotnet WebApi.dll` is failing due to mismatch in two dependencies:
- NewtonSoft.Json.dll - WebApi requires `10.0`, Microsoft.NET.Test.Sdk brings in `9.x`
- Microsoft.Extensions.DependencyModel - WebApi requires `2.0.0`, Microsoft.NET.Test.Sdk brings in `1.x`

**Workaround**
Add these dependencies to a higher version explicitly to test project.
```diff
diff --git a/MyService/Orchestration/Tests/Skeleton.tests.csproj b/MyService/Orchestration/Tests/Skeleton.tests.csproj
index b5f4da2..35085c8 100644
--- a/MyService/Orchestration/Tests/Skeleton.tests.csproj
+++ b/MyService/Orchestration/Tests/Skeleton.tests.csproj
@@ -7,9 +7,14 @@
   </PropertyGroup>

   <ItemGroup>
     <PackageReference Include="Microsoft.NET.Test.Sdk" Version="15.3.0" />
     <PackageReference Include="MSTest.TestAdapter" Version="1.1.18" />
     <PackageReference Include="MSTest.TestFramework" Version="1.1.18" />
+
+    <PackageReference Include="NewtonSoft.Json" Version="10.0.1" />
+    <PackageReference Include="Microsoft.Extensions.DependencyModel" Version="2.0.0" />
   </ItemGroup>

 </Project>
```

@szavoda do you need the test projects to be published in a docker image? May be there's a way to skip publishing those.

**Comment by szavoda** [comment]
@codito - in order to keep our dockerfile more generic (and use the same basic layout over several dozen solutions) we build based on solution rather than projects.  Our current workaround is to remove the test projects from the solution, but unfortunately, that means that TDD becomes more challenging.  

Another note - the current Microsoft.NET.Test.Sdk that is used during the project creation using the Unit Test VS Template is a preview version - 15.0.3.previewxxxxxx (can't remember the exact number).  The problem still exists with this version, but I thought it was worth noting.

I will check out the workaround and report back.

**Comment by codito** [comment]
@szavoda as I understand, the requirement is to ensure `Dockerfile` does a `dotnet publish myservice.sln`. It runs the actual _WebApp_. There isn't a need to run tests in the docker container.

May be it is better to turn off `publish` for all test projects. This property could be put in all test projects or in a build props file imported in the test projects.

```diff
diff --git a/MyService/Orchestration/Tests/Skeleton.tests.csproj b/MyService/Orchestration/Tests/Skeleton.tests.csproj
index b5f4da2..4c860ac 100644
--- a/MyService/Orchestration/Tests/Skeleton.tests.csproj
+++ b/MyService/Orchestration/Tests/Skeleton.tests.csproj
@@ -4,6 +4,7 @@
     <TargetFramework>netcoreapp2.0</TargetFramework>

     <IsPackable>false</IsPackable>
+    <IsPublishable>false</IsPublishable>
   </PropertyGroup>

   <ItemGroup>
```

I am wondering if it's possible to fix this in Microsoft.NET.Test.Sdk. We can't upgrade the dependencies of Microsoft.NET.Test.Sdk as it may break older test projects (netcoreapp1.0 for instance). Dependencies should stay at the lowest possible versions.

Ideally, these conflicts are resolved during publish if Project System is aware of the conflicts (this is how the first workaround works). However for publish in sln, I don't think the Project System understands if there are conflicts across projects, hence it just copies explicit dependencies, that leads to runtime failure.

**Comment by szavoda** [comment]
@codito thanks!  I was not aware of the <IsPublishable> option.  That makes for a great workaround.

**Comment by codito** [comment]
Thanks @szavoda for confirmation. Marking this issue closed.
