### ISSUE TITLE
Enabling of TRX Logger/Any loggers is not possible VIA runsettings/testsettings

### ISSUE THREAD

**Issue by acesiddhu** [Microsoft/vstest#1262]
## Description
> Enabling Trx logger (or any logger) via Runsettings/TestSettings

## Steps to reproduce
Today in Multi Agent flow we use TestLoggerManagerClass to generate TRX file. We want to get rid of this dependency in TPV2. Hence this requirement

**Comment by adamfriedland** [comment]
Is there any update on this? Would be very convenient to specify certain logger configurations via runsettings.

**Comment by smadala** [comment]
Addressed https://github.com/Microsoft/vstest/pull/1382
