### ISSUE TITLE
Platform API should accept Custom Adapters folder 

### ISSUE THREAD

**Issue by nigurr** [microsoft/vstest#1268]
Platform v1 API accepts custom adapter folder to find the right set of adapters to use for discover/execution.
Platform v2 API requires full path to adapter and fails to execute tests/discovery when user has given adapter path.

It should support both to maintain consistent API experience

**Comment by pvlakshm** [comment]
Is it possible to change the API-consumption logic to specify full path to adapter?

**Comment by nigurr** [comment]
@pvlakshm yes we can. but it would be different for v1/v2.

**Comment by smadala** [comment]
@nigurr Is this still relevant?
