### ISSUE TITLE
Are data collector events synchronous?

### ISSUE THREAD

**Issue by AM5800** [Microsoft/vstest#1279]
## Description
> Describe the issue you've observed

It is merely a question about how it is supposed to be. Can I expect that if I subscribe to TestCaseStart event test case won't start until I finish my work in that callback?

Right now tests are started when I am still in the middle of my callbacks.

## Steps to reproduce
> What steps can reproduce the defect?
> Please share the setup, commandline for vstest.console, sample project, target
> framework etc.

Crete data collector, subscribe to TestCaseStart. Put a 10 second sleep in it. And then log the following events:
Actual test body start
TestCaseStart callback after 10 second sleep

## Expected behavior
> Share the expected output

## Actual behavior
> What is the behavior observed?

## Diagnostic logs
> Please share test platform diagnostics logs. Instructions to collect logs are [here](https://github.com/Microsoft/vstest-docs/blob/master/docs/diagnose.md#test-platform-diagnostics).  
> The logs may contain test assembly paths, kindly review and mask those before sharing.

## Environment
> Please share additional details about the test environment.
> Operating system, Build version of vstest.console
Microsoft (R) Test Execution Command Line Tool Version 15.5.0-preview-20171012-09

.NET Command Line Tools (2.2.0-preview1-007460)

Product Information:
 Version:            2.2.0-preview1-007460
 Commit SHA-1 hash:  173cc035e4

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.15063
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Work\vstest\tools\dotnet\sdk\2.2.0-preview1-007460\

Microsoft .NET Core Shared Framework Host

  Version  : 2.1.0-preview1-25825-07
  Build    : 4c165c13bd390adf66f9af30a088d634d3f37a9d

**Comment by pvlakshm** [comment]
Yes, they are intended to be synchronous.

**Comment by AM5800** [comment]
@pvlakshm thanks, but as I said they are not synchronous for me. Should I create a new issue or update this one?

I have created a sample solution. 
[DC202.zip](https://github.com/Microsoft/vstest/files/1467835/DC202.zip)
Basic idea is as follows: In data collector TestCaseStart event grab a global mutex and wait inside for 10 seconds. At the same time unit test will try to grab the same mutex. And in my tests it can't - because mutex already taken by datacollector.

![image](https://user-images.githubusercontent.com/621585/32740257-a63ba84e-c8a2-11e7-9739-3586964d0e56.png)
Here on screenshot:
18:38:41.897 - data collector takes mutex
18:38:42.959 - unit test tries to take the same mutex and fails
18:38:51.897 - data collector releases mutex

I would expect those events happened in this order:
[0s] data collector takes mutex
[+10s] data collector releases mutex
[+1s] unit test tries to take the same mutex and succeeds

**Comment by smadala** [comment]
@AM5800 Thanks for repro. Issue only repro for .NET Core test projects. Looks like issue fixed with latest `Microsoft.NET.Test.Sdk.15.5.0`. Feel free to reopen the issue if you still facing issue after upgrading `Microsoft.NET.Test.Sdk` to latest.
