### ISSUE TITLE
When a test passes but there is an error in the data collector trx reports the test as failed

### ISSUE THREAD

**Issue by ShreyasRmsft** [Microsoft/vstest#1283]
When a test passes but there is an error in the data collector trx reports the test as failed even though the test actually has passed.

**Comment by harshjain2** [comment]
@ShreyasRmsft Please share repro project/ repro steps.

**Comment by ShreyasRmsft** [comment]
Provided repro offline

**Comment by smadala** [comment]
@ShreyasRmsft Please re-open the issue if you can provide repro here.
