### ISSUE TITLE
The test source file "/UseVsixExtensions:true" provided was not found

### ISSUE THREAD

**Issue by raviteja50cent** [Microsoft/vstest#1290]
## Description
Hi guys, I am beginner starting with .netcore2.0, I see this error when running tests, 

### I am using below commands to build with .netcore2.0 
> dotnet build -o ./../bin --framework netcoreapp2.0
> dotnet publish -o ./../release --framework netcoreapp2.0 

### FYI, I have installed VS2017 Enterprise version and using MSBuild 15.4

I am using this as vstest.console.test path 
VSTestExec='C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\Common7\IDE\Extensions\TestPlatform\vstest.console.exe'

### I am using a powershell script to run tests and generate codecoverage on Sonar.

VERBOSE: codeCoverageExe = C:\Program Files (x86)\Microsoft Visual
--
11-Nov-2017 21:42:10 | Studio\2017\Enterprise\Team Tools\Dynamic Code Coverage Tools\CodeCoverage.exe
11-Nov-2017 21:42:10 | VERBOSE: Working Directory: D:\BambooBld\SERVICECORE-CSSVC-JOB1\bin
11-Nov-2017 21:42:10 | VERBOSE: Searching test assemblies: /**\*Tests*.dll ...
11-Nov-2017 21:42:10 | VERBOSE:
11-Nov-2017 21:42:13 | Found 1 test assembly(s)
11-Nov-2017 21:42:13 | VERBOSE: Test assembly(s)
11-Nov-2017 21:42:13 | -----------------------
11-Nov-2017 21:42:13 | D:\BambooBld\SERVICECORE-CSSVC-JOB1\CustomerSearchUnitTests\obj\Debug\netcoreapp2.0\CustomerSearchUnitTests.dll
11-Nov-2017 21:42:13 | VERBOSE: Processing file
11-Nov-2017 21:42:13 | D:\BambooBld\SERVICECORE-CSSVC-JOB1\CustomerSearchUnitTests\obj\Debug\netcoreap
11-Nov-2017 21:42:13 | p2.0\CustomerSearchUnitTests.dll
11-Nov-2017 21:42:13 | Microsoft (R) Test Execution Command Line Tool Version 15.3.0-preview-20170628-02
11-Nov-2017 21:42:13 | Copyright (c) Microsoft Corporation.  All rights reserved.
11-Nov-2017 21:42:13 |  
11-Nov-2017 21:42:13 | The test source file "/UseVsixExtensions:true" provided was not found.
11-Nov-2017 21:42:13 | The test source file "/UseVsixExtensions:true" provided was not found.
11-Nov-2017 21:42:13 | C:\temp\SERVICECORE-CSSVC-JOB1-233-PowerShellTask-2906343833956554482.ps1 :
11-Nov-2017 21:42:13 | Error caught in try-catch block
11-Nov-2017 21:42:13 | At line:1 char:106
11-Nov-2017 21:42:13 | + &{$ErrorActionPreference=1;.
11-Nov-2017 21:42:13 | 'C:\temp\SERVICECORE-CSSVC-JOB1-233-PowerShellTask- ...
11-Nov-2017 21:42:13 | + ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
11-Nov-2017 21:42:13 | ~~~
11-Nov-2017 21:42:13 | + CategoryInfo          : NotSpecified: (:) [Write-Error], WriteErrorExcep
11-Nov-2017 21:42:13 | tion
11-Nov-2017 21:42:13 | + FullyQualifiedErrorId : Microsoft.PowerShell.Commands.WriteErrorExceptio
11-Nov-2017 21:42:13 | n,SERVICECORE-CSSVC-JOB1-233-PowerShellTask-2906343833956554482.ps1

Please help me figure out why am I getting below error, 
"The test source file "/UseVsixExtensions:true" provided was not found"

**Comment by raviteja50cent** [comment]
FYI I have also included "/Framework:FrameworkCore10" in the powershell script.

**Comment by codito** [comment]
@raviteja50cent for running netcoreapp2.0 tests, VSIX extensions are not applicable. Can you try without `/UseVsixExtensions:true`?

The error message is showing up because `/UseVsixExtensions:true` is available in new test platforms shipping as part of `15.5.0+` versions of Visual Studio. These builds are in preview currently (*Download Visual Studio Preview* at https://www.visualstudio.com/downloads/).

**Comment by raviteja50cent** [comment]
@codito Thanks for finding that out. I will remove //code UseVsixExtentions:true and try building.

**Comment by raviteja50cent** [comment]
I am getting this issues when I removed `UseVsixExtentions:true`


Using shared compilation with compiler from directory: C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\MSBuild\15.0\Bin\Roslyn
--
12-Nov-2017 23:37:13 | SearchTypeProvider.cs(22,13): warning xUnit2017: Do not use Contains() to check if a value exists in a collection. [D:\BambooBld\SERVICECORE-CSSVC-JOB1\CustomerSearchUnitTests\CustomerSearchUnitTests.csproj]
12-Nov-2017 23:37:13 | SearchTypeProvider.cs(32,13): warning xUnit2017: Do not use Contains() to check if a value exists in a collection. [D:\BambooBld\SERVICECORE-CSSVC-JOB1\CustomerSearchUnitTests\CustomerSearchUnitTests.csproj]
12-Nov-2017 23:37:13 | SearchTypeProvider.cs(53,13): warning xUnit2017: Do not use Contains() to check if a value exists in a collection. [D:\BambooBld\SERVICECORE-CSSVC-JOB1\CustomerSearchUnitTests\CustomerSearchUnitTests.csproj]
12-Nov-2017 23:37:13 | SearchTypeProvider.cs(63,13): warning xUnit2017: Do not use Contains() to check if a value exists in a collection. [D:\BambooBld\SERVICECORE-CSSVC-JOB1\CustomerSearchUnitTests\CustomerSearchUnitTests.csproj]
12-Nov-2017 23:37:13 | SearchTypeProvider.cs(73,13): warning xUnit2017: Do not use Contains() to check if a value exists in a collection. [D:\BambooBld\SERVICECORE-CSSVC-JOB1\CustomerSearchUnitTests\CustomerSearchUnitTests.csproj]
12-Nov-2017 23:37:13 | SearchTypeProvider.cs(42,13): warning xUnit2013: Do not use Assert.Equal() to check for collection size. [D:\BambooBld\SERVICECORE-CSSVC-JOB1\CustomerSearchUnitTests\CustomerSearchUnitTests.csproj]
12-Nov-2017 23:37:13 | SearchTypeProvider.cs(85,13): warning xUnit2013: Do not use Assert.Equal() to check for collection size. [D:\BambooBld\SERVICECORE-CSSVC-JOB1\CustomerSearchUnitTests\CustomerSearchUnitTests.csproj]
12-Nov-2017 23:37:13 | SearchTypeProvider.cs(43,13): warning xUnit2017: Do not use Contains() to check if a value exists in a collection. [D:\BambooBld\SERVICECORE-CSSVC-JOB1\CustomerSearchUnitTests\CustomerSearchUnitTests.csproj]
12-Nov-2017 23:37:13 | SearchTypeProvider.cs(86,13): warning xUnit2017: Do not use Contains() to check if a value exists in a collection. [D:\BambooBld\SERVICECORE-CSSVC-JOB1\CustomerSearchUnitTests\CustomerSearchUnitTests.csproj]
12-Nov-2017 23:37:13 | SearchTypeProvider.cs(96,13): warning xUnit2017: Do not use Contains() to check if a value exists in a collection. [D:\BambooBld\SERVICECORE-CSSVC-JOB1\CustomerSearchUnitTests\CustomerSearchUnitTests.csproj]
12-Nov-2017 23:37:13 | SearchTypeProvider.cs(106,13): warning xUnit2017: Do not use Contains() to check if a value exists in a collection. [D:\BambooBld\SERVICECORE-CSSVC-JOB1\CustomerSearchUnitTests\CustomerSearchUnitTests.csproj]
12-Nov-2017 23:37:13 | SearchTypeProvider.cs(116,13): warning xUnit2017: Do not use Contains() to check if a value exists in a collection. [D:\BambooBld\SERVICECORE-CSSVC-JOB1\CustomerSearchUnitTests\CustomerSearchUnitTests.csproj]
12-Nov-2017 23:37:13 | SearchTypeProvider.cs(126,13): warning xUnit2017: Do not use Contains() to check if a value exists in a collection. [D:\BambooBld\SERVICECORE-CSSVC-JOB1\CustomerSearchUnitTests\CustomerSearchUnitTests.csproj]
12-Nov-2017 23:37:13 | _CopyFilesMarkedCopyLocal:
12-Nov-2017 23:37:13 | Copying file from "D:\BambooBld\SERVICECORE-CSSVC-JOB1\CustomerSearchMicroService\bin\Debug\netcoreapp2.0\CustomerSearchMicroService.dll" to "bin\Debug\netcoreapp2.0\CustomerSearchMicroService.dll".
12-Nov-2017 23:37:13 | Copying file from "D:\BambooBld\SERVICECORE-CSSVC-JOB1\CustomerSearchMicroService\bin\Debug\netcoreapp2.0\CustomerSearchMicroService.pdb" to "bin\Debug\netcoreapp2.0\CustomerSearchMicroService.pdb".
12-Nov-2017 23:37:13 | Touching "D:\BambooBld\SERVICECORE-CSSVC-JOB1\CustomerSearchUnitTests\obj\Debug\netcoreapp2.0\CustomerSearchUnitTests.csproj.CopyComplete".
12-Nov-2017 23:37:13 | _CopyOutOfDateSourceItemsToOutputDirectory:
12-Nov-2017 23:37:13 | Copying file from "C:\Users\svc_bambooagent\.nuget\packages\xunit.runner.visualstudio\2.3.0\build\netcoreapp1.0\xunit.runner.visualstudio.dotnetcore.testadapter.dll" to "bin\Debug\netcoreapp2.0\xunit.runner.visualstudio.dotnetcore.testadapter.dll".
12-Nov-2017 23:37:13 | Copying file from "C:\Users\svc_bambooagent\.nuget\packages\xunit.runner.visualstudio\2.3.0\build\netcoreapp1.0\xunit.runner.reporters.netcoreapp10.dll" to "bin\Debug\netcoreapp2.0\xunit.runner.reporters.netcoreapp10.dll".
12-Nov-2017 23:37:13 | Copying file from "C:\Users\svc_bambooagent\.nuget\packages\xunit.runner.visualstudio\2.3.0\build\netcoreapp1.0\xunit.runner.utility.netcoreapp10.dll" to "bin\Debug\netcoreapp2.0\xunit.runner.utility.netcoreapp10.dll".
12-Nov-2017 23:37:13 | CopyFilesToOutputDirectory:
12-Nov-2017 23:37:13 | Copying file from "obj\Debug\netcoreapp2.0\CustomerSearchUnitTests.dll" to "bin\Debug\netcoreapp2.0\CustomerSearchUnitTests.dll".
12-Nov-2017 23:37:13 | CustomerSearchUnitTests -> D:\BambooBld\SERVICECORE-CSSVC-JOB1\CustomerSearchUnitTests\bin\Debug\netcoreapp2.0\CustomerSearchUnitTests.dll
12-Nov-2017 23:37:13 | Copying file from "obj\Debug\netcoreapp2.0\CustomerSearchUnitTests.pdb" to "bin\Debug\netcoreapp2.0\CustomerSearchUnitTests.pdb".
12-Nov-2017 23:37:13 | CleanupEmptyRefsFolder:
12-Nov-2017 23:37:13 | Directory "D:\BambooBld\SERVICECORE-CSSVC-JOB1\CustomerSearchUnitTests\bin\Debug\netcoreapp2.0\refs" doesn't exist. Skipping.
12-Nov-2017 23:37:13 | Done Building Project "D:\BambooBld\SERVICECORE-CSSVC-JOB1\CustomerSearchUnitTests\CustomerSearchUnitTests.csproj" (Rebuild target(s)).
12-Nov-2017 23:37:13 | Done Building Project "D:\BambooBld\SERVICECORE-CSSVC-JOB1\CustomerSearchMicroService.sln" (Rebuild target(s)).
12-Nov-2017 23:37:13 |  
12-Nov-2017 23:37:13 | Build succeeded.
12-Nov-2017 23:37:13 |  
12-Nov-2017 23:37:13 | "D:\BambooBld\SERVICECORE-CSSVC-JOB1\CustomerSearchMicroService.sln" (Rebuild target) (1) ->
12-Nov-2017 23:37:13 | "D:\BambooBld\SERVICECORE-CSSVC-JOB1\CustomerSearchMicroService\CustomerSearchMicroService.csproj" (Rebuild target) (2) ->
12-Nov-2017 23:37:13 | (CoreCompile target) ->
12-Nov-2017 23:37:13 | Providers\SearchTypeProvider.cs(12,45): warning CS1998: This async method lacks 'await' operators and will run synchronously. Consider using the 'await' operator to await non-blocking API calls, or 'await Task.Run(...)' to do CPU-bound work on a background thread. [D:\BambooBld\SERVICECORE-CSSVC-JOB1\CustomerSearchMicroService\CustomerSearchMicroService.csproj]
12-Nov-2017 23:37:13 | Providers\SearchTypeProvider.cs(43,45): warning CS1998: This async method lacks 'await' operators and will run synchronously. Consider using the 'await' operator to await non-blocking API calls, or 'await Task.Run(...)' to do CPU-bound work on a background thread. [D:\BambooBld\SERVICECORE-CSSVC-JOB1\CustomerSearchMicroService\CustomerSearchMicroService.csproj]
12-Nov-2017 23:37:13 | Controllers\HealthController.cs(31,30): warning CS0168: The variable 'ex' is declared but never used [D:\BambooBld\SERVICECORE-CSSVC-JOB1\CustomerSearchMicroService\CustomerSearchMicroService.csproj]
12-Nov-2017 23:37:13 | Providers\SearchTypeProvider.cs(78,37): warning CS1998: This async method lacks 'await' operators and will run synchronously. Consider using the 'await' operator to await non-blocking API calls, or 'await Task.Run(...)' to do CPU-bound work on a background thread. [D:\BambooBld\SERVICECORE-CSSVC-JOB1\CustomerSearchMicroService\CustomerSearchMicroService.csproj]
12-Nov-2017 23:37:13 |  
12-Nov-2017 23:37:13 |  
12-Nov-2017 23:37:13 | "D:\BambooBld\SERVICECORE-CSSVC-JOB1\CustomerSearchMicroService.sln" (Rebuild target) (1) ->
12-Nov-2017 23:37:13 | "D:\BambooBld\SERVICECORE-CSSVC-JOB1\CustomerSearchUnitTests\CustomerSearchUnitTests.csproj" (Rebuild target) (3) ->
12-Nov-2017 23:37:13 | SearchTypeProvider.cs(22,13): warning xUnit2017: Do not use Contains() to check if a value exists in a collection. [D:\BambooBld\SERVICECORE-CSSVC-JOB1\CustomerSearchUnitTests\CustomerSearchUnitTests.csproj]
12-Nov-2017 23:37:13 | SearchTypeProvider.cs(32,13): warning xUnit2017: Do not use Contains() to check if a value exists in a collection. [D:\BambooBld\SERVICECORE-CSSVC-JOB1\CustomerSearchUnitTests\CustomerSearchUnitTests.csproj]
12-Nov-2017 23:37:13 | SearchTypeProvider.cs(53,13): warning xUnit2017: Do not use Contains() to check if a value exists in a collection. [D:\BambooBld\SERVICECORE-CSSVC-JOB1\CustomerSearchUnitTests\CustomerSearchUnitTests.csproj]
12-Nov-2017 23:37:13 | SearchTypeProvider.cs(63,13): warning xUnit2017: Do not use Contains() to check if a value exists in a collection. [D:\BambooBld\SERVICECORE-CSSVC-JOB1\CustomerSearchUnitTests\CustomerSearchUnitTests.csproj]
12-Nov-2017 23:37:13 | SearchTypeProvider.cs(73,13): warning xUnit2017: Do not use Contains() to check if a value exists in a collection. [D:\BambooBld\SERVICECORE-CSSVC-JOB1\CustomerSearchUnitTests\CustomerSearchUnitTests.csproj]
12-Nov-2017 23:37:13 | SearchTypeProvider.cs(42,13): warning xUnit2013: Do not use Assert.Equal() to check for collection size. [D:\BambooBld\SERVICECORE-CSSVC-JOB1\CustomerSearchUnitTests\CustomerSearchUnitTests.csproj]
12-Nov-2017 23:37:13 | SearchTypeProvider.cs(85,13): warning xUnit2013: Do not use Assert.Equal() to check for collection size. [D:\BambooBld\SERVICECORE-CSSVC-JOB1\CustomerSearchUnitTests\CustomerSearchUnitTests.csproj]
12-Nov-2017 23:37:13 | SearchTypeProvider.cs(43,13): warning xUnit2017: Do not use Contains() to check if a value exists in a collection. [D:\BambooBld\SERVICECORE-CSSVC-JOB1\CustomerSearchUnitTests\CustomerSearchUnitTests.csproj]
12-Nov-2017 23:37:13 | SearchTypeProvider.cs(86,13): warning xUnit2017: Do not use Contains() to check if a value exists in a collection. [D:\BambooBld\SERVICECORE-CSSVC-JOB1\CustomerSearchUnitTests\CustomerSearchUnitTests.csproj]
12-Nov-2017 23:37:13 | SearchTypeProvider.cs(96,13): warning xUnit2017: Do not use Contains() to check if a value exists in a collection. [D:\BambooBld\SERVICECORE-CSSVC-JOB1\CustomerSearchUnitTests\CustomerSearchUnitTests.csproj]
12-Nov-2017 23:37:13 | SearchTypeProvider.cs(106,13): warning xUnit2017: Do not use Contains() to check if a value exists in a collection. [D:\BambooBld\SERVICECORE-CSSVC-JOB1\CustomerSearchUnitTests\CustomerSearchUnitTests.csproj]
12-Nov-2017 23:37:13 | SearchTypeProvider.cs(116,13): warning xUnit2017: Do not use Contains() to check if a value exists in a collection. [D:\BambooBld\SERVICECORE-CSSVC-JOB1\CustomerSearchUnitTests\CustomerSearchUnitTests.csproj]
12-Nov-2017 23:37:13 | SearchTypeProvider.cs(126,13): warning xUnit2017: Do not use Contains() to check if a value exists in a collection. [D:\BambooBld\SERVICECORE-CSSVC-JOB1\CustomerSearchUnitTests\CustomerSearchUnitTests.csproj]
12-Nov-2017 23:37:13 |  
12-Nov-2017 23:37:13 | 17 Warning(s)
12-Nov-2017 23:37:13 | 0 Error(s)
12-Nov-2017 23:37:13 |  
12-Nov-2017 23:37:13 | Time Elapsed 00:00:08.46
12-Nov-2017 23:37:13 | SonarQube Scanner for MSBuild 3.0.2
12-Nov-2017 23:37:13 | Default properties file was found at C:\Sonar\sonar-scanner-msbuild-3.0.2.656\SonarQube.Analysis.xml
12-Nov-2017 23:37:13 | Loading analysis properties from C:\Sonar\sonar-scanner-msbuild-3.0.2.656\SonarQube.Analysis.xml
12-Nov-2017 23:37:13 | Post-processing started.
12-Nov-2017 23:37:13 | 07:37:13.554  Temporary analysis directory (usually .sonarqube) doesn't exist. The "begin" step was probably not executed.
12-Nov-2017 23:37:13 | 07:37:13.554  Post-processing failed. Exit code: 1

**Comment by raviteja50cent** [comment]
Also what does this mean and do `/Framework:FrameworkCore10`? 
Can't I have something like this for running .netcoreapp2.0 `/Framework:FrameworkCore20`??

**Comment by codito** [comment]
@raviteja50cent the error logs you shared are from `build` step. Is it stopping because of warnings?

Can you confirm that `vstest.console.exe` has run?

`/Framework:FrameworkCore10` works for any netcore target. There isn't a FrameworkCore20 switch.

**Comment by raviteja50cent** [comment]
Hi @codito 
Nope warning doesn't stop build. Yes it is using vstest.console.exe.

**Comment by raviteja50cent** [comment]
And yes `Framework:FrameworkCore10` worked 👍

**Comment by singhsarab** [comment]
@raviteja50cent Seems things are working for you now, May I go ahead and close this one ?
