### ISSUE TITLE
VSTest v. 15.0.26929.2 could not work with MSTest V2 unittests

### ISSUE THREAD

**Issue by petrciml** [Microsoft/vstest#1303]
## Description
> Unittest project using MSTest.TestAdapter and MSTest.TestFramework (both v. 1.1.18) (MSTest V2) couldn't be run via VSTest v. 15.0.26929.2
> This version of VSTest is distributed via "Agents for Visual Studio 2017" (v. 15.4.3)

## Steps to reproduce
> Create a new unittest project in VS2017 with one simple unittest aka Assert.IsTrue(true);
> Run command:
`C:\Program Files (x86)\Microsoft Visual Studio\2017\TestAgent\Common7\IDE\CommonExtensions\Microsoft\TestWindow>vstest.console.exe u:\VSTestCheck\Debug\VSTestCheck.dll /testadapterpath:"u:\VSTestCheck\Debug" /listtests`

## Expected behavior
> All tests in assembly listed in console

## Actual behavior
> No test listed

## Environment
> Windows Server 2012 R2 Standard
> Agents for Visual Studio 2017 (v. 15.4.3)
> VSTest.Console v. 15.0.26929.2

**Comment by petrciml** [comment]
Diagnostics log from VSTest:

[diag.txt](https://github.com/Microsoft/vstest/files/1484803/diag.txt)

**Comment by petrciml** [comment]
![image](https://user-images.githubusercontent.com/16851927/33014299-2c31f73e-cde7-11e7-8f3c-2f3b087d9f42.png)

Trying to use adapter from MSTest.TestAdapter NuGet package content.

**Comment by petrciml** [comment]
We have different version of Agents for Visual Studio 2017 - I have 15.4.3, you 15.4.4.
Version of VSTest.Console 15.0.26929.2 is same, but some dependencies could be in different version.
Please, do you have a chance to test it on v. 15.4.3.? I'm in corporate environment and upgrade of software is very difficult and long term "mission". :(

**Comment by jayaranigarg** [comment]
I don't think it is an issue with different version of Agents for Visual Studio.

@petrciml : Can you also drop "Microsoft.VisualStudio.TestPlatform.TestFramework.Extensions.dll" in your testadapter path and try?

**Comment by petrciml** [comment]
![image](https://user-images.githubusercontent.com/16851927/33022014-fd7c89c8-ce03-11e7-941f-f5a95193d46a.png)

Unfortunately did not help too :(

**Comment by jayaranigarg** [comment]
Can you enable vstest.executionengine*.exe.config logging. [Here ](https://blogs.msdn.microsoft.com/aseemb/2012/03/01/how-to-enable-ute-logs/)is how you can enable that. And share the logs with us.

Can you use below command to run the tests to make sure vstest.executionengine*.exe is indeed launched :
"C:\Program Files (x86)\Microsoft Visual Studio\2017\TestAgent\Common7\IDE\CommonExtensions\Microsoft\TestWindow\vstest.console.exe" <Testdll> /testadapterpath:<pathToAdapter> /inisolation

**Comment by petrciml** [comment]
Great, problem solved. Many thanks!

In _vstest.console.TpTrace.log_ I'm found following error:

> System.NotSupportedException: An attempt was made to load an assembly from a network location which would have caused the assembly to be sandboxed in previous versions of the .NET Framework. This release of the .NET Framework does not enable CAS policy by default, so this load may be dangerous. If this load is not intended to sandbox the assembly, please enable the loadFromRemoteSources switch. See http://go.microsoft.com/fwlink/?LinkId=155569 for more information.

After moving folder from _U:\VSTestCheck_ into _C:\VSTestCheck_ problem is solved
