### ISSUE TITLE
Misleading spacing in case of output messages

### ISSUE THREAD

**Issue by jayaranigarg** [Microsoft/vstest#1309]
## Steps to reproduce
1. Create a C# UT Project.
2. Add 2 unit tests like
        [TestMethod]
        public void TestMethod33()
        {
            Console.Write("HelloAgain");
            Assert.Inconclusive();
        }

        [TestMethod]
        public void TestMethod34()
        {
            Assert.AreEqual(1, 2);
        }

3. Compile and run tests using CLI.

## Expected behavior
There ought to be no blank line "before" the standard output messages; there ought to be a blank line after.

here is the output I would expect:

Microsoft (R) Test Execution Command Line Tool Version 15.5.0
Copyright (c) Microsoft Corporation.  All rights reserved.
 
Starting test execution, please wait...
Skipped  TestMethod33
Error Message:
 Assert.Inconclusive failed.
Stack Trace:
   at UnitTestProject30.UnitTest1.TestMethod33() in C:\Users\pratapl\Source\Repos\UnitTestProject30\UnitTestProject30\UnitTest1.cs:line 13
Standard Output Messages:
 HelloAgain
 
Failed   TestMethod34
Error Message:
 Assert.AreEqual failed. Expected:<1>. Actual:<2>.
Stack Trace:
   at UnitTestProject30.UnitTest1.TestMethod34() in C:\Users\pratapl\Source\Repos\UnitTestProject30\UnitTestProject30\UnitTest1.cs:line 19
 
Total tests: 2. Passed: 0. Failed: 1. Skipped: 1.
Test Run Failed.
Test execution time: 0.5314 Seconds

## Actual behavior
> What is the behavior observed?
![image](https://user-images.githubusercontent.com/17309452/33369926-0b122100-d51c-11e7-9f7c-de685d21c15e.png)

It appears as if Output messages are with TestMethod34 but they are actually with TestMethod33.

## Environment
MSTest 1.2.0
vstest.console 15.5.0
Win10

**Comment by pvlakshm** [comment]
It is indeed a little misleading.

There ought to be no blank line "before" the Standard Output Messages; there ought to be a blank line after.

Here is the output I would expect:
```
Microsoft (R) Test Execution Command Line Tool Version 15.5.0
Copyright (c) Microsoft Corporation.  All rights reserved.
 
Starting test execution, please wait...
Skipped  TestMethod33
Error Message:
 Assert.Inconclusive failed.
Stack Trace:
   at UnitTestProject30.UnitTest1.TestMethod33() in C:\Users\pratapl\Source\Repos\UnitTestProject30\UnitTestProject30\UnitTest1.cs:line 13
Standard Output Messages:
 HelloAgain
 
Failed   TestMethod34
Error Message:
 Assert.AreEqual failed. Expected:<1>. Actual:<2>.
Stack Trace:
   at UnitTestProject30.UnitTest1.TestMethod34() in C:\Users\pratapl\Source\Repos\UnitTestProject30\UnitTestProject30\UnitTest1.cs:line 19
 
Total tests: 2. Passed: 0. Failed: 1. Skipped: 1.
Test Run Failed.
Test execution time: 0.5314 Seconds
```

**Comment by acesiddhu** [comment]
fixed
