### ISSUE TITLE
Referenced projects not creating correct json files.

### ISSUE THREAD

**Issue by owenniblock** [Microsoft/vstest#1311]
## Description
I have several projects which all reference Microsoft.NET.Test.Sdk - these projects are then referenced by a parent project.

When I try to run the tests using `dotnet vstest MyAssembly.dll` I get errors like this:

```
No test is available in *****Tests.dll. Make sure test project has a nuget reference of package "Microsoft.NET.Test.Sdk" and framework version settings are appropriate and try again.
```

I have verified that if I copy the `MyAssembly.runtimeconfig.dev.json` and `MyAssembly.deps.json` in to the build directory - the tests run correctly.

## Steps to reproduce
1. Create 2 .Net Core test projects (MyTests and MyParent) - create a test class in MyTests and reference MyTests with MyParent. Reference 
2. Build and browse to the MyParent build directory.
3. Run `dotnet vstest MyTests.dll`

## Expected behavior
Tests should run correctly.

## Actual behavior
Receive the `Make sure test project has a nuget reference of package "Microsoft.NET.Test.Sdk"` error.

## Environment
```
.NET Command Line Tools (2.0.2)

Product Information:
 Version:            2.0.2
 Commit SHA-1 hash:  a04b4bf512

Runtime Environment:
 OS Name:     Mac OS X
 OS Version:  10.12
 OS Platform: Darwin
 RID:         osx.10.12-x64
 Base Path:   /usr/local/share/dotnet/sdk/2.0.2/

Microsoft .NET Core Shared Framework Host

  Version  : 2.0.0
  Build    : e8b8861ac7faf042c87a5c2f9f2d04c98b69f28d
```

**Comment by singhsarab** [comment]
@owenniblock 
TestPlatform needs the deps.json and runtimeconfig.dev.json files in order to find out the dependencies (it needs to find out the path to testhost.dll)
So this behavior is by design. You'd need to keep the deps.json and runtimeconfig.dev.json next to the test dll.
The error message needs to be refined, I am going to fix that.
