### ISSUE TITLE
Need better user experience for collecting diagnostic logs of vstest.console from VS

### ISSUE THREAD

**Issue by smadala** [microsoft/vstest#1315]
## Description
See https://github.com/Microsoft/vstest/issues/623#issuecomment-348532950

For Test explorer changes logged a bug https://devdiv.visualstudio.com/DevDiv/VS.in%20Agile%20Testing%20IDE/_queries/edit/531191/?triage=true

**Comment by Evangelink** [comment]
There is a GUI option available now. You can also refer to this document for fully pledge steps: https://github.com/microsoft/vstest-docs/blob/main/docs/troubleshooting.md
