### ISSUE TITLE
User should able to troubleshoot the testplatform/adapter failures from logs

### ISSUE THREAD

**Issue by smadala** [microsoft/vstest#1316]
## Description
See https://github.com/Microsoft/vstest/issues/623#issuecomment-348532950 

- User should able to troubleshoot the testplatform/adapter failures from logs obtained by `--diag`  argument.

- Create document to understand critical steps from  logs like Is testhost/datacollector launched? Right runsetttings used? Required adapter/extensions loaded? Is communication between process established? etc.. And should figure out that issue related to Clients(VS IDE/VSTest task/dotnet test...), Test platform(vstest), Adapters(MSTestv2/xUnit/Nunit..) or Tests itself.

**Comment by soeron** [comment]
Even better in test output tab in the IDE.

**Comment by smadala** [comment]
@soeron Logs can gets very huge based on number of tests(can cause VS hang) and generated in two or more processes( can impact performance).

**Comment by soeron** [comment]
That's why you can choose what information you want to see there. Obviously if you are looking at the logs most of the time you are trying to figure out where is the problem if there is any, but that's my opinion.

**Comment by Evangelink** [comment]
This troubleshooting document is a good starting point: https://github.com/microsoft/vstest-docs/blob/main/docs/troubleshooting.md
