### ISSUE TITLE
TestAdapterPath should work together with other lookup methods

### ISSUE THREAD

**Issue by smadala** [Microsoft/vstest#1319]
_From @NikolayPianikov on November 17, 2017 15:8_

I mean project output directory, nuget and etc.

- We could have the identical behavior for full and core .net, I mean when I specify `TestAdapterPath` for .net full it does not try to find adapters in the project output directory but for .net core it properly finds.

So I should copy my custom adapter to the root of solution directory to run tests for mixed solution (with full .net and core .net projects). And vstest could spend potentially significant time finding all required adapters when agent checkout directory has a lot of files/directories. It is very important for CI.

- It would be great if we could specify several paths separated by semicolon or add new parameter `TestAdapterPaths` for that to work together with other lookup methods.

_Copied from original issue: Microsoft/vstest-docs#103_

**Comment by smadala** [comment]
@NikolayPianikov
>It would be great if we could specify several paths separated by semicolon or add new parameter TestAdapterPaths for that to work together with other lookup methods.

You can use `/TestAdapterPath` argument multiple times [code](https://github.com/Microsoft/vstest/blob/master/src/vstest.console/Processors/TestAdapterPathArgumentProcessor.cs#L85).

**Comment by smadala** [comment]
_From @NikolayPianikov on November 18, 2017 14:23_

@smadala yes, but I used it under `dotnet test` or `msbuild /t:vstest`. Error is `specified in the 'TestAdapterPath' is invalid. Error: The given path's format is not supported.` 
Exception is [here](https://github.com/Microsoft/vstest/blob/f717a0da656e06474e2e6d598055b5ccc535a5df/src/vstest.console/Processors/TestAdapterPathArgumentProcessor.cs#L168)

**Comment by smadala** [comment]
_From @dtretyakov on December 5, 2017 12:40_

@smadala, in `VSTestTask`, which is shipped with .net core sdk, allowed only one argument for `VSTestTestAdapterPath` and it's is bypassed into vstest console as a [single argument](https://github.com/Microsoft/vstest/blob/123adc3ebfdc05be24ee6f44ace1e9eef79e372f/src/Microsoft.TestPlatform.Build/Tasks/VSTestTask.cs#L144):

And it's blocking use case in our integration, see https://github.com/JetBrains/teamcity-dotnet-plugin/issues/101

When do you plan to fix it?

**Comment by smadala** [comment]
@NikolayPianikov @dtretyakov Feel free to raise PR. 
/cc @pvlakshm for triage.

**Comment by dtretyakov** [comment]
@smadala, it was also mentioned in https://github.com/Microsoft/vstest/issues/141#issuecomment-277763615 by @AbhitejJohn that:
> the commandline testadapterpath argument does not take in multiple paths which is another gap.

**Comment by dtretyakov** [comment]
@smadala, please take a look at the following PR: https://github.com/Microsoft/vstest/pull/1320

**Comment by smadala** [comment]
- This issue need to address handling multiple values from VSTestTask. 
- Should have same adapter picking up logic for both .NET Core & .NET Full?
/cc thoughts @singhsarab @pvlakshm @mayankbansal018
