### ISSUE TITLE
Microsoft.VisualStudio.CodeCoverage is not copied to output for .NET Core

### ISSUE THREAD

**Issue by twsouthwick** [Microsoft/vstest#1327]
## Description

I have a project where I want to enable Code Coverage. I added the `Microsoft.VisualStudio.CodeCoverage` and see the shim available on .NET Framework builds but not on .NET Core builds.

## Steps to reproduce
Setup a project with the following:

```xml
<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFrameworks>net45;netcoreapp2.0</TargetFrameworks>
    <IsPackable>false</IsPackable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.NET.Test.Sdk" Version="15.5.0" />
    <PackageReference Include="xunit" Version="2.3.1" />
    <PackageReference Include="xunit.runner.visualstudio" Version="2.3.1" />
    <PackageReference Include="Microsoft.CodeCoverage" Version="1.0.3" />
    <DotNetCliToolReference Include="dotnet-xunit" Version="2.3.1" />
  </ItemGroup>

</Project>
```

and a simple test so we can compile (name it `test.cs` in the same directory):

```csharp
using System;
using Xunit;

namespace test
{
    public class UnitTest1
    {
        [Fact]
        public void Test1()
        {
        }
    }
}
```

Now run `dotnet build` (or `msbuild /t:restore;build`).

This breaks the ability to run code coverage with vstest as it can't find the collector.

## Expected behavior
`Microsoft.VisualStudio.CodeCoverage.Shim` should be available in the `.netcoreapp2.0` directory

## Actual behavior

`Microsoft.VisualStudio.CodeCoverage.Shim` is **not** available in the `.netcoreapp2.0` directory. The directory listing is shown below:

```
├───net45
│       Microsoft.VisualStudio.CodeCoverage.Shim.dll
│       System.Runtime.InteropServices.RuntimeInformation.dll
│       test.dll
│       test.pdb
│       xunit.abstractions.dll
│       xunit.assert.dll
│       xunit.core.dll
│       xunit.execution.dotnet.dll
│       xunit.runner.reporters.net452.dll
│       xunit.runner.utility.net452.dll
│       xunit.runner.visualstudio.testadapter.dll
│
└───netcoreapp2.0
        test.deps.json
        test.dll
        test.pdb
        test.runtimeconfig.dev.json
        test.runtimeconfig.json
        xunit.runner.reporters.netcoreapp10.dll
        xunit.runner.utility.netcoreapp10.dll
        xunit.runner.visualstudio.dotnetcore.testadapter.dll
```

## Environment
Visual Studio 2017 Update 5
Windows FCU

**Comment by smadala** [comment]
@twsouthwick It seems behavior difference in `dotnet build`. You can use `dotnet publish` to unblock yourself. No need to add  `Microsoft.CodeCoverage`  packages explicitly, It gets ships with `Microsoft.NET.Test.Sdk`.

@livarcocc @eerhardt Any idea why this is happening?

**Comment by eerhardt** [comment]
> Any idea why this is happening?

NuGet dependencies are not copied to the output folder on `dotnet build`.  They are loaded from the NuGet cache during `dotnet run`.

See https://docs.microsoft.com/en-us/dotnet/core/tools/dotnet-build?tabs=netcore2x

> If the project has third-party dependencies, such as libraries from NuGet, they're resolved from the NuGet cache and aren't available with the project's built output. With that in mind, the product of dotnet build isn't ready to be transferred to another machine to run. This is in contrast to the behavior of the .NET Framework in which building an executable project (an application) produces output that's runnable on any machine where the .NET Framework is installed. To have a similar experience with .NET Core, you need to use the dotnet publish command. For more information, see .NET Core Application Deployment.

**Comment by twsouthwick** [comment]
@smadala if this is not needed, then the docs should be updated as they say you need to include them.

**Comment by twsouthwick** [comment]
@smadala Since the package is no longer necessary, I've created a PR to update the docs. Is this only true on 15.5, or is it true for 15.3?
