### ISSUE TITLE
NUnit Test Adapter does not find nunit.framework if In-Proc Data Collection is used

### ISSUE THREAD

**Issue by pkruk2** [Microsoft/vstest#1331]
Hello, 

I want to interact with process which executes unit tests, for example change environment variables on test case start/end. As I understand the only official(?) API for this is the use of "In-Proc Data Collection" (3rd party data collector in test execution host).

**Problem summary:**
When using in-proc data collector, I am getting exception while running NUnit UT.
Everything works correctly when running xUnit UT.
Also, with out of process data collector, both NUnit and xUnit work correctly.

**Details:**
I have used example from https://github.com/Microsoft/vstest/issues/715 to write a simple InProcDataCollection implementation which logs to a text file. I can confirm that it is used (log is created) for both NUnit and xUnit runs.

But for NUnit run, an exception is thrown in the driver while loading tests, and NUnit Adapter does not find any tests in the test assembly. The exception says it could not find nunit.framework assembly.

I'm not sure if this is a problem in vstest, nunit, or in the way I'm using the api...

I am attaching:
[nunit.output.txt](https://github.com/Microsoft/vstest/files/1542944/nunit.output.txt)
[xunit.output.txt](https://github.com/Microsoft/vstest/files/1542945/xunit.output.txt)
[InProcTestDataCollector.zip](https://github.com/Microsoft/vstest/files/1542955/InProcTestDataCollector.zip)

I have tested this with:
* vstest built locally (5aaae53291e1333f4260ca9ef30d5ad5baadf533) but also vstest from VS 2017 (15.3.0-preview-20170628-02) 
* NUnit3TestAdapter.3.9.0
* xunit.runner.visualstudio.2.3.1

**Comment by ShreyasRmsft** [comment]
Hi @pkruk2, can you tell me the command line you are using to run your tests? Also can you provide the runsettings file you are using? And maybe a sample Nunit Project (as simple a one as possible) where this issue repros so that i can debug through it.

**Comment by pkruk2** [comment]
Hi @ShreyasRmsft, I also created an issue against nunit3-vs-adapter - could you please see https://github.com/nunit/nunit3-vs-adapter/issues/426#issuecomment-354306273 for detailed repro?

Sorry for creating two issues for the same problem, but I was not sure (and still am not) if this is problem with vstest or nunit test adapter.

**Comment by ShreyasRmsft** [comment]
Hi @pkruk2, Is your data collector by any chance trying to access something from the Nunit framework?

**Comment by ShreyasRmsft** [comment]
Hi @pkruk2, looks like it mostly is an Nunit issue. Since the only piece of code that is referring to the framework dll is the test code whose dependencies we in the platform never try to resolve explicitly.

**Comment by pkruk2** [comment]
@ShreyasRmsft I see. I thought this may be vstest related issue because I think when you use in-proc data collector, vstest starts separate process (e.g. testhost.x86.exe) and executes tests adapter there. Without it, tests are executed in main process. So I think it could affect assembly resolution process. I may be wrong though.

**Comment by ShreyasRmsft** [comment]
@pkruk2 I'll investigate and get back to you now that I have the source files. That was just a hunch.

**Comment by ShreyasRmsft** [comment]
Hi @pkruk2, am looking into this issue. Will get back to you in a few days.

**Comment by pkruk2** [comment]
OK Thank you

**Comment by ShreyasRmsft** [comment]
Hi @pkruk2, So I had a look and it is not an issue on vstest side. The Nunit adapter itself was responsible for looking for the dll and finding when no inproc data collector was there, and when an inproc data collector is present they do not look for it in the bin directory.

**Comment by ShreyasRmsft** [comment]
The adapter is responsible for loading all of its dependencies and this failure is occurring inside the app domain created by the Nunit adapter and not in the appdomain created by us.

**Comment by ShreyasRmsft** [comment]
There is a flag that you can pass /InIsolation where you can force vstest.console.exe to create the testhost.x86.exe process and the tests pass when there is no inproc data collector even when run under testhost.x86.exe.

**Comment by ShreyasRmsft** [comment]
@pkruk2, I am closing this issue here.

**Comment by ShreyasRmsft** [comment]
@pkruk2, Also MsTest does not discover the test unless the framework dll is present along with the adapter dlls. This extra logic of looking for the framework dlls along with the test binaries is something that Nunit does (that is not done by Mstest and I can probably go ahead and say Xunit also). But the general expectation is to have your framework dlls along with the adapter dll.

**Comment by pkruk2** [comment]
@ShreyasRmsft thanks for looking into this. Do you think NUnit should start shipping test adapter together with nunit.framework.dll?

I have checked other frameworks and for example xUnit seems to work without xunit.core.dll. And NUnit works correctly with InIsoltion setting:


Adapter | Normal | InIsolation | InProc DC | Comment
-- | -- | -- | -- | --
Nunit V3 | OK | OK | Exception | No   nunit.framework.dll, only nunit.engine.dll
xUnit | OK | OK | OK | No xunit.core.dll,   only xunit.abstractions.dll
MSTest V2 | OK | OK | OK | Has   Microsoft.VisualStudio.TestPlatform.TestFramework.dll

**Comment by ShreyasRmsft** [comment]
@pkruk2, that's totally up to them, but I guess what confuses users is that they look in bin (test dll directory) for the framework dll when no inproc data collector is there and fail to do so when you provide one. This lack of uniformity is probably what needs resolving.

**Comment by pkruk2** [comment]
@ShreyasRmsft thanks, I will let them know.

**Comment by thomashoef** [comment]
@pkruk2 Did you find a solution for this issue? Whenever I run tests locally, they work, but on Team Foundation Server, they fail saying nunit.framework could not be found (FileNotFoundException)

2018-05-04T11:20:56.4737305Z Die Vstest-Diagnose wird in der Datei E:\agent\_work\_temp\357c6d10-4f8d-11e8-b1c2-eb05188701ef.txt protokolliert.
2018-05-04T11:20:56.8487239Z NUnit Adapter 3.10.0.21: Test execution started
2018-05-04T11:20:56.8643421Z Running all tests in E:\agent\_work\14\s\d\App.Tests\obj\Debug\App.Tests.dll
2018-05-04T11:20:57.2706299Z Exception NUnit.Engine.NUnitEngineException, Exception thrown executing tests in E:\agent\_work\14\s\d\App.Tests\obj\Debug\App.Tests.dll
2018-05-04T11:20:57.2706299Z An exception occurred in the driver while loading tests.
2018-05-04T11:20:57.2862129Z    bei NUnit.Engine.Runners.DirectTestRunner.LoadDriver(IFrameworkDriver driver, String testFile, TestPackage subPackage)
2018-05-04T11:20:57.2862129Z    bei NUnit.Engine.Runners.DirectTestRunner.LoadPackage()
2018-05-04T11:20:57.2862129Z    bei NUnit.Engine.Runners.TestDomainRunner.LoadPackage()
2018-05-04T11:20:57.2862129Z    bei NUnit.Engine.Runners.DirectTestRunner.EnsurePackageIsLoaded()
2018-05-04T11:20:57.2862129Z    bei NUnit.Engine.Runners.DirectTestRunner.Explore(TestFilter filter)
2018-05-04T11:20:57.2862129Z    bei NUnit.Engine.Runners.MasterTestRunner.Explore(TestFilter filter)
2018-05-04T11:20:57.2862129Z    bei NUnit.VisualStudio.TestAdapter.NUnit3TestExecutor.RunAssembly(String assemblyPath, TestFilter filter)
2018-05-04T11:20:57.2862129Z Innerexception: System.IO.FileNotFoundException: Die Datei oder Assembly "nunit.framework" oder eine Abhängigkeit davon wurde nicht gefunden. Das System kann die angegebene Datei nicht finden.
2018-05-04T11:20:57.2862129Z Dateiname: "nunit.framework"

**Comment by pkruk2** [comment]
@thomashoef hmm I think for nunit v2 and xunit I'm simply using latest test adapter as is. For nunit v3 I'm making sure test adapter is next to nunit.framework.dll by making copying both to a temporary directory (more or less)

**Comment by thomashoef** [comment]
Hi @pkruk2 , that is funny - I set a test adapter folder to $(Build.SourcesDirectory)\Testing\NUnit3TestAdapter.3.10.0\build\net35 and made sure to copy the nunit.framework.dll into it -- result: does not change a thing. If I change the version of the task from v2.0 to v1.0 it runs fine.
