### ISSUE TITLE
Add a new test method, build the solution, the status bar shows "Unexpected error detected".

### ISSUE THREAD

**Issue by Xiu-Li** [Microsoft/vstest#1334]
## Steps to reproduce
- Create a new .net core xUnit/Unit Test Project, open the "Test Explorer" window.
- Restore, build and run all succeeded, the status icon on test method "Test1" appears correctly in code editor.
- If add a new test method "Test2", build the solution again, the status icon on test method "Test2" doesn't appear.
- The status bar in the lower left corner shows "**_Unexpected error detected. Check the Tests Output Pane for details._**"
- The Output window of Tests shows an error:
 "Error: **_Unable to fetch source Information for test method: NCXUnitTestProject1.UnitTest1.Test2 contained in project: NCXUnitTestProject1_**.
![image](https://user-images.githubusercontent.com/24784908/34101461-c616a88c-e420-11e7-8536-4f885bd169bb.png)
## Environment
VS Build: D15svc.27130.2012 (15.5.3)
dotnet --info:

> .NET Command Line Tools (2.1.2)
> 
> Product Information:
>  Version:            2.1.2
>  Commit SHA-1 hash:  5695315371
> 
> Runtime Environment:
>  OS Name:     Windows
>  OS Version:  10.0.15063
>  OS Platform: Windows
>  RID:         win10-x64
>  Base Path:   C:\Program Files\dotnet\sdk\2.1.2\
> 
> Microsoft .NET Core Shared Framework Host
> 
>   Version  : 2.0.3
>   Build    : a9190d4a75f4a982ae4b4fa8d1a24526566c69df

**Comment by cltshivash** [comment]
@Xiu-Li : You are running into the issue reported here : https://developercommunity.visualstudio.com/content/problem/158160/unable-to-fetch-source-information-for-test-method.html.  Please use the above issue for further tracking.
