### ISSUE TITLE
JetBrains dotCover can't get coverage when testhost is killed

### ISSUE THREAD

**Issue by AM5800** [Microsoft/vstest#1335]
## Description
> **IMPORTANT**: if the defect is reproduced only in a workflow from within the Visual Studio IDE then do not report the issue here - instead, please report it using Visual Studio's "Send Feedback" option that can be accessed from the Help menu OR using this link https://developercommunity.visualstudio.com.
>
> For a defect reproducable from the vstest command line, describe the issue you've observed.

Hi, I am from dotCover team. Recently we have detected an issue with vstest that prevents our users from covering unit tests in console mode. 
dotCover is a classic coverage profiler. We store intermediate coverage data in the profiled process. And when this process is about to exit - we save this data on disk. But if the process is killed - coverage data is lost. This is what I am observing now. 

Say we have a command `dotnet vstest testAssembly.dll` and we would like to get unit test coverage with dotCover console tool. We feed this command into dotCover and the following happens(a little simplified):
1) dotCover spawns dotnet.exe process
2) dotnet.exe launches testhost.dll 
3) tests are run in testhost, they are instrumented by dotCover and coverage is collected in memory.
4) When tests are finished dotCover starts to save data
5) And suddenly testhost process is killed and coverage is lost.

I believe this happens in this line: https://github.com/Microsoft/vstest/blob/master/src/Microsoft.TestPlatform.CrossPlatEngine/Client/ProxyOperationManager.cs#L217 - Test host is killed after 100ms timeout. 
Most of the time 100ms is enough to save coverage. But sometimes not.

So do you have any ideas on how we can resolve this issue?

## Steps to reproduce
> What steps can reproduce the defect?
> Please share the setup, commandline for vstest.console, sample project, target
> framework etc.

I don't have a stable repro for you. It happens not always and you need really big project to exceed those 100 ms. I am able to reproduce this issue if I insert sleeps into dotCover executable. But I can't share it

So far I tried to reproduce this only with netcoreapp2.0 projects.

## Expected behavior
> Share the expected output

## Actual behavior
> What is the behavior observed?

## Diagnostic logs
> Please share test platform diagnostics logs. Instructions to collect logs are [here](https://github.com/Microsoft/vstest-docs/blob/master/docs/diagnose.md#test-platform-diagnostics).  
> The logs may contain test assembly paths, kindly review and mask those before sharing.

## Environment
> Please share additional details about the test environment.
> Operating system, Build version of vstest.console

**Comment by AM5800** [comment]
Hello, any news?

**Comment by cltshivash** [comment]
@AM5800 Modelling this as a data collector is the right mechanism. The out of the box code coverage support is build on this extension point. The test host will end once the tests end  execution. There isn't a mechanism today to extend the exit timeout for the testhost.

**Comment by smadala** [comment]
@AM5800 You can use `InProcDataCollection.TestSessionEnd` to achieve it([code](https://github.com/Microsoft/vstest/blob/master/src/Microsoft.TestPlatform.CrossPlatEngine/Execution/BaseRunTests.cs#L254)).  Example [here](https://github.com/smadala/vstest.datacollectors/blob/master/Examples/InProcDataCollectionExample.cs#L78) and [command](https://github.com/smadala/vstest.datacollectors#example-command-to-run-in-proc-data-collector) (for .NET full framework, change it for .NET Core).

**Comment by NikolayPianikov** [comment]
I think it is not convenient way to hard-coded the timeout ... why not 3000 ms or not 10 ms? Potentially it could be a cause of issues related to other performance/memory profilers for instance. User has no way to find any simple workaround on that.
