### ISSUE TITLE
TPv2 CDP for E2E testing

### ISSUE THREAD

**Issue by sbaid** [Microsoft/vstest#134]
## Description

Goals
On TPv2 releases
1. Run IDE integration tests 
2. Run CLI E2E tests
3. Share the infra work between TPv2 & testfx and not duplicate the effort

Solution 
Putting the discussion notes between me & Arun
1. Apex smoke tests will be reused. They will stay in vs repo & shared with maddog runs.
2. CLI E2E tests will come from vstest repo

Let's put more details as we discuss

**Comment by codito** [comment]
We have acceptance tests running in PR and CI. A CDP runs tests related to CC. Closing this one.
