### ISSUE TITLE
vstest v15.5.0 unable to find executor://mstestadapter/v2

### ISSUE THREAD

**Issue by CryptonZylog** [Microsoft/vstest#1340]
## Description
v.15.5.0 part of Test Agent distribution is unable to find MSTest.Adapter executor.

## Steps to reproduce
1. Create simple unit test project with MSTest targeting:
```xml
  <package id="MSTest.TestAdapter" version="1.2.0" targetFramework="net462" />
  <package id="MSTest.TestFramework" version="1.2.0" targetFramework="net462" />
```
2. Run via batch file
```
C:\Jenkins\path\to\project\workspace>"C:\Program Files (x86)\Microsoft Visual Studio\2017\TestAgent\Common7\IDE\Extensions\TestPlatform\vstest.console.exe" MyUnitTestDLL.dll /Logger:trx /Platform:x64 /inIsolation /Collect:"Code Coverage" 
```

Output:
```
14:32:22 Microsoft (R) Test Execution Command Line Tool Version 15.5.0
14:32:22 Copyright (c) Microsoft Corporation.  All rights reserved.
14:32:22 

14:32:23 Starting test execution, please wait...
14:32:23 Test run will use DLL(s) built for framework .NETFramework,Version=v4.6.2 and platform X64. Following DLL(s) do not match framework/platform settings.
14:32:23 SPC.Services.Auth.Roles.Tests.dll is built for Framework 4.6.2 and Platform X86.
14:32:23 Go to http://go.microsoft.com/fwlink/?LinkID=236877&clcid=0x409 for more details on managing these settings.
14:32:23 
14:32:25 Microsoft (R) Coverage Collection Tool Version 15.0.30319.1
14:32:25 Copyright (c) Microsoft Corporation.  All rights reserved.
14:32:25 
14:32:25 2.2682
14:32:30 Could not find test executor with URI 'executor://mstestadapter/v2'.  Make sure that the test executor is installed and supports .net runtime version  .
14:32:30 No test is available in C:\Jenkins\path\to\workspace\MyUnitTest\bin\Release\MyUnitTestDLL.dll. Make sure that test discoverer & executors are registered and platform & framework version settings are appropriate and try again.
```

## Expected behavior
Unit tests are discovered and ran, producing code coverage report

## Actual behavior
`Could not find test executor with URI 'executor://mstestadapter/v2'.  Make sure that the test executor is installed and supports .net runtime version  .`

## Environment
Jenkins agent running in Windows 2012 R2 Server

Certain paths and assembly names have been masked.

**Comment by ShreyasRmsft** [comment]
Hi @CryptonZylog, can you try adding the following option
/TestAdapterPath:"Path-to-Microsoft.VisualStudio.TestPlatform.MSTest.TestAdapter.dll"

try telling vstest.console.exe explicitly where the adapter dll is.

Lemme know if this works.

**Comment by codito** [comment]
Verbose traces of vstest.console.exe may provide more insights into the issue.

Instructions are at https://github.com/Microsoft/vstest-docs/blob/master/docs/diagnose.md#collect-traces-using-command-line

**Comment by CryptonZylog** [comment]
Hi, I created another issue here. It seems to stop working if you enable code coverage (which is not available in a Community or Test Agent install).

Microsoft/testfx/issues/336

**Comment by ShreyasRmsft** [comment]
@CryptonZylog This only occurs when you try with code coverage on a box with VS community edition right? Please re-open the issue if this is not the case. (ie. you are using Enterprise and it is not working)
