### ISSUE TITLE
Console logger initialized in design mode

### ISSUE THREAD

**Issue by abhishekkumawat23** [Microsoft/vstest#1343]
Observation:
Console logger getting initialized in design mode.

Expectation: 
Console logger should be initialized in case of command line only (and not in design mode.)

Why?
Currently we have a check to add console logger only if design mode is true in command line options.
But design mode value is set true in command line options after this check (and thus check becomes void)

**Comment by acesiddhu** [comment]
this is fixed by Abhishek PR https://github.com/Microsoft/vstest/pull/1399
