### ISSUE TITLE
Why deps.json and dev.json need to be writable?

### ISSUE THREAD

**Issue by qingjuntian** [Microsoft/vstest#1345]
## Description
> when run .Net Core cases, the deps.json and runtimeconfig.dev.json file need to be writable, why? when Look into https://github.com/Microsoft/vstest/blob/master/src/Microsoft.TestPlatform.CoreUtilities/Helpers/FileHelper.cs, in line 46, the FileAccess flag is readWrite. Could this be read only?

**Comment by smadala** [comment]
@qingjuntian Yes, It can be read only, Feel free to raise a PR to fix it.

**Comment by qingjuntian** [comment]
Seems I do not have permission?

**Comment by smadala** [comment]
Did you fork the repo? If not please fork it and create a branch with your changes and raise the PR.

**Comment by qingjuntian** [comment]
I do clone the repo, check out a new branch and get permission denied when I try to push:
"remote: Permission to Microsoft/vstest.git denied to qingjuntian.
fatal: unable to access 'https://github.com/Microsoft/vstest.git/': The requested URL returned error: 403". I also tried this from office and failed with my alias account: qitia

**Comment by smadala** [comment]
Yeah, you can't push a branch to remote https://github.com/Microsoft/vstest.git/.  You have to fork it(like you did for SNS-Shim), See https://help.github.com/articles/fork-a-repo/

**Comment by ShreyasRmsft** [comment]
You can fork the repo from the github UI also. Just click on the fork button as shown below and clone the forked version of the repo, make your changes to master in the forked version, push it and create a PR. If you're unable to do this then please reopen the issue and I'll help you out.

![image](https://user-images.githubusercontent.com/25194518/34478367-a484e394-efc6-11e7-8b85-2a3ac7b2d730.png)

**Comment by qingjuntian** [comment]
PR https://github.com/Microsoft/vstest/pull/1372 sent.

**Comment by qingjuntian** [comment]
Thanks Satya,

May I know how to install version with this fix? I tried to install Dotnet
Core SDK 2.1.300-preview3-008424 - which I think is the newest build. But
it seems still request write access to the dev.json file.

thanks.
Qingjun

**Comment by smadala** [comment]
@qingjuntian You are changes released in >= 15.7.0-preview-20180221-13. You can see the version when you run `dotnet test`. 

![image](https://user-images.githubusercontent.com/4337332/38200613-b0b3cd64-36b2-11e8-916a-958197e526c7.png)
****

I learnt while working on another issue that you can open a file in two different process with read mode also. You should specify [fileshare](https://msdn.microsoft.com/en-us/library/system.io.fileshare(v=vs.110).aspx) while [opening file](https://msdn.microsoft.com/en-us/library/y973b725(v=vs.110).aspx).

- Can you explain your scenario? 
- How are you running into this issue?
- Did you test your changes for your scenario?

**Comment by qingjuntian** [comment]
thanks Satya,

In fact I did not test the change with my scenario - that is why i am
asking here how to install version with this fix.

My scenario is when I run cases (my funtional test case project is
targeting Dotnet core app2.0)
1, the dev.json file is a soft link, which is not writable - I work around
this by copying the real json file
2, I need to run the cases in a parallel way, thus there is a race
condition where two processes try to require the same dev.json file's
writable access, this cause one of the cases failed.

Qingjun

**Comment by smadala** [comment]
@qingjuntian I have update my earlier comment.
>I learnt while working on another issue that you cann't open a file in two different process with read mode also. You should specify fileshare while opening file.

Because of above reason, your second scenario won't work with your fix.

**Comment by qingjuntian** [comment]
The default value Fileshare  Enum when opening file is FileShare.Read
right?

https://referencesource.microsoft.com/#mscorlib/system/io/filestream.cs,460

In this case should I specify the fileshare parameter again?

Thanks,
Qingjun

**Comment by qingjuntian** [comment]
hello Satya, could you please help check my previous question?
"
The default value Fileshare  Enum when opening file is FileShare.Read
right?

https://referencesource.microsoft.com/#mscorlib/system/io/filestream.cs,460

In this case should I specify the fileshare parameter again?"

Thanks,
Qingjun
