### ISSUE TITLE
VS2017 Enterprise v15.5.2 - Ordered tests - no tests available to choose from

### ISSUE THREAD

**Issue by Legends** [Microsoft/vstest#1347]
Win 10.

None of the existing tests are available to choose from in the ordered test.

**Comment by smadala** [comment]
@Legends In case you are using [MSTest v2](https://blogs.msdn.microsoft.com/devops/2016/06/17/taking-the-mstest-framework-forward-with-mstest-v2) (https://github.com/Microsoft/testfx), Ordered tests not supported with it. 
If it is not MSTest V2 test project, Please share repro project/steps.

@pvlakshm Please point out the documentation/blog for this scenario.

**Comment by pvlakshm** [comment]
This a tracked here: https://github.com/Microsoft/testfx/issues/25
