### ISSUE TITLE
TestAdapterPath in runsettings does not take relative paths

### ISSUE THREAD

**Issue by AbhitejJohn** [microsoft/vstest#135]
## Description

The TestAdapterPaths XML section does not understand relative paths unlike ResultsDirectory. This however works on using a testadapterpath commandline switch. With most adapters dropping the test adapter binaries in bin\debug, this inconsistency surfaces more.
## Steps to reproduce
1. Create an MSTest V2 test project.
2. Form a runsettings with a TestAdapterPath in the RunConfiguration section.
3. Run vstest.console with this runsettings.
## Expected behavior

The relative test adapter path gets honored and tests are discovered and run.
## Actual behavior

The adapter path does not get honored and tests do not run.
## Environment

> Please share additional details about the test environment.
> Operating system, Build version of vstest.console

[AB#1865835](https://devdiv.visualstudio.com/0bdbc590-a062-4c3f-b0f6-9383f67865ee/_workitems/edit/1865835)

**Comment by SabotageAndi** [comment]
It looks like this is still a problem in VS 2017 15.7 Preview 3.0 and in vstest.console.exe 15.7.0-preview-20180320-02.

Is there a recommendation what to do, if devs have their sources on different locations on their machines?

**Comment by vbondaryuk** [comment]
Dear vstest team, any update of it?

**Comment by nohwnd** [comment]
This is a new feature and won't be implemented, we are focusing on adding new features to Testing.Platform instead. https://aka.ms/testingplatform
