### ISSUE TITLE
Enabling the Server GC for Unit Tests in VS2017

### ISSUE THREAD

**Issue by iharwell** [Microsoft/vstest#1350]
## Description
> In previous versions of Visual Studio, adding `<serverGC enabled="true"/>` to the runtime configuration settings in vstest.console.exe.config allowed the use of the server GC for unit tests. This does not work in VS2017.

## Steps to reproduce
> Add `<serverGC enabled="true"/>` to vstest.console.exe.config located in the "....Common7\IDE\Extensions\TestPlatform" directory, and check the `GCSettings.IsServerGC` property in an NUnit 3 test.

## Expected behavior
> `GCSettings.IsServerGC` should return `true` in unit tests.

## Actual behavior
> `GCSettings.IsServerGC` returns `false`, and performance is consistent with the workstation GC.

## Environment
> vstest.console.exe: Version 15.5.0

**Comment by smadala** [comment]
.NET full tests runs in testhost.x86.exe/testhost.exe, Add `<gcServer enabled="true"/>` to respective config file.
