### ISSUE TITLE
xunit test fail to load System.Reflection.Extensions when targeting netcoreapp1.0 and not referencing xunit.runner.visualstudio package

### ISSUE THREAD

**Issue by livarcocc** [Microsoft/vstest#1357]
_From @jeremymeng on January 3, 2018 0:52_

As mentioned in https://github.com/xunit/xunit/issues/1601#issuecomment-354843968

1. `dotnet new xunit`
2. down targeting `netcoreapp1.0`
3. upgrade xunit verions to `2.4.0-*`
4. remove the `xunit.runner.visualstudio` package reference
5. when restoring, use the xunit myget feed too: `https://www.myget.org/F/xunit/api/v3/index.json`
6. `dotnet xunit`

**Actual**:
```
Detecting target frameworks in repro.csproj...
Building for framework netcoreapp1.0...
  repro -> C:\temp\repro\bin\Debug\netcoreapp1.0\repro.dll
Running .NET Core 1.0.5 tests for framework netcoreapp1.0...
error: Could not load file or assembly 'System.Reflection.Extensions, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'. The system cannot find the file specified.
```

**Expected**:
The removal of `xunit.runner.visualstudio` package shouldn't affect command line runs.

If we don't do step 4) then the test runs fine.

Differences in csproj/deps.json/asserts.json only shows the presence/absence of `xunit.runner.visualstudio` package. Nothing additional is restored by adding this package reference. @bradwilson suggested that .NET Core team should investigate.

Here's the only diff in the csproj:

![image](https://user-images.githubusercontent.com/7583839/34505898-20e7206c-efdd-11e7-986e-12a27923f1bb.png)

## Environment data
`dotnet --info` output:
```
.NET Command Line Tools (2.1.3)

Product Information:
 Version:            2.1.3
 Commit SHA-1 hash:  a0ca411ca5

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.14393
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\2.1.3\

Microsoft .NET Core Shared Framework Host

  Version  : 2.0.4
  Build    : 7f262f453d8c8479b9af91d34c013b3aa05bc1ff
```

_Copied from original issue: dotnet/cli#8317_

**Comment by livarcocc** [comment]
_From @jeremymeng on January 3, 2018 0:55_

I have a repro VM to share internally if needed.

**Comment by livarcocc** [comment]
I am not sure how this is a CLI issue.

I see that with 2.3.1 of xunit, this does not work at all, even with the `xunit.runner.visualstudio` entry in place. While with 2.4.0-* it works, like you said, as long as the visualstudio package is in place.

In any case, I will move the issue to the vstest repo, to see if someone there can see what might be wrong here.

**Comment by cltshivash** [comment]
@livarcocc The runner used in this case is the xunit runner and needs to be tracked with the xunit team on the xunit repo.

**Comment by livarcocc** [comment]
@cltshivash could you please move this issue to xunit then? Instead of just closing it?

**Comment by bradwilson** [comment]
The issue originated on the xUnit.net repo. I don't think it belongs in VSTest, but rather probably deserves some investigation by the .NET Core team to understand why the presence or absence of an unrelated dependency suddenly causes this issue.

**Comment by jeremymeng** [comment]
@livarcocc could you please re-open the dotnet/cli issue (and move to a proper repository if needed) so someone can have a look?
