### ISSUE TITLE
Test case Data driven tests fail in TPv2

### ISSUE THREAD

**Issue by ShreyasRmsft** [Microsoft/vstest#1359]
Visual Studio Version 15.5.2

TFS version 2018 (Shouldn't matter actually)

Sample test method (using MsTest v1 (Quality Tools) and a Test Settings file to force legacy mode)

        [TestMethod]
        [DataSource("Microsoft.VisualStudio.TestTools.DataSource.TestCase", "http://sinjithtfs18/DefaultCollection;AnjaAndric", "289", DataAccessMethod.Sequential)]
        public void TestMethod1()
        {
        }

Error message:
MSTestAdapter could not run the test as the classic mode helper is not available. It can occur if the test settings has been selected or you are using attributes like HostType, UrlToTest, Credential or DataSource in your test. Either unselect the test settings or remove these attributes from the test and try again.

Diag file:
[log.host.18-01-04_17-15-23_77304_1.txt](https://github.com/Microsoft/vstest/files/1603215/log.host.18-01-04_17-15-23_77304_1.txt)

Note: the same works in TPv1

**Comment by ShreyasRmsft** [comment]
[1/8/2018 12:05:06 PM Informational] ------ Discover test started ------
[1/8/2018 12:05:19 PM Error] MSTestAdapter could not discover the test because the classic mode helper is not available. If a TestSettings file has been selected, unselect it and try again.

This occurred when loading the testplatform sln in the devdiv code base. Not sure if it is related but adding it here anyway

**Comment by abhishkk** [comment]
Test case data driven is working with TPv2 for mstest v1 adapters (tried the same for DataSource attribute with CodedUI.)
