### ISSUE TITLE
Failed to negotiate protocol. Wait for response timed out

### ISSUE THREAD

**Issue by ShreyasRmsft** [Microsoft/vstest#1361]
[link to original issue on vsts-tasks repo](https://github.com/Microsoft/vsts-tasks/issues/6073)

detailed logs at devops alias.

[8_Run tests.txt](https://github.com/Microsoft/vstest/files/1606051/8_Run.tests.txt)

**Comment by ShreyasRmsft** [comment]
Customer is using latest tpv2 nuget pacakge

**Comment by ShreyasRmsft** [comment]
Have attached logs of various failures occurring on Hosted 2017 agents related to test platform to the customer query on mseng.

**Comment by ShreyasRmsft** [comment]
@mayankbansal018, I've attached the builds with diag logs enabled to the associated mseng customer query item. It'll be of the form guid.txt in the build logs.

**Comment by drjp81** [comment]
Chiming in, I have also started experiencing similar failures. Is there a way we can ensure this will no longer be an issue in the future, we have several applications in our critical path that rely on the dependability of this.

**Comment by mayankbansal018** [comment]
@drjp81 , can you please elaborate your scenario, are you using VSTS Hosted Agents to run tests?
Does you test have datacollection enabled, for e.g. CodeCoverage or Fakes?

We recently found an issue with datacollection on Hosted Agents with VS2017 update 5

**Comment by drjp81** [comment]
Yes Codecoverage is activated, simple unit testing is also done. And yes it is on a hosted 2017 agent. We had the path for the testing tool "hard coded" in the VSTS task (ie: c:\program files ... vstest201.exe)

**Comment by ShreyasRmsft** [comment]
@janpieterz as per [your issue](https://github.com/Microsoft/vsts-tasks/issues/6073), after further investigation, 
 
"_TpTrace Verbose: 0 : 2768, 6, 2018/01/07, 17:00:24.845, 6455593939, vstest.console.exe, Test Runtime launched
TpTrace Error: 0 : 2768, 1, 2018/01/07, 17:01:24.852, 7055627718, vstest.console.exe, ProxyExecutionManager.StartTestRun: Failed to start test run: Microsoft.VisualStudio.TestPlatform.ObjectModel.TestPlatformException: Failed to initialize client proxy: could not connect to test process.
   at Microsoft.VisualStudio.TestPlatform.CrossPlatEngine.Client.ProxyOperationManager.SetupChannel(IEnumerable`1 sources, CancellationToken cancellationToken)
   at Microsoft.VisualStudio.TestPlatform.CrossPlatEngine.Client.ProxyExecutionManager.StartTestRun(TestRunCriteria testRunCriteria, ITestRunEventsHandler eventHandler)
TpTrace Verbose: 0 : 2768, 1, 2018/01/07, 17:01:24.859, 7055698884, vstest.console.exe, TestRunRequest:SendTestRunMessage: Starting.
TpTrace Information: 0 : 2768, 1, 2018/01/07, 17:01:24.860, 7055708664, vstest.console.exe, TestRunRequest:SendTestRunMessage: Completed.
TpTrace Verbose: 0 : 2768, 1, 2018/01/07, 17:01:24.863, 7055743446, vstest.console.exe, TestRunRequest:TestRunComplete: Starting. IsAborted:True IsCanceled:False.
TpTrace Warning: 0 : 2768, 1, 2018/01/07, 17:01:29.246, 7099570758, vstest.console.exe, ProxyOperationManager: Failed to end session: System.NullReferenceException: Object reference not set to an instance of an object.
   at Microsoft.VisualStudio.TestPlatform.CommunicationUtilities.TestRequestSender.EndSession()
   at Microsoft.VisualStudio.TestPlatform.CrossPlatEngine.Client.ProxyOperationManager.Close()"_

From the above logs it seems that the issue is because of connection failure b/w various process, primarily b/w vstest.console, & testhost.exe. If you face this issue again can you please set a **build variable** "VSTEST_CONNECTION_TIMEOUT" with value 120 as part of your build definition, this should give vstest sufficient time to connect to testhost process. Let us know if you still get this failure.

**Comment by mayankbansal018** [comment]
@drjp81 , can you please explain what _"(ie: c:\program files ... vstest201.exe)"_ path is? Is it "C:\Program Files (x86)\Microsoft Visual Studio\Preview\d16stg\Common7\IDE\CommonExtensions\Microsoft\TestWindow\vstest.console.exe"? 

Also I've not seen the issue with CodeCoverage alone, does your definition also have tests have Fakes enabled? or some other datacollector?
Is it possible for you to share some logs or your build definition with us?

**Comment by mayankbansal018** [comment]
@drjp81 , I'm closing this issue, regarding the hang issue you are facing during datacollection, we have resolved it in latest preview version. For more details please follow issue #1419 . I've also posted a solution there.
