### ISSUE TITLE
Test with .NET 4.7.1 Causing MissingMethodException on TestHost CreateClient

### ISSUE THREAD

**Issue by msmolka** [Microsoft/vstest#1365]
## Description
> When trying to create test that using `TestServer` and `CreateClient`, there is an exception `MissingMethodException` on .NET Framework 4.7.1. On .NET 4.6.2 all is working correctly.

## Steps to reproduce
> Create MS UnitTest for .NET Core with target .NET 4.7.1 and add reference to `Microsoft.AspNetCore.TestHost`. Then in test method create:
```csharp

        [TestMethod]
        public void TestMethod1()
        {

            var server = new TestServer(
                new WebHostBuilder()
                    .UseStartup<Startup>());

            var client = server.CreateClient();

        }

```
> This method won't run. It will cause `MissingMethodException`. I've created test project.
[WebApplication2.zip](https://github.com/Microsoft/vstest/files/1611360/WebApplication2.zip)

## Expected behavior
> Method should run.

## Actual behavior
> This method won't run. It will cause `MissingMethodException`.

## Environment
> .NET 4.7.1
> Windows 10 
> Visual Studio 15.5.2

**Comment by mayankbansal018** [comment]
@msmolka , I analyzed this issue, & it seems that appropriate binding redirects are not generated for the UnitTest project, even though it has set GenerateBindingRedirectsOutputType,  & AutoGenerateBindingRedirects  to "true"

/cc @eerhardt  , @nguerrera, can you please help us investigate this.
In the attached project(see bug description), if you change both UnitTest , & WebApplication to net462, it generated appropriate binding redirects for Unit Test project, & test run fine.

**Comment by eerhardt** [comment]
I repro'd this myself with VS 15.6 Preview 3.  It appears to be a bug with the sdk (or targeting pack) that is supposed to be adding these binding redirects for net471.  `System.Net.Http.dll` is getting locally bin placed, but no binding redirects are being added.

Talking with @weshaggard and @ericstj, it appears that `netfx.force.conflicts.dll` is not getting referenced on net471, and thus the binding redirects aren't making their way into the app config by default.

Adding the binding redirect manually fixes the issue:

```
<configuration>
  <runtime>
    <assemblyBinding xmlns="urn:schemas-microsoft-com:asm.v1">
      <dependentAssembly>
        <assemblyIdentity name="System.Net.Http" publicKeyToken="b03f5f7f11d50a3a" culture="neutral" />
        <bindingRedirect oldVersion="0.0.0.0-4.2.0.0" newVersion="4.2.0.0" />
      </dependentAssembly>
    </assemblyBinding>
  </runtime>
</configuration>
```

We should open a bug on dotnet/sdk for this scenario if one doesn't already exist.  A fix needs to go in there.

/cc @joperezr @AlexGhiondea

**Comment by joperezr** [comment]
yup, this is fixed with the new targeting pack that will now include netfx.force.conflicts on 4.7.1 as well. This new targeting pack was already inserted to the CLI, and in theory it is supposed to make it to VS 15.6 RTM since that CLI is in theory going to be inserted into VS. @livarcocc do you know if that CLI has already been inserted into VS? which preview of VS 15.6 should we expect the fix to be in?

**Comment by mayankbansal018** [comment]
@joperezr , can you provide me link to dotnet bug where this got fixed? Also can you share the preview version of dotnet sdk, which @msmolka can you use to unblock?

**Comment by joperezr** [comment]
Sure, this is the PR that inserted the package with the fix into the CLI https://github.com/dotnet/cli/pull/8249 and this is the actual PR that fixed that package https://github.com/dotnet/corefx/pull/25786.

@livarcocc should be able to point us to a CLI that will contain the fix.

**Comment by mayankbansal018** [comment]
@msmolka , the issue was on dotnet sdk end, which they have fixed. Please move to latest preview, & you should not hit this issue any more.
I'm closing this now, please reopen it if it does not get resolved in latest dotnet sdk
