### ISSUE TITLE
VsTest Platform installer indicating path too long

### ISSUE THREAD

**Issue by jdholbrook81** [Microsoft/vstest#1368]
## Description
I added VsTest Platform installer task to my release with Version set to Latest Pre-Release. When the task runs it fails indicating it cannot install. Logs indicate path is too long. Directory limit is 248 characters as indicated in the log, but my directory is only 69 characters.

I also tried using the specific version option and setting that to "15.6.0-preview-20171211-02" which is the current version in the nuget gallery.

## Environment
Agent.OS | Windows_NT
Agent.OSVersion | 6.3.9600
Agent.Version | 2.124.0

## Diagnostic logs
> 2018-01-08T13:53:16.8618746Z ##[section]Starting: VsTest Platform Installer
> 2018-01-08T13:53:16.8782263Z ==============================================================================
> 2018-01-08T13:53:16.8782263Z Task         : Visual Studio Test Platform Installer
> 2018-01-08T13:53:16.9087427Z Description  : Acquires the test platform from nuget.org or the tools cache. Satisfies the ‘vstest’ demand and can be used for running tests and collecting diagnostic data using the Visual Studio Test task.
> 2018-01-08T13:53:16.9087427Z Version      : 1.0.3
> 2018-01-08T13:53:16.9087427Z Author       : Microsoft Corporation
> 2018-01-08T13:53:16.9087427Z Help         : Acquires the <a href="https://www.nuget.org/packages/Microsoft.TestPlatform/">test platform from nuget.org</a> or the tools cache. Satisfies the ‘vstest’ demand and can be used for running tests and collecting diagnostic data using the ‘Visual Studio Test’ task.
> 2018-01-08T13:53:16.9087427Z ==============================================================================
> 2018-01-08T13:53:18.4123441Z Starting VsTest platform tools installer task.
> 2018-01-08T13:53:18.4123441Z ==============================================================================
> 2018-01-08T13:53:18.4123441Z Looking for the latest pre-release version of the Microsoft.Testplatform.
> 2018-01-08T13:53:22.2694764Z [command]C:\VSTSReleaseAgent\vsts-agent-win7-x64-2.110.0_2\_work\_tasks\VisualStudioTestPlatformInstaller_2c65196a-54fd-4a02-9be8-d9d1837b7111\1.0.3\nuget.exe install Microsoft.TestPlatform -Version 15.6.0-preview-20171211-02 -Source https://api.nuget.org/v3/index.json -OutputDirectory C:\VSTSReleaseAgent\vsts-agent-win7-x64-2.110.0_2\_work\_temp\VsTest -NoCache -DirectDownload
> 2018-01-08T13:53:22.3623966Z Feeds used:
> 2018-01-08T13:53:22.3623966Z   https://api.nuget.org/v3/index.json
> 2018-01-08T13:53:22.3623966Z 
> 2018-01-08T13:53:22.3943197Z 
> 2018-01-08T13:53:22.3943197Z 
> 2018-01-08T13:53:22.4717887Z Attempting to gather dependency information for package 'Microsoft.TestPlatform.15.6.0-preview-20171211-02' with respect to project 'C:\VSTSReleaseAgent\vsts-agent-win7-x64-2.110.0_2\_work\_temp\VsTest', targeting 'Any,Version=v0.0'
> 2018-01-08T13:53:23.9288385Z Gathering dependency information took 1.43 sec
> 2018-01-08T13:53:23.9600560Z Attempting to resolve dependencies for package 'Microsoft.TestPlatform.15.6.0-preview-20171211-02' with DependencyBehavior 'Lowest'
> 2018-01-08T13:53:24.0225533Z Resolving dependency information took 0 ms
> 2018-01-08T13:53:24.0225533Z Resolving actions to install package 'Microsoft.TestPlatform.15.6.0-preview-20171211-02'
> 2018-01-08T13:53:24.0225533Z Resolved actions to install package 'Microsoft.TestPlatform.15.6.0-preview-20171211-02'
> 2018-01-08T13:53:24.0694243Z Retrieving package 'Microsoft.TestPlatform 15.6.0-preview-20171211-02' from 'nuget.org'.
> 2018-01-08T13:53:24.1631710Z   GET https://api.nuget.org/v3-flatcontainer/microsoft.testplatform/15.6.0-preview-20171211-02/microsoft.testplatform.15.6.0-preview-20171211-02.nupkg
> 2018-01-08T13:53:24.3749288Z   OK https://api.nuget.org/v3-flatcontainer/microsoft.testplatform/15.6.0-preview-20171211-02/microsoft.testplatform.15.6.0-preview-20171211-02.nupkg 209ms
> 2018-01-08T13:53:27.4662730Z Adding package 'Microsoft.TestPlatform.15.6.0-preview-20171211-02' to folder 'C:\VSTSReleaseAgent\vsts-agent-win7-x64-2.110.0_2\_work\_temp\VsTest'
> 2018-01-08T13:53:28.5918697Z WARNING: Install failed. Rolling back...
> 2018-01-08T13:53:28.5918697Z Executing nuget actions took 4.55 sec
> 2018-01-08T13:53:28.5918697Z The specified path, file name, or both are too long. The fully qualified file name must be less than 260 characters, and the directory name must be less than 248 characters.
> 2018-01-08T13:53:28.7268717Z ##[warning]Failed to download version 15.6.0-preview-20171211-02 of the test platform. Looking in the cache for the latest available version.
> 2018-01-08T13:53:28.7425047Z ##[warning]Failed to find any version of the test platform package in the cache.
> 2018-01-08T13:53:28.7425047Z ##[error]Failed to acquire the test platform. Please refer to the logs for additional information.

**Comment by ShreyasRmsft** [comment]
Hi @jdholbrook81, The test platform package has a certain files whose path **relative** to the agent folder is as much as 194 chars. Adding that to your 69 chars for the agent directory path easily exceeds the character limit for file paths. Sadly the only workaround for this is to reduce the path to your agent folder to a lesser value **x** (**x** + 194 < 248).

**Comment by jdholbrook81** [comment]
@ShreyasRmsft thank you. I should have pulled down the package and looked there. I will reduce my agent path. It shouldn't have the version in the path anyways, but this agent was from my first attempt.

**Comment by ShreyasRmsft** [comment]
@jdholbrook81, the only reason we haven't added a preemptive warning in the task is that there is no way for us to know beforehand what the longest path inside a particular version of the test platform package will be. We will rethink a strategy for this, meanwhile closing this issue.
