### ISSUE TITLE
Test host fails unexpectedly

### ISSUE THREAD

**Issue by ryanbrandenburg** [Microsoft/vstest#1370]
## Description
Test runs sometimes fail with no apparent reason, all the tests will report as passing then vstest will return an exit code of 1 and an error like `Unable to read data from the transport connection: An established connection was aborted by the software in your host machine.`

## Steps to reproduce
Reproduction steps are hazy because this happens intermittently, but a start would be:
1. Clone aspnet/Configuration
2. Run `./build.cmd` in a loop until one of them fails.
We see it most often when building while the system is under heavy load.

## Expected behavior
The tests should pass.

## Actual behavior
Test process' fail seemingly at random with errors like `Runner error: Unable to read data from the transport connection: An established connection was aborted by the software in your host machine.`.

## Diagnostic logs
[UnitTests-net461-19172.txt](https://github.com/Microsoft/vstest/files/1624048/UnitTests-net461-19172.txt)
[UnitTests-net461-19172.host.18-01-10_21-51-00_52850_19.txt](https://github.com/Microsoft/vstest/files/1624049/UnitTests-net461-19172.host.18-01-10_21-51-00_52850_19.txt)
[UnitTests-net461-19172.datacollector.18-01-10_21-50-59_79479_19.txt](https://github.com/Microsoft/vstest/files/1624050/UnitTests-net461-19172.datacollector.18-01-10_21-50-59_79479_19.txt)

## Environment
We've seen this on multiple different OS's.
`Microsoft (R) Test Execution Command Line Tool Version 15.6.0-preview-20171211-02`

CC @natemcmaster and reference aspnet/BuildTools#539

**Comment by abhishkk** [comment]
@ryanbrandenburg  The EndOfStreamException can occur in vstest.console process (testhost processes orchestrator) when the testhost process (In which tests run) crashes. 
Can you follow steps from [Issue 1069](https://github.com/Microsoft/vstest/issues/1069) to know which test or group of tests is causing test host to crash.

**Comment by ryanbrandenburg** [comment]
If you're refering to `--blame` it's already on and doesn't result in any information about what crashed the host.

**Comment by mayankbansal018** [comment]
@ryanbrandenburg the logs that you shared are throwing exception in case data collector is enabled, however as part of your build / test run, that is not the case.
Also the exceptions that you have mentioned are all related to datacollector.

Can you please enable just diag logs, & share those if you get any failure again, w/o enabling blame datacollector as it is just causing confusion, but adding EndOfStreamException & Other exception

**Comment by mayankbansal018** [comment]
@ryanbrandenburg , I tried to repro this locally, by running the script multiple times, but could not get a repro. I'm closing this issue for now, as we don't have required logs, please re-open it if you are still getting this error, & share with us the logs
