### ISSUE TITLE
"New" UWP engine fails to run test, and simply hangs

### ISSUE THREAD

**Issue by borrrden** [Microsoft/vstest#1373]
## Description
Possibly related to #594 but I've been running unit tests on Jenkins by using [this script](https://github.com/couchbase/couchbase-lite-net/blob/feature/api-v2/src/Couchbase.Lite.Tests.UWP/run_tests.bat).  It is very simple, with only two lines and has served me well until now.  Recently I decided to attempt to upgrade to .NET Standard 2.0 for our library.  This requires the latest version of UWP and so I set the target and min versions appropriately to the latest version.  According to #594 this changes the behavior of test discovery.  In fact, changing the minimum version back to a lower version (Anniversary edition) makes this go away.  With the lower minimum version everything works as expected.  With the target and min version set higher, the unit test app launches with a blank white body and simply hangs forever.

## Steps to reproduce
Using VS 15.5.3, create a new unit test app and launch by building an APPX package via msbuild, and then launch using vstest.console.exe (though the logs I provide are from my own unit test app, I tried with a brand new unit test app from the VS templates and the result was the same)

## Expected behavior
The tests should run and report the results

## Actual behavior
The unit test app hangs with a white screen (no UI)

## Diagnostic logs
[Log from bad run](https://github.com/Microsoft/vstest/files/1630665/log-bad.txt) with both versions set to Fall Creator's update
[Log from good run](https://github.com/Microsoft/vstest/files/1630667/log-good.txt) where the only change was the minimum version of Windows (Set to Anniversary edition)

## Environment
Windows 10 Fall Creator's Update
Visual Studio 15.5.3
[Actual Test App](https://github.com/couchbase/couchbase-lite-net/tree/feature/api-v2/src/Couchbase.Lite.Tests.UWP) (note: will change as I fight to work around this issue)

**Comment by mayankbansal018** [comment]
@borrrden, as per Logs from bad run, it seems you are trying to run your test via CLI, & you are passing ".appx" as input.
As you know for Fall Creators Update we implicitly move projects to go via newer platform(Tpv2). We plan to move all UWP projects eventually to this newer platform.

For your current issue, unfortunately in Tpv2, we have not yet added support for ".appx" as CLI input, however you can pass ".appxrecipe" file as input to vstest.console
E.g. vstest.console <path_to_appxrecipe> --framework:FrameworkUap10

Let me know if this resolved your issue?

**Comment by borrrden** [comment]
Yes, that solved the issue and the output is much better too!  Thanks.

**Comment by dotMorten** [comment]
I don't really understand you make such a significant change before all the tooling is ready for it?

**Comment by mayankbansal018** [comment]
@dotMorten , we understand your concern, but the newer platform was bringing in support for IOT devices as well, & the work to enable ".appx" as source was in flight already, which would be available in 15.7 RTM.

As a CLI solution we made sure we had something for the customers, so we started with ".appxrecipe".
Given the overall benefits of bringing in the new platform we took this call.

**Comment by dotMorten** [comment]
@mayankbansal018 I don't have a problem with adding new functionality, but a problem with changing and breaking existing functionality for the sake of adding new functionality. It was very disruptive for our automated testing
