### ISSUE TITLE
TestDiscovery Message needs to be more meaningful

### ISSUE THREAD

**Issue by cltshivash** [Microsoft/vstest#1377]
## Description
The following message when no tests are discovered from a source could be made more actionable and clear:

No test is available in C:\Users\arturs\Source\Repos\ClassLibrary1\XU2\bin\Debug\XU2.dll. Make sure that test discoverer & executors are registered and platform & framework version settings are appropriate and try again.

Specifically would folks relate more to test adapters here instead? Also, once folks see this error, can we point them to a link that explains how they can setup their projects so discovery works? This would definitely involve both IDE and CLI information.

## Steps to reproduce
Run a test dll in CLI with no tests

**Comment by mayankbansal018** [comment]
We can take this as improvement if it comes as an input from users stating that they don't understand this message. Closing this as not received any such inputs
