### ISSUE TITLE
vstest.console.exe discovers no tests

### ISSUE THREAD

**Issue by pMaske** [Microsoft/vstest#1379]
[UITestAndroid.zip](https://github.com/Microsoft/vstest/files/1644924/UITestAndroid.zip)
[UnitTestApp1.zip](https://github.com/Microsoft/vstest/files/1644925/UnitTestApp1.zip)

## Description
I created a simple Xamarin cross platform UI test project and when I run vstest command to execute those tests I get a warning that no tests are available and the tests are not run. There is only one test in the app. The app is pretty much out of the box app.

C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\Common7\IDE\CommonExtensions\Microsoft\TestWindow>vstest.console.exe C:\Users\Pree6725\source\repos\UnitTestApp1\bin\Debug\UnitTestApp1.dll
Microsoft (R) Test Execution Command Line Tool Version 15.0.26929.2
Copyright (c) Microsoft Corporation.  All rights reserved.
Starting test execution, please wait...
Warning: No test is available in C:\Users\Pree6725\source\repos\UnitTestApp1\bin\Debug\UnitTestApp1.dll. Make sure that installed test discoverers & executors, platform & framework version settings are appropriate and try again.

Information: Additionally, you can try specifying '/UseVsixExtensions' command if the test discoverer & executor is installed on the machine as vsix extensions and your installation supports vsix extensions. Example: vstest.console.exe myTests.dll /UseVsixExtensions:true

## Steps to reproduce
-  Create an out of the box xamarin Android Unit test app.
-  Create a out-of the box xamarin UI test project
-  Hook them up together by adding reference of Android project to the UI test project
- You would also need to specify .apk in StartUp() method of the UI test project.

I am using VS2017 update 4, .Net Framework 4.7.1

Xamarin  Please share the setup, commandline for vstest.console, sample project, target
> framework etc.

## Expected behavior
The test should run when run from command line

## Actual behavior
The tests are not discovered and nothing is executed

## Diagnostic logs
> Please share test platform diagnostics logs. Instructions to collect logs are [here](https://github.com/Microsoft/vstest-docs/blob/master/docs/diagnose.md#test-platform-diagnostics).  
> The logs may contain test assembly paths, kindly review and mask those before sharing.

## Environment
> Please share additional details about the test environment.
> Operating system, Build version of vstest.console

Win 10, 1709 OS build 16299.125

**Comment by smadala** [comment]
@pMaske vstest.console don't support xamarin Andriod UITests, It supports .NET Full framework, .NET Core and UWP test projects.  [This](https://forums.xamarin.com/categories/xamarin-test-cloud) looks like right place for you question.
