### ISSUE TITLE
Configuring environment variables

### ISSUE THREAD

**Issue by pkruk2** [Microsoft/vstest#1381]
Hi, 

is it possible to specify environment variables for vstest somehow? The variable must be set when process starts, so for example setting them in in-proc data collector is too late.

I am using VsTestConsoleWrapper so I can set them in process which starts session ("parent"). But this is not optimal, as I think the variable must stay set until I finish running unit tests (until EndSession())? If yes, then any other process started from "parent" will also have those variables set, which may be not desirable.

Is there a different way? 

If not, I would like to propose enhancement to add such ability (for example allow passing evironment to VsTestConsoleWrapper constructor).

Thanks

**Comment by cltshivash** [comment]
@pkruk2  Could you please provide more details on your scenario ?

**Comment by pkruk2** [comment]
@cltshivash I want to set up profiler, and for that I need to have environment variables set up before process starts (https://docs.microsoft.com/en-us/dotnet/framework/unmanaged-api/profiling/setting-up-a-profiling-environment)

**Comment by pkruk2** [comment]
@smadala thank you, I will try it.

**Comment by pkruk2** [comment]
Hello again, 

I have troubles making VsTestConsoleWrapper use a data collector.

That is, I can pass it to vstest.console.exe and it is used (initialized). But when I try to pass it to VsTestConsoleWrapper, it is not used. I have tried a couple of variants with RunSettings.

I am attaching repro. Could you please tell me if I'm doing something wrong?

# Repro

[VstestCustomDataCollector.zip](https://github.com/Microsoft/vstest/files/1659933/VstestCustomDataCollector.zip) - contains 3 projects:
- sample data collector,
- nunit tests
- VsTestConsoleWrapper program

1. unpack VstestCustomDataCollector.zip
2. build solution
3. download and unpack vstest.console.exe (https://www.nuget.org/packages/Microsoft.TestPlatform/15.6.0-preview-20171211-02)
4. update runVstest.bat and runVsTestConsoleWrapper.bat with path to vstest.console.exe
5. execute runVstest.bat, notice that debugger is launched and/or c:\tmp\SampleDataCollector.txt was created/updated - this means the data collector was initialized
6. execute runVsTestConsoleWrapper.bat, notice that debugger is not launched and c:\tmp\SampleDataCollector.txt is not created

**Comment by smadala** [comment]
@pkruk2 You have to locate datacollector assembly in `runsettings` when running from VsTestConsoleWrapper using `TestAdaptersPaths` element.

```xml
<RunSettings>
    <RunConfiguration>
     <TestAdaptersPaths>E:\d\Jan-2018\VstestCustomDataCollector\VstestCustomDataCollector\bin\Debug</TestAdaptersPaths>
</RunConfiguration>
    <DataCollectionRunSettings>
        <DataCollectors>
            <DataCollector friendlyName=""SampleDataCollector"" uri=""my://sample/datacollector"" >
                <Configuration>
                    <LogFileName>DataCollectorLogs.txt</LogFileName>
                </Configuration>
            </DataCollector>
        </DataCollectors>
    </DataCollectionRunSettings>
</RunSettings>
```
