### ISSUE TITLE
How to log to Visual Studio IDE output window

### ISSUE THREAD

**Issue by suntong** [Microsoft/vstest#1389]
Just a simple noob question,

How to log to Visual Studio IDE output window? 

I have a NUnit test, and I want to log some info to Visual Studio IDE output window during test execution. I've traced NUnit's own logging (to Visual Studio IDE output) to this project, but I can't make it works myself. E.g., I tried, among many other things, 

    Microsoft.VisualStudio.TestTools.UnitTesting.Logging.Logger.LogMessage("My own IDE output window log message");

but none is working for me. 

Or, what `IMessageLogger` I should use (that is for Visual Studio IDE output), when initializing my own logger like the following?

https://github.com/nunit/nunit3-vs-adapter/blob/d8943d87ecccc097224494f905df287d79f097b3/src/NUnitTestAdapter/NUnitTestAdapter.cs#L121

Please help. Thanks!

**Comment by pvlakshm** [comment]
Not sure I understand ...
If you use ```Console.Writeline``` you should see the emitted text in the Visual Studio Test Explorer's Output link.

Or, you can use a TextWriter ...
```
    System.IO.TextWriter t = TestContext.Out;
    t.WriteLine("using TextWriter");
```
Here too you should see the emitted test in the Visual Studio Test Explorer's Output link.

**Comment by suntong** [comment]
First, I want to log some info to Visual Studio IDE output window, check this out:

![2018-01-31 09_48_10-easyuxautomation - microsoft visual studio](https://user-images.githubusercontent.com/422244/35629235-13425b70-066c-11e8-8f98-8bd7bf88569c.png)

Second, I want to log them during test execution, not debugging. 

NUnit's own logging is able to do it, logging to Visual Studio IDE output, but I'm not clear how. Hence the questions in OP. 

Thx.

**Comment by acesiddhu** [comment]
@suntong there is only one way today (and we don't want any other message to flow in test output window because it will have too many messages in the window which will confuse users
The only way (and I suggest we use that only for debugging) is Console.Error.WriteLine("test");

Normal Console.WriteLine("") messages wont flow to test window output. but they will flow to output of test case
![image](https://user-images.githubusercontent.com/1168823/35849240-e807cc1c-0b46-11e8-9171-c3327f3d2d1c.png)

**Comment by suntong** [comment]
That looks like a _normal_ Unit test instead of a NUnit test, which is easy to write to (using `Debug.WriteLine`) because of that "Output" link. A NUnit test doesn't have that:

![image](https://user-images.githubusercontent.com/422244/35867388-9c7f536a-0b27-11e8-9e90-aeb867cb8279.png)

That's why I need them to be in Visual Studio IDE `output` window as posted above:

![2018-01-31 09_48_10-easyuxautomation - microsoft visual studio](https://user-images.githubusercontent.com/422244/35629235-13425b70-066c-11e8-8f98-8bd7bf88569c.png)

**Comment by acesiddhu** [comment]
it is a nunit test 

using NUnit.Framework;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace nunit
{
    public class Class1
    {
        [Test]
        public void Test1()
        {
            //   Console.Error.WriteLine("test");  // this prints in output window
            Console.WriteLine("test"); // this shows in test window output as image attached in my previous reply
        }
    }
}

**Comment by suntong** [comment]
Gotya! Thanks **a lot** for helping!!!
