### ISSUE TITLE
Please document the list of NuGet packages in README.md

### ISSUE THREAD

**Issue by jnm2** [Microsoft/vstest#1392]
It's hard to discover information about which NuGet packages should be used and when. Please add a readme section which lists the main NuGet packages to use and why each one exists.

For example, when I need to run vstest.console.exe from a build script on a build server without VS installed, which is the smallest NuGet package or metapackage which I need?

I happen to know the answer to that question now, but I initially failed to find anything and I [just happened to be told](https://developercommunity.visualstudio.com/solutions/185103/view.html) as part of another issue.

**Comment by heaths** [comment]
Or, more generally, how this is expected to be used? The vstest-docs repo covers the architecture, extensibility, and more well, but where's a doc that just says whether this effectively replaces calling out to the VS-installed adapter, and other brief "how to" content. That should be covered in this repo's README.md, IMO. Given the current [difficulties](Microsoft/vswhere/issues#126) in calling vstest.console.exe, can developers just expect to install these packages and not have to worry about how to find vstest.console.exe?

**Comment by jnm2** [comment]
@heaths :+1:– also I think GitHub messed up your link.

**Comment by pvlakshm** [comment]
Please see here: [0014-Packaging.md](https://github.com/Microsoft/vstest-docs/blob/master/RFCs/0014-Packaging.md).

**Comment by heaths** [comment]
On GitHub, it's more common to list these in the README (or a link therefrom) or in the wiki that is included in all projects by default. I wasn't expecting to spelunk for documentation

**Comment by jnm2** [comment]
That looks great! It's exactly what I hoped for!

Now, can this be done for all packages published from this repo?

For example, when writing a test adapter, you'd want to reference Microsoft.TestPlatform.ObjectModel.

Or here's something I'm looking at right now. In the tests for the NUnit adapter, I want to create an `ITestCaseFilterExpression` from a given string to test against. The keys to that are public in `Microsoft.VisualStudio.TestPlatform.Common.dll` So what I'm hoping to know is, which NuGet package should I reference? `Microsoft.TestPlatform.TestHost` seems like the smallest package which contains it, but the lib/net45 assemblies are missing. Do you think it's possible for the NuGet package documentation to answer questions like this?

**Comment by mayankbansal018** [comment]
@pvlakshm , can you please update the readme, & close this
