### ISSUE TITLE
Custom TestAdapterPath XML element should be "TestAdapterPaths", but NOT "TestAdaptersPaths"

### ISSUE THREAD

**Issue by saikrishnav** [Microsoft/vstest#141]
## Description

From command line, we do:  /testadapterpath: "<PathToAdapter">
From RunSettings: we should do: `<TestAdapterPaths>`
since we can specify more than one path there. 

Currently we are expecting "TestAdaptersPaths" - which is not consistent and not intuitive. 

Change this to "TestAdapterPaths" in RunConfiguration

**Comment by saikrishnav** [comment]
I think it is OK to have the old name. Unnecessary confusion otherwise. Closing this for now.
@codito - Please reopen if you think you want to add anything here. I do not see anything required here.

**Comment by AbhitejJohn** [comment]
There is however a disparity in this naming: The runsettings uses "TestAdaptersPaths" and the commandline accepts testadapterpath. Should we not have the same naming here? IIRC the commandline testadapterpath argument does not take in multiple paths which is another gap.

**Comment by smadala** [comment]
Not changing name for compact reasons. Gap is addressed by @dtretyakov https://github.com/Microsoft/vstest/pull/1320,
