### ISSUE TITLE
Test results are silently dropped for tests that were not submitted during the discovery phase.

### ISSUE THREAD

**Issue by plioi** [Microsoft/vstest#1413]
## Description

When any test framework's ITestExecutor emits a test result by calling ITestExecutionRecorder.RecordResult(TestResult), where the TestResult's TestCase's FullyQualifiedName had *not* been similarly sent earlier during the discovery phase, the result is silently dropped.

A test framework may need to emit a result at execution time that could not have been discovered at discovery time. Instead of hiding a failure from the user, the system should be safe by default and report it to the user by including it in the results, as if it had been previously submitted during discovery.

## Steps to reproduce

For any custom test framework's integration with `dotnet test` and Test Explorer, call RecordResult for a result whose FullyQualifiedName was not submitted during the discovery phase.

## Expected behavior

The result would be included in the output.

## Actual behavior

The result is not included in the output. The following message is logged (visible in the Tests output pane when running under Test Explorer):

[2/3/2018 10:48:15 AM Error] Test adapter sent back a result for an unknown test case. Ignoring result for '*The.Fully.Qualified.Test.Name*'.

## Environment

Windows 10 Home
VS Community 2017 Version 15.5.2

**Comment by singhsarab** [comment]
@plioi This does not appear to be an issue with test platform, rather related to experience in VS IDE. Can you please raise a feedback ticket at https://developercommunity.visualstudio.com
Please close this issue once you raise the ticket.

@AbhitejJohn Just FYI.
