### ISSUE TITLE
dotnet test --blame does not work

### ISSUE THREAD

**Issue by nothrow** [Microsoft/vstest#1427]
## Description
`dotnet test --blame` does not work. 

```
root@b859639f95c8:/tmp/test# dotnet test --blame
MSBUILD : error MSB1001: Unknown switch.
Switch: --blame
```

## Steps to reproduce
- Create empty xunit project
`dotnet new xunit`
- Run test with --blame
`dotnet test --blame`

## Expected behavior
Test to run, and eventually create Sequence.xml

## Actual behavior
```
root@b859639f95c8:/tmp/test# dotnet test --blame
MSBUILD : error MSB1001: Unknown switch.
Switch: --blame
```

## Diagnostic logs
I believe this is not necessary.

## Environment
- Tested on Win10 with SDK 2.1.4
- Easiest to reproduce is on docker: `docker run -it --rm microsoft/dotnet`

```
root@b859639f95c8:/tmp/test2# dotnet --info
.NET Command Line Tools (2.1.4)

Product Information:
 Version:            2.1.4
 Commit SHA-1 hash:  5e8add2190

Runtime Environment:
 OS Name:     debian
 OS Version:  9
 OS Platform: Linux
 RID:         linux-x64
 Base Path:   /usr/share/dotnet/sdk/2.1.4/

Microsoft .NET Core Shared Framework Host

  Version  : 2.0.5
  Build    : 17373eb129b3b05aa18ece963f8795d65ef8ea54
```

**Comment by singhsarab** [comment]
@nothrow --blame option in it's current form is for figuring out the faulty test in case of abort, where the host process crashes unexpectedly.
The sequence file gets generated only in abort scenarios.
So in your case, as per the repro steps, --blame would not generate the sequence file.

**Comment by smadala** [comment]
Looks like blame changes for `dotnet test` are not in right branch of dotnet-cli.  We will fix this. Meanwhile you can use `dotnet vstest` to create sequence file.
```
PS C:\Users\samadala\tmp\mstest-sample> dotnet vstest C:\Users\samadala\tmp\mstest-sample\bin\Debug\netcoreapp1.0\mstest-sample.dll /blame
Microsoft (R) Test Execution Command Line Tool Version 15.6.0
Copyright (c) Microsoft Corporation.  All rights reserved.

Starting test execution, please wait...
The active test run was aborted. Reason: Process is terminated due to StackOverflowException.


Attachments:
  C:\Users\samadala\tmp\mstest-sample\TestResults\58f19a61-6a3b-45e7-8e2a-7a231b1a6478\Sequence.xml

Test Run Aborted.

The active Test Run was aborted because the host process exited unexpectedly while executing following test(s):
tmp.UnitTest1.TestMethod1
```

**Comment by mayankbansal018** [comment]
@nothrow , the option is available in latest dotnet sdk https://github.com/dotnet/cli/releases/tag/v2.1.300-preview2-008530 , can you please try it again.

**Comment by acesiddhu** [comment]
Closing the issue as this should work in latest dotnet sdk
