### ISSUE TITLE
The active test run was aborted: Reason: After parsing a value an unexpected character ...

### ISSUE THREAD

**Issue by davidfowl** [Microsoft/vstest#1435]
I'm seeing the following error randomly on test runs:

```
The active test run was aborted. Reason: After parsing a value an unexpected character was encountered: V. Path 'Payload.NewTestResults[4].Messages[0].Text', line 1, position 16177.
```
I can't reproduce it consistently but it would be good to get a clue of where to look. I'm using the xunit test runner implementation but I don't know where the issue might be.

**Comment by smadala** [comment]
@davidfowl  Can you please share repo url?

**Comment by davidfowl** [comment]
A bit more info:
- It seems to fail when running tests on .NET 4.6.1
- xunit vs runner 2.4.0-beta.1.build3945
- xunit 2.3.1

dotnet --info
```
.NET Command Line Tools (2.1.300-preview2-008044)

Product Information:
 Version:            2.1.300-preview2-008044
 Commit SHA-1 hash:  c22f7e29a0

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.16299
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Users\dfowler\.dotnet\x64\sdk\2.1.300-preview2-008044\

Microsoft .NET Core Shared Framework Host

  Version  : 2.1.0-preview2-26130-06
  Build    : b13a0d5c331f374afd35ded57b9a4b4ab128864c
```


The repository is here.

https://github.com/aspnet/SignalR/pull/1468  This commit https://github.com/aspnet/SignalR/tree/08cd53bc7a5c21e89a1e761893e97b6d9a561984.

run `build.cmd` this will download and bring a new version of the .NET CLI to %userprofile%\.dotnet\x64 on windows and will run all tests.

run dotnet from that folder and run it on these tests (just run dotnet test) https://github.com/aspnet/SignalR/tree/08cd53bc7a5c21e89a1e761893e97b6d9a561984/test/Microsoft.AspNetCore.SignalR.Client.FunctionalTests.

Running it several times in a row crashes for me.

**Comment by smadala** [comment]
@davidfowl Thanks for more info. Looks like info is sufficient to investigate the issue. Let us know if it is blocking you then we investigate in priority.

**Comment by smadala** [comment]
Looks like crash is due to [Newtonsoft.Json](https://stackoverflow.com/questions/43900333/after-parsing-a-value-an-unexpected-character-was-encountered-6-path-0) serialization while reporting new test results to vstest.console from testhost(Test running process). 

By error message, Newtonsoft.Json failed to serialize [Text](https://github.com/Microsoft/vstest/blob/master/src/Microsoft.TestPlatform.ObjectModel/TestResult.cs#L305).  Text is part of TestResult and represents `Console.Writeline()`, `Console.Error.WriteLine()`, `Debug.Trace()`, etc(See [Categories of Text](https://github.com/Microsoft/vstest/blob/master/src/Microsoft.TestPlatform.ObjectModel/TestResult.cs#L263)). 

Is there new `Console.Writeline()` or `Console.Error.WriteLine()` added in this [PR](https://github.com/aspnet/SignalR/pull/1468/files)?.

**Comment by davidfowl** [comment]
AFAIK nothing new was added in this PR with respect to writing out to the console.

**Comment by davidfowl** [comment]
The .NET Framework tests print to the output a lot more, and thats where it fails. Why is it failing to serialize?

**Comment by singhsarab** [comment]
We fixed a similar issue via https://github.com/Microsoft/vstest/pull/1457
The fix is available in VS 15.6.2 release and for dotnet core projects we have released nuget packages (Microsoft.Net.Test.Sdk 15.6.1)

Can you please try out these bits and tell us if this fixed the issue for you.

**Comment by davidfowl** [comment]
I'm hoping you guys re-ran the repro I gave you and confirmed the fix works right?

**Comment by davidfowl** [comment]
IIRC @smadala was able to reproduce the exact failure.

**Comment by smadala** [comment]
@davidfowl While trying to repro the issue, I have updated the Microsoft.NET.Test.Sdk to 15.6.0(it was [15.3.0](https://github.com/aspnet/SignalR/blob/08cd53bc7a5c21e89a1e761893e97b6d9a561984/build/dependencies.props#L57) in your PR, 15.6.0 has more logging), and able the repro (didn't try with 15.3.0 after that).
 
We have seen similar issue in developer community. 
https://github.com/Microsoft/vstest/pull/1457 fixed [developer community issue](https://developercommunity.visualstudio.com/content/problem/203298/156-preview-6-fails-test-adapter-run-f.html) which was introduced in Microsoft.NET.Test.Sdk 15.6.0-preview-20171211-02. 

Is there any chance you repro the issue with Microsoft.NET.Test.Sdk >= 15.6.0-preview-20171211-02? If not, I'm not sure about #1457 fixing this issue.

**Comment by smadala** [comment]
Please reopen this issue, If you see the failure again with 15.6.1.
