### ISSUE TITLE
Symbols for stepping into testhost.exe source

### ISSUE THREAD

**Issue by jnm2** [Microsoft/vstest#1439]
Do you make symbols available anywhere with each release? If not, would you consider it?

**Comment by cltshivash** [comment]
@jnm2 There was an issue with publishing portable pdbs to the symbol server. It has been fixed (to publish the full pdbs) and you should be able to use it in a week's time when the archival requests are completed., @jayaranigarg fyi.

**Comment by jnm2** [comment]
You sounds great! Just so I understand, this means I'll be able to step into the source of all the DLLs in https://www.nuget.org/packages/Microsoft.TestPlatform by including 'Microsoft Symbol Servers'?

![image](https://user-images.githubusercontent.com/8040367/36676271-3701ad1e-1ad9-11e8-89d6-085bbc5de204.png)

**Comment by jnm2** [comment]
This sounds great! Just so I understand, this means I'll be able to step into the source of all the DLLs in https://www.nuget.org/packages/Microsoft.TestPlatform by including 'Microsoft Symbol Servers'?

![image](https://user-images.githubusercontent.com/8040367/36676271-3701ad1e-1ad9-11e8-89d6-085bbc5de204.png)
