### ISSUE TITLE
UWP test app gets launched in background?

### ISSUE THREAD

**Issue by borrrden** [Microsoft/vstest#1448]
## Description
I am not sure what has triggered this to behave differently but my setup had been working fine for quite some time, and now when I launch vstest for UWP I have quite odd behavior.  The app will run tests for a while and then sit there and do nothing.  It will sit there and do nothing forever **UNLESS** I log into the machine it is running on, and click on the test runner app (thereby focusing the window that until that point was running in the background and flashing in the bottom icons in Windows).  As soon as I do that, the tests run to completion.

## Steps to reproduce
My script is very simple:
```batch
@echo off

msbuild /p:Configuration=Release /p:Platform=x64 PROJECT.csproj
vstest.console.exe /InIsolation /Platform:x64 /Framework:FrameworkUap10 bin\x64\Release\PROJECT.build.appxrecipe /Logger:trx
```

## Expected behavior
Tests should run to completion without intervention

## Actual behavior
The tests hang until UI interaction

## Diagnostic logs
I will work on getting these

## Environment
Windows 10 Fall Creator's update
vstest 15.5.0
visual studio 15.5.3
UWP 6

**Comment by cltshivash** [comment]
@borrrden : Can you try with the latest update 15.6 and let us know if the issue persists ? Are you trying to run your app in CI pipeline ?

**Comment by borrrden** [comment]
Yes, I am trying to run unit tests as part of a build / promotion pipeline.  I will upgrade to 15.6 and respond here if the issue continues.

**Comment by borrrden** [comment]
It seems to have happened again.  I tried using powershell to bring it to the front at one point, but UWP apps seem immune to the regular window focusing tactics...

**Comment by borrrden** [comment]
Yes, it is definitely still happening.  I think Jenkins is involved somehow.  If there is a powershell way to bring it to the foreground I'd like to know about it.

**Comment by smadala** [comment]
@borrrden Is this repro on local machine? 
Can you share sample repo project and diagnostics logs(/diag:log.txt)?

**Comment by borrrden** [comment]
The odd thing is that this doesn't happen on my local machine, only on the VM...but I will try getting the diagnostic log.

**Comment by smadala** [comment]
This looks like similar https://github.com/Microsoft/vstest/issues/1500. The program which launches vstest.console running as service(background program)?

**Comment by borrrden** [comment]
I'm not doing anything fancy, literally just run those three lines above on my compiled app package and the UWP window launches "behind" other things (as if I clicked away from it).

**Comment by borrrden** [comment]
P.S. It looks like it will be a while for the logs since .NET Native just barfed over the recent changes I made...

**Comment by borrrden** [comment]
Ok new information, this seems unrelated to being behind other windows or not, it seems that just logging into the machine causes the tests to resume.  Maybe related to the "display sleep" settings?  I disabled them and will let you know.

**Comment by borrrden** [comment]
It's been a while since I've seen this, so I think it was actually the machine's display going to sleep ("display" here is kind of confusing since it is in a VM which is one of several dozen running via Xen on a machine).
