### ISSUE TITLE
VsTest platform tools installer task fails: nuget.exe: invalid arguments

### ISSUE THREAD

**Issue by RuslKoval** [Microsoft/vstest#1455]
## Description
nuget.exe says "invalid arguments" 
![image](https://user-images.githubusercontent.com/23101758/36797909-defc74b6-1cb1-11e8-8d8e-99af89d25eb2.png)

## Steps to reproduce
1. Run build definition with "VsTest platform tools installer" task

## Expected behavior
> VsTest Platform will be installed on the agent

## Actual behavior
> VsTest Platform installation fails

## Diagnostic logs
[3_VsTest Platform Installer.txt](https://github.com/Microsoft/vstest/files/1767826/3_VsTest.Platform.Installer.txt)

## Environment
VSTS, Windows 10

**Comment by acesiddhu** [comment]
@RuslKoval thanks for reporting the issue. this happens because output directory has spaces in it
-OutputDirectory C:\Program Files\VSTSAgent\_work\_temp\VsTest
to workaround if the agent is configured inside a folder without any spaces this should work.
@ShreyasRmsft FYI

**Comment by ShreyasRmsft** [comment]
Fixed in the above linked PR. @RuslKoval in the next vsts-update this should work. Thank you for reporting this issue.
