### ISSUE TITLE
VSTest.Console.Exe `/Tests:` parameter matches substrings

### ISSUE THREAD

**Issue by evilC** [Microsoft/vstest#1468]
## Description
The command-line `vstest.console.exe MyTests.dll /Tests:"Add"` runs ALL TESTS that contain the word "Add".  
Furthermore, given the command-line `vstest.console.exe MyTests.dll /Tests:"ns1.ns2.c1.Add"`, the following tests would match:  
```
ns1.ns2.c1.Add
newns1.ns2.c1.Add
ns1.ns2.c1.AddSomethingElse
```

## Steps to reproduce
Create a suite with the tests `Add` and `AddThisToThat`  
Run the command-line `vstest.console.exe MyTests.dll /Tests:"Add"`  
Both tests run  

## Expected behavior
Only the specified test should run  
OR  
The [documentation](https://msdn.microsoft.com/en-us/library/jj155796.aspx) should clearly state that this is a substring.  

There also appears to be no way to force this switch to use literal names, which makes it basically useless if you want to only run specific tests.  

## Actual behavior
Both tests run

## Diagnostic logs
NA

## Environment
NA

**Comment by singhsarab** [comment]
@evilC This is by design.
@pvlakshm Pratap, we need to change the documentation as suggested.

**Comment by prawalagarwal** [comment]
@evilC Don't know if this will be helpful but you can use:
 **/TestCaseFilter:"FullyQualifiedName=Namespace.ClassName.MethodName"** in case you want to run a specific test.

**Comment by evilC** [comment]
Yes, I worked that out, I just though that the docs needed updating as it caused us quite some confusion.

**Comment by pvlakshm** [comment]
This is already done: [here](https://msdn.microsoft.com/en-CA/library/jj155796.aspx)

**Comment by evilC** [comment]
@pvlakshm I don't see it.  
The entry for `/Tests:[ test name ]` is identical to what it was before, nothing has changed.
