### ISSUE TITLE
Communication Setup overhead in testhost startup

### ISSUE THREAD

**Issue by KevinH-MS** [microsoft/vstest#1475]
## Description
> When profiling Live Unit Testing execution, it has been established that communication setup is a significant cost.

## Steps to reproduce
> Create a project with tests
> Right-click the project (in solution explorer) > Live Unit Testing > Include
> Wait for LUT glyphs to appear
> Start profiler
> Make some whitespace change
> Wait for LUT glyphs to update (no more faded "clock" glyphs)
> Stop profiler

## Expected behavior
> Setup costs should ideally be ten(s) of ms...

## Actual behavior
> Setup costs are several hundred ms...

TcpChannel setup and DefaultContractResolver.ResolveContract (Json deserializer) are two things that stand out to me...

**Comment by smadala** [comment]
@abhishkk I think you worked on this. Can you please update your finding here?

**Comment by abhishkk** [comment]
@KevinH-MS @smadala 
We will investigate Json serialization overhead and take changes for 15.8 if needed.
Letting the issue open considering it enhancement for 15.8.

**Comment by KevinH-MS** [comment]
@abhishkk @mayankbansal018 this is the other serialization library I was thinking of this morning:   https://github.com/Microsoft/bond

**Comment by singhsarab** [comment]
@genlu Are we still looking at perf improvements in this respect ?

**Comment by genlu** [comment]
FYI @AbhitejJohn @shyamnamboodiripad

**Comment by shyamnamboodiripad** [comment]
@singhsarab Any improvements we can make here would be awesome as it looks like we are paying this cost on every code change that causes tests to be executed for LUT.

It would be interesting to investigate MessagePack for serialization in TP - we are using this in other parts of our code. @AbhitejJohn had measured MessagePack v/s JsonRPC and found that to be better / faster for our uses.

cc @jfleisher @drognanar @ManishJayaswal FYI

**Comment by nohwnd** [comment]
This change would require architectural changes, and breaking changes to public API and won't be implemented, we are focusing on adding new features to Testing.Platform instead. https://aka.ms/testingplatform
