### ISSUE TITLE
Using /diag:logs/log.txt generates log.txt but not any log.host.*.txt

### ISSUE THREAD

**Issue by amanda-tarafa** [Microsoft/vstest#1479]
## Description
I've set up CI using appveyor.  On the simplest form I'm running `vstest.console.exe <test.dll> /logger:Appveyor /diag:logs\log.txt`.
`logs\log.txt` is correctly generated. But the most informative `logs\log.host.*.txt` are not.
Is there something else I need to add somewhere? 

## Steps to reproduce
I can create a simple reduced version if it turns out I'm not missing anything and this needs deeper looking at.
## Expected behavior
Both `log.txt` and `log.host.*.txt` generated. From the instructions I'm assuming that they will be generated in `logs`.

## Actual behavior
Only `log.txt` generated.

## Diagnostic logs
Precisely my problem, I don't have them, just `log.txt`

## Environment
Will share a sample project if it turns out this is not just something I'm missing.

**Comment by cltshivash** [comment]
If you don't pass /InIsolation flag the tests would be run in the vstest.console.exe process and no testhost process would be launched. Please check the log.txt you should be having the needed information.

**Comment by amanda-tarafa** [comment]
Ok, I passed /InIsolation and now I get a little more info on `log.txt`, specifically where to find `vstest.*.dmp` files. But I still don't get any `log.host.*.txt` files.
My vstes execution is crashing, probably some of my tests are making it crash, but to properly diagnose that I would like to take a look also at `log.host.*.txt`. But apparently they are not being generated.

- If they were generated, where would they be? Same folder where `log.txt` is? Somewhere else?

- Is it possible that they are not being generated because vstes crashes? Any alternative?
