### ISSUE TITLE
Follow up question from #1479

### ISSUE THREAD

**Issue by amanda-tarafa** [Microsoft/vstest#1485]
This is a follow up question to #1479.
I passed /InIsolation and now I get a little more info on `log.txt`, specifically where to find `vstest.*.dmp` files. But I still don't get any `log.host.*.txt` files.
My vstes execution is crashing, probably some of my tests are making it crash, but to properly diagnose that I would like to take a look also at `log.host.*.txt`. But apparently they are not being generated.

- If they were generated, where would they be? Same folder where `log.txt` is? Somewhere else?

- Is it possible that they are not being generated because vstes crashes? Any alternative?

**Comment by smadala** [comment]
> If they were generated, where would they be? Same folder where log.txt is? Somewhere else?

   Log.host.*.txt gets created in same folder as log.txt.

> Is it possible that they are not being generated because vstes crashes? Any alternative?

   Tests runs in testhost.exe process, log.host.*.txt created by teshost.exe, It is possible vstest.console getting crashed before launching testhost or testhost crashing before creating log file. 

Get more info from the eventviewer logs. and  [user mode full dump](https://msdn.microsoft.com/en-us/library/windows/desktop/bb787181(v=vs.85).aspx).

Share log.txt, console output and repro project with us to help you.

**Comment by amanda-tarafa** [comment]
Here's a [branch](https://github.com/amanda-tarafa/google-cloud-visualstudio/tree/vstest-diagnostics) in the repo you can take a look at.
I've fixed the tests so vstest is not crashing anymore, still, no `log.host.*.txt`.
[Here's ](https://github.com/amanda-tarafa/google-cloud-visualstudio/blob/c6dd39889faeff90b9561a8f4fd32145dac0ee71/TestScript.ps1#L21)the line where I activate diagnostics and [here's](https://ci.appveyor.com/project/amanda-tarafa/google-cloud-visualstudio/build/1.0.83-vstest-diagnostics/artifacts) a successful appveyor build, you can see in the Artifacts tab that in the `logs` folder there's just `log.txt`. [Here's ](https://github.com/amanda-tarafa/google-cloud-visualstudio/blob/c6dd39889faeff90b9561a8f4fd32145dac0ee71/appveyor.yml#L25)the line that pushes everything in `logs` folder as an artifact.
Let me know if there's something I can do.
Thanks.

**Comment by smadala** [comment]
What is VS version on build agent? 
Looks like the VS version < 15.5. That is the reason you are not seeing *host files. If you move to > VS 15.5, you can use /blame option to figure out which test is causing test-process to crash.
