### ISSUE TITLE
`VsTestConsoleWrapper.CancelDiscovery` is not implemented

### ISSUE THREAD

**Issue by genlu** [microsoft/vstest#149]
It'd be nice to be able to cancel test discovery when LUT is paused or discovery hangs due to bugs in test platform/test adapter/test framework.

Also, behavioral wise, I think it'd make sense to let `CancelDiscovery`  to immediately abort current discovery, kill testhost process and cause the call to DiscoverTests to return (with i`sAborted`set to true). @saikrishnav Does this sound reasonable?

**Comment by pvlakshm** [comment]
Closing this; reactivate if still required.

**Comment by AbhitejJohn** [comment]
I've gone ahead and reopened this issue. It would be really great to have a form of discovery cancellation where other high priority operations need to supersede a currently running potentially long discovery operation. For instance a build/rebuild/clean operation or a solution close. 

From an implementation standpoint if I understand this correctly it could probably just be killing the testhost process.

**Comment by ManishJayaswal** [comment]
@cltshivash - any update on this issue?

**Comment by cltshivash** [comment]
@ManishJayaswal The changes are in and we should be inserting the TP version with the fix for 16.3 this week.

**Comment by ManishJayaswal** [comment]
@cltshivash great to hear this!

**Comment by AbhitejJohn** [comment]
@cltshivash : I just tried this out on a solution with 100,000 MSTest tests -> Closed solution while discovery is still in progress but that did not stop the operation. It looks like we bail out from discovery between adapter calls but if an adapter is still servicing a request, there isn't a way of hard-stopping it. That's probably a change in the adapter interface but until that is fixed, we could probably use a testhost process kill similar to AbortTestRun. That should fix the scenario above for us.

**Comment by singhsarab** [comment]
This should be resolved by https://github.com/microsoft/vstest/pull/2076 and https://github.com/microsoft/vstest/pull/2134
