### ISSUE TITLE
VSTS CLOUD LOAD TEST behind Firewall

### ISSUE THREAD

**Issue by lloydmonteiro** [Microsoft/vstest#1492]
## Description
I followed this article https://blogs.msdn.microsoft.com/devops/2016/08/22/use-cloud-load-agents-on-your-infrastructure/ and successfully am able to run Load Tests using Cloud on my own machines behind Firewall. It is running fine on VisualStudio and VSTS Portal

Now I want this to also run using VSTS Release TASK and to that end I add the Cloud Load Test task. I also installed the AzurePS on the VM which initially vsts was complaining that deployment group is not provisioned.

## Steps to reproduce
I am not able to understand how the CLT in Release Pipeline mode works with "Self-Provisioned Agents" or use my RIG as I don't see an option anywhere to do that?

## Expected behavior
Option to set the "Load test rig" 

## Actual behavior
Don't know how to run CLT using Self provisioned Rig in release pipeline. Can you confirm is this supported in release pipeline? 
It is supported from VSTS IDE and VSTS Portal, however in release pipeline, CLT task??

**Comment by smadala** [comment]
This issue was moved to Microsoft/vsts-tasks#6772

**Comment by ShreyasRmsft** [comment]
@lloydmonteiro Have provided a solution in the [issue](Microsoft/vsts-tasks#6772)
