### ISSUE TITLE
REQUEST: Have a HORIZONTAL SCROLL BAR when the test names are long

### ISSUE THREAD

**Issue by PureKrome** [microsoft/vstest#1495]
Hi 👋 

Totally loving the heirachy view. Thank you!

Now, some test names move 'offscreen' because the test runner window is not big enough. When this happens, **no HORIZONTAL SCROLL BAR** appears. A vertical one does appear if the list of tests go below the window size (yay!) ... just not sideways. 

It's important because we can't see the full test name (which isn't a big deal because you can just double click on the test to auto-jump to the test) BUT if the test is a `[Theory]` (if using xUnit) then we can't see what INPUT ARGUMENTS were provided to the test, which sometimes means we need to comment out all the theories passed in and slowly turn on each one, one-by-one until we found the offending 'red' theory.

Here's a visual example about what I mean:

![image](https://user-images.githubusercontent.com/899878/37804461-77cd171c-2e88-11e8-829c-7b50276af898.png)

cc @kendrahavens 🙏 

Keep up the good work!

**Comment by smadala** [comment]
Couldn't assign to @kendrahavens. Assigning to @ManishJayaswal

**Comment by ManishJayaswal** [comment]
This is currently tracked by the following internal VS issue - (https://devdiv.visualstudio.com/DevDiv/_workitems/edit/575737)

**Comment by PureKrome** [comment]
@Sanan07 - does that mean that this is fixed?

**Comment by Sanan07** [comment]
@PureKrome Yes, that is fixed.

**Comment by PureKrome** [comment]
@Sanan07  Woot! TA! 🍰 🎉 

![](https://media.giphy.com/media/ZGHczTUuB1nw5HfFwh/giphy.gif)
