### ISSUE TITLE
dotnet test assumes output assembly is test file

### ISSUE THREAD

**Issue by paulvanbrenk** [Microsoft/vstest#1501]
I'm in the progress of making the Node Tools JavaScript unit test adapter work with different project types. One of those project types is ASP.NET Core, I specifically want to make it work with `dotnet test` to it's easy to integrate with existing build infrastructure.

One of the issues I ran into is that in the [Microsoft.TestPlatform.targets](https://github.com/Microsoft/vstest/blob/d493ee92a4bfc54f1857617a8942da6d6ea9035b/src/Microsoft.TestPlatform.Build/Microsoft.TestPlatform.targets#L34) on Line 34, the `TestFileFullPath` is hardcoded to the `$(TargetPath)` (which is the output assembly).

The way the Node Tools JavaScript unit test adapter works is, is that it reads the project file, and parses out all the `.js` and `.ts` files, and passes those to the unit test framework the user selected.

Any suggestions on how to make this work, in a forward/backward compatible way? And ideally I don't want to prevent developers from running both C#/VB and JavaScript unit tests in the same project.

One fix I can think of is the following:

```
  <PropertyGroup>
    <VSTestTaskAssemblyFile Condition="$(VSTestTaskAssemblyFile) == ''">Microsoft.TestPlatform.Build.dll</VSTestTaskAssemblyFile>
    <VSTestConsolePath Condition="$(VSTestConsolePath) == ''">$([System.IO.Path]::Combine($(MSBuildThisFileDirectory),"vstest.console.dll"))</VSTestConsolePath>
    <MSBuildAllProjects>$(MSBuildAllProjects);$(MSBuildThisFileFullPath)</MSBuildAllProjects>
    <TestFileFullPath Condition="'$(TestFileFullPath)' == ''">$(TargetPath)</TestFileFullPath>
  </PropertyGroup>

// ...

    <Microsoft.TestPlatform.Build.Tasks.VSTestTask
      TestFileFullPath="$(TestFileFullPath)"
      VSTestSetting="$(VSTestSetting)"
// ...
```

 This would allow me to set the TestFileFullPath in the properties I import with my test adapter, though this would block developers from running both any other unit tests.

**Comment by smadala** [comment]
Currently `dotnet test` supports  .NET Core and .NET Full framework tests.

For .NET Core framework tests, below is the process tree:
![processes-created-while-running-core-tests](https://user-images.githubusercontent.com/4337332/37863444-70781d02-2f84-11e8-8ebb-7d6b72777e6d.PNG)

```
"C:\Program Files\dotnet\dotnet.exe" test -f netcoreapp2.0

"dotnet.exe" exec "C:\Program Files\dotnet\sdk\2.1.100-preview-007328\MSBuild.dll" /m /v:m /nologo /t:VSTest /v:quiet /nologo /p:TargetFramework=netcoreapp2.0 "/Logger:Microsoft.DotNet.Tools.MSBuild.MSBuildLogger,C:\Program Files\dotnet\sdk\2.1.100-preview-007328\dotnet.dll"

"dotnet" exec "C:\Program Files\dotnet\sdk\2.1.100-preview-007328\vstest.console.dll" --framework:.NETCoreApp,Version=v2.0 D:\mstest-sample\bin\Debug\netcoreapp2.0\mstest-sample.dll

"C:\Program Files\dotnet\dotnet.exe" exec --runtimeconfig "D:\mstest-sample\bin\Debug\netcoreapp2.0\mstest-sample.runtimeconfig.json" --depsfile "D:\mstest-sample\bin\Debug\netcoreapp2.0\mstest-sample.deps.json" "C:\Users\samadala\.nuget\packages\microsoft.testplatform.testhost/15.5.0\lib/netstandard1.5/testhost.dll" --port 3033 --endpoint 127.0.0.1:03033 --role client --parentprocessid 28364 --telemetryoptedin false
```



For .NET Full framework tests, below is the process tree:

![processes-created-while-running-desktop-tests](https://user-images.githubusercontent.com/4337332/37863445-70ac61de-2f84-11e8-8d17-6956112df1e8.PNG)


```
"C:\Program Files\dotnet\dotnet.exe" test -f net46

"dotnet.exe" exec "C:\Program Files\dotnet\sdk\2.1.100-preview-007328\MSBuild.dll" /m /v:m /nologo /t:VSTest /v:quiet /nologo /p:TargetFramework=net46 "/Logger:Microsoft.DotNet.Tools.MSBuild.MSBuildLogger,C:\Program Files\dotnet\sdk\2.1.100-preview-007328\dotnet.dll"

"dotnet" exec "C:\Program Files\dotnet\sdk\2.1.100-preview-007328\vstest.console.dll" --testAdapterPath:D:\mstest-sample\bin\Debug\net46 --framework:.NETFramework,Version=v4.6 D:\mstest-sample\bin\Debug\net46\mstest-sample.dll

"C:\Program Files\dotnet\sdk\2.1.100-preview-007328\Extensions\..//TestHost\testhost.x86.exe"  --port 5979 --endpoint 127.0.0.1:05979 --role client --parentprocessid 10464 --telemetryoptedin false
```

Tests runs in 4th process dotnet testhost.dll(Path to this determined by mstest-sample.deps.json and mstest-sample.runtimeconfig.dev.json) for .NET Core and testhost.exe from .NET Full tests.

Your approach will work if the project is targeting .NET Full (`dotnet test` only runs `.js` or `.ts` tests in this case).

is support for both .NET Core and .NET full projects required?

What is the target framework of "Node Tools JavaScript unit test adapter" assembly?

I can think of following idea.

you can leverage [VSTestCLIRunSettings option](https://github.com/Microsoft/vstest/blob/d493ee92a4bfc54f1857617a8942da6d6ea9035b/src/Microsoft.TestPlatform.Build/Microsoft.TestPlatform.targets#L43).

Example: `dotnet test -- NodeToolsJavaScript.TestSource=D:\mstest-sample\mstest-sample.csproj`, [More details.](https://github.com/Microsoft/vstest-docs/blob/master/docs/configure.md) 

Using your adapter properties, set `VSTestCLIRunSettings`  to ` NodeToolsJavaScript.TestSource="D:\mstest-sample\mstest-sample.csproj`". 

When you adapter loads in testhost.exe or dotnet testhost.dll. these runsettings will be available to your adapter, adapter can parse the runsettings xml string, get the csproj and run the tests.

**Comment by paulvanbrenk** [comment]
> is support for both .NET Core and .NET full projects required?

yes, we want to support both ASP.NET Full and ASP.NET Core
> What is the target framework of "Node Tools JavaScript unit test adapter" assembly?

Not sure what you're question is, but we build the adapter against, .NET 4.6 and .NET Standard 1.0

I'll investigate the run settings option, but that does look promising.

**Comment by smadala** [comment]
> Not sure what you're question is, but we build the adapter against, .NET 4.6 and .NET Standard 1.0, I would expect to support an ASP.NET core application independent of which framework they target.

You answered my question. I'm surprised that you were able to build adapter with just NS1.0 APIs 😃  . Make sure you drop your adpater(should end name with *.testadapter.dll) to output directory(bin/Debug). 

>I'll investigate the run settings option, but that does look promising.

Great 👍 , We are looking forward to try this out. Please ping us once you are done with this change(best thing)/face any issue(second best thing 😃 ).

As of now there no Action from vstest. I'm closing this issue.

**Comment by paulvanbrenk** [comment]
@smadala which version of NS would you recommend, and what are the trade-offs? Depending on  a newer version would make a bunch of things easier.

**Comment by smadala** [comment]
@paulvanbrenk Depends on which processes loads your NS test adapter. For working with `dotnet test` NS1.6 is good enough to support >= .NET Core1.0.  [More details](https://github.com/dotnet/standard/blob/master/docs/versions.md)

![image](https://user-images.githubusercontent.com/4337332/38199967-34956208-36b0-11e8-9664-4f3a5a3c1992.png)

**Comment by paulvanbrenk** [comment]
@smadala I finally had a chance to look at using the `VSTestCLIRunSettings`. This works great from the command line, when you specify a runsettings file, but I haven't found a way to inject this into the process by setting a property in the project file for the project I'm targeting. Any ideas there?

**Comment by smadala** [comment]
@paulvanbrenk You can have some target like below in adapter's targets file.

```xml

<Target Name="SetNodeToolsJavaScriptTestSource" BeforeTargets="VSTest">
    <VSTestCLIRunSettings>$(VSTestCLIRunSettings);NodeToolsJavaScript.TestSource="D:\mstest-sample\mstest-sample.csproj"</VSTestCLIRunSettings>
</Target>
```
