### ISSUE TITLE
Print better message when multiple versions of same extension is found

### ISSUE THREAD

**Issue by jayaranigarg** [Microsoft/vstest#1516]
## Description
Currently, when we have multiple versions of adapter being referenced in a solution, we print following message on console : 
 
![version](https://user-images.githubusercontent.com/17309452/38019254-b68f7f3e-3294-11e8-91c2-1d6bc2da34ea.png)

File version hardly makes any sense to user. Better to print Adapter/extension version or full file path.

Additionally, also validate that same message is being propagated to TestWindow in case of IDE scenarios.(Currently, no message is printed in IDE)

## Steps to reproduce
1. Create first UnitTest Project referring 1.2.0 MSTest nuget packages
2. Add second UnitTest Project referring 1.3.0-beta2 MSTest nuget packages
3. Run tests from CLI as 
vstest.console "c:\users\jagarg\source\repos\UnitTestProject3\UnitTestProject1\bin\Debug\UnitTestProject1.dll" "c:\users\jagarg\source\repos\UnitTestProject3\UnitTestProject3\bin\Debug\UnitTestProject3.dll"

## Expected behavior
Better output message.

## Actual behavior
Shown in image above

**Comment by mayankbansal018** [comment]
Closing, as not high priority
