### ISSUE TITLE
Visual Studio doesn't remember all pinned files

### ISSUE THREAD

**Issue by trparky** [Microsoft/vstest#1530]
## Description
Visual Studio doesn't remember all pinned files.

## Steps to reproduce
> Right-click on Project and choose Properties.
> Pin Project Properties window.
> Close solution.
> Reopen solution.
> Notice that your pinned properties window isn't reopened.

## Expected behavior
> When you reopen the solution all pinned windows should be reopened.

## Actual behavior
> Not all pinned windows are reopened upon reopening solution.

**Comment by cltshivash** [comment]
@trparky : Please open this issue at https://developercommunity.visualstudio.com/
