### ISSUE TITLE
Wrong exception handling (outside of catch block) makes 2 same test results instead of single one.

### ISSUE THREAD

**Issue by asartem** [Microsoft/vstest#1531]
## Description
vstest.console.exe returns two exceptions instead of single one and that creates two test results in TFS instead of one. The problem is in wrong and to earlier exception handling. Developer may need to suppress current exception and wrap it or update exception message inside of catch block, but vstest doesn't handle the last exception, it creates 2 exceptions.

## Steps to reproduce
> What steps can reproduce the defect?

1. Create any unit test (using NUnit)
2. Add a wrap of try catch
3. Update exception inside of catch (create new instance or update _message property via reflection)
4. rethrow update exception.

         [Test]
        [KnownBugCustomCategory("16832")] // category with id of JIRA ticket
        public void CantCreateTemplateWithTheSameName()
        {
            try
            {
                throw new ArgumentNullException("some inner text for exception")
            }
            catch (Exception e)
            {
                var updatedException = WrapTestMethodException(e); // add here a message for TFS UI,  that it's a known bug and id 16832 of ticket is in JIRA. 
                Logger.Error(updatedException);
                throw updatedException;
            }
        }
5. Run throw console.

## Expected behavior
the last, wrapped exception should appear:

Failed   CantCreateTemplateWithTheSameName
Error Message: "This an old bug. JIRA ticket id is 16832. original message: some inner text for exception"

## Actual behavior
returns 2 exceptions and 2 test results:
1. with message "some inner text for exception"
2. with message updated message and JIRA id.

console output: 
"
Failed   CantCreateTemplateWithTheSameName
Error Message: "some inner text for exception"
Stack trace....
Failed   CantCreateTemplateWithTheSameName
Error Message: "This an old bug. JIRA ticket id is 16832. original message: some inner text for exception"
Stack trace....
"

## Environment
Windows 8.1 with updates
vstest.console.exe version 15.0.27323.2 for VS 2017.
NUnit 3 (latest)

Inside of VS studio vith Resharper it works correct.

I inspected BaseRunTests.cs file in sources and see in line 443 this.TestRunEventsHandler?.HandleLogMessage( 

I see that you  take original exception message and stores it. Looks like it too early and you use this outdated version of error message, instead of the latest. Because even change of exception field via reflection doesn't save situation

**Comment by acesiddhu** [comment]
@asartem as @vagisha-nidhi said I see one test result and one stack trace and exception (in latest VS). I am closing the issue for now. if you have a sample test with repro please share it with us.
