### ISSUE TITLE
VsTest Console - TestCaseFilter via filter file

### ISSUE THREAD

**Issue by bastianbrinkmann** [Microsoft/vstest#1532]
## Description
The filtering of testcases can only be performed directly in the command line (https://github.com/Microsoft/vstest-docs/blob/master/docs/filter.md).
In my use case scenario, I need to filter individual test cases by FullyQualifiedName causing the arguments to get too long for the command line (>  32,767 characters). 

It would be beneficial if it would be possible to pass the test filter via a file.

## Steps to reproduce
Build a Filter that is too long for the commandline
"C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\Common7\IDE\CommonExtensions\Microsoft\TestWindow\vstest.console.exe"
/TestCaseFilter:"FullyQualifiedName=MainProject.Test.StringHelperTest.Concat_BothNotNull|FullyQualifiedName=MainProject.Test.StringHelperTest.Add_OnlyPositives|....

## Expected behavior
Passing the TestCaseFilter via a filter file

## Actual behavior
vstest.console not executable with such a long argument

**Comment by smadala** [comment]
@bastianbrinkmann VSTest.console accepts response file. Can you try it?

Example command: `vstest.console.exe @filewithlenghty.rsp`

**Comment by AutomationTester01** [comment]
I am having the same issue with my project.
Is there some way out for this?

**Comment by nohwnd** [comment]
There is an option in runsettings: https://github.com/microsoft/vstest/issues/2273#issuecomment-595292726

Another option is using response files. They currently don't work with dotnet test and dotnet vstest, but work just fine for vstest.console. Tracking that bug here: https://github.com/microsoft/vstest/issues/3513
