### ISSUE TITLE
`FIlterOptions` is not serialized correctly when running .NET Core tests

### ISSUE THREAD

**Issue by genlu** [Microsoft/vstest#1539]
We have noticed that for .NET Core tests, when we run them using filter and a valid `FilterOptions` (through `IVsTestConsoleWrapper`, see the first screenshot below), the `FilterOptions` received on the testhost side will be `null` (see 2nd screenshot below). This doesn't happen for desktop framework tests.

Here's the internal bug tracking this
https://devdiv.visualstudio.com/DevDiv/_workitems/edit/597060

1. When TestExplorer sending run request through console wrapper:

![image](https://user-images.githubusercontent.com/788783/38578091-bd942e7e-3cb7-11e8-987e-12b4a6b67de6.png)

2. When message received and deserialized on the other side:

![image](https://user-images.githubusercontent.com/788783/38578228-29c78d3e-3cb8-11e8-8b33-1162ae4ad1d2.png)

**Comment by genlu** [comment]
FYI @ManishJayaswal

**Comment by mayankbansal018** [comment]
Fixed in VS 15.7 RTM
