### ISSUE TITLE
Allow ISettingsProvider implementation with the test adapter itself.

### ISSUE THREAD

**Issue by abhishkk** [Microsoft/vstest#1545]
**Issue**:
ITestDsicoverer, ITestExecutor are the required implementations of test adater.
ISettingsProvider is the implementation which is optional for the adapter, but is a [part](https://github.com/Microsoft/vstest-docs/blob/master/RFCs/0004-Adapter-Extensibility.md#adapter-specific-settings) of adapter extensibility.

Today we require SettingsProvider to be implemented as a separate assembly even though its part of adapter extensibility. For datacollector, loggers, its makes sense that they are not part of test adapter being totally different extension points, but same is not true for SettingsProvider.

**Expectations**:
We should allow the SettingsProvider implementation with the test adapter itself. Also update this [documentation](https://github.com/Microsoft/vstest-docs/blob/07d7d13850e44252c38684b841f2bf388998b6c5/RFCs/0004-Adapter-Extensibility.md).

**Code example**:
https://github.com/Microsoft/vstest/blob/e9a708b7c8d547283f72ede7e72f038a2ac15e64/src/Microsoft.TestPlatform.Common/SettingsProvider/SettingsProviderExtensionManager.cs#L118

https://github.com/Microsoft/vstest/blob/e9a708b7c8d547283f72ede7e72f038a2ac15e64/src/Microsoft.TestPlatform.Common/SettingsProvider/SettingsProviderExtensionManager.cs#L118

**Comment by smadala** [comment]
Will be addressed with https://github.com/Microsoft/vstest/issues/1652
