### ISSUE TITLE
Restoring NuGet "Microsoft.TestPlatform.TranslationLayer" fails for Project targeting 4.6.1

### ISSUE THREAD

**Issue by bastianbrinkmann** [Microsoft/vstest#1549]
## Description
When I try installing the NuGet Package "Microsoft.TestPlatform.TranslationLayer" (current Version: 15.7.0) in a project targeting .NET Framework 4.6.1, I get the following Error Message:

> Failed to add reference to 'System.Runtime'. Please make sure that it is in the Global Assembly Cache.

Workaround: Adding a reference to 'C:\Program Files (x86)\Reference Assemblies\Microsoft\Framework\.NETFramework\v4.6.1\Facades\System.Runtime.dll' fixes the Issue, but this does not seem to be right.

## Steps to reproduce
> What steps can reproduce the defect?
> Please share the setup, commandline for vstest.console, sample project, target
> framework etc.

## Expected behavior
> Installing NuGet "Microsoft.TestPlatform.TranslationLayer" is possible for a project targeting 4.6.1

## Actual behavior
> Installing NuGet fails

**Comment by mayankbansal018** [comment]
@bastianbrinkmann , I tried to repro this, & was successful in referencing package "Microsoft.TestPlatform.TranslationLayer" to net461 app, please see attached screenshot.

If you are stil facing this on latest VS 2015.6.6, can you please share a sample repro with us.
![translationlayerref](https://user-images.githubusercontent.com/24792973/39433111-b3ceb67e-4cb2-11e8-9e70-c280066ea19f.PNG)

**Comment by mayankbansal018** [comment]
@bastianbrinkmann , I cannot repro this currenly please reopen, & attach a sample project, if you still hit this issue.
