### ISSUE TITLE
Xamarin.Forms UI Tests cannot be run

### ISSUE THREAD

**Issue by PaulVrugt** [Microsoft/vstest#1556]
## Description
Xamarin.Forms UI Tests cannot be run. In visual studio IDE the tests show up in the test explorer, but once you try to run the tests, the test output windows shows:

------ Run test started ------
[20-Apr-18 09:50:27 Warning] No test is available in ***.dll. Make sure that test discoverer & executors are registered and platform & framework version settings are appropriate and try again.
[20-Apr-18 09:50:27 Informational] ========== Run test finished: 0 run (0:00:01.2411966) ==========

I'm using the default quickstart downloaded from:
https://developer.xamarin.com/guides/testcloud/uitest/quickstarts/android/

I've actually experimented with xamarin forms ui tests before, and had a successful test run in a project about half a year ago. Re-opening this same (unchanged) project and trying to run the tests again results in the same behavior. No tests found

## Steps to reproduce
Pre:
Visual studio 15.6.6
Included test project

Steps:
Open the solution. ([CreditCardValidator.Droid.zip](https://github.com/Microsoft/vstest/files/1931249/CreditCardValidator.Droid.zip))
Build the UITest project.
Try to execute the tests

## Expected behavior
Test should run

## Actual behavior
The test doesn't run, it states no tests are found the dll

## Diagnostic logs
[log.txt](https://github.com/Microsoft/vstest/files/1931233/log.txt)

## Environment
Visual studio 15.6.6
VSTest version 15.6.2
Windows 10

**Comment by cltshivash** [comment]
Could you please open an issue at https://developercommunity.visualstudio.com/ ?

**Comment by PaulVrugt** [comment]
@cltshivash 

Just to be sure:
I've opened an issue here, because the behavior is not specific to visual studio. Trying to run the tests from the command line (using vstest.console) results in the same issue.

**Comment by PaulVrugt** [comment]
ok never mind, I've left the project alone for a while, and now when I tried again this morning it magically worked.
