### ISSUE TITLE
Trx file generated is not beautified when opened in editor

### ISSUE THREAD

**Issue by abhishkk** [Microsoft/vstest#1561]

**Comment by cltshivash** [comment]
@abhishkk Please validate on top of https://github.com/Microsoft/vstest/pull/1521

**Comment by mayankbansal018** [comment]
@abhishkk , please provide details on expectations, also as mentioned by Shiva, can you validate whether this has been fixed as per your expectations?

**Comment by smadala** [comment]
@abhishkk Assigning to you for `No description provided.`

**Comment by abhishkk** [comment]
Resolved. PR: https://github.com/Microsoft/vstest/pull/1709
