### ISSUE TITLE
Code Coverage Excludes for Native C++ Code

### ISSUE THREAD

**Issue by ericlemes** [Microsoft/vstest#1567]
## Steps to reproduce
> What steps can reproduce the defect?

Not sure if it is a defect. May only be a question. Just run any C++ Native Source Code project, linked to any external library/header, and with the linker setup as described in https://blogs.msdn.microsoft.com/jsocha/2011/08/16/capturing-c-code-coverage-with-visual-c/.

I work for Microsoft btw (alias ercintra) and have the full example uploaded to VSTS.

In my example, I've used the command line: vstest.console.exe C:\SandBox\UnitTestFrameworkEvaluation\Debug\ExampleCode.MSTests.dll /enablecodecoverage /Settings:TestsAndCoverage.runsettings

My RunSettings file is: 

<?xml version="1.0" encoding="utf-8"?>  
<RunSettings>  
  <RunConfiguration>  
    <MaxCpuCount>1</MaxCpuCount>  
    <ResultsDirectory>.\TestResults</ResultsDirectory>  
    <TargetPlatform>x86</TargetPlatform>  
  </RunConfiguration>  
  
  <DataCollectionRunSettings>  
    <DataCollectors>  
      <DataCollector friendlyName="Code Coverage" uri="datacollector://Microsoft/CodeCoverage/2.0" assemblyQualifiedName="Microsoft.VisualStudio.Coverage.DynamicCoverageDataCollector, Microsoft.VisualStudio.TraceCollector, Version=11.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a">  
        <Configuration>  
          <CodeCoverage>  
            <ModulePaths>  
              <Exclude>  
                <ModulePath>.*CPPUnitTestFramework.*</ModulePath>  
				<ModulePath>.*examplecode.mstests.dll Microsoft*</ModulePath>
              </Exclude>  
            </ModulePaths>  
  
              
            <UseVerifiableInstrumentation>True</UseVerifiableInstrumentation>  
            <AllowLowIntegrityProcesses>True</AllowLowIntegrityProcesses>  
            <CollectFromChildProcesses>True</CollectFromChildProcesses>  
            <CollectAspDotNet>False</CollectAspDotNet>  
  
          </CodeCoverage>  
        </Configuration>  
      </DataCollector>  
  
    </DataCollectors>  
  </DataCollectionRunSettings>  
  
    
  <TestRunParameters>  
    <Parameter name="webAppUrl" value="http://localhost" />  
    <Parameter name="webAppUserName" value="Admin" />  
    <Parameter name="webAppPassword" value="Password" />  
  </TestRunParameters>  
  
    
  
    
  <MSTest>  
    <MapInconclusiveToFailed>True</MapInconclusiveToFailed>  
    <CaptureTraceOutput>false</CaptureTraceOutput>  
    <DeleteDeploymentDirectoryAfterTestRunIsComplete>False</DeleteDeploymentDirectoryAfterTestRunIsComplete>  
    <DeploymentEnabled>False</DeploymentEnabled>  
    <AssemblyResolution>  
      <Directory path="D:\myfolder\bin\" includeSubDirectories="false"/>  
    </AssemblyResolution>  
  </MSTest>  
  
</RunSettings>  

## Expected behavior
I should be able to specify a ModulePath for exclusion that allows me to exclude everything that starts with Microsoft.

## Actual behavior
I either can exclude all the examplecode.mstests.dll or anything. The screenshot here helps to understand the behaviour:

![coverage screenshot](https://user-images.githubusercontent.com/1776244/39375268-91822fa4-4a02-11e8-9603-0c97d3854664.png)

## Environment
Visual Studio 2017 Enterprise 15.6.6 Enterprise
Native C++ Code
Compiled to x86, machine running x64.

**Comment by mayankbansal018** [comment]
@ericlemes , I'm not sure what is the exact ask here, you mentioned that you would want to exclude anything that contains "Microsoft" in path, which is possible today as you can mention such modules under <Modules> <Exclude> section of code coverage configuration.

Also as per your screenshot I see only one module covered which is exam**.dll, which I suppose is what you would want.

Are you looking for a way to exclude source files , namespaces.. etc? We also support those, please [look here](https://msdn.microsoft.com/en-us/library/jj159530.aspx) for complete information on configuring codecoverage settings.

**Comment by ericlemes** [comment]
Hi @mayankbansal018 
The issue here is that because it is C++ and there are external libraries compiled and linked inside the module examplecode.mstests.dll, some namespaces which does not make sense to track coverage are being tracked. In the example above, Microsoft::VisualStudio::CppUnitTestFramework is the unit test framework compiled inside the .dll. I don't want to track that coverage, because it is not my code.
Same for fakeit.
I can exclude only the full module, which does not solve my problem.

**Comment by mayankbansal018** [comment]
@ericlemes , you can exclude functions under namespaces, by specifying then under *Function* tag of Coverage Configuration, please look at https://msdn.microsoft.com/en-us/library/jj159530.aspx, for details on how namespaces, source files, modules etc can be excluded from Coverage.

For your specific e.g. above, we already exclude "Microsoft::VisualStudio::CppUnitTestFramework" namespace by default in CodeCoverage configuration

**Comment by ericlemes** [comment]
Hi @mayankbansal018,

Thanks! That is really helpful.  But I've bumped in a new issue. 

![image](https://user-images.githubusercontent.com/1776244/39577708-f365e9a0-4ed9-11e8-99b7-d905e4fad5cc.png)

Is it possible to exclude these "static void __scr_initialize" and similar. This is not my code...

I used these expressions and they don't work:

<Function>_scrt_.*</Function>
<Function>dllmain\_.*</Function>
<Function>_IMAGE_SECTION_HEADER.*</Function>
<Function>_get_entropy.*</Function>
<Function>FakeIt.*</Function>
<Function>^static*</Function>

It is being very painful to set this up. I found odd that the code coverage setup is in the test run configuration and you have to setup files and everything. I personally found the OpenCppCoverage way easier to setup (even though still complex), and everything can be contained simply in the command line. I'm sending just in case you are interested in doing some benchmarks to simplify the whole process for C++.

Thanks for your help.

**Comment by mayankbansal018** [comment]
@ericlemes , we also control exclusion at file level, & by default we ignore certain paths for C++, e.g.  any source file from "*\\atlmfc\\.*" , "*\\vctools\\.*"   etc.. 

We will take this feedback, & try to improve the experience for C++ coverage.

**Comment by ericlemes** [comment]
Hi @mayankbansal018,

This information is very helpful. But I still didn't manage to do what I want. To clarify the use case I'm expecting is:

1) Run coverage on command line
2) Publish results on a CI tool (TeamCity and VSTS)
3) Provide reports for the developer, allowing to run specific files
4) Provide a html coverage report that can be upload to the CI tool.

So, the process using the .TestSettings and excluding by file worked fine. My problem now is that running vstest.console with /EnableCodeCoverage, does not allow me to specify where the .output coverage file will be, making very difficult to deliver step 2 of the use case, since I need somehow to figure out which the test run.

If I run CodeCoverage.exe and wraps vstest.console inside, the coverage output does not  follow the excludes used in the /Settings parameter of vstest.console.

Is there any way of setting the .coverage output file?

**Comment by ericlemes** [comment]
I'll open a new issue, since this one was closed even.
