### ISSUE TITLE
Add NUnit templates by default to dotnet test

### ISSUE THREAD

**Issue by kendrahavens** [Microsoft/vstest#1570]
## Description
Currently a user needs to run `dotnet new -i NUnit3.DotNetNew.Template`
before they run `dotnet new nunit` in order to create an NUnit project. Since mstest and xUnit templates are shipped with the dotnet cli we should also include the NUnit ones to make it easier for users to discover.

## Steps to reproduce
- Install dotnet cli
- Run `dotnet new nunit`

## Expected behavior
Create an nunit project.

## Actual behavior
Use sees no suggestion to install NUnit templates or indication that they do exist for .NET Core:
![image](https://user-images.githubusercontent.com/8293542/39441603-5481ba30-4c63-11e8-93fc-7b165a059210.png)

**Comment by cltshivash** [comment]
@kendrahavens This needs to be tracked on the dotnet core repo for templates
