### ISSUE TITLE
Code Coverage Excludes and Specifying Output File (C++ Native Code)

### ISSUE THREAD

**Issue by ericlemes** [Microsoft/vstest#1575]
Hi there,

I'm trying to use Visual Studio for code coverage, and my main use case is:

* Run coverage on command line, using the proper excludes to leave only production code coverage (ignoring libraries, runtimes, 3rd party code, etc)
* Publish results on a CI tool (TeamCity and VSTS)
* Provide reports for the developer, allowing to run specific files
* Provide a html coverage report that can be upload to the CI tool.

As pointed in another issue here (#1657), the way of specifying includes/excludes is using a .runsettings file.

My problem now is that running vstest.console with /EnableCodeCoverage, does not allow me to specify where the .output coverage file will be, making very difficult to deliver step 2 of the use case, since I need somehow to figure out the results of the test run (vstest.console will create, by default, something like TestResults\<guid>\<machinename><date>.coverage.

If I run CodeCoverage.exe wrapping vstest.console inside, the coverage output does not follow the excludes used in the /Settings parameter of vstest.console.

Is there any way of setting the .coverage output file AND applying the excludes at the same time?

**Comment by cltshivash** [comment]
@ericlemes For a single test run, there would be only one code coverage file generated that will be present in the run results directory. The results directory for a run is configurable through the runsettings file.
