### ISSUE TITLE
Unable to capture Performace counters from server machine while executing Load tests using Visual studio Team services

### ISSUE THREAD

**Issue by Praveen1im** [Microsoft/vstest#1583]
We are using Visual studio 2017 Cloud load test and self provisioned rig for running our load tests and we configured some vm's as agents under the self provisioned rig and running the load test using cloud but we are not able to capture the counters from the server machines.

Virtual machines which are acting as agents and the server machines from which we need to capture the counters are in different domain and vsts and visual studio are in different domain.

Steps to Reproduce:
1. Create a self Provisioned rig using powershell command and configure some agents under the rig using Powershell commands.
2. Create a Load test and in test settings file select Run tests using visual studio team services option.
3. In the Counter set mappings add the machine name from which we need the counters from and select specific counter.
4. In counter set portion of Load test try to add few more counters from the server machine, there is error saying cant read performance counters from the specified machine.
5. If you bypass the error and execute the test, details section of load test output window shows the following error "Load tests run using visual studio team services do not support collecting performance counters from non-agent machines. Counters will not be collected from specified machine.

![image](https://user-images.githubusercontent.com/39156811/39919219-92a5e8f6-5530-11e8-9c83-bbad0593fa17.png)

![image](https://user-images.githubusercontent.com/39156811/39919186-7c333b96-5530-11e8-9149-de0d892b0cd7.png)

![image](https://user-images.githubusercontent.com/39156811/39919254-a756c14e-5530-11e8-9015-cc65a04083c9.png)

![image](https://user-images.githubusercontent.com/39156811/39919154-64e55e9c-5530-11e8-857e-7c6069d2d0e1.png)

So please let us know how capture the performance counters from the server machines when we run the load test using Visual studio cloud load test.

**Comment by cltshivash** [comment]
@Praveen1im Thanks for reaching out and using the static agent feature. This isn't supported today. Please  open a developer community issue as the load test issues aren't tracked in this repo. Closing the issue here
