### ISSUE TITLE
Diagnostics improvement: pass testHostPath also for NoTestHostFileExist

### ISSUE THREAD

**Issue by chuanboz** [Microsoft/vstest#1585]
https://github.com/Microsoft/vstest/blob/47230ad1736246c63f476177064886c5c613ba8c/src/Microsoft.TestPlatform.TestHostProvider/Hosting/DotnetTestHostManager.cs#L229

```C#
if (this.fileHelper.Exists(testHostPath))
            {
                EqtTrace.Verbose("DotnetTestHostmanager: Full path of testhost.dll is {0}", testHostPath);
                args += " " + testHostPath.AddDoubleQuote() + " " + connectionInfo.ToCommandLineOptions();
            }
            else
            {
// below line shall pass in the testHostPath also, in additional to sourcePath for easier troubleshooting.
                string message = string.Format(CultureInfo.CurrentCulture, Resources.NoTestHostFileExist, sourcePath); 
                EqtTrace.Verbose("DotnetTestHostmanager: " + message);
                throw new FileNotFoundException(message);
            }
```

see also https://github.com/Microsoft/vstest/issues/1584, if I even have the full testHostPath, that trouble-shooting would be much easier than current error message.

**Comment by singhsarab** [comment]
testHostPath changes as the code flows. This information is available in detail in the logs using /diag option. Isn't the information provided in the logs sufficient for diagnosis ?

**Comment by chuanboz** [comment]
No, I've used /diag and checked the detail logs, still couldn't figure out what is wrong.
I finally figure out #1584 after I look into the source code of DotnetTestHostManager.cs, but we shouldn't expect every user to do so for troubleshooting, the error message here shall be improved to be more clear and actionable.

**Comment by singhsarab** [comment]
This is now fixed.
