### ISSUE TITLE
Code Coverage Excludes and Specifying Output File (C++ Native Code)

### ISSUE THREAD

**Issue by ericlemes** [microsoft/vstest#1592]
Hi,

Sorry for open a new issue, but since you closed the previous one without my confirmation that a solution was provided, I thought that would be appropriate.

In the issue #1575 you mentioned that I can specify the code coverage output in the runsettings file. Searching all the documentation I found (https://msdn.microsoft.com/en-us/library/jj155796.aspx, https://msdn.microsoft.com/en-us/library/jj635153.aspx and https://msdn.microsoft.com/en-us/library/jj159530.aspx) I couldn't find any feature that address this issue.

Unfortunately the .coverage file always generates in a new test run, new directory with a GUID plus machine name and other magic. This makes the process of automating on a CI server really complicated.

Can you confirm exactly the settings on the runsettings file that allows this to be setup? Would be good to add that in the documentation as well.

**Comment by smadala** [comment]
@ericlemes Apologies for delay in response.

Currently there is no way to create .coverage file in specific location. 
Can you consider using `trx` logger? which can be used to get the coverage file [programatically](https://github.com/Microsoft/vstest/blob/master/test/Microsoft.TestPlatform.AcceptanceTests/CodeCoverageTests.cs#L151). 

**Example command**
`C:\Path\to\vstest.console.exe "D:\Path\to\test-assembly.dll"  /logger:"trx;logfilename=E:\path\to\test-results.trx" /collect:"Code Coverage"`

[VSTS](https://docs.microsoft.com/en-us/vsts/pipelines/tasks/test/publish-test-results?view=vsts) and [TeamCity](https://confluence.jetbrains.com/display/TCD10/XML+Report+Processing) support trx file for test/code coverage report.

**Comment by ericlemes** [comment]
Hi @smadala thanks for the response. I noticed that and that's why sometimes using the code coverage tool in Visual Studio is quite discouraging. Most of the operations that are achieved with a single command line in most coverage tools in all platforms needs to be scripted here. Also I found the lack of local coverage reports and speed quite poor.

Here is a snapshot of my MSBuild file to run what I run with a single command line in OpenCppCoverage:

The only extra bit is the report generator, which I need to use a 3rd party.

```

	<Target Name="RunTestsWithVSCoverage">		
		<RemoveDir Directories="$(MSBuildProjectDirectory)\TestResults" />
		<RemoveDir Directories="$(MSBuildProjectDirectory)\CoverageReport" />
		<Exec Command="$(VSTestLocation) /Settings:$(MSBuildProjectDirectory)\TestsAndCoverage.runsettings /ResultsDirectory:$(MSBuildProjectDirectory)\TestResults /logger:trx;LogFileName=Results.trx /EnableCodeCoverage $(TestProjects)  " />
		<CallTarget Targets="GenerateVSCoverageReport" />
	</Target>
	
	<Target Name="GenerateVSCoverageReport">
		<ItemGroup>
			<CoverageReport Include="$(MSBuildProjectDirectory)\TestResults\**\*.coverage" Exclude="$(MSBuildProjectDirectory)\TestResults\**\In\**\*.*" />
		</ItemGroup>
		<Copy SourceFiles="@(CoverageReport)" DestinationFiles="$(MSBuildProjectDirectory)\TestResults\Code.coverage" />		
		<Exec WorkingDirectory="$(MSBuildProjectDirectory)" Command="$(CodeCoverageLocation) analyze /output:TestResults\CoverageReport.xml TestResults\Code.coverage" />
		<Message Text="Converting @(CoverageReport) to HTML report" />
		<Exec WorkingDirectory="$(MSBuildProjectDirectory)" Command="$(ReportGeneratorLocation) -reports:TestResults\CoverageReport.xml -targetdir:CoverageReport -reporttypes:Html"  />
	</Target>
```

If VS team is interested in improving these things, please don't hesitate to contact me. My alias is ercintra. I have big code bases and I'm experimenting with a lot of different test tools and frameworks and having interesting results.

**Comment by pvlakshm** [comment]
**>> If VS team is interested in improving these things, please don't hesitate to contact me.**
@ericlemes, Yes we are interested.
What are the painpoints you would like to see us address first?
Can you try out the tool on your codebases and let me know how it fares.
Thank you.

**Comment by ericlemes** [comment]
Hi @pvlakshm,

I think the first thing is to simplify the command line exclusions, without needing to write a script to run tests + coverage. Personally I think everything you do in .testsettings should be doable by command line, which is the current "standard" for devops/build automation.

Other things, I'd rather take offline because I have some information I can't disclose here. If you can contact me in my internal e-mail (Microsoft Alias ercintra), I can give you more information.

**Comment by pvlakshm** [comment]
We will take this up for consideration in the next round of planning (for Q4 onwards).
