### ISSUE TITLE
Use MEF for discovering ITestExplorerServiceClient...

### ISSUE THREAD

**Issue by KevinH-MS** [Microsoft/vstest#160]
I've added code to the dll that defines our `ITestExplorerServiceClient` that depends on Microsoft.VisualStudio.TestPlatform.ObjectModel.dll.  This results in a `MissingMethodException` in `LiveUnitTestingClientProvider.InitializeTestExtension` because the call to `Assembly.LoadFrom` will find the object model dll on the probing path (see "The LoadFrom method has the following disadvantages" ... at https://msdn.microsoft.com/en-us/library/1009fa28(v=vs.110).aspx).

Also, it seems less than ideal to be materializing reflection info for all the types in the assembly every time we initialize the extension.  An alternative would be to just use VS MEF.

**Comment by snkota** [comment]
This is being tracked external to this repo here:
https://developercommunity.visualstudio.com/content/problem/145936/use-mef-for-discovering-itestexplorerserviceclient.html
