### ISSUE TITLE
So what, exactly, is the default console logger verbosity, and what should it be?

### ISSUE THREAD

**Issue by IanKemp** [Microsoft/vstest#1606]
Environment: Visual Studio 2017 Enterprise 15.7.1, Windows 10 1803 (OS Build 17134.48) x64

There are various issues and PRs floating around that set the console logger's verbosity to `normal` or `minimal`. From what I understand, the default **is intended to be** `minimal`, but this breaks the workflow of many users who are expecting `normal` as the default. So right now I'm not sure what the default is, especially since it doesn't seem to be documented anywhere (the only official page that a Google search for "vstest verbosity" turns up is [this one](https://msdn.microsoft.com/en-us/library/jj155796.aspx) which is for VS2012).

The reason I ask is that #1321 suggests that the correct default is/should be `minimal`, but when I run `vstest.console.exe /?` I get the following output:

```
Microsoft (R) Test Execution Command Line Tool Version 15.7.1

...

--logger|/logger:<Logger Uri/FriendlyName>
      ...

      Change the verbosity level in log messages for console logger as shown below
      Example: /logger:console;verbosity=<Defaults to "normal">
      Allowed values for verbosity: quiet, minimal, normal and detailed.

      ...
```

Note the `<Defaults to "normal">` line above, which I would expect to be `<Defaults to "minimal">` based on the above issue and its associated PR.

Another question: why are there two versions of `vstest.console.exe` in my Visual Studio 2017 directory? I have one in `\Common7\IDE\CommonExtensions\Microsoft\TestWindow` (which seems to be the correct version) and another in `\Common7\IDE\Extensions\TestPlatform` which seems to be an old version.

**Comment by IanKemp** [comment]
Nobody?

**Comment by singhsarab** [comment]
@IanKemp 
1. Regarding verbosity
a. For vstest.console, the default verbosity is normal and that's what the help docs say today (fixed via the PR you have pointed to)
b. If you use dotnet test, then the default verbosity is minimal.

2. Regarding 2 versions of vstest.console
a.  `\Common7\IDE\CommonExtensions\Microsoft\TestWindow` has older platform and will go away in the next major release.
b. `\Common7\IDE\Extensions\TestPlatform` contains the new test platform, open source and crossplat.

**Comment by IanKemp** [comment]
@singhsarab Thank you very much, that tells me exactly what I need to know :).
