### ISSUE TITLE
vsTest is hung after running all tests.

### ISSUE THREAD

**Issue by pMaske** [Microsoft/vstest#1611]
Hello @mayankbansal018 , 
Very recently we have started seeing vstest command hangs after running all tests. It appears to hang at the very end tail of the  process, almost like at the time of reporting how many tests passed/failed.
OR sometimes vstest process will abort in the middle of running tests, the message is " vstest process aborted and reason is blank.
Any ideas what could be wrong here. I have attached the diagnostics file. I can find any obvious glitch.

## Steps to reproduce
- I run following command 
`C:\>vstest.console "E:/GitRepos/output/windesktop_AnyCPU_debug/bin/Esri.ArcGISRuntime.Tests.dll" /Logger:trx;LogFileName=C:/Scrapeit/TestResults/WhatIsthis.trx --diag:C:/Scrapeit/TestResults/Diagnosticlog.txt /blame`
- .Net Framework is 4.6.1

## Expected behavior
Test runs to complete and report results.

## Actual behavior
> What is the behavior observed?
vstest test process is hung and had to be killed eventually.

## Diagnostic logs
[Diagnosticlog.zip](https://github.com/Microsoft/vstest/files/2024120/Diagnosticlog.zip)
> Please share test platform diagnostics logs. Instructions to collect logs are [here](https://github.com/Microsoft/vstest-docs/blob/master/docs/diagnose.md#test-platform-diagnostics).  
> The logs may contain test assembly paths, kindly review and mask those before sharing.

## Environment
Visual Studio 15.6
Windows 10 ( 1709), OS build 16299.371
![image](https://user-images.githubusercontent.com/3878047/40330995-c260b14a-5d03-11e8-8239-c94b805ebbb4.png)

**Comment by pMaske** [comment]
Another set of logs files when the process stats are not generated and process is hung..
[2063_2018-05-21_17-03-15log.zip](https://github.com/Microsoft/vstest/files/2028114/2063_2018-05-21_17-03-15log.zip)

**Comment by singhsarab** [comment]
@pMaske In case the process hangs, Can you try creating a dump and see where it is stuck ? You can share the dumps with us to take a look.
You can also try setting test case level timeout for your tests, the long running test responsible for hang will timeout.

**Comment by pMaske** [comment]
@singhsarab , thanks for following up. I was unable to get any info on which test were causing the hang. So I went by what changes were made to the API since the tests started hanging and trailed down new tests added and commented tests that I suspected would be the reason. There were couple tests with an async call that never returned. Whilst the all tests ran and completed but probably a thread from that unreturned call was holding the vstest process to finish. It was a tough find. I hope there was a more straightforward way troubleshooting such scenarios or cases that are causing the hang, especially with async calls in unit test. But for now the problem is solved.

**Comment by singhsarab** [comment]
@pMaske Thanks. Good to know that your issue is now resolved. I will close the issue.
Hangs like these are hard, creating a dump and identifying what state the process is in a way to diagnose.

@mayankbansal018 @smadala Let's take a note, we need to re-think about these hang cases related to async tests and see if we add more diagnostics for user.

**Comment by smadala** [comment]
@pMaske Can you please share sample repro for behavior you faced?

**Comment by pMaske** [comment]
@smadala not sure if I can easily. There was a bug in our API that was causing a hang. The flows was: async method in API calls into our c-api native method that threw an exception because of which handler was not getting released and await in API call didn't return. The unit test method had that await async call and hence hung up the entire process.
