### ISSUE TITLE
Cannot run tests with Fakes

### ISSUE THREAD

**Issue by liangdaxian** [Microsoft/vstest#1616]
## Description
> **IMPORTANT**: if the defect is reproduced only in a workflow from within the Visual Studio IDE then do not report the issue here - instead, please report it using Visual Studio's "Send Feedback" option that can be accessed from the Help menu OR using this link https://developercommunity.visualstudio.com.
>
> For a defect reproducable from the vstest command line, describe the issue you've observed.

i have a machine which uninstalled all visualstuido- want to simulate real testing environment, and i was using 15.7.2 nuget package version, the cmd used to run the tests is simple:
D:\NugetCache\Microsoft.TestPlatform.15.7.2\tools\net451\Common7\IDE\Extensions\TestPlatform\vstest.console.exe path_to_the_test_dll

Error Message:
 Class Initialization method Microsoft.SharePoint.UnitTests.ClientSideFramework.SPClientSideDevCookieDebugComponentProviderTest.ClassInit threw exception. Microsoft.QualityTools.Testing.Fakes.UnitTestIsolation.UnitTestIsolationException: Microsoft.QualityTools.Testing.Fakes.UnitTestIsolation.UnitTestIsolationException: **Failed to resolve profiler path from COR_PROFILER_PATH and COR_PROFILER environment variables..**
Stack Trace:
   at Microsoft.QualityTools.Testing.Fakes.UnitTestIsolation.IntelliTraceInstrumentationProvider.ResolveProfilerPath()
   at Microsoft.QualityTools.Testing.Fakes.UnitTestIsolation.IntelliTraceInstrumentationProvider.Initialize()
   at Microsoft.QualityTools.Testing.Fakes.UnitTestIsolation.UnitTestIsolationRuntime.InitializeUnitTestIsolationInstrumentationProvider()
   at Microsoft.QualityTools.Testing.Fakes.Shims.ShimRuntime.CreateContext()
   at Microsoft.QualityTools.Testing.Fakes.ShimsContext.Create()
   at Microsoft.SharePoint.UnitTests.ClientSideFramework.SPClientSideDevCookieDebugComponentProviderTest.ClassInit(TestContext context) in d:\Office\dev\sts\stsom\ClientSideComponent\UnitTests\SPClientSideDevCookieDebugComponentProviderTest.cs:line 18

## Steps to reproduce
> What steps can reproduce the defect?
> Please share the setup, commandline for vstest.console, sample project, target
> framework etc.

1. build a test dll with fakes, the version Microsoft.QualityTools.Testing.Fakes.dll we are using is 12.0.21005.1
2. writing tests, build the dll and then trigger the vstest.console

## Expected behavior
> Share the expected output
the tests should run correctly.
## Actual behavior
> What is the behavior observed?
exceptions was throw.
## Diagnostic logs
> Please share test platform diagnostics logs. Instructions to collect logs are [here](https://github.com/Microsoft/vstest-docs/blob/master/docs/diagnose.md#test-platform-diagnostics).  
> The logs may contain test assembly paths, kindly review and mask those before sharing.

## Environment
> Please share additional details about the test environment.
> Operating system, Build version of vstest.console

**Comment by singhsarab** [comment]
@liangdaxian 
Prerequisite for using any of the datacollectors (fakes, code coverage etc) with xcopyable package is to set the following environment variables for profiler paths.

In your case, set the paths as follows
`set COR_PROFILER_PATH_32=D:\NugetCache\Microsoft.TestPlatform.15.7.2\tools\net451\Common7\IDE\CommonExtensions\Microsoft\IntelliTrace\Microsoft.IntelliTrace.Profiler.dll`
`set COR_PROFILER_PATH_64=D:\NugetCache\Microsoft.TestPlatform.15.7.2\tools\net451\Common7\IDE\CommonExtensions\Microsoft\IntelliTrace\x64\Microsoft.IntelliTrace.Profiler.dll`

Apologies for the inconvenience. We are planning to document this soon.

**Comment by acesiddhu** [comment]
@liangdaxian I am closing the issue for now. Please let us know if you are still facing the issue.

**Comment by oscarcabrero** [comment]
this did not solve the problem for me

**Comment by mayankbansal018** [comment]
@oscarcabrero , any update on this? is your issue resolved

**Comment by mayankbansal018** [comment]
@oscarcabrero, pinging again

**Comment by yukia-yuqin** [comment]
any update on this? I am facing the same issue.

**Comment by mayankbansal018** [comment]
@yukia-yuqin , can you please file a new bug for the exact issue you are facing.
