### ISSUE TITLE
Create a testadapter to target .NET Core / .NET Standard

### ISSUE THREAD

**Issue by paulvanbrenk** [Microsoft/vstest#1633]
I'm working on creating a test adapter which should work with .NET Framework 4.5.x, .NET Standard 1.6, and .NET Core 1.0, but I have trouble getting the test adapter to even run in most cases. 

I use the following command line to run the tests:

```
dotnet test -a:<path to testadapter>
```

The only case I can get this to work if when the assembly containing the tests targets net461, in all other cases the output is the following (I have added the nuget package to the project, which doesn't make a difference):
```
System.IO.FileNotFoundException: Unable to find tests for d:\tmp\source\repos\ClassLibrary1\ClassLibrary1\bin\Debug\netstandard16\MSFT.VS.NodeTools.dll. Make sure test project has a nuget reference of package "Microsoft.NET.Test.Sdk" and framework version settings are appropriate. Rerun with /diag option to diagnose further.
   at Microsoft.VisualStudio.TestPlatform.CrossPlatEngine.Hosting.DotnetTestHostManager.GetTestHostProcessStartInfo(IEnumerable`1 sources, IDictionary`2 environmentVariables, TestRunnerConnectionInfo connectionInfo)
   at Microsoft.VisualStudio.TestPlatform.CrossPlatEngine.Client.ProxyOperationManager.SetupChannel(IEnumerable`1 sources)
   at Microsoft.VisualStudio.TestPlatform.CrossPlatEngine.Client.ProxyExecutionManager.StartTestRun(TestRunCriteria testRunCriteria, ITestRunEventsHandler eventHandler)

Test Run Aborted.
```

Any ideas?

```cshap
    [FileExtension(".dll")]
    [DefaultExecutorUri("executor://JavaScriptExecutor")]
    public class ShimTestDiscoverer : ITestDiscoverer
    {
        public void DiscoverTests(IEnumerable<string> sources, IDiscoveryContext discoveryContext, IMessageLogger logger, ITestCaseDiscoverySink discoverySink)
        {
            logger.SendMessage(TestMessageLevel.Informational, "DiscoverTests");
        }
    }

    [ExtensionUri("executor://JavaScriptExecutor")]
    public class ShimTestExecutor : ITestExecutor
    {
        public void Cancel()
        {
        }

        public void RunTests(IEnumerable<TestCase> tests, IRunContext runContext, IFrameworkHandle frameworkHandle)
        {
            var settings = runContext.RunSettings.SettingsXml;
            frameworkHandle.SendMessage(TestMessageLevel.Informational, "RunTests");
        }

        public void RunTests(IEnumerable<string> sources, IRunContext runContext, IFrameworkHandle frameworkHandle)
        {
            var settings = runContext.RunSettings.SettingsXml;
            frameworkHandle.SendMessage(TestMessageLevel.Informational, "RunTests");
        }
    }
```

**Comment by singhsarab** [comment]
@paulvanbrenk Can you share your test project?
Inside the output folder for the netcoreapp1.0, please check if *deps.json file is present.

Also try running with /diag option and share the logs.

**Comment by paulvanbrenk** [comment]
This repo should contain everything you need to reproduce. https://github.com/paulvanbrenk/githubtestadapter


The log files are in the root.

**Comment by smadala** [comment]
@paulvanbrenk TestAdapter assembly should be present in same directory as tests-source assembly for .NET Core. This was enforced in .NET Core tests to make test adapter discover ability easy.  After adding below patch test adapter getting used. 

```diff
diff --git a/UnitTestProject/UnitTestProject.csproj b/UnitTestProject/UnitTestProject.csproj
index 625393a..dcd82b5 100644
--- a/UnitTestProject/UnitTestProject.csproj
+++ b/UnitTestProject/UnitTestProject.csproj
@@ -12,4 +12,12 @@
     <PackageReference Include="MSTest.TestFramework" Version="1.2.1" />
   </ItemGroup>

+  <ItemGroup>
+    <ProjectReference Include="..\CoreTestAdapter\CoreTestAdapter.csproj" />
+  </ItemGroup>
+
+  <ItemGroup>
+    <Service Include="{82a7f48d-3b50-4b1e-b82e-3ada8210c358}" />
+  </ItemGroup>
+
 </Project>
```

```ps
PS D:\g\public\githubtestadapter\UnitTestProject> dotnet test
Build started, please wait...
Build completed.

Test run for D:\g\public\githubtestadapter\UnitTestProject\bin\Debug\netcoreapp1.0\UnitTestProject.dll(.NETCoreApp,Version=v1.0)
Microsoft (R) Test Execution Command Line Tool Version 15.8.0-preview-20180510-03
Copyright (c) Microsoft Corporation.  All rights reserved.

Starting test execution, please wait...
RunTests

Total tests: 1. Passed: 1. Failed: 0. Skipped: 0.
Test Run Failed.
Test execution time: 1.4522 Seconds
```

[This is how](https://github.com/Microsoft/testfx/blob/master/src/Adapter/Build/NetCore/MSTest.TestAdapter.props#L2) MSTestV2 adapter copies the test adapter to test project output directory.

**Comment by paulvanbrenk** [comment]
that explains a lot... so the `-a, --test-adapter-path <ADAPTER_PATH>   The path to the custom adapters to use for the test run.`  command line option doesn't so anything. (I can file a bug for that).

**Comment by smadala** [comment]
I think for historical reasons `--test-adapter-path` is the only way to pass any custom vstest-extensions(Datacollectors, Loggers, TestAdapters, RuntimeHost, etc..). In .NET Core case you can use `--test-adapter-path` to pass other extensions path but not test-adapter.

There has been debate about adding `extension-path` which makes more sense. Please file a separate issue for that we will try to fix the confusion.

**Comment by smadala** [comment]
@paulvanbrenk Created https://github.com/Microsoft/vstest/issues/1648 to follow upon this.
