### ISSUE TITLE
VsTestPlatform fails to initialize trx logger when ResultDirectory is passed empty in the runsettings

### ISSUE THREAD

**Issue by ShreyasRmsft** [Microsoft/vstest#1634]
```
<?xml version="1.0" encoding="utf-8"?>
<RunSettings>
  <RunConfiguration>
    <MaxCpuCount>0</MaxCpuCount>
    <ResultsDirectory />
  </RunConfiguration>
</RunSettings>
```

Commandline:
vstest.console.exe "C:\AgentSmith133\_work\r7\a\_shrer tia fix\drop\NewBuildSample\UnitTestProject1\bin\Release\UnitTestProject1.dll" /Settings:"C:\Users\shrer\AppData\Local\Temp\tmp860.tmp" /InIsolation /Logger:"trx" /TestAdapterPath:"C:\AgentSmith133\_work\r7\a" /Diag:"C:\AgentSmith133\_work\_temp\Attempt-0_393feea1-7e2b-44e8-8689-f31778f4b052.diag"

Logs:
Microsoft (R) Test Execution Command Line Tool Version 15.8.0-preview-20180510-03
Copyright (c) Microsoft Corporation.  All rights reserved.

Starting test execution, please wait...
Logging Vstest Diagnostics in file: C:\AgentSmith133\_work\_temp\Attempt-0_393feea1-7e2b-44e8-8689-f31778f4b052.diag
Could not find a test logger with AssemblyQualifiedName, URI or FriendlyName 'trx'.

Diag Logs don't have anymore useful info. repro is simple enough. Not providing sample solution.

**Comment by smadala** [comment]
@ShreyasRmsft I'm assigning this to you. Create a PR to fix this when you get chance.

**Comment by smadala** [comment]
Fixed via https://github.com/Microsoft/vstest/pull/1674
