### ISSUE TITLE
VSTS Platform installer on a machine not connected to the internet

### ISSUE THREAD

**Issue by MagnusTim** [Microsoft/vstest#1641]
## Description
I am trying to install the VTest platform installer to get the vstest demand satisfied on a machine in a deployment group. The machine does not have access to the internet and cant access Nuget.org and fails. Is there a way to download the package locally or the specify out internal Nuget instead?

## Steps to reproduce
Use the VsTest Platform installer on a machine not connected to the internet.

## Diagnostic logs
2018-06-11T11:28:22.7721611Z Feeds used:
2018-06-11T11:28:22.7722801Z   https://api.nuget.org/v3/index.json
2018-06-11T11:28:22.7723844Z 
2018-06-11T11:28:22.7724549Z 
2018-06-11T11:28:22.7725017Z 
2018-06-11T11:28:22.7725324Z Attempting to gather dependency information for package 'Microsoft.TestPlatform.15.7.2' with respect to project 'D:\vstsagent\A1\_work\_temp\VsTest', targeting 'Any,Version=v0.0'
2018-06-11T11:28:22.8412685Z Unable to load the service index for source https://api.nuget.org/v3/index.json.
2018-06-11T11:28:22.8414486Z   An error occurred while sending the request.
2018-06-11T11:28:22.8415729Z   The remote name could not be resolved: 'api.nuget.org'

## Environment
TFS 2018.2, Windows 2016

**Comment by ShreyasRmsft** [comment]
@MagnusTim Offline support for VsTest Platform Installer is in our back log and we will be picking it up soon. But it will probably only be available in TFS 2019.

@PBoraMSFT for more details.

**Comment by ShreyasRmsft** [comment]
@MagnusTim sadly there's no recommended way for acquiring the platform without internet connectivity :(

**Comment by PBoraMSFT** [comment]
@MagnusTim - as Shreyas mentioned, support for "not connected" agents will be picked up for implementation soon. Until then, the only way to get VSTest capability for agents that are not connected to the internet is through a full VS install.

**Comment by ShreyasRmsft** [comment]
Closing this issue. Hope that a clear resolution was provided.

**Comment by MagnusTim** [comment]
OK, tanks.

/Magnus

Från: Prachi Bora <notifications@github.com>
Skickat: den 13 juni 2018 12:13
Till: Microsoft/vstest <vstest@noreply.github.com>
Kopia: Magnus <magnus@timner.se>; Mention <mention@noreply.github.com>
Ämne: Re: [Microsoft/vstest] VSTS Platform installer on a machine not connected to the internet (#1641)


@MagnusTim<https://github.com/MagnusTim> - as Shreyas mentioned, support for "not connected" agents will be picked up for implementation soon. Until then, the only way to get VSTest capability for agents that are not connected to the internet is through a full VS install.
