### ISSUE TITLE
Ngen: default /ExeConfig value for testhost.x86.exe causes error

### ISSUE THREAD

**Issue by idontknowwhY666** [microsoft/vstest#1647]
## Description
During repeated installation of VS2017 I received error

06/12/2018 16:59:23.881 [5988]: Command line: C:\Windows\Microsoft.NET\Framework\v4.0.30319\ngen.exe eqi 0 
06/12/2018 16:59:23.887 [5988]: Executing command from offline queue: install "C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\Common7\IDE\Extensions\TestPlatform\testhost.x86.exe" /NoDependencies /ExeConfig:"..\..\..\artifacts\release\net451\win7-x64\testhost.x86.exe" /queue:1
06/12/2018 16:59:23.887 [5988]: Error: The specified file or directory "..\..\..\artifacts\release\net451\win7-x64\testhost.x86.exe" is invalid.

I haven't mentioned folder at all. Does it relate to https://github.com/Microsoft/vstest/pull/1452 ?

Solution seems to be modification to:
install "C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\Common7\IDE\Extensions\TestPlatform\testhost.x86.exe" /NoDependencies /ExeConfig:"C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\Common7\IDE\vsn.exe" /queue:3

Can you change it in default?

env.:
Microsoft Visual Studio Enterprise 2017 ver 15.7.3 (27703.2026)
.NET Framework ver 4.7.02558
on fully updated Windows Server 2008 R2 Enterprise SP1 (64b)
[ngen.log](https://github.com/Microsoft/vstest/files/2102650/ngen.log)

**Comment by smadala** [comment]
> Can you change it in default?
From logs looks like only testhost.exe is on queue 1. I think we should reduce the priority.

@idontknowwhY666 Feel free to create PR for this?

**Comment by idontknowwhY666** [comment]
hi smadala, I guess the main issue is where comes '/ExeConfig:"......\artifacts\release\net451\win7-x64\testhost.x86.exe' from...mainly this part needs to be changed

**Comment by smadala** [comment]
@idontknowwhY666 I read your original issue again.

 Yes, Looks like we have to fix value for `ExeConfig`.

I'm not sure how the `..\..\..\artifacts\release\net451\win7-x64\testhost.x86.exe` ended up for ExeConfig value which is looks a lot like path to testhostx86.exe in CI build system.

Can share details steps how to repro the issue?


>I haven't mentioned folder at all. Does it relate to #1452 ?

Yes

@abhishkk  Can you look into this?

**Comment by idontknowwhY666** [comment]
Can share details steps how to repro the issue?

>> this issue appears always as I try to install the Microsoft Visual Studio Enterprise 2017 ver 15.7.3 (27703.2026) ...I 'fixed' this way I used older ver 15.0.x...installation details you can see in the above attached ngen.log

**Comment by idontknowwhY666** [comment]
hi, could be fixed in an upcoming preview of Visual Studio 15.8.Preview4?

**Comment by vagisha-nidhi** [comment]
Thank you for your feedback.
We will get this fix in upcoming Visual Studio 16.0.

**Comment by idontknowwhY666** [comment]
Hello, really cannot be fixed already in 15.9.x? Has been reported in June...can confirm error persists with 15.9.28307.145. I guess it is not so big change...thank you for feedback.

**Comment by idontknowwhY666** [comment]
-

**Comment by cltshivash** [comment]
@idontknowwhY666 Do you still see this issue ? Can you share the details on the installation being done (scripts) ? We haven't heard this issue anywhere else.

**Comment by singhsarab** [comment]
@idontknowwhY666 Apologies for the delay in getting back this. Can you please revert back?
