### ISSUE TITLE
Failed to set up the execution context to run the test

### ISSUE THREAD

**Issue by Owen-Mak** [Microsoft/vstest#1657]
## Description
If we run vstest.console.exe on two production dlls, A.dll and B.dll, all the tests in B.dll will fail with error message "Failed to set up the execution context to run the test".  

However, if we specify B.dll before A.dll in the command line, all tests run fine (i.e. specifying "A.dll B.dll" in vstest.console.exe produces the error, but specifying "B.dll A.dll" does not).

It's worth noting that B.dll loads A.dll.  It seems as if vstest.console.exe does not unload A.dll by the time B.dll tries to load A.dll. Is there a way to ensure A.dll is unloaded through settings?

We tried using the /parallel option, which works for a small number of files, but since we have over 80 dlls, we have noticed that the problem resurfaces occasionally.

## Steps to reproduce
 Run the following command (B.dll loads A.dll):
`vstest.console.exe A.dll B.dll /platform:x86 /UseVsixExtensions:true /inIsolation` 
 Framework: .NET Framework 4.0

## Expected behavior
All tests in A.dll and B.dll run without issue.

## Actual behavior
All tests in B.dll fail with error message "Failed to set up the execution context to run the test".

## Environment
Microsoft (R) Test Execution Command Line Tool Version 15.5.1
Windows 10
Visual Studio 15.5.7

**Comment by smadala** [comment]
@Owen-Mak Thanks for creating issue.

>It's worth noting that B.dll loads A.dll. It seems as if vstest.console.exe does not unload A.dll by the time B.dll tries to load A.dll. Is there a way to ensure A.dll is unloaded through settings?

This is very important information. Yes, VSTest.console loads both the dlls in same process. With `/parallel` option it creates pool of test-processes(testhost.x86.exe) depending on number of cores and reuses it for all the 80 assemblies. As there is a chance to both A.dll and B.dll goes same test-process, you will hit the issue randomly. 

Currently there is a way you can specify launch separate test-process for each assembly by using below command(`-- RunConfiguration.DisableAppDomain=true` should be at the end of command).

 `vstest.console.exe A.dll B.dll /platform:x86 /UseVsixExtensions:true -- RunConfiguration.DisableAppDomain=true`

I think this should solve the issue. If not please share sample repro project over github?

**Comment by smadala** [comment]
I'm assuming above comment helped you address the issue. Closing the issue, Feel free to ping again if issue not resolved.
