### ISSUE TITLE
Support wildcards in filenames for vstest.console.exe

### ISSUE THREAD

**Issue by nphmuller** [microsoft/vstest#1663]
## Description
I'm using dotnet cli extensively and (almost) all commands have wildcard support. (dotnet restore, build, test, etc). It would be great to be able to do 
`vstest.console.exe /path/to/project/tests/**.Tests/**/*.Tests.dll`. 
Or in my case `dotnet vstest  /path/to/project/tests/**.Tests/**/*.Tests.dll`.

**Comment by pvlakshm** [comment]
Indeed, if we were to support wildcards in filenames, it will need to be supported uniformly by `vstest.console.exe`,  `dotnet test`, and `dotnet vstest`.

**Comment by acesiddhu** [comment]
@vagisha-nidhi is this done. I see that there was a PR above that was merged with this support

**Comment by vagisha-nidhi** [comment]
@acesiddhu Yes this is complete

**Comment by nphmuller** [comment]
@vagisha-nidhi Do you perhaps now in which version this improvement has been included?

**Comment by vagisha-nidhi** [comment]
@nphmuller Here is the latest version that is released https://github.com/microsoft/vstest/releases/tag/v16.3.0-preview-20190808-03

**Comment by saurabhporwal28** [comment]
I'm working on creating a differential build for our Monolithic solution and so don't want to run all the test files on every build and run only those which have been impacted. I've the logic for differential pieces and I'm thinking of using VSTest.Console.exe to run those test files and so would need to include wildcards in the path as well as file names. I tried doing that on my Visual Studio Command prompt but that does not look like takes wildcards but I get the error that the test Source file provided was not found. So, how do I get this version running on my local which will take the wildcards in the filepaths and filenames. Thanks
