### ISSUE TITLE
Service Fabric test projects (x64) start failing after upgrading to VS2017 15.6.7

### ISSUE THREAD

**Issue by markti** [Microsoft/vstest#1668]
## Description
Long working unit tests projects suddenly stop working after upgrading Visual Studio to version 15.6.7,

## Steps to reproduce
Create a new Unit Test Project using VS Testing Tools (Microsoft.VisualStudio.TestPlatform.TestFramework). Change TargetFramework to 4.6.1 PlatformTarget to x64.

## Expected behavior
VS executes the tests.

## Actual behavior

> [7/2/2018 2:11:51 PM Error] System.IO.FileNotFoundException: C:\Users\Mark\AppData\Local\Temp\VisualStudioTestExplorerExtensions\MSTest.TestAdapter.1.3.2\build\_common\Microsoft.VisualStudio.TestPlatform.MSTest.TestAdapter.dll
>    at System.Diagnostics.FileVersionInfo.GetVersionInfo(String fileName)
>    at Microsoft.VisualStudio.TestPlatform.Utilities.Helpers.FileHelper.GetFileVersion(String path)
>    at Microsoft.VisualStudio.TestPlatform.CrossPlatEngine.Hosting.DefaultTestHostManager.GetAndLogFileVersion(String path)
>    at Microsoft.VisualStudio.TestPlatform.CrossPlatEngine.Hosting.DefaultTestHostManager.FilterExtensionsBasedOnVersion(IEnumerable`1 extensions)
>    at Microsoft.VisualStudio.TestPlatform.CrossPlatEngine.Hosting.DefaultTestHostManager.GetTestPlatformExtensions(IEnumerable`1 sources, IEnumerable`1 extensions)
>    at Microsoft.VisualStudio.TestPlatform.CrossPlatEngine.Client.ProxyExecutionManager.InitializeExtensions(IEnumerable`1 sources)
>    at Microsoft.VisualStudio.TestPlatform.CrossPlatEngine.Client.ProxyExecutionManager.StartTestRun(TestRunCriteria testRunCriteria, ITestRunEventsHandler eventHandler)
> [7/2/2018 2:11:51 PM Error] System.IO.FileNotFoundException: C:\Users\Mark\AppData\Local\Temp\VisualStudioTestExplorerExtensions\MSTest.TestAdapter.1.3.2\build\_common\Microsoft.VisualStudio.TestPlatform.MSTest.TestAdapter.dll
>    at System.Diagnostics.FileVersionInfo.GetVersionInfo(String fileName)
>    at Microsoft.VisualStudio.TestPlatform.Utilities.Helpers.FileHelper.GetFileVersion(String path)
>    at Microsoft.VisualStudio.TestPlatform.CrossPlatEngine.Hosting.DefaultTestHostManager.GetAndLogFileVersion(String path)
>    at Microsoft.VisualStudio.TestPlatform.CrossPlatEngine.Hosting.DefaultTestHostManager.FilterExtensionsBasedOnVersion(IEnumerable`1 extensions)
>    at Microsoft.VisualStudio.TestPlatform.CrossPlatEngine.Hosting.DefaultTestHostManager.GetTestPlatformExtensions(IEnumerable`1 sources, IEnumerable`1 extensions)
>    at Microsoft.VisualStudio.TestPlatform.CrossPlatEngine.Client.ProxyExecutionManager.InitializeExtensions(IEnumerable`1 sources)
>    at Microsoft.VisualStudio.TestPlatform.CrossPlatEngine.Client.ProxyExecutionManager.StartTestRun(TestRunCriteria testRunCriteria, ITestRunEventsHandler eventHandler)
> [7/2/2018 2:11:51 PM Informational] ========== Run test finished: 0 run (0:00:00.185157) ==========

## Diagnostic logs
> Please share test platform diagnostics logs. Instructions to collect logs are [here](https://github.com/Microsoft/vstest-docs/blob/master/docs/diagnose.md#test-platform-diagnostics).  
> The logs may contain test assembly paths, kindly review and mask those before sharing.

## Environment
Windows 10 Enterprise Build 17134
VS2017 15.6.7
Service Fabric Tools v2.0
Azure Tools v2.9

**Comment by abhishkk** [comment]
@markti 
Versioning of `MSTest.Adapter` was not followed properly earlier and this if old version of MSTest adapter is present, test platform might pick that old adapter and thus causing issues above mentioned.

Can you please clear cached `VisualStudioTestExplorerExtensions` folder and try the scenario again?

**Comment by mayankbansal018** [comment]
closing this issue, please comment here if you are still facing issue.
