### ISSUE TITLE
dotnet test doesn't run net462 after strong naming assemblies

### ISSUE THREAD

**Issue by bruno-garcia** [Microsoft/vstest#1684]
## Description
Once I enabled strong naming assemblies, running `dotnet test` on a multi targeted project no longer runs `net462` target. `netcoreapp2.x` targets still work normally.

The project is on GitHub. I merged [this PR](https://github.com/getsentry/sentry-dotnet/pull/41/files) which adds strong naming to all assemblies in the solution. The [build of the PR passed](https://ci.appveyor.com/project/sentry/sentry-dotnet/build/356) but what I didn't notice is that there were [600 tests less than the build before](https://ci.appveyor.com/project/sentry/sentry-dotnet/build/353/tests) that.

## Steps to reproduce
1. [Check out the repo](https://github.com/getsentry/sentry-dotnet/tree/24ab3c8ab8527b84f5a2c85da7c7bc01308aab32)
2. Run `dotnet test`

## Expected behavior
All 3 targets would run for all test project

## Actual behavior

The two netcoreapp targets run correctly, and net462 outputs:

```
Copyright (c) Microsoft Corporation.  All rights reserved.

Starting test execution, please wait...
[xUnit.net 00:00:01.75] Skipping: Sentry.AspNetCore.Tests (could not find dependent assembly 'Sentry.AspNetCore.Tests, Version=1.0.0')
No test is available in C:\Users\bruno\git\sentry-dotnet\test\Sentry.AspNetCore.Tests\bin\Release\net462\Sentry.AspNetCore.Tests.dll. Make sure that test discoverer & executors are registered and platform & framework version settings are appropriate and try again.

...

Starting test execution, please wait...
[xUnit.net 00:00:01.63] Skipping: Sentry.Extensions.Logging.Tests (could not find dependent assembly 'Sentry.Extensions.Logging.Tests, Version=1.0.0')
No test is available in C:\Users\bruno\git\sentry-dotnet\test\Sentry.Extensions.Logging.Tests\bin\Release\net462\Sentry.Extensions.Logging.Tests.dll. Make sure that test discoverer & executors are registered and platform & framework version settings are appropriate and try again.

...

Starting test execution, please wait...
[xUnit.net 00:00:01.75] Skipping: Sentry.AspNetCore.Tests (could not find dependent assembly 'Sentry.AspNetCore.Tests, Version=1.0.0')
No test is available in C:\Users\bruno\git\sentry-dotnet\test\Sentry.AspNetCore.Tests\bin\Release\net462\Sentry.AspNetCore.Tests.dll. Make sure that test discoverer & executors are registered and platform & framework version settings are appropriate and try again.

Build started, please wait...


```

## Diagnostic logs
The output of: `dotnet test -d:debug.txt`

[debug.host.18-07-11_14-02-41_73660_5.txt](https://github.com/Microsoft/vstest/files/2184344/debug.host.18-07-11_14-02-41_73660_5.txt)
[debug.host.18-07-11_14-02-47_51519_5.txt](https://github.com/Microsoft/vstest/files/2184345/debug.host.18-07-11_14-02-47_51519_5.txt)
[debug.host.18-07-11_14-02-52_92419_1.txt](https://github.com/Microsoft/vstest/files/2184346/debug.host.18-07-11_14-02-52_92419_1.txt)
[debug.txt](https://github.com/Microsoft/vstest/files/2184347/debug.txt)

## Environment
The .NET SDK version is locked on `global.json`: 2.1.300

Windows 10 (10.0.17134), .NET Framework 4.7.2, .NET Core SDK 2.1.300

**Comment by bruno-garcia** [comment]
Running tests through `dotnet xunit` points out the exact issue:

```sh
λ dotnet xunit -f net462
Detecting target frameworks in Sentry.Tests.csproj...
Building for framework net462...
  Sentry -> C:\Users\bruno\git\sentry-dotnet\src\Sentry\bin\Debug\netstandard2.0\Sentry.dll
  Sentry.Testing -> C:\Users\bruno\git\sentry-dotnet\test\Sentry.Testing\bin\Debug\net462\Sentry.Testing.dll
  Sentry.Tests -> C:\Users\bruno\git\sentry-dotnet\test\Sentry.Tests\bin\Debug\net462\Sentry.Tests.dll
Running desktop CLR tests for framework net462...
xUnit.net Console Runner (64-bit Desktop .NET 4.0.30319.42000)
System.IO.FileLoadException: Could not load file or assembly 'Sentry.Tests, Version=1.0.0.0, Culture=neutral, PublicKeyToken=fba2ec45388e2af0' or one of its dependencies. Strong name signature could not be verified.  The assembly may have been tampered with, or it was delay signed but not fully signed with the correct private key. (Exception from HRESULT: 0x80131045)
```

Google pointed me to: https://github.com/dotnet/roslyn/issues/6052

Disabling shadow copy for xunit seems to solve the problem when running `dotnet test` through the command line.

I still can't get the tests to run on **Visual Studio** though. Only shows *netcoreapp2.x*

**Comment by mayankbansal018** [comment]
@bruno-garcia from the logs provided above I can see the same exception in file "debug.host.18-07-11_14-02-52_92419_1.txt", unfortunately it came as warning from xunit, hence it did not get logged on console. For such failing scenarios, we recommend you pass verbosity flag to vstest.console, to get more detailed log straight on console.

Closing as issue already has a resolution.
