### ISSUE TITLE
Nuget pacakge 15.8.0 is broken

### ISSUE THREAD

**Issue by NetTecture** [Microsoft/vstest#1687]
IVor .NETCoreApp and .NEETFramework

it looks for Microsoft.CodeCoverage versions >= 15.8.9

That is not how they are numbered - they currently area at version 1.0.3

That was working nice in the last preview I have (0610-02), but now the upgrade is broken.

**Comment by mswietlicki** [comment]
For me it's looking for Microsoft.CodeCoverage 15.8.0 but still this version is not published yet. 
"Unable to find package Microsoft.CodeCoverage with version (>= 15.8.0)"

**Comment by NetTecture** [comment]
Which is what I say.

Excelt: This version will also not be published for a LONG time as Microsoft.CodeCoverage uses a different numbering scheme and is now at 1.0.3 - the 15.8.0 is the vstest numbering, so likely a copy/paste error.

**Comment by NetTecture** [comment]
Close. Whow. Someone published that one - and changed the CodeCoverage numbering scheme seriously to 15.8 - quite a jumb.
