### ISSUE TITLE
NuGet Package License

### ISSUE THREAD

**Issue by dev-rsilver** [Microsoft/vstest#1691]
The license associated with the NuGet package for Microsoft.NET.Test.Sdk is the Microsoft .NET Library license. Is this intentional as this project appears to be licensed under MIT?

**Comment by pvlakshm** [comment]
Several of the vstest related packages are indeed using the Microsoft .NET Library license. Is there any specific concern?

**Comment by dev-rsilver** [comment]
The .NET Library license imposes relatively significant requirements on an application that utilizes software licensed under it (compared to permissive open source licenses).

The .NET Core packages appear to be made available under permissive open source licenses. The Microsoft.NETCore.App package license for instance points back to the MIT license in the repository. 

The .NET Core CLI has the option to add an MSTest project.

I concluded (perhaps incorrectly) that the Microsoft test-related projects were open sourced, at least in part, to create a cross platform, open source testing framework compatible with .NET Core. 

Adding an MSTest project to a .NET Core project is, however, pulling in these non open source packages (Microsoft.NET.Test.Sdk, MSTest.TestAdapter, MSTest.TestFramework).

I realize that the packages are also being utilized with the closed .NET framework, but it would be helpful to have packages that are "compatible" with the open source nature of .NET Core. Since the various Microsoft test-related repositories appear to have open source licenses, it didn't seem like an unreasonable request that the packages match those licenses for compatibility with .NET Core's licensing.

**Comment by pvlakshm** [comment]
Although I cannot commit to whether (and by when) this might get changed, I will have someone more conversant with licensing from our side to have a look. Thank you for bringing this up.

**Comment by pvlakshm** [comment]
These are indeed the licenses we are required to use.
