### ISSUE TITLE
.Net Core tests take a long time to report a missing SDK.

### ISSUE THREAD

**Issue by AbhitejJohn** [microsoft/vstest#1692]
## Description 
When I run a .Net Core test where the sdk being targeted is not installed on the box we do nothing for about a minute after which we show the following message in the output pane
```
 Microsoft.VisualStudio.TestPlatform.ObjectModel.TestPlatformException: Testhost process exited with error: It was not possible to find any compatible framework version
The specified framework 'Microsoft.NETCore.App', version '2.1.0-preview2-26406-04' was not found.
  - Check application dependencies and target a framework version installed at:
      C:\Program Files\dotnet\
  - Installing .NET Core prerequisites might help resolve this problem:
      http://go.microsoft.com/fwlink/?LinkID=798306&clcid=0x409
  - The .NET Core framework and SDK can be installed from:
      https://aka.ms/dotnet-download
  - The following versions are installed:
      2.1.0-preview1-25929-02 at [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
      2.1.1 at [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]

   at Microsoft.VisualStudio.TestPlatform.CrossPlatEngine.Client.ProxyOperationManager.ThrowExceptionOnConnectionFailure(Int32 connTimeout)
   at Microsoft.VisualStudio.TestPlatform.CrossPlatEngine.Client.ProxyOperationManager.SetupChannel(IEnumerable`1 sources)
   at Microsoft.VisualStudio.TestPlatform.CrossPlatEngine.Client.ProxyExecutionManager.StartTestRun(TestRunCriteria testRunCriteria, ITestRunEventsHandler eventHandler)
[7/6/2018 4:08:48 PM Error] Microsoft.VisualStudio.TestPlatform.ObjectModel.TestPlatformException: Testhost process exited with error: It was not possible to find any compatible framework version
The specified framework 'Microsoft.NETCore.App', version '2.1.0-preview2-26406-04' was not found.
  - Check application dependencies and target a framework version installed at:
      C:\Program Files\dotnet\
  - Installing .NET Core prerequisites might help resolve this problem:
      http://go.microsoft.com/fwlink/?LinkID=798306&clcid=0x409
  - The .NET Core framework and SDK can be installed from:
      https://aka.ms/dotnet-download
  - The following versions are installed:
      2.1.0-preview1-25929-02 at [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
      2.1.1 at [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]

   at Microsoft.VisualStudio.TestPlatform.CrossPlatEngine.Client.ProxyOperationManager.ThrowExceptionOnConnectionFailure(Int32 connTimeout)
   at Microsoft.VisualStudio.TestPlatform.CrossPlatEngine.Client.ProxyOperationManager.SetupChannel(IEnumerable`1 sources)
   at Microsoft.VisualStudio.TestPlatform.CrossPlatEngine.Client.ProxyExecutionManager.StartTestRun(TestRunCriteria testRunCriteria, ITestRunEventsHandler eventHandler)
```
This is precise and helpful messaging. Is there a way we could report this earlier then having to wait for the connection timeout? This isn't very important but would give a better experience.

**Comment by singhsarab** [comment]
@pvlakshm Please triage.

**Comment by jainaashish** [comment]
I also raised this[ feedback ticket](https://developercommunity.visualstudio.com/content/problem/325145/test-explorer-window-hangs-after-rebuilding-the-pr.html?childToView=326005#comment-326005) for the same issue. And IMHO this feels like a broken scenario. I installed the latest VS 15.8 and opened an existing solution and tried to run tests. If Test explorer window has hard dependency on some sdk version then should that be included as part of installer or Test explorer should take dependency on latest sdk which is part of the installer itself... either way we shouldn't expect customers to install those specific sdk versions separately for us to be working properly...

**Comment by AbhitejJohn** [comment]
@jainaashish : Test Explorer or the platform does not take a hard dependency on an sdk. It picks up whatever the test app specifies. The VS installer AFAIK downloads only the latest stable sdk. you might want to look at additional components to install 1.* sdks or pull the one the app requires from the downloads page.

**Comment by singhsarab** [comment]
@AbhitejJohn Is this still an issue? I thought this was fixed a long time ago.

**Comment by AbhitejJohn** [comment]
@singhsarab : Tried this out on a simple MSTest .NET Core project and I did not see the delay. So I guess this is fixed - Don't really know what fixed this though.

**Comment by singhsarab** [comment]
Thanks for the confirmation. I think I remember we rolled our a fix for this. 
Closing.
