### ISSUE TITLE
Can vstest.console.exe support -nologo parameters ?

### ISSUE THREAD

**Issue by liangdaxian** [microsoft/vstest#1696]
we are using this exe to run our tests , however our build engine does not handle trackmarks well( a.k.a Domino), so we see problems about logging in domino build, most likely the log get truncked.

so is it possbile to support adding -nologo to supress this lines ?

Microsoft (R) Test Execution Command Line Tool Version 15.7.0
Copyright (c) Microsoft Corporation.  All rights reserved.

**Comment by mayankbansal018** [comment]
this is already fixed
