### ISSUE TITLE
Code Coverage not getting collected for some assemblies

### ISSUE THREAD

**Issue by smadala** [Microsoft/vstest#1702]
## Description
- No code coverage data available for some assemblies

## Steps to reproduce
- git clone https://github.com/dotnet/reactive
 - Make sure to have a 2.1.4xx dotnet available.(https://dotnetcli.blob.core.windows.net/dotnet/Sdk/2.1.400-preview-008975/dotnet-sdk-2.1.400-preview-008975-win-x64.exe)
- Go to Ix.NET\Source
 
- Run `dotnet test .\System.Interactive.Async.Tests.csproj --collect:"Code Coverage" -f netcoreapp2.1 /p:DebugType=portable`
 
Look at the coverage reports and you won’t find System.interactive.Async.dll in there.

## Expected behavior
- Coverage data should be collected for `System.interactive.Async.dll`

## Actual behavior
-  No coverage data available for `System.interactive.Async.dll`

/cc @onovotny

**Comment by smadala** [comment]
I have debugged this issue found that  `System.interactive.Async` code coverage not available because `DIA` api not able to load the  `System.interactive.Async.pdb`. 

@mayankbansal018 Can you please take a look at this?

**Comment by mayankbansal018** [comment]
What was the error thrown by DIA API's? If we are sure that it is DIA issue, can you create an internal bug, & assign it to DIA team.

**Comment by mayankbansal018** [comment]
@tmat, can you please take a look, coverage file is generated is debugtype is full, for portable it is not. I've also dropped a mail to you internally

**Comment by smadala** [comment]
This is issue due to bug in `DIA` apis. @VCZYK has fix for it. I will update regarding fix release ASAP here.

**Comment by onovotny** [comment]
Any updates on this in terms of a servicing vehicle? When/where can we expect to see this fix?

**Comment by karanjitsingh** [comment]
Closing this as it has been fixed.

**Comment by onovotny** [comment]
Thanks @karanjitsingh. What version of the test SDK has the fix in it?

**Comment by karanjitsingh** [comment]
@onovotny, I truly apologize for this but I was mistakenly under the impression that the DIA api fix had gone in, I tried the repro with the latest version and it seems that it has not been fixed. Reopening the issue.

**Comment by mayankbansal018** [comment]
@onovotny the fix should be available in .net test sdk 15.9, let me know if it is not resolved.

**Comment by onovotny** [comment]
@mayankbansal018 I'm seeing this issue with the latest 16.0 preview test SDK's.

No code coverage:
https://dev.azure.com/dotnet/Rx.NET/_build/results?buildId=10303

Added /p:DebugType=Full has coverage:
https://dev.azure.com/dotnet/Rx.NET/_build/results?buildId=10304

That was the only change.
