### ISSUE TITLE
Failed: ETIMEDOUT connect ETIMEDOUT error while running tests on browserstack through npm task

### ISSUE THREAD

**Issue by ShaifaliKhera** [Microsoft/vstest#1703]
I have a protractor test automation framework which is integrated with browserstack. When I run the tests from local system in browserstack, the tests run fine. But on "Hosted VS2017" agent, when npm task run to start tests on browserstack (and wait for the results), the tests are failing at random places with Failed: ETIMEDOUT connect ETIMEDOUT error.  The issue is not from the browserstack side and we don't have any proxy. What can be the reason of failure?

**Comment by smadala** [comment]
@ShaifaliKhera Can you provide more details about to how repro the issue?
What is the exact `vstest.console.exe` command you are running?

**Comment by ShaifaliKhera** [comment]
I'm using npm task to run "npm run e2e-browserstack" command specified in package.json file, which actually calling  "node ./node_modules/protractor/bin/protractor ./e2e/protractorBrowserstack.conf.js" command. I have protractorBrowserstack.conf.js file which controls running tests on browserstack. Can't share the whole framework for you to reproduce the issue. do you need any specific file, then I can share that? When the tests run on browserstack it takes some time for them to execute like 1-2 minutes and then it prints the logs on console. It seems like Hosted VS2017 idle timeout is very less, so it's timing out when waiting for the response from browserstack.

**Comment by smadala** [comment]
Looks like issue related to Hosted VS2017. Moving to `vsts-tasks` repo.

**Comment by smadala** [comment]
This issue was moved to Microsoft/vsts-tasks#7880
