### ISSUE TITLE
Discrepancy in test state while running combination of tests targeting different frameworks

### ISSUE THREAD

**Issue by abhishkk** [microsoft/vstest#1729]
## Description
We have enabled association support for MSTest v2. Not users can associate mstest v2(both full framework and net core).

If a user adds net core and full frameword mstest v2 tests in same test plan and runs it via vstest v2 task, then following happens:
1. If target framework is set to .NET (in runsettings) and test plan is ran, .NET core tests are not discovered and thus are not ran.
2. If target framework is set to .NET core and test plan is ran, error is thrown while discovery for .NET tests and thus test ran gets aborted.

## Issue
Even though we will educate users that combination of net core and full framework can't be ran in single test plan; the behavior of test ran is inconsistent when target framework is changed in runsettings.

**This issue is to know if there is a possibility to make the behavior of test platform consistent (i.e. either throwing error in both scenarios OR skipping discovery in both scenarios)**

**Comment by singhsarab** [comment]
I think, if both .Net core and full framework dlls are given, we should error out and tell the user. Point (1) seems to be an issue to me.

**Comment by singhsarab** [comment]
@vagisha-nidhi Can you check the behavior for architecture as well ?

**Comment by vagisha-nidhi** [comment]
@singhsarab With platform architecture as well, we get similar warning message about framework/platform settings with `No test available` warning.
