### ISSUE TITLE
Getting error Test host exited with error: '' when run vstest.console.exe

### ISSUE THREAD

**Issue by amolraut86** [Microsoft/vstest#1733]
## Description
Hi All, I have been searching for solution this problem i am facing since couple of days,
I am getting an error **Test host exited with error: ''**
I am using xunit test project with target framework dotnetcore 2.0 

## Steps to reproduce

I have tried every solution available in MS community but not getting success,

Get below errors in logs,
1) vstest.console.exe, Test host exited with error: ''
2) Failed to start test run: Microsoft.VisualStudio.TestPlatform.ObjectModel.TestPlatformException: Failed to initialize client proxy: could not connect to test process.

We are using nant for build project, Unit Test execution with jenkins build server, below is the configuration for the same

nant config for vstest.console.exe is 
[nantConfigurationbuildfile.txt](https://github.com/Microsoft/vstest/files/2292780/nantConfigurationbuildfile.txt)

I have tried running it directly with console using command

D:\Program Files (x86)\Microsoft Visual Studio\2017\TestAgent\Common7\IDE\CommonExtensions\Microsoft\TestWindow\vstest.console.exe 
"D:\jenkins\jobs\SVN_Project_Branch\workspace\WebApi\ProjectServiceApplication\ProjectService.Tests\bin\Release\netcoreapp2.0\ProjectService.Tests.dll" /EnableCodeCoverage /Logger:trx /framework:".NETCoreApp,Version=v2.0" /Diag:"D:\jenkins\jobs\SVN_Project_Branch\workspace\TestResults\DiagnosticTraceLogs\TraceLogs.txt"

When i remove the parameter **/EnableCodeCoverage** from above command, test runs successfully, but i want code coverage to be included.
		
I have even tried running below command
D:\>dotnet exec --runtimeconfig "D:\jenkins\jobs\SVN_Project_Branch\workspace\WebApi\ProjectServiceApplication\ProjectService.Tests\bin\Release\netcoreapp2.0\ProjectService.Tests.runtimeconfig.json" --depsfile "D:\jenkins\jobs\SVN_Project_Branch\workspace\WebApi\ProjectServiceApplication\ProjectService.Tests\bin\Release\netcoreapp2.0\ProjectService.Tests.deps.json" "C:\Users\SRVDEVOPSSERVICE\.nuget\packages\microsoft.testplatform.testhost/15.8.0\lib/netstandard1.5/testhost.dll" --port 20756 --endpoint 127.0.0.1:020756 --role client --parentprocessid 11052 --diag "D:\jenkins\jobs\SVN_Project_Branch\workspace\TestResults\DiagnosticTraceLogs\TraceLogs.host.18-08-16_06-37-50_73650_5.txt" --datacollectionport 0 --telemetryoptedin false
but nothing happens

Then i added xunit.runner.json with below configuration to disable parallel execution of tests and including but no luck 

{
  "diagnosticMessages": true,
  "longRunningTestSeconds": 5,
  "maxParallelThreads": -1,
  "parallelizeAssembly": false,
  "parallelizeTestCollections": false
}

Below is my test project structure,
[TestProjectfile_Structure.txt](https://github.com/Microsoft/vstest/files/2292782/TestProjectfile_Structure.txt)

Please let me know what i am doing wrong

## Expected behavior
> should execute unit tests successfully and to generate code coverage for the same

## Actual behavior
> 1) vstest.console.exe, Test host exited with error: ''
> 2) Failed to start test run: Microsoft.VisualStudio.TestPlatform.ObjectModel.TestPlatformException: Failed to initialize client proxy: could not connect to test process.

## Diagnostic logs
> Please find attached logs,
[TraceLogs.txt](https://github.com/Microsoft/vstest/files/2292681/TraceLogs.txt)
[Diag.datacollector.txt](https://github.com/Microsoft/vstest/files/2292682/Diag.datacollector.txt)

## Environment
> windows server 2012 R2.
> Operating system, Build version of vstest.console

**Comment by amolraut86** [comment]
Hi Guys,
Can anybody response on this issue plzz?

Please find below screenshots for more reference 
![xunit_issue](https://user-images.githubusercontent.com/41044479/44327980-f13d6500-a47d-11e8-8d6e-bd406d044aad.PNG)

Does anybody knows why this is happening? this message appears whenever i add /EnableCodeCoverage option in vstest run command. when i remove /EnableCodeCoverage, tests executes successfully

**Comment by singhsarab** [comment]
@amolraut86 What is the version of dotnet installed on your machine ?
Have you tried using *dotnet test* verb?

**Comment by amolraut86** [comment]
Thanks for your reply, 

I am using dotnet version 2.0.2
Yes, I have tried with dotnet test --collect:"Code Coverage" and get the same result as 
Data collection : Could not find data collector 'Code Coverage'

Have gone through the link https://github.com/Microsoft/vstest/issues/981 as support for code coverage is not yet provided in dotnet test but it should work with VS Test Agent 2017 & vstest.console.exe but its not

**Comment by singhsarab** [comment]
@amolraut86 The support for  dotnet test --collect:"Code Coverage" is available for windows now. Try dotnet version 2.1.400

Yes, it should work via vstest.console.
Can you please share the diagnostic logs? https://github.com/Microsoft/vstest-docs/blob/master/docs/diagnose.md#collect-trace-using-config-file

**Comment by singhsarab** [comment]
@amolraut86 Can you please share the logs, so we can diagnose your issue.

**Comment by singhsarab** [comment]
@amolraut86 Closing this issue for now. Please let us know if you are still hitting the issue, We'd re-open the issue.
