### ISSUE TITLE
Errors running in Framework35

### ISSUE THREAD

**Issue by jhedlund** [Microsoft/vstest#1734]
## Description

I have target v3.5 framework project with unit tests that I was looking to upgrade from NUnit 2 to 3.  

I am having a few issues running some of the tests I believe due to a change in VSTest that runs in compat mode instead of running in v3.5 test process.

The easiest issue to describe:

The code contains deserialization routines that read a string into a MemoryStream to deserialize. 

When running the test via the Test Explorer, the test fails with:

<System.Exception: Error deserializing orders object ---> System.NotSupportedException: Memory stream is not expandable.
   at System.IO.MemoryStream.set_Capacity(Int32 value)
   at System.IO.MemoryStream.EnsureCapacity(Int32 value)
   at System.IO.MemoryStream.Write(Byte[] buffer, Int32 offset, Int32 count)
   at System.IO.StreamWriter.Flush(Boolean flushStream, Boolean flushEncoder)
   at System.IO.StreamWriter.Dispose(Boolean disposing)
   at System.IO.StreamWriter.Close()
   at System.Xml.XmlTextWriter.Close()
   at System.Xml.XmlWriter.Dispose(Boolean disposing)
   at System.Xml.XmlWriter.Dispose()
   [...]

When run in nunit3-console the tests pass successfully.    If I set the --framework version to v4.0 for nunit3-console, it blows up with the same error as above. 

I tried setting the .runsettings to <TargetFrameworkVersion>Framework35</TargetFrameworkVersion> but it still throws the exception.

## Environment

This is on Windows 7, Visual Studio 2017 15.7.4

**Comment by singhsarab** [comment]
@mayankbansal018 @cltshivash Thoughts?

**Comment by jhedlund** [comment]
I'll try to get a repro that I can share, thanks.

**Comment by jayaranigarg** [comment]
@jhedlund : Any updates on this?

**Comment by nigurr** [comment]
@jhedlund We are closing this issue as we don't have repro. Please reach us with repro and feel free to re-open the issue.

**Comment by jhedlund** [comment]
Hi, sorry for the delay, I was finally able to re-try the error and I can no longer reproduce it.  Perhaps fixed in a subsequent release of VS?  Thanks for the attention to the issue
