### ISSUE TITLE
VSTest starts work unpredictable after adding TfsPublisher

### ISSUE THREAD

**Issue by vbondaryuk** [Microsoft/vstest#1739]
## Description
We found out strange behavior after adding TfsPublisher logger to our project.
For one of our business cases we implemented custom logger. This logger uses without coping to extension folder, just add `--TestAdapterPath`. It works correctly. 

But now we try to add TfsPublisher we found out some issues:
- can't use some of new futures vstest for example: `--ResultsDirectory`, moreover no one argument does not work if call it with `--`
- custom logger does not work (`Could not find a test logger with AssemblyQualifiedName, URI or FriendlyName`). Argument `--TestAdapterPath`sets, but does not work.
- vstest version was decrised(15.7.2 => 15.0.27617.1) 

Moreover if try to add TfsPublisher like `--logger:TfsPublisher` instead of `/Logger:TfsPublisher` vstest does not find it.

**Comment by singhsarab** [comment]
@vbondaryuk This is a known issue.
TfsPublisher is not supported with new TestPlatform.

If TfsPublisher is opted like /logger:TfsPublisher, it fallbacks to older TestPlatform which does not have the new features.

/cc: @pvlakshm @cltshivash @smadala @mayankbansal018

**Comment by vbondaryuk** [comment]
@singhsarab Thank you for your response. 

Will it be fixed in future?

Since TfsPublisher is not supported with new TestPlatform is there any possibilities to publish test results to Tfs without usage of TfsPubliser? 

If yes, could you provide any examples?

**Comment by singhsarab** [comment]
@vbondaryuk TfsPublisher is only used to publish results against XAML builds. With most of our customers on or moving to new build system, highly unlikely we would be investing here.

We have had no asks for new Test platform to support this. In next major release, we would not be supporting via fallback scenario as well.

Given that, the general guidance from our side to write a custom logger to achieve that. For example, https://github.com/spekt/appveyor.testlogger

**Comment by singhsarab** [comment]
@vbondaryuk Please let us know if you have any concerns.
If you don't, I will go ahead and close the issue.
