### ISSUE TITLE
Tests execution freezes while closing the app

### ISSUE THREAD

**Issue by Delphinidae84** [Microsoft/vstest#1747]
## Description
After building an UWP-project via msbuild I am running the tests inside the project via:

```batch
vstest.console.exe "myProject.build.appxrecipe" /logger:trx;LogFileName=myProject.trx /EnableCodeCoverage
```
While it does work using command line, all tests pass and the application is being closed, I do have issues running those tests via a "Windows Batch-File" element in Jenkins.

The project does build. It does run the tests but after it passes some tests, it tries to close the application and freezes in that condition forever:

```
Attempting to deploy to target 'Local Machine'.
Creating a new clean layout...

Copying files: Total 49 mb to layout...

Checking whether required frameworks are installed...

Registering the application to run from layout...

Deployment complete (0:00:01,632). Full package name: "dummy"

Deployment operation succeeded, package moniker: 'dummy'.
Attempting to launch app with app user model Id 'dummy!vstest.executionengine.universal.App' and arguments '--port xxxxx --endpoint 127.0.0.1:xxxxx --role client --parentprocessid xxxx --telemetryoptedin false'.
Successfully launched process Id '10708'.
Passed Test1
Passed Test2
Closing app with package full name 'dummy'.
The active test run was aborted. Reason: At least one error was detected.
Closing app with package full name 'dummy'.
```

## Expected behavior
If the tests do actually fail, the running app should be closed and a exception thrown.

## Actual behavior
The build never stops it just hangs forever in the last line `Closing app with package full name` .

## Environment
* Windows 10 (latest)
* Inside a Jenkins (latest) build
* `vstest.console.exe` Version 15.8.0

**Comment by singhsarab** [comment]
@mayankbansal018 this is unexpected. Any ideas?

**Comment by mayankbansal018** [comment]
@singhsarab , no idea, closing of the App is handled by runtime provider, we can ask UWP team to see what logs we can enable to understand, why it has stuck.

**Comment by mayankbansal018** [comment]
@MSLukeWest , can you please help here.

**Comment by MSLukeWest** [comment]
Can you describe the behavior of the app in this case?  When you see this message is it still running?  And if so what happens when you close it?

@mayankbansal018 - There is an issue on the test platform side here as well.  It's calling CleanTestHostAsync twice, presumably because the first one failed.  That's why we see two instances of the message "Closing app with package full name 'dummy'".

**Comment by Delphinidae84** [comment]
@MSLukeWest Yes, the app is still running (I can see it) when I see the message. If I kill the Jenkins job, The app and the process (Task-Manager) are still running, so still I can see the app. If I close the app nothing special seems to happen, both the app and the according process are being stopped.

**Comment by jayaranigarg** [comment]
@Delphinidae84 : Can you run your tests from vstest.console and pass --diag:log.txt switch and share those logs with us?

@MSLukeWest : Can you tell @Delphinidae84 which logs he should enable where we can see why first call to CleanTestHostAsync  failed maybe or any such logs which might help debug this issue?

**Comment by acesiddhu** [comment]
We haven't heard back on this issue. @Delphinidae84 if you are still facing the issue please share the diag logs with us. 
@MSLukeWest it would be great if there are any logs that we can enable which will help us dig deeper to CleanTestHostAsync failure. Let us know if there are any logs that can help here
