### ISSUE TITLE
Add option to use a different DOTNET host than the one located in the path

### ISSUE THREAD

**Issue by ViktorHofer** [microsoft/vstest#1749]
Follow-up on the offline discussion that we had. We (the .NET team) want to enable VS Text Explorer support for corefx.

We are building the shared framework and the runtime ourselves, we do things differently as the average user. Still we see a strong demand for enabling Test Explorer like in a regular app.
- Framework
We (corefx) are the ones that build the framework itself. Therefore we can’t use the shared framework located under `%PATH%/dotnet/shared/Microsoft.NETCore.App/x.x.x/` as we want to test our live build.
- Host
We don’t take a dependency on the globally installed .NET Core SDK and its dotnet.exe host and use nightly builds instead. That’s because we rely on features that aren’t yet available and because we don’t need that dependency.

We need a way to tell the VS Text Framework (Test Explorer) to use our dotnet host under corefx instead of the global one in the path. Probably via a switch in the .runsettings file that allows to set the custom path.

> How are we running the tests? do we use vstest.console or dotnet test verb ?

On the command-line we run tests in a different way by directly invoking xunit.console.dll but with Visual Studio we just want to use the Test Explorer which I'm not sure what it uses behind the scenes. For xunit we are using its test adapter: https://www.nuget.org/packages/xunit.runner.visualstudio/

> Can’t we temporarily set the environment variable “PATH” to point to the new path in a script before invoking the test command ?

Can we do that when we just use VS Test Explorer?

cc @singhsarab @danmosemsft

**Comment by singhsarab** [comment]
@ViktorHofer As I asked in the mail.
Can’t we set the environment variable “PATH” to point to the new path to dotnet?

**Comment by singhsarab** [comment]
@ViktorHofer Gentle ping.

**Comment by ViktorHofer** [comment]
Sorry for the late response, I was OOF for a few days.

> Have you tried setting the environment variable before invoking the devenv in cmd/shell.

Sure that's an option but we want to use a different host for testing than for building (in corefx we currently use a minimal dotnet host which is only used during testing). Also for an optimal inner loop dev scenario we want to avoid setting local environment variables and launching VS from bash.

**Comment by singhsarab** [comment]
@ViktorHofer 
Any reason, why we avoid setting local environment variables and launching VS from bash?

One basic principle we follow is to avoid adding new tags in Runsettings unless absolutely necessary. Reason being, adding is easy, removing is difficult. This ask is very specific to this particular scenario. And given there is already a workaround for this, I am not able to make a case.

Another concern I have is if we add something on lines you suggest, we'd have to document it. Even a normal user will also be able to set the path to whatever location he/she wants and that might result in unexpected behavior.

/cc: @PBoraMSFT @cltshivash

**Comment by ViktorHofer** [comment]
> Any reason, why we avoid setting local environment variables and launching VS from bash?

Yes two reasons:

- We use a different dotnet host for testing than for building
- We want to provide a dev flow that doesn't require setting environment variables and launching VS from bash.

**Comment by ViktorHofer** [comment]
So we discussed that topic internally and it seems in fact we don't need to tell the test framework to use a different host but to use the same as the project-system does. We pass the host via the StartProgram/RunCommand (launchSettings.json) same as the usual customer does.

If I'm right the test-framework currently determines the host in the specific order (https://devdiv.visualstudio.com/DevDiv/_git/DotNet-Source-Build-Tarball?path=%2Fsrc%2Fvstest%2Fsrc%2FMicrosoft.TestPlatform.TestHostProvider%2FHosting%2FDotnetTestHostManager.cs&version=GBmaster&line=172&lineEnd=183&lineStartColumn=13&lineEndColumn=14&lineStyle=plain):
1. if the current process is dotnet.exe use it
2. otherwise look into the path

I spoke with @davkean yesterday who agrees that the test-framework should ask the project-system for it.

cc @eerhardt

**Comment by singhsarab** [comment]
@ViktorHofer Thank you for note.
This seems like a better approach to me. Can you please help me get a better understanding of these environment variables passed in via launchSettings.json ?
If you think it is a small change in the code you pointed out, feel free to contribute. :)

**Comment by ViktorHofer** [comment]
@davkean can you please assist here? How can the test framework ask the project system for the right executable and other stuff defined in the launchSettings.json / Run props?

**Comment by jayaranigarg** [comment]
@ViktorHofer : Any updates here?

**Comment by ViktorHofer** [comment]
I didn't yet get a response from Dave, I also contacted him offline. Let me reach out to him again as I don't know how to follow-up here.

**Comment by jayaranigarg** [comment]
@ViktorHofer : Did you get a chance to follow up with Dave?

**Comment by ViktorHofer** [comment]
Not yet. Unfortunately I couldn't find the right person who could help here. Can you assist here?

**Comment by danmosemsft** [comment]
@davkean?

**Comment by ViktorHofer** [comment]
@ManishJayaswal @nohwnd I want to resume the discussion for this ask. To make the ask more specific, we need the following feature:

Allow specifying the path to the .NET Host `dotnet.exe` that is used for invoking the VSTest testhost. This should be an additional setting in the .runsettings file. Together with https://github.com/microsoft/vstest/issues/2273, we will then be able to fully switch to VSTest in https://github.com/dotnet/runtime and use the `dotnet test` verb on CLI.

For .NET Framework we don't need an additional hook as we can add the `DEVPATH` environment variable (which allows to load from a different .NET Framework directory) into the .runsetting's environment variable section.

Proposed .runsettings change:
```xml
<?xml version="1.0" encoding="utf-8"?>
<RunSettings>
  <RunConfiguration>
    <TestHostMuxer>%absolute-path-to-muxer%\dotnet.exe</TestHostMuxer>
  </RunConfiguration>
</RunSettings>
```

Muxer = technical term for the native host.

**Comment by eerhardt** [comment]
Small question on the naming: Do we use the term `Muxer` anywhere else in public settings/APIs/docs? I don't think we should use that term publicly. What about just `TestHost` or `TestHostPath`? Or if that is confusing with the `testhost.exe` binary, then maybe `DotNetHostPath`.

**Comment by ViktorHofer** [comment]
You are right, `DotNetHostPath` is a much better term.
