### ISSUE TITLE
Feature Request: Expose test case timeout on TestCase object during discovery

### ISSUE THREAD

**Issue by bichuga** [microsoft/vstest#1753]
## Description
When discovering test cases we would like to have access to any [Timeout(..)] attribute information specified by the test case author. If none is specified we would like to have the default timeout which the vstest.console.exe will use when it runs. Without this information we do not know how long our test harness should wait between messages from the test console.

## Steps to reproduce
Discover test cases, examine discoveredTestCases in

`public void HandleDiscoveredTests(IEnumerable<TestCase> discoveredTestCases)`
or

`public void HandleDiscoveryComplete(long totalTests, IEnumerable<TestCase> lastChunk, bool isAborted)`

## Desired behavior
`TimeSpan timeout` is included in TestCase properties

## Actual behavior
This data is returned:
```
object LocalExtensionData
Guid Id
string FullyQualifiedName
string DisplayName
Uri ExecutorUri
string Source
string CodeFilePath
int LineNumber
IEnumerable<TestProperty> Properties
```

## Environment
using Microsoft.TestPlatform.15.8.0

**Comment by Ofekw** [comment]
Ping on this? This is something that's been impacting us for years and would be a great enhancement ;)

**Comment by nohwnd** [comment]
This is a new feature and won't be implemented, we are focusing on adding new features to Testing.Platform instead. https://aka.ms/testingplatform
