### ISSUE TITLE
Code Coverage enabled breaks reporting

### ISSUE THREAD

**Issue by MoiMoiDG** [Microsoft/vstest#1755]
## Description
> **IMPORTANT**: if the defect is reproduced only in a workflow from within the Visual Studio IDE then do not report the issue here - instead, please report it using Visual Studio's "Send Feedback" option that can be accessed from the Help menu OR using this link https://developercommunity.visualstudio.com.
>
> For a defect reproducable from the vstest command line, describe the issue you've observed.

In TFS 2018.2 CI build, enabling code coverage breaks reporting of test results (and code coverage itself).

## Steps to reproduce
> What steps can reproduce the defect?
> Please share the setup, commandline for vstest.console, sample project, target
> framework etc.

TFS 2018.2, code coverage enabled. See details below.

## Expected behavior
> Share the expected output

Enabling code coverage shall show the code coverage, disabling it shall not compute it or hide the results.

## Actual behavior
> What is the behavior observed?

Enabling code coverage breaks test results.

## Diagnostic logs
> Please share test platform diagnostics logs. Instructions to collect logs are [here](https://github.com/Microsoft/vstest-docs/blob/master/docs/diagnose.md#test-platform-diagnostics).  
> The logs may contain test assembly paths, kindly review and mask those before sharing.

Code Coverage enabled, see screenshot below:
![ccenabled](https://user-images.githubusercontent.com/41326099/44846632-2c475180-ac51-11e8-8743-0273a54565c4.PNG)

Code Coverage disabled, see screenshot below:
![ccdisabled](https://user-images.githubusercontent.com/41326099/44846653-3bc69a80-ac51-11e8-895f-b3f018614d2a.PNG)

Logs, see attachment below:
[13_Test Assemblies release.Tests.dll;-obj.txt](https://github.com/Microsoft/vstest/files/2335791/13_Test.Assemblies.release.Tests.dll.-obj.txt)

## Environment
> Please share additional details about the test environment.
> Operating system, Build version of vstest.console

TFS 2018.2, see attached logs for more details. Let me know whether more information is needed.

**Comment by ShreyasRmsft** [comment]
@MoiMoiDG take a look at issue https://github.com/nunit/nunit3-vs-adapter/issues/519

Nunit does not support running tests with code coverage run while using the vstest platform tool installer.

**Comment by MoiMoiDG** [comment]
@ShreyasRmsft: Thank you the reply. I had a look at the linked issue, but I could not find any information to solve my problem.

**Comment by ShreyasRmsft** [comment]
@MoiMoiDG as of now this hasn't been fixed. We have to go fix it in the Nunit adapter. Until then you may want to use VS instead of the vstestplatformtool installer for running Nunit tests with code coverage

**Comment by ShreyasRmsft** [comment]
@MoiMoiDG please follow the workaround for now. Will track the issue in the one filed on the NUnit Adapter side

**Comment by MoiMoiDG** [comment]
@ShreyasRmsft: Thanks for the reply. I understand to keep the other issue open, but the workaround is not that easy for me, because I would need VS Enterprise on each machine running the tests. Is there any other solution but switching from NUnit to MS Test?
