### ISSUE TITLE
Tests get executed with compatibility level of .NET Framework 4.5.x

### ISSUE THREAD

**Issue by x2048** [Microsoft/vstest#1756]
## Description
When using Microsoft.NET.Test.SDK to execute tests, e.g. xUnit tests, compiled for a recent version of .NET Framework (e.g. .NET 4.7.1), the code of the tests is always executed at compatibility level of .NET Framework 4.5.x.

For example, tests that rely on TLS 1.2 being supported by default will fail.

## Steps to reproduce

  * Check out [Example](https://github.com/x2048/vstest-targetframework-issue).
  * cd ExampleTest
  * dotnet test

## Expected behavior

Test passes, see ConsoleApp in the same project, which runs exactly the same code outside the test host.

## Actual behavior

Test fails with error __"Could not create TLS/SSL secure channel"__

## Diagnostic logs

[log.txt](https://github.com/x2048/vstest-targetframework-issue/blob/master/ExampleTest/log.txt)
[log.host.*.txt](https://github.com/x2048/vstest-targetframework-issue/blob/master/ExampleTest/log.host.18-08-30_23-11-19_58156_1.txt)

## Environment
$ dotnet --info
.NET Core SDK (reflecting any global.json):
 Version:   2.1.301
 Commit:    59524873d6

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.14393
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\2.1.301\

Host (useful for support):
  Version: 2.1.1
  Commit:  6985b9f684

.NET Core SDKs installed:
  1.1.0 [C:\Program Files\dotnet\sdk]
  2.0.3 [C:\Program Files\dotnet\sdk]
  2.1.4 [C:\Program Files\dotnet\sdk]
  2.1.301 [C:\Program Files\dotnet\sdk]

.NET Core runtimes installed:
  Microsoft.AspNetCore.All 2.1.1 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.App 2.1.1 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 1.0.5 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 1.1.2 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.0.3 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.0.5 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.1 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]

Microsoft.NET.Test.SDK version: 15.8.0

**Comment by smadala** [comment]
@x2048 It is Adapter(xunit) responsibility to set right target framework while running tests. Can you please create an issue at https://github.com/xunit/xunit/issues .

FYI, MSTest V2 sets the right target framework, See the patch [mstest.txt](https://github.com/Microsoft/vstest/files/2404023/mstest.txt)
