### ISSUE TITLE
Avoid usage of JsonConvert in test host process

### ISSUE THREAD

**Issue by ObeA** [Microsoft/vstest#1757]
Putting the following code in a test case, or executing something like this some where in your application wil cause tests to run indefinitely. My guess it is messes up the communication with VSTest, because JsonConvert will fall back to the settings returned by JsonConvert.DefaultSettings.

```C#
JsonConvert.DefaultSettings = () => new JsonSerializerSettings
{
    ContractResolver = new DefaultContractResolver
    {
        NamingStrategy = new SnakeCaseNamingStrategy()
    }
}
```

I've found that JsonConvert is being called [here](https://github.com/Microsoft/vstest/blob/7b6248203164f8ea821f6795632bd22e0b69afb0/src/Microsoft.TestPlatform.CommunicationUtilities/JsonDataSerializer.cs#L113-L153). But replacing it with `this.Serialize()` doesn't solve the issue so I think it must be used somewhere in [TranslationLayer](https://github.com/Microsoft/vstest-docs/blob/master/RFCs/0008-TranslationLayer.md) package which isn't open-source(?).

**Comment by ShreyasRmsft** [comment]
@ObeA can you please provide us with a basic sample repro? Create a github repo with a bare minimum project where this repros and we'll take it from there.

**Comment by ObeA** [comment]
@ShreyasRmsft you can reproduce it by running the test case in https://github.com/ObeA/vstest-issue-1757.

**Comment by ShreyasRmsft** [comment]
@ObeA thanks, we'll get back to you on this.

**Comment by ObeA** [comment]
Great! Sounds excellent. Can you give any indication of when this should be fixed?

**Comment by ObeA** [comment]
@ShreyasRmsft any updates?

**Comment by svatal** [comment]
this issue in result crashes both Resharper and Rider
https://youtrack.jetbrains.com/issue/RSRP-471623

**Comment by abhishkk** [comment]
Fixed.
