### ISSUE TITLE
Test stack trace when exception is thrown from both try block and finally block

### ISSUE THREAD

**Issue by ShreyasRmsft** [Microsoft/vstest#1769]
## Description
> 

```
        public void TestMethod1()
        {
            try
            {
                throw new Exception("1");
            }
            finally
            {
                throw new Exception("2");
            }
        }
```

## Steps to reproduce
> Run the test in the provided solution. The stack trace only has info of the exception 2
> Run the same code in a console app and the stack trace points to the first exception

## Expected behavior
> Test stack trace should ideally have both exceptions listed and if this is not possible then the first exception is more important is it is the one causing the test to fail

## Actual behavior
> The stack trace in the test only has info of the exception 2

[TryFinallyDebacle.zip](https://github.com/Microsoft/vstest/files/2404354/TryFinallyDebacle.zip)

**Comment by smadala** [comment]
Console app prints `Exception("1")` stacktrace. But both the xunit and mstest v2 prints `Exception("2")` stack trace. This bug should be logged on adapter.

Below is console app output.

```
PS D:\g\public\vstest-targetframework-issue\ConsoleApp> dotnet run

Unhandled Exception: System.Exception: 1
   at ConsoleApp.Program.Main(String[] args)
PS D:\g\public\vstest-targetframework-issue\ConsoleApp>
```
