### ISSUE TITLE
FileExtension is not being respected

### ISSUE THREAD

**Issue by josepmc** [Microsoft/vstest#1772]
## Steps to reproduce
- Use the sample project encountered here: https://github.com/josepmc/githubtestadapter
- Run `dotnet test'

## Expected behavior
One test would be detected, and 'RunTest' would be diplayed in the console.

## Actual behavior
No tests are detected. If the 'FileExtension' is changed back to 'dll' then one test will be detected.

## Environment
- Windows 10

It's worth mentioning that this only happens in .NET Core adapters, as I do have a working adapter in .NET 4.6.2 and uses the same principle.

## Why is this relevant?
In order to run the tests in Azure DevOps, one needs to resort to VSTest in order to get the results uploaded and properly interpreted.
Furthermore, linking with the test management tool is only possible if the 'automation' is able to be run through VSTest.
This causes that if one wants to run any kind of tests that are not .NET-based in Azure Devops and sync with this (paid) product, one needs to build an adapter which targets other extension types.

**Comment by jayaranigarg** [comment]
@josepmc : Thank you for reaching out to us.

FileExtension Attribute is used to specify the extension of test binaries your TestAdapter can execute. Specifying  `[FileExtension(".xml")]` means that your CoreTestAdapter can only execute testcode written in xml files, but since your testcode i.e. UnitTestProject is generating output as '.dll' file, hence specifying '[FileExtension(".dll")]' works.

**Comment by josepmc** [comment]
@jayaranigarg Correct me if I'm wrong, but here are my assumptions;
- If we use the FileExtensionAttribute, then the platform will invoke the adapter for every file matching this Attribute (according to the parameters through which it was invoked).
- Once invoked, then it's up to the adapter to determine if that file contains a test or not. Another part of the adapter (the executor), will run the tests for the files passed-through and then report the results using the Platform-provided APIs.

This is how I built this adapter https://github.com/josepmc/ProtractorAdapter that targets .NET Framework 4.6.1, where I use the FileExtension attribute to indicate the filetype I want to target.

Now given these assumptions, I would understand that the framework should:
- Load up the adapter (which does) and associate it with a file type.
- When asked to run, round up all the files with the .xml extension and invoke the adapter for each of these.
- The adapter would then proceed to discover the tests and run them (if invoked like that).

Whilst this behavior occurs with .NET Framework 4.6.1, it doesn't with .NET Core (as shown in the example). This means, we're pretty much limited to get the tests running under Windows systems - which means we need to hack our way around if we want to run our tests under another OS.

If the adapter is not correct in some way to achieve the above results, could you please provide an example for this? The adapter is pretty much doing what's stated here https://github.com/Microsoft/vstest-docs/blob/master/RFCs/0004-Adapter-Extensibility.md#writing-an-adapter but as you can see that example is not working as intended.

**Comment by jayaranigarg** [comment]
@josepmc : Can you try moving to latest version of Nuget packages 
```  
<PackageReference Include="Microsoft.NET.Test.Sdk" Version="15.8.0" />
<PackageReference Include="MSTest.TestAdapter" Version="1.3.2" />
<PackageReference Include="MSTest.TestFramework" Version="1.3.2" />
```
and see if things work for you?

**Comment by josepmc** [comment]
@jayaranigarg: I tried to upgrade the packages (and updated the project) but I can't get it to detect the file. I am running the following commands:
```
<path>\UnitTestProject PS>dotnet test --test-adapter-path "<path>\UnitTestProject\bin\Debug\netcoreapp1.0"
Build started, please wait...
Build completed.

Test run for <path>\UnitTestProject\bin\Debug\netcoreapp1.0\UnitTestProject.dll(.NETCoreApp,Version=v1.0)
Microsoft (R) Test Execution Command Line Tool Version 15.8.0
Copyright (c) Microsoft Corporation.  All rights reserved.

Starting test execution, please wait...
No test is available in <path>\UnitTestProject\bin\Debug\netcoreapp1.0\UnitTestProject.dll. Make sure that test discoverer & executors are registered and platform & framework version settings are appropriate and try again
````

And directly with vsconsole, the result being the same:

```
& "C:\Program Files (x86)\Microsoft Visual Studio\2017\Professional\Common7\IDE\CommonExtensions\Microsoft\TestWindow\vstest.console.exe" File.xml /testadapterpath:"<path>\UnitTestProject\bin\Debug\netcoreapp1.0" /Framework:"FrameworkCore10"
```

**Comment by jayaranigarg** [comment]
@josepmc : You need to specify 
```
frameworkHandle.RecordResult(tr);
```
in your RunTests() methods to inform us(vstest runner) that there were some test results, otherwise it just assumes no tests ran as part of test run and prints "No test available" message.

![image](https://user-images.githubusercontent.com/17309452/46539255-9c419b00-c8d3-11e8-8a06-dfa4193d025a.png)

PS- "RunTests" message is being printed for me clearly signifying that your adapter indeed got called.

**Comment by josepmc** [comment]
@jayaranigarg The tests will run when you use the '.NET Framework' mode (e.g you pass --Framework:".NETFramework,Version=4.6.1" or any similar). But will fail whenever you use the **.NET Core** mode (e.g. you use --Framework:'.NETCore,Version=<any>').

The easiest way to reproduce this is to run it under *NIX systems, where .NET Framework is not going to be present (or in WSL).

Also, with the latest 15.9.0-dev there's apparently no way to get it working even when using the .NET Framework mode.

**Comment by jayaranigarg** [comment]
@josepmc : To run tests using `dotnet` , we need a TestProject.deps.json file to figure out the location of testhost.dll. In your case, since the source is an xml file, you should make sure that the name of your xml file is consistent with the name of *.deps.json file. 
Please try renaming File.xml to UnitTestProject.xml and see that you will get 'RunTests' message getting printed.

**Comment by josepmc** [comment]
@jayaranigarg Thanks! I can confirm that it does work like this now.
Is there a way to avoid having a .deps.json per each file? My adapter is meant to target .feature files, so I'd like to avoid having a script copying the same .deps.json next to every .feature that I want to have loaded.

**Comment by jayaranigarg** [comment]
@josepmc : Glad to know it worked for you. 

There is currently no way to avoid deps.json. In dotnet world, we need testhost.dll to run the tests and currently we figure out the location of testhost.dll from deps.json file only. This is how it has been designed. To de-couple these things, we will have to make some design changes on our end.

Tagging @singhsarab @mayankbansal018 @cltshivash to see if we want to make these changes.

**Comment by josepmc** [comment]
I am happy to use a deps.json for .NET Core. However, I believe it would make sense to support the flag `--additional-deps` that is supported by dotnet (but not MSTest).
Using that we could have one dependency per project (e.g point always to the same dependency file) instead of having to do something like `DEPS="$(pwd)/foo.deps.json" find -name "*.feature" -execdir sh -c 'cp $DEPS $(basename "{}" .feature).deps.json' \;` before executing the VSTest task in devops.

**Comment by josepmc** [comment]
For anyone coming across this issue, this is what you need to do:
- Create your .NET adapter, publish it to NuGet (if you want)
- Create a sample project (e.g. 'testProject') that just imports the .NET Adapter
- Build the project (you can use a nuget.config to get the dependencies into a folder). Take the .dll (e.g. testProject.dll), .deps.json, .runtimeconfig.json, .runtimeconfig.dev.json as you'll be using these as reference.
- For each custom file you have (e.g. .feature), you'll need to:
* Copy a renamed .deps.json, .runtimeconfig.json, .runtimeconfig.dev.json (e.g. if your file is labelled 'test.feature', then the files should be test.deps.json, test.runtimeconfig.json, test.runtimeconfig.dev.json)
* Copy both the compiled .dll (e.g. testProject.dll) and *your adapter* into the same folder where your test file is located.
* Run `dotnet vstest <your file> --Framework:".NETCoreApp,Version=2.0"`. The TestAdapterPath flag is ignored, and using the DOTNET_ADDITIONAL_DEPS flag is also not working for this.

Overall *if you can avoid it*, do it. You're better using the .NETFramework adapters. But if you need to use vstest in MacOS/Linux (e.g. Azure Devops, where VS2017 containers don't allow to use linux docker images), this may be your only option.
@jayaranigarg fyi ^.
