### ISSUE TITLE
dotnet test verbosity level for test output only

### ISSUE THREAD

**Issue by livarcocc** [Microsoft/vstest#1773]
_From @codefactorydevelopment on September 28, 2018 14:10_

If we want to have a list of tests passed in test suite (only overall stats), we need to use at least
`dotnet test -v n` 
verbosity level. But, that one comes with a whole bunch of build output info also.

It would be nice to have a verbosity level that would show tests that were run in suite but without all the build info.

_Copied from original issue: dotnet/cli#10063_

**Comment by jayaranigarg** [comment]
@codefactorydevelopment: you can specify  --logger:"console;verbosity=normal" in your arguments to dotnet test to show passed tests.
 Command would look like 
> dotnet test  Test.csproj --logger:"console;verbosity=normal"

**Comment by jayaranigarg** [comment]
Closing the thread. Please feel free to re-open if the above command didn't work for you.

**Comment by inkel** [comment]
It isn't really working for me:

```
dotnet test '--logger:console;verbosity=minimal' --verbosity quiet --filter FooBar
watch : Started
Build started, please wait...
/usr/local/share/dotnet/sdk/2.2.105/Sdks/Microsoft.NET.Sdk/targets/Microsoft.NET.Sdk.DefaultItems.targets(153,5): warning NETSDK1071: A PackageReference to 'Microsoft.AspNetCore.All' specified a Version of `2.2.2`. Specifying the version of this package is not recommended. For more information, see https://aka.ms/sdkimplicitrefs [/Users/inkel/foo/bar/bar.csproj]
Build completed.

Test run for /Users/inkel/dev/foo/bar/test/bar/bin/Debug/netcoreapp2.2/API.Tests.dll(.NETCoreApp,Version=v2.2)
Microsoft (R) Test Execution Command Line Tool Version 15.9.0
Copyright (c) Microsoft Corporation.  All rights reserved.

Starting test execution, please wait...

Total tests: 1. Passed: 1. Failed: 0. Skipped: 0.
Test Run Successful.
Test execution time: 7.0201 Seconds
```

I'm ok with leaving the build warning, but afterward, I only want to see this:

```
Total tests: 1. Passed: 1. Failed: 0. Skipped: 0.
Test Run Successful.
Test execution time: 7.0201 Seconds
```

Is that possible at all?

Note that I'm using `--verbosity quiet` which, according to `dotnet test -h` _set the MSBuild verbosity level_.

**Comment by vagisha-nidhi** [comment]
@inkel  The minimal verbosity level is `--verbosity quiet`, but this will show the below status as designed.
```
Test run for /Users/inkel/dev/foo/bar/test/bar/bin/Debug/netcoreapp2.2/API.Tests.dll(.NETCoreApp,Version=v2.2)
Microsoft (R) Test Execution Command Line Tool Version 15.9.0
Copyright (c) Microsoft Corporation.  All rights reserved.

Starting test execution, please wait...
```

**Comment by inkel** [comment]
@vagisha-nidhi so there's no way to remove the copyright notice? Bummer 😞

**Comment by zoechi** [comment]
I tried to silence log output but `dotnet test` (v2.2) doesn't seem to care at all about such parameters.

`dotnet test --filter DisplayName~InitDatabase_RunManually -l "console;verbosity=quiet" --verbosity quiet`

prints even all info level log output

**Comment by nohwnd** [comment]
You can remove the copyright notice by `--nologo`

**Comment by elninoisback** [comment]
> @vagisha-nidhi so there's no way to remove the copyright notice? Bummer 😞

You can pass --nologo 
It runs tests without displaying the Microsoft TestPlatform banner.

**Comment by C0DK** [comment]
If you look at test runners for other languages, they provide a lot better user experience from the terminal. However if you are running it in bash, it should be perhaps possible to filter the output with grep, yet I haven't found the best option yet.

**Comment by pubnoconst** [comment]
> If you look at test runners for other languages, they provide a lot better user experience from the terminal.

+1 to this, for a typical test summary should look like the following:

```
$ cargo test 
    Finished test [unoptimized + debuginfo] target(s) in 0.00s
     Running unittests src/lib.rs (target/debug/deps/either-f15afe36bccaae34)

running 8 tests
test basic ... ok
test error ... ok
test deref ... ok
test iter ... ok
test macros ... ok
test read_write ... ok
test seek ... ok
test should_fail ... FAILED

failures:

---- should_fail stdout ----
thread 'should_fail' panicked at 'assertion failed: `(left == right)`
  left: `1`,
 right: `3`', src/lib.rs:1342:5
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace


failures:
    should_fail

test result: FAILED. 7 passed; 1 failed; 0 ignored; 0 measured; 0 filtered out; finished in 0.00s

error: test failed, to rerun pass '--lib'
```
There should be no need to use grep hacks to see a summary of what passed and what failed.

**Comment by bpainter1** [comment]
I've been able to get some minimal output in my terminal using a command like this from PowerShell:

`dotnet build && clear && dotnet test --no-build --nologo --filter ConfigurationService`
