### ISSUE TITLE
vstest.console does not create a trx file when logger is used with LogFileName

### ISSUE THREAD

**Issue by jyotisingh100988** [Microsoft/vstest#1774]
When ever i run the below command without 'LogFileName' i can see a new .trx getting created in TestsResults Folder but When i use it there is no .trx file creating but the Log file get created
> vstest.console.exe /TestAdapterPath:"C:\...\tools" "C:\...\Test.dll"  /ResultsDirectory:"C:\...TestsResults" /logger:"trx;LogFileName=logFile.txt"

Can anyone please help. I have tried many combinations to make it work but nothing helps. I need to have both the file .trx and the log.txt file.

**Comment by jayaranigarg** [comment]
@jyotisingh100988 : Thank you for reaching out to us. 
LogFileName is just used to give a custom name/extension(.txt in your case) to your trx file that gets generated. You can't have both the trx file and LogFile.txt with same contents. Refer [this](https://github.com/Microsoft/vstest-docs/blob/master/docs/report.md#2-trx-logger) doc for detailed explanations.

However, if you want vstest.console.exe logs, you can pass /diag:logFile.txt switch to achieve that. Refer [this](https://github.com/Microsoft/vstest-docs/blob/master/docs/diagnose.md#collect-traces-using-command-line) doc here.
Let us know if this helps!

**Comment by jayaranigarg** [comment]
Closing the thread. Please feel free to re-open if the above comment didn't unblock you.
