### ISSUE TITLE
Re-Run failed tests using vstest command line options.

### ISSUE THREAD

**Issue by pMaske** [microsoft/vstest#1776]
I am trying to look for command line switches to pass to VSTest.console command to re-run the flaky failed tests. We have lot of tests that rely on real-time data and often times the tests will time out and fail. When re-run, they will most likely pass. I saw this [article](https://docs.microsoft.com/en-us/azure/devops/release-notes/2017/dec-11-vsts#identify-flaky-tests) and was wondering if this can achieved via vstest command run from command line.

cc @mayankbansal018 can you please direct my question to right team/person.

**Comment by pMaske** [comment]
I think it will be a very good enhancement. I think , if relevant tags are provided by platform, this could be easily be achieved by passing values to parameters in test settings file.

**Comment by pMaske** [comment]
@PBoraMSFT do you think this is a feasible enhancement?

**Comment by bergmeister** [comment]
Moving this feature into vstest would also be helpful to me because then we could add more parameters and tweak its behaviour. At the moment, because the code is in AzureDevOps, I cannot do that. I'd like to see options on what to do if a test had to be re-run, for example I'd like the test suite to be marked as orange instead of green to indicate that tests were ok but still need to be looked into at some point

**Comment by kiragengis** [comment]
I think this would be really helpful. Right now I created my own piece of software only to call the vstest.console and receive the results. If it was the first failure, convert the output to: failed-'NameOfMethod' if it was the second time report the output to TeamCity.
I really appreciate if you handle this.

**Comment by HeikeHofmann** [comment]
This would be a really helpful feature. We use testplatform in combination with cakebuild. And we have for example one project with 33k Unittests, where sometimes 1-2 Unittests fail through random Timing Problems.
It is frustrating, that this flaky Unittests broke often release builds.

**Comment by nirasher1** [comment]
This would be a very heplful feature also for me.
@Sanan07 Do you have an estimated time for the feature to be released?

**Comment by Sanan07** [comment]
@nirasher1 I can't say for now, we still need discussion with the team, if it makes sense to implement on our side. If so, I assume, not earlier that the beginning of the next year.

**Comment by ffMathy** [comment]
The Pruner CLI makes this possible.

https://github.com/pruner/cli

**Comment by cocolucio** [comment]
hi all, any update on this feature

**Comment by nohwnd** [comment]
This is a new feature and won't be implemented, we are focusing on adding new features to Testing.Platform instead. https://aka.ms/testingplatform
