### ISSUE TITLE
Microsoft.TestPlatform.TestHost NetStandard is missing Utilities and CrossPlatEngine assemblies

### ISSUE THREAD

**Issue by dotMorten** [Microsoft/vstest#1790]
## Description
The NuGet Package Microsoft.TestPlatform.TestHost v15.8.0 has a `Microsoft.TestPlatform.Utilities.dll` dll in the UAP10.0 folder, but this is missing in the netstandard1.5 folder. The result of this is when using the package on anything but UAP10.0 or net45+, you get the following compilation error:

```
C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\MSBuild\Xamarin\Android\Xamarin.Android.Common.targets(1830,2): error XA2002: Can not resolve reference: `Microsoft.TestPlatform.Utilities`, referenced by `Microsoft.TestPlatform.CrossPlatEngine`. Please add a NuGet package or assembly reference for `Microsoft.TestPlatform.Utilities`, or remove the reference to `Microsoft.TestPlatform.CrossPlatEngine`.
C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\MSBuild\Xamarin\Android\Xamarin.Android.Common.targets(1830,2): error XA2002: Can not resolve reference: `Microsoft.TestPlatform.Utilities`, referenced by `Microsoft.VisualStudio.TestPlatform.Common`. Please add a NuGet package or assembly reference for `Microsoft.TestPlatform.Utilities`, or remove the reference to `Microsoft.VisualStudio.TestPlatform.Common`.

```

## Steps to reproduce
Create a Xamarin.Android application and reference the nuget package and some code hitting the code-path. Compile.

## Expected behavior
Build completes.

## Actual behavior
Build error: Can't 

## Environment
Visual Studio 15.8.6, Win10 1809 x64

**Comment by mayankbansal018** [comment]
@dotMorten , `Microsoft.TestPlatform.Utilities.dll` shouldn't be a build time dependency, can you please share the exact build errors you are facing?

**Comment by dotMorten** [comment]
The repro steps are:
1. `File->New Project-> Android App (Xamarin)`
2. Add NuGet package `Microsoft.TestPlatform.TestHost NetStandard`
3. Compile

You'll get these build errors:

```
1>------ Build started: Project: MSTestRepro, Configuration: Debug Any CPU ------
1>  MSTestRepro -> C:\Users\mn\Documents\Visual Studio 2017\Projects\MSTestRepro\MSTestRepro\bin\Debug\MSTestRepro.dll
1>C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\MSBuild\Xamarin\Android\Xamarin.Android.Common.targets(1830,2): error XA2002: Can not resolve reference: `Microsoft.VisualStudio.TestPlatform.ObjectModel`, referenced by `Microsoft.TestPlatform.CommunicationUtilities`. Please add a NuGet package or assembly reference for `Microsoft.VisualStudio.TestPlatform.ObjectModel`, or remove the reference to `Microsoft.TestPlatform.CommunicationUtilities`.
1>C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\MSBuild\Xamarin\Android\Xamarin.Android.Common.targets(1830,2): error XA2002: Can not resolve reference: `Microsoft.VisualStudio.TestPlatform.ObjectModel`, referenced by `Microsoft.TestPlatform.CrossPlatEngine`. Please add a NuGet package or assembly reference for `Microsoft.VisualStudio.TestPlatform.ObjectModel`, or remove the reference to `Microsoft.TestPlatform.CrossPlatEngine`.
1>C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\MSBuild\Xamarin\Android\Xamarin.Android.Common.targets(1830,2): error XA2002: Can not resolve reference: `Microsoft.VisualStudio.TestPlatform.ObjectModel`, referenced by `Microsoft.VisualStudio.TestPlatform.Common`. Please add a NuGet package or assembly reference for `Microsoft.VisualStudio.TestPlatform.ObjectModel`, or remove the reference to `Microsoft.VisualStudio.TestPlatform.Common`.
1>C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\MSBuild\Xamarin\Android\Xamarin.Android.Common.targets(1830,2): error XA2002: Can not resolve reference: `Microsoft.TestPlatform.PlatformAbstractions`, referenced by `testhost`. Please add a NuGet package or assembly reference for `Microsoft.TestPlatform.PlatformAbstractions`, or remove the reference to `testhost`.
========== Build: 0 succeeded, 1 failed, 0 up-to-date, 0 skipped ==========
```

**Comment by mayankbansal018** [comment]
@dotMorten , I tried the above steps & could repro the issue, but I would suggest that you please use [Microsoft.NET.Test.Sdk](https://www.nuget.org/packages/Microsoft.NET.Test.SDK) to take reference for test platform, as this brings in the required dependencies for test platform.

I could build the android app successfully after taking reference of `Microsoft.NET.Test.Sdk`

**Comment by mayankbansal018** [comment]
@dotMorten any update on this?

**Comment by mayankbansal018** [comment]
@dotMorten , I'm closing this issue with solution suggested above, please comment back here, if you think it needs to be discussed further.

**Comment by dotMorten** [comment]
Sorry I dropped the ball on this and never responded. Could we reopen this, as changing the project type really isn't an option when building a test runner host app for Xamarin.
If you look in the nuget package's `netstandard1.5` folder you'll find the 4 assemblies:

- `Microsoft.TestPlatform.CommunicationUtilities.dll`
- `Microsoft.TestPlatform.CrossPlatEngine.dll`
- `Microsoft.VisualStudio.TestPlatform.Common.dll`
- 'testhost,dll`

However CrossPlatEngine has a dependency on `Microsoft.TestPlatform.Utilities.dll` which isn't in this folder. It is however in the UAP folder, and the build issue is resolved by manually referencing this (which of course isn't an viable option when working with nuget packages)
You can clearly see in the project file that this is a required dependency: https://github.com/Microsoft/vstest/blob/master/src/Microsoft.TestPlatform.CrossPlatEngine/Microsoft.TestPlatform.CrossPlatEngine.csproj#L24

WIthout fixing this, we can't hope to build a Xamarin app that uses VSTest's testhost, so that we can integrate VSTest.Console with Xamarin.

**Comment by dotMorten** [comment]
I also no understand why your proposed "fix" resolves the issue for you: It's because it's the equivalent of not adding a package reference at all, so it wouldn't really do anything.

**Comment by mayankbansal018** [comment]
>If this was fixed, all I have to do is call Microsoft.VisualStudio.TestPlatform.TestExecutor.UnitTestClient.Run("...") to make my Android or iOS app a remote test client app, similar to UWP. 

Thanks, I probably did not try it out with this last time I was compiling by taking reference to `Microsoft.NET.Test.Sdk`, also it makes sense that it's on no use for Xamarin based apps, since it has no target for netstandard. The reason I was suggesting it was because we want to have a common nuget package, which is referred by every test project.

_I would really like to change `Microsoft.NET.Test.Sdk` nuget itself to allow building for netstandard as well._

@singhsarab, @cltshivash thoughts on _above_?

**Comment by dotMorten** [comment]
> I would really like to change Microsoft.NET.Test.Sdk nuget itself to allow building for netstandard as well

That could work too

**Comment by mayankbansal018** [comment]
>However since all the Test SDK package does is adding a dependency to Microsoft.TestPlatform.TestHost, we still would need to fix that package to begin with.

Agreed on this, please give me sometime to discuss this with other team members. We have other similar changes going on, regarding how we want to acquire test platform dependencies for other scenarios(netcore, UWP, fullCLR), & this falls in same line

**Comment by mayankbansal018** [comment]
@dotMorten we had a discussion for this internally, & it makes sense to enhance Microsoft.NET.Test.Sdk to target ".NetStandard1.4" as needed for Xamarin apps.

It would be helpful if can raise a PR for the same.
