### ISSUE TITLE
Make TRXLogger public

### ISSUE THREAD

**Issue by dotMorten** [Microsoft/vstest#1791]
## Description

In order for other test runners or frameworks to generate TRX reports, it would be useful if the TrxLogger class, it's default constructor and Initialize method were made public and published in a NuGet Package (with .NET Standard support).
I successfully referenced the TRX Logger source code myself and called these two methods, and was able to generate TRX Reports with just these two members.

**Comment by smadala** [comment]
@dotMorten Are you planning to create PR for creating NuGet package?

**Comment by dotMorten** [comment]
@smadala I could, if you can tell me where to start

**Comment by smadala** [comment]
@dotMorten Nuspec file location is https://github.com/Microsoft/vstest/tree/master/src/package/nuspec .
After build.cmd `.\artifacts\Debug\packages` location contains nuget packages.
