### ISSUE TITLE
Add "!~" operator to test filter

### ISSUE THREAD

**Issue by livarcocc** [Microsoft/vstest#1794]
_From @mano-cz on October 10, 2018 8:12_

## Steps to reproduce
run "dotnet test Some.csproj --filter FullyQualifiedName!~Some.Namespace"

## Expected  behavior
Not contain operator will work.

## Actual behavior
Not contain operator is not implemented yet.

## Use case
Parallelization of test execution according to namespaces e.g.:
#1 thread - filter on few namespaces
#2 thread - filter on other few namespaces
#3 thread - filter on remaining (dynamic) namespaces (with usage of !~ operator on namespaces from previewous threads)

_Copied from original issue: dotnet/cli#10149_

**Comment by mayankbansal018** [comment]
@mano-cz, we don't support similar to(~) operator, with not(!), however we support similar(~). For more queries related to filters please go through https://github.com/Microsoft/vstest-docs/blob/master/docs/filter.md

However if you exact ask is !~, that would be an enhancement on our part

**Comment by hgran** [comment]
Issue #1385 describes the same functionality.

**Comment by baruchiro** [comment]
How can I know if my `dotnet vstest` supports this?

```bash
$: dotnet vstest

--TestCaseFilter|/TestCaseFilter:<Expression>
      Run tests that match the given expression.
      <Expression> is of the format <property>Operator<value>[|&<Expression>]
         where Operator is one of =, != or ~  (Operator ~ has 'contains'
         semantics and is applicable for string properties like DisplayName).
         Parenthesis () can be used to group sub-expressions.
      Examples: /TestCaseFilter:"Priority=1"
                /TestCaseFilter:"(FullyQualifiedName~Nightly
                                  |Name=MyTestMethod)"
```

And how can I get this change?

**Comment by baruchiro** [comment]
Sorry, my problem was unupgraded `Microsoft.sdk.Test` nuget.
