### ISSUE TITLE
Setting environment variables for tests

### ISSUE THREAD

**Issue by livarcocc** [Microsoft/vstest#1795]
_From @bbc2 on October 10, 2018 9:47_

Environment variables can be set for `dotnet run` with `launchSettings.json`.  However, I couldn't find an equivalent for `dotnet test`.  Does that exist?  If not, would adding it be considered?

My use case is the setting of `CORECLR_*` environment variables for attaching a profiler to the CoreCLR.  You can set the variables before calling `dotnet` but then you end up also profiling the CLI itself, not just your executable or your tests.  That's why the `--launch-profile` option is useful in this case, but it only applies to `dotnet run` as far as I'm aware.

_Copied from original issue: dotnet/cli#10150_

**Comment by kaadhina** [comment]
Thank you for your feedback, but please note that for profiling scenarios, we recommend using data collection, which sets env vars on top of testhost where the tests are actually run.
Here is a link that can help you get started: https://github.com/Microsoft/vstest-docs/blob/master/docs/extensions/datacollector.md

**Comment by bbc2** [comment]
That's interesting, thanks!  I didn't know about data collectors.  It's more complicated than defining environment variables in a JSON file but it works:

```c#
    public IEnumerable<KeyValuePair<string, string>> GetTestExecutionEnvironmentVariables()
    {
        return new List<KeyValuePair<string, string>> {
            new KeyValuePair<string, string>("CORECLR_ENABLE_PROFILING", "1"),
            new KeyValuePair<string, string>("CORECLR_PROFILER", "{guid-of-the-profiler}"),
            new KeyValuePair<string, string>("CORECLR_PROFILER_PATH", "/path/to/profiler")
        };
    }
```

```xml
<?xml version="1.0" encoding="utf-8"?>
<RunSettings>
  <RunConfiguration>
    <TestAdaptersPaths>/path/to/the/data/collector/dll</TestAdaptersPaths>
  </RunConfiguration>
  <DataCollectionRunSettings>
    <DataCollectors>
      <DataCollector friendlyName="friendlyNameOfTheCollector">
      </DataCollector>
    </DataCollectors>
  </DataCollectionRunSettings>
</RunSettings>
```

It worked on Linux but not WIndows (for some reason unrelated to profiling: `System.IO.FileNotFoundException: Could not load file or assembly 'System.Runtime.Extensions [...]'`).  I think I'll open a separate issue for that.

**Comment by kaadhina** [comment]
Glad this helped. Yes, please go ahead and open another issue if you face any.
