### ISSUE TITLE
VS Test task fails for data-driven tests that use TestCase as data source

### ISSUE THREAD

**Issue by NDDeveloper13** [Microsoft/vstest#1796]
I have the following setup:
- Compiled my solution with my test assemblies in 15.9.0 Preview 3 (I have also tried 15.8.6)
- VSTS Agent version 2.141.0 (I have also tried other agent versions including 2.140.2)
- Test agents are Win10 OS
- On-Premise TFS 2018 Update 3

I have a release definition with the following steps:
- VsTest Platform Installer installing the latest pre-release (15.9.0)
- Copy Test Assemblies - copies assemblies from a drop location to the agent
- Visual Studio Test - runs tests from a test plan

I have followed the instructions listed here and created the Test.TestCaseAccessToken variable for my release definition:
https://docs.microsoft.com/en-us/visualstudio/releasenotes/tfs2018-update1#testpipeline

The Visual Studio Test task fails for test cases that have the DataSource as Microsoft.VisualStudio.TestTools.DataSource.TestCase are failing with the following error:
The unit test adapter failed to connect to the data source or to read the data. Could not load file or assembly 'Microsoft.TeamFoundation.TestManagement.Controller or one of its dependencies. The system cannot find the file specified.

Upon putting the missing dlls (there are 9 of them) into the C:\agent_work_tool\VsTest\15.9.0\x64\tools\net451\Common7\IDE\Extensions\TestPlatform folder on the agent, I get around those missing assemblies errors. However, I get to this error and don't know how to move further:
The unit test adapter failed to connect to the data source or to read the data. Error details: Object reference not set to an instance of an object.

I have attempted running the test using vstestconsole.exe via command line and I get the same results. However, if I run the test locally within my Visual Studio IDE, the test passes as expected.

Here is the log data from the release logs for the VS Test task:
[ReleaseVSTestTaskLog.txt](https://github.com/Microsoft/vstest/files/2466515/ReleaseVSTestTaskLog.txt)
I am aware of the warnings about missing assemblies in the logs - I get these warnings in tests that pass also, so I'm assuming that is not the issue.

I am not comfortable posting the vstest.console logs here. If you need additional logs, please provide me with an email address to send them to.

**Comment by abhishkk** [comment]
@NDDeveloper13 There were various issues in test case data driven based tests. We have resolved them in 15.9 preview 4 which will be publicly available on 23rd October.

> Upon putting the missing dlls (there are 9 of them) into the C:\agent_work_tool\VsTest\15.9.0\x64\tools\net451\Common7\IDE\Extensions\TestPlatform folder on the agent, I get around those missing assemblies errors

You don't need to do this when you try in 15.9 preview 4 once available.

> The unit test adapter failed to connect to the data source or to read the data. Error details: Object reference not set to an instance of an object.

You will be able to resolve this issue with 15.9 preview 4 along with using Test.TestCaseAccessToken variable.

Closing this issue for now. Please re-open in case you face any issues in 15.9 preview 4.

**Comment by NDDeveloper13** [comment]
We are still working with old VS 2013 test controllers and test agents and have been trying to upgrade to use build/release definitions for years, but have been unable to because all of the features supported with lab center and automated testing within MTM were not supported with build/release definitions. The last piece of it was data-driven testing.  

TFS 2018 RTW release notes states:
"Support for Lab Center and automated testing flows in Microsoft Test Manager has been removed."
https://docs.microsoft.com/en-us/visualstudio/releasenotes/tfs2018-relnotes#features-removed-in-tfs-2018-rtw

With XAML builds reintroduced back in 2018 Update 2, I was hoping Lab Center and automated testing flows in MTM were added back as well, but it appears not to be, according to the exception I get when attempting to add the lab environment to TFS 2018:
(QTController.exe, PID 12084, Thread 9) DEPLOY: PollDeploymentRuns : Handled Exception System.NotSupportedException: Using a test controller with Team Foundation Server 2018 for creating and managing Lab environments is no longer supported. You can use Build and Release Management for automated testing. Refer to https://aka.ms/xiu7ff for more details. --->

We are blocked from upgrading to TFS 2018, as a large percentage of our tests are data driven via test case. I was originally told that data-driven testing was fixed in VS 2017 Update 6, then VS 2013 Update 9 preview 3, now yet another later version. We have been blocked from upgrading to TFS 2018 because of this issue.

**Comment by NDDeveloper13** [comment]
I have come up with a solution that removes the dependency on a fix being available for data driven tests using test cases. I'm posting it here so that maybe it will be useful to someone else.

1. Remove the DataSource attribute for data-driven tests using test cases and replace with this:
    [TestProperty("DataSourceTestCaseId", "52550")]
2. In your test initialize, put the following code:
if (TestContext.Properties["DataSourceTestCaseId"] != null)
{
        PopulateTestData(int.Parse(TestContext.Properties["DataSourceTestCaseId"].ToString()));
}
`
			

		private void PopulateTestData(int testCaseId)
		{
			//Get the test case data via TFS
			List<DataRow> testCaseDataRows;
			using (TfsTeamProjectCollection collection = new TfsTeamProjectCollection(
				TfsTeamProjectCollection.GetFullyQualifiedUriForName(ConfigurationManager.AppSettings["TFSServerURL"])))
			{
				ITestManagementService tcmService = collection.GetService<ITestManagementService>();
				ITestManagementTeamProject project = tcmService.GetTeamProject(ConfigurationManager.AppSettings["TFSProject"]);
				DataSet testCaseDataSet = project.TestCases.Find(testCaseId).DataReadOnly;
				testCaseDataRows = testCaseDataSet.Tables[0].Rows.OfType<DataRow>().ToList();
			}

			//Set the DataRow property - it is read only, so need to use reflection in order to do this
			FieldInfo fieldInfo = TestContext.GetType().GetRuntimeFields().First(x => x.Name.Contains("dataRow"));
			fieldInfo.SetValue(TestContext, testCaseDataRows[0]);
		}

`

NOTE: We use test case parameters as a way to easily swap out data without a code change, and we currently don't have a case where we have multiple rows of data. This solution will not work if you have multiple rows of data. If you do have multiple rows of data, instead of setting the TestContext.DataRow, you could potentially set an entirely different TestContext property with the List<DataRow> object and have your test case manually iterate through the rows, but of course you will lose everything that comes along with the automatic iteration of rows which is the point of the DataSource attribute. Hopefully the data driven test issues are fixed soon.
