### ISSUE TITLE
vstest language setting

### ISSUE THREAD

**Issue by maxime645** [Microsoft/vstest#1797]
I am currently working on a script to run some Unit Tests for a precommit hook. Everything works fine, except for the display language of vstest is in French. Everytime I run my script with git bash, there is this message that comes up "▒chec de la s▒rie de tests." (for "tests failed"). Used with VS17, I get the following message "Unable to translate bytes [90] at index 0 from specified code page to Unicode." on commit. I am guessing the two issues are related.

There is clearly an encoding issue on my side. The thing is, it would actually be better if this message was in English, but I don't know how to do that. Do you have any lead ? Otherwise, do you know how I could get my encoding issue fixed ? I didn't managed to find how to do it.

I am running on Windows 8.1 in French and VS17 in English.

**Comment by mayankbansal018** [comment]
@maxime645 Can you please set env variable `DOTNET_CLI_UI_LANGUAGE=en-US`, at system level, & then restart VS, it should display information in English

**Comment by maxime645** [comment]
That didn't do the trick, results are still in French...

Here is a screen that might help understand my situation

![image](https://user-images.githubusercontent.com/42465940/47088015-ca9d6f80-d21d-11e8-867d-e75dd2ed74ff.png)

**Comment by maxime645** [comment]
That didn't do the trick, results are still in French...

**Comment by mayankbansal018** [comment]
@maxime645 ,Can you please share the VS version, I believe our changes to honor this var went in the VS2017 update 9, if you are on update 8, then it won't work.

Alternatively you can download [Testplatform nuget](https://www.nuget.org/packages/Microsoft.TestPlatform/15.9.0), & try to do the same. You can find vstest.console at "tools\net451\Common7\IDE\Extensions\TestPlatform" inside the nuget

**Comment by maxime645** [comment]
I am on 15.8.2

I'll try that workaround thanks

**Comment by mayankbansal018** [comment]
@maxime645 any update on this?

**Comment by mayankbansal018** [comment]
@maxime645 , closing this issue for now, please comment again for reopening, if the above solution doesn't work for you.

**Comment by maxime645** [comment]
Sorry for the timing @mayankbansal018, I did not have time until today to try.
My project is still using .NET 4.5, so I can't even install the latest package. Would this work with a previous version?

**Comment by mayankbansal018** [comment]
Yes, the package will work irrespective of the .net version you are using for your test/product assemblies.
 
Follow https://github.com/Microsoft/vstest/issues/1797#issuecomment-430623602 to see how you can use that package as standalone.

**Comment by maxime645** [comment]
It works well with this package.
The only thing that bother me is that I need to update the target version of .Net from 4.5 to 4.5.1.
I suppose there is no solution to avoid that ?

Anyway, thanks a lot for your time

**Comment by mayankbansal018** [comment]
@maxime645 good to know that your issue got resolved.
