### ISSUE TITLE
v15.9.0 release info missing

### ISSUE THREAD

**Issue by SIkebe** [Microsoft/vstest#1798]
## Description
Microsoft.NET.Test.Sdk v15.9.0 seems to have been released 1 week ago.
https://www.nuget.org/packages/Microsoft.NET.Test.Sdk/15.9.0

However the release page in this repo doesn't have that version.

**Comment by mayankbansal018** [comment]
added [release info]( https://github.com/Microsoft/vstest/releases/tag/v15.9.0)
