### ISSUE TITLE
v15.9.0 shows wrong version

### ISSUE THREAD

**Issue by SIkebe** [Microsoft/vstest#1799]
## Description
Microsoft.NET.Test.Sdk v15.9.0 shows wrong version in console.

## How to repro
```
dotnet new xuint
dotnet add package Microsoft.NET.Test.Sdk --version 15.9.0
dotnet test
```

## Expected behavior
```
Microsoft (R) Test Execution Command Line Tool Version 15.9.0
Copyright (c) Microsoft Corporation.  All rights reserved.
```

## Actual behavior
```
Microsoft (R) Test Execution Command Line Tool Version 15.8.0
Copyright (c) Microsoft Corporation.  All rights reserved.
```

**Comment by singhsarab** [comment]
@SIkebe This version for the command line tool is *NOT* the same as the Microsoft.Net.Test.Sdk version. This is the version of the test platform component that gets shipped with dotnet cli.
Installing the latest dotnet SDK should update this version.

**Comment by SIkebe** [comment]
Thank you for clarification! I found this.
https://github.com/dotnet/cli/blob/v2.1.403/build/DependencyVersions.props#L56
