### ISSUE TITLE
Suggestion: remove extra summary result from Data Driven tests

### ISSUE THREAD

**Issue by kendrahavens** [microsoft/vstest#1808]
### Summary
Data Driven tests give an extra result that is the sum of all the data driven tests. So if all are passing then the summary test passes, if one fails then the summary test also fails. We got [some feedback](https://twitter.com/kitokeboo/status/1053372805096427520) that this extra result was confusing and does not provide them much value.

> If the test fails, I am only about which set of input data caused the failure. A comment on this docs would also help eliminate the confusion.

We can [document ](https://github.com/MicrosoftDocs/visualstudio-docs/issues/1715)this behavior, but have we considered taking it out? Have we received contradictory feedback?

**Comment by mayankbansal018** [comment]
@PBoraMSFT , @pvlakshm to take a call

**Comment by divais** [comment]
Hi Kendra, 
The basic principle of Data driver or ordered tests is if all are passing then it passes, if one fails then it also fails. Other than a customer feedback, can you share other reasons why should this change?

**Comment by Evangelink** [comment]
Memo: test if that's correctly fixed.

**Comment by Evangelink** [comment]
I have just checked and we now correctly display only 1 test in the result.
