### ISSUE TITLE
VsTest.Console: Behavior changes from 15.8.0 to 15.9.0

### ISSUE THREAD

**Issue by csoltenborn** [Microsoft/vstest#1809]
## Description
Switching the end-to-end tests of [GoogleTestAdapter](https://github.com/csoltenborn/GoogleTestAdapter) to VsTest.Console 15.9.0 shows two kinds of behavioral changes:
* With 15.8.0, if a test run would not result in any test cases (e.g. because no test case filter matched), no output `.trx` file had been produced. Now, a file is produced, pointing out that the test run has been completed, but no tests have been run. Note that I consider this not a bug, but an improvement, but still thought I'd mention it.
* However, there seems to be a regression concerning the `className` attributes of the `<TestMethod>` nodes: In many cases, they now seem to contain the test executable's name (without file extension).

## Steps to reproduce
My end-to-end tests compare the resulting `.trx` file of a certain invocation of VsTest.Console with a golden file. The differences between V15.8.0 and 15.9.0 are shown in [this commit](https://github.com/csoltenborn/GoogleTestAdapter/commit/0fc2e571004355ef788b4f66bb322f187b24c96c), which contains the golden files after being updated to make the tests pass with 15.9.0 (i.e., they now contain the erronous `className`s).

In case you would like to run the tests yourself, refer to the description at #1805.

## Expected behavior
The `className` attributes should contain the same values as with V15.8.0.

## Diagnostic logs
The output of VsTest.Console.exe when running the the failing tests can be seen at [this CI build](https://ci.appveyor.com/project/csoltenborn/googletestadapter-u1cxh/builds/19673710) (the artifacts of which also contain diff files of the broken tests' golden files).

## Environment
VsTest.Console.exe V15.9.0 as consumed through https://www.nuget.org/packages/Microsoft.TestPlatform/.

**Comment by mayankbansal018** [comment]
@csoltenborn , since you have closed the other issues(#1805), is this still valid? As you know the fix is available in VS 15.9.0 which will be available in next VS update(15.9).

**Comment by csoltenborn** [comment]
This issue (#1809) is valid. In #1805, as I wrote, I was surprised to learn that the patch would only go into 15.9.0, and that VS is still delivered with the bug, but that's how it is, I suppose....

**Comment by mayankbansal018** [comment]
@csoltenborn , please try with latest vstest.console, the issue should have been fixed. Please ping back if it is still valid
