### ISSUE TITLE
Data-Driven Unit Tests Failing

### ISSUE THREAD

**Issue by Mastahh** [Microsoft/vstest#1810]
Hi,

I have CodedUi Test projects and it is uses following sources
[DataSource("Microsoft.VisualStudio.TestTools.DataSource.TestCase", "https://tfs.xxxxx.com/Development 4.0/;ProjectName", "2873", DataAccessMethod.Sequential)]

We just upgraded to TFS 2017 and all tests which we were running using XAML Build and MTM 2012 stoped working, only we can run tests from VS.

Each time when I run tests using VsTest I have error

**Error Message:
 The unit test adapter failed to connect to the data source or to read the data. For more information on troubleshooting this error, see "Troubleshooting Data-Driven Unit Tests" (https://go.microsoft.com/fwlink/?LinkId=62412) in the MSDN Library.
Error details: Could not load file or assembly 'Microsoft.TeamFoundation.TestManagement.Controller, PublicKeyToken=b03f5f7f11d50a3a' or one of its dependencies. The system cannot find the file specified.**

I tried do copy all missing DLLs to 

**C:\vstagent_test\_work\_tool\VsTest\15.9.0-preview-20180924-03\x64\tools\net451\Common7\IDE\Extensions\TestPlatform**

But it is also do not work, then i have another error

**Error details: Unable to cast object of type 'Microsoft.TeamFoundation.TestManagement.Controller.TestCaseDataConnection' to type 'Microsoft.VisualStudio.TestTools.Utility.TestDataConnection'.**

Does anybody have DataDriven tests working with VsTest?

**Comment by Mastahh** [comment]
> 
> 
> @Mastahh are you running these test locally or using build vnext? if you are using buildvnext which task are you using?

I'm using vNext Build and run it using Vstest Platform Installer and then VS Test to run tests.

Also I have a *.bat file to run tests locally, and it is works same way and also failing with same error.

I run this Agent with parameters
C:\vstagent_test\_work\_tool\VsTest\16.0.0-preview-20181205-02\x64\tools\net451\Common7\IDE\Extensions\TestPlatform\vsTest.console

**Comment by acesiddhu** [comment]
@Mastahh thanks for the info. Unfortunately running test case data driving test is not supported via test tools installer and https://www.nuget.org/packages/Microsoft.TestPlatform nuget package. you need to have full VS installed to run these test cases.

**Comment by Mastahh** [comment]
At the moment I'm moving Test Data from TFS to SQL Server and plan to access this parameters same way as it was done for TFS.
I Just changed DataSourceAttribute to access SQL Server and it is working for now.

I'm do not want to install VS Enterprise on Test PC only for Test Run :)

**Comment by acesiddhu** [comment]
@Mastahh the only thing which is not supported by tools installer and the nuget packages is Microsoft.VisualStudio.TestTools.DataSource.TestCase.
Accessing data from sql will work for you as you mentioned.

There are any plans to support DataSource = Microsoft.VisualStudio.TestTools.DataSource.TestCase in the nuget package/Tools installer.

/cc: @PBoraMSFT
