### ISSUE TITLE
Programatically Run/Ignore Tests Plugin

### ISSUE THREAD

**Issue by grizzle2101** [microsoft/vstest#1818]
Hey Guys,

I am looking to see if there is a way to programatically run or ignore tests based on a CSV. We have something working with NUnit where we intercept the test before running to check if the name exists then call run or ignore.
Any solution we've come across for VSTest has been create a Custom Attribute, or inheriting from a Base Test which sets up the ignore/run, however these solutions pollute our tests & add overhead.
Wondering if this is something you guys have in the backlog or already exists?

**Comment by cltshivash** [comment]
@grizzle2101 We don;t have this execution extensibility at the test platform level. The extensibility exists in the test framework (mstest).

**Comment by singhsarab** [comment]
@grizzle2101 We are trying to run through all the issues and prepare a backlog of important issues. Is this still an important ask?

To make Shiva's comment more clear, the test platform is the vstest.console runner in this case. By framework he means, the test framework and adapter being used to author and eventually run the tests.
This ask seems to be MSTest framework specific, reason he wanted to differentiate between the two.

This repo has code for Test platform, you should use https://github.com/microsoft/testfx for framework related asks.

**Comment by nohwnd** [comment]
This is a new feature and won't be implemented, we are focusing on adding new features to Testing.Platform instead. https://aka.ms/testingplatform
