### ISSUE TITLE
Can't call target with multiple dlls in TargetPath unlike the CLI

### ISSUE THREAD

**Issue by NinoFloris** [microsoft/vstest#1820]
## Steps to reproduce
> What steps can reproduce the defect?
> Please share the setup, commandline for vstest.console, sample project, target
> framework etc.

```
dotnet msbuild /t:Test /p:VSTestNoBuild=true /p:TargetPath="../Project1/bin/Debug/netcoreapp2.1/Project1.dll ../Project2/bin/Debug/netcoreapp2.1/Project2.dll"
```
Won't work while it does in the CLI.
Going via the TestProjects route gives different behavior as vstest is basically started twice in that case. Fixing or having an option to have that do the other behavior would solve it too!

```
<Project>
    <ItemGroup>
        <TestProjects Include="../Project1/*.csproj;../Project2/*.fsproj" />
        <Watch Include="../**/*.cs;../**/*.fs;../**/*.?proj;../**/*.resx" />
    </ItemGroup>

    <Target Name="Test">
        <MSBuild Targets="VSTest" Projects="@(TestProjects)" />
    </Target>

    <Import Project="$(MSBuildExtensionsPath)/Microsoft.Common.targets" />
</Project>
```

EDIT:
Interestingly running this target file with or without `/p:VSTestNoBuild=true` changes the workings completely. Running without that prop my second project gets built and then msbuild exits before running tests on that project. While if I run the target with `/p:VSTestNoBuild=true` I see both of them get run sequentially, not entirely how I would like it but not wildly incorrect behavior like the former.

Also to expand, my end goal is to be able to correctly run dotnet watch with multiple TestProjects, as performant as possible.

## Expected behavior
> Share the expected output
```
Total tests: 100. Passed: 100. Failed: 0. Skipped: 0.
Test Run Successful.
Test execution time: 1.8733 Seconds
```

## Actual behavior
> What is the behavior observed?
```
Total tests: 50. Passed: 41. Failed: 0. Skipped: 0.
Test Run Successful.
Test execution time: 1.0097 Seconds

[...]

Total tests: 41. Passed: 41. Failed: 0. Skipped: 0.
Test Run Successful.
Test execution time: 1.0097 Seconds
```

## Environment
> Please share additional details about the test environment.
> Operating system, Build version of vstest.console
macOS Mojave — 2.1.403 sdk

**Comment by NinoFloris** [comment]
So why is the sample pointing me to do it like this?
https://docs.microsoft.com/en-us/aspnet/core/tutorials/dotnet-watch?view=aspnetcore-2.1#custom-watch-projects

**Comment by mayankbansal018** [comment]
@NinoFloris dotnet watch is a valid behavior, & should work. My response was to as per your initial comment where you are passing path to multiple test dll.

For the dotnet watch issue, can you please share a small repro project, I'll investigate it further from there.

**Comment by NinoFloris** [comment]
I explained in the opening post, when I add multiple TestProjects to `<MSBuild Targets="VSTest" Projects="@(TestProjects)" />` it doesn't work correctly if build is enabled (VSTestNoBuild=true). If build isn't enabled it at least builds the 2 projects, but it basically starts vstest twice instead of running it in the same process.

**Comment by NinoFloris** [comment]
FYI just noticed I said "it doesn't work correctly if build is enabled (VSTestNoBuild=true). If build isn't enabled it at least BUILD the 2 projects" which of course should be "runs"

**Comment by NinoFloris** [comment]
https://github.com/Microsoft/vstest/issues/1503 is related, so a lot actually happens it just doesn't show up by default in the console

**Comment by NinoFloris** [comment]
doing 

```sh
export MSBUILDENSURESTDOUTFORTASKPROCESSES=1
dotnet watch msbuild -nodereuse:false -t:DefaultTests
```
seems to work around all weirdness


proj file:


```
...props...

    <Target Name="DefaultTests">
        <MSBuild Targets="Restore" Projects="@(DefaultTestProjects)" Condition="'$(TestNoBuild)' != 'true'" />
        <MSBuild Targets="VSTest" Projects="@(DefaultTestProjects)" Properties="VSTestNoBuild='$(TestNoBuild)'" />
    </Target>
```

**Comment by nohwnd** [comment]
The two paths can be specified by specifying the property multiple times: 

```
dotnet msbuild 
  /t:VSTest
  /p:VSTestNoBuild=true
  /p:TargetPath="S:\p\vstest3\playground\MSTest1\bin\Debug\net472\MSTest1.dll" 
  /p:TargetPath="S:\p\vstest3\playground\MSTest1\bin\Debug\net5.0\MSTest1.dll" 
  /p:VSTestNoBuild=true
```

Originally this would maybe fail with a target framework conflict, but from 17.3 vstest.console will be able to mix tfms and architectures under the same instance.
