### ISSUE TITLE
Microsoft.Net.Test.Sdk specific tfm targets should not contain TargetFrameworkIdentifier checks

### ISSUE THREAD

**Issue by ViktorHofer** [Microsoft/vstest#1827]
Right now the `Microsoft.Net.Test.Sdk.targets` file contains conditions that check on the `TargetFrameworkIdentifier`. That makes sense for the file that is placed under `buildMultiTargeting` but not for the files that are under specific tfm directories, i.e. `netcoreapp1.0`.

Removing these conditions and code paths that aren't related to the specific tfms would help us in corefx. That would help us with our current testing strategy running netstandard test assemblies against different tfms without cross-compiling.

A solution here would be to factor out common code into a file and import it by the different tfm targets files. If you are ok with my proposal I can quickly spin up PR which addresses this.

cc @ericstj

**Comment by mayankbansal018** [comment]
@ViktorHofer, can you please explain this
> That makes sense for the file that is placed under buildMultiTargeting but not for the files that are under specific tfm directories, i.e. netcoreapp1.0.

The current checks for `TargetFrameworkIdentifier` are required for .netcore scenario, as we need to generate exe output type for .netcore UT

I'm not sure how files under specific tfm e.g. `netcoreapp1.0`, get affected by this condition. Can you raise a PR, which will bring out your changes? From your comments,  it seems to me that if user has files layout in folders like `netcoreapp1.0`, `net45`, etc.. & the project is targeting multiple frameworks then dotnet will implicitly build for each framework, as per the folder layouts, did I get it right, or can you explain it a bit more.

**Comment by ViktorHofer** [comment]
Forget my comment about buildMultiTargeting, as it only contains the props file, I mixed that up.

> The current checks for TargetFrameworkIdentifier are required for .netcore scenario, as we need to generate exe output type for .netcore UT

Sure, I get that. What I'm saying is that you should not reuse your Microsoft.Net.Test.Sdk.targets file for different tfms (netcoreapp and netfx) and instead specialize them so that you don't need the TargetFrameworkIdentifier checks which trouble us in corefx.

![image](https://user-images.githubusercontent.com/7412651/48059026-5e78b080-e1b8-11e8-87da-179f87e5f59b.png)

> Can you raise a PR, which will bring out your changes?

Sure can do.

**Comment by ViktorHofer** [comment]
Added PR https://github.com/Microsoft/vstest/pull/1829 yesterday.
