### ISSUE TITLE
Testhost.exe has exited with code -1 (0xffffffff)

### ISSUE THREAD

**Issue by marcosadeghi** [Microsoft/vstest#1832]
I am attempting to override a few variables in my integration test with secrets sourced from KeyVault via a variable group within the build pipeline.

I have added a .runsettings file & I'm able to retrieve the dummy variables when I debug through the test. The test however exits abruptly as soon as the instruction to read the dummy value has been executed with the error below:

Value of CrmClientSecret is JustSomeSecret
Step into: Stepping over non-user code 
'IntegrationTests.Helpers.Helper.DeleteUserFromCRM' Step into: Stepping over 
non-user code 'IntegrationTests.Helpers.Helper. d__4..ctor' 'testhost.exe' 
(CLR v4.0.30319: TestSourceHost: Enumering source 
(C:\source\repos\Azure\Integrat ionTests\bin\Debug\Tests.dll)): Loaded 
'C:\source\repos\Azure\IntegrationTests\bin\Debug\Utilities.dll'. Symbols 
loaded. The thread 0x527c has exited with code 0 (0x0). The program '[26720] 
testhost.exe' has exited with code -1 (0xffffffff). The program '[26720] 
testhost.exe: Program Trace' has exited with code 0 (0x0).

Any help is appreciated

The solution is hosted in Visual Studio Ent 2017. The test project is net 4.61 & the following Nuget packages are installed:
Microsoft.NET.Test.Sdk v 15.9.0
MSTest.TestAdapter v 1.3.2
MSTest.TestFramework v 1.3.2
NUnit3TestAdapter version 3.11.0

My runSettings file is attached.
      
[TestRunSettings.txt](https://github.com/Microsoft/vstest/files/2558713/TestRunSettings.txt)

**Comment by karanjitsingh** [comment]
Hi @marcosadeghi, could you share the diagnostic logs for the crash?

**Comment by cltshivash** [comment]
Also you can leverage the options listed here https://github.com/Microsoft/vstest-docs/blob/master/RFCs/0024-Blame-Collector-Options.md to collect dump and analyze it.

**Comment by karanjitsingh** [comment]
@marcosadeghi, any update on this?

**Comment by karanjitsingh** [comment]
Closing the thread. Please feel free to re-open the issue once you have the required logs and crash dumps.
