### ISSUE TITLE
InProcDataCollection.TestCaseStart fired after test is actually started?

### ISSUE THREAD

**Issue by pkruk2** [Microsoft/vstest#1833]
## Description
Hi,

I have InProcDataCollection implementation. It seems that TestCaseStart is called after a test starts executing. I assume this is not correct. 

Is this handled by vstest, or by vstest test adapter? I'm using nunit 3.

I created a simple test which logs current time to a file. 
Similarly, I log current time from the in-proc data collector. 

In logs I can see:

[2018-11-09T16:59:08.3634227+01:00] TestSessionStart
[2018-11-09T16:59:08.**9644828**+01:00] TestFail (from test)
[2018-11-09T16:59:08.**9684832**+01:00] TestCaseStart: TestFail (from InProcDataCollection)

As you can see, the "TestFail (from test)" has earlier time than "TestCaseStart: TestFail" (logged from in-proc data collector).

## Steps to reproduce
I am attaching solution with unit tests.
[Vstest_Nunit.zip](https://github.com/Microsoft/vstest/files/2566580/Vstest_Nunit.zip)

I can attach in-proc data collector project if you need it, but I need to clean it first. Please tell me if it's mandatory. But I hope this is something that could be easily checked in code (if test is executed first or if in-proc events are fired first, or maybe they are done asynchronously/concurrently).

## Expected behavior
(In proc) data collector start events should be fired before test starts.

## Actual behavior
They are not (sometimes? depends on test engined - nunit/xunit etc?)

## Diagnostic logs
I can provide logs if needed, but this requires additional preparation. Please tell me if it's mandatory.

## Environment
I'm using Windows 7 and:
* Microsoft.TestPlatform.ObjectModel 15.9.0
* Microsoft.TestPlatform 15.9.0
* nunit latest 3.11.0 (both nunit and test adapter)

**Comment by karanjitsingh** [comment]
Hey @pkruk2, yes NUnit adapter fires asynchronous events to InProcDataCollector, so any synchronous log statements inside the test have a possibility to be logged before the asynchronous collector events. @osiristerje to confirm on that.

**Comment by OsirisTerje** [comment]
@pkruk2 Yes, this seems to be the case.  I see you have a repro project.  Can you raise this as an issue in the NUnit3TestAdapter project ?   (https://github.com/nunit/nunit3-vs-adapter/issues)  .   And yes, would be very helpful if you can add in the data collector project too.

**Comment by pkruk2** [comment]
Hi, thanks for quick replies.

@OsirisTerje yes, you answered just as I was writing a comment here :) I have prepared a full repro (including in-proc data collector) in the meantime and will also attach it to the new issue.
