### ISSUE TITLE
Debugging of .NET Framework Unit Tests in VSCode got broken with vstest.console.exe from VS2017; worked with VS2015

### ISSUE THREAD

**Issue by dmgonch** [Microsoft/vstest#1835]
## Description
Debugging .NET Framework tests in VSCode natively, i.e. by clicking "Debug Test" link over a test, is broken as described in https://github.com/OmniSharp/omnisharp-roslyn/issues/1332. A workaround for the issue was to execute vstest.console.exe from VS2015 using VSCode's launch configuration. If a breakpoint was set on a test, VSCode will break into the debugger when vstest.console.exe is launched. Unfortunately with vstest.console.exe from VS2017 this workaround doesn't work anymore - the tests do get executed but VSCode doesn't stop at breakpoints anymore.

## Steps to reproduce
(on Windows)
1. Prepare a machine with VS2015 and VS2017 installed, VSCode and C# OmniSharp extension installed (all of the latest versions).
2. Unzip [UT_NET461_VS2015.zip](https://github.com/Microsoft/vstest/files/2570545/UT_NET461_VS2015.zip) to c:\tests\UT_NET461_VS2015
3. Open, as Administrator, "Developer Command Prompt for VS 2017"
4. CorFlags.exe /32BITPREF- /Force "%VSINSTALLDIR%\Common7\IDE\CommonExtensions\Microsoft\TestWindow\vstest.console.exe" (this is to work around the same "Only 64-bit processes can be debugged." error as described in https://github.com/OmniSharp/omnisharp-roslyn/issues/1332).
5. Close the prompt.
6. Open "Developer Command Prompt for VS 2017" as the regular user; cd /d c:\tests\UT_NET461_VS2015
7. msbuild /t:rebuild /p:DebugType=portable
8. code . (launches VSCODE which opens the UT project)
9. Click on UnitTest1.cs to open it in the text editor
10. Set breakpoint on line 11 (the first line of TestMethod1)
11. Press "F5" to launch 'Run Tests' configuration.

## Expected behavior
VSCode breaks in to the debugger on line 11 as happens with vstest.console.exe from VS2015.

## Actual behavior
Tests are executed by the breakpoint is not hit.

## Diagnostic logs
[diagnostic_logs.zip](https://github.com/Microsoft/vstest/files/2570543/diagnostic_logs.zip)

## Environment
dotnet --info
.NET Core SDK (reflecting any global.json):
 Version:   2.1.403
 Commit:    04e15494b6

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.17134
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\2.1.403\

Host (useful for support):
  Version: 2.1.5
  Commit:  290303f510

.NET Core SDKs installed:
  2.1.403 [C:\Program Files\dotnet\sdk]

.NET Core runtimes installed:
  Microsoft.AspNetCore.All 2.1.5 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.App 2.1.5 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 2.1.5 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]

To install additional .NET Core runtimes or SDKs:
  https://aka.ms/dotnet-download

**Comment by cltshivash** [comment]
@dmgonch Any reason as to why is this issue reported in the test platform repo ?

**Comment by cltshivash** [comment]
Also based on the info you have provided I don't see the test runner behave incorrectly. It looks like the debugger settings are not getting honored/picked up resulting in the breakpoint being hit. I don't have much context on the internal workings of the debugger. But do let us know if there's anything specific that you need help on with respect to the test platform.

**Comment by dmgonch** [comment]
@cltshivash: I chose this repo as the starting point for the issue because the only variable that I'm changing in the repro steps is the version of vstest.console.exe. The issue does repo on a machine with both VS2015 and VS2017 installed and with the same VSCode & OmniSharp.

Regarding the debugger settings not being honored: any idea what could have changed in VS test platform that could have caused the settings not being picked, given all other pieces of the puzzle being the same? 

Thanks!

**Comment by karanjitsingh** [comment]
@dmgonch as of TPV2, vstest.console.exe has been moved to Common7\IDE\CommonExtensions\Microsoft\TestPlatform\vstest.console.exe,

For .4 try turning on flag for `%VSINSTALLDIR%\Common7\IDE\CommonExtensions\Microsoft\TestPlatform\vstest.console.exe`

**Comment by dmgonch** [comment]
@karanjitsingh : the file you are referring to doesn't seem to exist with VS2017 install but "%VSINSTALLDIR%\Common7\IDE\CommonExtensions\Microsoft\TestWindow\vstest.console.exe" does. Using it though doesn't fix the problem, Please see new logs attached [logs1.zip](https://github.com/Microsoft/vstest/files/2577082/logs1.zip).

**Comment by karanjitsingh** [comment]
@dmgonch, my bad the path is actually `"%VSINSTALLDIR%\Common7\IDE\Extensions\TestPlatform`

**Comment by dmgonch** [comment]
@karanjitsingh : tried this exe as well but fortunately with the same result, i.e. debugger wouldn't attach. I was wondering if you were able to follow the repro steps and get the same result (good with vstest.console.exe from VS2015 and bad from VS2017)

**Comment by karanjitsingh** [comment]
In your launch.json you should remove the argument `/Platform:x64` as an argument to vstest.console.exe. 

```json
...
            "program": "${env:VSINSTALLDIR}/Common7/IDE/CommonExtensions/Microsoft/TestWindow/vstest.console.exe",
            "args": [
                "${workspaceRoot}/bin/Debug/UT_NET461_VS2015.dll",
            ],
...
```

What's happening here is that whenever `/Platform:x64` or `/InIsolation` is set, vstest.console.exe starts another another process (testhost.exe) which eventually runs the test. VSCode successfully attaches to vstest.console.exe but since tests are being run in a separate process that VSCode is unaware of hence the breakpoint is never hit.

**Comment by dmgonch** [comment]
@karanjitsingh : indeed this worked - thank you very much for the hint! 
Sounds like as long one has a choice of targeting AnyCPU platform they can debug their .NET Framework tests in VSCode. 
[UT_NET461_VS2015-x64.zip](https://github.com/Microsoft/vstest/files/2581802/UT_NET461_VS2015-x64.zip) contains modified sample UT project that can target x64. To build it run:
`msbuild /t:rebuild /p:DebugType=portable /p:Platform=x64 /p:Configuration=Debug`
In this case it looks like debugging still is not working, with or without `/Platform:x64`, I'm presuming for the similar reason you described above.
Do you ideas for how this scenario be enabled as well giving the existing tools?

**Comment by karanjitsingh** [comment]
In that case you will have to manually attach to testhost.exe

1. Add a .NET attach configuration to your launch.json with `type: clr`. *The environment variable `VSTEST_HOST_DEBUG` will set debug mode for the testhost process.*

```json
{
    "version": "0.2.0",
    "configurations": [
        {
            "name": ".NET Attach",
            "type": "clr",
            "request": "attach",
            "processId": "${command:pickProcess}",
        },
        {
            "name": "Run Tests",
            "type": "clr",
            "request": "launch",
            "program": "${env:VSINSTALLDIR}/Common7/IDE/Extensions/TestPlatform/vstest.console.exe",
            "args": [
                "${workspaceRoot}/bin/x64/Debug/UT_NET461_VS2015.dll",
            ],
            "cwd": "${workspaceRoot}",
            "stopAtEntry": false,
            "console": "internalConsole",
            "justMyCode": false,
            "logging": {
                "programOutput": true,
                "exceptions": false,
                "moduleLoad": false,
                "engineLogging": false
            },
            "env":{
                "VSTEST_HOST_DEBUG": "1"
            }
        },
    ]
}
```

        

2. Run the `Run Tests` configuration and you should get something like this:

![image](https://user-images.githubusercontent.com/4632805/48548948-6640ff00-e8f4-11e8-8aca-99c626b26e90.png)

3. Attach to the testhost process using `.NET Attach`, the debugger will attach in paused state, continue the execution for your code to hit.

***Note: If you're running multiple dlls in parallel vstest.console.exe will start multiple testhost processes in parallel with all of them waiting for a debugger to attach.***

**Comment by dmgonch** [comment]
This works as well - I truly appreciate all your help folks! I believe you can close the issue now. Thanks!
