### ISSUE TITLE
Document the vstest cli options

### ISSUE THREAD

**Issue by singhsarab** [Microsoft/vstest#1842]
## Description
> Add documentation for the vstest.console cli and dotnet test cli options and usage patterns.

**Comment by pvlakshm** [comment]
Here is the documentation: 
- [`vstest.console` CLI options documentation](https://docs.microsoft.com/en-us/visualstudio/test/vstest-console-options?view=vs-2017)
- [`dotnet test` CLI optoins documentation](https://docs.microsoft.com/en-us/dotnet/core/tools/dotnet-test?tabs=netcore21)

**Comment by singhsarab** [comment]
@PBoraMSFT Will these suffice?
