### ISSUE TITLE
Test Runner hangs intermittently, datacollector.exe appears deadlocked

### ISSUE THREAD

**Issue by mayerj** [Microsoft/vstest#1845]
## Description
> Intermittently during our build process our unit tests seem to hang.  All individual tests have <20s timeouts applied to them, and it appears a test is not currently running, even though the test process is still executing.  After 1 hour (overall build timeout) the build fails.
>
> Debugging seems to indicate that datacollector.exe is hanging when trying to handle a child process exiting while the tests are running.

## Steps to reproduce
> Intermittently reproducible, anecdotally related to unit tests that spawn subprocesses

## Expected behavior
> Tests do not hang.

## Actual behavior
> Tests hang.  DataCollector.exe always has the following callstacks:

> Thread 1

> 0:004> !CLRStack
> OS Thread Id: 0xb44 (4)
>         Child SP               IP Call Site
> 000000f332aff0f8 00007ffbb572f0e4 [HelperMethodFrame_1OBJ: 000000f332aff0f8] System.Threading.WaitHandle.WaitOneNative(System.Runtime.InteropServices.SafeHandle, UInt32, Boolean, Boolean)
> 000000f332aff220 00007ffb9b4be98b System.Threading.WaitHandle.InternalWaitOne(System.Runtime.InteropServices.SafeHandle, Int64, Boolean, Boolean)
> 000000f332aff250 00007ffb9b4be95e System.Threading.WaitHandle.WaitOne(Int32, Boolean)
> 000000f332aff290 00007ffb3de69726 Microsoft.VisualStudio.Diagnostics.Logging.LoggerEngine.Stop(Boolean)
> 000000f332aff310 00007ffb3de66342 Microsoft.VisualStudio.TraceCollector.CommonDataCollector+LoggerWrapper.LoggedProcess_Exited(System.Object, Boolean)
> 000000f332aff360 00007ffb9b503423 System.Threading.ExecutionContext.RunInternal(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)
> 000000f332aff430 00007ffb9b5032b4 System.Threading.ExecutionContext.Run(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)
> 000000f332aff460 00007ffb9beb1425 System.Threading._ThreadPoolWaitOrTimerCallback.PerformWaitOrTimerCallback(System.Object, Boolean)
> 000000f332aff610 00007ffb9d406d93 [GCFrame: 000000f332aff610] 
> 000000f332aff808 00007ffb9d406d93 [DebuggerU2MCatchHandlerFrame: 000000f332aff808] 
> 0:004> ~5s

> Thread 2

> 0:005> !CLRStack
> OS Thread Id: 0x51cc (5)
>         Child SP               IP Call Site
> 000000f332cfe408 00007ffbb572f0e4 [GCFrame: 000000f332cfe408] 
> 000000f332cfe548 00007ffbb572f0e4 [GCFrame: 000000f332cfe548] 
> 000000f332cfe588 00007ffbb572f0e4 [HelperMethodFrame_1OBJ: 000000f332cfe588] System.Threading.Monitor.Enter(System.Object)
> 000000f332cfe680 00007ffb3de5d9fd Microsoft.VisualStudio.TraceCollector.CommonDataCollector+LoggerWrapper.SendMessage(MessageCreator, Boolean)
> 000000f332cfe730 00007ffb3de4d7ce Microsoft.VisualStudio.TraceCollector.CommonDataCollector.DispatchMessage(MessageCreator)
> 000000f332cfe7a0 00007ffb3de64dd8 Microsoft.VisualStudio.TraceCollector.CommonDataCollector.OnTestCaseEnd(System.Object, Microsoft.VisualStudio.TestPlatform.ObjectModel.DataCollection.TestCaseEndEventArgs)
> 000000f332cfea98 00007ffb9d406d93 [DebuggerU2MCatchHandlerFrame: 000000f332cfea98] 
> 000000f332cfedd8 00007ffb9d406d93 [HelperMethodFrame_PROTECTOBJ: 000000f332cfedd8] System.RuntimeMethodHandle.InvokeMethod(System.Object, System.Object[], System.Signature, Boolean)
> 000000f332cfef50 00007ffb9b513e60 System.Reflection.RuntimeMethodInfo.UnsafeInvokeInternal(System.Object, System.Object[], System.Object[])
> 000000f332cfefc0 00007ffb9b4e2519 System.Delegate.DynamicInvokeImpl(System.Object[])
> 000000f332cff010 00007ffb3de4b472 Microsoft.VisualStudio.TestPlatform.Utilities.MulticastDelegateUtilities.SafeInvoke(System.Delegate, System.Object, System.EventArgs, System.String)
> 000000f332cff070 00007ffb3de4aeea Microsoft.VisualStudio.TestPlatform.Common.DataCollector.TestPlatformDataCollectionEvents.RaiseEvent(Microsoft.VisualStudio.TestPlatform.ObjectModel.DataCollection.DataCollectionEventArgs)
> 000000f332cff0c0 00007ffb3de648db Microsoft.VisualStudio.TestPlatform.Common.DataCollector.DataCollectionManager.TestCaseEnded(Microsoft.VisualStudio.TestPlatform.ObjectModel.DataCollection.TestCaseEndEventArgs)
> 000000f332cff130 00007ffb3de5ee59 Microsoft.VisualStudio.TestPlatform.CommunicationUtilities.DataCollection.DataCollectionTestCaseEventHandler.ProcessRequests()
> 000000f332cff180 00007ffb3de4e57d Microsoft.VisualStudio.TestPlatform.CommunicationUtilities.DataCollection.DataCollectionRequestHandler.b__22_0()
> 000000f332cff1e0 00007ffb9b54ca96 System.Threading.Tasks.Task.Execute()
> 000000f332cff220 00007ffb9b503423 System.Threading.ExecutionContext.RunInternal(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)
> 000000f332cff2f0 00007ffb9b5032b4 System.Threading.ExecutionContext.Run(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)
> 000000f332cff320 00007ffb9b54cd35 System.Threading.Tasks.Task.ExecuteWithThreadLocal(System.Threading.Tasks.Task ByRef)
> 000000f332cff3d0 00007ffb9b54c463 System.Threading.Tasks.Task.ExecuteEntry(Boolean)
> 000000f332cff410 00007ffb9b5425f2 System.Threading.ThreadPoolWorkQueue.Dispatch()
> 000000f332cff8a8 00007ffb9d406d93 [DebuggerU2MCatchHandlerFrame: 000000f332cff8a8] 

## Diagnostic logs
> TBD

## Environment
> Please share additional details about the test environment.
> Windows 10
> 0:000> lm v m vstest*
> Browse full module list
> start    end        module name
> 00820000 00844000   vstest_console   (deferred)             
>     Image path: C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\Common7\IDE\CommonExtensions\Microsoft\TestWindow\vstest.console.exe
>     Image name: vstest.console.exe
>     Browse all global symbols  functions  data
>     Has CLR image header, track-debug-data flag not set
>     Image was built with /Brepro flag.
>     Timestamp:        EFCF0EB1 (This is a reproducible build file hash, not a timestamp)
>     CheckSum:         00029D14
>     ImageSize:        00024000
>     File version:     15.0.27924.0
>     Product version:  15.0.27924.0
>     File flags:       0 (Mask 3F)
>     File OS:          4 Unknown Win32
>     File type:        1.0 App
>     File date:        00000000.00000000
>     Translations:     0000.04b0 0000.04e4 0409.04b0 0409.04e4
>     Information from resource tables:

**Comment by karanjitsingh** [comment]
Hi @mayerj, I am not able to infer much from the stack trace you've provided. Could you turn on the `--diag` option and upload the logs here.

It would be even more helpful if you could share a sample project which runs into such problems.

**Comment by mayerj** [comment]
I have the diagnostic traces, but I'm a little reticent to upload them here, as there are a lot of product specific paths and references in them.  Is there some way to share them privately?

**Comment by karanjitsingh** [comment]
@mayerj, can you provide your email on here? If that's not possible then I would suggest posting it on [developer community](https://developercommunity.visualstudio.com), you can limit access to attachments on developer community to only be visible by folks at microsoft

**Comment by singhsarab** [comment]
@karanjitsingh Just checking, you did not get the logs yet, right?
@mayerj Did you get a chance to create an issue on developer community? or is there any other way you want us to access the logs, please let us know.

Please update this thread, so we understand what state we are in.

**Comment by karanjitsingh** [comment]
@singhsarab Yep, haven't received the logs

**Comment by karanjitsingh** [comment]
@singhsarab Yep, haven't received the logs

**Comment by singhsarab** [comment]
@mayerj Is there some support ID that you are using to track the case ?

**Comment by singhsarab** [comment]
Closing this as user has already opened premier support case.
