### ISSUE TITLE
Dotnet test Data Collection problem, “Could not find data collector”

### ISSUE THREAD

**Issue by lvasilev1** [Microsoft/vstest#1846]
## Steps to reproduce
> What steps can reproduce the defect?
1. In Visual Studio 2017, create a new solution and add a Visual C#  .NET Core 2.0 xUnit Test Project. Name the project TEST.MyUnitTests
2. Also add a Visual C# .NET Core 2.0 Class Library project.
3. Add at least one unit test to first project.
4. In Class Library project, add a DataCollector, like in [this](https://github.com/Microsoft/vstest-docs/blob/master/docs/extensions/datacollector.md) tutorial. Let's say the Data Collector friendly name is "MyDataCollector" and the project it's located in is "TEST.DataCollector".
5. Compile solution.
6. Open PowerShell and navigate to folder where C# project file for unit test project is located.
7. Type the following command in PowerShell:

> [unit tests directory]>dotnet test --collect:"MyDataCollector" --test-adapter-path "../TEST.DataCollector/bin/Debug/netcoreapp2.0"

**"../TEST.DataCollector/bin/Debug/netcoreapp2.0"** is the path to the **TEST.DataCollector** assembly, e.g. where **TEST.DataCollector.dll** is located.

## Expected behavior

Data Collector is called and it performs the actions, such as logging, in its event handlers (TestHostLaunched, SessionStart, SessionEnd, TestCaseStart, and TestCaseEnd). Unit test passes.

## Actual behavior

Even though unit test passes, the Data Collector is not found and the following message is displayed in PowerShell:

> Data collection: Could not find data collector 'MyDataCollector'

Update: also, in a log file called "log.datacollector.18-11-20......txt", I see the following error:

> TpTrace Information: 0 : 41652, 6, 2018/11/20, 12:17:51.508, 11772736188955, datacollector.dll, DataCollectionRequestHandler.ProcessRequests : Datacollector received message: (DataCollection.AfterTestRunEnd) -> false
TpTrace Error: 0 : 41652, 6, 2018/11/20, 12:17:51.808, 11772736773687, datacollector.dll, DataCollectionAttachmentManager.GetAttachments: Fail to get attachments: System.Collections.Generic.KeyNotFoundException: The given key was not present in the dictionary.
   at System.ThrowHelper.ThrowKeyNotFoundException()
   at System.Collections.Generic.Dictionary`2.get_Item(TKey key)
   at Microsoft.VisualStudio.TestPlatform.Common.DataCollector.DataCollectionAttachmentManager.GetAttachments(DataCollectionContext dataCollectionContext) 

## Diagnostic logs
 
[diagnostic_log_1.txt](https://github.com/Microsoft/vstest/files/2600754/diagnostic_log_1.txt)

## Environment

OS: Windows 8

**Comment by singhsarab** [comment]
@lvasilev1 
It seems the datacollector you wrote is not getting recognised. Can you share the repro project with us?

Note: If TestPlatform does not recognise the data collector it simply ignores that collector and goes ahead with the execution hence, the tests passed.

**Comment by singhsarab** [comment]
@lvasilev1 Closing this issue for now. Please let know if you still hit the issue and share the repro project if possible. Thanks.

**Comment by sasivishnu** [comment]
Hi, I am facing same issue but in .Net framework. Please let me know whether I need to open a new issue since this is for .net core. 

I am using Visual Studio 15.9.2 on Windows 10.
My unit test project is based on 4.7.1 framework. References Test Framework (MSTest.TestFramework.1.2.0

cmd:
```
vstest.console.exe "testproject.dll" /collect:"NewDataCollector" 

vstest.console.exe "testproject.dll" /collect:"NewDataCollector" /testadapterpath:"C:\Visual Studio 2017\Projects\OutOfProcDataCollector\OutOfProcDataCollector\bin\Release"
```

I used both type of commands. I get same error both the time. Any help is appreciated. Thanks.

```
Starting test execution, please wait...
Data collection : Could not find data collector 'NewDataCollector'
```

I have attached my sample data collector which I wrote based on vstest docs example. Just ignore some stuff like trying add logs to some file.. I was just playing around. All I wanted was logs in console stating "X test method started", " x test method succeeded/ended"

[OutOfProcDataCollector.zip](https://github.com/Microsoft/vstest/files/2722891/OutOfProcDataCollector.zip)
