### ISSUE TITLE
Troubleshooting HttpWebRequest on a Hosted Agent

### ISSUE THREAD

**Issue by jrmcdona** [Microsoft/vstest#1847]
Hi All,
Is there anything on a Hosted Agent that would block an HttpWebRequest?

I have logged this issue in the Azure pipeline but wanted to reference it here because it is test specific,
https://github.com/Microsoft/azure-pipelines-tasks/issues/8888

Thanks

**Comment by karanjitsingh** [comment]
@jrmcdona, I think this does not relate to the MSTestAdapter itself since things seem to be working locally.

**Comment by singhsarab** [comment]
Closing this as it is not related to vstest. And I see the related issue on azure-pipeline-tasks was closed.
