### ISSUE TITLE
Custom arguments with `dotnet vstest`

### ISSUE THREAD

**Issue by rhalaly** [microsoft/vstest#1854]
## Description
Cant read the custom args that send via `dotnet vstest` command. 

## Steps to reproduce
Running the command `dotnet vstest Test.dll -- arg1=val1 arg2=val2`
Read the arguments `arg1` and `arg2` with the `TestContext.Properties` or `Environment.GetCommandLineArgs` but non of them contains those arguments.

## Expected behavior
Able to read `val1` and `val2` from `TestContext.Properties` or `Environment.GetCommandLineArgs`

## Actual behavior
Both `TestContext.Properties` and `Environment.GetCommandLineArgs` do not contains those arguments.

## Environment
.Net Core 2.1 and .Net Core 2.1

**Comment by singhsarab** [comment]
@PBoraMSFT @cltshivash Please triage this.

**Comment by rhalaly** [comment]
Is this is `enhancement`?? How should we read these custom arguments inside the tests?

**Comment by shanchin2k** [comment]
@singhsarab I have below scenario.

I want to run Selenium based UI tests using  mstest tasks in  Azure pipeline.  Need to configure multiple browsers testing  for the same set of test cases. Plan to create separate test task for each browser, which uses the same test code but with browser name passed at run time. I thought of passing browser name in command line and read it from TestContext in code. But it seems not getting those command line parameters. I tend to see same behaviour was available with .Net framework but not with core.

Any lead on this?

**Comment by maksim36ua** [comment]
@singhsarab 

[Documentation](https://docs.microsoft.com/en-us/dotnet/core/tools/dotnet-vstest?tabs=netcore21) says [args] should be supported, but seems like it's still not working.

Could you please clarify on this?

**Comment by singhsarab** [comment]
I hope this PR should help. We have added the support for add/overriding TestRunParameters

PR: https://github.com/microsoft/vstest/pull/2251

**Comment by Evangelink** [comment]
I think #2251 answered this ticket as you can now call `-- testrunparameters.parameter1=10 testrunparameters.parameter2=11`. Although it's probably less convenient than being able to do `-- parameter1=10 parameter2=11`, it would be too complex to be able to understand for which setting we should route the argument.

I am closing this ticket but if you feel like some part of your request was not covered, please feel free to comment.
