### ISSUE TITLE
VSTest Could not load file or assembly (0x80070020)

### ISSUE THREAD

**Issue by ParmjeetSingh15** [Microsoft/vstest#1874]
## Description

> Our team has adopted VSTest for our E2E functional tests. The machine has 8 cores so we trigger 8 profiles to be run in parallel. 

## Steps to reproduce
One profile is executed as follows.  In this manner we execute 8 profiles.
"C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\Common7\IDE\CommonExtensions\Microsoft\TestWindow\vstest.console.exe" /platform:x64 /logger:trx  Foo.ExtendedTests.dll'  /InIsolation /TestCaseFilter:"P1_Bar"

We have multiple profiles (Test Categories) coming from same dll, thus multiple vstest.console.exe/testhost.exe us trying to load same test dll. The obvious workaround for us is to add a Try/Catch block around the code which is trying to run a profile and add few retries if “E_SHARINGVIOLATION” is  thrown.  However  we would prefer if vstest.console.exe natively handles it. and doesn't want consumer of vstest.console.exe to handle this error by adding try/catch block and retries.

## Actual behavior
Starting test execution, please wait...
Could not load file or assembly 'Foo.ExtendedTests.dll' or one of its dependencies. The process cannot access the file because it is being used by another process. (Exception from HRESULT: 0x80070020)

**Comment by abhishkk** [comment]
@ParmjeetSingh15 
We are not able to repro this issue. Following is what i have tried.

Code:
```
        [TestMethod]
        [TestCategory("First")]
        public void TestMethod1()
        {
            Thread.Sleep(15000);
        }

        [TestMethod]
        [TestCategory("First")]
        public void TestMethod2()
        {
            Thread.Sleep(15000);
        }

        [TestMethod]
        [TestCategory("Second")]
        public void TestMethod3()
        {
            Thread.Sleep(15000);
        }

        [TestMethod]
        [TestCategory("Second")]
        public void TestMethod4()
        {
            Thread.Sleep(15000);
        }

```

Command1: `"C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\Common7\IDE\Extensions\TestPlatform\vstest.console.exe" /platform:x64 /logger:trx UnitTestProject.dll /InIsolation /TestCaseFilter:"TestCategory=First"`
Command2: `"C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\Common7\IDE\Extensions\TestPlatform\vstest.console.exe" /platform:x64 /logger:trx UnitTestProject.dll /InIsolation /TestCaseFilter:"TestCategory=Second"`

I am able to successfully run both command in parallel. (tried for both .NETCore, .NET full framework)
Can you please verify if your test code is holding the test dll access or not.
If not, can you please share following information?
1. Sample repro test project
2. VS version
3. Platform against which you are building repro test project (x64, AnyCPU etc)

Also, I see that you are using vstest for functional tests. Can you make sure that tests running in parallel are thread safe?

**Comment by ShreyasRmsft** [comment]
@ParmjeetSingh15 may i know how you are running your 8 profiles in parallel? 

Don't tell me you are invoking 8 instances of vstest.console.exe all at once!

**Comment by ShreyasRmsft** [comment]
@ParmjeetSingh15 can you share a sample repro?

**Comment by ShreyasRmsft** [comment]
@ParmjeetSingh15 this is very little to go on and Abhishek tried to get a repro but was unable to do so.

The best way to move forward is if we have a repro project.

**Comment by ShreyasRmsft** [comment]
Also am I right in understanding that this is because there is test code that is trying to access common resources? Or are you claiming the testplatform itself is causing this issue?

**Comment by ParmjeetSingh15** [comment]
@ShreyasRmsft  I understand the repro is hard due to low repro rate.  Thus I don't know how much sharing the test project will help.  We are also looking into adding /Diag switch to our run to collect logs in case it repros again. 



> Also am I right in understanding that this is because there is test code that is trying to access common resources? Or are you claiming the testplatform itself is causing this issue?

Yes, my current line of thinking is the issue with testpaltform, however the more information may reveal only from diag logs

**Comment by ShreyasRmsft** [comment]
@ParmjeetSingh15 we load all resources in read only mode. Doesn't seem likely that the platform is causing this. Anyway you can re-open the issue either when you have a repro or when you have the diag logs. Thanks.

**Comment by ParmjeetSingh15** [comment]
Sherayas please help me re-open the issue ( i am unable to reopen it).   The issue is still repro'ing and frequency of repro has increased but not  100%
It appears on github "you cannot re-open your own issues if a repo collaborator closed them"

**Comment by ShreyasRmsft** [comment]
@ParmjeetSingh15 were you able to get the diag logs?

**Comment by ParmjeetSingh15** [comment]
> @ParmjeetSingh15 were you able to get the diag logs? As stated above without the diag logs or a sample repro project there's not much we can do to help you out.

Hi Shreyas we enabled platform diagnostic traces and have a repro yesterday night. Let me contact you to share the required files.

**Comment by acesiddhu** [comment]
@ParmjeetSingh15 as discussed offline. the bug was actually in older version of test platform <15.8. see this issue and related fix that went in https://github.com/Microsoft/vstest/issues/1638. please upgrade to latest stable version of vstest/VS. that should fix the problem

**Comment by acesiddhu** [comment]
I will close the issue. if you face the issue again please do reopen the issue or mail us back,
