### ISSUE TITLE
'dotnet test' hangs on 'Microsoft.TestPlatform.Build.Tasks.VSTestTask' task

### ISSUE THREAD

**Issue by yhvicey** [Microsoft/vstest#1875]
## Description
`dotnet test` command hangs on `Microsoft.TestPlatform.Build.Tasks.VSTestTask` task, and reports below error after 90 seconds:

> Failed to negotiate protocol, waiting for response timed out after 90 seconds. This may occur due to machine slowness, please set environment variable VSTEST_CONNECTION_TIMEOUT to increase timeout.
> Test Run Aborted.

It seems raised from `src\Microsoft.TestPlatform.CommunicationUtilities\TestRequestSender.cs!CheckVersionWithTestHost()`.

## Steps to reproduce
1. `git clone <repo path>`
1. `dotnet test`
1. Error after 90 seconds

## Expected behavior
Runs normally, won't be blocked

## Actual behavior
> What is the behavior observed?

## Diagnostic logs
Log shows it keeps trying to communicate with 127.0.0.1:3015/3016 but no response.:

```txt
TpTrace Verbose: 0 : 18324, 7, 2018/12/22, 01:40:16.482, 8902393823, vstest.console.dll, SocketServer.OnClientConnected: Client connected for endPoint: 127.0.0.1:3015, starting MessageLoopAsync:
TpTrace Verbose: 0 : 18324, 10, 2018/12/22, 01:40:16.482, 8902395760, vstest.console.dll, TcpClientExtensions.MessageLoopAsync: Polling on remoteEndPoint: 127.0.0.1:3016 localEndPoint: 127.0.0.1:3015
...
TpTrace Error: 0 : 18324, 5, 2018/12/22, 01:41:46.531, 9802885862, vstest.console.dll, ProxyExecutionManager.StartTestRun: Failed to start test run: Microsoft.VisualStudio.TestPlatform.ObjectModel.TestPlatformException: Failed to negotiate protocol, waiting for response timed out after 90 seconds. This may occur due to machine slowness, please set environment variable VSTEST_CONNECTION_TIMEOUT to increase timeout.
   at Microsoft.VisualStudio.TestPlatform.CommunicationUtilities.TestRequestSender.CheckVersionWithTestHost()
   at Microsoft.VisualStudio.TestPlatform.CrossPlatEngine.Client.ProxyOperationManager.SetupChannel(IEnumerable`1 sources)
   at Microsoft.VisualStudio.TestPlatform.CrossPlatEngine.Client.ProxyExecutionManager.StartTestRun(TestRunCriteria testRunCriteria, ITestRunEventsHandler eventHandler)
TpTrace Verbose: 0 : 18324, 5, 2018/12/22, 01:41:46.535, 9802927655, vstest.console.dll, TestRunRequest:SendTestRunMessage: Starting.
TpTrace Information: 0 : 18324, 5, 2018/12/22, 01:41:46.535, 9802928886, vstest.console.dll, TestRunRequest:SendTestRunMessage: Completed.
TpTrace Verbose: 0 : 18324, 5, 2018/12/22, 01:41:46.543, 9803007276, vstest.console.dll, TestRequestSender.EndSession: Sending end session.
TpTrace Warning: 0 : 18324, 5, 2018/12/22, 01:41:46.644, 9804016478, vstest.console.dll, ProxyOperationManager: Timed out waiting for test host to exit. Will terminate process.
TpTrace Verbose: 0 : 18324, 5, 2018/12/22, 01:41:46.649, 9804061722, vstest.console.dll, ParallelProxyExecutionManager: HandlePartialRunComplete: Total completed clients = 1, Run complete = True, Run canceled: False.
```

## Environment
Windows 10 1809, VS 2019 preview

**Comment by yhvicey** [comment]
Digging into the code a little and I found that it seems the SocketServer started successfully, but the SocketClient failed right after starting MessageLoopAsync. Client log:

> TpTrace Information: 0 : 19176, 8, 2018/12/22, 23:45:34.193, 120439504104, testhost.dll, DefaultEngineInvoker.StartProcessingAsync: Connected to vstest.console, Starting process requests.
> TpTrace Verbose: 0 : 19176, 7, 2018/12/22, 23:45:34.193, 120439504687, testhost.dll, Connected to server, and starting MessageLoopAsync

**Comment by abhishkk** [comment]
@yhvicey 
I am not able to reproduce this issue. I tried following steps on `Microsoft/vstest` repo:
1. cd `test\Microsoft.TestPlatform.Build.UnitTests`
2. dotnet test

Project built and test ran successfully. Can you do following?
1. Elaborate the steps tried. You haven't mentioned for which project you are trying to run `dotnet test`.
2. Are you able to reproduce this issue in any other machine as well?
3. Can you run `where dotnet` and `dotnet --version` commands and share the outputs?
4. Can you check in event traces if testhost.exe crashed? If yes can you share the stack trace from event traces?

**Comment by yhvicey** [comment]
I'm not testing this repo but test my own project. However it works well now. Have no idea why, will reopen this if it occurs again. Thanks for your help!
