### ISSUE TITLE
Unable to Instrument .Net Core Assemblies using VSinstr /Coverage 15.0.28218 x64

### ISSUE THREAD

**Issue by mohankumarp** [Microsoft/vstest#1878]
## Description
Unable to Instrument .Net Core Assemblies using VSinstr 15.0.28218 x64

## Steps to reproduce
> Created a console app project (Calc.dll) with Target framework as .Net Core2.1. 
> Project Debugging information set to 'Full'  in  Advance build settings (Not 'Portable')
> Instrument dll   `Vsinstr Calc.dll /Coverage /Verbose`
> I am using VS2017 Enterprise edition Version 15.9.4. 

## Expected behavior
> Instrumentation should be successful as it like .Net Framework assemblies

## Actual behavior
Error VSP1026: Coverage is not supported on libraries that do not reference MSCorLib. This is often the case for Portable Libraries.

## Diagnostic logs
E:\CalcDLL\bin\Debug\netcoreapp2.1>vsinstr  Calc.dll /Coverage /Verbose
Microsoft (R) VSInstr Post-Link Instrumentation 15.0.28218 x64 Copyright (C) Microsoft Corp. All rights reserved.

File to Process: E:\CalcDLL\bin\Debug\netcoreapp2.1\Calc.dll --> E:\CalcDLL\bin\Debug\netcoreapp2.1\Calc.dll Original file backed up to E:\CalcDLL\bin\Debug\netcoreapp2.1\Calc.dll.orig

**Error VSP1026: Coverage is not supported on libraries that do not reference MSCorLib. This is often the case for Portable Libraries.**

_Note:  I'm able to instrument dlls of .Net Framework 4.6 but NOT .Net Core 2.1_

**Comment by vagisha-nidhi** [comment]
Hi @mohankumarp 
To collect coverage using `vstest.console.exe`, you can use **/EnableCodeCoverage** command line option to generate coverage information. 
Example : `vstest.console.exe Calc.dll /EnableCodeCoverage`
You can find more details [here](https://docs.microsoft.com/en-us/visualstudio/test/vstest-console-options?view=vs-2017).
For using vsinstr, please file this issue on [developer community]( https://developercommunity.visualstudio.com). An appropriate team will get back to you on this.
Feel free to reopen the issue if you have any questions regarding vstest.console.exe.
