### ISSUE TITLE
Build pipeline getting stuck at “Cleanup” task, while running tests with “Test Plan” or “Test Assemblies” as the “Test Selection”.

### ISSUE THREAD

**Issue by uppadhyayraj1201** [Microsoft/vstest#1879]
## Description
> Build pipeline getting stuck at “Cleanup” task, while running tests with “Test Plan” or “Test Assemblies” as the “Test Selection”.

## Steps to reproduce
> 1.	Create a simple build pipeline with some sample Selenium or Coded Ui tests.
>2.	Add tasks to build the solution and deploy the Test Platform installer (if required).
>3.	Add VsTest tasks to run tests from a “Test Plan” or “Test Assemblies”.
>4.	Queue the build.

## Expected behavior
> It should run the test, publish the results in Test Plan and build should complete (according to test results).

## Actual behavior
> It runs the tests, publish the result but build get stuck in “Cleanup” task for 3 hours.

**Comment by ShreyasRmsft** [comment]
Can you please set system.debug = true and share the _entire_ zip logs?

**Comment by vagisha-nidhi** [comment]
@uppadhyayraj1201 Any updates?

**Comment by kaadhina** [comment]
Closing this. Please reopen with logs.
