### ISSUE TITLE
VSTest UWP console app

### ISSUE THREAD

**Issue by ViktorHofer** [Microsoft/vstest#1884]
In corefx we currently test our UWP project with https://github.com/dotnet/arcade/tree/master/src/Microsoft.DotNet.XUnitRunnerUap which consists of a runner and and a launcher. The runner is a UWP console app xunit runner which just runs the tests that are discover able and the launcher bundles the runner and the UWP test project together as we can't do Assembly.Load in UWP.

While discussing with @onovotny how to get rid of our custom runner he pointed out that vstest is probably doing the same thing that we do with our C++ launcher which bundles, registers and deploys the UWP launcher. We would like to just use what vstest offers and get rid of our custom runner but we don't want to loose the benefits of a UWP console app which a) works well with CI, can write directly to stdout which is very valuable when capturing logs and is faster over a GUI application.

1. Are there any plans to switch to a UWP console app in vstest?
2. Are ther eany current limitations with vstest and UWP, i.e. filtering test cases that could hinder our migration?

cc @danmosemsft @singhsarab @mayankbansal018

**Comment by mayankbansal018** [comment]
@ViktorHofer , can you please explain

> Are there any plans to switch to a UWP console app in vstest? 
a bit more

Our current UWP implementation requires users to use UWP Test template in VS, by default user can write tests in mstest framewowrk, but xUnit(latest) also works with our test template.
The test app can also take reference to another UWP project which is to be tested.

To run the test, user can directly run them from VS, or from CLI via(.appxrecipe). I would suggest that you please try out our current implementation, & let us know if you find some scenario that is missing.

**Comment by ViktorHofer** [comment]
@mayankbansal018 I'm not sure we are talking about the same thing here. The template just creates an appx package but contains no GUI. 

```
Microsoft.VisualStudio.TestPlatform.TestExecutor.UnitTestClient.CreateDefaultUI();

            // Ensure the current window is active
            Window.Current.Activate();

            Microsoft.VisualStudio.TestPlatform.TestExecutor.UnitTestClient.Run(e.Arguments);
```

Can you please point me to the source code where the UWP test runner lives (internal/external)?

**Comment by mayankbansal018** [comment]
@ViktorHofer shall I close this issue, as we have started a thread internally & have added you to it ?

**Comment by ViktorHofer** [comment]
I agree. Let's close this one. I will respond on the offline thread asap.
