### ISSUE TITLE
Results are different when executed using "dotnet vstest" vs "Test Explorer" from Visual studio

### ISSUE THREAD

**Issue by ViktorHofer** [Microsoft/vstest#1885]
from @jaydeept:

I am using `System.Diagnostics.StackFrame` class inside my `log4net` related code where I am seeing an issue with API called `GetMethod()`. When I execute from Test Explorer, the error is something like below for `KeyNotFoundExcpetion`:

> Thrown System.Collections.Generic.KeyNotFoundException "testMessage"\r\n at LoggingUnitTests.Log4NetLogTestsLoggingEnabled.GetStackFramesRecursive (source file unavailable)\r\n at LoggingUnitTests.Log4NetLogTestsLoggingEnabled.GetStackFrames (source file unavailable)

While using **dotnet vstest** the error is something like:

> Thrown System.Collections.Generic.KeyNotFoundException "testMessage"\r\n at LoggingUnitTests.Log4NetLogTestsLoggingEnabled.GetStackFramesRecursive (source file unavailable)\r\n at LoggingUnitTests.Log4NetLogTestsLoggingEnabled.mytestcasename (source file unavailable)

If you will notice, the test case name i.e. mytestcasename is being added in error message string when executing from dotnet vstest. This inconsistent behavior should have been fixed.

I would like to highlight over here that `GetStackFrames()` is my private method I have created inside my Test Class which is being invoked from my Test Case.

from @danmosemsft:

What is the true callstack? mytestcasename -> GetStackFrames -> GetStackFramesRecursive?

If so is it possible that GetStackFrames is getting inlined in the 2nd case?

When you break in in the debugger when in the innermost frame and do Environment.StackTrace, what do you get?

from @ViktorHofer:

Maybe its related to inlining but this definitely doesn't belong into corefx but into Microsoft/vstest. Moving.

**Comment by mayankbansal018** [comment]
@jaydeept, can you share a repro project for this issue?

**Comment by vagisha-nidhi** [comment]
Closing this. Please feel free to reopen with a repro project.

**Comment by jaydeept** [comment]
It was in-lining the private function when executed using dotnet vstest

**Comment by mayankbansal018** [comment]
@jaydeept testplatform will not inline any function, infact it won't even know what function is getting executed. In-lining of any function would be handled by dotnet itself.
