### ISSUE TITLE
Package inserted into CLI should not include dependencies

### ISSUE THREAD

**Issue by nguerrera** [microsoft/vstest#1886]
See https://github.com/dotnet/toolset/pull/70

These files are in the package that come from other repos (newtonsoft.json, core-setup, corefx).

NewtonSoft.Json.dll;
Microsoft.DotNet.PlatformAbstractions.dll;
Microsoft.Extensions.DependencyModel.dll;
System.Xml.XPath.XmlDocument.dll

cc @livarcocc

**Comment by mayankbansal018** [comment]
@nguerrera we simply drop dependencies present in this package to dotnet, however as the issue says dotnet sdk already brings these along, which are also latest in revision. 

Can you provide some mechanism by which we can make sure that what ever additional dependencies we have, like those mentioned above, are getting packaged into dotnet sdk, & if not then only we drop those explicitly via our nuget. 

One way I could of is by, rather can including these dll in contentFiles, & copying them, we take dependency on their respective nuget packages, but I'm not sure if that will make sure that those files get dropped if needed?

**Comment by mayankbansal018** [comment]
@nguerrera , any suggestions here please?

**Comment by nguerrera** [comment]
What other inserters to the root dotnet directory do is provide a package with genuine runtime assets and dependencies and dependencies on other things, instead of putting dlls in the content folder. We can then let nuget resolve the right version. Look at https://www.nuget.org/packages/Microsoft.Build.Runtime/
