### ISSUE TITLE
Logger parameters via command line with special characters

### ISSUE THREAD

**Issue by nvborisenko** [Microsoft/vstest#1889]
It seems I cannot do the following:
```cmd
dotnet test --logger:MyCustomLogger;param1=some_param_value_with=character_inside
```

Output:
> The Test Logger URI 'MyCustomLogger;param1=some_param_value_with=character_inside' is not valid.  The Test Logger will be ignored.

Is there some way how we can escape characters in logger parameters?

**Comment by nvborisenko** [comment]
```
dotnet test --logger:"trx;LogFileName=c:\temp\logFile.txt"
```

works.

But
```
dotnet test --logger:"trx;LogFileName=c:\temp\log=File.txt"
```
doesn't work. I really want to use `log=File.txt` as a name of my file.

**Comment by mayankbansal018** [comment]
@nvborisenko this is the current design of trx parser, as you can see, [we use "=" delimiter](https://github.com/Microsoft/vstest/blob/7fbfc61921f426b2d680a04b209ed5db804e7cc3/src/vstest.console/Processors/EnableLoggerArgumentProcessor.cs#L167) to identify the file path provided by user.

We don't see this as a major blocker for customers, & adding any specific checks to parse user input for trx logger doesn't seem a good solution.

We will be happy to take a contribution if you really feel this is something you can contribute towards. Please let us know.

**Comment by nvborisenko** [comment]
This issue is marked as `bug`, and closed. May I suppose that it is fixed?

**Comment by mayankbansal018** [comment]
@nvborisenko, Apologies, while investigating it seemed like it was a bug, but after analysis like I mentioned above this behavior is currently by design, & it doesn't seem like key scenario. However if you feel strongly, we will be happy to guide you in raising a PR for it.

Please let us know if you wish so.
