### ISSUE TITLE
Cannot build/ test vstest TestPlatform project in visual studio 2017

### ISSUE THREAD

**Issue by Mobrockers** [Microsoft/vstest#1891]
## Description
I always get this error when building and or running tests in visual studio, this is blocking me from debugging my change:

```
Code	NETSDK1007	

Description	Cannot find project info for 'C:\git\vstest\src\Microsoft.TestPlatform.CommunicationUtilities\Microsoft.TestPlatform.CommunicationUtilities.csproj'.  This can indicate a missing project reference.	

Project    samples\UnitTestProject	

File    C:\Program Files\dotnet\sdk\2.2.100\Sdks\Microsoft.NET.Sdk\targets\Microsoft.NET.Sdk.targets
```

The project builds and tests can be run using build.cmd and test.cmd, but this is not a good debugging experience.

This error comes up for any project that I try to run that uses Microsoft.TestPlatform.CommunicationUtilities through Microsoft.TestPlatform.VsTestConsole.TranslationLayer

## Steps to reproduce
Clone vstest repo, open solution in visual studio 2017 (latest bits), build project. May have to try to run tests before it shows up but it fails for me every time either when building or when running unit tests.

## Expected behavior
Project is build/ tests are run in visual studio

## Actual behavior
Error message

**Comment by Mobrockers** [comment]
After playing around I noticed the stylecop analyzers would once in a while show up as a yellow triangle with no error message. After deleting the stylecop analyzer inclusion from the TestPlatform targets file the project started behaving normally.

**Comment by mayankbansal018** [comment]
@Mobrockers , we have not seen any such issue in with VS 2017, however since you have found a workaround to your issue, should we go ahead and close this?

**Comment by mayankbansal018** [comment]
Closing this for now, we will investigate, if it repro's locally.
