### ISSUE TITLE
With VSTest.Console.Exe skipped tests' outcome is changed to "Not Executed".

### ISSUE THREAD

**Issue by pMaske** [Microsoft/vstest#1898]
## Description
The issue I am facing is that for WPF and UWP unit tests that are `Skipped` when run through test explorer have outcome of `Not Executed` when via vstest.console.exe.

I would like to know why the behavior of skipped tests as "Not Executed" in the TRX- file when run via vstest command line.

Is there a workaround for this?
Our Jenkins plug in marks the build as failed even with 0 failures  because of the "Not Executed" status for skipped tests in the trx file.

## Expected behavior
> Share the expected output

## Actual behavior
> What is the behavior observed?

## Diagnostic logs
> Please share test platform diagnostics logs. Instructions to collect logs are [here](https://github.com/Microsoft/vstest-docs/blob/master/docs/diagnose.md#test-platform-diagnostics).  
> The logs may contain test assembly paths, kindly review and mask those before sharing.

## Environment
> Please share additional details about the test environment.
> Operating system, Build version of vstest.console

**Comment by nigurr** [comment]
@pMaske `Skipped` is specific to MsTest adapter which is what's getting reported in Test explorer.
The results which are shown in Test explorer are derived from Test adapter (MsTest/Nunit/Xunit).

However TRX is not adapter specific, it has its own format of spitting out the results.
Irrespective of which test adapter being used, the TRX output format will be same (it's exactly as designed).
It's not an ideal design to propagate the adapter specific formats directly to TRX.

Please refer to this code for supported outcomes: https://github.com/Microsoft/vstest/blob/7b6248203164f8ea821f6795632bd22e0b69afb0/src/Microsoft.TestPlatform.Extensions.TrxLogger/ObjectModel/TestOutcome.cs
