### ISSUE TITLE
Failing to load test-assemblies and discover tests leads to "success" in VSTest.Console.exe

### ISSUE THREAD

**Issue by josteink** [microsoft/vstest#1899]
## Description

When trying to load broken test-projects and failing to discover tests, ideally the test-runner should report that the test-project is broken, and thus break the build.

VSTest.Console.Exe just reports failure to load DLLs or discover in the console output, but still exits with an exit code of 0.

## Steps to reproduce

1. Create a test-project with some incorrect binding redirects for a direct dependency, for instance System.Reflection.DLL.
2. Build the project (it *should* build!)
3. Try to run the tests via VSTest.Console.exe directly, or through TFS test-runner task.

````
"vstest.console.exe" C:\agent1\_work\30\b\SomeProject.Working.Tests.dll C:\agent1\_work\30\b\SomeProject.Failing.Tests.dll
````

Observe that VSTest does indeed report failure to load the DLL:

````
[MSTest][Discovery][C:\agent1\_work\30\b\SomeProject.Failing.dll] Failed to discover tests from assembly C:\agent1\_work\30\b\SomeProject.Failing.dll. Reason:Could not load file or assembly 'System.Reflection, Version=4.1.1.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' or one of its dependencies. The system cannot find the file specified.
````

However VSTest.Console.exe does not have a non-zero exit-code.

## Expected behavior

VSTest.Console to have a non-zero exit-code when failing to load tests.

Because of this highly unexpected behaviour (don't fail on failure to load specific tests), we've had builds where we after making some changes to package-references lost 90% of our test-coverage and we didn't notice until much later.

**This is a critical error.**

````
C:\> echo %errorlevel%
1
````

## Actual behavior

````
C:\> echo %errorlevel%
0
````

## Environment

This has been reproduced with local testruns on developer PCs and on TFS (on-prem) build-servers using the TFS "Visual Studio Test"-task.

(In Visual Studio this error-condition leads to the project not being visible in the Test Explorer, instead of being shown as a "red" test project)

**Comment by mayankbansal018** [comment]
@josteink , the test platform itself in not responsible to execute the tests, that is handled by Test Frameworks, & Adapters, like mstest, xunit, nunit, etc.. If the adapters report back saying that test dll had some issues, & raise error, then the platform will report that back. 

For e.g. if you provide a dll, which has no test, then the test platform will give appropriate warning for it.

**Comment by josteink** [comment]
So what you're saying is that this is not an error with VSTest itself but rather with the MSTest test-adapter?

**Comment by mayankbansal018** [comment]
@josteink yes, most likely, can you also share a small repro project, we can investigate the issue better

**Comment by mayankbansal018** [comment]
closing this.
