### ISSUE TITLE
vstest.console.exe many test dlls

### ISSUE THREAD

**Issue by saxenark** [Microsoft/vstest#1914]
Hi,
I want to know how to pass many test dlls to vstest.console.exe in VS2017. I know these assemblies have to separated by spaces but I am unsure if there is any max limitations on number of assemblies that can be passed as command line argument. Questions:

1. is there a limit on the number of arguments (or length of arguments) passed to vstest.console.exe?
2. can the assembly names be input through @file argument?
3. can the runsettings file be used to supply assembly names to vstest.console.exe

Another related question (in case I land up with multiple .trx files), is there a way to merget multiple .trx files into one, so that I can then publish them as one single HTML?

**Comment by nigurr** [comment]
@saxenark `vstest.console.exe /? ` should help you out.
You can wrap all the dlls in response file (source.txt) and pass it as `vstest.console.exe @source.txt`

**Comment by saxenark** [comment]
For reference, I was able to use TRX Merger utility well https://github.com/rndsolutions/trx-merger just in case someone needs it.

**Comment by saxenark** [comment]
@nigurr,

You mentioned earlier: "However we are already working on this functionality to show code coverage report in Azure DevOps"

Is there a ticket or reference that you can share with me for progress on this feature? When is the tentative timeline for this feature?

Thanks,
Anubhav

**Comment by nigurr** [comment]
@saxenark as mentioned, we don't have tentative timelines to share. Please watch out for Azure Devops Release notes.
