### ISSUE TITLE
How to destroy objects with live unit testing in vs2017

### ISSUE THREAD

**Issue by DinoSourcesRex** [Microsoft/vstest#1915]
## Description
First of all sorry if this is in the wrong place. If it is any direction on where I should post it is welcome.

So. I am currently running Specflow in a dotnet 471 test application for my acceptance tests.

As part of this I have a MongoDb in memory using Mongo2Go.

Unfortunately the way Specflow lets me setup the DB is using static methods and static objects, so I suspect this is part of the problem.

Example
```
[BeforeTestRun]
static void Setup() // where I setup Mongo2Go
[AfterTestRun]
static void TearDown() // where I dispose of Mongo2Go
[AfterScenario("dbdependent")]
static void CleanUp() // I run this after every test to clear the db
```

The attributes are used by specflow and work fine when executing the tests normally. I can see in task manager that a MongoDb is created and destroyed.

However when I am running this with live unit tests in VS2017 v `15.9.5` any time the live unit tests execute the MongoDb is not disposed of, leaving me to assume that the `TearDown` step is not being executed.

## Steps to reproduce
I will create an MVP later. However here is a dump of my libraries;

Dotnet Framework `471`.

```
  <ItemGroup>
    <PackageReference Include="FluentAssertions" Version="5.6.0" />
    <PackageReference Include="Microsoft.NET.Test.Sdk" Version="15.9.0" />
    <PackageReference Include="Mongo2Go" Version="2.2.9" />
    <PackageReference Include="NSubstitute" Version="4.0.0" />
    <PackageReference Include="SpecFlow" Version="2.4.1" />
    <PackageReference Include="SpecFlow.xUnit" Version="2.4.1" />
    <PackageReference Include="xunit.runner.visualstudio" Version="2.4.1">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers</IncludeAssets>
    </PackageReference>
    <PackageReference Include="xunit" Version="2.4.1" />
  </ItemGroup>
```
## Expected behavior
For the `TearDown` method to be called.

## Actual behavior
`TearDown` is not called

## Diagnostic logs
No logs, sorry.

## Environment
Windows 10 - 10.0.17763

**Comment by karanjitsingh** [comment]
@DinoSourcesRex, live unit testing is a VS IDE scenario and not a part of vstest.
@ManishJayaswal, maybe you can help?

**Comment by DinoSourcesRex** [comment]
@karanjitsingh Sorry! I can cross post the question.

**Comment by karanjitsingh** [comment]
@DinoSourcesRex, since LUT is VS IDE scenario https://developercommunity.visualstudio.com/ would be the right place to post the question.
