### ISSUE TITLE
codecoverage.exe in Visual Studio 2017

### ISSUE THREAD

**Issue by saxenark** [Microsoft/vstest#1916]
Hi,

I  have many .coverage files that I generate as part of running vstest.console.exe. It appears 'codecoverage.exe analyze' allows specifying multiple .coverage files to emit a single xml file as output. Is there a way these .coverage files can be specified in an input file to codecoverage.exe?

If not, then I would be resorting to analyzing these .coverage and generating the .xml in a for loop. Can the resulting xmls be merged together using any tool? Any reference to such a tool will be helpful

Thanks
Anubhav.

**Comment by nigurr** [comment]
Hi @saxenark,

I am sorry to inform that such functionality doesn't exist currently.
However we would like to know your end to end scenario to suggest better solution.

We highly recommend using .coverage files to publish coverage information to Azure DevOps for code coverage experience.
If you are planning to use it with any other CI solutions, we would like to help as much as possible to get going however we do have limited support.

**Comment by mayankbansal018** [comment]
@saxenark as a workaround you can use API's Microsoft.VisualStudio.Coverage.Analysis to merge your ".coverage" files. It will give you single output coverage file. Following this use can use CodeCoverage.exe to generate XML content.

**Comment by dan-morris-by** [comment]
How would I be able to convert the singleFile.coverage into xml using github actions? I've generated the *.coverage file using vstest.console.exe but can't find a github action example converting the *.coverage file to an *.xml file.
