### ISSUE TITLE
Program has more than one entry point defined. Compile with /main to specify the type that contains the entry point.

### ISSUE THREAD

**Issue by BrokeBoy123** [Microsoft/vstest#1925]
Hi, I'm new to VSC and C#. I have created two test scripts that go like this:
First One:

using System;

namespace ForIteratioin
{
    class ForIteratioin
    {
        static void Main5(string[] args)
        {
            Console.WriteLine("Hi");
            Console.ReadLine();
        }

    }   
}

Second One:

using System;

namespace C
{
    class Program
    {
        static void Main(string[] args)
        {
            Console.WriteLine("Hi");
            Console.WriteLine("Input your name here: ");
            string FIRSTNAME;
            FIRSTNAME = Console.ReadLine();
            Console.WriteLine("Your name is " + FIRSTNAME + "!");
            Console.ReadLine();
        }
    }
}

When I try to compile it shows me this: Program has more than one entry point defined. Compile with /main to specify the type that contains the entry point. How can I fix?

**Comment by mayankbansal018** [comment]
@BrokeBoy123 while creating test projects for dotnet core, we implicitly add main functions to them. There is an inherit requirement for the test projects to be compiled as OutputType = "exe", to generate all the required dependencies, else the platform can fail to run the test. 

In your sample code I don't see that you are using any test framework to actually write the test, if you use [mstest](https://github.com/Microsoft/testfx), you can simply move your code in Main, to other methods.

**Comment by acesiddhu** [comment]
@BrokeBoy123 please try what Mayank suggested. I will go ahead and close the issue now. if you have more question do open another issue
