### ISSUE TITLE
build.cmd fails

### ISSUE THREAD

**Issue by tonyhallett** [Microsoft/vstest#1929]
## Steps to reproduce
run build.cmd

## Expected behavior
build vstest

## Actual behavior
BUILD FAILED

## Diagnostic logs
C:\Users\tonyh\Documents\vstest-master\vstest-master\tools\dotnet\sdk\3.0.100-preview4-010542\Microsoft.Common.CurrentVersion.targets(1636,5): error MSB3202: The project file "..\..\..\src\DataCollectors\Microsoft.TestPlatform.Extensions.EventLogCollector\Microsoft.TestPlatform.Extensions.EventLogCollector.csproj" was not found. [C:\Users\tonyh\Documents\vstest-master\vstest-master\test\DataCollectors\Microsoft.TestPlatform.Extensions.EventLogCollector.UnitTests\Microsoft.TestPlatform.Extensions.EventLogCollector.UnitTests.csproj]
    0 Warning(s)
    1 Error(s)

## Environment
Windows 10 Pro Version 1803

**Comment by acesiddhu** [comment]
@tonyhallett can you confirm if this file exists.
"C:\Users\tonyh\Documents\vstest-master\vstest-master\src\DataCollectors\Microsoft.TestPlatform.Extensions.EventLogCollector\Microsoft.TestPlatform.Extensions.EventLogCollector.csproj"

**Comment by acesiddhu** [comment]
@tonyhallett I am closing the issue for now. if you continue to face the issue please do reopen the issue
