### ISSUE TITLE
Cannot run unit tests for .NET core in dll with target platform x64 via IDE

### ISSUE THREAD

**Issue by singhsarab** [Microsoft/vstest#193]
## Description
> Changing the platform to x64 and building the project. Discovery kicks in, but no tests are reported in the TestWindow.

## Steps to reproduce
> Create a .NET core unit test project.
> Change the target platform configuration to x64.
> Build the solution

## Expected behavior
> The tests should get discovered.

## Actual behavior
> Discovery ends and no tests are discovered.

**Comment by smadala** [comment]
No repro.
