### ISSUE TITLE
Extend TestLoggerEvents with TestStarted event

### ISSUE THREAD

**Issue by nvborisenko** [Microsoft/vstest#1930]
TestLoggers knows when test finishes with specific `TestResult`
```csharp
public void Initialize(TestLoggerEvents events, string testRunDirectory)
{
  events.TestResult += TestResultHandler;
}
```

It would be nice if `TestLogger` also can handle event when specific test is starting execution.

**Comment by acesiddhu** [comment]
@nvborisenko whats the scenario?

**Comment by nvborisenko** [comment]
Just to provide much more information about tests execution for TestLogger. In my particular scenario TestLogger wants to know when test was started to handle this event properly. This should improve logging of events in case of kind of `real-time` logging, so user is able to see all in-progress tests.

**Comment by mayankbansal018** [comment]
@nvborisenko is it possible for you to try and implement it, we will we happy to help you in case you need help

**Comment by mayankbansal018** [comment]
@nvborisenko I'm closing this, please let us know if datacollection approach doesn't work for you.

**Comment by nvborisenko** [comment]
Could you please briefly explain what is principle difference between datacollector and testlogger? I see that architecturally they are similar. They get events from test platform and save it to somewhere. I saw trx logger and console logger (they are saving tests info), also I saw VideoRecorder (not sure whether this is logger or datacollector).

As for me all they are very similar. I see that others unit frameworks have full capability to notify when test was starting and finishing. I can understand that performance plays big role in unit testing, but I hope it play less role when we are talking about integration and acceptance testing.

I understand that MsTest/VsTest is one more tool for testing with it's own great features like executing data driven test at once and get all results (actually hating it when executing 30 UI tests).

Team, I am considering to use data collector approach. Please share your knowledge here. I am expecting that `testlogger` is particular case of `datacollector`, is it right? Thanks all in advance.
