### ISSUE TITLE
No release notes for version 16.0.0

### ISSUE THREAD

**Issue by Mobrockers** [Microsoft/vstest#1934]
Version 16.0.0 has been released to nuget.org today but I cannot find any release notes nor release packages on github. Please add the release notes so we can see what has been changed.

**Comment by vagisha-nidhi** [comment]
@Mobrockers We have added the release notes for 16.0.0. Please find it [here](https://github.com/Microsoft/vstest-docs/blob/master/docs/releases.md#1600).
