### ISSUE TITLE
Enable dependency flow

### ISSUE THREAD

**Issue by chcosta** [microsoft/vstest#1941]
Dependencies which are a part of source build, but do not publish using dependency flow end up causing incoherent builds. Source build is not able to determine which version of the asset is needed because it is not reported to BAR and then someone must manually go to a repo (like core-sdk) and trace back to find which version of the dependency is needed so that it can be built.

https://github.com/dotnet/arcade/blob/master/Documentation/DependencyFlowOnboardingWithoutArcade.md

**Comment by singhsarab** [comment]
/cc: @cltshivash @PBoraMSFT We would need to plan this work.

**Comment by chcosta** [comment]
Any update on this?

**Comment by singhsarab** [comment]
@chcosta This work is planned for this quarter. Will update once, we pick this.

**Comment by chcosta** [comment]
@singhsarab , am I to take "this quarter" as meaning, "it will be done by June"?  The last day for .NET Core 3.0 support in Jenkins is May 3rd.

**Comment by singhsarab** [comment]
@chcosta How is this related to Jenkins ?

**Comment by chcosta** [comment]
Ack, you're right, my bad. I crossed streams.

**Comment by singhsarab** [comment]
@chcosta fixed the issue hit while trying to generate manifest. Refer https://github.com/dotnet/arcade/pull/3080#pullrequestreview-251498763
