### ISSUE TITLE
Run custom adapter in Extensions folder

### ISSUE THREAD

**Issue by armanio123** [Microsoft/vstest#1944]
## Description
I was trying to setup a custom test adapter to the Extensions folder in Visual Studio but the test console doesn't pick it up as stated in bullet 5 of [Adapter Extensibliy documentation](https://github.com/Microsoft/vstest-docs/blob/master/RFCs/0004-Adapter-Extensibility.md). 

I tried testing it by running `dotnet test` on a .NET Core Console App after pasting our dlls on the Extensions folder.

I already reference the Microsoft.NET.Test.Sdk on the project. Is there an additional configuration? 

This is for project [Node.js Tools for Visual Studio](https://github.com/Microsoft/nodejstools/). Here's the [pull request](https://github.com/Microsoft/nodejstools/pull/1997) for reference.

## Steps to reproduce
1. Copy or custom adapter dll to the Extensions folder in visual studio (`C:\Program Files (x86)\Microsoft Visual Studio\2019\Preview\Common7\IDE\CommonExtensions\Microsoft\TestWindow\Extensions`)
2. Create a .Net Core project
3. Add the Microsoft.NET.Test.Sdk from nuget.
4. Set on the project the property `<GenerateProgramFile>false</GenerateProgramFIle>'
5. Add a JavaScript unit test and install the npm package necessary (e.g. Mocha).
6. Open a console in the project folder and run `dotnet test`
7. Console shows message "No test found" (seems like it's not picking up our adapter).

## Expected behavior
Run JavaScript unit tests.

## Actual behavior
No tests found.

## Diagnostic logs
[log.host.19-03-06_13-56-03_75492_5.txt](https://github.com/Microsoft/vstest/files/2938566/log.host.19-03-06_13-56-03_75492_5.txt)
[log.txt](https://github.com/Microsoft/vstest/files/2938568/log.txt)

**Comment by acesiddhu** [comment]
@armanio123 I didnt try to repro the issue. I have few suggestions though.
1) C:\Program Files (x86)\Microsoft Visual Studio\2019\Preview\Common7\IDE\CommonExtensions\Microsoft\TestWindow\Extensions is a wrong path to place any extensions. the correct place is C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\Common7\IDE\Extensions\TestPlatform\Extensions
2) We dont suggest loading of custom adapters from extensions folder. that is also mentioned in the link u mentioned. only out of the box plugins should be in that folder. you should try testadapterpath route instead.

**Comment by armanio123** [comment]
@acesiddhu I tried the path you mentioned but still vstest is not picking it up. The name of the dll is `Microsoft.JavaScript.TestAdapter.dll` I don't know if that has anything to do.

In regards to the Extensions folder. This is for the Node.js Tools for Visual Studio repo that ships with Visual Studio. We're trying to add support to JS tests on .NET Core apps and would like to deploy the dll out of the box. Is this the suggested way of doing it? We also consider creating a nuget package for this but we prefer to avoid the drawback of having a different release pipeline just for this. FYI, `dotnet test` works if installing through the nuget package.

**Comment by armanio123** [comment]
Hi @acesiddhu any comments on my reply? Might be a good idea to sync offline to get a better understanding on vstests and nodejstools repos.

**Comment by cltshivash** [comment]
@armanio123 The Extensions folder is not recommended for any new adpaters (including MSTest V2) and the recommendation is to use Nuget packages/alternatives to lay down the adpater next to the test dll/test file.
