### ISSUE TITLE
as a tfs 2018 agent all test method pass but test fail ,VsTest task failed.

### ISSUE THREAD

**Issue by mehdiAbbaspour** [Microsoft/vstest#1949]
i am use xunit in vs 2015 and tfs 2018 with ci/cd
error: 
Vstest failed with error. Check logs for failures. There might be failed tests.
Error: C:\Program Files (x86)\Microsoft Visual Studio 14.0\Common7\IDE\CommonExtensions\Microsoft\TestWindow\vstest.console.exe failed with return code: 1
VsTest task failed.

and  test assembly with this script :
**\$(BuildConfiguration)\*tests*.dll
!**\obj\**;-:**\xunit.runner.visualstudio.testadapter.dll

**Comment by mehdiAbbaspour** [comment]
then see trx file and find this error 
An exception occurred while invoking executor 'executor://xunit/VsTestRunner2/uap': Could not load file or assembly 'System.IO.FileSystem, Version=4.0.1.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' or one of its dependencies. The system cannot find the file specified.	
[xUnit.net 00:00:01.90] Skipping: Insurance.Tests (could not find dependent assembly 'System.Runtime, Version=4.1.0')	DEPLOYMENT

**Comment by ShreyasRmsft** [comment]
@mehdiAbbaspour can you please use the latest test platform using https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/tool/vstest-platform-tool-installer?view=azure-devops

Also please provide the entire set of logs for the build after setting system.debug = true.

**Comment by ShreyasRmsft** [comment]
Closing due to no-response. Please re-open the issue with the requested steps.
