### ISSUE TITLE
System.Security.VerificationException : Operation could destabilize the runtime

### ISSUE THREAD

**Issue by TclasenITVT** [Microsoft/vstest#1950]
## Description
We have set up a CI Pipeline in Azure DevOps that first builds out Library and then continues with first installing the Visual Studio Test Plattform via the Visual Studio Test Plattform Installer build task and then running the tests with the Visual Studio Test Build Task. Here we set it to use the Visual Studio Test Plattform and also checked the enable Code Coverage checkbox. The Problem is that when the Code Coverage Tool is executed our Test that use Newtonsoft.Json(12.0.0) JsonConvert<T>.Serialize() throw a "System.Security.VerificationException : Operation could destabilize the runtime". 
A small Repro Repository can be found [here](https://github.com/TclasenITVT/VSTestPlatformIssueRepro).
## Steps to reproduce

1. Create a new Azure DevOps Project
2. Import Repository from Github https://github.com/TclasenITVT/VSTestPlatformIssueRepro
3. Run Build
4. Experience  Build Error

Library built with .Net Framework 4.6.2
Visual Studio Test Platform 16.0.1
XUnit 2.4.1.0

## Expected behavior
The CodeCoverage should successfully be computed

## Actual behavior
The Task Fails with a System.Security.ValidationException.

## Diagnostic logs
[log_10_153.zip](https://github.com/Microsoft/vstest/files/2951960/log_10_153.zip)

## Environment
I am using the Azure DevOps Windows Agent 'VS2017-Win2016'

**Comment by ayls** [comment]
I bumped into the same issue, but then tried a different JSON serializer:

https://docs.microsoft.com/en-us/dotnet/api/system.web.script.serialization.javascriptserializer?view=netframework-4.7.2

That got my tests going so I suppose the issue is more likely to be with Newtonsoft.Json.

**Comment by samneefs** [comment]
Had the same problem, after switching to Newtonsoft.Json version 12.
Turning of Code Coverage seems to be the only workaround for me. The other JSON serializer isn't an option for me: since it isn't .NET Standard
Also found a related issue: https://github.com/nunit/nunit3-vs-adapter/issues/519

**Comment by samneefs** [comment]
Seems to be fixed with the combination of:
Latest Newtonsoft.Json 12.0.2 (doesn't work with 12.0.1)
Latest stable Test platform: 16.2 (should be >16.0.2)
Latest VSTest task 2.156.2 (should be >2.153.0)

**Comment by ani-mal** [comment]
Also seeing this problem with VS2017 DotCover. 

**To go around this issue the following approaches worked:**
- Add an assembly filter to remove Unity 
![2019-10-29_9-18-21](https://user-images.githubusercontent.com/36199397/67793938-26661f80-fa52-11e9-92d8-359721353a14.png)
- Use Assembly filters to only add the assemblies you want the code coverage to be checked. So instead of excluding Unity assemblies, just add the assemblies from your project that you want to be checked
