### ISSUE TITLE
Visual Studio Test in Team Foundation Server 2018 Patch 3.2 dont use runsettings

### ISSUE THREAD

**Issue by CSmith1111** [Microsoft/vstest#1956]
## Description
VSTest don't take the runsettings you provide by console options or directly from the tfs config site.
The runsettings is allways a default runsettings.

## Steps to reproduce
1: Create a VsTest Buildstep in TFS 
2: Select a runsettings from your project or pass it over console options
3: Check "...\AppData\Local\Temp\[a-z0-9]*.txt" for the vstest config and search for /Settings:"C:\Users\[a-zA-Z0-9]*\AppData\Local\Temp\[a-zA-Z0-9\-]*.runsettings"

## Expected behavior
70a71f50-45a2-11e9-9ea6-419c4a7353e6.runsettings should be the runsettings from the repository or a merge.

## Actual behavior
The runsettings is allways a default runsettings.

`<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<RunSettings>
  <DataCollectionRunSettings>
    <DataCollectors>
      <DataCollector friendlyName="Code Coverage" uri="datacollector://Microsoft/CodeCoverage/2.0" assemblyQualifiedName="Microsoft.VisualStudio.Coverage.DynamicCoverageDataCollector, Microsoft.VisualStudio.TraceCollector, Version=11.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a">
        <Configuration>
          <CodeCoverage>
            <UseVerifiableInstrumentation>False</UseVerifiableInstrumentation>
          </CodeCoverage>
        </Configuration>
      </DataCollector>
    </DataCollectors>
  </DataCollectionRunSettings>
</RunSettings>`

## Environment
Team Foundation Server 2018 Patch 3.2
VsTest 16.0.1

**Comment by ShreyasRmsft** [comment]
@CSmith1111 can you please provide the complete logs with system.debug = true

One of the reasons it takes the default runsettings is if the provided one is invalid.

**Comment by CSmith1111** [comment]
hope this is what you asked for, all logs whould be 9,44 MB / 120 MB

Localoutput
![cc_results_local](https://user-images.githubusercontent.com/48524869/54436083-2bc86100-4732-11e9-8543-ccd74bf0b6b2.png)

Agentoutput
![cc_results_agent](https://user-images.githubusercontent.com/48524869/54436090-2ff47e80-4732-11e9-9a7e-5f090b77c6fc.png)

VsTest - testAssemblies Output / Log (just VsTest log without unittestdata, file would be > 30mb)
[7_VsTest - testAssemblies.txt](https://github.com/Microsoft/vstest/files/2971352/7_VsTest.-.testAssemblies.txt)

Runsettings
[CodeCoverage.runsettings.txt](https://github.com/Microsoft/vstest/files/2971368/CodeCoverage.runsettings.txt)

**Comment by ShreyasRmsft** [comment]
@CSmith1111 there was a minor bug that we found and patched later round.

As a workaround:
Can you untick _enable code coverage_ in the task

and then add this to your runsettings file: <UseVerifiableInstrumentation>False</UseVerifiableInstrumentation>

the way it is getting added in the generated default runsettings

**Comment by CSmith1111** [comment]
If i untick "enable code coverage" the task don't create a runsettings but use my runsettings i defined in the vstest build step. this works fine and the .coverage also looks good. only problem is that now my .coverage don't get published to the overview but to " http://tfs:8080/tfs/XX/XXXX/_TestManagement/Runs#runId=543&_a=runCharts" under attachments.

![Clipboard01](https://user-images.githubusercontent.com/48524869/54528640-d08aae80-497d-11e9-975f-8befb33318e9.png)
![Clipboard02](https://user-images.githubusercontent.com/48524869/54528697-f9ab3f00-497d-11e9-8633-a21669de39b7.png)

**Comment by CSmith1111** [comment]
If i untick "enable code coverage" the task don't create a runsettings but use my runsettings i defined in the vstest build step. this works fine and the .coverage also looks good. only problem is that now my .coverage don't get published to the overview but to " http://tfs:8080/tfs/XX/XXXX/_TestManagement/Runs#runId=543&_a=runCharts" under attachments.
![Clipboard02](https://user-images.githubusercontent.com/48524869/54528849-7a6a3b00-497e-11e9-911c-bf8a9fb54230.png)
![Clipboard01](https://user-images.githubusercontent.com/48524869/54528851-7a6a3b00-497e-11e9-8214-30b5b13fea3d.png)

**Comment by ShreyasRmsft** [comment]
@CSmith1111 this has nothing to do with the fact that you unticked the code coverage checkbox.
The job that publishes this charts generally runs after sometime and not immediately.

You are saying this used to work before? Can you try queueing a few more runs (a mix of with the checkboc ticked and without) and tell me whether the code coverage summary appears?

**Comment by CSmith1111** [comment]
This used to work if the box is ticked.
Code Coverage in the Build Details used to have a downloadlink for the .coverage, now i have to go to the TestManagementHub if i unticked the box. 
It will come back to the Build Details if i add mspremier.BuildQualityChecks to the build.

**Comment by ShreyasRmsft** [comment]
@CSmith1111 the bug I mentioned was fixed in later updates (mostly in 2018 U3 the fix should be present).

I lost you in the last comment. Could you please explain with screenshots all the differences in terms of the coverage UI report of a build with the box checked and without.

**Comment by ShreyasRmsft** [comment]
@CSmith1111 any updates here?

**Comment by ShreyasRmsft** [comment]
Closing due to no response. Please re-open if still facing the issue.
