### ISSUE TITLE
vstest.console hangs indefinitely randomly

### ISSUE THREAD

**Issue by kiragengis** [Microsoft/vstest#1958]
## Description
When running Selenium tests via TeamCity build process occasionally get hangs. The only way to recover from them is to cancel the build. Even when looks like a random event always happen with the same tests. I compared the vstest.console log between a hanging test and any other and the only difference is the hanging one has missed the last six lines. The vstest.console is called from C# with Visual Studio Enterprise 2017 using the console.

## Steps to reproduce
Very hard to reproduce and we can't reliably duplicate it internally. 

The way we call the vstest.console from C#:
`process = new Process();`
`ProcessStartInfo startInfo = new ProcessStartInfo();`
`process.StartInfo.FileName = vstestConsolePath;`
`process.StartInfo.UseShellExecute = false;`
`process.StartInfo.RedirectStandardOutput = true;`
`process.EnableRaisingEvents = true;`
`process.Exited += new EventHandler(Process_Exited);`
`process.StartInfo.Arguments = string.Format($"{dll} /Tests:{FQDNTestname} /Settings:{settings}");`
`process.Start();`

Command line used:
`"C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\Common7\IDE\CommonExtensions\Microsoft\TestWindow\vstest.console.exe" "C:\testing.dll" /Tests:MyTest /Settings:"C:\mySettings.runsettings"`

## Expected behavior
Test run finishes without hanging.

## Actual behavior
Tests freeze and never recover.

## Diagnostic logs
This is the log from vstest.console:
https://drive.google.com/file/d/1XiaC21HOYe1ov3PoKw1shiYVBgV_1QzV/view?usp=sharing
This a log from ProcMon (Process Monitor) when the vstest.console is hanging:
https://drive.google.com/file/d/1BgC0peX5gg5lSTwYk3sexbFgiq1HdoKB/view?usp=sharing

## Environment
Windows 10 Enterprise 1703
Vstest.console version 15.0.28307.421

**Comment by ShreyasRmsft** [comment]
Are you on TFS Onprem or AzureDevops Hosted Service?

**Comment by kiragengis** [comment]
> Are you on TFS Onprem or AzureDevops Hosted Service?

We are using TFS Onprem

**Comment by ShreyasRmsft** [comment]
@kiragengis can you please provide me the task logs with system.debug == true.

Also the version of the vstest task if possible.

I add the fix for the hangs in the following [commit](https://github.com/Microsoft/azure-pipelines-tasks/commit/5460d2bf0177b10c9c809404fea20092a56f4e69#diff-0105c71955f75e0dad8170e7296413f0)

**Comment by ShreyasRmsft** [comment]
It is the responsibility of the test code to ensure all stale threads and process are terminated. If something lingers on then vstest.console.exe will not exit.

The commit I made force terminates such child processes to ensure there is no hang in case of running this on TFS. Azure-pipelines-tasks is the repo where the tasks for VSTS/TFS (now called AzureDevops).

**Comment by kiragengis** [comment]
@ShreyasRmsft I made a horrible mistake in the description of the defect. I am actually running the test in TeamCity and not the TFS, I am going to update the main description. Does your commit still fix my issue? I am really ashamed :(
I saw you commit is from January, what should I do to use it?

**Comment by kiragengis** [comment]
I have made some other tests. So far the only way to reproduce the issue (not consistently) is when I use:
`process.StartInfo.RedirectStandardOutput = true;`
`string results = process.StandardOutput.ReadToEnd();`

So far with these lines commented I have never been able to reproduce it. I am going to keep running the tests with the lines commented in order to verify if I am able to reproduce the issue.

**Comment by ShreyasRmsft** [comment]
@kiragengis the commit i made is for AzureDevops. This is not a vstestconsole issue as it is stale processes from the test code that is causing the issue. If you take a look at the processes list when this happens you will see a stale chrome (or someother browser) or chromedriver process lingering on that has inherited the stdout stream from vstestconsole.exe. It is the test code responsibility to ensure all such stale processes are killed.

One way to fix this issue is to change the code to this:

```
            var process = new Process
            {
                StartInfo =
                {
                    FileName = vstestConsolePath,
                    UseShellExecute = false,
                    RedirectStandardOutput = true,
                    RedirectStandardError = true,
                    Arguments = argsToPass
                }
            };

            //Stream the output data and error data to ExecutionTrace -> agent commands
            process.OutputDataReceived += (sender, e) =>
            {
                if (!string.IsNullOrEmpty(e.Data))
                {
                    ExecutionTrace.Info(e.Data);
                }
            };
            process.ErrorDataReceived += (sender, e) =>
            {
                if (!string.IsNullOrEmpty(e.Data))
                {
                    ExecutionTrace.Error(e.Data);
                }
            };

            try
            {
                if (!process.Start())
                {
                    ExecutionTrace.Error(string.Format(CultureInfo.CurrentCulture, Resource.FailedToStart, vstestConsolePath));
                    return 1;
                }
            }
            catch (Win32Exception)
            {
                ExecutionTrace.Error(string.Format(CultureInfo.CurrentCulture, Resource.ErrorInVsTestConsoleExe, vstestConsolePath));
                throw;
            }

            // Asynchronously read the standard output of the spawned process.
            // This raises OutputDataReceived events for each line of output.
            process.BeginOutputReadLine();
            process.BeginErrorReadLine();

            while (!process.HasExited)
            {
                process.WaitForExit(1000);
            }

            var exitCode = process.ExitCode;

            process.Close(); // once the process is closed, can't access any properties
```

**Comment by kaadhina** [comment]
Please try the above if the issue reproduces. And reopen if needed.
