### ISSUE TITLE
Additional Settings for Video Data Collector

### ISSUE THREAD

**Issue by tomaustin700** [microsoft/vstest#1959]
## Description
I am wanting to use the video data collector when running ui tests on Azure DevOps Server. After trialing this I am struggling to find any way to configure the data collector. Ideally I want to be able to reduce the quality of the videos as we have close to 2000 tests that run nightly, my testing has shown a 1min test produces a 2mb wmv file and a lot of our tests take upwards of 5 mins to run. Without being able to reduce the quality and the filesize it would be uploading a huge amount of data into Azure DevOps Server which is not ideal. Is there any advanced configuration or documentation for the video data collector?

Currently the only documentation I can find regarding the data collector is [here](https://docs.microsoft.com/en-gb/visualstudio/test/configure-unit-tests-by-using-a-dot-runsettings-file?view=vs-2017#video-data-collector). Which looks like this:

```xml
<DataCollectionRunSettings>
    <DataCollectors>
      <DataCollector uri="datacollector://microsoft/VideoRecorder/1.0" assemblyQualifiedName="Microsoft.VisualStudio.TestTools.DataCollection.VideoRecorder.VideoRecorderDataCollector, Microsoft.VisualStudio.TestTools.DataCollection.VideoRecorder, Version=15.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a" friendlyName="Screen and Voice Recorder">
        <!--Video data collector was introduced in Visual Studio 2017 version 15.5 -->
      </DataCollector>
    </DataCollectors>
  </DataCollectionRunSettings>
````

It would be good if I could specify a directory (ideally a unc path) where the video files are stored and also stop it uploading the file. Being able to name the video file would be useful also (ideally using the test name).

Thanks

**Comment by ShreyasRmsft** [comment]
@tomaustin700 you can get the required nodes by creating a testsettings file in VS and adding the screen and voice recorder and double clicking on it:

![image](https://user-images.githubusercontent.com/25194518/54590791-e5834280-4a4e-11e9-9587-4f8211769c65.png)

**Comment by tomaustin700** [comment]
@ShreyasRmsft Thanks for getting back to me, can an option to disable upload and save to a directory be added? If you have thousands of tests (as we do) then a huge amount of data would be uploaded to the database.

**Comment by ShreyasRmsft** [comment]
@PBoraMSFT

**Comment by Hilarius86** [comment]
I also search the web for the settings and failed. Maybe the documentation could be updated reporting all the possible settings.

**Comment by cvpoienaru** [comment]
Closing this issue since video data collector is a legacy tool and enhancing it is not a team priority.
