### ISSUE TITLE
[Urgent] DependencyContext cannot load entry assembly when used in a net46 test.

### ISSUE THREAD

**Issue by NTaylorMullen** [Microsoft/vstest#196]
## Description
Trying to do `DependencyContext.Load(TheCurrentAssembly)` in a net46 test returns null due to [core-setup's "is entry assembly check"](https://github.com/dotnet/core-setup/blob/eca152525e19a41d489cd5845afa14982653cc0a/src/Microsoft.Extensions.DependencyModel/DependencyContextLoader.cs#L64) failing. Ultimately it fails due to `Assembly.GetEntryAssembly()` returning `null` when invoked inside of a test. The test runner should ensure `GetEntryAssembly` works as expected.

## Environment
**dotnet --info:**
```
.NET Command Line Tools (1.0.0-preview3-004056)

Product Information:
 Version:            1.0.0-preview3-004056
 Commit SHA-1 hash:  ccc4968bc3

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.14393
 OS Platform: Windows
 RID:         win10-x64
```

**Microsoft.NET.Test.Sdk version tested:**
`15.0.0-preview-20161024-02`

**Comment by NTaylorMullen** [comment]
So I got back into migrating MVC this week and it looks like it was a different test that was failing than what I had tested above. This issue still holds true but for different reasons.

1. Desktop deps.json bits are not embedded into dll's anymore therefore [this check](https://github.com/dotnet/core-setup/blob/103226631f8393af0e16a206521795786d6e0ab7/src/Microsoft.Extensions.DependencyModel/DependencyContextLoader.cs#L114) fails. (**By Design**)
2. The test.dll is shadow copied to a temporary location for desktop which ends up breaking the logic [here](https://github.com/dotnet/core-setup/blob/103226631f8393af0e16a206521795786d6e0ab7/src/Microsoft.Extensions.DependencyModel/DependencyContextLoader.cs#L122) to locate the deps.json's location on disk. (**The Problem**)

In the end DependencyContext has no way of locating the deps.json file for the test.dll so `DependencyContext.Load(TestAssembly)` fails. May be able to work around the issue by also shadow copying (or manually copying) the deps.json file.

**Comment by blackdwarf** [comment]
@NTaylorMullen what is the latest you were able to do?

@codito @Faizan2304 any ideas?

**Comment by NTaylorMullen** [comment]
> @NTaylorMullen what is the latest you were able to do?

Not sure I follow.

**Comment by blackdwarf** [comment]
@NTaylorMullen you mentioned that you might be able to work around the issue, so just asking were you able to work around it or is this still blocking you?

**Comment by NTaylorMullen** [comment]
@blackdwarf Didn't go down that path yet. I let the test failure live and moved onto the next MVC test pieces to find more issues 😄. I'd imagine manually copying the bits needed next to the shadow copied dll for net46 should work but that's all speculation.

**Comment by blackdwarf** [comment]
@NTaylorMullen ok. :) Is this blocking you?

**Comment by NTaylorMullen** [comment]
After discussions with @Eilon. Yes this is blocking, if you could mark it as so that'd be great 😄

**Comment by Eilon** [comment]
@blackdwarf can we have a label in this repo called "blocking release" and mark this issue with that label? That way we can track it in Core War.

cc @balachir because we'll want to track this in his queries.

**Comment by blackdwarf** [comment]
@Eilon yup, makes sense. :)

**Comment by codito** [comment]
> The test.dll is shadow copied to a temporary location for desktop which ends up breaking the logic here to locate the deps.json's location on disk. (The Problem)

Shadow copy is default behavior of xunit adapter. It can be turned off with a [configuration file](https://xunit.github.io/docs/configuring-with-json.html). See attached project for sample.
[xunit3.zip](https://github.com/Microsoft/vstest/files/735979/xunit3.zip)

Following test passes with configuration.
```csharp
        [Fact]
        public void Test1()
        {
            // This passes since testhost.exe executes from assembly directory
            Assert.Equal(Environment.CurrentDirectory, @"D:\tmp\bash\xunit3\bin\Debug\net46");

            // This fails because the assembly seems to run from %temp%
            Assert.Equal(@"D:\tmp\bash\xunit3\bin\Debug\net46\xunit3.dll", typeof(UnitTest1).GetTypeInfo().Assembly.Location);
        }
```

**Comment by codito** [comment]
Closing this issue since `shadow copy` feature is part of adapter business logic and is configurable. It is not possible to fix it from test platform.
