### ISSUE TITLE
Naming nunit tests with "{m}" in formatting string creates artifacts in Test Explorer

### ISSUE THREAD

**Issue by lightmanca** [Microsoft/vstest#1970]
Environment:
     Visual Studio 2017 v15.9.9, also 2019 preview
     .Net Core solution
     Nunit3TestAdapter v 2.13.0
     Nunit v3.11.0
     Microsoft.NETCore.App v 2.2.3
     Microsoft.NET.Test.Sdk v16.0.1

With the following code:

using NUnit.Framework;

namespace TestArtifactSample
{
    [TestFixture]
    public class Program
    {
        public const string TestCaseNameAddValid = "{m}(Adding {0} and {1} = {2} Valid)";
        public const string TestCaseNameAddInvalid = "{m}(Adding {0} and {1} = {2} Invalid)";

        [TestCase(1 , 2, 3, true, TestName = TestCaseNameAddValid)]
        [TestCase(2 , 2, 4, true, TestName = TestCaseNameAddValid)]
        [TestCase(2 , 2, 5, false, TestName = TestCaseNameAddInvalid)]
        [TestCase(2 , 2, 10, false, TestName = TestCaseNameAddInvalid)]
        public void TestAdd(int a, int b, int expected, bool isValid)
        {
            if(isValid) 
            {
                Assert.AreEqual(expected, a + b);
            }
            else
            {
                Assert.AreNotEqual(expected, a + b);
            }
        }
    }
}

Visual studio test explorer will generate the test cases, and then find additional test cases beginning with {m}.

![image](https://user-images.githubusercontent.com/4454342/54960369-883d3480-4f19-11e9-8773-439080f40c08.png)

Also occasionally I have to clean, and rebuild to get all test cases to show up.

Expected results:  Artifact test names starting with "{m}" do not show up, performing rebuild causes test cases with variable interpolated names to show up.

Actual:  As shown above the tests cause test artifacts to show up in test explorer.

Note:  It does not matter if I'm using variables for test names as shown above, or with hard coded strings, such as:
        [TestCase(1 , 2, 3, true, TestName = "{m}(Adding {0} and {1} = {2} Valid)")]
        [TestCase(2 , 2, 4, true, TestName = "{m}(Adding {0} and {1} = {2} Valid)")]
        [TestCase(2 , 2, 5, false, TestName = "{m}(Adding {0} and {1} = {2} Invalid)")]
        [TestCase(2 , 2, 10, false, TestName = "{m}(Adding {0} and {1} = {2} Invalid)")]

**Comment by lightmanca** [comment]
Fyi.  I am using Nunit's Template based naming, outlined here.
https://github.com/nunit/docs/wiki/Template-Based-Test-Naming

**Comment by cltshivash** [comment]
Please report this issue in VS Developer community channel. https://developercommunity.visualstudio.com/spaces/8/index.html
