### ISSUE TITLE
Unable to execute codedui tests without installing Visual Studio thrtough Azure DevOps

### ISSUE THREAD

**Issue by Selvaraj1989** [Microsoft/vstest#1971]
## When the "Visual Studio Test Platform Installer" and "VsTest" tasks are added in the release definition, the CodedUI tests are failed with the below errors.

019-03-26T04:42:39.6678793Z ##[warning]DiscoveryMessage : TestSettings will soon be deprecated for automated unit and functional testing scenarios. It is recommended that you use RunSettings. To learn more, see http://aka.ms/runsettings
2019-03-26T04:42:40.3716628Z ##[warning]DiscoveryMessage : No test is available in F:\CodedUIAutomation\CodedUIAutomation\Test.dll. Make sure that test discoverer & executors are registered and platform & framework version settings are appropriate and try again.

Please help to resolve the issue.

**Comment by ShreyasRmsft** [comment]
Please provide the full set of logs (the entire zipfile you get when you click download all logs) with system.debug = true.

Also if you are building with a particular major version of VS then you will have to ensure you use the same major version of the testplatform when running CODED UI tests. My suspicions are on this.

**Comment by ShreyasRmsft** [comment]
@Selvaraj1989 closing due to no response, please re-open if you are still facing issues (with the requested logs) after following the suggestion above.
