### ISSUE TITLE
SettingsMigrator: Remote execution is not added in .runsettings

### ISSUE THREAD

**Issue by AndrewASel** [Microsoft/vstest#1973]
## Description
I used SettingsMigrator.exe tool for convert .testsettings to . runsettings. Remote execution parameters has been skipped in .runsettings file

## Expected behavior
Add remote execution settings in converted .runsettings file

## Actual behavior
TestSettings:
`<RemoteController name="Testcontroller" />`
 `<Execution location="Remote" parallelTestCount="2">`

Converted .runsettings file

`<MSTest>`
    `<ForcedLegacyMode>true</ForcedLegacyMode>`
  `</MSTest>`
  `<LegacySettings>`
   `<Execution parallelTestCount="2">`

Is any ability to execute automated tests on remote Test controllers with .runsettings file?

**Comment by mayankbansal018** [comment]
@kaadhina , can you please take a look

**Comment by kaadhina** [comment]
Hi @AndrewASel Remote controller is not a supported node in runsettings.

**Comment by AndrewASel** [comment]
Hello @kaadhina thank you!
I believe this can be related with 
Unable to run unit tests remotely on Test Agent using MSTest V2
https://github.com/Microsoft/testfx/issues/315

But actually starting form visual studio version 15.5 we getting message before test execution: TestSettings will soon be deprecated for automated unit and functional testing scenarios. It is recommended that you use RunSettings. To learn more, see http://aka.ms/runsettings

Is no any replacement (maybe it predicted in future versions) of testsettings to continue use test controller and test agents infrastructure? 
We are not able to use vstest task only on one server, because we need to distribute tests between remote agents to reduce time of testing.

Run Functional Tests task - which allowed distribute tests between agents, also became deprecated.
https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/test/run-functional-tests?view=azure-devops

**Comment by kaadhina** [comment]
@AndrewASel , the recommended way to distribute test is to use the multi agent settings in the pipeline itself. Please read https://aka.ms/testingwithphases for more info.

**Comment by AndrewASel** [comment]
@kaadhina
We use test controller and agents for CUIT+Selenium UI testing. Why we need to distribute tests:
1. Reduce time of execution thousand of tests, sure we can turn on parallelization, but it take resources. Anyway we use parallelization for selenium to reduce time of execution even on multiple agents.
2. We need to use different OSs and browsers.
We can take a look at selenium grid as alternative.

**Comment by kaadhina** [comment]
@AndrewASel Testing with phases (https://aka.ms/testingwithphases) will allow to do all the above mentioned scenarios. And is the recommended approach.

**Comment by AndrewASel** [comment]
Thanks @kaadhina, I will try it.
Testing with phases does not support Chrome/Edge and hosted agents, I believe in VStsets Version 3 task, this options will be available?
We not able to execute coded UI tests on build servers directly.
I will also try to copy artifacts to remote agents and execute this task, I hope that  I will be have only 1 combined .trx in output as we usually have when using remote controller.

>The test phase is setup as multi-config using ‘Browser’ variable, that has the values IE and Firefox. 
>....
> 4. Can I run UI tests on the hosted agents?
>    No, running UI tests on the hosted agents is not possible currently.

**Comment by kaadhina** [comment]
@AndrewASel  Testing on hosted agents is supported. It has chorme and firefox browsers installed.
Coded UI is not supported on hosted agents but you can run UI tests with selenium and that is the recommended approach as well. Or you can set your own agents and install anything you want.
There will not be one single combined trx, but you will have one single consolidated test reporting on the server.
Sure, please try this out and get back in case of questions.
