### ISSUE TITLE
Trx file has redundant outcomes listed in summary

### ISSUE THREAD

**Issue by WillR27** [Microsoft/vstest#1974]
At the end of a Trx results file, there is a ResultsSummary node with a count for each possible test outcome, however, from what I can tell it will only count 'total', 'executed', 'passed' and 'failed' despite having many more listed such as 'warning', 'aborted', 'inprogress', 'timeout' etc.

Not sure if this is intended or not and if it is why are the outcomes listed there? 

I would either expect all listed outcomes to potentially be counted, or the ones that aren't not to be listed at all.

In TestRunSummary.cs these other outcomes are explicitly set to 0 in the constructor:
![image](https://user-images.githubusercontent.com/8067185/55483055-b6a7c780-561d-11e9-8823-dc0e5e91d3e8.png)

Here is a snippet of the ResultsSummary node count:
![image](https://user-images.githubusercontent.com/8067185/55483307-3766c380-561e-11e9-9a44-e4bc3e5f2d61.png)

Thanks in advance for any enlightenment on this!

**Comment by mayankbansal018** [comment]
@WillR27 the summary will only contain whether a test passed or failed, even if the test was inprogress it will eventually complete, & can either fail, or pass, or get aborted, which again is treated as failed.

Hence the summary only contains total, executed, passed, & failed

**Comment by WillR27** [comment]
@mayankbansal018 That's understandable. I suppose a follow up question would be why are these other outcomes listed if they aren't counted?

**Comment by mayankbansal018** [comment]
The other outcomes are basically when the tests are being run, the way trx is generated is as an extensible logger, & when we get the results back for tests, it keeps on logging what is the state for a given test, now since a test is not completed, an intermediate state could be `inProgress`
