### ISSUE TITLE
isConsoleLoggerEnabled is always false.

### ISSUE THREAD

**Issue by Mpdreamz** [Microsoft/vstest#1975]
Browsing the code base noticed this:

https://github.com/Microsoft/vstest/blob/46cb498d95f0bea86bb5ac9cb1a38364366748be/src/Microsoft.TestPlatform.Build/Tasks/VSTestTask.cs#L207-L214

Should that not be the reverse e.g setting it to `true`? This is the only write usage so that leads me to believe `isConsoleLoggerEnabled` can never be `true`

**Comment by ShreyasRmsft** [comment]
https://github.com/Microsoft/vstest/blob/46cb498d95f0bea86bb5ac9cb1a38364366748be/src/Microsoft.TestPlatform.Build/Tasks/VSTestTask.cs#L168

Is console logger is set to true by default. The cmdline switch is to disable if required.

**Comment by mayankbansal018** [comment]
@Mpdreamz , the use of this variable is only to check whether the verbosity of console logger is to be overridden or not.

I agree the name is misleading, but what it is actually doing is checking if user has explicitly specified  verbosity `-v` on dotnet exe, & has also specified `logger:console`, then ignore the verbosity level in `-v`, & use whatever verbosity is specified for "`console`" logger.

However if `console:logger` is not specified, & `-v` is, then enable console logger, & set verbosity as defined in arg `-v`

**Comment by mayankbansal018** [comment]
I'll fix the naming.
