### ISSUE TITLE
Need to accurately communicate errors

### ISSUE THREAD

**Issue by EzrealJ** [Microsoft/vstest#1977]
Hello there
My English is not very good. The following text was obtained by the translation software.I hope that grammatical errors are not minded
After the official release of Visual Studio 2019, I installed it for the first time and coexisted with Visual Studio 2017; this caused me to have some problems when using the unit test project.
My test project refers to Microsoft.NET.Test.Sdk 15.9.1; when I install VS2019, the project can't run. After careful checking, I confirm that it is my Microsoft.NET.Test.Sdk version. I upgraded it to Microsoft. The behavior of the project after NET.Test.Sdk 16.0.1 is normal.
What I want to express is that when my SDK version is incorrect, the CLI should pass the correct information to me, making it clear that my SDK version is a problem, rather than giving me a confusing answer after waiting for 90s. As shown
![image](https://user-images.githubusercontent.com/28976837/55578497-a9d3c280-5748-11e9-86ef-f71f03239a39.png)

**Comment by mayankbansal018** [comment]
@EzrealJ Thanks for sharing this. I tried your scenario where in VS2019 I used 15.9.0 Test SDK, & was able to run the tests successfully.

Can you please try this scenario(`running tests using 15.9.0 Test SDK` from CLI(developer cmd prompt), & also enable diagnostics logs via --diag:<path_to_log>, & share those with us?

**Comment by EzrealJ** [comment]
[log@15.9.1.txt](https://github.com/Microsoft/vstest/files/3048353/log%4015.9.1.txt)
This is my log file

**Comment by mayankbansal018** [comment]
@EzrealJ there must be two log files, one having ".host" in it's path, can you please share that as well?

**Comment by EzrealJ** [comment]
[log.txt](https://github.com/Microsoft/vstest/files/3048550/log.txt)
[log.host.19-04-05_23-12-09_51783_6.txt](https://github.com/Microsoft/vstest/files/3048551/log.host.19-04-05_23-12-09_51783_6.txt)
Sorry to keep you waiting, I regenerated the logs.

**Comment by mayankbansal018** [comment]
from the logs the communication between the vstest & teshost process did not happen, however there is not sufficient info in logs to debug this.

Can you please run dotnet publish on your sample test project, & share the publish folder with us, we might be able to figure it out locally.

**Comment by EzrealJ** [comment]
ok ，I run “dotnet publish .\Ezreal.ShouQianBa.ApiClient.Test.csproj”, and package "publish"
[publish.zip](https://github.com/Microsoft/vstest/files/3048643/publish.zip)
Source code at
https://github.com/EzrealJ/ShouQianBa
If needed

**Comment by mayankbansal018** [comment]
Thanks for sharing above, I was able to successfully run the project you shared in publish folder.

The current issue that you faced, where vstest.console was unable to communicate with testhost.exe could be machine specific. Can you please try following.

- On your latest VS2019, please create an empty UT project, & manually set version of .NET.Test.SDK to 15.9.0, & see if that runs or not

- Can you try running your original project on some another Machine? & let us know if it successfully passes there or not.

**Comment by EzrealJ** [comment]
Ok, I am sure it is a problem with my computer. I asked my friend to repeat my steps. It is working on his computer. I recorded my screen and showed you what I encountered. One day someone else encountered the same problem as me and found out the reason. I hope you can tell me where the problem lies.
![录制_2019_04_08_23_46_53_453](https://user-images.githubusercontent.com/28976837/55738841-7fd91380-5a5a-11e9-967d-d272fc20ea85.gif)

**Comment by mayankbansal018** [comment]
@EzrealJ from this it is not clear why the communication would fail on your machine, when we have made no changes in the way we establish IPC between vstest.console, & testhost process.

**Comment by EzrealJ** [comment]
Thank you very much for taking the time to check the problem for me. I will evade this problem by upgrading sdk in order to continue using the test project.
Thanks again

**Comment by mayankbansal018** [comment]
Thanks for reporting this, apologies we could not get to the root of the issue.
