### ISSUE TITLE
testhost.x86 is not large address aware

### ISSUE THREAD

**Issue by sharwell** [Microsoft/vstest#1985]
Currently testhost.x86 is compiled with platform set to x86:

https://github.com/Microsoft/vstest/blob/53c0a341b07c1f224a31b2378e696f535a1f6080/src/testhost.x86/testhost.x86.csproj#L12

This compilation setting causes the application to omit the large address aware setting, which causes problems on larger multi-core machines (I'm observing frequent OOM errors on 2990WX).

The correct setting for an x86 build which is large address aware is a combination of the AnyCPU platform and the Prefer32Bit setting. See Microsoft/perfview@1582d04aefd7869a1ea6e1530c49ed2e6a1c5939 for an example of this configuration.

**Comment by AbhitejJohn** [comment]
@sharwell : Just trying to understand the affect of moving to LAA, how would this affect low config systems?

**Comment by ivonin** [comment]
From what I read, setting the performance hit from setting the /LAA flag exists although it's not too big.

Can't find anything more thourough than [this StackOverflow post](https://stackoverflow.com/a/26001862/501518) at the moment. @sharwell what's your take on this?

**Comment by sharwell** [comment]
I've never heard of there being a difference. I can't benchmark the difference in a meaninful way because the current release just crashes.
