### ISSUE TITLE
Execution target framework guidelines

### ISSUE THREAD

**Issue by verbal-defense** [Microsoft/vstest#1988]
I was wondering about targetted frameworks used for execution of tests.

On [docs.microsoft.com](https://docs.microsoft.com/en-us/visualstudio/test/vstest-console-options?view=vs-2019) documentation page, it is mentioned that "Valid values are Framework35, Framework40, Framework45, and FrameworkUap10." 

From code, however, I see that whatever is accepted in [FrameworkName's constructor](https://docs.microsoft.com/en-us/dotnet/api/system.runtime.versioning.frameworkname.-ctor?view=netframework-4.7.2#System_Runtime_Versioning_FrameworkName__ctor_System_String_) can be used.

I was therefore wondering about the following: should the documentation be updated to not be restrictive about the valid values?

Related question is: under what circumstances is it a good idea to run tests against a dll that targets 4.5 with /Framework:".NETFramework,Version=v4.5.2" and Framework:".NETFramework,Version=v4.7.2"  at the same time? My understanding is that this brings only very limited benefits as the runtime should behave the same 99.99%  of time.

**Comment by mayankbansal018** [comment]
>Related question is: under what circumstances is it a good idea to run tests against a dll that targets 4.5 with /Framework:".NETFramework,Version=v4.5.2" and Framework:".NETFramework,Version=v4.7.2" at the same time? My understanding is that this brings only very limited benefits as the runtime should behave the same 99.99% of time. 

Yes, you are correct, if the user is aware of the actual framework of the dll(452 vs 472) we recommend to use actual framework, though the platform itself doesn't bring in any additional benefits for either.

**Comment by mayankbansal018** [comment]
Moved to backlog to correct docs.
