### ISSUE TITLE
Trx Missing TestDefinitions

### ISSUE THREAD

**Issue by cheng93** [Microsoft/vstest#1989]
From #1979 

https://circleci.com/gh/cheng93/TripleTriad/29#tests/containers/0
trx https://gist.github.com/cheng93/d0749cac168a0ce92491a09c09b1fb3b
```
Im getting something similar on my CI build.

Trx shows ~75 test out of 329. Console output shows all test being run
Just focusing on the `Requests` project

Funny enough, running the command locally works perfectly
```
```
I was just focusing on step 7. The unit tests on `Requests`. Although the issue is also there in step 6.

You are right that the trx does show all the tests in the `Results` and `TestEntry` section, however in `TestDefinition` section, a lot is missing. 

Total lines of the file should be around ~1600
```

Diagnostic file https://gist.github.com/cheng93/cea3878115860b8e85f6b0883ac1203e

**Comment by cheng93** [comment]
Will try and produce small issue.

Can someone tag it with `bug` and `needs-repro`

**Comment by cheng93** [comment]
You'll need docker to reproduce.

1. Pull the docker image
```
docker pull mcr.microsoft.com/dotnet/core/sdk:2.2
```

2. Run the image in interactive mode (and mount a volume for easy access to logs)
```
docker run -v /tmp/TripleTriad:/tmp -it mcr.microsoft.com/dotnet/core/sdk:2.2 /bin/bash
```

3. Now inside the container, clone my repository
```
cd /tmp
git checkout https://github.com/cheng93/TripleTriad.git
cd TripleTriad
```

4. Run the following commands
```
dotnet restore
dotnet test ./tests/TripleTriad.Requests.Tests/TripleTriad.Requests.Tests.csproj --no-build --no-restore -c Release -v d --logger trx -r ./../../TestResults --diag:../../TestResults/log.txt --filter FullyQualifiedName=TripleTriad.Requests.Tests.GameTests.GameMoveTests.ValidatorTests.Bad_request_should_throw
```

5. On the host, you should be able to view the trx and logs in `/tmp/TripleTriad/TripleTriad/TestResults`

Here are my outputs

[_9e642c4ec876_2019-04-14_11_59_25_706.trx.txt](https://github.com/Microsoft/vstest/files/3077321/_9e642c4ec876_2019-04-14_11_59_25_706.trx.txt)
[log.host.19-04-14_11-59-23_70007_5.txt](https://github.com/Microsoft/vstest/files/3077322/log.host.19-04-14_11-59-23_70007_5.txt)

**Comment by mayankbansal018** [comment]
@cheng93 Thanks for the repro, I could see this, & the reason you are facing lesser number of entries under `TestDefinitions` section, is because of data driven tests, & how the identities are assigned to them.

Each test be it data driven or not, is uniquely marked under `Results` section, where they are assigned unique identity, however since data driven tests have same same meta data associated with them, we do not repeat that under `TestDefinitions`, as that would just be a waste of space. 

Could you please explain that if you are finding test missing under `Results` section, because that would be a bug.

**Comment by mayankbansal018** [comment]
Closing this, as this is by-design, please comment here to let me know if there are any concerns.

**Comment by cheng93** [comment]
@mayankbansal018 

I just noticed the classname inside TestDefinition's TestMethod is wrong. (line 161 in my reproduction)

It is `TripleTriad.Requests.Tests` instead of `TripleTriad.Requests.Tests.GameTests.GameMoveTests.ValidatorTests`
