### ISSUE TITLE
Trx TestDefinition classname

### ISSUE THREAD

**Issue by cheng93** [microsoft/vstest#1992]
## Description
> **IMPORTANT**: if the defect is reproduced only in a workflow from within the Visual Studio IDE then do not report the issue here - instead, please report it using Visual Studio's "Send Feedback" option that can be accessed from the Help menu OR using this link https://developercommunity.visualstudio.com.
>
> For a defect reproducable from the vstest command line, describe the issue you've observed.

The classname under test definition is wrong.

For example

```

    <UnitTest name="XunitTrx.FactTests.Test" storage="/home/xunittrx/xunittrx/bin/debug/netcoreapp2.2/xunittrx.dll" id="add8c0e4-fdbc-6929-f132-2c65282e85bb">
      <Execution id="cb57a616-fd2e-49c7-9da1-00f6109a1849" />
      <TestMethod codeBase="/home/XunitTrx/XunitTrx/bin/Debug/netcoreapp2.2/XunitTrx.dll" adapterTypeName="executor://xunit/VsTestRunner2/netcoreapp" className="XunitTrx" name="XunitTrx.FactTests.Test" />
    </UnitTest>
```

the classname is `XunitTrx` which is **wrong**

## Steps to reproduce
> What steps can reproduce the defect?

Instructions are here https://github.com/cheng93/XunitTrx

Example output is in the `TestResults` folder

> Please share the setup, commandline for vstest.console, sample project, target
> framework etc.

|docker tag|vstest|
|-|-|
|2.2|16.0.1|
|2.2.105|15.9.0|

## Expected behavior
> Share the expected output

```
    <UnitTest name="XunitTrx.FactTests.Test" storage="/home/xunittrx/xunittrx/bin/debug/netcoreapp2.2/xunittrx.dll" id="add8c0e4-fdbc-6929-f132-2c65282e85bb">
      <Execution id="cb57a616-fd2e-49c7-9da1-00f6109a1849" />
      <TestMethod codeBase="/home/XunitTrx/XunitTrx/bin/Debug/netcoreapp2.2/XunitTrx.dll" adapterTypeName="executor://xunit/VsTestRunner2/netcoreapp" className="XunitTrx.FactTests" name="XunitTrx.FactTests.Test" />
    </UnitTest>
```

the classname should be `XunitTrx.FactTests`

## Actual behavior
> What is the behavior observed?

See in **Description**

## Diagnostic logs
> Please share test platform diagnostics logs. Instructions to collect logs are [here](https://github.com/Microsoft/vstest-docs/blob/master/docs/diagnose.md#test-platform-diagnostics).  
> The logs may contain test assembly paths, kindly review and mask those before sharing.

See repository, logs are in `TestResults` folder

## Environment
> Please share additional details about the test environment.
> Operating system, Build version of vstest.console

See **Steps to reproduce**

----------------------------

Important!

It works correctly when I run it locally on my machine.

```
.NET Core SDK (reflecting any global.json):
 Version:   2.2.105
 Commit:    7cecb35b92

Runtime Environment:
 OS Name:     arch
 OS Version:  
 OS Platform: Linux
 RID:         arch-x64
 Base Path:   /opt/dotnet/sdk/2.2.105/

Host (useful for support):
  Version: 2.2.3
  Commit:  6b8ad509b6

.NET Core SDKs installed:
  2.2.105 [/opt/dotnet/sdk]

.NET Core runtimes installed:
  Microsoft.NETCore.App 2.2.3 [/opt/dotnet/shared/Microsoft.NETCore.App]
```

vstest version `15.9.0-preview-20180807-05`

**Comment by mayankbansal018** [comment]
@cheng93 can you share the different trx files generated when run locally, v/s when you are getting the error?

**Comment by cheng93** [comment]
@mayankbansal018  pushed to repo

**Comment by singhsarab** [comment]
@cheng93 Thanks for feedback. The fix will be available in the next preview release.
