### ISSUE TITLE
Dup of https://github.com/Microsoft/vstest/issues/627, fix is available in VS15.3.0 preview2. You can use `blame` option to narrow down the stackoverflow exception to particular test case.

### ISSUE THREAD

**Issue by Rod-in-NM** [Microsoft/vstest#2001]
In the reply that smadala made on June 21, 2017, he recommended the original poster, "... use the `blame` option to narrow down the stackoverflow exception to a particular test case". 
I would love to do that, but don't know what the `blame` is or means. What is it, please?

Dup of https://github.com/Microsoft/vstest/issues/627, fix is available in VS15.3.0 preview2. You can use `blame` option to narrow down the stackoverflow exception to particular test case.

_Originally posted by @smadala in https://github.com/Microsoft/vstest/issues/527#issuecomment-310281977_

**Comment by Rod-in-NM** [comment]
I've got an answer to my question on this [VSTest.Console.exe page](https://docs.microsoft.com/en-us/visualstudio/test/vstest-console-options?view=vs-2019).

**Comment by paul-cheung** [comment]
@Rod-in-NM using `blame `option help to solve my issue, thumbup~~~
