### ISSUE TITLE
Run scripts before or after tests are run from within visual studio

### ISSUE THREAD

**Issue by ftaran** [microsoft/vstest#2010]
is it possible to run scripts before or after tests are being run from within visual studio, either using runsettings file or another approach?

I need to generate a text summary report each time the tests are run locally by devs, but for this I first need to generate the XML report and then use another tool to turn that XML report to a text summary.

we want to include this report at the top of each pull request.

**Comment by singhsarab** [comment]
It is not very clear as to how you running these tests and what is the intent here?
If I understand correctly, you need some report for each pull request.

Why do you want to run and generate this report for every run in Visual Studio?
How are you running these tests? 
Have you considered using pipeline tasks ? 

If at all you want to generate a specific report, you can run your script after you invoke test task or script you have. But that said, given the VSTest task and publish test task provide the mechanism to achieve that I would encourage you to use them.

**Comment by jayaranigarg** [comment]
Closing the issue from our end because of no response. Let us know if you are still blocked on this!
