### ISSUE TITLE
Dependency resolution issues within net framework unit tetst class

### ISSUE THREAD

**Issue by jeffschwMSFT** [microsoft/vstest#2011]
from @maximburyak https://github.com/dotnet/coreclr/issues/20606

This issue replicates when referencing nuget package with embedded kestrel dlls from unit test class library, that also references aspnetcore.
Please take a look into this repro repository: https://github.com/maximburyak/EmbeddedProjectsReferenceIssue
I'm not sure if it's a coreclr issue or mstest issue, probably something in between, because for some reason, only when using tests infrastructure, the embedded dlls from the package, that should have been addressed like any other "resource" are used in the build process, and on the other hand, coreclr is not able to choose one "right" version for all packages and is not able to build correctly, but does not fail, instead, it issues the warning:
warning MSB3277: Found conflicts between different versions of "System.Memory" that could not be resolved. These reference conflicts are listed in the build log when log verbosity is set to detailed
And when running using mstest infrastructure to run the test using dotnet test (or when running the test from visual studio) the next message received:
The given assembly name or codebase was invalid. (Exception from HRESULT: 0x80131047) No test is available in

**Comment by singhsarab** [comment]
@maximburyak Can you please give some repro steps for this issue?

@jeffschwMSFT Why do we think the issue is with test platform?

**Comment by jeffschwMSFT** [comment]
> @dsplaisted This looks to me like an issue in https://github.com/microsoft/vstest, or if not then the test infrastructure would need to be involved in getting more details about why exactly this is failing.

This issue was in an a different repro and moved based on Daniel's analysis.

**Comment by jayaranigarg** [comment]
Closing the issue due to no response. Let us know if you are still blocked on this!
