### ISSUE TITLE
dotnet test without shared runtime

### ISSUE THREAD

**Issue by livarcocc** [microsoft/vstest#2013]
_From @Rast1234 on Tuesday, 23 April 2019 12:06:14_

Currently we run our apps with heavily customized corporate docker image. We publish self-contained apps, because we deemed it too time consuming and potentially problematic to get shared runtime to run in there.
So basically we do this (extra stuff omitted) in microsoft's SDK image:
```dockerfile
RUN dotnet restore "Foo.csproj" --runtime linux-x64
RUN dotnet build "Foo.csproj" --runtime linux-x64 --no-restore 
RUN dotnet publish "Foo.csproj" --runtime linux-x64 --no-restore --self-contained
```
Then we copy results to our image and just run the binary.

Is it possible to publish and run tests the same way? I am aware that test project is not executable by itself and requires a test runner. Test runner relies on shared runtime AFAIK. Can we get a self-contained test runner somehow? Or integrate it into test project maybe?

_Copied from original issue: dotnet/sdk#3170_

**Comment by karanjitsingh** [comment]
@Rast1234 you can take a reference on Microsoft.TestPlatform itself https://www.nuget.org/packages/Microsoft.TestPlatform/16.0.2-preview-20190502-01

![image](https://user-images.githubusercontent.com/4632805/57435290-9e4d4d00-725a-11e9-8a54-945da1346692.png)

**Comment by karanjitsingh** [comment]
Locking this conversation, if you want to get back to us on this, please open a new issue.
