### ISSUE TITLE
Intellitrace with runsettings

### ISSUE THREAD

**Issue by JakubJaworskiPL** [microsoft/vstest#2018]
Hi All,

Is it possible to turn on IntelliTrace for test run using .runsettings?
I can see it is available for .testsettings but cannot find any guidance for .runsettings.

Thanks
JJ

**Comment by jayaranigarg** [comment]
@JakubJaworskiPL : Can you please explain your scenario as to what are you trying to achieve? 
It would help if you can share with us a simple repro project along with sample testsettings file that is working for you?

**Comment by jayaranigarg** [comment]
Closing the issue from our end due to no response. Please feel free to open a new issue with the above details to help us investigate.
