### ISSUE TITLE
Update System.Net.Http from System.Net.Http@4.3.0 to 4.3.2 to avoid DoS, SFB, PE and Spoofing issues.

### ISSUE THREAD

**Issue by SeppPenner** [microsoft/vstest#2031]
## Description
Update the `System.Net.Http` from version 4.3.0 to 4.3.2 to avoid `Security Feature Bypass`, `Denial of Service`, `Elevation of Privilege` and `Spoofing` issues introduced with the prior version. Check https://github.com/aspnet/Announcements/issues/239 and https://app.snyk.io/vuln/SNYK-DOTNET-SYSTEMNETHTTP-60045.

I recently saw this issue using the snyk application on my Github account.

Example:

![grafik](https://user-images.githubusercontent.com/9639361/58503504-0a9bdc00-8189-11e9-87bc-834651675984.png)

**Comment by cltshivash** [comment]
@SeppPenner We target the lower versions of NetStandard to support a wider customer segment. Also we don't directly reference the impacted dll rather pick what is present with the installed framework.

**Comment by cltshivash** [comment]
We will look at the steps detailed at https://github.com/aspnet/Announcements/issues/239

**Comment by SeppPenner** [comment]
@cltshivash Thank you for the information.

**Comment by cltshivash** [comment]
System.Net.Http is not used in any of the TestPlatform flows and hence we won't be taking up the changes recommended for transitive dependency.

**Comment by cltshivash** [comment]
We do have plans to move the TP to target netstandard 2.0 soon which should address this.
