### ISSUE TITLE
Option to suppress stdout output to trx file

### ISSUE THREAD

**Issue by Jonathan-Walsh** [microsoft/vstest#2032]
## Description
I'm using VSTest throught the build task on Azure DevOps. We are logging to a .trx file and would like to retrieve that file once the build has completed. Unfortunately, the .trx file is too large to be uploaded (>75MB). It looks like if we suppress the stdout logging to the .trx, we could reduce the size of this file by 10x.

## Steps to reproduce
See this attached VSTest task log for the exact settings/configuration. The warning about the .trx file being too large is at the end as well: [vstest-task-log.txt](https://github.com/microsoft/vstest/files/3234666/vstest-task-log.txt)

## Environment
Using V2 of the VSTest task, see the file above for the actual configuration of VSTest

**Comment by jayaranigarg** [comment]
@Jonathan-Walsh : As of now, there is no way to suppress stdout logging to trx file.

**Comment by Jonathan-Walsh** [comment]
Is there some sort of CLI option that could be enabled for the logger to suppress this logging, or set logging to .trx to something like the "minimal" option for console?

**Comment by jayaranigarg** [comment]
Unfortunately, as of now there is no option to minimize logging to .trx files

**Comment by cltshivash** [comment]
@Jonathan-Walsh : The trx logger is part of this repo and enhancements to it are welcome.
