### ISSUE TITLE
Where are the project templates for C++ and UWP?

### ISSUE THREAD

**Issue by ChrisGuzak** [microsoft/vstest#2033]
I'd like to update the contents of the C++ project generated by the Visual Studio project templates (screen shot below). I was hoping to find them in this repo but they don't see to be here.

Specifically I'd like to
- Remove unnecessary artifacts from the test code generated by the template
- Create a C++ WinRT template so we don't need to use C++ CX

I found \test\TestAssets\CPPSimpleTestProject\CPPSimpleProj\CPPSimpleProj.vcxproj but this does not seem to be a template.

Where is the source for these templates?

![image](https://user-images.githubusercontent.com/2507280/58609759-a434bd80-825d-11e9-81af-5e5c61dc89ce.png)

**Comment by cltshivash** [comment]
@ChrisGuzak These aren't present in the repo and following up over email with you.
