### ISSUE TITLE
Multiple vstest.console processes being started in translation layer

### ISSUE THREAD

**Issue by vagisha-nidhi** [microsoft/vstest#2034]
## Description
vstest.console is started 2 times for each run in reference to this
[https://github.com/microsoft/vstest/blob/master/src/Microsoft.TestPlatform.VsTestConsole.TranslationLayer/VsTestConsoleProcessManager.cs#L123](https://github.com/microsoft/vstest/blob/master/src/Microsoft.TestPlatform.VsTestConsole.TranslationLayer/VsTestConsoleProcessManager.cs#L123)

Attaching process tree image
![image](https://user-images.githubusercontent.com/13175100/58620732-72673980-82e5-11e9-8a6f-261d622358c4.png)

**Comment by vagisha-nidhi** [comment]
Fixed in #2035

**Comment by Mobrockers** [comment]
Oops sorry 🙈
