### ISSUE TITLE
Compressed test results

### ISSUE THREAD

**Issue by adamralph** [microsoft/vstest#2040]
## Description

The test results output in the command line spans several lines and considerably bloats the line count, especially when multiple test runs form part of a single build.

## Steps to reproduce

Run any test project from the command line.

## Expected behavior

Something like:

```
Test run successful. Total tests: 63 (passed: 63, failed: 0, skipped: 0). Total time: 1.6310 seconds.
```

## Actual behavior

```
Test Run Successful.
Total tests: 63
     Passed: 63
 Total time: 1.6310 Seconds
```

## Environment

Windows 10, dotnet 2.2.300.

**Comment by ShreyasRmsft** [comment]
@adamralph we arrived with this format after much thought and it is a lot more readable than the compressed form.

However the vstestplatform is extremely extensible and you have the option to extend the existing logger and create a custom version of it that you use for your test runs.

https://blogs.msdn.microsoft.com/vikramagrawal/2012/07/26/writing-loggers-for-command-line-test-runner-vstest-console-exe/

Existing console logger that you can use as a base:
https://github.com/microsoft/vstest/blob/master/src/vstest.console/Internal/ConsoleLogger.cs

**Comment by adamralph** [comment]
@ShreyasRmsft how was this decision made? Was it discussed publicly?

I see that this is a recent thing, since older versions of the SDK have a more compact output.

**Comment by ShreyasRmsft** [comment]
@cltshivash @singhsarab to give reasoning behind the change.

**Comment by singhsarab** [comment]
@adamralph Here is the link to the issue https://github.com/microsoft/vstest/issues/1836
