### ISSUE TITLE
Couldn't locate Sequence.xml 

### ISSUE THREAD

**Issue by silentnightwalk** [microsoft/vstest#2042]
## Description
I cannot find expected Sequence.xml file after running dotnet vstest with /Blame option.
Where is it located?

## Steps to reproduce
The command ""C:\Program Files\dotnet\dotnet.exe" vstest  /Diag:"...........................Tests\bin\Release\diag.txt" "...........................Tests\bin\Release\...........................Tests.dll" /Blame /logger:trx;LogFileName="...........................Tests\bin\Release\TestOutput.trx" /Settings:"...........................Tests\bin\Release\...........................Tests.v461.runsettings"" exited with code 1.

**Comment by singhsarab** [comment]
@silentnightwalk The path to the sequence file is published on the console itself.
Can you please share the snapshot of the run ? What is the error that you get ?

**Comment by silentnightwalk** [comment]
Actually, the sequence itself is in the output (in the BuildLog which is most probably same as console). 
I tried to serch for Sequence.xml, but could not find it. 
Could you please hint the search words to use?

**Comment by ShreyasRmsft** [comment]
@silentnightwalk you will get the sequence xml only when the test run gets aborted.

![image](https://user-images.githubusercontent.com/25194518/59010448-f160f280-884e-11e9-847f-51e562e4b9bd.png)

**Comment by ShreyasRmsft** [comment]
Look for logs similar to above. But only on an aborted test run will it be created. Closing the issue. Please re-open if you are still unable to find it with the above information.
