### ISSUE TITLE
TfsPublishing - CustomLogger - Where and how is it supposed to publish info?

### ISSUE THREAD

**Issue by silentnightwalk** [microsoft/vstest#2049]
## Description
Where and how is it supposed to publish test results to when saying "tfs publishing"?

After looking at this issue
https://github.com/microsoft/vstest/issues/1739
it seems that TfsLogger is not supported anymore.

I'm trying to do a custom TFSLogger.
I can find general instructions of how to do custom loggers.
But where and how to send info from the logger?

A little bit more about ht e question:
- we have "Builds" tab in TFS (Team Explorer) in Visual Studio
- Build Summary opens when i double-click certain build in "My Builds" 
- so, the question is how to reach this build summary and write info there?
- or (if the build summary is only top of the iceberg) where and how is it supposed to publish test results to when saying "tfs publishing"?
- at the moment the only thing i would like to write there is the link to .trx file (and the pass rate) like following:
 
1 test run completed - 100% pass rate
 T (2019-02-10 15:27:03), 120 of 120 test(s) passed

- but in the future it could be more info.
Thanks!

## Environment
Latest

**Comment by ShreyasRmsft** [comment]
@silentnightwalk take a look at the TFS rest api docs.

https://docs.microsoft.com/en-us/rest/api/azure/devops/test/runs/create?view=azure-devops-rest-5.0

Make sure you select the appropriate version of the apis depending on your tfs version. You will basically need to create a test run. Add test results to it and then mark the test run as complete.
