### ISSUE TITLE
Source-build patch removal for VSTest

### ISSUE THREAD

**Issue by crummel** [microsoft/vstest#2050]
Source-build has some patches that we are currently applying to your repo.  This issue tracks removing the patches.  These patches can be found at https://github.com/dotnet/source-build/tree/release/3.0/patches/vstest.

Patches that have the responsibility "Repo" and the Disposition "Incorporate" are patches that we believe are valid source-build fixes that should be moved into your repo.  Please let us know if these don't seem like good patches.  Any changes with the responsibility "source-build" is something that we plan to keep going forward or integrate in another way - please also let us know if you think there may be problems with those patches.

Patch name | Type | Disposition | Responsibility | Notes
-- | -- | -- | -- | --
vstest/0001-Conditionally-remove-uap-from-TargetFramework-and-co.patch | Build | Incorporate | Repo | Believe Dan S might have a PR out for this   already
vstest/0002-Remove-unneccessary-projects-from-sln.patch | ProjRemoval | Incorporate | Repo |

**Comment by singhsarab** [comment]
@crummel 
https://github.com/microsoft/vstest/blob/master/TestPlatform_BuildFromSource.sln does not suffice here ?

**Comment by crummel** [comment]
That should take care of it, I'll make a PR if it doesn't.  Thanks!
