### ISSUE TITLE
How to control COM threading model during test execution?

### ISSUE THREAD

**Issue by aeulitz** [microsoft/vstest#2053]
Is there documentation describing if/how I can control the COM threading model (e.g. STA, MTA) while running C++ tests (https://docs.microsoft.com/en-us/visualstudio/test/how-to-use-microsoft-test-framework-for-cpp?view=vs-2019)?

Ideally, I'd want to use a test class or test method attribute to document the threading requirements in code (rather than a setting in a project file, let's say).

**Comment by cltshivash** [comment]
@aeulitz There isn't an option to control the threading model. The C++ tests run in STA today (  Microsoft.VisualStudio.TestTools.CppUnitTestFramework.Executor.dll.manifest). For any other option, will need the user to explicit set it in a separate thread and execute the required code in it.
