### ISSUE TITLE
 SatelliteResourceLanguages property doesn't filter all resources when publishing test projects

### ISSUE THREAD

**Issue by nguerrera** [microsoft/vstest#2057]
*Moved from https://github.com/dotnet/sdk/issues/3338 on behalf of @lzganec*

Having a dependency to Microsoft.CodeCoverage (which comes from Microsoft.NET.Test.Sdk) leaves Microsoft.VisualStudio.TraceDataCollector.resources.dll localized resource satellite assembly in the publish output using .NET Core version 2.2.

**Comment by nguerrera** [comment]
The issue is that the package is doing manual copies of these files in a custom target rather than supplying them as assets that publish can reason about:

https://github.com/microsoft/vstest/blob/64a4c978822a25e88c119c8da42b543fa9ac5a96/src/package/nuspec/Microsoft.CodeCoverage.targets#L17-L25

**Comment by MarcoRossignoli** [comment]
@jakubch1 is this one still an issue?
