### ISSUE TITLE
VSTest should publish artifacts to BAR

### ISSUE THREAD

**Issue by crummel** [microsoft/vstest#2063]
VSTest is included in the dotnet/toolset project, but VSTest doesn't publish to BAR so updates have to inserted manually.  You can enable BAR publishing without switching to Arcade using something like [this template](https://github.com/dotnet/arcade/blob/master/eng/common/templates/job/publish-build-assets.yml).  You can see an example of this being used in [source-build-reference-packages](https://github.com/dotnet/source-build-reference-packages/blob/4e7772de3c69be0945a1b4ed2a6ebd3ec4073493/azure-pipelines/builds/ci.yml#L8), and example of the build it produces [here](https://dev.azure.com/dnceng/internal/_build/results?buildId=234210).

Let me know if you have any questions or need help with this.

**Comment by singhsarab** [comment]
This is done. Related to #1941
