### ISSUE TITLE
Problem when rerunning tests Hosted VS2017

### ISSUE THREAD

**Issue by mxavierciandt** [microsoft/vstest#2064]
## Issue Description
I've enabled the option "Rerun failed tests", after my test have runned there was one test that has failed. When the test tryed to rerun occurs some erros:

### Question, Bug, or Feature?
Type: Bug

Enter Task Name: Visual Studio Runner

![image](https://user-images.githubusercontent.com/51972378/59718168-ed8a8400-91ef-11e9-9864-0b4f5e66c3bd.png)

## Environment
Server - Azure Pipelines

## Error logs
Log Snippet

`##[error]The test source file "C:\Users\VssAdministrator\AppData\Local\Temp\Delete" provided was not found.`

## Additional Data

My pipeline configuration
![image](https://user-images.githubusercontent.com/51972378/59719935-f67d5480-91f3-11e9-9059-eb75d9752181.png)

Visual Studio Test Runner configuration
![image](https://user-images.githubusercontent.com/51972378/59719977-11e85f80-91f4-11e9-914a-5bfea31503fd.png)

**Comment by kaadhina** [comment]
Hi can you please collect the complete debug logs (system.debug = true) and share them?

**Comment by kaadhina** [comment]
Closing this now. Please reopen or create new issue if u still face a problem.
