### ISSUE TITLE
Test run sessions should show TFM when multiple frameworks

### ISSUE THREAD

**Issue by clairernovotny** [microsoft/vstest#2070]
When multiple frameworks are being tested (with multi targeting), the test run session names are all the same: "VS Test Run session for ...". It's nearly impossible to see which platform the results are for.

In the case of multi-targeting, please add the TFM to the test result session name.

**Comment by mayankbansal018** [comment]
@onovotny can you please share an expected outcome, it would help us close on user experience 

/cc @singhsarab

**Comment by onovotny** [comment]
I would like to see the TFM added into the session name:

Here's what I see currently. I think adding net461/netcoreapp2.1, etc would help a lot.
![image](https://user-images.githubusercontent.com/1427284/60435043-8fd63e80-9bd6-11e9-8344-a39d5c0c125b.png)

**Comment by nohwnd** [comment]
The framework is still not output, we should amend the trx to do it.
