### ISSUE TITLE
dotnetcore filter parameter not working with xunit running on dotnetcoreapp3.0 

### ISSUE THREAD

**Issue by livarcocc** [microsoft/vstest#2072]
_From @vpaulino on Monday, June 24, 2019 7:20:43 PM_

On cake scripts Until recently i used --filter Category=unit on dotnetcoretests to filter my unit tests and execute them with Xunit2 tools.

But now to support code coverage with coverlet I had to change to  something like this: 

  ```
var dotNetTestSettings = new DotNetCoreTestSettings
			{            
				Configuration = configuration,
				DiagnosticOutput = true,
				Verbosity = DotNetCoreVerbosity.Normal,
				NoBuild = false,
				ArgumentCustomization = (args)=>
				{
					args.Append("/p:CollectCoverage=true");
					args.Append("/p:ThresholdStat=total");
					args.Append("/p:Exclude=\"[xunit.*]*\"");
					args.Append("--no-build");
					args.Append($"--logger \"trx;LogFileName={projectName}-TestsResults.trx\"");
				    args.Append("--filter \"TestCategory=Unit|Category=Unit\"");

					 
					return args;
				} 
			};
```
and my coverlet settings goes like this: 
```

var coverletSettings = new CoverletSettings {
				CollectCoverage = true,
				CoverletOutputFormat = CoverletOutputFormat.cobertura,
				CoverletOutputDirectory = Directory($"{outputDir}/Reports"),
				CoverletOutputName = $"CoverageResults",
				Threshold = 0,
			 	ThresholdType = ThresholdType.Method | ThresholdType.Line | ThresholdType.Branch 
			};

			DotNetCoreTest(file.FullPath, dotNetTestSettings, coverletSettings);


```

and I run my unit tests like this: 

	`DotNetCoreTest(file.FullPath, dotNetTestSettings, coverletSettings);`

The reason why Im here is because Im using xunit on my unit tests and my Directory.Build.Props to tests is like this:

```

<Project>

	<PropertyGroup>
		<TargetFrameworks>netcoreapp3.0</TargetFrameworks>
		<IsPackable>false</IsPackable>

		<DebugType>full</DebugType>
	</PropertyGroup>
	
	<ItemGroup>
		<PackageReference Include="coverlet.msbuild" Version="2.6.2" />
		<PackageReference Include="Microsoft.NET.Test.Sdk" Version="16.2.0-preview-20190606-02" />
		<PackageReference Include="Moq" Version="4.8.2" />
		<PackageReference Include="xunit.analyzers" Version="0.10.0" />
		<PackageReference Include="xunit" Version="2.4.1" />
	
    <PackageReference Include="xunit.runner.visualstudio" Version="2.4.1">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
        <PackageReference Include="FluentAssertions" version="4.19.4" />
		<PackageReference Include="NSubstitute" version="3.1.0" />
		 <PackageReference Include="Newtonsoft.Json" version="9.0.1" />
	</ItemGroup>
	

</Project>
```

and my unit tests are decorated with the attribute 

```
[Fact]
[Trait("Category", "Unit")]

```
the output message I receive is like this:

"No test is available projectDirectory\bin\debug\netcoreapp3.0\\*.dll  Make sure that test discoverer & executors are registered and platform & framework version settings are appropriate and try again. "

What Im I missing ?

here is a print screen showing that dotnet test --filter Category=Unit is failing:

![image](https://user-images.githubusercontent.com/859157/60046088-655c2100-96be-11e9-8eb9-0c813bc28517.png)

_Copied from original issue: dotnet/core-sdk#2617_

**Comment by livarcocc** [comment]
_From @livarcocc on Tuesday, June 25, 2019 3:32:42 PM_

I believe it would be more appropriate if you filled this issue under microsoft/vstest. Could you please move it there?

**Comment by mayankbansal018** [comment]
@vpaulino, can you please share [diagnostics logs](https://github.com/microsoft/vstest-docs/blob/master/docs/diagnose.md) for the same , also it would be helpful if you can share a repro project.

**Comment by vpaulino** [comment]
I will need some time to setup that repo because this is happening on my company CI that Im building, and the code I cannot share... as soon as possible I will share similiar use case on my github.

**Comment by kaadhina** [comment]
Will reopen when we have logs
