### ISSUE TITLE
TestPlatform ObjectModel has bad dependencies

### ISSUE THREAD

**Issue by onovotny** [microsoft/vstest#2073]
The TestPlatform ObjectModel has old/bad dependencies. It causes lots of package downgrade warnings.

![image](https://user-images.githubusercontent.com/1427284/60200341-eaa51a00-9813-11e9-91a7-304ab6eb2e29.png)

It should reference .NET Standard Library 1.6 and not the other packages. There should also be a netstandard2 target that reduces those all-together.

**Comment by mayankbansal018** [comment]
@onovotny a similar task is already picked by @vagisha-nidhi in #2067
