### ISSUE TITLE
Unit test failed only when analyzing code coverage

### ISSUE THREAD

**Issue by bidiudiu** [microsoft/vstest#2081]
## Description
Hi,
I have an UnitTest project. When Test->Run->All Tests, all tests are successful. But if Test->Analyze Code Coverage, **those tests with Process.Start()** are failed.

## Steps to reproduce
I'm using VS 2017 Enterprise with Microsoft.NET.Test.Sdk 15.8.0, MSTest.TestAdapter 1.2.1 and MSTest.TestFramework 1.2.1. My project's framework is NetCore 2.0.
## Expected behavior
Codes have been proved to be right in 'All Tests'.

## Actual behavior
But when running 'Analyze Code Coverage', here's error message from Process.StandardError:
```
    [Error] System.ArgumentException: Item has already been added. Key in dictionary: 'CODE_COVERAGE_SESSION_NAME'  Key being added: 'CODE_COVERAGE_SESSION_NAME'
    [Error]    at System.Collections.Hashtable.Insert(Object key, Object nvalue, Boolean add)
    [Error]    at System.Environment.ToHashtable(IEnumerable`1 pairs)
    [Error]    at System.Environment.GetEnvironmentVariables()
    [Error]    at System.Diagnostics.ProcessStartInfo.get_Environment()
    [Error]    at Microsoft.DotNet.Cli.Utils.ForwardingAppImplementation.GetProcessStartInfo()
    [Error]    at Microsoft.DotNet.Cli.Utils.MSBuildForwardingAppWithoutLogging.GetProcessStartInfo()
    [Error]    at Microsoft.DotNet.Tools.MSBuild.MSBuildForwardingApp.GetProcessStartInfo()
    [Error]    at Microsoft.DotNet.Tools.MSBuild.MSBuildForwardingApp.Execute()
    [Error]    at Microsoft.DotNet.Tools.Restore.RestoreCommand.Run(String[] args)
    [Error]    at Microsoft.DotNet.Cli.Program.ProcessArgs(String[] args, ITelemetry telemetryClient)
    [Error]    at Microsoft.DotNet.Cli.Program.Main(String[] args)
    [Error] 

```
What does 'CODE_COVERAGE_SESSION_NAME' mean? Does anyone know how to solve this strange problem? Thanks~

**Comment by mayankbansal018** [comment]
can you please upgrade to latest test sdk(15.9+), & see if that resolves the issue for issue?

**Comment by bidiudiu** [comment]
> can you please upgrade to latest test sdk(15.9+), & see if that resolves the issue for issue?

Hi,
  Thanks for your suggestion! I tried latest version 16.2.0 and the issue still exists. Maybe because I'm using netcore 2.0 but the sdk supports netcore 1.0?

**Comment by mayankbansal018** [comment]
@bidiudiu the SDK brings in the lower version netcore1.0 so that any higher target framework will get those dependencies implicitly.

Can you please try this via CLI, enable diagnostics logs, & share those with us. https://github.com/Microsoft/vstest-docs/blob/master/docs/diagnose.md

**Comment by bidiudiu** [comment]
> @bidiudiu the SDK brings in the lower version netcore1.0 so that any higher target framework will get those dependencies implicitly.
> 
> Can you please try this via CLI, enable diagnostics logs, & share those with us. https://github.com/Microsoft/vstest-docs/blob/master/docs/diagnose.md

Sure. Will provide more info later. Thanks!

**Comment by bidiudiu** [comment]
@mayankbansal018 I put logs here(still use 15.8.0 in the log since 16.2.0 has same behavior): [https://github.com/bidiudiu/Issue/tree/master/VsTest](VsTest)

**Comment by mayankbansal018** [comment]
@bidiudiu can you please share a sample repro project for this. I tried locally & it worked fine.

**Comment by bidiudiu** [comment]
@mayankbansal018 sure. I put a repro project here: https://github.com/bidiudiu/Issue/tree/master/VsTest/DevStudio/DevStudio.Core.UnitTest

I'm using VS Enterprise 2017, 15.9.13. Thanks for your help~

**Comment by mayankbansal018** [comment]
@bidiudiu I was able to run this project successfully both with & w/o coverage. This could be a machine specific issue, I can suggest that you please try this on a separate VM, & see if you still face this issue.

**Comment by bidiudiu** [comment]
@mayankbansal018 that's a little bit strange...On my two VMs and on VSTS (use 'dotnet test' in CI), same issue exists. 
But I just tried on my laptop (with earlier version VS 2017 15.6.7) and the issue disappeared. I'll re-install lower version VS on my VMs and try again.

**Comment by bidiudiu** [comment]
I find that there're two problems here: One is machine specific issue. Another is that: If in Process.Start() an user-written dll is executed, we should add Microsoft.CodeCoverage package to this user-written project.
