### ISSUE TITLE
Unable to find custom datacollector nuget

### ISSUE THREAD

**Issue by vagisha-nidhi** [microsoft/vstest#2087]
## Description
Unable to find custom datacollector nuget. Any custom datacollector, published as a nuget package would not be able to be directly consumed if specifying the datacollector via run settings file and running tests via VS.

## Related issue
https://github.com/tonerdo/coverlet/issues/485

## Steps to reproduce
1. Have a reference to coverlet.collector nuget in test project.
2. Add this runsettings
```
<RunSettings>
  <DataCollectionRunSettings>
    <DataCollectors>
      <DataCollector friendlyName="XPlat code coverage">
        <Configuration>
          <Format>lcov</Format>
        </Configuration>
      </DataCollector>
    </DataCollectors>
  </DataCollectionRunSettings>
</RunSettings>

```
3. Selected this .runsettings file to be used in VS2019 through the Test > Test Settings > Select Test Settings File option
4. Run all tests.

## Expected behavior
Get the coverage report in results directory

## Actual behavior
It generates the folder, but never actually spits out the coverage report.

As a workaround, nuget path can be specified explicitly as TestAdapterPaths to get the datacollector picked.

**Comment by dbsanfte** [comment]
Just hit this myself. 

```
Starting test execution, please wait...
Data collection : Could not find data collector 'XPlat code coverage'
```

**Comment by mayankbansal018** [comment]
@vagisha-nidhi Can you close this, doesn't look a bug, but as designed.
