### ISSUE TITLE
Unit test templates missing from .NET Core Unit test project 

### ISSUE THREAD

**Issue by hicks86** [microsoft/vstest#2094]
**Visual Studio Version**:
Visual Studio Professional 2017
Version 15.9.11

**Summary:**
Clicking on AddItem on a .NET Core 2.1 Unit Test Project does not show the Test category or any of the Unit test templates **(1)** (as opposed to a .NET Framework project **(2)** ).

**(1)**
![netcore_testtemplates](https://user-images.githubusercontent.com/11144895/57832213-02b66200-77af-11e9-83ef-9233b6a191eb.png)

**(2)**
![netframework_testtemplates](https://user-images.githubusercontent.com/11144895/57832214-02b66200-77af-11e9-8914-1ff882897dfa.png)

**Steps to Reproduce**:

1.  Right click on the unit test project go to "Add" > then select "New Item"

2. The "Add New Item" window will appear.

3. On the left hand side under Visual C# Items the "Test" category is missing, also in the central template area there are no test templates.

**Expected Behavior**:
To be able to Add a New Item to a test project using a template such as "Basic Unit Test"/"Generic Test"/"UnitTest")

**Actual Behavior**:
No test templates are found for .NET Core test project

**User Impact**:
Manual creation of a test class, via adding a plain class then adding the `[TestClass]` and `[TestMethod]` decorator attributes.

**Comment by karanjitsingh** [comment]
@hicks86, this repository is for test execution engine for visual studio. i.e visual studio test platform.

AFAIK, this is by design. Since this repository is out of context for this issue, I suggest you post this on http://developercommunity.visualstudio.com/ for better traction.

**Comment by hicks86** [comment]
Ah right! 

I posted this here: https://github.com/dotnet/project-system/issues/4828#event-2486592170, then I was told to move it here?

So this is a regression from .NET framework IMO, in the sense that this is not available. I cannot be the only person with this issue. I assume the "work around" is to create my own template.

**Comment by hicks86** [comment]
I have reposted on dev community as suggested - if anyone end up here, this is the link: https://developercommunity.visualstudio.com/content/problem/652802/unit-test-templates-missing-from-net-core-unit-tes.html

**Comment by tuca222** [comment]
Hey @hicks86, did you fix the problem? i'm in the same situation here, and i do not now how to fix.

**Comment by hicks86** [comment]
Hey @tuca222 unfortunately not - I posted it in the dotnet github then was told to move it to here, then I was told to move it to the developercommunity (see the link above) - which it was then promptly closed AGAIN with very little explanation or solution. The reason I was given is that they were doing some cleanup.
My only suggestion is to build your own templates for unit tests and just using them.

**Comment by sgarske** [comment]
I am hitting this same issue with an SDK unit test project even if using `<TargetFramework>net472</TargetFramework>` if that matters.

>Microsoft Visual Studio Enterprise 2019
Version 16.11.5

Sorry if this is the wrong place to update, it's a little murky to me whether the item templates are owned by the project system or these platforms/frameworks like `vstest`, `wpf`, etc
