### ISSUE TITLE
ConsoleWrapper.Endsession does not dispose of translation layer EqtTrace logs

### ISSUE THREAD

**Issue by ShreyasRmsft** [microsoft/vstest#2097]
## Description
ConsoleWrapper.Endsession does not dispose of translation layer EqtTrace logs

The only time the translation layer log file lock gets released is after the process hosting the translation layer dies.

**Comment by singhsarab** [comment]
@vagisha-nidhi I thought we fixed this one

**Comment by vagisha-nidhi** [comment]
ConsoleWrapper.Endsession kills the vstest.console process which is locking the files. We have fixed this. Will look into if this occurs again.
