### ISSUE TITLE
Allow passing in multiple TestCaseFilter/Filter arguments in dotnet vstest/test

### ISSUE THREAD

**Issue by ViktorHofer** [microsoft/vstest#2099]
Combine multiple filter arguments with an AND operator. Having to pass in many filters in one argument is cumbersome.

cc @mayankbansal018

**Comment by singhsarab** [comment]
@ViktorHofer This will be slightly confusing. 
Usually I would then expect it work like an OR instead.

@mayankbansal018 What do you think ?

**Comment by ViktorHofer** [comment]
Is it currently possible for the /Filter attribute to contain multiple lines? wrapping each condition with brackets in its own line is fine as well.

**Comment by ViktorHofer** [comment]
The reason is that we need to be able to replace this xunit exclusion syntax with what VSTest supports with the Filter parameter: https://github.com/dotnet/coreclr/blob/master/tests/CoreFX/CoreFX.issues.rsp

**Comment by Evangelink** [comment]
@ViktorHofer Do you still need this feature/improvement?

**Comment by ViktorHofer** [comment]
At this point this is only a nice to have but not required anymore by dotnet/runtime.

**Comment by nohwnd** [comment]
This is a new feature and won't be implemented, we are focusing on adding new features to Testing.Platform instead. https://aka.ms/testingplatform
