### ISSUE TITLE
Specify environment variables in the runsettings file

### ISSUE THREAD

**Issue by ViktorHofer** [microsoft/vstest#2100]
Specifying environment variables in the runsettings file is necessary to support non-trivial projects that require settings env vars like DOTNET_ROOT. As discussed offline this is a blocker for dotnet repositories like corefx and sdk to onboard onto VSTest (dotnet test / vstest) and being able to use VS Test Explorer.

cc @singhsarab @cltshivash @vitek-karas @mayankbansal018

**Comment by vagisha-nidhi** [comment]
@ViktorHofer 
What is the exact ask here? From what I am understanding, we need the capability to set environment variables before the test run starts.
I'll share a sample runsettings.

```
<?xml version="1.0" encoding="utf-8"?>
<!-- File name extension must be .runsettings -->
<RunSettings>
 <RunConfiguration>
    <MaxCpuCount>1</MaxCpuCount>
    <ResultsDirectory>.\TestResults</ResultsDirectory>
    <TargetPlatform>x86</TargetPlatform>
    <TargetFrameworkVersion>Framework40</TargetFrameworkVersion>
    <TestAdaptersPaths>%SystemDrive%\Temp\foo;%SystemDrive%\Temp\bar</TestAdaptersPaths>
    <TestSessionTimeout>10000</TestSessionTimeout>
  </RunConfiguration>
  <DataCollectionRunSettings>
    <DataCollectors>
     </DataCollector>
    </DataCollectors>
  </DataCollectionRunSettings>
  <EnvironmentVariables>
    <!-- List of environment variables we want to set as element and its value-->
    <DOTNET_ROOT>C:\ProgramFiles\dotnet</DOTNET_ROOT>
    <SDK_PATH>C:\Codebase\Sdk</SDK_PATH>
  </EnvironmentVariables>
</RunSettings>
```
These environment variables will be set when test host process is launched as part of its ProcessStartInfo.

@ViktorHofer Is there anything else to be taken into consideration?

cc: @singhsarab @PBoraMSFT

**Comment by singhsarab** [comment]
Things to consider:
1. Should we have a separate node? or should this node be part of the RunConfiguration node itself?
2. Will this run in isolation always (i.e. tests run in test host) ?
3. Can users give these settings as commandline arguments ?

**Comment by vagisha-nidhi** [comment]
@ViktorHofer Also, there is an option to specify [run parameters](https://github.com/microsoft/vstest-docs/blob/master/docs/configure.md#run-parameters) as key value pairs which can be used at run time. Does this suffice your need? 
Or is it necessary to set the variables during test host process start?
