### ISSUE TITLE
Any planned support for Microsoft fakes in .net core?

### ISSUE THREAD

**Issue by AdamYoblick** [microsoft/vstest#2105]
Hello,

Not sure if this is the right place to ask, so I apologize if it's not. I'm trying to use Microsoft Fakes to shim some non-virtual methods, and it seems fakes is not supported in .net core.

Are there any plans to support this tech in .net core?

Thank you :)

**Comment by singhsarab** [comment]
@AdamYoblick You should raise it here https://developercommunity.visualstudio.com/
