### ISSUE TITLE
Progress indicator floods CI server build log with lots of distracting "Test run in progress..." messages

### ISSUE THREAD

**Issue by stakx** [microsoft/vstest#2106]
## Description

VSTest's [`ProgressIndicator` class](https://github.com/microsoft/vstest/blob/1e37ee32dbba48ad797b03bff0058c5c60a3a770/src/vstest.console/Internal/ProgressIndicator.cs) doesn't play particularly well with some terminals, such as the one of AppVeyor for Linux. It repositions the cursor in order to display a varying number of dots behind a "Test run in progress" message, but that doesn't always work as intended. See e.g. [this AppVeyor log](https://github.com/microsoft/vstest/files/3444180/log.txt) or [this slightly more realistic one](https://github.com/microsoft/vstest/files/3444206/log2.txt), which gets needlessly long by these repetitive and malformatted messages and the actual test run output in-between can be hard to spot.

One can suppress it using the verbosity switch (e.g. `dotnet test -v q`) but that also suppresses other, useful messages (such as the list of skipped tests).

Would it be possible to adjust `ProgressIndicator` such that it plays along better with such  terminals... or could you add a switch to disable specifically the progress indicator, while leaving other messages visible?

## Steps to reproduce

I've prepared a small .NET Core test project (https://github.com/stakx/VSTestProgressIndicatorFloodRepro) that you can fork and add as a project on an AppVeyor account of your own, then trigger a build. The log you'll get should be very similar to the first one I posted above. (That project simply runs a few dummy tests that take long enough to give the progress indicator enough time to update itself a few times.)

**Comment by kaadhina** [comment]
We are tracking this using https://github.com/microsoft/vstest/issues/2120
