### ISSUE TITLE
Is it possible to trigger the post approval only on hundred percent success of tests from the task VSTest

### ISSUE THREAD

**Issue by Dstar2020** [microsoft/vstest#2109]
## Description
> **IMPORTANT**: if the defect is reproduced only in a workflow from within the Visual Studio IDE then do not report the issue here - instead, please report it using Visual Studio's "Send Feedback" option that can be accessed from the Help menu OR using this link https://developercommunity.visualstudio.com.
>
> For a defect reproducable from the vstest command line, describe the issue you've observed.

## Steps to reproduce
> What steps can reproduce the defect?
> Please share the setup, commandline for vstest.console, sample project, target
> framework etc.

## Expected behavior
> Share the expected output

## Actual behavior
> What is the behavior observed?

## Diagnostic logs
> Please share test platform diagnostics logs. Instructions to collect logs are [here](https://github.com/Microsoft/vstest-docs/blob/master/docs/diagnose.md#test-platform-diagnostics).  
> The logs may contain test assembly paths, kindly review and mask those before sharing.

## Environment
> Please share additional details about the test environment.
> Operating system, Build version of vstest.console

**Comment by ShreyasRmsft** [comment]
@Dstar2020 it is not possible to do this from the VsTest task.

However the vstest task fails if any tests fail and your approval automatically gets denied since the build/release will fail.

Therefore adding a script after the vstest to approve should work as this task never gets executed if even a singe test fails.

**Comment by Dstar2020** [comment]
Thanks @ShreaysRmSoft is there a sample script intended for this purpose

**Comment by ShreyasRmsft** [comment]
Please do go through the docs 

https://docs.microsoft.com/en-us/azure/devops/pipelines/release/approvals/approvals?view=azure-devops

https://docs.microsoft.com/en-us/azure/devops/pipelines/release/deploy-using-approvals?view=azure-devops

https://docs.microsoft.com/en-us/azure/devops/pipelines/release/approvals/gates?view=azure-devops
