### ISSUE TITLE
Vstest fails in build pipeline with message " Debug information could not be found for target assembly "

### ISSUE THREAD

**Issue by Dstar2020** [microsoft/vstest#2111]
## Description
> **IMPORTANT**: if the defect is reproduced only in a workflow from within the Visual Studio IDE then do not report the issue here - instead, please report it using Visual Studio's "Send Feedback" option that can be accessed from the Help menu OR using this link https://developercommunity.visualstudio.com.
>
> For a defect reproducable from the vstest command line, describe the issue you've observed.

## Steps to reproduce
> C# test project in .Net framework v4.7.2 run indefinitely in Build pipeline on premise TFS 

## Expected behavior
> Test runs fine and results are generated

## Actual behavior
> Tests are not executed and run indefinitely with error message 

>  **Debug information could not be found for target assembly 'AppName.UnitTest.dll'. For best analysis results, include the .pdb file with debug information for 'AppName.UnitTest.dll' in the same directory as the target assembly.**

## Diagnostic logs
> Please share test platform diagnostics logs. Instructions to collect logs are [here](https://github.com/Microsoft/vstest-docs/blob/master/docs/diagnose.md#test-platform-diagnostics).  
> The logs may contain test assembly paths, kindly review and mask those before sharing.

## Environment
Build server
VStest.console version 2

**Comment by ShreyasRmsft** [comment]
@Dstar2020 this is not the right forum for this question please post this on https://github.com/microsoft/azure-pipelines-tasks/issues and tag it with Area: Test to bubble it up to the Test team. Thanks
