### ISSUE TITLE
I am having issues running tests with fakes

### ISSUE THREAD

**Issue by dparvin** [microsoft/vstest#2112]
## Description
When I use the vstest.console.exe that is placed in my _tool folder on my machine where I have installed my Azure DevOps agent, (in my case: C:\agent\_work\_tool\VsTest\16.2.0\x64\tools\net451\Common7\IDE\Extensions\TestPlatform) the unit tests that I have created that use Fakes will fail with the error listed below.  If the machine I am running the tests on has Visual Studio 2015 or later installed and I use the vstest.console.exe from that install instead, my tests run as expected.  

When I do not have Visual Studio installed on my testing machine, I get the error listed below.  If I have VS 2019 installed then I get the error 

> Microsoft.QualityTools.Testing.Fakes.UnitTestIsolation.UnitTestIsolationException : Failed to get profiler module handle 'C:\Program Files (x86)\Microsoft Visual Studio\Shared\Common\IntelliTrace\ProfilerProxy\x86\Microsoft.IntelliTrace.ProfilerProxy.dll'. The specified module could not be found

I looked in that folder and it did have the file there.  I also know there is one that is copied into the **C:\agent\_work\_tool\VsTest\16.2.0\x64\tools\net451\Common7\IDE\CommonExtensions\Microsoft\IntelliTrace\ProfilerProxy\x86** folder, but when using the vstest.console.exe from my agent's tools folder, it does not like using the one from VS and does not try to use the one in the agent's tools folder.

## Steps to reproduce
When I have my compiled code, with my tests in a folder that looks like: **C:\agent\_work\r1\a\drop\Build\Releasex64**
I have my packages in the **C:\agent\_work\r1\a\drop** folder.
I have a **Visual Studio Test Platform Installer** task in my Pipeline for the agent to install the tools and then I set the **Visual Studio Test** task to use the installed tools.

I run either my batch file or use the Visual Studio Test, my tests with Fakes fail the same way.
My tests and the overall applications they are testing, are built with Framework verion 4.6.

## Expected behavior
The test runs and passes on a machine that does not have VS installed just as they do on a machine where VS is installed.

## Actual behavior

>  Error Message:
>     Microsoft.QualityTools.Testing.Fakes.UnitTestIsolation.UnitTestIsolationException : Failed to open profiler registry key 'CLSID\{9317ae81-bcd8-47b7-aaa1-a28062e41c71}\InprocServer32'.
>    Stack Trace:
>       at Microsoft.QualityTools.Testing.Fakes.UnitTestIsolation.IntelliTraceInstrumentationProvider.ResolveProfilerPath()
>     at Microsoft.QualityTools.Testing.Fakes.UnitTestIsolation.IntelliTraceInstrumentationProvider.Initialize()
>     at Microsoft.QualityTools.Testing.Fakes.UnitTestIsolation.UnitTestIsolationRuntime.InitializeUnitTestIsolationInstrumentationProvider()
>     at Microsoft.QualityTools.Testing.Fakes.Shims.ShimRuntime.CreateContext()
>     at Microsoft.QualityTools.Testing.Fakes.ShimsContext.Create()

## Environment
All of my build and test machines are Windows 10 machines. The ones with Visual Studio installed, have VS 2015 Enterprise with the latest update installed.  The machines that are my test agents do not have visual studio installed.  I have one machine that is setup as interactive and one that is not.  This works the same on both.

I have my tasks setup to use the latest version of vstest.console, which happens to be 16.2.0.

[CoverTest.zip](https://github.com/microsoft/vstest/files/3462363/CoverTest.zip)

**Comment by ShreyasRmsft** [comment]
@dparvin the testplatform in the _tool folder is installed by the vstestplatform tool installer and is meant to be used with the vstest task.

The reason is that additional work is done by the vstest task to set environment variables needed to point the testplatform to the intellitrace profiler dlls etc. in case of the nuget package.

If VS is installed on the machine these need not be set since the dlls are available in the GAC.

I would strong urge you to use the vstest task for running tests via the nuget package.

**Comment by ShreyasRmsft** [comment]
@dparvin were you able to try this out?

**Comment by ShreyasRmsft** [comment]
Closing due to no-response. Please re-open if issue persists after trying out above suggestions.

**Comment by dparvin** [comment]
Sorry, was on vacation.  I tried using the VSTest task to run the tests and I tried running a batch from the command line and both gave the same results.  I installed Visual Studio 2015 (That is the current version we are using with build) and VS 2019.  I was able to set the VSTest task to use the installed VS 2015 and my unit tests ran just fine.  I also made a test process that ran my tests with the batch file when VS installed and using the test console from that VS and the tests ran there too.  I was trying to setup a machine to run my unit tests without having to install VS on the machine and have the unit tests run.  The unit tests that do not use Fakes ran fine without VS installed, but any unit test that had fakes failed.  Currently I now have my test running machines with VS installed on them and my test processes setup to use VS 2015 for running the tests.  I expect in the next week or two I will have another machine that I can put an agent on where VS was not ever installed and I can try this again.  Until I installed VS 2015 and pointed my test processes to running the tests with the VS 2015 installed test console (using VSTest task or batch, it did not seem to matter) I never got my tests to run.

**Comment by ShreyasRmsft** [comment]
When using the VsTest platform tool installer task (https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/tool/vstest-platform-tool-installer?view=azure-devops) you also need to change an option in the vstest task to use the test platform from the tool installer. See the linked blog for details on how to do this.

Once this is done, whether you have VS or not on the machine  you should be able to run your tests with fakes enabled. If even after doing the steps mentioned you are facing issues please provide the full set of zip logs with system.debug = true.

**Comment by ShreyasRmsft** [comment]
Please re-open after following the requested steps.
