### ISSUE TITLE
Add support for a singleton datacollector

### ISSUE THREAD

**Issue by rishi2110** [microsoft/vstest#2114]
## Description
A new data collector process is spawned for each parallel assembly being tested using vstest.
There is no option to have a singleton data collector that serves all tests.
A new command line param or runsettings config should be added that allows for this behavior

We are creating a test framework which has the ability to capture network traces using fiddler.
The capture logic will be written in a datacollector that will also attribute http requests and responses to the currently running test.

Fiddler registers itself as a system proxy so it's logic can only be executed in one data collector.
The host started event provides the process id of the multiple test hosts (if multiple assemblies are being tested) and the test start and test events then provide us with the data needed to associate the captured traces with the correct tests.

**Comment by ShreyasRmsft** [comment]
@PBoraMSFT please take a look at the ask.

**Comment by ShreyasRmsft** [comment]
@rishi2110 as a workaround i could suggest your author your data collector in such a way that it handles conflict resolution and only one datacollector sets the proxy/launches fiddler.

**Comment by rishi2110** [comment]
That is an option we have considered but there will be a lot of overhead to make it work.
We would have to end up creating a global fiddler process that would need to communicate with the vstest spawned datacollector processes over sockets using json.

I think that it's better to support this in vstest natively than implement a one off solution only for us given that this single datacollector process option would be generalizable and could be useful for other projects in the community.

**Comment by ShreyasRmsft** [comment]
@rishi2110 this is something we would need to discuss with regards to feasibility and usage. I have tagged this as an enhancement and this will take quite a lot of time to implement as it involves changes in the architecture. We will be prioritizing enhancements based on popular demand.

You are however always free to contribute and we will help out in terms of reviews etc. where possible. Thanks

**Comment by Evangelink** [comment]
@MarcoRossignoli Do you know if the `InProcessDataCollector` would work and fit this need?

**Comment by nohwnd** [comment]
This is outdated, closing.
