### ISSUE TITLE
testhost.exe - only with Code Coverage: TestCaseEventsHandler.RaiseTestCaseStart: System.NullReferenceException

### ISSUE THREAD

**Issue by JesperBjerre** [microsoft/vstest#2119]
## Description
We see a lot of exceptions in the TestHost log file.

```
TpTrace Verbose: 0 : 14884, 16, 2019/08/08, 14:52:10.434, 1938244767245, testhost.exe, TestRunCache: OnNewTestResult: Notified the onCacheHit callback.
TpTrace Error: 0 : 14884, 16, 2019/08/08, 14:52:10.470, 1938245126933, testhost.exe, TestCaseEventsHandler.RaiseTestCaseStart: Exception occurred while calling handler of type Microsoft.VisualStudio.TestPlatform.CrossPlatEngine.DataCollection.ProxyOutOfProcDataCollectionManager for TestCaseStartEventArgs: System.Reflection.TargetInvocationException: Destinationen for en aktivering udløste en undtagelse. ---> System.NullReferenceException: Objektreferencen er ikke indstillet til en forekomst af et objekt.
   ved Microsoft.VisualStudio.TestPlatform.CommunicationUtilities.SocketCommunicationManager.ReceiveRawMessage()
   ved Microsoft.VisualStudio.TestPlatform.CommunicationUtilities.SocketCommunicationManager.ReceiveMessage()
   ved Microsoft.VisualStudio.TestPlatform.CommunicationUtilities.DataCollectionTestCaseEventSender.SendTestCaseStart(TestCaseStartEventArgs e)
   --- Slut på staksporing af indre undtagelser ---
   ved System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor)
   ved System.Reflection.RuntimeMethodInfo.UnsafeInvokeInternal(Object obj, Object[] parameters, Object[] arguments)
   ved System.Delegate.DynamicInvokeImpl(Object[] args)
   ved Microsoft.VisualStudio.TestPlatform.Utilities.MulticastDelegateUtilities.SafeInvoke(Delegate delegates, Object sender, EventArgs args, String traceDisplayName)
```

This only happens when Code Coverage is enabled.

**TFS Build Code Coverage issue:**

Our main issue is that the TFS build job hangs 3 out of 100 builds when Code Coverage is enabled and we expect the above exception to be related.

vstest.console.exe keeps polling testhost that never will return success or failure of the test.

25340, 11, 2019/06/27, 21:00:12.252, 1262844200883, vstest.console.exe, TcpClientExtensions.MessageLoopAsync: Polling on remoteEndPoint: 127.0.0.1:4419 localEndPoint: 127.02.0.0.1:4418

## Steps to reproduce

The issue can also be reproduced on a developer PC.

vstest.console (VS2017 or VS2019) is called from Command Prompt. The testhost exception is logged every time. Testhost will stop returning success or failure of test in 3 of 100 times.

## Environment
VS2017 Enterprise 15.9.13
VS2019 Enterprise 16.2
Windows 10
XUnit 2.4.1 / x64

### Parameters
"C:\udv\xyz.Test.dll"
/Settings:"C:\CodeCoverage
/EnableCodeCoverage
/logger:"trx"
/TestAdapterPath:"C:\udv\xyz"
/Platform:x64 
/Diag:c:\temp\logs\diag.txt

[CodeCoverage.runsettings.txt](https://github.com/microsoft/vstest/files/3481958/CodeCoverage.runsettings.txt)

**Comment by ShreyasRmsft** [comment]
@JesperBjerre could you please use the [vstest platform tool installer task](https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/tool/vstest-platform-tool-installer?view=azure-devops) and use the latest pre-release version of the testplatform to see if you still face the issue?

**Comment by ShreyasRmsft** [comment]
Closing due to no response. Please do re-open if problem persists after trying out the above suggestion.
