### ISSUE TITLE
Need to provide an API for custom test host launchers to launch process in same way as default "RunTests"

### ISSUE THREAD

**Issue by KevinH-MS** [Microsoft/vstest#212]
LUT currently implements ```ITestHostLauncher``` and passes it to ```IVsTestConsoleWrapper.RunTestsWithCustomTestHost``` in order to track the lifetime of the testhost process.

We want to ensure that the way in which the Process is launched is, as much as possible, the same as the default behavior (when calling ```IVsTestConsoleWrapper.RunTests```).  Today, the only convenient way I can find to do this is by calling into the ```DefaultTestHostManager``` in the CrossPlatEngine.

We need an API we can pass a ```TestProcessStartInfo``` to and get back a process id (or ```Process```) and behaves the same as ```IVsTestConsoleWrapper.RunTests```.

Given that we currently have no VS dependencies in the calling code, this API should ideally live in the Translation Layer or TestPlatform.

**Comment by pvlakshm** [comment]
Closing this; please reactivate if still required.
