### ISSUE TITLE
Visual Studio does not run all tests when the test discovery failed on one test in a class

### ISSUE THREAD

**Issue by DerAlbertCom** [microsoft/vstest#2122]
Visual Studio Test Runner does not run all xUnit Tests (maybe also other test frameworks) when the test discovery throws an exception. I also filed this under https://github.com/xunit/visualstudio.xunit/issues/165

## Steps to reproduce
Checkout the repository https://github.com/DerAlbertCom/MisbehavingUnittestRunners it in Visual Studio. More details why the problem occurs is also there.

## Expected  behavior

At least the exception within the test discovery shows up. And not silently not run the test without any reason. Also excepting to show a skip reason in the test runner. 

## Actual behavior

Test withing Visual Studio 2019 16.2 
![Wrong behavior](https://github.com/DerAlbertCom/MisbehavingUnittestRunners/raw/master/visual-studio-2019-16-2.PNG).
In the sample repository are 6 Unit Test, 2 of are not run without any hint because of an exception within the test discovery on one test.

**Comment by ShreyasRmsft** [comment]
@DerAlbertCom i think once xunit propagates this the IDE can show this against the tests. You can open this issue in the developer community if after xunit fixes this and it still does not show up.

**Comment by DerAlbertCom** [comment]
@ShreyasRmsft i've done some research on this topic on xunit side, i also added my findings on that issue. but xunit has a ton of indirection, not that easy to check or fix if someone is not familiar with the code.
