### ISSUE TITLE
Documentation on writing test adapters?

### ISSUE THREAD

**Issue by alexrp** [microsoft/vstest#2129]
Hello,

A little background: I'm working on a programming language implementation. While many aspects of the compiler and VM can be easily tested in e.g. xUnit, there are other things that are much easier to test with other tools similar to [LLVM's FileCheck](https://llvm.org/docs/CommandGuide/FileCheck.html). That said, I'd like for these tests to still be run and reported as part of `dotnet test` to make the development workflow as simple as possible.

So, from what I gather, the proper way to do this is to implement a test adapter that reports and runs these non-xUnit tests. However, I've not been able to find any current documentation on how to set up a test adapter project and which interfaces I need to implement. Can anyone point me in the right direction?

And a somewhat related question: Is it possible for a test project to declare and export a test adapter directly, such that referencing a NuGet package (e.g. `xunit.runner.visualstudio`) is not necessary?

(I originally posted this on [vstest-docs](https://github.com/microsoft/vstest-docs), but realized after that issues on that repository seem to get little to no attention, so posting here as well.)

**Comment by ShreyasRmsft** [comment]
@alexrp the docs are present here https://github.com/Microsoft/vstest-docs/blob/master/RFCs/0004-Adapter-Extensibility.md

You can ship the adapter however you want. You can quite literally copy it to the test directory just before running tests.

Or you can have it in some common location and set the adapter path property in the runsettings to point to the adapter dll.

Let us know if you need any further clarifications.
