### ISSUE TITLE
Allow sources to be parallelized across processes and controlled by adapters

### ISSUE THREAD

**Issue by NGloreous** [microsoft/vstest#2138]
## Description
Today vstest doesn't split tests within a dll across multiple processes (e.g. if I only have 1 dll with thousands of tests they will all run sequentially in one process, assuming the adapter doesn't support parallelization or the tests can't be parallelized in the same process).

Ideally control of how tests within a dll are split across processes is determined by the adapter to allow consumers to provide custom logic. 

## Context
My team is trying to migrate off a custom built test harness to vstest/mstest but we have built up logic within our harness to effectively stripe/parallelize our tests across multiple machines and processes. This allows up to load balance our tests based on runtime to minimize the overall test pass time. Losing the ability to load balance tests within a dll will greatly increase our overall test pass time.

**Comment by nohwnd** [comment]
This is a great idea but we won't be implementing it into TestPlatform any time soon, sorry.
