### ISSUE TITLE
Stopping Debugging shows non-descriptive error

### ISSUE THREAD

**Issue by vritant24** [microsoft/vstest#2141]
cancelling/stopping debugging before it is complete shows the following error in the test output pane:
```The active test run was aborted. Reason: Test host process crashed```

Would it be possible to indicate with the error that the debugger was cancelled.

**Comment by vagisha-nidhi** [comment]
When the debugger is cancelled such that the test host process aborts, the test host abort error will be shown. And as the test host has already aborted, I don't think there is a way to find out the reason of the abort was the debugger.
