### ISSUE TITLE
vstest batches execution

### ISSUE THREAD

**Issue by migheorghe** [microsoft/vstest#2143]
## Description
Tests marked with ClassData attribute are not executed in AzureDevOps using vstest configured with batches.

## Steps to reproduce

We have a job in AzureDevOps that uses strategy 'parallel' with 5 agents  and it's using vstest task in configured with the settings bellow: 
            distributionBatchType: 'basedOnExecutionTime'
            batchingBasedOnExecutionTimeOption: 'customTimeBatchSize'
            customRunTimePerBatchValue: '60'

We have a xUnit test marked with ClassData attribute. The attribute parameter it's a class that has 2 (but we tested with even more) values. 
When there are two values for ClassData both the test are discovered but only the first one is executed.

When we tested with 10 values in total we get errors like the ones bellow: 

Build Id: 469319
Test run with Id 1819964 associated
Received the command : Start
TestExecutionHost.ProcessCommand. Start Command handled
Received the command : Stop
TestExecutionHost.ProcessCommand. Stop Command handled
SliceFetch Aborted. Moving to the TestHostEnd phase
Test run '1819964' is in 'Aborted' state.
=====================
##[error]The slice of type 'Discovery' is 'Aborted' because of the error : System.Exception: [xUnit.net 00:00:52.45]   Discovered:  ************.Webhooks.Tests
Received the command : Stop
TestExecutionHost.ProcessCommand. Stop Command handled
SliceFetch Aborted. Moving to the TestHostEnd phase
Test run '1819964' is in 'Aborted' state.

## Expected behavior
All the tests should be discovered and executed.

## Actual behavior
Nondeterministic behavior. With 2 values both are discovered but only the first one is executed. With 10 values on one job the tests are discovered but none executed as the other jobs are failing with the errors above.

## Environment
AzureDevOps, jos strategy parallel with 5 agents, vstest configured to run with batches based on execution time.

**Comment by vagisha-nidhi** [comment]
@migheorghe Can you please get full logs by setting `system.debug=true` in your pipeline and share those with us?

**Comment by vagisha-nidhi** [comment]
Closing since no response. Please reopen with the logs.
