### ISSUE TITLE
Microsoft.CodeCoverage is missing

### ISSUE THREAD

**Issue by kant2002** [microsoft/vstest#2151]
Package `Microsoft.NET.Test.Sdk` version 16.3.0-preview-20190828-03 is depends on the Microsoft.CodeCoverage which is broken

**Comment by vagisha-nidhi** [comment]
Sorry for the trouble. Microsoft.CodeCoverage 16.3.0-preview-20190828-03 has been uploaded here https://www.nuget.org/packages/Microsoft.CodeCoverage/16.3.0-preview-20190828-03.
This should fix it.
