### ISSUE TITLE
`dotnet test --blame` does not produce Sequence.xml file

### ISSUE THREAD

**Issue by AArnott** [microsoft/vstest#2154]
dotnet SDK version: 2.2.401

`dotnet test -f netcoreapp2.1 --no-build --blame`  should produce a `Sequence.xml` file while running tests so we can know what test was running at the time of a crash or hang. But it doesn't create this file.

```
  --blame                                  Run the tests in blame mode. This option is helpful in isolating a problematic test causing the test host to crash.
                                           Outputs a 'Sequence.xml' file in the current directory that captures the order of execution of test before the crash.
```

Without this file, for async tests on linux it's impossible to know which test was running when the test runner hung.

**Comment by vagisha-nidhi** [comment]
@AArnott I just ran a quick test on blame and it seems like working.
Can you please provide a sample project where sequence.xml wasn't created? 
Can you also make sure that there is a crash in the tests? We do not create the sequence file until we have detected a crash. [This](https://github.com/microsoft/vstest/blob/master/src/Microsoft.TestPlatform.Extensions.BlameDataCollector/BlameCollector.cs#L361) is for reference.

**Comment by AArnott** [comment]
OK, there wasn't *actually* a crash in my testing. I just had tests that hung, so I then terminated the test process with Ctrl+C and expected to see the Sequence.xml file.

Is there *any* way to find out which test hangs in a case like this? The logger only writes to the console when the test *completes*, so I can't tell what test is running at any given time. :(

**Comment by vagisha-nidhi** [comment]
@AArnott We have added the functionality to collect dump on test hang here [here](https://github.com/microsoft/vstest/pull/2110). It generates a dump if for hang scenarios.
You can specify additional parameters with blame to get this in runsettings

```
<RunSettings>
  <!-- Configurations that affect the Test Framework -->
  <RunConfiguration>

  </RunConfiguration>

  <!-- Configurations for data collectors -->
  <DataCollectionRunSettings>
    <DataCollectors>
         <DataCollector friendlyName="blame" enabled="True">
             <Configuration>
                <ResultsDirectory>C:\TestResults</ResultsDirectory>
		<CollectDumpOnTestSessionHang TestTimeout="100" />
             </Configuration>
         </DataCollector>
     </DataCollectors>
  </DataCollectionRunSettings>
</RunSettings>
```
TestTimeout is used for specifying what the expected execution time for the longest running test is.
Also, this wouldn't work for dotnet 2.2.401. It has been inserted into the latest .Net Core 3.0 version.

**Comment by AArnott** [comment]
That's great to hear!

Does this work cross-plat or only on Windows? (What does a dump file even look like for non-Windows and how can one analyze it?)

Can I enable this and configure the directory to write dump files to as command line switches? I wouldn't want dump files produced by default during development on my local box, but I would like to check in a runsettings file to set the timeout, and then use switches in the Azure Pipelines build to enable the hang dumps and indicate what directory to write them to. And the target directory should be created automatically if it does not already exist. Does that work?

**Comment by vagisha-nidhi** [comment]
@AArnott Dump creation at present only work on windows as we use [ProcDump](https://docs.microsoft.com/en-us/sysinternals/downloads/procdump) for it. 

You can use vstest task in azure pipelines with run settings file configured to create dump in test hang.
```
<RunSettings>
  <!-- Configurations that affect the Test Framework -->
  <RunConfiguration>

  </RunConfiguration>

  <!-- Configurations for data collectors -->
  <DataCollectionRunSettings>
    <DataCollectors>
         <DataCollector friendlyName="blame" enabled="True">
             <Configuration>
                <ResultsDirectory>C:\TestResults</ResultsDirectory>
		<CollectDumpOnTestSessionHang TestTimeout="100" />
             </Configuration>
         </DataCollector>
     </DataCollectors>
  </DataCollectionRunSettings>
</RunSettings>
```
The directory is also configurable by the ResultsDirectory node in the run settings(It will create the directory if it doesn't already exist) All this will work on a windows agent as vstest task is supported only on windows. 
If you want to configure dump creation only in case of crash, you can use the already available option in the task.
![image](https://user-images.githubusercontent.com/13175100/64587153-043e1280-d3bc-11e9-8f24-49f3cf46dda3.png)
