### ISSUE TITLE
Tests don't run when doing 'dotnet test' or using VS IDE

### ISSUE THREAD

**Issue by nadvolod** [microsoft/vstest#2160]
## Description
Unit tests are not executing in a .NET Standard project using MsTest testing framework

## Steps to reproduce
1. Pull down this repo: https://github.com/saucelabs/simple_sauce/tree/first
2. Build this solution: https://github.com/saucelabs/simple_sauce/tree/first/dotnet
3. Try to run the MsTest unit test here: https://github.com/saucelabs/simple_sauce/blob/first/dotnet/SimpleSauce/SimpleSauce.Tests/Test.cs

## Expected behavior
I expect the test to execute and give me a pass/fail status

## Actual behavior
Nothing happens, whether through command line or through VS IDE

## Diagnostic logs
Couldn't figure out how to get these

## Environment
Windows 10, VS Enterprise 2019

**Comment by vagisha-nidhi** [comment]
@nadvolod I see that your test project does not have a nuget reference to MSTest.TestAdapter here https://github.com/saucelabs/simple_sauce/blob/first/dotnet/SimpleSauce/SimpleSauce.Tests/SimpleSauce.Tests.csproj#L9
Can you please add the reference and check if its working?
<PackageReference Include="MSTest.TestAdapter" Version="2.0.0" />
[Documentation link](https://docs.microsoft.com/en-us/dotnet/core/testing/unit-testing-with-mstest)

**Comment by kaadhina** [comment]
Closing this. Please get back if the above did not help.
