### ISSUE TITLE
VSTest is pushing to the wrong channel in BAR

### ISSUE THREAD

**Issue by ViktorHofer** [microsoft/vstest#2169]
VSTest pushes to ".NET Core 3 Dev" but we are already on ".NET Core 5 Dev". I recommend to either push a channel that is not directly tied to a release or always stay on the latest one.

Also VSTest should probably stop pushing to the myget feed (https://dotnet.myget.org/F/vstest/api/v2/package) and instead use the same one that all other repositories use (https://dotnetfeed.blob.core.windows.net/dotnet-core/index.json).

cc @singhsarab

**Comment by singhsarab** [comment]
This would probably require us to upgrade to use the latest Arcade toolset? 
/cc: @chcosta

**Comment by singhsarab** [comment]
The location given in the command seems to be pointing to the correct feed.
https://github.com/microsoft/vstest/blob/55e7e45431c9c05656c999b902686e7402664573/scripts/build.ps1#L829

**Comment by chcosta** [comment]
@riarenas @johntortugo?

**Comment by JohnTortugo** [comment]
Can you please point me to your build definition or to a build that is doing the wrong thing?

**Comment by singhsarab** [comment]
@JohnTortugo I have the definition offline, Can you please take a look.

**Comment by JohnTortugo** [comment]
@singhsarab your build definition seems to be quite outdated with the way Arcade proposes publishing to be implemented nowadays. We moved to stages based publishing, take a look here to see how to onboard: https://github.com/dotnet/arcade/blob/master/Documentation/CorePackages/YamlStagesPublishing.md

**Comment by riarenas** [comment]
I guess I'm a little confused by this whole issue. Is the problem just that master branch builds are publishing to the wrong channels so that corefx can take a dependency update on them, or that the packages need to be available in a different feed?

@mmitche Should vstest move to using the shared publishing infrastructure for .NET?

**Comment by chcosta** [comment]
Where's this repos build definition?

@johntortugo, are you saying that the sdk task packages are not working correctly?

**Comment by JohnTortugo** [comment]
This was the build that I looked: https://devdiv.visualstudio.com/DevDiv/_build/results?buildId=3058217&view=results . 

As far as I can tell it's a pretty custom build-definition: https://devdiv.visualstudio.com/DevDiv/_apps/hub/ms.vss-ciworkflow.build-ci-hub?_a=edit-build-definition&id=2923 and it looks like they are using their own custom sign, publish, etc. things.

The only Maestro++ channel configuration for repo `https://github.com/microsoft/vstest` is for branch `refs/heads/master` mapping to channel 19, which I don't think is correct as that's a release channel.

**Comment by chcosta** [comment]
Yeah, there are some repos that .NET Core depends on but aren't directly a part of the core product which are on dependency flow (at our request).  These repos (like NuGet, Application-Insights, etc...) we need to make sure we don't break and we provide support (generally in the form of guidance), so that they can flow dependencies without being in the inner ring of Arcade support.

**Comment by riarenas** [comment]
> All builds from https://github.com/microsoft/vstest where assigned to channel 3: .NET Core 3 Dev. Which is weird because the default channel mapping is pointing to channel 19.

Matt has been assigning and reassigning default channels to get everything release ready.

**Comment by JohnTortugo** [comment]
> This would probably require us to upgrade to use the latest Arcade toolset?

@singhsarab It's good to be on the latest toolset but I think you don't need it to fix the branch to where the builds are published. You just need to use Darc to configure to which channel the build should be assigned to by default.

**Comment by singhsarab** [comment]
@JohnTortugo I am not aware of how to do that. Can you please provide some guidance for that.

And @riarenas 
>Should vstest move to using the shared publishing infrastructure for .NET?

I think we have to move the repo to arcade tooling before we can do that.

**Comment by JohnTortugo** [comment]
> @JohnTortugo I am not aware of how to do that. Can you please provide some guidance for that.

Here are the instructions: https://github.com/dotnet/arcade/blob/master/Documentation/Darc.md#add-default-channel

**Comment by ViktorHofer** [comment]
any update?

**Comment by chcosta** [comment]
@ViktorHofer, the dev (@JohnTortugo) is OOF today, can this wait another day or two for an update or is this more pressing?

**Comment by ViktorHofer** [comment]
This can wait, thanks for the update.

**Comment by singhsarab** [comment]
> > @JohnTortugo I am not aware of how to do that. Can you please provide some guidance for that.
> 
> Here are the instructions: https://github.com/dotnet/arcade/blob/master/Documentation/Darc.md#add-default-channel

Sorry I am still not sure where do I run this instructions to make sure we are pointing to the right channel for vstest repo

**Comment by ViktorHofer** [comment]
You can invoke the darc CLI from any fully on boarded repo, ie from corefx. I should be able to change this as well and will try later.

**Comment by ViktorHofer** [comment]
I just updated the default channel.

Added: `(630)  https://github.com/Microsoft/vstest @ refs/heads/master -> .NET Tools - Latest`

Removed: `(578)  https://github.com/Microsoft/vstest @ refs/heads/master -> .NET Core 3 Release (Disabled)`

**Comment by singhsarab** [comment]
@ViktorHofer Great, I assume we can close this issue now ?

**Comment by ViktorHofer** [comment]
The packages are still not published to the blob feed: `https://dotnetfeed.blob.core.windows.net/dotnet-core/index.json`.

@JohnTortugo anybody know what needs to be changed to push to our feed?

**Comment by singhsarab** [comment]
@ViktorHofer I guess that will require us to change the CI definition. I currently pushes the packages to myget feed

**Comment by ViktorHofer** [comment]
You are right, this issue was about the channel. Let me close this one and create a new one for the feed request.
