### ISSUE TITLE
vstest batches execution errors

### ISSUE THREAD

**Issue by migheorghe** [microsoft/vstest#2170]
Reopenning of https://github.com/microsoft/vstest/issues/2143

Apparently the errors described in that issue were because the misuse of filter category in unit tests. Even if the behavior is strange this issue is open to solve a different case: execution of tests that are marked with ClassData IEnumerable objects

The follosing thins happens:
If the test is marked like this
    [Theory, Smoke] //where Smoke is a CategoryAttribute
    [ClassData(typeof(VersionsData))]

and the VersionsData class is
public class VersionsData : IEnumerable<object[]>
{
public IEnumerator<object[]> GetEnumerator()
{
yield return new object[] { "V1" };
yield return new object[] { "V2" };
yield return new object[] { "V3" };
}
    IEnumerator IEnumerable.GetEnumerator() => GetEnumerator();
}
all the test cases are discovered(in this case 3) but only the first one is executed. This happens on AzureDevOps running VsTest task with batches:
distributionBatchType: 'basedOnExecutionTime'
batchingBasedOnExecutionTimeOption: 'autoBatchSize'
Thanks

**Comment by kaadhina** [comment]
Can you please collect full debug logs (set pipeline variable system.debug = true) and share the logs zip file here ?

**Comment by migheorghe** [comment]
I ran the test with system.debug = true but I can't share all the logs with you. I looked over them and it doesn't seem to be helpful information for this problem. 
I would appreciate if you would take the time to create a project locally and fix this problems once you reproduce it.

Thanks

**Comment by kaadhina** [comment]
Please share a basic sample project and I will run this in a pipeline at my end to see if I can repro this.

**Comment by migheorghe** [comment]
Please find the most basic project at https://github.com/migheorghe/vstest
In includes a test marked with class data and the type for the class data is an enumerable with 5 items.
Let me know how testing goes

**Comment by vlad-zuga** [comment]
I am currently running into the same problem with the batching option, except that I use [InlineData()] and only the first test case is discovered (and run).

**Comment by kaadhina** [comment]
I was able to repro and debug this. The problem is that, when the nunit adapter gives a list of discovered test cases, all of them have the same fully qualified name. We do not support such scenarios right now. The FQDNs need to be unique for them to be treated as different test cases.
