### ISSUE TITLE
Handling of --verbosity is case-sensitive

### ISSUE THREAD

**Issue by matkoch** [microsoft/vstest#2179]
As already mentioned [here](https://github.com/microsoft/vstest/issues/1590#issuecomment-392955873). This is not in sync with the rest of dotnet CLI.

**Comment by matkoch** [comment]
Can this please be fixed soon? It's a major headache for everyone that can take a significant amount of time to track down.

**Comment by matkoch** [comment]
@mayankbansal018 I'm already surprised this hasn't been fixed after the [comments from last year](https://github.com/microsoft/vstest/issues/1590#issuecomment-392955873). This issue is so silly and it's wasting countless hours of your users time troubleshooting it. I'm really not happy with the pace of this project overall, especially since it's an important part for .NET.

**Comment by mayankbansal018** [comment]
@matkoch I just tired passing verbosity arg with different cases, & it worked fine on Windows, WSL, & Mac OS

Can you please try again with latest dotnet sdk(3.0.100), or are you facing this issue on some version of Linux? Can you please provide more details where you are facing this issue?

**Comment by mayankbansal018** [comment]
@matkoch can you please let us know if this is still an issue with dotnet skd(3.0.100, & greater) ?

**Comment by matkoch** [comment]
Yes it is.

**Comment by matkoch** [comment]
@mayankbansal018 ping. Could you please give an estimate?

**Comment by mayankbansal018** [comment]
@AbhitejJohn please track this issue

**Comment by AbhitejJohn** [comment]
Tagging @nohwnd . Should be a small change.

**Comment by nohwnd** [comment]
@AbhitejJohn kk, adding this to my work list 🙂
