### ISSUE TITLE
Check for tool in tool cache and skip download if exists

### ISSUE THREAD

**Issue by StephenRSkinner** [microsoft/vstest#2187]
The task should check the tools cache for the existence of the tool prior to download, and skip download if it's already there. This would greatly improve performance.

**Comment by singhsarab** [comment]
@StephenRSkinner By tool you mean dotnet sdk ?

**Comment by singhsarab** [comment]
@StephenRSkinner It is not very clear what is the expectation here. Closing this issue, Please provide the details for us to re-open. Thanks.
