### ISSUE TITLE
Update devdiv dependencies for xcopy Testplatform nuget

### ISSUE THREAD

**Issue by mayankbansal018** [microsoft/vstest#2193]
Solutions:

- In DevDiv repo, set up a pipeline which creates nuget out of devdiv dependencies & publishes the nuget to appropriate feed, which is accessible by Testplatform CI.

- In Testplatform CI pipeline, add a step to install latest VS version, & then cherry pick those dll's out of VS install folder into the nuget package.

**Comment by nohwnd** [comment]
The first solution would definitely be more convenient but would be a big bang rewrite of how it works now.

- third solution is to grab the dependencies from the cloud drop and from the internal nuget feed. I have a prototype for this. It identifies some files as missing and I was not able to find them in any of the nugets yet. Also some of the dependencies we are grabbing are not shipped in the end.

I think this approach would give us a solution that would be easier to get right.

**Comment by nohwnd** [comment]
From #2303:

Description
Test platform gets some of it's binaries from VisualStudio build via a deprecated mechanism. The source of binaries migrated to cloud drops.

 Research how cloud drops work and how to access them programatically
 Research how to get a subset of the drop limited to what we need
 Research what parts of the drop are needed for the various packages
 Solution proposal & prototype
Once that is done, we should:

 Modify the build to use the cloud drops
 Release Externals in automated way
🔥 problems:
 some files are not present in the drop anymore
 some files need to be grabbed via VS nuget feed, and the version sync there is difficult
/cc @singhsarab

**Comment by nohwnd** [comment]
@pavelhorak we agreed with @ManishJayaswal to do this in 16.6.0 but not actually commit it until we start 16.7.0, so we have a whole sprint to figure out potential issues with the build. The preparation is done. Moving this to 16.7.0.
