### ISSUE TITLE
vstest.console.exe /ListTests does not respect the /TestCaseFilter option

### ISSUE THREAD

**Issue by vagisha-nidhi** [microsoft/vstest#2195]
## Description
Issue related: https://developercommunity.visualstudio.com/content/problem/727051/vstestconsoleexe-listtests-does-not-respect-the-te.html

"‘vstest.console.exe /ListTests UnitTests.dll’ lists all the tests as expected.
‘vstest.console.exe /ListTests /TestCaseFilter:“Priority=0” UnitTests.dll’ also lists all the tests; I would expect it to only list the priority 0 tests.
The priority is set via the macro - TEST_PRIORITY( 0 )"

**Comment by vagisha-nidhi** [comment]
The issue is with cpp adapter. Workaround is to use a different adapter for c++ (ex. Google test adapter). Closing as low priority.

**Comment by JunielKatarn** [comment]
@vagisha-nidhi Where is the adapter implemented?

There are related bugs, like FSQNs not being printed when running.
https://github.com/microsoft/vstest/issues/1732
