### ISSUE TITLE
customize vstest summary

### ISSUE THREAD

**Issue by Coder-Bryan** [microsoft/vstest#2201]
Hi Guys, 

We have some personal requests about the summary of VSTest. I know we could modify the source codes to build our own VSTest. But except this, just want to check if VSTest already has the feature : ).

The current of summary is(for example):
**Total tests: 518. Passed: 517. Failed: 0. Skipped: 1.**
Could we count the total tests to **517**(means ignore the number of skip tests)? Or even not generate the summary, we could process the test result to get our own result?

Environment
> Windows OS version 1903
> VSTest version 15.8.0

I am very appreciate for any input : ).

Regards,

**Comment by singhsarab** [comment]
@Coder-Bryan You'd probably have write your own logger in that case.
You can follow https://github.com/microsoft/vstest-docs/blob/master/docs/report.md
