### ISSUE TITLE
ConfigurationManager.AppSettings is getting null on Azure Pipelines on 16.3-preview

### ISSUE THREAD

**Issue by xdaDaveShaw** [microsoft/vstest#2203]
## Steps to reproduce
Since Azure Pipelines has been updated to 16.3 preview all our test runs are now failing.
I'm not 100% sure what the full root cause is yet, but this appears to be related to reading a value from an `app.config` via `System.Configuration.ConfigurationManager.AppSettings` (this is on .NET Framework).

Previously our code was reading the value OK, now it is null.

## Expected behavior
Tests using `System.Configuration.ConfigurationManager.AppSettings` get a value.

## Actual behavior
`null` is returned.

## Diagnostic logs
Tests run against:
>"C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\Common7\IDE\Extensions\TestPlatform\vstest.console.exe" @d:\a\_temp\7369bca1-e130-11e9-8628-396c9d60e171.txt
Microsoft (R) Test Execution Command Line Tool Version 16.2.0

were passing.

Tests run against:
> C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\Common7\IDE\Extensions\TestPlatform\vstest.console.exe "@C:\Users\VssAdministrator\AppData\Local\Temp\tmp982A.tmp"
Microsoft (R) Test Execution Command Line Tool Version 16.3.0-preview-20190715-02

Now they are failing when run against.

## Environment
Running on Azure Pipelines.

**Comment by xdaDaveShaw** [comment]
We are still using VS2017 for developers at the moment. But we have managed to re-create by installing VS2019 (16.3) on one machine, so this might be a bigger problem than just console / Pipelines

**Comment by xdaDaveShaw** [comment]
There is also this in the Failing build that doesn't exist in the Passing one:

```
d:\a\_tasks\VSTest_ef087383-ee5e-42c7-9a53-ab56c98420f9\2.157.4\Modules\DTAExecutionHost.exe --inputFile d:\a\_temp\input_96a10d90-e365-11e9-9046-67324e9a5d6c.json
======================================================
##########################################################################
DtaExecutionHost version 17.157.29325.1.
Starting TestExecution Model...
Updated Run Settings:
<RunSettings>
  <RunConfiguration>
    <MaxCpuCount>0</MaxCpuCount>
    <BatchSize>1000</BatchSize>
    <ResultsDirectory>d:\a\_temp\TestResults</ResultsDirectory>
  </RunConfiguration>
</RunSettings>
```

**Comment by xdaDaveShaw** [comment]
Hi,
I can still reproduce it, to workaround the issue we added the following task:

```
  - task: VisualStudioTestPlatformInstaller@1
    inputs:
      packageFeedSelector: 'nugetOrg'
      versionSelector: 'specificVersion'
      testPlatformVersion: '16.2.0'
```
And added `vsTestVersion: 'toolsInstaller'` to our VSTest task.

If I revert this change, the problem re-occurs.

Our project is large with over 800 projects.

The test project is .NET Framework 4.5.2, using MSTest TestAdaptor 1.3.2 for running the tests.
The code that gets the AppConfig value is a .NET 4.0 DLL.

The dependencies go something like this:
```
Test -> net40/45 Project -> net40 Reading App Config -> net40 executable with app.config
```

We also build the assemblies into sub folders so following the same projects as above

```
BuildOutput\Tests -> BuildOutput\Client -> BuildOutput\Common -> BuildOutput\Client
```

If I get time I'll see if I can create a sample project that mimics this and build it.

**Comment by xdaDaveShaw** [comment]
Sorry, I'm not able to repro, every time I run these tests they fail, even with the same workaround: https://dev.azure.com/taeguk/Public/_git/TestFailures

I'm not sure what it is in a production code that makes these pass when using 16.2.0 and fail on newer versions.

**Comment by vagisha-nidhi** [comment]
I tried this project on my local box with VS with test platform version 16.2.0 and the test is still failing as you said. I will need a repro project to see what exactly is causing the failure.

**Comment by vagisha-nidhi** [comment]
Please feel free to reopen the issue with a repro.
