### ISSUE TITLE
Microsoft.NET.Test.Sdk needs the correct .net core version installed locally 

### ISSUE THREAD

**Issue by TclasenITVT** [microsoft/vstest#2209]
## Description
I have a Project that is configured to use the netcoreapp2.2 monicker. Using the latest Microsoft.NET.Test.Sdk (16.3.0) it fails in CI if the build agent hasnt installed the correct .net framework version in the default location. For our CI Build Agents we use the '.NET Core Tool Installer' Task to install .net core -> The path is then usually 

> X:\agent\_work\_tool\dncs\2.2.402\x64\dotnet.exe

This works fine for restore, build, pack, push, publish only test fails with this error:

> Test run for X:\agent\_work\143\s\TestProj\TestProj.UnitTest\bin\release\netcoreapp2.2\TestProj.UnitTest.dll(.NETCoreApp,Version=v2.2)
> Microsoft (R) Test Execution Command Line Tool Version 16.3.0
> Copyright (c) Microsoft Corporation.  All rights reserved.
> Starting test execution, please wait...
> A total of 1 test files matched the specified pattern.
> Testhost process exited with error: It was not possible to find any compatible framework version
> The specified framework 'Microsoft.NETCore.App', version '2.2.0' was not found.
>   - The following frameworks were found:
>       1.0.1 at [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
>       1.0.4 at [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
>       1.1.1 at [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
>       2.0.3 at [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
>       2.0.7 at [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
>       2.0.9 at [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
>       2.1.6 at [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
>       2.1.9 at [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
>       3.0.0 at [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
> You can resolve the problem by installing the specified framework and/or SDK.
> The .NET Core frameworks can be found at:
>   - https://aka.ms/dotnet-download
> . Please check the diagnostic logs for more information.
> Results File: F:\agent\_work\_temp\svc-tfsbuild_TFSBUILD01_2019-10-02_11_12_15.trx
> Test Run Aborted.

## Steps to reproduce
1. Get a vm that does not install the specified .net core version 2.2 in my case
2. Install the latest Version of .net core 3.0
3. Create a dotnet new xunit Project with netcoreapp2.2
4. Update to latest Microsoft.NET.Test.Sdk (16.3.0)
5. Run the test on the VM

## Expected behavior
dotnet test executes the unit tests.

## Actual behavior
The testrun is aborted stating that the correct dotnet core version is not found.

## Diagnostic logs
> Please share test platform diagnostics logs. Instructions to collect logs are [here](https://github.com/Microsoft/vstest-docs/blob/master/docs/diagnose.md#test-platform-diagnostics).  
> The logs may contain test assembly paths, kindly review and mask those before sharing.

## Environment
Windows_NT 6.3.9600
--

**Comment by singhsarab** [comment]
@TclasenITVT Can you try setting DOTNET_ROOT environment variable to point to the location for the dotnet ?

**Comment by TclasenITVT** [comment]
I could not reproduce it after we installed dotnet core 3.0.100 SDK proper. 
I then spun up a completly new agent with Version 2.155.1 there I also could not reproduce this behavior. I think it could just be something about the older Agent Version. I will close this now.

**Comment by carlin-q-scott** [comment]
I had this problem while running from VS2019 v16.4.3. I only have the 3.1.1 Microsoft.NETCore.App SDK installed. That SDK should be able to run NetCore.App v2.2. In fact, if I downgrade the Microsoft.NET.Test.Sdk package to 15.8.0, the issue goes away. That version of the Test.SDK is built against NetCore 1.

**Comment by mikesigs** [comment]
I just found this too. Microsoft.NET.Test.Sdk v 16.2.0 works fine, but 16.3.0 causes the test runner to fail to locate any tests to run. The ReSharper test hint beside a test says "Why can't I run tests?" and clicking on that shows the following error:

```
Error Microsoft.VisualStudio.TestPlatform.ObjectModel.TestPlatformException: Testhost process exited with error: It was not possible to find any compatible framework version
The framework 'Microsoft.NETCore.App', version '2.2.0' was not found.
  - The following frameworks were found:
      3.1.3 at [C:\Program Files (x86)\dotnet\shared\Microsoft.NETCore.App]
You can resolve the problem by installing the specified framework and/or SDK.
The specified framework can be found at:
  - https://aka.ms/dotnet-core-applaunch?framework=Microsoft.NETCore.App&framework_version=2.2.0&arch=x86&rid=win10-x86
. Please check the diagnostic logs for more information.
   at Microsoft.VisualStudio.TestPlatform.CrossPlatEngine.Client.ProxyOperationManager.ThrowExceptionOnConnectionFailure(Int32 connTimeout)
   at Microsoft.VisualStudio.TestPlatform.CrossPlatEngine.Client.ProxyOperationManager.SetupChannel(IEnumerable`1 sources, String runSettings)
   at Microsoft.VisualStudio.TestPlatform.CrossPlatEngine.Client.ProxyDiscoveryManager.DiscoverTests(DiscoveryCriteria discoveryCriteria, ITestDiscoveryEventsHandler2 eventHandler)
```

Also, running `dotnet --info` shows that I have the necessary SDK:

```
.NET Core SDK (reflecting any global.json):
 Version:   3.1.201
 Commit:    b1768b4ae7

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.18362
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\3.1.201\

Host (useful for support):
  Version: 3.1.3
  Commit:  4a9f85e9f8

.NET Core SDKs installed:
  2.1.608 [C:\Program Files\dotnet\sdk]
  2.1.801 [C:\Program Files\dotnet\sdk]
  2.2.206 [C:\Program Files\dotnet\sdk]
  2.2.401 [C:\Program Files\dotnet\sdk]
  3.1.201 [C:\Program Files\dotnet\sdk]

.NET Core runtimes installed:
  Microsoft.AspNetCore.All 2.1.12 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.1.15 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.1.17 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.2.6 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.2.7 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.2.8 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.App 2.1.12 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.1.15 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.1.17 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.2.6 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.2.7 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.2.8 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.1.3 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 2.1.12 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.15 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.17 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.2.6 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.2.7 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.2.8 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.1.3 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.WindowsDesktop.App 3.1.3 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
```

**Comment by nohwnd** [comment]
@mikesigs This is because in 16.3.0 the test platform started running projects in the correct bittness. It is a bit hard to see, but the runtime you are trying to resolve is a 32-bit (x86) runtime `3.1.3 at [C:\>>>Program Files (x86)<<<<\dotnet\shared\Microsoft.NETCore.App`. 
While the long list is showing all your x64 runtimes (including 2.2) `Microsoft.NETCore.App 2.2.8 [C:\>>>Program Files<<<\dotnet\shared\Microsoft.NETCore.App]`. 

The error is correct you don't have a 2.2.0 x86 runtime. To confirm that please run: 

```shell
# powershell
 & "C:\Program Files (x86)\dotnet\dotnet.exe" --info

# or cmd 
"C:\Program Files (x86)\dotnet\dotnet.exe" --info
```

**Comment by holytshirt** [comment]
This is really annoying. The Visual Studio Test Explorer defaults to CPU Architecture x86. 
Once I change it to auto the tests run. 
**x86 is a terrible default!**
![image](https://user-images.githubusercontent.com/90132/83870499-48312e80-a726-11ea-8958-39e463b70ebc.png)

**Comment by nohwnd** [comment]
@peterwald is it true that we default to x86, and is there a reason to prefer it over Auto / x64?

**Comment by peterwald** [comment]
> @peterwald is it true that we default to x86, and is there a reason to prefer it over Auto / x64?

The Test Explorer defaults to Auto if not specified. In this case it was probably set at some point in the past (maybe inadvertently).

**Comment by holytshirt** [comment]
This was a brand new win10 2004 install and first time I ran the tests in a fresh VS install, fresh cloned repo. Unless that is a profile option which is synced or a project setting?

**Comment by mikesigs** [comment]
In order to make this work with the ReSharper test runner I have to force my test assemblies to only target x64. If I have the platform target set to "Any CPU" shouldn't it build both x86 and x64? Leaving the target as "Any CPU" and telling ReSharper to use x64 still doesn't work, which I don't know if that's a ReSharper bug, or related to something else.

At any rate. This is all very intuitive, and doesn't seem like a great default behavior.

**Comment by mikesigs** [comment]
Can we please re-open this issue. It's not great that this is a default behavior out of the box with a default install of Visual Studio and .NET Core.

**Comment by nohwnd** [comment]
@peterwald do you want to transfer  this issue somewhwere more appropriate?

**Comment by peterwald** [comment]
It's not clear to me that this is actually a problem with Visual Studio. Maybe this could be an issue with Resharper. 

When assemblies are compiled as AnyCPU, they will run on either x86 or x64 runtimes. If the Auto setting is chosen (which is also the current VS default), then dotnet core tests will be run on the x64 dotnet runtime.

**Comment by aalmada** [comment]
I'm getting the same error when running **GitHub Actions**. My unit testing project targets `net461`, `netcoreapp2.1`, `netcoreapp3.1`, and `net5.0`. I get the following errors:

```
Test run for D:\a\NetFabric.Hyperlinq\NetFabric.Hyperlinq\NetFabric.Hyperlinq.UnitTests\bin\Debug\netcoreapp2.1\NetFabric.Hyperlinq.UnitTests.dll(.NETCoreApp,Version=v2.1)
Microsoft (R) Test Execution Command Line Tool Version 16.8.0-preview-20200811-01
Copyright (c) Microsoft Corporation.  All rights reserved.

Starting test execution, please wait...
A total of 1 test files matched the specified pattern.
Testhost process exited with error: It was not possible to find any compatible framework version
The framework 'Microsoft.NETCore.App', version '2.1.0' was not found.
  - The following frameworks were found:
      5.0.0-preview.8.20407.11 at [C:\hostedtoolcache\windows\dncs\5.0.100-preview.8.20417.9\x64\shared\Microsoft.NETCore.App]
You can resolve the problem by installing the specified framework and/or SDK.
The specified framework can be found at:
  - https://aka.ms/dotnet-core-applaunch?framework=Microsoft.NETCore.App&framework_version=2.1.0&arch=x64&rid=win10-x64
. Please check the diagnostic logs for more information.

Test Run Aborted.
C:\hostedtoolcache\windows\dncs\5.0.100-preview.8.20417.9\x64\sdk\5.0.100-preview.8.20417.9\Microsoft.TestPlatform.targets(32,5): error MSB4181: The "Microsoft.TestPlatform.Build.Tasks.VSTestTask" task returned false but did not log an error. [D:\a\NetFabric.Hyperlinq\NetFabric.Hyperlinq\NetFabric.Hyperlinq.UnitTests\NetFabric.Hyperlinq.UnitTests.csproj]

Test run for D:\a\NetFabric.Hyperlinq\NetFabric.Hyperlinq\NetFabric.Hyperlinq.UnitTests\bin\Debug\netcoreapp3.1\NetFabric.Hyperlinq.UnitTests.dll(.NETCoreApp,Version=v3.1)
Microsoft (R) Test Execution Command Line Tool Version 16.8.0-preview-20200811-01
Copyright (c) Microsoft Corporation.  All rights reserved.

Starting test execution, please wait...
A total of 1 test files matched the specified pattern.
Testhost process exited with error: It was not possible to find any compatible framework version
The framework 'Microsoft.NETCore.App', version '3.1.0' was not found.
  - The following frameworks were found:
      5.0.0-preview.8.20407.11 at [C:\hostedtoolcache\windows\dncs\5.0.100-preview.8.20417.9\x64\shared\Microsoft.NETCore.App]
You can resolve the problem by installing the specified framework and/or SDK.
The specified framework can be found at:
  - https://aka.ms/dotnet-core-applaunch?framework=Microsoft.NETCore.App&framework_version=3.1.0&arch=x64&rid=win10-x64
. Please check the diagnostic logs for more information.

Test Run Aborted.
C:\hostedtoolcache\windows\dncs\5.0.100-preview.8.20417.9\x64\sdk\5.0.100-preview.8.20417.9\Microsoft.TestPlatform.targets(32,5): error MSB4181: The "Microsoft.TestPlatform.Build.Tasks.VSTestTask" task returned false but did not log an error. [D:\a\NetFabric.Hyperlinq\NetFabric.Hyperlinq\NetFabric.Hyperlinq.UnitTests\NetFabric.Hyperlinq.UnitTests.csproj]
```

I'm using `windows-latest` with the following to install .NET 5.0:

``` yaml
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1.6.0
      with:
        dotnet-version: 5.0.100-preview.8
```

It was working previously. I don't know what changed. Here I bumped to all the latest versions to see if it would fix the issue but it doesn't...

**Comment by pedramrezaei** [comment]
I am having the same exact issue on github actions with .NET 5

**Comment by nohwnd** [comment]
@aalmada @pedramrezaei  your environment does not have all the runtimes that you need. You are building your project via the net5.0 SDK and target netcoreapp2.1, netcoreapp3.1 and net5.0. Net5.0 SDK has runtime for net5.0, but does not have runtime for 3.1 and 2.1. You need to either install those runtimes, or allow the host resolver to roll forward to a newer major version (by setting it to `2`) which will use the 5.0 runtime. This kinda loses the purpose of running the multitargeted tests though. 

```
DOTNET_ROLL_FORWARD_ON_NO_CANDIDATE_FX=2

Disables minor version roll forward, if set to 0. 
For more information, see Roll forward.

This setting is superseded in .NET Core 3.0 by DOTNET_ROLL_FORWARD. 
The new settings should be used instead.
```

https://docs.microsoft.com/cs-cz/dotnet/core/tools/dotnet#environment-variables

**Comment by pensono** [comment]
I'm having the same issue as @aalmada and @pedramrezaei. It seems to be related to https://github.com/actions/setup-dotnet/issues/136. As a workaround, I install both the SDK I build with and the SDK which the tests/project target, in my case 5.0 and 3.1
