### ISSUE TITLE
2 years later profiling of unit tests is not supported for .Net Core framework

### ISSUE THREAD

**Issue by dimant** [microsoft/vstest#2222]
## Description
see title

## Steps to reproduce
try to profile any unit test in a .net core framework project

## Expected behavior
profiling works

## Actual behavior
profiling doesn't work

## Environment
Visual Studio 2019 version 16.3.3

**Comment by vagisha-nidhi** [comment]
@dimant This is a VS IDE issue. Please file the issue on developer community https://developercommunity.visualstudio.com/content/problem/post.html?space=8. We won't be tracking IDE issues on this platform.
