### ISSUE TITLE
When changing the build configuration in MSBuild Task from Debug to Release, tests dont run

### ISSUE THREAD

**Issue by camerontbelt** [microsoft/vstest#2230]
## Description
> **IMPORTANT**: if the defect is reproduced only in a workflow from within the Visual Studio IDE then do not report the issue here - instead, please report it using Visual Studio's "Send Feedback" option that can be accessed from the Help menu OR using this link https://developercommunity.visualstudio.com.
>
> For a defect reproducable from the vstest command line, describe the issue you've observed.

## Steps to reproduce
As the title says, when I changed the build configuration from Debug to Release, this caused my tests not to run in the VSTest task on azure dev ops. I changed the build configuration back to Debug and the tests still will not run. 

## Expected behavior
I expect the tests to run no matter what the build configuration is. 

## Actual behavior
Only runs in debug and if its changed they no longer run no matter if its changed back to debug. 

## Diagnostic logs
[Tests run on this release ReleaseLogs_211.zip](https://github.com/microsoft/vstest/files/3763919/ReleaseLogs_211.zip)

[Tests do not run on this release ReleaseLogs_217.zip](https://github.com/microsoft/vstest/files/3763925/ReleaseLogs_217.zip)

## Environment
Azure Dev Ops

**Comment by singhsarab** [comment]
@camerontbelt Can you please make you are doing a clean build, and there are no stale built binaries ?

**Comment by ShreyasRmsft** [comment]
Closing due to no response, please re-open after trying following the suggestion mentioned above and if issue persists.
