### ISSUE TITLE
.NET Core 1.0 no longer supported by Microsoft.NET.Test.Sdk?

### ISSUE THREAD

**Issue by thomaslevesque** [microsoft/vstest#2231]
## Description

[Microsoft.NET.Test.Sdk 16.3.0](https://www.nuget.org/packages/Microsoft.NET.Test.Sdk/16.3.0) claims it supports netcoreapp1.0, but it depends on [Microsoft.TestPlatform.TestHost 16.3.0](https://www.nuget.org/packages/Microsoft.TestPlatform.TestHost/16.3.0), which only supports netcoreapp2.1.

## Steps to reproduce
- In a test project targeting netcoreapp1.0, upgrade to the latest version (16.3.0) of Microsoft.NET.Test.Sdk.
- restore packages

## Expected behavior

Restore should succeed, as it did with 16.2.0

## Actual behavior

Restore fails:

```
...\MyProject.csproj : warning NU1701: Package 'Microsoft.TestPlatform.TestHost 16.3.0' was restored using '.NETFramework,Version=v4.6.1, .NETFramework,Version=v4.6.2, .NETFramework,Version=v4.7, .NETFramework,Version=v4.7.1, .NETFramework,Version=v4.7.2, .NETFramework,Version=v4.8' instead of the project target framework '.NETCoreApp,Version=v2.0'. This package may not be fully compatible with your project.
...\MyProject.csproj : error NU1202: Package Microsoft.TestPlatform.TestHost 16.3.0 is not compatible with netcoreapp1.0 (.NETCoreApp,Version=v1.0). Package Microsoft.TestPlatform.TestHost 16.3.0 supports:
...\MyProject.csproj : error NU1202:   - net45 (.NETFramework,Version=v4.5)
...\MyProject.csproj : error NU1202:   - netcoreapp2.1 (.NETCoreApp,Version=v2.1)
...\MyProject.csproj : error NU1202:   - uap10.0 (UAP,Version=v10.0)
```

## Diagnostic logs
N/A

## Environment
Windows 10, .NET Core SDK 3.0.100

**Comment by buvinghausen** [comment]
For the time being you can use conditions to reference 16.2.0 for the lower level frameworks

```xml
<ItemGroup Condition="'$(TargetFramework)' == 'net452' or '$(TargetFramework)' == 'netcoreapp2.0' or '$(TargetFramework)' == 'netcoreapp1.1' or '$(TargetFramework)' == 'netcoreapp1.0'">
  <PackageReference Include="Microsoft.NET.Test.Sdk" Version="16.2.0" />
</ItemGroup>
<ItemGroup Condition="'$(TargetFramework)' == 'netcoreapp3.0' or '$(TargetFramework)' == 'netcoreapp2.2' or '$(TargetFramework)' == 'netcoreapp2.1'">
  <PackageReference Include="Microsoft.NET.Test.Sdk" Version="16.3.0" />
</ItemGroup>
```

**Comment by thomaslevesque** [comment]
Thanks @buvinghausen 

> For the time being

What do you mean? Is this going to change in a future release?

**Comment by buvinghausen** [comment]
@thomaslevesque I can't speak to what Microsoft's long term strategy here is but in the event they do fix it backwards you can then go back to a normal package reference...

**Comment by buvinghausen** [comment]
@thomaslevesque just as a follow up so that you're not maintaining two condition statements I have moved to using the choose .. when .. otherwise element to set the reference to the correct test SDK.

`  <Choose>
    
    <When Condition="'$(TargetFramework)' == 'netcoreapp2.0' or '$(TargetFramework)' == 'netcoreapp1.1' or '$(TargetFramework)' == 'netcoreapp1.0'">
      <ItemGroup>
        <PackageReference Include="Microsoft.NET.Test.Sdk" Version="16.2.0" />
      </ItemGroup>
    </When>
    <Otherwise>
      <ItemGroup>
        <PackageReference Include="Microsoft.NET.Test.Sdk" Version="16.4.0" />
      </ItemGroup>
    </Otherwise>
  </Choose>`

**Comment by thomaslevesque** [comment]
Thanks @buvinghausen

**Comment by singhsarab** [comment]
Here is the official support page for reference https://dotnet.microsoft.com/platform/support/policy/dotnet-core 

And the recommendation is to bump up the target framework, or to have a reference to older version of the Microsoft.NET.Test.Sdk

**Comment by thomaslevesque** [comment]
@singhsarab thanks, but the problem is not really solved... The package is still lying about which framework it supports. It says that it supports netcoreapp1.0, but it's not true.
