### ISSUE TITLE
No tests discovered for C++ UWP project in Release x64 configuration

### ISSUE THREAD

**Issue by mcooley** [microsoft/vstest#2233]
## Repro steps:
- In Visual Studio (tested with VS 16.3.6), create a new Unit Test App (Universal Windows - C++/CX) project.
- Set the configuration to "Release" and the platform to "x64"
- "Run All" in test explorer.
- No tests are discovered. Test output window says "No tests found to run."
- Note that in x86 or Debug configurations, the test runs and passes.

The same behavior occurs when the tests are run with vstest.console.exe. [Diagnostic logs are here.](https://gist.github.com/mcooley/e34bcf3b96f87d291b82029c4862032b)

**Comment by mayankbansal018** [comment]
Sorry Matt, it took this long to finally narrow down this issue. I’m adding you to original thread we are tracking internally. I'm closing the issue here, hope that would be okay.
