### ISSUE TITLE
Question: is roll-forward available in dotnet vstest commandline?

### ISSUE THREAD

**Issue by heng-liu** [microsoft/vstest#2237]
dotnet commandline has a --roll-forward parameter to choose the runtime pick policy.
https://github.com/dotnet/designs/blob/master/accepted/runtime-binding.md#rollforward

May I know if "dotnet vstest" is able to use this "--roll-forward" parameter? Thanks!

**Comment by singhsarab** [comment]
@heng-liu No it does not.

**Comment by heng-liu** [comment]
Thanks Sarabjot.

**Comment by singhsarab** [comment]
@heng-liu Closing the issue, let me know if you want to keep it open.
