### ISSUE TITLE
"No test is available" when change TFM from netcoreapp3.0 to netcoreapp5.0

### ISSUE THREAD

**Issue by heng-liu** [microsoft/vstest#2238]
## Description
Our testing projects work well on Linux when TFM is netcoreapp3.0.
Recently we changed testing projects  TFM from netcoreapp3.0 to netcoreapp5.0, to use latest feature that only in netcoreapp5.0.
We installed SDK 5.0 daily builds from [here](https://github.com/dotnet/core-sdk)(Linux-x64 version)
We build the testing projects (we use global.json to specify version 5.0.100-alpha1).
And the build is successful. I checked ./bin/Debug/netcoreapp5.0/ has dlls generated.
But when I tried to run the tests by:
`dotnet vstest ./bin/Debug/netcoreapp5.0/test.dll`
The result is:
```
Microsoft (R) Test Execution Command Line Tool Version 16.3.0-preview-20190911-02
Copyright (c) Microsoft Corporation.  All rights reserved.

Starting test execution, please wait...

A total of 1 test files matched the specified pattern.

No test is available in /home/####/bin/Debug/netcoreapp5.0/NuGet.Packaging.FuncTest.dll. Make sure that test discoverer & executors are registered and platform & framework version settings are appropriate and try again.

Additionally, path to test adapters can be specified using /TestAdapterPath command. Example  /TestAdapterPath:<pathToCustomAdapters>.
```
Pls let me know if any other info is needed. Thanks!

**Comment by ShreyasRmsft** [comment]
For running tests using dotnet vstest you need to ensure that the test project is published.

Take a look at https://docs.microsoft.com/en-us/dotnet/core/tools/dotnet-publish?tabs=netcore21

**Comment by jayaranigarg** [comment]
@heng-liu : Any update on this?

**Comment by vagisha-nidhi** [comment]
@heng-liu Closing the issue for now. Please reopen if this is still happening.
