### ISSUE TITLE
Microsoft.VisualStudio.Coverage.Analysis is not a well-structured nuget package

### ISSUE THREAD

**Issue by dfederm** [microsoft/vstest#2239]
## Description
Microsoft.VisualStudio.Coverage.Analysis is not a well-structured nuget package.

Specifically, there are no dlls under the `lib\net45` dir in the package. Instead, the dlls are under subdirectories there, which make it incorrectly structured.

My guess is that these dlls are separated by architecture for the sole purpose of pointing to the correct native assembly. In that case there should still only be one managed assembly and the correct native assembly should be dynamically chosen.

## Steps to reproduce
Add a PackageReference to Microsoft.VisualStudio.Coverage.Analysis

## Expected behavior
The package restores successfully.

## Actual behavior
```
Package Microsoft.VisualStudio.Coverage.Analysis 16.0.28704 is not compatible with net472 (.NETFramework,Version=v4.7.2). Package Microsoft.VisualStudio.Coverage.Analysis 16.0.28704 does not support any target frameworks.
```

## Diagnostic logs
N/A

## Environment
N/A

**Comment by mayankbansal018** [comment]
Please use package https://dev.azure.com/mseng/Domino/_packaging?_a=package&feed=VsTest-CloudBuild&package=Microsoft.VisualStudio.Coverage.Analysis&protocolType=NuGet&version=16.0.29510&view=overview
