### ISSUE TITLE
Few unit tests are taking infinite time and requires cancelling the test run

### ISSUE THREAD

**Issue by harshjain2** [Microsoft/vstest#224]
## Description
> After migrating from xproj to csproj, few UTs are taking infinite time for execution, test run has to be stopped. 

## Steps to reproduce
> Tests showing this behaviour :
> 1. EnableDiagArgumentProcessorExecutorShouldCreateDirectoryOfLogFileIfNotExists

> Clone repo https://github.com/harshjain2/vstest and checkout branch migrate2.
> Remove tag [Ignore] from any of the above mentioned tests. 
> Run command dotnet test [ProjectName].csproj.

## Expected behavior
> Tests should complete successfully.

## Actual behavior
> Test execution is stuck. 

## Environment
> Please share additional details about the test environment.
> Operating system, Build version of vstest.console

Product Information:
 Version:            1.0.0-preview3-004056
 Commit SHA-1 hash:  ccc4968bc3

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.14393
 OS Platform: Windows
 RID:         win10-x64

**Comment by sbaid** [comment]
@harshjain2  pl update for the latest build

**Comment by harshjain2** [comment]
@sbaid Same behavior is observed when running this command :
`.\tools\dotnet\dotnet.exe test .\test\vstest.console.UnitTests\vstest.console.UnitTests.csproj `
