### ISSUE TITLE
Microsoft.TestPlatform.Portable vstest.console.dll does not run on netcore sdk 3.0.x

### ISSUE THREAD

**Issue by Mobrockers** [microsoft/vstest#2240]
## Description
At stryker-net we are trying to implement rollForwardOnNoCandidateFx so that consumers don't have to install .netcore sdk 2.1 in their build every run (assuming no breaking changes) but as soon as we allow rollForwardOnNoCandidateFx to major versions we can no longer attach to vstest.console.dll from stryker. I have tried to pass rollForwardOnNoCandidateFx to vstest.console.dll as well through a custom ITestHostLauncher as environment variable but this does not have the desired effect.

Can anyone tell us whether or not vstest.console.dll from Microsoft.TestPlatform.Portable is supposed to be able to be started on a netcore sdk 3.0 only system and if not if it's possible to use rollForwardOnNoCandidateFx to force allow a major version roll forward?

## Steps to reproduce
See: https://dev.azure.com/stryker-mutator/Stryker/_build/results?buildId=3054&view=logs&j=59ee5473-4355-59e8-3cdb-05fe186645bf&t=d4aceccd-e7de-59e6-f3ce-e57273708193&l=62
And: https://github.com/stryker-mutator/stryker-net/pull/786

## Expected behavior
vstest.console.dll starts up and can be connected to through translationlayer client

## Actual behavior
There is no logging available (even though it is turned on) so I assume vstest.console.dll fails to start up

## Diagnostic logs
No logging available so I assume vstest.console.dll fails to start

## Environment
Azure pipelines Microsoft hosted agent (ubuntu-latest, macos-latest)
Microsoft.TestPlatform.Portable 16.3.0 vstest.console.dll

**Comment by singhsarab** [comment]
You can try setting an environment variable (VSTEST_RUNNER_DEBUG=1) to make sure we know for sure.
This flag helps break the vstest.console at the start.

**Comment by Mobrockers** [comment]
I set the VSTEST_RUNNER_DEBUG=1 environment variable which caused my unit tests starting using azure pipelines vstest task to halt (wait for debugger attach) but the vstest instance I start from the translationlayer client using the vstest.console.dll from the portable nuget package does not seem to halt or log anything

**Comment by singhsarab** [comment]
@Mobrockers It is in the main itself, so should break for any flow
https://github.com/microsoft/vstest/blob/06101ef5feb95048cbe850472ed49604863d54ff/src/vstest.console/Program.cs#L22

**Comment by singhsarab** [comment]
@Mobrockers If there is no break, that means we are not even trying to start the exe, is there any exception while initializing the translation layer?

**Comment by Mobrockers** [comment]
Yes sorry I linked to the build pipeline with the exception but I understand you would rather not have to go search for it. The exception is a timeout failure to connect, this does not happen on dotnet core 2.1 runtime, only on dotnet core 3.0. This is why I think starting the exe is failing:

```
---> Microsoft.TestPlatform.VsTestConsole.TranslationLayer.TransationLayerException: /home/vsts/.dotnet/tools/dotnet-stryker process failed to connect to vstest.console process after 90 seconds. This may occur due to machine slowness, please set environment variable VSTEST_CONNECTION_TIMEOUT to increase timeout.
   at Microsoft.TestPlatform.VsTestConsole.TranslationLayer.VsTestConsoleWrapper.WaitForConnection()
   at Microsoft.TestPlatform.VsTestConsole.TranslationLayer.VsTestConsoleWrapper.EnsureInitialized()
   at Microsoft.TestPlatform.VsTestConsole.TranslationLayer.VsTestConsoleWrapper.InitializeExtensions(IEnumerable`1 pathToAdditionalExtensions)
   at Stryker.Core.TestRunners.VsTest.VsTestRunner.InitializeVsTestConsole()
   --- End of inner exception stack trace ---

```

**Comment by Mobrockers** [comment]
@singhsarab Anything else I can test or any other data I can provide you with?

**Comment by nohwnd** [comment]
@Mobrockers Sorry for the delayed response, I am taking over this issue. The original build is no longer available, is there a different build that I could inspect and learn more about the failure?

**Comment by Mobrockers** [comment]
Hey @nohwnd no problem, thank you for taking a look!

I started a new pipeline run for you here: https://dev.azure.com/stryker-mutator/Stryker/_build/results?buildId=3448

I can provide you with any information or changes required

**Comment by nohwnd** [comment]
@Mobrockers Ahhh. In your code you still have the VSTEST_RUNNER_DEBUG set to 1, that is why the build shows timeout. (The console waits for debugger to be attached and stryker times out. There is no output but I can use procexp to see the process running, and waiting.) 

I don't see your previous build and I can't change your branch (as far as I know) to get back to state that does not time out. 

In my local tests it seems that everything works fine with the roll forward. Here is what I am doing in form of powershell script. Hope it will help you debug this. 

```powershell 
# !!! build your cli solution first
$projectPath = "C:\Projects\temp\stryker-net"

# get a local copy of dotnet 3.1.100
$install = [ScriptBlock]::Create((Invoke-RestMethod -Method Get 'https://dot.net/v1/dotnet-install.ps1'))
& $install -Version 3.1.100 -InstallDir "$projectPath\tools\3.1\"

# change this to 0 or 1 to see it fail to resolve runtime for netcoreapp2.1
# to confirm your setup
$env:DOTNET_ROLL_FORWARD_ON_NO_CANDIDATE_FX=2
# keep this 0 to disable using shared sdks
$env:DOTNET_MULTILEVEL_LOOKUP=0
# keep this 0 to disable waiting for debugger and timing out
$env:VSTEST_RUNNER_DEBUG=0
# set PATH to resolve only to a local copy of dotnet 
# (and also to be able to find git)
$env:PATH="$projectPath\tools\3.1;C:\Program Files\Git\cmd;$(gi ~\.dotnet\tools).FullName"

# run it from the built dll
cd "$projectPath\integrationtest\TargetProjects\NetCoreTestProject.XUnit"
dotnet "$projectPath\src\Stryker.CLI\Stryker.CLI\bin\Debug\netcoreapp2.1\Stryker.CLI.dll"

# or from the tools folder 
cd "$projectPath\integrationtest\TargetProjects\NetCoreTestProject.XUnit"
& "~\.dotnet\tools\dotnet-stryker.exe" --dev-mode -f -l trace

# running it like this fails because it can't see it as installed,
# but it should not change anything
dotnet stryker --dev-mode -f -l trace
```

In both cases I see the mutation report and no failure, which to me seems like succeess, but I don't know much about stryker:

![image](https://user-images.githubusercontent.com/5735905/70921181-17e4bf00-2024-11ea-85fe-1c0c91a8521b.png)

Please try out the outlined steps, and if it still does not work, please fix the branch so I can see the real failure. 🙂

**Comment by Mobrockers** [comment]
Thank you for taking a look, and you are right I forgot to remove that again. I am running a new build without the debug lines.

**Comment by nohwnd** [comment]
Tried to reproduce this in WSL2 on Ubuntu LTS and I get this strange error on the test project. Do you see something the I do obivously wrong? 

![image](https://user-images.githubusercontent.com/5735905/71191287-698c8400-2286-11ea-8c53-0d4957590ccd.png)

**Comment by Mobrockers** [comment]
Could you show me what kind of system dotnet reports your system as from RuntimeInformation.IsOSPlatform ? It looks like it failed to deploy the correct vstest binary for your target platform.

**Comment by nohwnd** [comment]
`Console.WriteLine($"{RuntimeInformation.OSDescription} {RuntimeInformation.OSArchitecture} is linux: {RuntimeInformation.IsOSPlatform(OSPlatform.Linux)}");`

`Linux 4.19.84-microsoft-standard #1 SMP Wed Nov 13 11:44:37 UTC 2019 X64 is linux: True`

**Comment by Mobrockers** [comment]
This is the line it's crashing on:

https://github.com/stryker-mutator/stryker-net/blob/d26e5b6880934801066272d2511f1734490b6c5d/src/Stryker.Core/Stryker.Core/ToolHelpers/VsTestHelper.cs#L194

It looks like for some reason the assembly does not contain the vstest zip. Was this a local build or the package from our azure devops build?

Because packaging the vstest binary is a bit tricky, the deployable zip is packaged in our release pipeline. For local development we use the on-disk version from the nuget cache collected here:

https://github.com/stryker-mutator/stryker-net/blob/d26e5b6880934801066272d2511f1734490b6c5d/src/Stryker.Core/Stryker.Core/ToolHelpers/VsTestHelper.cs#L174

If this was a local build of stryker, perhaps the vstest portable package is not available in your nuget cache for some reason.

**Comment by nohwnd** [comment]
Okay, two problems I had here, you are looking for USERNAME and NUGET_PACKAGES env variables, none of which were defined on my system (Consider switching on USERNAME for win and HOME for non-windows, maybe?), secondly my nuget cache has vstest console based on netcoreapp2.1 and you look for netcoreapp2.0.

**Comment by nohwnd** [comment]
Think I got it, the problem is that you are launching the console via the console wrapper, there you are not providing any env variable and so it does not know that it should roll forward. The api there does not allow you to pass the variable as far as I can see, but the nice thing about env variables is that they are inherited from the parent process. So to fix this you simply need to set the variable to you environment and every process spawned should inherit it. 

One place where it definitely works is setting it in `InitializeVsTestConsole`, but setting right after the process starts should also do the job: 

```csharp
Environment.SetEnvironmentVariable("DOTNET_ROLL_FORWARD_ON_NO_CANDIDATE_FX", "2");
_vsTestConsole.StartSession();
```

**Comment by Mobrockers** [comment]
I am passing the env variable to the testhost, does the testhost not pass them on to the vstest.console dll? See:

https://github.com/stryker-mutator/stryker-net/pull/786/files#diff-6047aae96dc8fe74725299152ea52c58R34

**Comment by Mobrockers** [comment]
@nohwnd 

https://dev.azure.com/stryker-mutator/Stryker/_build/results?buildId=3512&view=results

😍😍😍😍😍😍😍😍😍😍

Thank you!!!!

**Comment by nohwnd** [comment]
👏👏👏👏👏
