### ISSUE TITLE
Error "Could not load file or assembly" after changing Microsoft.Dynamics365.UIAutomation.Sample.dll with Powershell

### ISSUE THREAD

**Issue by yohanosullivan** [microsoft/vstest#2242]
## Description
I am trying to use the Visual Stuidio Test task to run some tests stored in the Repos. However i want to update the tests config file mid-pipeline using Azure Devops powershell task ( to pass in login parameters) 

I have stored my sample tests in the Repos for Azure DevOps . The tests use a config file (for example “Microsoft.Dynamics365.UIAutomation.Sample.dll.config”) to store values such as username , URL and password. This is hardcoded usually. 

I plan to use set the logins to generic strings in the config file and then replace these strings using powershell as a task before running the Visual studio test. 

## Steps to reproduce
> Upload the Easyrepro tests DLLs found at https://github.com/microsoft/EasyRepro into your Repos as well as upload the config file Microsoft.Dynamics365.UIAutomation.Sample.dll.config
> Edit the Microsoft.Dynamics365.UIAutomation.Sample.dll.config so that the values are easily identifiable 
    <add key="OnlineUsername" value="admin@username_to_be_replaced.onmicrosoft.com" />
    <add key="OnlinePassword" value="password_to_be_replaced" />
    <add key="OnlineCrmUrl" value="https://URL_to_be_replaced.crm4.dynamics.com/" />

> Create a pipeline that uses powershell to replace these keys with other viable logins

$currentDirectory = Convert-Path .
$filepath = $currentDirectory +"\Microsoft.Dynamics365.UIAutomation.Sample.dll.config"
$file = Get-Content -path $filepath -Raw
(Get-Content $filepath ).Replace('username_to_be_replaced','RealUsername') | Out-File $filepath 
(Get-Content $filepath ).Replace('URL_to_be_replaced','RealURL') | Out-File $filepath 
(Get-Content $filepath ).Replace('password_to_be_replaced','RealPassword') | Out-File $filepath 
Get-Content -path $filepath -Raw

>Add a second task - Visual Studio Test and reference/call the test DLLs you have uploaded. 
> Run pipeline

## Expected behavior
> The powershell should update the config file and the tests should run , using these new values to be able to successfully login. 

## Actual behavior
> Powershell does seem to update the config file
> Visual Studio Test does not seem to be able to initialize any of the tests - they all throw up errors

MSTestAdapter failed to discover tests in class 'Microsoft.Dynamics365.UIAutomation.Sample.TestSettings' of assembly 'D:\a\1\s\Microsoft.Dynamics365.UIAutomation.Sample.dll'. Reason Could not load file or assembly 'Microsoft.VisualStudio.QualityTools.UnitTestFramework, Version=10.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' or one of its dependencies. Exception from HRESULT: 0x80131902.
MSTestAdapter failed to discover tests in class 'Microsoft.Dynamics365.UIAutomation.Sample.UCIAppName' of assembly 'D:\a\1\s\Microsoft.Dynamics365.UIAutomation.Sample.dll'. Reason Configuration system failed to initialize.

## Diagnostic logs
With diagnostics
[log_6_207.zip](https://github.com/microsoft/vstest/files/3805250/log_6_207.zip)

Without Diagnostics 
[log_6_206.zip](https://github.com/microsoft/vstest/files/3805251/log_6_206.zip)

**Comment by ShreyasRmsft** [comment]
@yohanosullivan you can consider using the test run parameters in a runsettings file and then overriding them using vstest task input field name "override test run params".

docs for vstest task inputs here https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/test/vstest?view=azure-devops

Runsettings docs for TestRunParamters here https://docs.microsoft.com/en-us/visualstudio/test/configure-unit-tests-by-using-a-dot-runsettings-file?view=vs-2019#example-runsettings-file

**Comment by yohanosullivan** [comment]
This worked a treat, thank you @ShreyasRmsft
