### ISSUE TITLE
Custom Test Logger registration fails silently if the custom logger doesn't have the ExtensionURI attribute

### ISSUE THREAD

**Issue by bakester14** [microsoft/vstest#2254]
## Description
After implementing a custom VSTest logger according to the docs [here](https://github.com/microsoft/vstest-docs/blob/master/docs/report.md), trying to register it via Friendly or Assembly-qualified name to VSTest.console.exe fails with a misleading error message.

## Steps to reproduce
In a new solution, implement a basic test logger following the instructions in the doc linked above. (No need to implement any event handling, just need an `Initialize` method to compile.) Name it CustomLogger, give it a FriendlyName attribute like this: `[FriendlyName("CustomLogger")]`, and add `<AssemblyName>CustomLogger.testlogger</AssemblyName>` to the right place in the .csproj file. Then run the following command: `vstest.console.exe <path to any test binary> --testadapterpath:<path to directory where your custom logger binary is> --logger:CustomLogger`

## Expected behavior
VSTest should run, register the logger correctly, and send events to that logger (if implemented). If I spelled something wrong or got it wrong, it should give a clear error instead about the nature of the problem (in this case, that I didn't implement `ExtensionUri`).

## Actual behavior
VSTest fails with the following error: `Could not find a test logger with AssemblyQualifiedName, URI or FriendlyName 'CustomLogger'.`

## Diagnostic logs
N/A (I think)

## Environment
Version 16.5.0-dev of vstest.console, Windows 10

**Comment by bakester14** [comment]
I did some digging on this and I think I found an issue, editing this comment to show the results of that dig, but wanted to post it before I finish writing in case anyone is reviewing this before I finish

**Comment by hvinett** [comment]
@bakester14 ,We added the  error message in logs .You can find the changes [here](https://github.com/microsoft/vstest/pull/2264 )
