### ISSUE TITLE
How to exclude mutiple tests based on their fully qualified names

### ISSUE THREAD

**Issue by himajan** [microsoft/vstest#2257]
## Description
I am trying to exclude certain tests using FullyQualifiedName test filter criteria using vstest.console.exe. Is this supported?
Eventually I want to use this filter in the Azure DevOps VsTest task. But, looks like FullyQualifiedName only allows one test to exclude.

I tried many different combinations like below:

C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\Common7\IDE\Extensions\TestPlatform\vstest.console.exe" MyDateTimeTest.Proect1.exe /TestCaseFilter:FullyQualifiedName!=MyNameSpace.ClassName1.Test1, MyNameSpace.ClassName2.Test2

C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\Common7\IDE\Extensions\TestPlatform\vstest.console.exe" MyDateTimeTest.Proect1.exe /TestCaseFilter:FullyQualifiedName!=MyNameSpace.ClassName1.Test1&MyNameSpace.ClassName2.Test2

C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\Common7\IDE\Extensions\TestPlatform\vstest.console.exe" MyDateTimeTest.Proect1.exe /TestCaseFilter:FullyQualifiedName!=MyNameSpace.ClassName1.Test1&FullyQualifiedName!=MyNameSpace.ClassName2.Test2

I tried many other combinations like using quotes, with out quotes using &, | etc.

## Steps to reproduce
1. Create a test project and add three or more tests.
2. Now, exclude atleast 2 tests using their FullyQualifiedName (with out using any Test Category or priority)

## Expected behavior
Should be able to exclude tests using their FullyQualifiedName

## Actual behavior
Only the first tests supplied to the FullyQualifiedName!= filter is skipped, other tests are not skipped.

**Comment by hvinett** [comment]
Hey @himajan ,
Can you try this 
```/TestCaseFilter:"FullyQualifiedName!=MyNameSpace.ClassName1.Test1&FullyQualifiedName!=MyNameSpace.ClassName2.Test2" ``` and see?

**Comment by himajan** [comment]
Hi Vineeth,

I already tried this and even this did not work. Only the first test in the filter criteria is getting skipped.

Thanks,
Himaja

**Comment by hvinett** [comment]
Hey @himajan ,
Can you provide the sample project and the command that you have tried ?

**Comment by ShreyasRmsft** [comment]
@himajan any updates here?

**Comment by ShreyasRmsft** [comment]
Closing due to no response please re-open with the requested data.
