### ISSUE TITLE
 Same test case running fast for .NET Core App 2.0, but can't finish for .NET Core App 3.0 at low memory VM

### ISSUE THREAD

**Issue by xuzhg** [microsoft/vstest#2258]
## Description

I have test projects both targeting .NET Core App 2.0 and .NET Core App 3.0

Total test cases number is > 7700.

If i run dotnet test to run the test cases for both target framework:

![image](https://user-images.githubusercontent.com/9426627/69685371-00439780-1071-11ea-95a8-a395a2e5da2f.png)

the test for 2.0 is finished quickly, but the 3.0 can't finished. 

![image](https://user-images.githubusercontent.com/9426627/69685449-40a31580-1071-11ea-8c2d-5a03b4d6bad4.png)

## Steps to reproduce

The running machine is a VM as following information:

![image](https://user-images.githubusercontent.com/9426627/69685186-611ea000-1070-11ea-8209-3d2cfcbb389b.png)

The memory is low.

## Addition

If i run the same at other machine (not VM) as below:

![image](https://user-images.githubusercontent.com/9426627/69685224-84494f80-1070-11ea-9ea5-7c6daf947f03.png)

It can finish quickly as below:

![image](https://user-images.githubusercontent.com/9426627/69685250-a5aa3b80-1070-11ea-80ff-c6bb5a622cc6.png)

## Expected behavior
> Finish the test running quickly both for .NET Core 2.0 and .NET Core 3.0, even at low memory machine.

## Actual behavior
> .NET Core 2.0 finish quickly.
> .NET Core 3.0 can't finish, running .... (I don't know what are running)

## Diagnostic logs
> How to get the log?

## Environment
> See above

**Comment by singhsarab** [comment]
@xuzhg Is it possible for you to share a repro project ?

**Comment by xuzhg** [comment]
@singhsarab you can get the source code from: https://github.com/xuzhg/WebApi/tree/RoutingBaseForNEtCore30

run the https://github.com/xuzhg/WebApi/tree/RoutingBaseForNEtCore30/test/UnitTest/Microsoft.AspNetCore.OData.Test\Microsoft.AspNetCore.OData.Test.csproj for net core 3.0 framework testing at low memory VM

**Comment by singhsarab** [comment]
@xuzhg Thanks for the information. We are prioritizing other important feedback right now.
I will update soon.

**Comment by Evangelink** [comment]
@xuzhg Are you still impacted by this performance issue on new versions of test platform?
