### ISSUE TITLE
RunSettingsFilePath property isn't honored by VSTest

### ISSUE THREAD

**Issue by ViktorHofer** [microsoft/vstest#2265]
The property `RunSettingsFilePath` which points to the local .runsettings file for the test session should be honored by VSTest and not just by Visual Studio. Doc that points to that property: https://docs.microsoft.com/en-us/visualstudio/test/configure-unit-tests-by-using-a-dot-runsettings-file?view=vs-2019#visual-studio-2019-version-164-and-later

We need this in the runtime repo (converged repo of coreclr, corefx and core-setup) to configure our test sessions without always needing to type the path to the runsettings file. Our end-goal is that `dotnet test` is sufficient to run our tests.

cc @ManishJayaswal @singhsarab

**Comment by nohwnd** [comment]
A simple repro for this is to have a MSTest test project with a single inconclusive test and force the inconclusive state to translate to fail via run settings. This will give a failing test when settings are picked up and a skipped test when they are not. 

```csharp
using Microsoft.VisualStudio.TestTools.UnitTesting;

namespace UnitTestProject1
{
    [TestClass]
    public class UnitTest1
    {
        [TestMethod]
        public void TestMethod1()
        {
            Assert.Inconclusive();
        }
    }
}
```
Add the following `example.runsettings` in your solution folder

```xml
<?xml version="1.0" encoding="utf-8"?>
<RunSettings>
  <MSTest>
    <MapInconclusiveToFailed>True</MapInconclusiveToFailed>
  </MSTest>
</RunSettings>
```
and configure the project to pick up the settings file by adding this to your csproj: 
```diff 
<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>netcoreapp2.1</TargetFramework>

    <IsPackable>false</IsPackable>

+    <RunSettingsFilePath>$(SolutionDir)\example.runsettings</RunSettingsFilePath>
  </PropertyGroup>
```

Now running it via Test runner will report the test as failed, while running it via `dotnet test` will report the test as skipped. 

![image](https://user-images.githubusercontent.com/5735905/70433097-16922000-1a81-11ea-9da9-fd6efe7370fe.png)

**Comment by vritant24** [comment]
This issue is currently being discussed here #2229
