### ISSUE TITLE
Suppress `The active test run was aborted` message when a run is explicitly cancelled

### ISSUE THREAD

**Issue by shyamnamboodiripad** [microsoft/vstest#2270]
When user cancels a test run / discovery in the VS Test Explorer currently, this message ends up being printed in the VS 'Test' output pane -

`The active test run was aborted. Reason: Test host process crashed`

Ideally, the message should be suppressed when client triggers an explicit cancellation. It should only be returned in the case where the test host process dies unexpectedly.

**Comment by nohwnd** [comment]
I finally back to this. I have repro for Discovery, but not Run as we discussed. Will look into solving it tomorrow.

**Comment by nohwnd** [comment]
This was a bug in the caller, merged a fix there. The message can still be printed when the process actually crashes, but not so often on re-build.
