### ISSUE TITLE
Dotnet Test selecting the wrong Test Execution Command Line Tool Version

### ISSUE THREAD

**Issue by Fenrir2017** [microsoft/vstest#2271]
## Description
I am attempting the use the "dotnet test" command to run unit tests. In my project file, I specify "Microsoft.NET.Test.Sdk" Version="16.4.0", however when the command runs, version 16.3 is used, which will not work for my scenario. 16.4 fixed a bug that did not allow my tests to properly be ran using x86. When ran from the VS studio IDE, everything works as expected. It is only when I run from the CLI that I have an issue.

## Expected behavior
I expect the tests to be executed using 16.4.

## Actual behavior
Tests are ran using 16.3

## Environment
I updated to VS 16.4, and updated my references in the test project to the ones below. The documentation seems to imply the references in the project file will define what Sdk gets used.

    <PackageReference Include="Microsoft.EntityFrameworkCore" Version="2.2.6" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Relational" Version="2.2.6" />
    <PackageReference Include="Microsoft.NET.Test.Sdk" Version="16.4.0" />
    <PackageReference Include="MSTest.TestAdapter" Version="2.0.0" />
    <PackageReference Include="MSTest.TestFramework" Version="2.0.0" />

**Comment by singhsarab** [comment]
The runner version that you see, it comes with dotnet sdk.
You should try using the latest version of the dotnet sdk, that should enable your scenario.

**Comment by vagisha-nidhi** [comment]
@Fenrir2017 Please use the latest version of dotnet sdk as suggested above. Reopen this issue if you face anything else.

**Comment by Fenrir2017** [comment]
Hey guys, I am using the latest SDK, .NET Core SDK (3.1.100), its still using 16.3 as opposed to 16.4.
