### ISSUE TITLE
Pass coverlet codebase in runsettings for inproc data collector initialization

### ISSUE THREAD

**Issue by vagisha-nidhi** [microsoft/vstest#2275]
## Description
Initilization of inproc coverlet collector today needs passing the datacollector extensibility in TestPluginCache. This enables the InProcDataCollectionExtensionManager to be able to find the datacollector in all datacollector extension paths if inproc datacollector codebase path is not an absolute path.
We should directly add this path in runsettings ideally since vstest.console.exe is aware of all datacollector extension paths.
This will remove unnecessary coverlet specific changes from https://github.com/microsoft/vstest/blob/ca987de449d17284f8c9806df36f42276f13962a/src/Microsoft.TestPlatform.CrossPlatEngine/Client/ProxyExecutionManager.cs#L272 and 
https://github.com/microsoft/vstest/blob/master/src/Microsoft.TestPlatform.TestHostProvider/Hosting/DotnetTestHostManager.cs#L321

cc: @AbhitejJohn @MarcoRossignoli

**Comment by MarcoRossignoli** [comment]
I'm working on this, I'll let you know.

**Comment by vagisha-nidhi** [comment]
Thanks @MarcoRossignoli 👍
