### ISSUE TITLE
Dotnet Test selecting the wrong Test Execution Command Line Tool Version

### ISSUE THREAD

**Issue by Fenrir2017** [microsoft/vstest#2286]
https://github.com/microsoft/vstest/issues/2271

I'm unable to reopen the above issue.

Same issue, I have the most recent SDK(.NET Core SDK (3.1.100)) and it is still using 16.3, as opposed to 16.4.

If I run from the CLI, using "dotnet test", 16.3 is used. However, if I use the developer CLI from Visual Studio, and use "vstest.console.exe", 16.4 is used as expected.

I've uninstalled all SDK's, then reinstalled 3.1.100, same issue. I also found that the version of "vstest.console.dll" that is being placed in the dotnet directory(Program Files\dotnet\sdk\3.1.100) is version 16.3.

**Comment by Fenrir2017** [comment]
A new SDK was released on 1/14, same issue, still reference 16.3

**Comment by goblinmaks** [comment]
Reproduced for me also. How I can use latest released 1.6.5 version of Microsoft.Net.Test.Sdk when start tests by `dotnet test` command ?

**Comment by nohwnd** [comment]
Test platform is inserted into Visual Studio and dotnet toolset and will be resolved to those versions that are built-in, for 3.1.100 that is 16.3. You can override the path to the vstest console using ` -p:VSTestConsolePath="<path>"`, the appropriate assembly is shipped in microsoft.testplatform.portable nuget package. 

[Relevant code](https://github.com/microsoft/vstest/blob/master/src/Microsoft.TestPlatform.Build/Microsoft.TestPlatform.targets#L16)

```powershell
dotnet test -p:VSTestConsolePath="$(Get-Item ~\.nuget\packages\microsoft.testplatform.portable\16.5.0\tools\netcoreapp2.1\vstest.console.dll)" 
```

Next release of SDK will reference 16.5.0 test sdk.
More info about the insertions [here](https://github.com/microsoft/vstest/issues/2287#issuecomment-584520530).

**Comment by goblinmaks** [comment]
NET Core SDK 3.1.102 still using version 16.3 of vstest
![image](https://user-images.githubusercontent.com/1436234/76001694-28fbe880-5f0e-11ea-9e48-adc42c75d3fb.png)

**Comment by nohwnd** [comment]
@goblinmaks yes, that is how the shipping works, the version of vstest.console is baked into dotnet test and Visual Studio. The latest version should be in 3.1.200

**Comment by nohwnd** [comment]
What is the fix that you are looking forward to use? Because if you update the desktop SDK version the new test host will be used from that nuget package.

**Comment by goblinmaks** [comment]
@nohwnd it should be expected behavior to use SDK version from nuget for my point of view. I'm still wait https://github.com/microsoft/vstest/issues/862#issuecomment-585427338 this improvement.
Thanks,

**Comment by goblinmaks** [comment]
@nohwnd we know anything about release date of 3.1.200 sdk ?

**Comment by nohwnd** [comment]
@goblinmaks 

> we know anything about release date of 3.1.200 sdk 

I don't think there was anything publicly announced. And I can't share internal info 🙂 

> it should be expected behavior to use SDK version from nuget for my point of view. 

Are you talking about test.sdk here? Because it does. Test SDK does not carry the console, just the targets that make your project a test project  and give it a default entry point. And then it depends on test host nuget. 

The version of console is selected by the runner, not by the project. Either you select it because you invoke vstest.console.exe directly. Or VS uses the one that is built in into it. Or dotnet test uses the one the is built into the sdk.  You can also override it using the `VSTestConsolePath` msbuild param shown above: 

```
C:\Projects\temp\UnitTestProject1 [master +12 ~9 -0 !]> dotnet --version
3.1.101
C:\Projects\temp\UnitTestProject1 [master +12 ~9 -0 !]> dotnet test
Test run for C:\Projects\temp\UnitTestProject1\UnitTestProject1\bin\Debug\netcoreapp3.1\UnitTestProject1.dll(.NETCoreApp,Version=v3.1)
Microsoft (R) Test Execution Command Line Tool Version 16.3.0
Copyright (c) Microsoft Corporation.  All rights reserved.

Starting test execution, please wait...

A total of 1 test files matched the specified pattern.

Test Run Successful.
Total tests: 1
     Passed: 1
 Total time: 1,9922 Seconds
C:\Projects\temp\UnitTestProject1 [master +10 ~9 -0 !]> dotnet test -p:VSTestConsolePath="C:\Users\jajares\Downloads\microsoft.testplatform.portable.16.6.0-preview-20200309-01\tools\netcoreapp2.1\vstest.console.dll"
Test run for C:\Projects\temp\UnitTestProject1\UnitTestProject1\bin\Debug\netcoreapp3.1\UnitTestProject1.dll(.NETCoreApp,Version=v3.1)
Microsoft (R) Test Execution Command Line Tool Version 16.6.0-preview-20200309-01
Copyright (c) Microsoft Corporation.  All rights reserved.

Starting test execution, please wait...

A total of 1 test files matched the specified pattern.

Test Run Successful.
Total tests: 1
     Passed: 1
 Total time: 1,9813 Seconds
```

**Comment by nohwnd** [comment]
That said I think it would be nice if we were publishing a package that will add the executables to the output folder, like testhost does, and that vs and dotnet test would look for those executables first. This would help to both simplify the delivery of updates, because we could fix the version without updating VS, and might work nicely for self-contained scenarios. I will try to bring it up with our team, but don't expect it any time soon, we still work hard on stabilization, and this would be a new feature.

**Comment by gasparnagy** [comment]
@nohwnd Is there somewhere a documentation (or an easy way to find out) on which VsTest versions are bundled with .NET SDK versions? E.g. for .NET Core 2.1

**Comment by nohwnd** [comment]
Not that I am aware of, but we should start putting them into release notes I think. I will be working some more on our release pipelines and shipping strategy in the upcoming sprint, what I would like to see are better release notes that sum up our efforts and also point out community contributions. Linking the version to the sdk in which it was released would be a nice addition to that. 

Just btw if you was .NET Core 2.1 which exact version do you mean? It might change with every servicing release.  🙂

**Comment by gasparnagy** [comment]
@nohwnd Thx! The release note of 16.5 that summarized all the issues of the pre-releases (since 16.4) was very useful (so that people did not have to cumulate the issues of the pre-releases), so please keep that practice as well!

**Comment by nohwnd** [comment]
Great to hear that, I was lazy and just wrote a script to write it for me, so there is no added work to just specify the previous major version instead of previous preview version when I am releasing :)
