### ISSUE TITLE
Listing tests takes too long

### ISSUE THREAD

**Issue by TheRealPiotrP** [Microsoft/vstest#229]
`dotnet test -lt`

Expected:
Fairly immediate response

Actual
based on `/v:diag` output, this invocation does a clean build each time invoked, regardless of the test binary already being built. It also hides this output from the user, appearing to hang.

Why do we need to do a build each time? If it's already built then we should be able to scan it... xunit reports that it takes about .15s to do the actual scan!

**Comment by NickCraver** [comment]
I'm assuming this is related to the double build in VS 2017 - where you build to discover, and then clicking "Run All" builds *again*. Noting here since these likely cross in cause.

**Comment by pvlakshm** [comment]
When  the build does happen, the following messages are shown on the command line:
```
Build started, please wait...
Build completed.
...
```
Use ```dotnet test -t --no-build``` if you don't want to the build to happen.
