### ISSUE TITLE
[loc][Query][OSS_VSTest] Localizability of 0; "UnableToFetchUriString"

### ISSUE THREAD

**Issue by PDostalek** [microsoft/vstest#2291]
Hello developers,
please help localization team to answer question from translator.
In case translator is not sure about context/meaning/localizability of string we raise a question.

Source:
Unable to find a datacollector with friendly name '{0}'.

String ID:
0; "./src/nativeStrings.not_exited_yet"

File Name:
Microsoft.TestPlatform.Common\Resources\xlf\Resources.xlf

Query:
Is "datacollector" localizable? If yes, can we translate it as "data collection object"?

**Comment by singhsarab** [comment]
This should not be translated

**Comment by PDostalek** [comment]
Thanks for reply
