### ISSUE TITLE
Should StyleCop be installed into every project

### ISSUE THREAD

**Issue by nohwnd** [microsoft/vstest#2292]
Not every project enforces code style rules, because not every project has StyleCop.Analyzers nuget package installed. Installing it to every project except for the test assets raises some 650 errors (most of which are build errors because the base dependencies are bot able to build). 

Should the analyzers be installed into all projects (except for test assets and samples)?

![image](https://user-images.githubusercontent.com/5735905/71827126-d766e700-309f-11ea-9181-9dbe231cc73e.png)

**Comment by nohwnd** [comment]
I quckly tried fixing the most pressing issues in the common libraries, and reached ObjectModel which has a lot of code style issues. This is a bigger task and probably needs better justification. 

https://github.com/microsoft/vstest/compare/master...nohwnd:fix-style

**Comment by HeroMaxPower** [comment]
I can take up this challenge

**Comment by nohwnd** [comment]
@HeroMaxPower I am going to close this issue. and possible remove the stylecop rules from all the projects unless someone on the team strongly objects. We are pretty good at keeping the style consistent in all projects in this solution, even when they don't have style cop. Editing a project that has it enabled is extremely frustrating. No-one likes to run a build for 10 minutes only to be notified that a comma should not be preceded by space.

**Comment by nohwnd** [comment]
@HeroMaxPower but what I wanted to say is: Thanks for the offer :)

**Comment by HeroMaxPower** [comment]
No problem 👍 ☕️

**Comment by nohwnd** [comment]
@cvpoienaru @jakubch1 team, do you agree that I disable style cop in the solution to avoid annoying rules that fail build on a misplaced comma, to much whitespace etc.? For me the most annoying is that you can't comment out code because it usually is not followed the correct amount of spaces. It is not enabled in most of the projects anyway.
