### ISSUE TITLE
More extensibile nuget based adapter settings 

### ISSUE THREAD

**Issue by AbhitejJohn** [microsoft/vstest#2294]
Currently settings for nuget based data collectors are difficult to specify given that the code base entry cannot be a fixed path on disk. 
Currently this is achieved by adding in a check in the vstest code to fix this up based on a build property that supplies test adapter paths through a `VSTestTestAdapterPath` build property. 
We'd either want to have an inbuilt mechanism that falls back to adapter paths if a codebase entry is not a path or we'd want to have a better mechanism for adapters to specify a full file path.
Originated from a discussion at #2288

**Comment by MarcoRossignoli** [comment]
For the completeness at the moment there is a fallback inside inproc collector based on list of paths passed to host before testing 

https://github.com/microsoft/vstest/blob/ca24ad0d8b48021ddbe98e4d688bb7e31c7b7eaf/src/Microsoft.TestPlatform.CrossPlatEngine/DataCollection/InProcDataCollectionExtensionManager.cs#L244

That PR remove that custom code that pass `coverlet.collector.dll` base path.

**Comment by nohwnd** [comment]
This is a new feature and won't be implemented, we are focusing on adding new features to Testing.Platform instead. https://aka.ms/testingplatform
