### ISSUE TITLE
Add support to MSIX as packaging format for UWP unit tests

### ISSUE THREAD

**Issue by qmatteoq** [microsoft/vstest#2296]
## Description
> **IMPORTANT**: if the defect is reproduced only in a workflow from within the Visual Studio IDE then do not report the issue here - instead, please report it using Visual Studio's "Send Feedback" option that can be accessed from the Help menu OR using this link https://developercommunity.visualstudio.com.
>
> For a defect reproducable from the vstest command line, describe the issue you've observed.

In Windows 10 1809 Microsoft has released the next generation of Windows 10 packaging format for Windows applications, called MSIX. This format is replacing AppX and Visual Studio generates a MSIX package if a UWP project has 17736 as minimum target SDK.
The same applies to UWP unit test projects. If you choose 17736 as minimum target SDK, Visual Studio will generate a MSIX package.
In this scenario the Test Explorer in Visual Studio can run tests just fine, but vstest.console isn't able to recognize MSIX properly. When you try to run it passing, as parameter, the path to the generated MSIX package, it will find the tests, but then it won't execute them.
The same unit test project with a lower min SDK target and packaged as AppX will be executed just fine.

## Steps to reproduce
> What steps can reproduce the defect?
> Please share the setup, commandline for vstest.console, sample project, target
> framework etc.

1. Create a Universal Windows Platform class library, selecting 18362 as Target SDK and minimum SDK.
2. Inside the library create a class which exposes a simple sum method.
3. Create a Unit Test UWP project, selecting 18362 as Target SDK and minimum SDK.
4. Add a test to validate the sum method defined in the library.
5. Run the tests with Test Explorer in Visual Studio. Notice how the test is properly executed.
6. Right click on the Unit Test project, choose Publish -> Create app package and complete the wizard. It will generate a MSIX package.
7. Ran from the command line:

`vstest.console package_name.msix`

## Expected behavior
> Share the expected output

vstest.console should find the test and execute them.

## Actual behavior
> What is the behavior observed?

vstest.console finds the test, but then it doesn't execute them.

This is the output you get:

`
Microsoft (R) Test Execution Command Line Tool Version 16.4.0
Copyright (c) Microsoft Corporation.  All rights reserved.

Starting test execution, please wait...

A total of 1 test files matched the specified pattern.

Additionally, path to test adapters can be specified using /TestAdapterPath command. Example  /TestAdapterPath:<pathToCustomAdapters>.
`

## Diagnostic logs
> Please share test platform diagnostics logs. Instructions to collect logs are [here](https://github.com/Microsoft/vstest-docs/blob/master/docs/diagnose.md#test-platform-diagnostics).  
> The logs may contain test assembly paths, kindly review and mask those before sharing.

## Environment
> Please share additional details about the test environment.
> Operating system, Build version of vstest.console

Windows 10 1909
Microsoft (R) Test Execution Command Line Tool Version 16.4.0

**Comment by aronweiler** [comment]
So... more than a year, and this is still an issue?

Is there any workaround for this?  As-is, it appears like I cannot run UWP unit tests from the command line.

**Comment by aronweiler** [comment]
Ok, so after some more research, it appears possible to use vstest to run the unit tests from the command line:

vstest.console.exe /Platform:x64 YOUR_PACKAGE_1.0.0.0_x64_Debug.msix /Logger:trx **/framework:frameworkuap10**

The key was adding the framework flag.  Without it, I get the original issue.

**Comment by Evangelink** [comment]
Closing as there is a workaround provided.
