### ISSUE TITLE
[loc][Query][OSS_VSTest] Localizability of 0; "InvalidTestRunParameterArgument"

### ISSUE THREAD

**Issue by PDostalek** [microsoft/vstest#2298]
Hello developers,
please help localization team to answer question from translator.
In case translator is not sure about context/meaning/localizability of string we raise a question.

Source:
The test run parameter argument '{0}' is invalid. Please use the format below.\r\n Format: TestRunParameters.Parameter(name=\\"<name>\\", value=\\"<value>\\")

String ID:
0; "InvalidTestRunParameterArgument"

File Name:
vstest.console\Resources\xlf\Resources.xlf

Query:
The parts \\"<name>\\" and \\"<value>\\" can be translated ?

**Comment by singhsarab** [comment]
The entire format should not be translated.

**Comment by PDostalek** [comment]
Thanks for reply
