### ISSUE TITLE
system.io.filenotfoundexception: could not load file or assembly 'microsoft.mshtml, version=7.0.3300.0, culture=neutral, publickeytoken=b03f5f7f11d50a3a' or one of its dependencies.

### ISSUE THREAD

**Issue by angelwang** [microsoft/vstest#2301]
Seems the package is missing microsoft.mshtml,. I encountered below error when running codedUI tests. If I copy microsoft.mshtml.dll over to where the tool installed under the agent, it works. 
The agent is Windows 10 1903, it is a clean install without visual studio or legacy vs test agent installed.

Error: 
system.io.filenotfoundexception: could not load file or assembly 'microsoft.mshtml, version=7.0.3300.0, culture=neutral, publickeytoken=b03f5f7f11d50a3a' or one of its dependencies.

**Comment by greycoding** [comment]
I have exactly the same problem with Windows 10 version 2020.
@angelwang Can you describe your workaround in more detail? Which DLL (from which file path) did you copy to which target path?

**Comment by nohwnd** [comment]
@cvpoienaru this is coded UI tests, do you know more about it, please?

**Comment by Evangelink** [comment]
Ping @cvpoienaru
