### ISSUE TITLE
Error CS0234: The type or namespace name 'TestPlatform' does not exist in the namespace 'Microsoft.VisualStudio'

### ISSUE THREAD

**Issue by cheenamalhotra** [microsoft/vstest#2312]
## Description

I'm trying to compile our tests with the new SDK and we're facing this issue for platforms "x86" and "AnyCPU" when using "Microsoft.NET.Test.Sdk" version 16.4.0.

`Error CS0234: The type or namespace name 'TestPlatform' does not exist in the namespace 'Microsoft.VisualStudio'`

It worked fine for v15.9.0 and we never had any issues. We'd like to upgrade to a later version, but this issue is kind of confusing.

```cmd
CoreCompile:
    Using shared compilation with compiler from directory: C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\MSBuild\Current\Bin\Roslyn
##[error]C:\Users\dotnet\.nuget\packages\microsoft.net.test.sdk\16.4.0\build\netcoreapp2.1\Microsoft.NET.Test.Sdk.Program.cs(3,25): Error CS0234: The type or namespace name 'TestPlatform' does not exist in the namespace 'Microsoft.VisualStudio' (are you missing an assembly reference?)
```
Failing build: https://dev.azure.com/sqlclientdrivers-ci/sqlclient/_build/results?buildId=5437&view=logs

Please refer jobs: 
- Win10Enclave AnyCPU,Release,netfx,true
- Win10Enclave x86,Release,netfx,true

This issue does not occur when building locally on Developer command prompt on the same machine using same steps where this is occurring, but fails when building with Azure Pipelines.

## Environment
OS: Windows 10
.NET Framework: 4.6.1
MSBuild: v16 (VS 2019 Enterprise v16.4.3)
Platform: x86 and AnyCPU

**Comment by cvpoienaru** [comment]
Hello Cheena. Many thanks for your ping. Unfortunately there's been no significant progress on this as of yet, but I'll do my best to have a resolution in place by the end of next week.

**Comment by nohwnd** [comment]
@cheenamalhotra I briefly looked at this, and your build is for some reason picking up the program.cs that we inject by custom targets into netcoreapp from Microsoft.NET.Test.Sdk but not into net4.

``` 
C:\Users\dotnet\.nuget\packages\microsoft.net.test.sdk\16.5.0\build\netcoreapp2.1\Microsoft.NET.Test.Sdk.Program.cs
```

I tried to repro using a similar project and cannot get it to fail. BUT if I add the compile item into my project I see the same failure. 

This looks like a build problem and not like vstest problem but I would be interested in seeing why this happens. I see that you are providing a custom output path so possibly the results of subsequent builds are mixed in a way that causes this issue. 

Please provide a diagnostic build log or binlog. 


My csproj: 

```csproj
<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFrameworks>net461</TargetFrameworks>

    <IsPackable>false</IsPackable>
    <EnableDefaultCompileItems>false</EnableDefaultCompileItems>
    <Platforms>x86</Platforms>
    <IntermediateOutputPath>$(ObjFolder)$(Configuration).FunctionalTests</IntermediateOutputPath>
    <OutputPath>$(BinFolder)$(Configuration).FunctionalTests</OutputPath>
  </PropertyGroup>

  <ItemGroup>
    <!--<Compile Include="C:\Users\jajares\.nuget\packages\microsoft.net.test.sdk\16.5.0\build\netcoreapp2.1\Microsoft.NET.Test.Sdk.Program.cs" />-->
    <Compile Include="UnitTest1.cs" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="xunit" Version="2.4.1" />
    <PackageReference Include="xunit.runner.visualstudio" Version="2.4.1" />
    <PackageReference Include="xunit.runner.console" Version="2.4.1" />
    <PackageReference Include="xunit.runner.utility" Version="2.4.1" />
    <PackageReference Include="Microsoft.NET.Test.Sdk" Version="16.4.0" />    
  </ItemGroup>

</Project>
```

**Comment by cheenamalhotra** [comment]
Hi @nohwnd 

I'd also like to highlight, this does not happen when building locally in Developer Command Prompt but only with Azure Pipeline Jobs, that too intermittently. I've also tested locally in the same Agent machine where the build occurs from pipeline, but could not reproduce anytime.

That is why it's so annoying!

Could you also try to build your repro project from Azure Pipelines and confirm your project builds properly? I've also captured binlog for it before and investigated, but it just doesn't make sense why would this go to .NET Core side of things!

I'm captured binlog in devops job again, it's intermittent so took multiple runs.
[binlog.zip](https://github.com/microsoft/vstest/files/4361088/binlog.zip)

**Comment by nohwnd** [comment]
@cheenamalhotra  could you hit me with a bin log from successful run please? 

It looks like this is "stale" for some reason: 
![image](https://user-images.githubusercontent.com/5735905/77197751-03fa9e80-6ae6-11ea-93d1-b1b9c24d6473.png)

And the generate build will enter the tests projects from the XUnitUtilities project. But I am hardly sure about it until comparing it with a working build. 

```
Import: E:\ci-agent1\_work\12\s\src\Microsoft.Data.SqlClient\tests\tools\Microsoft.DotNet.XUnitExtensions\obj\Microsoft.DotNet.XUnitExtensions.csproj.nuget.g.props at (62;3)
                    Import: C:\Users\dotnet\.nuget\packages\microsoft.testplatform.testhost\16.4.0\build\netcoreapp2.1\Microsoft.TestPlatform.TestHost.props at (16;5)
                    Import: C:\Users\dotnet\.nuget\packages\microsoft.codecoverage\16.4.0\build\netstandard1.0\Microsoft.CodeCoverage.props at (17;5)
                    Import: C:\Users\dotnet\.nuget\packages\microsoft.net.test.sdk\16.4.0\build\netcoreapp2.1\Microsoft.NET.Test.Sdk.props at (18;5)
                    Import: C:\Users\dotnet\.nuget\packages\xunit.runner.visualstudio\2.4.1\build\netcoreapp1.0\xunit.runner.visualstudio.props at (19;5)
                    Import: C:\Users\dotnet\.nuget\packages\xunit.runner.console\2.4.1\build\xunit.runner.console.props at (20;5)
                    Import: C:\Users\dotnet\.nuget\packages\xunit.core\2.4.1\build\xunit.core.props at (21;5)
```

**Comment by cheenamalhotra** [comment]
[success-binlog.zip](https://github.com/microsoft/vstest/files/4361556/success-binlog.zip)

**Comment by rainersigwald** [comment]
@cheenamalhotra There are some issues with the structure of the `build.proj` used to structure the repo's overall build.

Because it runs `Restore` as part of the main build, instead of as a separate phase, you won't reliably pick up updated build logic. You should build with `dotnet build /restore` (or `msbuild.exe /restore`) instead. But that won't be sufficient to fix this problem.

I don't think that's the major problem here, though. In `build.proj`, restore is run separately for netcore and netfx:

https://github.com/dotnet/SqlClient/blob/2874114481d73f5e51384dc0a7834b90c33e664d/build.proj#L53-L63

Because each restore operation happens for a specific `TargetFramework`, the generated import file `Microsoft.Data.SqlClient.Tests.csproj.nuget.g.targets` is specific for a given TF. In the failure log you uploaded, that means it includes

```xml
  <ImportGroup Condition=" '$(ExcludeRestorePackageImports)' != 'true' ">
    <Import Project="$(NuGetPackageRoot)microsoft.codecoverage\16.4.0\build\netstandard1.0\Microsoft.CodeCoverage.targets" Condition="Exists('$(NuGetPackageRoot)microsoft.codecoverage\16.4.0\build\netstandard1.0\Microsoft.CodeCoverage.targets')" />
    <Import Project="$(NuGetPackageRoot)microsoft.net.test.sdk\16.4.0\build\netcoreapp2.1\Microsoft.NET.Test.Sdk.targets" Condition="Exists('$(NuGetPackageRoot)microsoft.net.test.sdk\16.4.0\build\netcoreapp2.1\Microsoft.NET.Test.Sdk.targets')" />
    <Import Project="$(NuGetPackageRoot)microsoft.dotnet.genapi\1.0.0-beta.18578.2\build\Microsoft.DotNet.GenAPI.targets" Condition="Exists('$(NuGetPackageRoot)microsoft.dotnet.genapi\1.0.0-beta.18578.2\build\Microsoft.DotNet.GenAPI.targets')" />
    <Import Project="$(NuGetPackageRoot)coverlet.msbuild\2.8.0\build\coverlet.msbuild.targets" Condition="Exists('$(NuGetPackageRoot)coverlet.msbuild\2.8.0\build\coverlet.msbuild.targets')" />
  </ImportGroup>
```

Note the explicit include of the `netcoreapp2.1` build logic from referenced packages.

What happens is this:

1. The core restore happens, and `*.nuget.g.targets` is written (for `netcoreapp`).
1. The full restore happens
  a. Because you don't specify `ExcludeRestorePackageImports=false` when doing restore, MSBuild follows the import laid down by step 1, and loads the `netcoreapp` flavor of `*.nuget.g.targets` into projects into its XML cache.
  b. `*.nuget.g.targets` is overwritten with a desktop framework/netfx version
1. The core build happens and is happy (because the import comes from 2a and is netcore).
1. The netfx build happens and is unhappy (because the import comes from 2a and is netcore).

The best fix for this would be to rely on standard multitargeting for the projects--specifying `TargetFrameworks` (plural) with the appropriate set for the current build environment.

(By the way, you should consider moving to solution-based restore for performance and consistency.)

**Comment by nohwnd** [comment]
Thank you very much @rainersigwald for explanation and confirming that this is not a Test.SDK issue. @cheenamalhotra I am going to close this now, hopefully you will be able to refactor it to the target frameworks approach that was suggested. 

I saw that the working log is _probably_ not from the build server. Both me and @rainersigwald and very curious about why it would be an intermittent issue. If you had a chance and shared a bin log of a working build from the build server it would be great :)

**Comment by dharmanel** [comment]
This error has been produced by 'Intellisense'. If you build with Build only the error disappear. Just select only the Build and test it. However, it works fine.
![Error](https://user-images.githubusercontent.com/12986120/84257524-cc394b00-ab58-11ea-9430-3a95afab2134.png)
