### ISSUE TITLE
Remove dependency on Visual Studio 2017

### ISSUE THREAD

**Issue by nohwnd** [microsoft/vstest#2313]
## Description
Build script is dependent on Visual Studio 2017 because it searches for msbuild 15, and also searches for VS 15.0<= x <16.0.

Make sure VS2019 (ideally Community) can be used, and document the required workloads to be installed.

**Comment by nohwnd** [comment]
FYI @AbhitejJohn

**Comment by AbhitejJohn** [comment]
Thanks @nohwnd 👍
