### ISSUE TITLE
Add dotnet store to the default test adapter search paths

### ISSUE THREAD

**Issue by foriequal0** [microsoft/vstest#2317]
## Description
I want to install my vstest logger to the dotnet store. However, it doesn't search there by default.

## Steps to reproduce
1. Install some testlogger with dotnet store
```shell
echo >> RuntimePackages.manifest<<EOF
<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>netcoreapp3.1</TargetFramework>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="XunitXml.TestLogger" Version="2.1.26" />
  </ItemGroup>
</Project>

EOF

dotnet store --manifest RuntimePackages.manifest \
  --framework netcoreapp3.1 --runtime win10-x64 \
  --skip-optimization # this is a workaround of issue dotnet/core/issues/4031
```
You might need to fix these issues first: https://github.com/dotnet/sdk/issues/10590, https://github.com/dotnet/core/issues/4031

2. ```dotnet test -l:xunit```

## Expected behavior
```dotnet test -l:xunit``` can find XunitXml.TestLogger by default.

## Actual behavior
```dotnet test "-l:xunit" "-p:VSTestTestAdapterPath=C:/Users/user/.dotnet/store/x64/netcoreapp3.1/"``` is needed

## Diagnostic logs
I'm testing my custom logger `GithubActionsDotnetLogger`, whose friendly name is `GithubActionsDotnetTestLogger`

Log for ```dotnet test "-l:GithubActionsDotnetTestLogger;RepositoryRoot=$PWD;" "-p:VSTestDiag=diag.log;tracelevel=verbose"```
[diag.log](https://github.com/microsoft/vstest/files/4151042/diag.log)

Log for ```dotnet test "-l:GithubActionsDotnetTestLogger;RepositoryRoot=$PWD;" "-p:VSTestTestAdapterPath=C:/Users/user/.dotnet/store/x64/netcoreapp3.1/" "-p:VSTestDiag=diag.log;tracelevel=verbose"```
[diag.host.20-02-04_10-46-50_07387_6.log](https://github.com/microsoft/vstest/files/4151040/diag.host.20-02-04_10-46-50_07387_6.log)

## Environment
```
.NET Core SDK(global.json 반영):
 Version:   3.1.101
 Commit:    b377529961

런타임 환경:
 OS Name:     Windows
 OS Version:  10.0.18363
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\3.1.101\

Host (useful for support):
  Version: 3.1.1
  Commit:  a1388f194c

.NET Core SDKs installed:
  3.1.101 [C:\Program Files\dotnet\sdk]

.NET Core runtimes installed:
  Microsoft.AspNetCore.All 2.1.15 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.App 2.1.15 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.1.1 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 2.1.15 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.1.1 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.WindowsDesktop.App 3.1.1 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]

To install additional .NET Core runtimes or SDKs:
  https://aka.ms/dotnet-download
```

**Comment by Evangelink** [comment]
Could you try adding the package directly to your project? This way it should be picked up automatically.

**Comment by nohwnd** [comment]
This is a new feature and won't be implemented, we are focusing on adding new features to Testing.Platform instead. https://aka.ms/testingplatform
