### ISSUE TITLE
Broken HTML logger?

### ISSUE THREAD

**Issue by provegard** [microsoft/vstest#2318]
## Description

I'm trying to use the HTML logger, but it fails with both `dotnet test` and `dotnet vstest`.

## Steps to reproduce

I simply run `dotnet test` or `dotnet vstest`.

## Expected behavior

An HTML test report is generated.

## Actual behavior

When I run `dotnet test --logger html` or `dotnet vstest <path to DLL> --logger:html`:

    Html Logger Error : Could not find a part of the path '<path to test folder>\TestResults\TestResult_<user name>_<computer name>_20200204_163900.xml'.

## Environment

* Windows 10, 1909
* `dotnet --version` says 3.1.100

**Comment by provegard** [comment]
By the way, the TRX logger works fine.

**Comment by nohwnd** [comment]
@provegard works for me. I was trying to repro on 2.1.402 and that does not contain the html logger. And I way trying to reproduce on 3.1.101 and that works without a problem. I tried it with netcoreapp2.1, netcoreapp3.1 projects and with multiple versions of Test.Sdk and still could not reproduce. Please try it out, hopefully it works. Otherwise let me know if not. My steps below:

```
dotnet test --logger html
Test run for C:\Projects\temp\UnitTestProject52\UnitTestProject52\bin\Debug\netcoreapp3.1\UnitTestProject52.dll(.NETCoreApp,Version=v3.1)   Microsoft (R) Test Execution Command Line Tool Version 16.3.0
Copyright (c) Microsoft Corporation.  All rights reserved.

Starting test execution, please wait...

A total of 1 test files matched the specified pattern.
  X TestMethod1 [34ms]
  Error Message:
   Assert.AreEqual failed. Expected:<>. Actual:<16.4.0>.
  Stack Trace:
     at UnitTestProject52.UnitTest1.TestMethod1() in C:\Projects\temp\UnitTestProject52\UnitTestProject52\UnitTest1.cs:line 12

Test run in progress.Html test results file : C:\Projects\temp\UnitTestProject52\UnitTestProject52\TestResults\TestResult_jajares_JAJARES-SURBOOK_20200318_121407.html

Test Run Failed.
Total tests: 1
     Failed: 1
 Total time: 1,2960 Seconds
```

```json
# file global.json
{
  "sdk": {
    "version": "3.1.101"
  }
}
```

```cs
// file UnitTest1.cs
using ClassLibrary1;
using Microsoft.VisualStudio.TestTools.UnitTesting;

namespace UnitTestProject52
{
    [TestClass]
    public class UnitTest1
    {
        [TestMethod]
        public void TestMethod1()
        {
            Assert.AreEqual("", new Class1().GetVersion());
}
```

```csproj
<!-- file UnitTestProject52.csproj -->
<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>netcoreapp3.1</TargetFramework>

    <IsPackable>false</IsPackable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.NET.Test.Sdk" Version="16.3.0" />
    <PackageReference Include="MSTest.TestAdapter" Version="2.1.0" />
    <PackageReference Include="MSTest.TestFramework" Version="2.1.0" />
    <PackageReference Include="coverlet.collector" Version="1.2.0" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\ClassLibrary1\ClassLibrary1.csproj" />
  </ItemGroup>

</Project>

```

**Comment by provegard** [comment]
@nohwnd you're right, this appears to be a NUnit test adapter problem. I'll open an issue in that repo instead. Apologies for the noise and the glaring lack of information in the issue.

**Comment by nohwnd** [comment]
@provegard no problem, hope you get it fixed :)

**Comment by 0xced** [comment]
I had the exact same issue (on macOS with xUnit). My understanding is that the html logger needs to write and intermediary xml file inside the `TestResults` directory but doesn't ensure that the `TestResults` exists. I worked around the problem by manually creating the `TestResults` directory before running the tests.

**Comment by nohwnd** [comment]
Okay might be possible.

**Comment by nohwnd** [comment]
Still can't repro. Do you have a call stack?
