### ISSUE TITLE
Theory Test names not displayed correctly in the ADO Test Results dashboard

### ISSUE THREAD

**Issue by himajan** [microsoft/vstest#2320]
## Description
The Theory Test names are appearing incorrectly in the ADO Test Results dashboard. But, they are displayed correctly in the trx file.

## Steps to reproduce
Any Theory Test that takes in the MemberData from an IEnumerable Collection like List.

## Expected behavior
The Test Names should appear with the right member data in the Test Results tab in ADO build pipeline.

## Actual behavior
All the Tests have the same member data in the Test Results tab. But, when I dig into the Rerun Attempt it shows the right data.

![image](https://user-images.githubusercontent.com/56146857/73973027-aa903480-48d6-11ea-9338-030401610f7c.png)

## Environment
Build Link: https://dynamicscrm.visualstudio.com/OneCRM/_build/results?buildId=5835248&view=ms.vss-test-web.build-test-results-tab

Link To trx File: https://vw6tcmprodwus231.vstmrblob.vsassets.io/37a2c3ee-9664-49a9-a37d-e3089e536a06-197-runid-15069370/GeneralAttachment/VssAdministrator_fv-az48_2020-02-06_06_37_13.trx?sv=2017-04-17&sr=b&si=logstore-read-list-policy&sig=Za3eelK71GFIj5QvA%2F6nNCiMQzm1FiPzMYO%2F16CzpRI%3D&spr=https&rsct=application%2Foctet-stream

**Comment by Evangelink** [comment]
Note to self: Transfer to AzDo

**Comment by Evangelink** [comment]
Closing this issue, it was transferred to AzDo tasks repository.
