### ISSUE TITLE
Test parallelization is grouped by target framework

### ISSUE THREAD

**Issue by AbhitejJohn** [microsoft/vstest#2322]
## Description
[Filing this from an internal email exchange]

We have a number of test projects, each targeting 2-3 frameworks. Not all projects target the same frameworks. We run the “dotnet test” command in the same directory as the .sln file, and it seems to pick up all the test projects referenced by it.

If we run all the tests in one go, **even though the tests are set to run in parallel**, what we see is all the tests for the first (automatically detected) framework run in parallel. Once that is complete, the next framework gets a go. Finally the last one goes. For our integration tests in that set, they take about 5 minutes per framework, and stacked up that is 15 minutes. We can get it down to nearly 5 minutes if each framework’s tests ran at the same time.

But if we manually separate them by specifying the framework, the test projects that don’t support that framework issue an error, that tricks the script into thinking the test run failed, but it really is a red herring.

What we’d really like is for all discovered frameworks to start executing in parallel and not have to handle splitting them up ourselves. Short of that, we’d like to know how we can suppress that error about a test project not supporting the specified framework.

**Comment by drwill-ms** [comment]
For others, sharing our work around for the suppression issue, which is conditionally turning off the project as a test project. Add this line (with your own conditional) to your .net core project.

<IsTestProject Condition="('$(TargetFramework)' != 'netcoreapp2.1')">False</IsTestProject>

**Comment by Evangelink** [comment]
This is fixed in 17.3+.
