### ISSUE TITLE
Please add non-Windows CI to this repo

### ISSUE THREAD

**Issue by piotrpMSFT** [Microsoft/vstest#233]
We've seen a few issues in CLI repo that only repro on x-plat. #213 is a good example, and I worry we'll hit others as we start exercising more of the capabilities of `dotnet test`. Though I'd be glad to catch issues before external users run into them, it would be wonderful if the CI for this repo included at least a linux, ideally a linux and a Mac.

**Comment by codito** [comment]
Blocked on https://github.com/dotnet/sdk/issues/335

`restore` works great. `build` throws bunch of errors on net46. Will need to explore if it's possible to exclude `net46` from <TargetFrameworks> dynamically based on operating system.

**Comment by codito** [comment]
Completed
