### ISSUE TITLE
dotnet test failed integration test after new .net core sdk installed

### ISSUE THREAD

**Issue by SaeidSabzalizadeh** [microsoft/vstest#2336]
Here is my xunit test project:

```xml
  <PropertyGroup>
    <TargetFramework>netcoreapp2.1</TargetFramework>
    <IsPackable>false</IsPackable>
  </PropertyGroup>

 <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.App" Version="2.1.1" />
    <PackageReference Include="Microsoft.AspNetCore.Mvc.Testing" Version="2.1.0" />
    <PackageReference Include="Microsoft.AspNetCore.TestHost" Version="2.1.0" />
    <PackageReference Include="Microsoft.NET.Test.Sdk" Version="15.9.0" />
    <PackageReference Include="moq" Version="4.12.0" />
    <PackageReference Include="xunit" Version="2.4.0" />
    <PackageReference Include="xunit.runner.visualstudio" Version="2.4.0" />
  </ItemGroup>
```

All was good up until I installed .NET Core 3.1 SDK, now all my integration tests failed.
I checked in different machines as long as I have only .NET Core 2.1 every thing is good but by installing .NET Core 3.1 all integration tests failed. 

Is there any config I should add to my project?
It's not an option for me to upgrade my project or test project to 3.1.

It seems it is a .net issue and not a xunit:
https://github.com/xunit/xunit/issues/2066

**Comment by nohwnd** [comment]
That's interesting could you post the actual failure please? 

You can pin your dotnet version using global.json that way, you know what you will be invoking against. For example like this: 

```
dotnet new globaljson --sdk-version 2.1.804
```

**Comment by SaeidSabzalizadeh** [comment]
> That's interesting could you post the actual failure please?
> 
> You can pin your dotnet version using global.json that way, you know what you will be invoking against. For example like this:
> 
> ```
> dotnet new globaljson --sdk-version 2.1.804
> ```

Thank you, It works fine with global.json

**Comment by SaeidSabzalizadeh** [comment]
> That's interesting could you post the actual failure please?

Fails are vary in different servers in one I got 404 for all api requests.
In another server I got System.IO.IOException : The process cannot access the file.
 
By adding global.json file and pin the sdk version all passed.

**Comment by nohwnd** [comment]
Awesome, closing :)

**Comment by sphinxy** [comment]
404 maybe because of https://stackoverflow.com/questions/43669633/why-is-testserver-not-able-to-find-controllers-when-controller-is-in-separate-as/
