### ISSUE TITLE
Suspicious folder structure for TestAssets

### ISSUE THREAD

**Issue by MarcoRossignoli** [microsoft/vstest#2347]
@nohwnd is this structure for test assets correct https://github.com/microsoft/vstest/blob/master/test/TestAssets/TestAssets.sln/TestAssets.sln?

I mean there is a folder called `TestAssets.sln` with a solution file with same name inside.

**Comment by nohwnd** [comment]
That’s how it is, it is weird but I did not change it yet, because I was not sure that none of our builds depend on it

**Comment by MarcoRossignoli** [comment]
Ah ok, close this so.
