### ISSUE TITLE
Upgrade build infrastructure to arcade

### ISSUE THREAD

**Issue by nohwnd** [microsoft/vstest#2349]
## Description
As mentioned here test.sdk is not flowing correctly via darc. This probably needs to be prioritized, and the amount of necessary changes is unclear. 

https://github.com/dotnet/sdk/issues/10734

**Comment by nohwnd** [comment]
@ManishJayaswal bringing this to your attention, we figured this out when trying to add the dotnet 5.0 templates. I think I need to spend some time to figure this out, so we are good citizens in the integrations with other repos. Should we move this to priority 1?

**Comment by ManishJayaswal** [comment]
@nohwnd  - sure. Done.

**Comment by nohwnd** [comment]
Right now there is a step added to the pipeline that will promote the build which was a short-term workaround suggested by the arcade team. I made a build and it created the PR correctly: https://github.com/dotnet/sdk/pull/10858
