### ISSUE TITLE
Add tests for new Datacollector Configuration usage

### ISSUE THREAD

**Issue by vritant24** [microsoft/vstest#2353]
To support the new fakes implementation, a new configuration generator was added which is retrieved from `FakesUtilities.TryGetFakesDataCollectorConfigurator(out Func<IEnumerable<string>, bool, DataCollectorSettings> configurator)` in this #2339 . 

Tests for this need to be added once the new Fakes implementation is pushed.

**Comment by Evangelink** [comment]
@vritant24 If you have some time to add these tests, that would be awesome!
