### ISSUE TITLE
VsTest Console - TestCaseFilter

### ISSUE THREAD

**Issue by AutomationTester01** [microsoft/vstest#2357]
## Description
The filtering of test cases can only be performed directly in the command line (https://github.com/Microsoft/vstest-docs/blob/master/docs/filter.md).
In my use case scenario, I need to filter individual test cases by FullyQualifiedName causing the arguments to get too long for the command line (> 32,767 characters).

It would be beneficial if it would be possible to pass some file which contains fully qualified paths as a parameter to the vstest console.

**Comment by nohwnd** [comment]
Would runsettings be good enough? #2273

**Comment by nohwnd** [comment]
Runsettings in the linked PR are the way forward. Command line size limits are set by OS and we cannot do anything about that. 

Solution and example here: https://github.com/microsoft/vstest/issues/2273#issuecomment-595292726

Works fine with
