### ISSUE TITLE
TranslationLayer should be able to pick TestAdapterPath from Runsettings

### ISSUE THREAD

**Issue by jayaranigarg** [Microsoft/vstest#236]
## Description
Translation layer is not able to pick testadapter path provided to it from runsettings and we have to explicitly call InitializeExtensions("FilePath to adapter dll")

## Steps to reproduce
1. Give testadapterpath in runSettingXml till the folder of testadapter.dll
2. Call DiscoverTests() with this runSettingXml 

## Expected behavior
Tests should get discovered.

## Actual behavior
Tests were not discovered because adapter dll was not found.

## Environment
Using following Nuget Packages :
1. Microsoft.TestPlatform.TranslationLayer.15.0.0-preview-20161110-01
2. Microsoft.TestPlatform.15.0.0-dev

**Comment by codito** [comment]
@singhsarab I think this is already fixed, can you please validate and close the issue?

**Comment by singhsarab** [comment]
This was fixed via https://github.com/Microsoft/vstest/pull/455

**Comment by singhsarab** [comment]
Validated. Closing.
