### ISSUE TITLE
Review visibility of public interfaces

### ISSUE THREAD

**Issue by cvpoienaru** [microsoft/vstest#2362]
### Motivation

Some of the public interfaces inside this repository should not be public by default (e.g.: IDesignModeClient, etc.) as they are only used by components implemented by us that aren't meant to be replaceable by third party components.

In order to avoid exposing unneeded interfaces and make it convenient for us to mutate them without having to worry about breaking compatibility, we should review which public interfaces should remain public and which ones can be made internal.

**Comment by nohwnd** [comment]
Taking note of this in a design doc, this needs huge refactoring of the extensibility model, and dependency model to have any impact.
