### ISSUE TITLE
Allow multiple loggers to be provided

### ISSUE THREAD

**Issue by nohwnd** [microsoft/vstest#2368]
Cool! Is the syntax to support multiple loggers like this?

```bash
dotnet test --logger trx;LogFileName=foo.trx --logger html;LogFileName=foo.html
```

_Originally posted by @RehanSaeed in https://github.com/microsoft/vstest/pull/2103#issuecomment-533487376_

**Comment by HeroMaxPower** [comment]
This would be good for TeamCity, sometimes you need to generate a trx with a more verbose console message

**Comment by nohwnd** [comment]
@RehanSaeed yes that works, but you should put those options in quotes if you run them from bash / powershell because ; terminates the command and you would end up evaluating only half of the command. Or in powershell you can use the parsing terminator `--%`: 

```shell
# cmd / bash / powershell
dotnet test --logger "trx;LogFileName=foo.trx" --logger "html;LogFileName=foo.html"

# or another way in powershell
dotnet test --% --logger trx;LogFileName=foo.trx --logger html;LogFileName=foo.html
```

**Comment by nohwnd** [comment]
https://github.com/MicrosoftDocs/visualstudio-docs/pull/5482

**Comment by kirinnee-atomi** [comment]
How does this translate to `<VSTestLogger>` in  `csproj` ?

**Comment by nohwnd** [comment]
Just using multiple loggers would be `<VSTestLogger>trx;html</VSTestLogger>`. To also specify the paths you need more complex syntax: https://stackoverflow.com/a/21743192

**Comment by RobSwDev** [comment]
When I specify multiple loggers to `dotnet vstest`, it seems to work when the tests target Net5.0, but not if they target Net6.0.
In 6.0, I get an error: 

```
System.InvalidOperationException: Option '--logger' only accepts a single argument but 2 were provided.
   at System.CommandLine.Binding.ArgumentConverter.GetValueOrDefault[T](ArgumentConversionResult result)
```

**Comment by nohwnd** [comment]
You are right, dotnet sdk repository moved our parameter parsing to use System.CommandLine, and it was not bug free. Please use `dotnet test` for your command, it does the same thing as `dotnet vstest` when you give it a dll.

**Comment by Kevin-Andrew** [comment]
Switching from `dotnet vstest` that had multiple `--logger` arguments to using `dotnet test` worked for us. Thanks!
