### ISSUE TITLE
Allow multiple loggers to be provided via runsettings

### ISSUE THREAD

**Issue by nohwnd** [microsoft/vstest#2369]
> Is it possible to specify html logger and other loggers via runsettings file? 

---

How to use this html logger with runsettings file? I tried via cli and it works, but no luck through the config file.

`<LoggerRunSettings>
        <Loggers>
            <Logger friendlyName="html">
                <Configuration>
                    <LogFileName>test.html</LogFileName>
                </Configuration>
            </Logger>
        </Loggers>
</LoggerRunSettings>`

_Originally posted by @dracos1993 in https://github.com/microsoft/vstest/pull/2103#issuecomment-536173035_

**Comment by nohwnd** [comment]
@ViktorHofer  added a new issue here.

**Comment by ViktorHofer** [comment]
Thanks!

**Comment by mdalepiane** [comment]
This issue seems to be specific for configurations provided using runsettings. Is it possible to use multiple loggers using command line parameters?

**Comment by ViktorHofer** [comment]
Just tried this out and it works as expected:

```xml
  <LoggerRunSettings>
    <Loggers>
      <Logger uri="logger://Microsoft/TestPlatform/TrxLogger/v1">
        <Configuration>
          <LogFileName>testResults.trx</LogFileName>
        </Configuration>
      </Logger>
      <Logger uri="logger://Microsoft/TestPlatform/HtmlLogger/v1">
        <Configuration>
          <LogFileName>testResults.html</LogFileName>
        </Configuration>
      </Logger>
    </Loggers>
  </LoggerRunSettings>
```

@nohwnd I believe we can close this issue but should consider updating the logger documentation.

**Comment by nohwnd** [comment]
@dracos1993 

This is what you'd do from settings, I actually just copied it from the log and removed unneeded lines: 

```shell
dotnet test --% --logger trx;LogFileName=foo.trx --logger html;LogFileName=foo.html --diag c:\temp\log.txt
```

```xml
<RunSettings>
  <RunConfiguration>
  </RunConfiguration>
  <LoggerRunSettings>
    <Loggers>
      <Logger friendlyName="trx" enabled="True">
        <Configuration>
          <LogFileName>foo.trx</LogFileName>
        </Configuration>
      </Logger>
      <Logger friendlyName="html" enabled="True">
        <Configuration>
          <LogFileName>foo.html</LogFileName>
        </Configuration>
      </Logger>
    </Loggers>
  </LoggerRunSettings>
</RunSettings>

```

**Comment by nohwnd** [comment]
https://github.com/MicrosoftDocs/visualstudio-docs/pull/5482

**Comment by nohwnd** [comment]
https://github.com/MicrosoftDocs/visualstudio-docs/pull/5483
