### ISSUE TITLE
Incomplete documentation for Translation layer and generate xml for IntelliSense to work

### ISSUE THREAD

**Issue by jayaranigarg** [Microsoft/vstest#237]
## Description
Documentaion for Translation layer APIs is not complete. Also IntelliSense currently does not work for TranslationLayer Nuget package. Generate appropriate xmls for same and include them in Nuget Package.

## Steps to reproduce
1. Fill in the gaps in documentation for TranslationLayer code.
2. Also generate xml files and place them in Nuget Packages so as for IntelliSense to work.

## Environment
Using this Nuget package:
Microsoft.TestPlatform.TranslationLayer.15.0.0-preview-20161110-01

**Comment by singhsarab** [comment]
Associated pull requests.
https://github.com/Microsoft/vstest/pull/457
https://github.com/Microsoft/vstest/pull/464
