### ISSUE TITLE
xUnit under VSTest.Console does not always use the correct .NET Framework runtime - report false test failures

### ISSUE THREAD

**Issue by TalAloni** [microsoft/vstest#2376]
I have created a minimal xUnit test project demonstrating the problem (the test project use the SDK-style csproj, and target net472).
when running the test with 'dotnet test' and on some machines also VSTest.Console, it will throw the following exception:
System.ArgumentException : The specified value is not valid in the 'SslProtocolType' enumeration.
This exception is not thrown by .NET Framework 4.7.2

This issue does not occur with MSTest v2.

Project demonstrating the problem:
https://github.com/TalAloni/dotnettest-xunit

**Comment by nohwnd** [comment]
Thanks for reporting, I see the same. I took your code and put it into net472 console app and it succeeded, and then put it in net451 app and it crashed with the error that you've shown. This is most likely due to testhost.exe being compiled against net451. 

Reposting similar my repro, using your code in case you'd delete the repo before we fix this. 

```csproj
<!-- file net.csproj -->
<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <!-- change to net451 to see it fail, this shows that testhost.exe is also running using net451 rather than net472 -->
    <TargetFramework>net472</TargetFramework>
  </PropertyGroup>

</Project>

```

```cs
// file Program.cs
using System;
using System.IO;
using System.Net.Security;
using System.Security.Authentication;

namespace net
{
    class Program
    {
        static void Main(string[] args)
        {
            MemoryStream stream = new MemoryStream();
            SslStream sslStream = new SslStream(stream);
            sslStream.BeginAuthenticateAsClient("google.com", null, SslProtocols.None, false, new AsyncCallback(ProcessInformation), nul
l);
        }

         static void ProcessInformation(IAsyncResult result)
        {
        }
    }


}

```
