### ISSUE TITLE
Passing test run parameters not working and breaks old method for overriding run settings

### ISSUE THREAD

**Issue by TroyWalshProf** [microsoft/vstest#2377]
## Description
With the newest release of VSTest I can no long pass in test run parameters.
This hack working a week ago:
`dotnet vstest tests.dll --TestCaseFilter:TestCategory=Smoke --Settings:Parallel.RunSettings -- TestRunParameters/Parameter[contains(@name,'Browser')]/@value="Chrome"`
So now I get the following error:
> The test run parameter argument 'TestRunParameters.Parameter(name=Browser,' is invalid. Please use the format below.
>      Format: TestRunParameters.Parameter(name=\"<name>\", value=\"<value>\")

Given the error I should be able to do this instead:
`dotnet vstest tests.dll --TestCaseFilter:TestCategory=Smoke --Settings:Parallel.RunSettings -- TestRunParameters.Parameter(name="Browser",value="Chrome")`
but I still get the same parameter argument error.

Note*  This is almost certainly related to @singhsarab changes in  #2251
## Steps to reproduce
1. Create a simple test
2. Run
`dotnet vstest tests.dll -- TestRunParameters.Parameter(name="Browser",value="Chrome")`
or
`"C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\Common7\IDE\CommonExtensions\Microsoft\TestWindow\vstest.console.exe" vstest tests.dll -- TestRunParameters.Parameter(name="Browser",value="Chrome")`
3. Note the error VSTest returns

## Expected behavior
There would be some way pass in test run parameters

## Actual behavior
No matter what I do I get the following error:

> The test run parameter argument 'TestRunParameters.Parameter(name=Browser,' is invalid. Please use the format below.
>      Format: TestRunParameters.Parameter(name=\"<name>\", value=\"<value>\")

## Diagnostic logs
See: https://github.com/TroyWalshProf/ActionsSample/runs/539569841?check_suite_focus=true

## Environment
1. GitHub actions using windows-latest build agent
 - see: https://github.com/TroyWalshProf/ActionsSample/runs/539569841?check_suite_focus=true
2. Local Windows 10 using latest VS 2019 Enterprise install
3. Using VSTest console directly or "dotnet vstest"

**Comment by nohwnd** [comment]
@TroyWalshProf please see https://github.com/microsoft/vstest/issues/862#issuecomment-603894275 for some workarounds and explanation. You will need to do some escaping, which will also depend on whether you run the commands from cmd or powershell. Because vstest does not route via msbuild you should be able to escape it like this, and in the same way for vstest.console.

```powershell
# powershell
dotnet vstest tests.dll -- 'TestRunParameters.Parameter(name=\"Browser\",value=\"Chrome\")'
```
or 
```cmd
REM cmd
dotnet vstest tests.dll -- TestRunParameters.Parameter(name=\"Browser\",value=\"Chrome\")
```


We will be working on improving this, but can't promise any date.

**Comment by nohwnd** [comment]
Tracking in #862
