### ISSUE TITLE
How to get output sent to `dotnet vstest` output sink with `dotnet test`?

### ISSUE THREAD

**Issue by togakangaroo** [microsoft/vstest#2389]
[See this SO question](https://stackoverflow.com/questions/61087246/xunit-show-itestoutputhelper-output-when-run-in-the-console).

Basically, I am using xUnit and would like to be able to see messages output in console output with `dotnet watch test`. Those messages get sent to the `dotnet vstest` sink and I don't know how to get them to display.

**Comment by nohwnd** [comment]
This was answered in the linked StackOverflow question.
