### ISSUE TITLE
System.Runtime not found

### ISSUE THREAD

**Issue by nohwnd** [microsoft/vstest#2402]
## Description
Test run fails with

Failed to discover tests from assembly My.Tests.dll. Reason:Could not load file or assembly 'System.Runtime, Version=4.2.1.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' or one of its dependencies. The system cannot find the file specified.

**Comment by nohwnd** [comment]
You are seeing this because you are running .NET Core tests in .NET Framework runner. This is because vstest.console will inspect your assembly and check the `TargetFramework` assembly attribute. When the attribute is not present it will fall back .NET Framework runner. 

This starts test host that is built for .NET Framework, and not .NET Core. The adapter for example MSTest, will try to load your assembly as reflection only and will fail to resolve the System.Runtime with that version.

To fix this specify the /Framework parameter to the runner in some way, either directly or via RunSettings. Or review your build process to avoid removing that attribute from the assembly. 

```shell
vstest.console.exe My.Tests.dll /framework:netcoreapp2.1
```

Looking at a correct assembly in ILSpy: 
![image](https://user-images.githubusercontent.com/5735905/79223894-7c8d1a80-7e5a-11ea-92af-7f01a09f3508.png)

Looking at incorrect assembly in ILSpy:
![image](https://user-images.githubusercontent.com/5735905/79224548-8f541f00-7e5b-11ea-8a17-a3862bcd14ee.png)

**Comment by quasarea** [comment]
required adding entry in csproj (second)
```
    <GenerateTargetFrameworkAttribute>false</GenerateTargetFrameworkAttribute>
```
mind that its not:
```
    <GenerateAssemblyInfo>false</GenerateAssemblyInfo>
```
