### ISSUE TITLE
Why is the default verbosity quiet for the VSTest target?

### ISSUE THREAD

**Issue by ViktorHofer** [microsoft/vstest#2413]
The quiet log level was introduced by @Faizan2304 [here](https://github.com/dotnet/sdk/blame/43df9a170d485f5309dedd2895e30175295388fb/src/dotnet/commands/dotnet-test/Program.cs#L97) and is still in the product as-is.

The other dotnet verbs run with minimal verbosity instead of quiet by default. This currently swallows all outputs from targets that are sequenced before or after VSTest. The output on minimal and quiet is identical which makes this even more questionable.

Example:
```
  <Target Name="GenerateCoverageReport"
          Condition="'$(VSTestCollect)' == 'XPlat code coverage'"
          AfterTargets="VSTest">

    <Exec Command="$(CoverageReportCommand)" />       <!-- output swallowed
  </Target>
```

cc @nohwnd @ManishJayaswal

**Comment by nohwnd** [comment]
I don't know,  probably because they did not want the output from the build to be seen in the pipeline? That output is a bit of an implementation detail. But if everyone else uses minimal then we should look at that option as well.

**Comment by ViktorHofer** [comment]
> probably because they did not want the output from the build to be seen in the pipeline?

The output with `minimal` and `quiet` is identical. I could imagine it was different back in 2016.

> But if everyone else uses minimal then we should look at that option as well.

I'll send a PR to dotnet/sdk.

**Comment by ViktorHofer** [comment]
Ok found a difference between the minimal and quiet log levels. The incremental build logging is hidden even though the incremental restore is shown... I'm in favor of switching to the minimal level as hiding such details and with that potential output logging doesn't feel right.

### Quiet verbosity
```
C:\git\runtime3\src\libraries\System.Text.RegularExpressions\tests>dotnet test -f netcoreapp5.0
Microsoft (R) Build Engine version 16.7.0-preview-20215-01+aa655667e for .NET Core
Copyright (C) Microsoft Corporation. All rights reserved.

  Determining projects to restore...
  All projects are up-to-date for restore.
Test run for C:\git\runtime3\artifacts\bin\System.Text.RegularExpressions.Tests\netcoreapp5.0-Debug\System.Text.RegularExpressions.Tests.dll(.NETCoreApp,Version=v5.0)
Starting test execution, please wait...
```

### Minimal verbosity
```
C:\git\runtime3\src\libraries\System.Text.RegularExpressions\tests>dotnet test -f netcoreapp5.0 -v m
Microsoft (R) Build Engine version 16.7.0-preview-20215-01+aa655667e for .NET Core
Copyright (C) Microsoft Corporation. All rights reserved.

  Determining projects to restore...
  All projects are up-to-date for restore.
  TestUtilities -> C:\git\runtime3\artifacts\bin\TestUtilities\netcoreapp5.0-Debug\TestUtilities.dll
  System.Text.RegularExpressions.Tests -> C:\git\runtime3\artifacts\bin\System.Text.RegularExpressions.Tests\netcoreapp5.0-Debug\System.Text.RegularExpressions.Tests.dll
Test run for C:\git\runtime3\artifacts\bin\System.Text.RegularExpressions.Tests\netcoreapp5.0-Debug\System.Text.RegularExpressions.Tests.dll(.NETCoreApp,Version=v5.0)
Starting test execution, please wait...
```
