### ISSUE TITLE
RunSettings auto-detection for assembly invocation scenarios

### ISSUE THREAD

**Issue by ViktorHofer** [microsoft/vstest#2418]
Following up on https://github.com/microsoft/vstest/issues/2229#issuecomment-571822652.

If no .runsettings file is passed to vstest.console on an assembly invocation (ie dotnet test abc.dll), it should search for one in the test assembly's directory. The cwd could be used as a probing location as well.

cc @nohwnd @vritant24

**Comment by mcichonqa** [comment]
Hi, is there any way to execute tests which have runsettings for own dll from cmd?
I don't know if this is possible at the moment, I couldn't find an answer to my question.

I used this, but it doesn't load dll's runsettings files.

`dotnet vstest Test1.dll Test2.dll Test3.dll`

I'm using netcoreapp3.1 and VS 16.8.2.

**Comment by ViktorHofer** [comment]
Nope, that isn't possible as dotnet test / vstest only works with a single .runsettings file when operating on n assemblies.

**Comment by mcichonqa** [comment]
Thanks for answer @ViktorHofer.

**Comment by nohwnd** [comment]
This is a new feature and won't be implemented, we are focusing on adding new features to Testing.Platform instead. https://aka.ms/testingplatform

But I do agree that having to set runsettings in VS or explicitly provide them in console is annoying and it would be very helpful to have a default place where settings are found, like nuget.config, Directory.Build.Props etc.
