### ISSUE TITLE
dotnet test help message and docs need to be updated to reflect test and vstest verb convergence 

### ISSUE THREAD

**Issue by ViktorHofer** [microsoft/vstest#2423]
With https://github.com/dotnet/toolset/commit/1214ec9da622b4a751230a6c2240b1c103791728#diff-3e71c85821fdc972adec6f9e60e2541e, `dotnet test` now also supports invoking an assembly which makes dotnet vstest de facto obsolete. The docs and `dotnet test` help message needs to be updated to reflected the added feature.

**Comment by Evangelink** [comment]
As far as I can tell, the documentation was correctly updated. I will move forward by closing this issue, if you see some place not updated, please let us know.
