### ISSUE TITLE
CodeCoverage.exe as dotnet tool nuget package

### ISSUE THREAD

**Issue by dmarzo** [microsoft/vstest#2424]
Command `dotnet test --collect:"Code coverage"` generate file in binary format, to process with for example [reportgenerator](https://github.com/danielpalme/ReportGenerator), convert is required https://github.com/microsoft/vstest/issues/1939:
`CodeCoverage.exe analyze /output:example.coveragexml  example.coverage`
Package Microsoft.CodeCoverage.16.6.1.nupkg\build\netstandard1.0\CodeCoverage\ contains .exe and binaries that can be extracted into a local directory and works, but is usefull if can install, as for example:
`dotnet tool install Microsoft.CodeCoverage.Console --global`

[AB#1343593](https://devdiv.visualstudio.com/0bdbc590-a062-4c3f-b0f6-9383f67865ee/_workitems/edit/1343593)

**Comment by agent00jackson** [comment]
Bumping this.

**Comment by jakubch1** [comment]
You can try out new code coverage global tool from here:
https://dev.azure.com/dnceng/public/_packaging?_a=package&feed=test-tools&package=Microsoft.CodeCoverage.Console&protocolType=NuGet&version=17.0.0-beta.21329.1

This is still preview version. It's supporting merging of .coverage files with `xml` and `coverage` format outputs. 
For example: `codecoverage merge *.coverage -r -f xml` will merge all coverage files in current directory and subdirectories and output it in xml format.

**Comment by PureKrome** [comment]
@jakubch1 heya! is there / will there be any blog post, etc ... about this new global tool? Does this work on any OS?

**Comment by jakubch1** [comment]
We will create blog post or at least some documentation soon. Tool is uploaded to nuget.org:
https://www.nuget.org/packages/Microsoft.CodeCoverage.Console/

Currently it contains 2 commands:

1. Merge - fully cross-plat (can be also used for convert)
2. Collect - available for Win x86, Win x64 and Linux x64

**Comment by onionhammer** [comment]
@jakubch1 How do you get dotnet-coverage to exit with a non-zero exit code if tests fail?
