### ISSUE TITLE
Coverlet doesn't work when the test assembly is invoked directly

### ISSUE THREAD

**Issue by ViktorHofer** [microsoft/vstest#2433]
The `Coverlet.collector` data collector is resolved based on the `VSTestTestAdapterPath` property: https://github.com/microsoft/vstest/blob/d8bc445c7e127598a3b004253c68d266df01544f/src/vstest.console/Processors/CollectArgumentProcessor.cs#L128-L144. 
That property is set before VSTest executes: https://github.com/coverlet-coverage/coverlet/blob/3c55332ccee37d3c9cfbbf28a33e219fe7eaa40d/src/coverlet.collector/build/netstandard1.0/coverlet.collector.targets#L21.

The problem with relying on an msbuild property being set is that the data in-proc collector can't be resolved when an assembly is invoked via `dotnet test` or `dotnet vstest`:

```
PS C:\git\runtime3\artifacts\bin\System.Text.RegularExpressions.Tests\net5.0-Debug> dotnet test System.Text.RegularExpressions.Tests.dll

Microsoft (R) Test Execution Command Line Tool Version 16.7.0-dev
Copyright (c) Microsoft Corporation.  All rights reserved.

Starting test execution, please wait...

A total of 1 test files matched the specified pattern.
Data collection : Unable to find a datacollector with friendly name 'XPlat code coverage'.
Data collection : Could not find data collector 'XPlat code coverage'
```

This works well in a `dotnet publish` scenario as the required assemblies are copied into the publish directory: https://github.com/coverlet-coverage/coverlet/blob/3c55332ccee37d3c9cfbbf28a33e219fe7eaa40d/src/coverlet.collector/build/netstandard1.0/coverlet.collector.targets#L12-L18

There are two ways to solve that:
1. Copy the coverlet.collector binaries not just during publish but also during the build into the app's output directory. The obvious major downside of that approach is that it bloats the output directory, especially as coverlet.collector relies on many other helper assemblies which would need to be copied over as well.
2. Read the test app's deps.json file to determine the path to coverlet.colletor's data collector if the coverlet.collector.dll isn't present in the output directory. Other components in VSTest are already doing that (I believe the testhost?).

cc @MarcoRossignoli @nohwnd

**Comment by MarcoRossignoli** [comment]
> Read the test app's deps.json

You mean something like https://github.com/coverlet-coverage/coverlet/blob/master/src/coverlet.core/Instrumentation/CecilAssemblyResolver.cs#L173

**Comment by ViktorHofer** [comment]
Exactly

**Comment by MarcoRossignoli** [comment]
Need to check better(busy at the moment) but I think it works if build with `<PreserveCompilationContext>`

**Comment by ViktorHofer** [comment]
I assumed this works without `PreserveCompilationContext` being set. If it requires that switch, that would be a stopper.

**Comment by MarcoRossignoli** [comment]
Maybe it works I had issue with shared framework references, I don't know if there are issue with nuget ref https://github.com/dotnet/sdk/blob/master/toolset/Documentation/specs/runtime-configuration-file.md#opt-in-compilation-data

**Comment by nohwnd** [comment]
@MarcoRossignoli  is this something that needs to be solved, or it can be closed?

**Comment by MarcoRossignoli** [comment]
I don't think it's solved but it's really old I wonder if it's still an issue. The chance looks not super quick(read the deps to find out coverlet extension).

**Comment by ViktorHofer** [comment]
Yes, this is still an issue.
