### ISSUE TITLE
dotnet test -t do not list right result with mstest/nunit

### ISSUE THREAD

**Issue by athinboy** [microsoft/vstest#2435]
as follow:
https://github.com/dotnet/sdk/issues/11503

sorry i can not find the root cause,and i had wait for  dotnetsdk  tens of day,thanks!

**Comment by nohwnd** [comment]
@athinboy Hello, I did not look how you implement explorer, but guessing from the other issue you are running `dotnet test` and parsing the output? 

There is probably a better way to do that and that would be this wrapper that allows you to interact with vstest console and get the actual objects from it. 

https://github.com/microsoft/vstest/blob/57527561e6342aaaaca4012dc14d25ad08c0a326/src/Microsoft.TestPlatform.VsTestConsole.TranslationLayer/VsTestConsoleWrapper.cs

The wrapper is used by other tools (e.g. Stryker), but hopefully the way we use it in our repo will help you get started: https://github.com/microsoft/vstest/search?q=vstestconsolewrapper&unscoped_q=vstestconsolewrapper

**Comment by athinboy** [comment]
@nohwnd  thanks for you reply,and sorry for my poor english!

the vscode-dotnet-test-explorer depends on the output of dotnet test -t . As stated in issue #11503,
the output of "dotnet test -t "(maybe vstest) is different for mstest/xunit/nuit, it show the full qualitified name like "XunitTests.TestClass1.Fail3" for xunit only! So vscode-dotnet-test-explorer  can not identify the test method exactly when test project is based on nunit/mstest. 
I have some question:
1、why does visual studio work correctly? I dont't know how VS work .
2、why do  vstest  not output the full qualitified  name for mstest/nunit?
The "dotnet test -t " is the only cmd command that can be invoke in npm.
I will study of this ,thanks again!

**Comment by athinboy** [comment]
It is same case: 

 dotnet vstest -lt .\TestClient.dll

the output is :
    WrapTest_One
    Test
    Test1
    Test2
    A
    Test
    Test
    One

**Comment by nohwnd** [comment]
> 1、why does visual studio work correctly? I dont't know how VS work .

VS uses the wrapper to communicate with the vstest console and gets much richer objects that what is printed to the console. 

2、why do vstest not output the full qualitified name for mstest/nunit? 

This is controlled by what the adapter sets in the result object, vstest does not control that.
