### ISSUE TITLE
VSTest installation failure

### ISSUE THREAD

**Issue by stevenf977** [microsoft/vstest#2447]
While running azure pipeline vstest task.  We are getting the error below:
**##[error]Failed to download version 16.6.1 of the test platform with error Error: Failed rmRF: rm: could not remove file (code EPERM): D:\azuredevops-buildagent02\_work\_tool\VsTest\16.6.1\x64/tools/net451/Common7/IDE/CommonExtensions/Microsoft/IntelliTrace/Microsoft.IntelliTrace.Profiler.dll**

it seems to happen at least once a day.  The only way I've been able to resolve it is to reboot my build server.   I attached the log file of the error.  Please advise
[logfile.txt](https://github.com/microsoft/vstest/files/4690847/logfile.txt)

**Comment by nohwnd** [comment]
@jakubch1 seen this before?

**Comment by jakubch1** [comment]
@stevenf977  do you have code coverage enabled? When running tests are you spawning some additional processes?

**Comment by stevenf977** [comment]
Code coverage is enabled.  When we run tests, there are no other processes running with it.  We do have multiple agents on the servers.  3 agents running on each build server.  We have started doing some heavy unit testing in the last couple of months.  Can one agent interfere with the other.  I was under the impression that each agent has their own installation of the vstest installation.

> @stevenf977 do you have code coverage enabled? When running tests are you spawning some additional processes?

**Comment by Evangelink** [comment]
@stevenf977 Are you still experiencing this issue with newer versions?
