### ISSUE TITLE
Is it possible to write custom test execution plugin

### ISSUE THREAD

**Issue by angelovstanton** [microsoft/vstest#2448]
I am sorry if I am not writing in the right channel regarding this question. You can redirect me to the right one if this is not the place.
I did research and read most of the links you provided in the readme but couldn't figure out whether my case is supported. I am wondering whether there is a way to change how dotnet test executes the tests (create a plugin, extension or something like that). In my project, we want to run our Selenium UI tests instead on the current machine using threads, etc. - in parallel through Azure functions. We have the cloud setup and everything, but instead of writing our own test runner with logic to locate the tests for all major unit testing frameworks, I was wondering whether it is possible to reuse vstest infrastructure and change the behavior a bit to fit our needs, I imagine that I will need to change only how the tests are executed and the class, test ints/cleanup, etc.

**Comment by nohwnd** [comment]
Closest to what you want is probably implementing your own : ITestRuntimeProvider. This is how we implement one that starts dotnet test host. https://github.com/microsoft/vstest/blob/3f18c870db1776dab9c94e7b819c0dad90ff9686/src/Microsoft.TestPlatform.TestHostProvider/Hosting/DotnetTestHostManager.cs

It will be then discovered, loaded, and based on `CanExecuteCurrentRunConfiguration` it will be used or not. From there you can start what ever run you want per source. As long as you communicate the results back. 

So you probably want some kind of a proxy that will run the tests, and stream the results back. Unfortunatel I don't know enough about Azure functions to give your full plan, but I guess you will want to run testhost, there pointing to the source (dll) that has your tests.

**Comment by angelovstanton** [comment]
Thank you for the fast response I will check it!
