### ISSUE TITLE
Microsoft.TestPlatform.ObjectModel packages the wrong dlls

### ISSUE THREAD

**Issue by dfederm** [microsoft/vstest#2458]
## Description
The Microsoft.TestPlatform.ObjectModel package has netcoreapp2.1 dlls in the netstandard2.0 folder.

## Steps to reproduce
N/A

## Expected behavior
The dlls in the netstandard2.0 dir target netstandard2.0

## Actual behavior
The dlls in the netstandard2.0 dir target netcoreapp2.1

![image](https://user-images.githubusercontent.com/6445614/84179031-33aca900-aa3a-11ea-9da4-669fc0a0022c.png)

**Comment by dfederm** [comment]
It looks like this is due to the nuspec specifying `$NetCoreTargetFramework$`:

https://github.com/microsoft/vstest/blob/8ee627ea54aba31b941e5d45a1a1614b50f7befb/src/package/nuspec/TestPlatform.ObjectModel.nuspec#L42-L44

Which from looking at the build scripts is `netcoreapp2.1`

https://github.com/microsoft/vstest/blob/8ee627ea54aba31b941e5d45a1a1614b50f7befb/scripts/build.ps1#L98

**Comment by Evangelink** [comment]
This is now fixed.
