### ISSUE TITLE
Custom Collector does not emit Console.WriteLine to console

### ISSUE THREAD

**Issue by mide1234** [microsoft/vstest#2465]
## Description
When running `dotnet test` with --collect `CustomCollector` Console.WriteLine is not emitted into the console. Is it intended by design or can it be considered as a bug?

## Steps to reproduce

1. Create a custom collector like the following:
```
    [DataCollectorFriendlyName("SampleDataCollector")]
    [DataCollectorTypeUri("my://sample/datacollector")]
    public class SampleDataCollector: DataCollector
    {
        public override void Initialize(
            System.Xml.XmlElement configurationElement,
            DataCollectionEvents events,
            DataCollectionSink dataSink,
            DataCollectionLogger logger,
            DataCollectionEnvironmentContext environmentContext)
        {
            events.TestCaseEnd += this.Events_TestCaseEnd;
        }

        private void Events_TestCaseEnd(object sender, TestCaseEndEventArgs e)
        {            
            Console.WriteLine("Hello world!");
        }
    }
```

2. Place it in a new project (the assembly name must end with "collector")
3. Reference this collector project in some test project
4. in console run `dotnet test TestProjectFolder --collect SampleDataCollector`
5. check there is no sign of "Hello world!" in the console

## Expected behavior
Console.WriteLine is emitted to the console.

## Actual behavior
Console.WriteLine is NOT emitted to the console.

## Environment
Windows 10, netstandard2.0, netcore3.1

**Comment by mide1234** [comment]
Also note that using the DataCollectionLogger is not much helpful as it offers only logging an error or a warning. In my case it is more about logging a progress. Anyway the logger does not emit the message immediately but it seems to be kept by some `dotnet test` buffer which is emited to the console at the very end of `dotnet test` command. 

I believe it would be nice to have the option to print some message immediately..

**Comment by nohwnd** [comment]
This is by design.
