### ISSUE TITLE
[loc][Query][OSS_VSTest] Localizability of 0; "AccessDenied"

### ISSUE THREAD

**Issue by PDostalek** [microsoft/vstest#2466]
Hello developers,
please help localization team to answer question from translator.
In case translator is not sure about context/meaning/localizability of string we raise a question.

Id | File Name Live Page Extended | String Resource ID | Full Source String | Extended Description | Answer Needed By
-- | -- | -- | -- | -- | --
50754 | Microsoft.TestPlatform.Common\Resources\xlf\Resources.xlf | 0; "AccessDenied" | {0} Access denied while trying   to create "TestResults" folder in mentioned location. You are   getting this exception because you are running vstest.console.exe from a   folder which requires having write access. To solve the issue: please  run vstest.console.exe from a folder where   you have write privileges. For more information, please look at the error   message: | Please clarify the placeholder. |  
50769 | Microsoft.TestPlatform.Common\Resources\xlf\Resources.xlf | 0;   "AccessDenied" | {0}   Access denied while trying to create "TestResults" folder in   mentioned location. You are getting this exception because you are running   vstest.console.exe from a folder which requires having write access. To solve   the issue: please  run   vstest.console.exe from a folder where you have write privileges. For more   information, please look at the error message: | Please   let us know more info for "{0}". |

**Comment by Sanan07** [comment]
@PDostalek Placeholder {0} - is original exception message. For instance : "Access to the path 'C:\Program Files (x86)\Microsoft Visual Studio\2019\Preview\TestResults\aadcaa8d-9f03-49ba-8a95-376647689faa' is denied". So full error message can look like this : 
![tempsnip](https://user-images.githubusercontent.com/8465726/84898236-35fcac00-b0a7-11ea-8cca-4aba454e7e0e.png)

**Comment by Sanan07** [comment]
@PDostalek Is everything clear for you now? Can we close the issue?

**Comment by PDostalek** [comment]
Thank you
