### ISSUE TITLE
Test host process crashed with SQLite being using inside Docker

### ISSUE THREAD

**Issue by leealexander** [microsoft/vstest#2467]
## Description
Running dotnet test against a test which uses SQLite crashes in Docker using  image "mcr.microsoft.com/dotnet/core/sdk:3.1-alpine3.12" vs "mcr.microsoft.com/dotnet/core/sdk:3.1-alpine3.11 " which works.

## Steps to reproduce
Please find attached project...I have two docker files only different in the image version of .net sdk used. Run the bat file "RunTestVersions.bat" which will demonstrate the working version vs the failing one.

## Expected behavior
> Test should run without error

## Actual behavior
> Crashes with "The active test run was aborted. Reason: Test host process crashed"

>>Environment
* Windows  10 
* Docker for Desktop 2.3.0.3 (45519
[SqlLiteFails.zip](https://github.com/microsoft/vstest/files/4799093/SqlLiteFails.zip)
)

**Comment by liiri** [comment]
I couldn't get sqlite to work with .NET core in Alpine at all. Not via service or test. Installing sqlite packages didn't help either.
I ended up moving to a Debian based image.
