### ISSUE TITLE
VSTest doesn't support MSIX

### ISSUE THREAD

**Issue by jamers99** [microsoft/vstest#2476]
## Description
UWP now generates MSIX packages instead of APPX. APPX was supported by VSTest, but the new MSIX is not.
I also created this [StackOverflow question](https://stackoverflow.com/q/62767937/3609052) for the issue.

## Steps to reproduce
Build a UWP unit test project with a min version of 1809+
Generate the package for the unit test project
Run vstest.console.exe with the path to the generated MSIX path
```
vstest.console.exe "C:\AppPackages\UnitTestProject\UnitTestProject_1.0.0.0_Debug_Test\UnitTestProject_1.0.0.0_x86_Debug.msix" /TestAdapterPath:"C:\AppPackages\UnitTestProject\UnitTestProject_1.0.0.0_Debug_Test\"
```

## Expected behavior
It should run the unit tests in the project

## Actual behavior
No tests are discovered

## Diagnostic logs (diag)
```
No test discoverer is registered to perform discovery for the type of test source 'C:\AppPackages\UnitTestProject\UnitTestProject_1.0.0.0_Debug_Test\UnitTestProject_1.0.0.0_x86_Debug.msix'. Register a test discoverer for this source type and try again.
```

## Environment
Visual Studio 2019 Enterprise
Windows 10 Pro 10.0.18363.900
vstest.console build version 16.6.0

**Comment by jamers99** [comment]
FYI, I just found that I can rename the MSIX to APPX and run the tests against that. So really the discoverer needs to just have the msix extension added.

**Comment by MSLukeWest** [comment]
This is supported, I just tried using this syntax and it worked:

vstest.console.exe /framework:FrameworkUap10 UnitTestProject4_1.0.0.0_x86_Debug.msix

I noticed you're supplying the TestAdapterPath argument, perhaps the problem is with the custom adapter.

**Comment by jamers99** [comment]
I tried with and without, but it didn't work....

**Comment by jamers99** [comment]
That worked! Thanks!

**Comment by jamers99** [comment]
There should be documentation for this somewhere before this issue is closed.

**Comment by nohwnd** [comment]
Looks like there is bit more work to be done, because the Framework parameter forces a framework to be used, and then I guess the UWP discoverer is selected based on that framework (the dotnet and .NET Framework work like that).

So it would be useful to see which framework it detects when used with msix and with appx.

Could you try enabling the diag logs and searching them for:

```
vstest.console, Determined framework for all sources:
```

You enable the logs like this: 

```shell
vstest.console xunit1.dll /Diag:c:\temp\discovery\log.txt
```

**Comment by nohwnd** [comment]
Thinking about it a bit more, maybe we can't do that, because from what I understood, MSIX is more general than just packing UWP, so we would not know what test payload is there.

**Comment by mcooley** [comment]
@nohwnd I think this should be reconsidered (and I opened #2943 with a suggested change).

There is no difference whatsoever between .appx and .msix files--it's just a different file extension (and brand). A .msix file could contain non-UWP test payload...but so could an .appx file. I think vstest should treat them the same way.
