### ISSUE TITLE
Cannot update Microsoft.NET.Test.Sdk from v16.0.1 to v16.6.1

### ISSUE THREAD

**Issue by SetTrend** [microsoft/vstest#2486]
When I try to update Microsoft.NET.Test.Sdk from v16.0.1 to v16.6.1 I get the following error message:

```
Cannot modify an evaluated object originating in an imported file "C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\MSBuild\Microsoft\WindowsXaml\v16.0\Microsoft.Windows.UI.Xaml.Common.targets".				
```

![grafik](https://user-images.githubusercontent.com/9283914/87842523-563da780-c8ad-11ea-8105-33207d76f793.png)

So, I'm not able to update.

**Comment by Sanan07** [comment]
@SetTrend Were you able to fix the issue? I suppose, it is not relating to Test Platform. Try to manually add package reference to you .csproj file. `<PackageReference Update="Microsoft.NET.Test.Sdk" Version="16.6.1" />`

**Comment by nohwnd** [comment]
This is happening because the version is hardcoded, it was fixed internally, but probably not shipped, here is a workaround: 

https://developercommunity.visualstudio.com/content/problem/1117910/cannot-update-microsoftnettestsdk-from-v1601-to-v1.html

**Comment by SetTrend** [comment]
Thanks guys, for helping and fixing this issue! 👍

So, if I get you right, for this particular project of mine the workaround will do its job.

The original version (v16.0.1) was linked to by a project template. Is it the v16.0.1 version that's containing the hard coded part? If so, will the Visual Studio 2019 project templates be updated accordingly to refer to the latest version so new projects won't fall into this kind of trap?

**Comment by nohwnd** [comment]
Yes, we will be updating the version when releasing. For some reason it hasn't been done for a long time, and I was not aware of it when taking over this codebase.

**Comment by SetTrend** [comment]
Excellent. Closing now.
