### ISSUE TITLE
Getting “StackExchange.Redis.RedisConnectionException” while running tests with runsettings

### ISSUE THREAD

**Issue by sanoopkarakkat** [microsoft/vstest#2490]
## Description

I am facing an issue while trying to run the test using runsettings file. We have one redis cache with SSL enabled which we are trying to access from our tests.

StackExchange.Redis.RedisConnectionException: No connection is available to service this operation: SET sample.TM.test|ConnectionSample|System.String|Sample ---> StackExchange.Redis.RedisConnectionException: SocketFailure on .cache.windows.net:6380/Subscription, origin: Connected, input-buffer: 0, outstanding: 0, last-read: 1s ago, last-write: 1s ago, unanswered-write: 464270s ago, keep-alive: 60s, pending: 0, state: Connecting, last-heartbeat: never, last-mbeat: -1s ago, global: 1s ago, mgr: Inactive, err: never ---> System.IO.IOException: Unable to read data from the transport connection: An existing connection was forcibly closed by the remote host. ---> System.Net.Sockets.SocketException: An existing connection was forcibly closed by the remote host

When are able to run the same tests without using this runsettings.

Is there anyway I can successfully run the tests without migrating to MSTest V2?

OR

Can I use the same Test Controller/Agent setup with MSTest V2 for running tests?

Please see the runsettings file that I am using. 
<?xml version="1.0" encoding="utf-8"?> 
<RunSettings> <RunConfiguration> <TargetPlatform>x86</TargetPlatform>  <ResultsDirectory>..\Portal\TestResults</ResultsDirectory> </RunConfiguration> <MSTest> <MapInconclusiveToFailed>True</MapInconclusiveToFailed> <CaptureTraceOutput>false</CaptureTraceOutput> <SettingsFile>Local.testsettings</SettingsFile> <ForcedLegacyMode>true</ForcedLegacyMode> </MSTest> </RunSettings> 

## Environment
> OS: Windows 10 (1909), vstest.console : 15.0.28307.421

**Comment by Sanan07** [comment]
@sanoopkarakkat Are these runsettings which you are using (x86 ..\Portal\TestResults True false Local.testsettings true)? Could you please provide content of you runsettings file or explain that options mean?

**Comment by sanoopkarakkat** [comment]
@Sanan07 I was able to solve this issue by adding following keys to the registry of my test agent machines.

[HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\.NETFramework\v4.0.30319]
"SystemDefaultTlsVersions"=dword:00000001
"SchUseStrongCrypto"=dword:00000001

[HKEY_LOCAL_MACHINE\SOFTWARE\WOW6432Node\Microsoft\.NETFramework\v4.0.30319]
"SystemDefaultTlsVersions"=dword:00000001
"SchUseStrongCrypto"=dword:00000001

Thanks for the reply.
