### ISSUE TITLE
Public API for accessing TestFilter while listing test

### ISSUE THREAD

**Issue by iskiselev** [microsoft/vstest#2502]
There is no public API to access test filter during test discovery for test adapters. There is issue nunit/nunit3-vs-adapter#438 that NUnit ignores TestCaseFilter while ListTests specified. But looks like there is no API in vstest to make this scenario working correct.
`ITestDiscoverer.DiscoverTests` accept `IDiscoveryContext`. It is implemented with  `Microsoft.VisualStudio.TestPlatform.CrossPlatEngine.Discovery.Implementation`, that contains `GetTestCaseFilter` function - but it is not accessible though interface.

**Comment by nohwnd** [comment]
I implemented this in XUnit, or at least a similar feature. Please review this code if it helps: https://github.com/xunit/visualstudio.xunit/pull/205/files
