### ISSUE TITLE
Search for adapters in project output directory by default

### ISSUE THREAD

**Issue by AbhitejJohn** [Microsoft/vstest#251]
## Description
Currently for users to run tests for test frameworks acquired by a nuget package from CLI, they would have to provide a testadapterpath in order for the test platform to understand which adapter can run these tests. Although this is left to the user today, it would be nice to have a smart default in the test platform to look for adapters assemblies paired up under the same folder the test assembly is in. This reduces the overhead for users and would provide a seamless experience to run tests.

## Steps to reproduce
> What steps can reproduce the defect?
> Please share the setup, commandline for vstest.console, sample project, target
> framework etc.

## Expected behavior
> Share the expected output

## Actual behavior
> What is the behavior observed?

## Environment
> Please share additional details about the test environment.
> Operating system, Build version of vstest.console

**Comment by sbaid** [comment]
@smadala @codito @pvlakshm How about including source directory in `testadapterpath` by default only if there is _only_ one source directory

That is 
* vstest.console c:\foo\mytest.mstest.dll [works]
* vstest.console c:\bar\mytest.xunit.dll [works]
* vstest.console c:\foo\mytest.mstest.dll c:\bar\mytest.xunit.dll [requires /testadapterpath to be specified explicitly]

On a side note - Does `/testadapterpath` support multi-value or single value only?

**Comment by smadala** [comment]
@sbaid /testadapterpath takes single value.
In TPv1 if multiple test assemblies passed, It looks for adapter from all assemblies directories.

**Comment by sbaid** [comment]
@smadala I am thinking we should enable most common scenario (example 1 & 2) above where `/testadapterpath:.` can be avoided and clearly there is only one folder that can be looked at for test adapter.

When user specifies multiple folder, looking for adapters in all folders by default may give unpredictable result since they can have different versions of adapters etc.  Having user specify `/testadapterpath` explicitly is likely better. 

@pvlakshm @codito

**Comment by AbhitejJohn** [comment]
I think that is a disparity in behavior and would result in a confusing experience. The part where we say that there are multiple versions of the adapters can be easily logged as a warning. In fact this is exactly how the vstest task behaves today(I'm not sure about the warning though). 

Lets go a little deeper into the third scenario
> vstest.console c:\foo\mytest.mstest.dll c:\bar\mytest.xunit.dll 

what would we expect the user to pass in as an adapter path?

**Comment by smadala** [comment]
Addressed in https://github.com/Microsoft/vstest/pull/1026.
