### ISSUE TITLE
Microsoft Coverage Collection is spaced

### ISSUE THREAD

**Issue by eddynaka** [microsoft/vstest#2519]
## Description
> **IMPORTANT**: if the defect is reproduced only in a workflow from within the Visual Studio IDE then do not report the issue here - instead, please report it using Visual Studio's "Send Feedback" option that can be accessed from the Help menu OR using this link https://developercommunity.visualstudio.com.
>
> For a defect reproducable from the vstest command line, describe the issue you've observed.

When I run the command:

`dotnet test --collect:"Code Coverage" --results-directory:"TestResults" --configuration Release --no-build -- RunConfiguration.DisableAppDomain=true`

It's showing spaced strings:
![image](https://user-images.githubusercontent.com/16199012/90236271-e8779380-ddf8-11ea-8cbf-7c38b3e273c2.png)

**this isn't something new, tested already with 16.6.1 and the new preview version**

## Steps to reproduce
> What steps can reproduce the defect?
> Please share the setup, commandline for vstest.console, sample project, target
> framework etc.

Run dotnet test command and check the output

## Expected behavior
> Share the expected output

I would expect that the text looks not spaced. Something like this:
![image](https://user-images.githubusercontent.com/16199012/90236362-080ebc00-ddf9-11ea-9c9b-e72e8eee263f.png)

## Actual behavior
> What is the behavior observed?

The text is spaced.

## Diagnostic logs
> Please share test platform diagnostics logs. Instructions to collect logs are [here](https://github.com/Microsoft/vstest-docs/blob/master/docs/diagnose.md#test-platform-diagnostics).  
> The logs may contain test assembly paths, kindly review and mask those before sharing.

## Environment
> Please share additional details about the test environment.
> Operating system, Build version of vstest.console

GitHub Actions / windows-latest
OR
Windows 10 (local machine) using any terminal (tested with stable Windows Terminal)

cc: @nohwnd

**Comment by eddynaka** [comment]
Adding more info: if we look at the logs generated by GitHub Actions, we can see this:

```
2020-08-14T02:39:01.0883248Z M�i�c�r�o�s�o�f�t� �(�R�)� �C�o�v�e�r�a�g�e� �C�o�l�l�e�c�t�i�o�n� �T�o�o�l� �V�e�r�s�i�o�n� �1�6�.�0�.�3�0�3�1�9�.�3�0�0�2�
2020-08-14T02:39:01.0884271Z �
2020-08-14T02:39:01.0884657Z �
2020-08-14T02:39:01.0885197Z �C�o�p�y�r�i�g�h�t� �(�c�)� �M�i�c�r�o�s�o�f�t� �C�o�r�p�o�r�a�t�i�o�n�.� � �A�l�l� �r�i�g�h�t�s� �r�e�s�e�r�v�e�d�.�
2020-08-14T02:39:01.0885559Z �
2020-08-14T02:39:01.0885892Z �
2020-08-14T02:39:01.0886195Z �
2020-08-14T02:39:01.0886519Z �
2020-08-14T02:39:01.1706448Z �
```

**Comment by nohwnd** [comment]
@jakubch1 do you know why this is?

**Comment by jakubch1** [comment]
I see the same strange output in test logs. We will fix it but this is not our priority now. @eddynaka  is this blocking you?

**Comment by eddynaka** [comment]
@jakubch1 not at all. Let me know if I can help 👍

**Comment by jakubch1** [comment]
@eddynaka  I'm not able to reproduce it anymore. Please reopen if you still see this issue using latest vstest.console and latest Microsoft.NET.Test.Sdk
