### ISSUE TITLE
MsTest & Xunit templates need to use UTF-8 encoding for UnitTest1.cs

### ISSUE THREAD

**Issue by sbaid** [Microsoft/vstest#252]
## Description
UnitTest1.cs is not created with UTF-8 encoding. Instead created with Western European - code page 1252 encoding. To see it - save as the file & use save with encoding option.

## Steps to reproduce
1. Using Create New Project (CNP) dialog  - Create a MSTest or Xunit .net core project
2. Add GB18030 characters into name of a test method - TestMethod1㐀㒣
3. Save & close the file
4. Open the file

## Expected behavior
File contents are ok

## Actual behavior
TestMethod1?? is seen

## Environment
Win10 + VS 2017 RC build - d15rel 25920.0

**Comment by sbaid** [comment]
@smadala I tried the following characters in the .NET core template for the test method. File save complained about saving the file with other encoding. Pl validate if the bug is fixed.

**Comment by codito** [comment]
Error that shows up.

![test_project_unicode](https://cloud.githubusercontent.com/assets/28766/24134834/d5c6167a-0e2c-11e7-8abb-34fbccd95002.png)

**Comment by smadala** [comment]
Verified in: 15.1(26405.3) vsuwpt. Files contents are intact without any warning.
