### ISSUE TITLE
Microsoft.NET.Test.Sdk v16.7.1 has incorrect dependency on Microsoft.TestPlatform.TestHost

### ISSUE THREAD

**Issue by jameswoodley** [microsoft/vstest#2530]
## Description
Microsoft.NET.Test.Sdk version 16.7.1 has a dependency on Microsoft.TestPlatform.TestHost >= 16.7.1 however that version of TestHost is not listed

## Steps to reproduce
Add Microsoft.NET.Test.Sdk version 1 to your project and receive error: 
```
Unable to find a stable package Microsoft.TestPlatform.TestHost with version (>= 16.7.1)
  - Found 96 version(s) in nuget.org [ Nearest version: 16.8.0-preview-20200806-02 ]
  - Found 0 version(s) in Microsoft Visual Studio Offline Packages
```
## Expected behavior
Package is installed

## Actual behavior
Package is not installed

**Comment by nohwnd** [comment]
@jameswoodley Could you retry please? I think you've just hit an intermittent problem with us publishing the test.sdk package to nuget before the testhost.

@cvpoienaru I usually upload the Test.SDK package last to avoid this. Can it be that you uploaded the TestHost package after the Test.SDK?

**Comment by nohwnd** [comment]
Looked at nuget and it looked correctly. Tried it locally, it works. Let us know if you still see the problem :)

**Comment by jameswoodley** [comment]
Can confirm, working now- many thanks!
