### ISSUE TITLE
CI test reporters

### ISSUE THREAD

**Issue by natemcmaster** [Microsoft/vstest#254]
dotnet-test-xunit and supported detecting CI build environments and reporting tests results in a format consumable by that CI environment. For example, building on AppVeyor and TeamCity would automatically light up test reporters. 

How can we do the same thing with VS Test? Is it already possible?

**Comment by onovotny** [comment]
This capability is currently done by the xUnit runner. We implement our own reporter extensibility mechanism that detects CI environment and interacts appropriately. An xUnit user can implement an interface and specify a command line option to pass in a custom reporter.

**Comment by tmat** [comment]
Jenkins supports xUnit format and trx. The problem with trx is size - it's >10x larger than xunit format :(. I'd like to be able to use xunit format in ```dotnet test```.

**Comment by Faizan2304** [comment]
Few CI reporters are available now:

| Scenario | Nuget Package | Source Repository |
| -------- | ------------- | ----------------- |
| Local, CI, CD | Inbuilt | [Trx Logger][] |
| Local, CI, CD | Inbuilt | [Console Logger][] |
| Local, CI, CD | [XunitXml.TestLogger][xunit.nuget] | [Xunit Logger][] |
| AppVeyor | [AppVeyor.TestLogger][appveyor.nuget] | [AppVeyor Logger][] |
| TeamCity | [TeamCity.VSTest.TestAdapter][teamcity.nuget] | [Teamcity Logger][] |

[Trx Logger]: https://github.com/Microsoft/vstest/tree/master/src/Microsoft.TestPlatform.Extensions.TrxLogger
[Console Logger]: https://github.com/Microsoft/vstest/blob/master/src/vstest.console/Internal/ConsoleLogger.cs
[Xunit Logger]: https://github.com/Faizan2304/LoggerExtensions
[AppVeyor Logger]: https://github.com/Faizan2304/LoggerExtensions
[TeamCity Logger]: https://github.com/JetBrains/TeamCity.VSTest.TestAdapter

[xunit.nuget]: https://www.nuget.org/packages/XunitXml.TestLogger
[appveyor.nuget]: https://www.nuget.org/packages/AppVeyor.TestLogger
[teamcity.nuget]: https://www.nuget.org/packages/TeamCity.VSTest.TestAdapter

Documentation for loggers are available [here](https://github.com/Microsoft/vstest-docs/blob/master/docs/report.md).

**Comment by omerlh** [comment]
Hey, are there plans to support Circle CI test runner? Look like they can parse [test results](https://circleci.com/docs/2.0/collect-test-data/) in a specific format (see xunit/xunit#1882)
