### ISSUE TITLE
What is expected behavior of AbortTestRun and CancelTestRun?

### ISSUE THREAD

**Issue by wiweinbe** [microsoft/vstest#2540]
## Description
We've implemented an IVsTestConsoleWrapper and are have ITestRunEventsHandler that monitors test execution. When running multiple iterations of a same test to gather performance data and the test is failing, we want to fail fast, rather than waste time continuing to run a test that is not yielding useful information (beyond the fact that something is broken).

## Steps to reproduce
Call VsTestConsoleWrapper.RunTests(testCases, runSettings, options, testRunEventsHandler);
testCases is an enumerable list of a single test case to run for several iterations (e.g., 12)
runSettings is valid runsettings XML, including <BatchSize>1</BatchSize> so testRunEvents are provided for every execution
testRunEventsHandler includes an implementation of HandleTestRunStatsChange that detects test failures and calls AbortTestRun when too many are seen.

## Expected behavior
I would expect that once AbortTestRun is called, no further testCases in the list will be executed.

## Actual behavior
All testCases are executed.

## Diagnostic logs
In this log, the abort case is simulated by calling AbortTestRun on every call to HandleTestRunStatsChange after the third one.
[diag2.log](https://github.com/microsoft/vstest/files/5126677/diag2.log)

## Environment
Microsoft Windows [Version 10.0.19041.450]
Microsoft (R) Test Execution Command Line Tool Version 16.8.0-preview-20200812-03

**Comment by Sanan07** [comment]
@wiweinbe If you want immediately stop test run you can use `wrapper.EndSession()` - where `wrapper` is object of your `VsTestConsoleWrapper`

**Comment by wiweinbe** [comment]
@Sanan07 That sounds like a really big hammer. But worth considering.

**Comment by Sanan07** [comment]
@wiweinbe After my quick investigation, I see that, `AbortTestRun()` calls asynchronously, so while aborting operation is executing, tests are running in another thread. `AbortTestRun` calls `HandleTestRunComplete` from `ITestRunEventsHandler` and complete execution.

I did my own test: using 300 empty test methods. I have condition: to abort after 10 test methods already executed, but it ended up aborting after 170 or 220 test method, during different runs.

I suppose, the same happens in your case : your tests are executing quite quickly, so they had finished before aborting started.
Try to increase number of tests and see if it aborts before all tests executed.

On other hand, `EndSession()` quits almost immediately, but you lose `TestRunStatistics` data while handling test run complete in `HandleTestRunComplete`.

Hope, that helps to understand.

**Comment by wiweinbe** [comment]
That is helpful. I've actually made progress on this and found that I get a more expected behavior by calling ``CancelTestRun``, instead of Abort (and by operating on a more realistic test case that takes some time to execute).
However, it appears that even in this case, the run acts more like it's aborted. Much of the end processing (what you note as ``HandleTestRunComplete`` above?). For instance, our data collectors do not get notified of ``OnTestSessionEnd`` in order to do session-level cleanup. On one level, this seems like a bug.
Also, is there documentation for all of this behavior? I can't find any.

**Comment by Sanan07** [comment]
@wiweinbe When you call `AbortTestRun` it then calls `HandleTestRunComplete`, so you can collect your metadata as inside `HandleTestRunComplete`, but `CancelTestRun` just cancel active test run, so that why you can collect metrics.

As you can see from this comment [BaseTestsRun.cs ](https://github.com/microsoft/vstest/blob/50b5b33261f7593eb92ae221dae1b9c74234207e/src/Microsoft.TestPlatform.CrossPlatEngine/Execution/BaseRunTests.cs#L266-L267), when you call `CancelTestRun` it does not call `HandleTestRunComple` to cancel quickly.

I was not able to find any related docs either. We are planning to update and extend our documentation, so possibly we will add in future.
