### ISSUE TITLE
How i can specify batch size for vstest task if i run under windows docker ?

### ISSUE THREAD

**Issue by vasokot** [microsoft/vstest#2550]
I use visual studio build tools 2019 at windows docker (image microsoft/dotnet-framework:3.5-runtime-20190312-windowsservercore-ltsc2019)

how can i specify batch size for vstest from comandline to use it at docker ?

**Comment by nohwnd** [comment]
Do you have a repro please, or more information about what exactly you are trying to do? If anything fails, please post the error.

**Comment by nohwnd** [comment]
You can specify the BatchSize in runsettings, or using inline runsettings `dotnet test -- RunConfiguration.BatchSize=100`.
