### ISSUE TITLE
API to run vstest without using vstest.console.exe? 

### ISSUE THREAD

**Issue by lovettchris** [microsoft/vstest#2561]
Is there an API way to run a test?  I want to run a test from an C# Azure Function which means I need to use nuget to install the vstest host, but do you have docs/sample somewhere that shows how to run a test using API's in this nuget package?

**Comment by Sanan07** [comment]
@lovettchris You can use [VsTestConsoleWrapper.cs](https://github.com/microsoft/vstest/blob/master/src/Microsoft.TestPlatform.VsTestConsole.TranslationLayer/VsTestConsoleWrapper.cs#L62) explicitly discover and run your tests. But for this you need to send path to `vstest.console.exe` and then call `DiscoverTests` and `RunTests` methods. 

For this you need to install `Microsoft.TestPlatform.TranslationLayer` nuget package as well.

As and example you can look at this test project, which I created : https://github.com/Sanan07/VsTestConsoleWrapperExample

**Comment by nohwnd** [comment]
https://github.com/microsoft/testfx/issues/733 there was a similar question on testfx few days ago. There are few more links.

**Comment by lovettchris** [comment]
Thanks.
