### ISSUE TITLE
Can't run web integration test in version xunit.runner.visualstudio 2.4.3

### ISSUE THREAD

**Issue by eddynaka** [microsoft/vstest#2564]
## Description
> **IMPORTANT**: if the defect is reproduced only in a workflow from within the Visual Studio IDE then do not report the issue here - instead, please report it using Visual Studio's "Send Feedback" option that can be accessed from the Help menu OR using this link https://developercommunity.visualstudio.com.
>
> For a defect reproducable from the vstest command line, describe the issue you've observed.

I have a web integration test that has reference to the api/mvc. I'm facing an issue when I update the version of `xunit.runner.visualstudio` from `2.4.1` to `2.4.3`.

The motivation to update to `2.4.3` came from this: https://github.com/microsoft/vstest/issues/2384. With net5.0, the version `2.4.1` hangs forever.

## Steps to reproduce
> What steps can reproduce the defect?
> Please share the setup, commandline for vstest.console, sample project, target
> framework etc.

1. Access this: https://github.com/dotnet/AspNetCore.Docs/tree/master/aspnetcore/test/integration-tests/samples
2. Change the version from `2.4.1` to `2.4.3`

## Expected behavior
> Share the expected output

No issues when building/testing

## Actual behavior
> What is the behavior observed?

I'm receiving the following error:
```
CSC : error CS5001: Program does not contain a static 'Main' method suitable for an entry point [C:\samples\3.x\IntegrationTestsSample\tests\RazorPagesProject.Tests\RazorPagesProject.Tests.csproj]
    0 Warning(s)
    1 Error(s)
```

## Diagnostic logs
> Please share test platform diagnostics logs. Instructions to collect logs are [here](https://github.com/Microsoft/vstest-docs/blob/master/docs/diagnose.md#test-platform-diagnostics).  
> The logs may contain test assembly paths, kindly review and mask those before sharing.

## Environment
> Please share additional details about the test environment.
> Operating system, Build version of vstest.console

**Comment by nohwnd** [comment]
FYI you are on the latest net5.0 rc1 the version 2.4.3 of xunit runner is no longer needed, the reverted the change that caused this. https://github.com/dotnet/core/blob/master/release-notes/5.0/5.0-known-issues.md#preview-8-1 see 1. and 2.

The entrypoint should be generated by Microsoft.NET.Test.SDK do you have that installed?

**Comment by nohwnd** [comment]
^^^ checked the projects myslef. You don't have it installed. Add that reference and you should be good to go.

**Comment by eddynaka** [comment]
@nohwnd , thanks for the hint. I'm updating that!

The strange part: locally the tests was working fine (even with the version `2.4.1`), but when I was testing using Azure Devops, the issue occurred!

**Comment by eddynaka** [comment]
Thanks for the hint. It solved my issues!
