### ISSUE TITLE
Notification about tests in progress

### ISSUE THREAD

**Issue by Tasteful** [microsoft/vstest#2565]
## Description
Notification about tests in progress.

## Steps to reproduce
Run the same test for the second time.

## Expected behavior
When starting the test for the second time, mark the test as s `Not run`
![image](https://user-images.githubusercontent.com/357589/92869566-3c2eca00-f403-11ea-9c73-96c3d510ba3e.png)

## Actual behavior
Test is starting but it is hard to read by numbers how many tests that have been executed. If all test have the same status as before (passed/failed) and the only indication is the progress bar that somehow shows how many tests in the new run that have been tested.

## Environment
Microsoft Visual Studio Enterprise 2019
Version 16.7.2

**Comment by nohwnd** [comment]
@Tasteful Thanks for reporting, this is a VS specific issue, we can't do much about it here, but I am tagging John below, maybe he knows about a Feedback ticket that already mentions this.

@jfleisher is there any Feedback ticket for this where it can be redirected please?

**Comment by Evangelink** [comment]
Ping @AbhitejJohn

**Comment by AbhitejJohn** [comment]
This is addressed with the new status bar we've added into Test Explorer in 17.2.
