### ISSUE TITLE
Cannot test a delayed signed assembly

### ISSUE THREAD

**Issue by lovettchris** [microsoft/vstest#2567]
## Description
[UnitTestProject.zip](https://github.com/microsoft/vstest/files/5220225/UnitTestProject.zip)

vstest.console reports "Strong name validation failed. (Exception from HRESULT: 0x8013141A)" on the attached unit test.

## Steps to reproduce
- nuget restore UnitTestProject.sln
- msbuild UnitTestProject.sln
- vstest.console UnitTestProject\bin\Debug\net48\UnitTestProject.dll

## Expected behavior
I need a way to test delay signed assemblies to make sure they work before going through the expense of full signing.

## Actual behavior
Strong name validation failed. (Exception from HRESULT: 0x8013141A)

## Diagnostic logs
[log.txt](https://github.com/microsoft/vstest/files/5220254/log.txt)

## Environment
Windows 10 2004, build 19041.508
Microsoft (R) Test Execution Command Line Tool Version 16.7.0
vstest that comes with Visual Studio 2019 16.7.3, located here:
C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\Common7\IDE\CommonExtensions\Microsoft\TestWindow\vstest.console.exe

**Comment by Evangelink** [comment]
Hi @lovettchris,

I am doing some backlog cleaning and just tested your project with `dotnet test` and it seems to be working fine.

I will move forward by closing this issue but feel free to comment if you are still experiencing any issue.

**Comment by lovettchris** [comment]
cool, thanks for checking.

**Comment by Evangelink** [comment]
@Alex-Sob could you let me know which version of dotnet you are using? Also if you are doing anything specific (extra argument or something)? It's working fine for me:

![image](https://github.com/microsoft/vstest/assets/11340282/ef45800a-7828-4516-a485-538b662bfabb)

**Comment by Alex-Sob** [comment]
I'm doing `dotnet test` without any params as well:

![image](https://github.com/microsoft/vstest/assets/52070444/00b642e5-8002-4986-b845-9dcc6c09d7f9)
