### ISSUE TITLE
Dotnet test fails in docker ENTRYPOINT when using ARG Configuration=Release.

### ISSUE THREAD

**Issue by marcpopMSFT** [microsoft/vstest#2573]
---
**Issue moved from dotnet/sdk#13568**
- Please respond to @VictorioBerra.

---

_From @VictorioBerra on Monday, September 14, 2020 2:49:16 AM_

Hear me out...

`dotnet new xunit`

## Dockerfile:

```dockerfile
FROM mcr.microsoft.com/dotnet/core/sdk:3.1-alpine AS sdk
ARG Configuration=Release
WORKDIR /tests
COPY . .
RUN dotnet restore
RUN dotnet build --no-restore
ENTRYPOINT ["dotnet", "test", "--no-build"]
```

- `docker build --tag docker-dotnet-test-arg .`
- `docker run -it --rm docker-dotnet-test-arg`

## ERROR:

```
❯ docker run -it --rm docker-dotnet-test-arg:latest
Test run for /tests/bin/Debug/netcoreapp3.1/DockerDotnetTest2.dll(.NETCoreApp,Version=v3.1)
Microsoft (R) Test Execution Command Line Tool Version 16.7.0
Copyright (c) Microsoft Corporation.  All rights reserved.

The argument /tests/bin/Debug/netcoreapp3.1/DockerDotnetTest2.dll is invalid. Please use the /help option to check the list of valid arguments.
/usr/share/dotnet/sdk/3.1.402/Microsoft.TestPlatform.targets(32,5): error MSB4181: The "Microsoft.TestPlatform.Build.Tasks.VSTestTask" task returned false but did not log an error. [/tests/DockerDotnetTest2.csproj]
```

Now comment out `ARG Configuration=Release`, build and run the container again. I spent all day doing guess, test and retry to figure this out. I would love some help as to why this happens and how I can fix it.

Note: You can see in the above Dockerfile snippet I am not using the ARG just to simplify the example, but you would commonly use it like so: `RUN dotnet build --configuration $Configuration --no-restore`

**Comment by marcpopMSFT** [comment]
---
**Issue moved from dotnet/sdk#13568**
- Please respond to @marcpopMSFT.

---

_From @marcpopMSFT on Tuesday, September 15, 2020 11:30:39 PM_

@dotnet/dotnet-test-templates-admin for triage

**Comment by farhad-taran** [comment]
I am having the same issue

**Comment by VictorioBerra** [comment]
@farhad-taran 

> I am having the same issue

I am still waiting on an official reply, but the main issue is that its trying to test the default .dll in /Debug, not the one that was built in /Release. If you hardcode the Configuration option in your test command it will work.

When arg is commented out, it builds and tests both in Debug.

**Comment by VictorioBerra** [comment]
I should reply with my usecase for anyone else (and my future self) since I cant edit the orig post now:

Running the tests AFTER the container is built would be really important if you wanted to connect to a SQL container to run the tests against using docker-compose. But if you run the tests after like in `ENTRYPOINT` you can no longer get access to the orig Configuration that was used to build the container.

**Comment by dpomBF** [comment]
Has this issue been resolved?

**Comment by nohwnd** [comment]
The msbuild instance running under dotnet test won't pick up the configuration from environment, but you can redefine it as `ENV` and then it will work: 

Add `ENV Configuration=$Configuration`

```dockerfile

**Comment by nohwnd** [comment]
That said, this is probably better done as multi stage build, and then pointing dotnet test on the dll artifact directly.
