### ISSUE TITLE
Blame adapter too verbose and throws exception if no dump was generated

### ISSUE THREAD

**Issue by ViktorHofer** [microsoft/vstest#2582]
```
Test run for C:\git\runtime3\artifacts\bin\System.Console.Tests\net5.0-Windows_NT-Debug\System.Console.Tests.dll (.NETCoreApp,Version=v5.0)
Starting test execution, please wait...
A total of 1 test files matched the specified pattern.
Data collector 'Blame' message: All tests finished running, Sequence file will not be generated.
Data collector 'Blame' message: System.IO.FileNotFoundException: Collect dump was enabled but no dump file was generated.
   at Microsoft.TestPlatform.Extensions.BlameDataCollector.ProcessDumpUtility.GetDumpFiles()
   at Microsoft.TestPlatform.Extensions.BlameDataCollector.BlameCollector.SessionEndedHandler(Object sender, SessionEndEventArgs args).
Results File: C:\git\runtime3\artifacts\bin\System.Console.Tests\net5.0-Windows_NT-Debug\TestResults\vihofer_DESKTOP-803H9R0_2020-09-27_15_26_21.trx
Html test results file : C:\git\runtime3\artifacts\bin\System.Console.Tests\net5.0-Windows_NT-Debug\TestResults\TestResult_vihofer_DESKTOP-803H9R0_20200927_152626.html

Passed!  - Failed:     0, Passed:   128, Skipped:     0, Total:   128, Duration: 5 s - System.Console.Tests.dll (net5.0)
```

@nohwnd can we make the success path less verbose by not logging the "Sequence file will not be generated" message? This is always logged and doesn't provide much value. I would instead document when a Sequence gets generated with the blame logger.

Also it seems that the FileNotFoundException shouldn't occur in the "blessed" path when no dump is generated?

**Comment by nohwnd** [comment]
Which version of dotnet-sdk (otr tesplatform is this?) I fixed the file not found exception in rc2 I think.

As for the sequence file, people who are aware of it always asked why it was not generated in some cases, that is why the warning was added.  Without it it is hard to distinguish when it just did not work at all, and when it did not upload the sequence file for a reason.

**Comment by ViktorHofer** [comment]
> Which version of dotnet-sdk (otr tesplatform is this?) I fixed the file not found exception in rc2 I think.

Cool, I'm testing with an RC1 build.

> As for the sequence file, people who are aware of it always asked why it was not generated in some cases, that is why the warning was added. Without it it is hard to distinguish when it just did not work at all, and when it did not upload the sequence file for a reason.

Can we downgrade the warning to an information message only? We usually turn on TreatWarningsAsErrors and even though this code might not be affected as it comes from VSTest, IMO a warning is still an overkill.

**Comment by nohwnd** [comment]
Can we still make changes after rc2? Otherwise we would have to do it in net6.0 only

**Comment by ViktorHofer** [comment]
Not really as the SDK is now in ask-mode afaik. I think it's fine if we do this for 6.0, we might need a 6.0 SDK anyway if we depend on a working inisolation mode in dotnet/runtime.

**Comment by juwens** [comment]
> I also get this message if using "-blame-crash-collect-always". Its frustrating, because I try why the dump is not working on the server and I can't get it working locally and dotnet is just telling me "I have not created a dump and don't know why I haven't done it" with this Exception.

i have the same problem  
a crash i cannot diagnose, because not dump is created, not even with "--blame-crash-collect-always mini"

**Comment by nohwnd** [comment]
This is a new feature and won't be implemented, we are focusing on adding new features to Testing.Platform instead. https://aka.ms/testingplatform
