### ISSUE TITLE
Test duration numbers are wrong

### ISSUE THREAD

**Issue by ViktorHofer** [microsoft/vstest#2594]
```
Passed!  - Failed:     0, Passed:  4542, Skipped:    20, Total:  4562, Duration: 9 m 33 s - System.Net.Security.Tests.dll (netcoreapp6.0)
```

This shows that the test assembly executed for more than 9 minutes even though it only took ~1 minute. @stephentoub just noticed the same issue on his machine locally as well.

Using the latest runner: 16.8.0-release-20201009-01

**Comment by Sanan07** [comment]
@ViktorHofer  which test adapter do you use? Is it XUnit? As I can see from code we use duration which is sent from adapter, so we convert it and output in console

**Comment by ViktorHofer** [comment]
> @ViktorHofer which test adapter do you use? Is it XUnit?

xunit.runner.visualstudio.

> As I can see from code we use duration which is sent from adapter, so we convert it and output in console

Some offline conversations with @ericstj:

>
[Yesterday 11:39 PM] Eric St. John
    I noticed something funny when playing with VStest
​[Yesterday 11:39 PM] Eric St. John
    If I run it on System.Text.Json.Tests it says the tests take 3minutes, however the process is exiting in under a minute
​[Yesterday 11:40 PM] Eric St. John
    (~53s)
​[Yesterday 11:40 PM] Eric St. John
    I think it's counting per-cpu-time

Does that make sense @Sanan07?

**Comment by ViktorHofer** [comment]
cc @clairernovotny

**Comment by ViktorHofer** [comment]
Closing as dup of https://github.com/microsoft/vstest/issues/2585
