### ISSUE TITLE
Test timeout kills the process while the debugger is attached

### ISSUE THREAD

**Issue by ViktorHofer** [microsoft/vstest#2595]
The test timeout should likely not be respected when a debugger is attached. Conditioning on the DEBUG switch wouldn't work as the SDK contains the Release configuration of VSTest.

**Comment by nohwnd** [comment]
Which timeout is this about? We multiply connection timeout by 5 when debugging and I rarely run into that, as it is considered only in few places where we actually connect. Or is this about the Timeout attribute on some testing framework?

**Comment by ViktorHofer** [comment]
IIRC this was about the `--blame-hang-timeout`.

**Comment by nohwnd** [comment]
I don't think this should be implemented. No-one else upvoted this and the hang timeout is easy to disable or make the interval longer. I also often debug it, and after experience with Assert.Debug which behaves differently under debugger and without debugger, this behavior is just confusing (to me at least).
