### ISSUE TITLE
DataCollector in ".runsettings" file does not get injected into the test host process

### ISSUE THREAD

**Issue by caghand** [microsoft/vstest#2599]
## Description
When running `dotnet test`, if I specify a DataCollector using the command line, the in-process collector *will* be injected.  But if I specify a DataCollector using a ".runsettings" file, the in-process collector *won't* be injected.

## Steps to reproduce
**Good case:**
`dotnet test <path_to_csproj_file> --collect "XPlat Code Coverage"`
- coverlet.collector gets injected into the test host process, and there are no problems.

**Bad case:**
`dotnet test <path_to_csproj_file> --settings test.runsettings`
(test.runsettings contains a DataCollector element with friendlyName="XPlat Code Coverage".)
- coverlet.collector still works, but because it doesn't get injected into the test host process, the following issue is encountered: https://github.com/coverlet-coverage/coverlet/blob/master/Documentation/KnownIssues.md#1-vstest-stops-process-execution-earlydotnet-test

## Environment
.NET Core 3.1

**Comment by jakubch1** [comment]
Coverlet is not standard data collector. It is InProcess data collector which requires additional `InProcDataCollector ` tag. I was able to run it correctly with below run settings.

```
  <DataCollectionRunSettings>
    <DataCollectors>
      <DataCollector friendlyName="XPlat Code Coverage" enabled="True" />
    </DataCollectors>
  </DataCollectionRunSettings>
  <InProcDataCollectionRunSettings>
    <InProcDataCollectors>
      <InProcDataCollector assemblyQualifiedName="Coverlet.Collector.DataCollection.CoverletInProcDataCollector, coverlet.collector, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null" friendlyName="XPlat Code Coverage" enabled="True" codebase="C:\Users\UseThisAccount\.nuget\packages\coverlet.collector\3.0.3\build\netstandard1.0\coverlet.collector.dll" />
    </InProcDataCollectors>
  </InProcDataCollectionRunSettings>
```

The issue will be gone when coverlet will keep results in shared memory. In such case in process data collector is not needed.
I hope it will be resolved by: https://github.com/coverlet-coverage/coverlet/issues/808.
