### ISSUE TITLE
Aborting test discovery prints a message indicating that the test host crashed

### ISSUE THREAD

**Issue by AbhitejJohn** [microsoft/vstest#2607]
## Description
When a discovery operation is aborted from VS Test Explorer, the test platform ends up sending the following message to the Test Explorer which is printed to the Output->Tests pane.
"The active test discovery was aborted. Reason: Test host process crashed"

This does not happen when a test run is aborted though. This message is confusing and would be great to get rid off in this specific scenario.

## Steps to reproduce
1. Open a solution with large number of test projects.
2. Before the discovery operation is complete (you'd see progress in the output->tests pane), trigger a "Run All" operation

## Expected behavior
Just the following messages from Test Explorer in the Tests pane:

---------- Starting test discovery ----------
Aborting test discovery because a test run was requested.
========== Test discovery aborted: 1 Tests found in 1.2 sec ==========

## Actual behavior
---------- Starting test discovery ----------
Aborting test discovery because a test run was requested.
**The active test discovery was aborted. Reason: Test host process crashed**
========== Test discovery aborted: 1 Tests found in 1.2 sec ==========

## Environment
16.9 intpreview builds. It does repro on 16.8 as well.

**Comment by AbhitejJohn** [comment]
/cc: @shyamnamboodiripad.
Also tagging @cvpoienaru as well since this would fall in the same workflow as the other performance updates you were thinking about.

**Comment by nohwnd** [comment]
https://github.com/microsoft/vstest/issues/2270 is it related to this? Which version do you see that on? I remember not being able to get stable repro, but after the fix it was way less common.

**Comment by nohwnd** [comment]
https://devdiv.visualstudio.com/DevDiv/_git/VSUnitTesting/pullrequest/223694 this is the fix I am referring to.

**Comment by wyoming98-hub** [comment]
Any updates on this topic? We are experiencing the same issue from test.sdk version 16.7. on. 16.6. is running fine on our build pipline


```

Test run for D:\a\1\s\xxx.Api.Integration.Tests.dll (.NETCoreApp,Version=v3.1)
Microsoft (R) Test Execution Command Line Tool Version 16.8.3
Copyright (c) Microsoft Corporation.  All rights reserved.

Starting test execution, please wait...
A total of 1 test files matched the specified pattern.
The active test run was aborted. Reason: Test host process crashed : Fatal error. Internal CLR error. (0x80131506)
```

**Comment by Stamo-Gochev** [comment]
I am experiencing the same problem, can you provide a workaround?

**Comment by stevomccormack** [comment]
========== Starting test run ==========
The active Tests Run was aborted.
========== Test run aborted: 0 Tests (0 Passed, 0 Failed, 0 Skipped) run in < 1 ms ==========
========== Starting test discovery ==========
The active Tests Discovery was aborted.
========== Test discovery aborted: 0 Tests found in 2.2 ms ==========




Microsoft Visual Studio Professional 2022 Preview
Version 17.0.0 Preview 7.0
VisualStudio.17.Preview/17.0.0-pre.7.0+31825.309
Microsoft .NET Framework
Version 4.8.04084

Installed Version: Professional

Visual C++ 2022   00476-80000-00000-AA403
Microsoft Visual C++ 2022

.NET Core Debugging with WSL   1.0
.NET Core Debugging with WSL

ASP.NET and Web Tools 2019   17.0.786.62401
ASP.NET and Web Tools 2019

ASP.NET Web Frameworks and Tools 2019   17.0.786.62401
For additional information, visit https://www.asp.net/

Azure App Service Tools v3.0.0   17.0.786.62401
Azure App Service Tools v3.0.0

Azure Functions and Web Jobs Tools   17.0.786.62401
Azure Functions and Web Jobs Tools

C# Tools   4.0.0-6.21521.2+68d3c0e77ff8607adca62a883197a5637a596438
C# components used in the IDE. Depending on your project type and settings, a different version of the compiler may be used.

Common Azure Tools   1.10
Provides common services for use by Azure Mobile Services and Microsoft Azure Tools.

Fabric.DiagnosticEvents   1.0
Fabric Diagnostic Events

Linux Core Dump Debugging   1.0.9.31808
Enables debugging of Linux core dumps.

Microsoft Azure Service Fabric Tools for Visual Studio   17.0
Microsoft Azure Service Fabric Tools for Visual Studio

Microsoft Azure Tools for Visual Studio   2.9
Support for Azure Cloud Services projects

Microsoft JVM Debugger   1.0
Provides support for connecting the Visual Studio debugger to JDWP compatible Java Virtual Machines

Microsoft Library Manager   2.1.134+45632ee938.RR
Install client-side libraries easily to any web project

Microsoft MI-Based Debugger   1.0
Provides support for connecting Visual Studio to MI compatible debuggers

Microsoft Visual C++ Wizards   1.0
Microsoft Visual C++ Wizards

Microsoft Visual Studio Tools for Containers   1.2
Develop, run, validate your ASP.NET Core applications in the target environment. F5 your application directly into a container with debugging, or CTRL + F5 to edit & refresh your app without having to rebuild the container.

Microsoft Visual Studio VC Package   1.0
Microsoft Visual Studio VC Package

Node.js Tools   1.5.30901.1 Commit Hash:2ce65f585c66dbd15240cf57f8e995513c270b0b
Adds support for developing and debugging Node.js apps in Visual Studio

NuGet Package Manager   6.0.0
NuGet Package Manager in Visual Studio. For more information about NuGet, visit https://docs.nuget.org/

ProjectServicesPackage Extension   1.0
ProjectServicesPackage Visual Studio Extension Detailed Info

Razor (ASP.NET Core)   17.0.0.2150514+d9e17e7b7f06829e976f616716a987599c5c66e9
Provides languages services for ASP.NET Core Razor.

SQL Server Data Tools   17.0.62110.20190
Microsoft SQL Server Data Tools

TypeScript Tools   17.0.1001.2002
TypeScript Tools for Microsoft Visual Studio

Visual Basic Tools   4.0.0-6.21521.2+68d3c0e77ff8607adca62a883197a5637a596438
Visual Basic components used in the IDE. Depending on your project type and settings, a different version of the compiler may be used.

Visual C++ for Linux Development   1.0.9.31808
Visual C++ for Linux Development

Visual F# Tools   17.0.0-beta.21519.2+727a6abda5bb3276f3e8dd918b721c5d21464aac
Microsoft Visual F# Tools

Visual Studio Code Debug Adapter Host Package   1.0
Interop layer for hosting Visual Studio Code debug adapters in Visual Studio

Visual Studio Container Tools Extensions   1.0
View, manage, and diagnose containers within Visual Studio.

Visual Studio IntelliCode   2.2
AI-assisted development for Visual Studio.

Visual Studio Tools for CMake   1.0
Visual Studio Tools for CMake

Visual Studio Tools for Containers   1.0
Visual Studio Tools for Containers
