### ISSUE TITLE
HttpContext.GetAsync fails when using RunImpersonated, but ONLY when in a Test

### ISSUE THREAD

**Issue by Vaccano** [microsoft/vstest#2651]
## Description
When run in a unit test (and ONLY in a unit test) an impersonated call to any URL will fail.  (Impersonated calls made outside a unit test work just fine.)

This happens in NUnit and XUnit, which leads me to believe that it is an underlying issue with the `Microsoft.NET.Test.Sdk` NuGet Package.

The fact that it works without errors outside a unit test, and fails in both NUnit and XUnit is the reason I am reporting this here (because they both use `Microsoft.NET.Test.Sdk` to run the unit tests.)

## Steps to reproduce
1. Create a project using the code listed in the Sample Code section below
2. Save and build
3. Open a command line tool and change directory to the dll of the built unit tests
3. Run `vstest.console YourDllNameHere.dll`
4. The test  `Should_CallUrl_When_Impersonated` will fail.

## Expected behavior
The call to the URL will succeed instead of fail.

## Actual behavior
The call has a DNS error:
> System.Net.Sockets.SocketException : This is usually a temporary error during hostname resolution and means that the local server did not receive a response from an authoritative server.

## Diagnostic logs
[log.txt](https://github.com/microsoft/vstest/files/5586734/log.txt)

## Environment
* Windows 10 1903 - Build 18362.1139
* Visual Studio 2019 - 16.7.7
* `dotnet --version`: 3.1.403

## Sample Code

The test `Should_CallUrl_When_Impersonated` fails with the exception indicated above.  However, to run it, the `LogonUser` method call needs to updated to a valid windows user for your domain.  (Replacing `"user", "myDomain.net", "password"` with the user, domain and password.)

As a comparison, the test ` Should_CallUrl_When_NotImpersonated` just loads the url without actually doing an impersonation (the `SafeAccessTokenHandle.InvalidHandle` makes the `RunImpersonated` not actually swap users).  It will always succeed (assuming a valid internet connection).

Note that this impersonation code was drawn from [.Net Core 3.1 documentation.](https://docs.microsoft.com/en-us/dotnet/api/system.security.principal.windowsidentity.runimpersonated?view=netcore-3.1)

    using System;
    using System.Net.Http;
    using System.Runtime.InteropServices;
    using System.Security.Principal;
    using System.Threading.Tasks;
    using FluentAssertions;
    using Microsoft.Win32.SafeHandles;
    using NUnit.Framework;

    namespace ImpersonationUnitTests
    {
        public class ImpersonationTest
        {
            [DllImport("advapi32.dll", SetLastError = true, CharSet = CharSet.Unicode)]
            public static extern bool LogonUser(String lpszUsername, String lpszDomain, String lpszPassword,
                int dwLogonType, int dwLogonProvider, out SafeAccessTokenHandle phToken);
            
            private static readonly HttpClient httpClient = new HttpClient();

            [Test]
            public async Task Should_CallUrl_When_Impersonated()
            {
                //+ Arrange
                SafeAccessTokenHandle testAccountHandle;
                bool returnValue = LogonUser("user", "myDomain.net", "password", 2, 0, out testAccountHandle);
                HttpResponseMessage response = null;

                //+ Act
                await WindowsIdentity.RunImpersonated<Task>(testAccountHandle, async () =>
                {
                    var url = "https://accounts.google.com/.well-known/openid-configuration";
                    response = await httpClient.GetAsync(url);
                });

                //+ Assert
                returnValue.Should().BeTrue("login has to succeed");
                response.Should().NotBeNull("we need a valid response");
            }

            [Test]
            public async Task Should_CallUrl_When_NotImpersonated()
            {
                //+ Arrange
                HttpResponseMessage response = null;

                //+ Act
                WindowsIdentity.RunImpersonated(SafeAccessTokenHandle.InvalidHandle, () =>
                {
                    var url = "https://accounts.google.com/.well-known/openid-configuration";
                    response = httpClient.GetAsync(url).Result;
                });

                //+ Assert
                response.Should().NotBeNull("we need a valid response");
            }
        }
    }

This is the project file that holds the above file (provided so that installing NuGet references is easy).

  <Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
      <TargetFramework>netcoreapp3.1</TargetFramework>
    </PropertyGroup>

    <ItemGroup>
      <PackageReference Include="FluentAssertions" Version="5.10.3" />
      <PackageReference Include="System.Security.Principal.Windows" Version="4.3.0" />
      <PackageReference Include="nunit" Version="3.12.0" />
      <PackageReference Include="NUnit3TestAdapter" Version="3.17.0">
        <PrivateAssets>all</PrivateAssets>
        <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
      </PackageReference>
      <PackageReference Include="Microsoft.NET.Test.Sdk" Version="16.6.1" />
    </ItemGroup>

  </Project>

**Comment by Vaccano** [comment]
I can't be sure, but this may be related to this issue:

https://github.com/dotnet/runtime/issues/29935

**Comment by Vaccano** [comment]
This seems to be a workaround to this issue:

    Environment.SetEnvironmentVariable("DOTNET_SYSTEM_NET_HTTP_USESOCKETSHTTPHANDLER", "0");

I have no idea what this does or why it fixes it.

**Comment by nohwnd** [comment]
Thanks for the workaround, and sorry about the silence.
