### ISSUE TITLE
Run tests in a specific order

### ISSUE THREAD

**Issue by ffMathy** [microsoft/vstest#2654]
It would be great if `dotnet test` could allow running tests in a specific order, perhaps via a runsettings file - similar to the old Playlist feature that used to exist.

The reason I want to do this is that I would like to (for instance) run failed tests first on the build server.

**Comment by Sanan07** [comment]
We have this [Rerun failed tests](https://github.com/microsoft/vstest/issues/1776) feature request and potentially can implement it.

**Comment by Evangelink** [comment]
This is more of a test framework (xUnit, MSTest...) matter than on vstest so we will close this issue.
