### ISSUE TITLE
VSTest hangs for over 45 minutes before running a few unit tests.

### ISSUE THREAD

**Issue by MarkKharitonov** [microsoft/vstest#2655]
## Description
> **IMPORTANT**: if the defect is reproduced only in a workflow from within the Visual Studio IDE then do not report the issue here - instead, please report it using Visual Studio's "Send Feedback" option that can be accessed from the Help menu OR using this link https://developercommunity.visualstudio.com.
>
> For a defect reproducable from the vstest command line, describe the issue you've observed.

I have a .Net Core 3.1 code which has a few unit tests using NUnit. The tests have a global OneTimeSetUp phase and then there are about 2 dozens unit tests.
**dotnet test --no-build** runs for 45 minutes on average. The setup phase takes about 30 seconds. The tests in total take about the same. 

I ran `dotnet test --no-build -p:VSTestVerbosity=diag -p:VSTestDiag=c:\temp\test.log`. I got two files:

 - test.log
 - test.host.20-11-24_21-25-00_45838_6.log

The logs show the same pattern. One second later, the first log starts showing
```
TpTrace Verbose: 0 : 66568, 10, 2020/11/24, 21:25:01.363, 63471109902700, vstest.console.dll, TcpClientExtensions.MessageLoopAsync: Polling on remoteEndPoint: 127.0.0.1:20496 localEndPoint: 127.0.0.1:20495
```
And will show these messages for the next 44 minutes before successfully completing.

Around the same time the second log starts showing
```
TpTrace Verbose: 0 : 59460, 10, 2020/11/24, 21:25:02.029, 63471116570605, testhost.dll, TcpClientExtensions.MessageLoopAsync: Polling on remoteEndPoint: [::ffff:127.0.0.1]:20495 localEndPoint: [::ffff:127.0.0.1]:20496
```
And will be showing such messages for the next 45 minutes as well. After that something clicks and the test completes.

All the tests have `SingleThreaded` attribute on their fixture.

## Steps to reproduce
Unfortunately I cannot share the project. I will have to come up with a minimal reproduction.
I can reproduce it easily - **dotnet test --no-build** does it every time.

OS: Windows 10
.Net: .Net Core 3.1

## Expected behavior
Tests complete in less than 2 minutes.

## Actual behavior
Takes about 45 mins to complete. Successfully.

## Diagnostic logs
[test.log](https://github.com/microsoft/vstest/files/5596816/test.log)
[test.host.20-11-24_21-25-00_45838_6.log](https://github.com/microsoft/vstest/files/5596817/test.host.20-11-24_21-25-00_45838_6.log)

**Comment by Sanan07** [comment]
@MarkKharitonov Which version of vstest.console do you use? Is it 16.5.0? You can see it console output.
Do you face this issue only with this test project or some others too?

**Comment by MarkKharitonov** [comment]
Here is the output of the command:
```
Test run for C:\Dayforce\DevOps\GenerateBindingRedirects\src\GenerateBindingRedirectsTests\bin\Debug\netcoreapp3.1\GenerateBindingRedirectsTests.dll(.NETCoreApp,Version=v3.1)
Microsoft (R) Test Execution Command Line Tool Version 16.7.0-release-20200703-01
Copyright (c) Microsoft Corporation.  All rights reserved.

Starting test execution, please wait...
Logging Vstest Diagnostics in file: c:\temp\test2.log

A total of 1 test files matched the specified pattern.
Logging TestHost Diagnostics in file: c:\temp\test2.host.20-11-25_01-03-47_22267_6.log
NUnit Adapter 3.16.1.0: Test execution started
Running all tests in C:\Dayforce\DevOps\GenerateBindingRedirects\src\GenerateBindingRedirectsTests\bin\Debug\netcoreapp3.1\GenerateBindingRedirectsTests.dll
   NUnit3TestExecutor converted 22 of 22 NUnit test cases
  √ AssertFailMismatchingBindingRedirects(1\DataSvc) [753ms]
  √ AssertFailNoBindingRedirects(1\DataSvc) [496ms]
  √ AssertPass(1\DataSvc) [508ms]
  √ AssertPass(1\CommonTests) [265ms]
  √ Generate(1\DataSvc) [626ms]
  √ Generate(1\BJE) [854ms]
  √ Generate(1\ReportingSvc) [578ms]
  √ Generate(1\CommonTests) [300ms]
  √ Generate(1\RuleEngineTests) [593ms]
  √ Generate(2\CandidatePortal) [1s 36ms]
  √ Generate(2\MyDayforce) [1s 597ms]
  √ Generate(3\Api) [1s 906ms]
  √ Generate(3\OData) [1s 104ms]
  √ Generate(4\Clock) [123ms]
  √ GenerateCreateNewConfigFile(1\DataSvc) [519ms]
  √ GenerateCreateNewConfigFile(1\CommonTests) [258ms]
  √ GenerateOverwriteMismatchingConfigFileNoAssemblyBindingElement(1\DataSvc) [493ms]
  √ GenerateOverwriteMismatchingConfigFileNoAssemblyBindingElement(1\CommonTests) [284ms]
NUnit Adapter 3.16.1.0: Test execution complete
  √ GenerateOverwriteMismatchingConfigFileNoDependentAssemblyElement(1\DataSvc) [490ms]
  √ GenerateOverwriteMismatchingConfigFileNoDependentAssemblyElement(1\CommonTests) [262ms]
  √ GenerateOverwriteMismatchingConfigFileNoRuntimeElement(1\DataSvc) [523ms]
  √ GenerateOverwriteMismatchingConfigFileNoRuntimeElement(1\CommonTests) [261ms]

Test Run Successful.
Total tests: 22
     Passed: 22
 Total time: 45.4361 Minutes
```
So, it is `16.7.0-release-20200703-01`

I face it with this particular solution only. No other solution exhibits this behaviour.

**Comment by nohwnd** [comment]
That seems like there is some long setup somewhere. I would dump the testhost process while it is waiting (e.g. open Task Manager, find the testhost process, right click and select Create Dump File). Then you can open it in Visual Studio, and look at the different call stacks to see where it is hanging. Or share it with us.

**Comment by MarkKharitonov** [comment]
I can do that. To make sure I am doing the right thing, could you give me procdump.exe command line? This way I will capture it exactly the way you wish.

**Comment by nohwnd** [comment]
IDK I just do it via the right click in Task Manager. 😁 It's actually better if you inspect it in your VS because you have all the symbols for your project, it will ask you to navigate to them imho. So you will see more info than me. I usually do Debug > Windows > Parallel callstacks, and look at all the call stacks to see if it's waiting in some user code. The one running user code is usually the tallest one. But in this case I am not sure how it will look like *if* it is stuck in Setup.

**Comment by MarkKharitonov** [comment]
I found the root cause. Your advice to attach the debugger to testhost.exe was the most fruitful. I have a global setup that runs a process using the following code:
```
            var p = new Process
            {
                StartInfo = new ProcessStartInfo
                {
                    Arguments = arguments,
                    FileName = exe,
                    CreateNoWindow = true,
                    LoadUserProfile = false,
                    UseShellExecute = false,
                    WindowStyle = ProcessWindowStyle.Hidden,
                    RedirectStandardError = true,
                    RedirectStandardOutput = true
                },
            };
            var sbStdErr = new StringBuilder();
            p.ErrorDataReceived += (sender, e) =>
            {
                sbStdErr.Append(e.Data);
            };
            p.Start();
            p.BeginErrorReadLine();
            string output = p.StandardOutput.ReadToEnd();
            p.WaitForExit();

            TestContext.WriteLine(output);
            Trace.WriteLine(output);

            if (sbStdErr.Length > 0)
            {
                output += "\r\n" + sbStdErr.ToString();
            }
            Assert.AreEqual(0, p.ExitCode, output);
            return output;
```
I copied this pattern from https://docs.microsoft.com/en-us/dotnet/api/system.diagnostics.processstartinfo.redirectstandardoutput?view=netframework-4.7.2 

As it turns out, the test apparently deadlocks on `p.StandardOutput.ReadToEnd();`, but only for about 45 minutes and only when running on the console. Now I need to figure out how to code it correctly.

**Comment by MarkKharitonov** [comment]
Posted here - https://stackoverflow.com/questions/65044945/how-to-collect-redirected-standard-output-and-error-in-net-core-correctly

**Comment by nohwnd** [comment]
Thanks for the follow up.
