### ISSUE TITLE
Adding Microsoft.NET.Test.Sdk to a .NET Core prevents it to be packed as a NuGet-Package

### ISSUE THREAD

**Issue by broetchenrackete36** [microsoft/vstest#2656]
Not sure if this belongs here or to dotnet/core...

## Description
Adding Microsoft.NET.Test.Sdk to a .NET Core or .NET5 project prevents it to be packed as a NuGet-Package.

## Steps to reproduce
```
dotnet new console
dotnet pack
dotnet add bugreport.csproj package Microsoft.NET.Test.Sdk
dotnet pack
```
The first `dotnet pack` works as expected, the second one `dotnet pack` doesn't do anything, it doesn't fail but it doesn't produce a NuGet-Package either.
Same behavior with Visual Studio and msbuild.

## Expected behavior
`dotnet pack` produces a package even when Microsoft.NET.Test.Sdk is referenced

## Environment
```
Runtime:
 OS Name:     Windows
 OS Version:  10.0.18363
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\5.0.100\

Host (useful for support):
  Version: 5.0.0
  Commit:  cf258a14b7
```

**Comment by Haplois** [comment]
Projects referencing `Microsoft.NET.Test.Sdk` are not packageable by-design. If you would like to override this behavior, please set the `IsPackable` property to true in your `.csproj` file. An example is below:

```
<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net5.0</TargetFramework>
    <RootNamespace>_2656</RootNamespace>
    <IsPackable>true</IsPackable>
    <GenerateProgramFile>false</GenerateProgramFile>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.NET.Test.Sdk" Version="16.8.0" />
  </ItemGroup>

</Project>
```

_Note: You might get a warning about multiple entry-points. To fix this, please add another property named `GenerateProgramFile` and set it to `false` as shown above._

**Comment by broetchenrackete36** [comment]
Thank you for the quick response, setting the property fixed my problem.
