### ISSUE TITLE
Dotnet vstest producing console logging output out of sync

### ISSUE THREAD

**Issue by ashewani** [microsoft/vstest#2657]
## Description

Dotnet vstest is printing detailed test cases output out of sync on the console.

This issue is similar to [issue #612 ](https://github.com/microsoft/vstest/issues/612).

## Steps to reproduce

Create a new XUnit Test project with a couple of test cases, some of them being failed and running the test command through the CLI.

dotnet vstest XUnitTestProject1.dll --logger:"console;verbosity=Normal"

## Expected behavior

Basically, when the tests are run. ideally the vstest should print the output in a sync manner. 
i.e. Show the test case result, along with the test case name and if it fails it should show the stacktrace, etc.

For eg:

[Passed] TestCase 1
[Failed] TestCase 2
Stacktrace......
[Passed] TestCase 3

[xUnit.net] Finished: TestProject

## Actual behavior

It prints out of sync.

1. In between, it prints the error stack trace of a particular test case and again it prints the same stacktrace of the same test case.

![image](https://user-images.githubusercontent.com/37093828/100422583-af7cd980-30de-11eb-8f54-7cc2324bed30.png)

2. Prints finished before showing the passed/failed test case names.

![image](https://user-images.githubusercontent.com/37093828/100422691-e18e3b80-30de-11eb-8b32-79607fba961b.png)

## Environment

The original issue was observed on the project built using .NetCoreApp 2.0.
SDK: 2.1.201

NuGet packages:

1. Microsoft.NET.Test.Sdk 15.5.0
2. xunit 2.3.1
3. xunit.runner.visualstudio 2.3.1

.NET Command Line Tools (2.1.201)

Product Information:
 Version:            2.1.201
 Commit SHA-1 hash:  7932dc6179

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.18363
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\2.1.201\

**Note**: The same can be reproduced using 5.0.100 SDK with Microsoft Test Execution Command Line Tool Version 16.8.0 with the latest NuGet Packages.

Attached is the sample console output of the failed test cases.
[Sample output.txt](https://github.com/microsoft/vstest/files/5606562/Sample.output.txt)

**Comment by AndiRudi** [comment]
Yep, pretty annoying. I am forwarding all logs into the test window, and you really can't say which log is related to which test. I feel there should be something like this 

```
Starting Test XX.XX.XX
- log message
- log message
- console output
- etc.
Passed Test XX.XX.XX
```

**Comment by Evangelink** [comment]
@AndiRudi @ashewani I have run some tests locally using latest versions of xunit and test platform and it seems that the issue was fixed. I will proceed with closing this ticket but if you are still having some problems, please let me know.
