### ISSUE TITLE
[Code Coverage] Support attribute exclusions for lambdas, yield, local and async functions AB#1265121

### ISSUE THREAD

**Issue by jakubch1** [microsoft/vstest#2658]
## Description
Dynamic code coverage can show coverage info inside excluded methods that contain lambda, yield or local functions. Same can happen if method is async.  The issue is that compiler is not preserving attributes when generating nested classes or methods. This can be fixed in similar way as coverlet did it:
https://github.com/coverlet-coverage/coverlet/pull/671

Related issues:
https://github.com/dotnet/core/issues/4361
https://github.com/dotnet/diagnostics/issues/1771
https://github.com/dotnet/core/issues/5664

AB#1265121

**Comment by pavelhorak** [comment]
AB#1265121

**Comment by jakubch1** [comment]
We added support for all cases we could. Especially async methods are now correctly supported. Changes will be available in latest dev 17 test platform packages and in VS 2022.
To support fully exclusions we need support from roslyn (dotnet/csharplang#4826). 
Closing this issue on our side.
