### ISSUE TITLE
dotnet test vs dotnet vstest

### ISSUE THREAD

**Issue by JDCain** [microsoft/vstest#2664]
The documentation located https://docs.microsoft.com/en-us/dotnet/core/tools/dotnet-vstest says:

> The dotnet vstest command is superseded by dotnet test, which can now be used to run assemblies. See dotnet test.

Is the ability to run assemblies with dotnet test using this project still under the hood but with different command line syntax? Running dotnet vstest vs dotnet test with a specified assembly seem to produce the same output and version numbers as far as I can tell.

**Comment by Haplois** [comment]
`dotnet test` and `dotnet vstest` are basically identical if you call it on an assembly; both execute the test via `vstest.console`. There is a difference in command-line arguments, though.
