### ISSUE TITLE
Vstest.console.exe exited with code -1073741819.

### ISSUE THREAD

**Issue by tomaustin700** [microsoft/vstest#2667]
## Required Information

Entering this information will route you directly to the right team and expedite traction.

**Question, Bug, or Feature?**  
*Type*: Bug

**Enter Task Name**: VsTestV2

## Environment
- Server - Azure Pipelines

- Agent - Private
    
OS is Windows 10 2004, Agent version is 2.175.2

## Issue Description

One of our pipelines is throwing the following exception or completely locking up when running tests. The exception/lockup always occurs after the same amount of time. I have ruled out it being related to a test by removing the test it normally happened on but the issue still occurred. This is a large pipeline running automated UI tests and normally takes about 11 hours to run and runs about 1000 tests, the issue seems to occur after about 4 hours into the test run. I have many other pipelines that are running fine and this issue seems isolated to one specific pipeline. This issue seems to have randomly started happening and this pipeline has been running fine for years until this point. We have many agents and this seems to be occurring on all agents with this pipeline.

### Task logs

I have attached two sets of logs. One zip contains logs without debug turned on but this contains the Vstest.console.exe exited with code -1073741819 exception, the other zip contains logs with debug turned on but this pipeline froze and I had to manually cancel it.

[LogsNoDebugWithError.zip](https://github.com/microsoft/azure-pipelines-tasks/files/5465344/LogsNoDebugWithError.zip)
[LogsDebugHang.zip](https://github.com/microsoft/azure-pipelines-tasks/files/5465346/LogsDebugHang.zip)

I also took a dump of the vstest.console whilst it was hung. This is too big to attach so I've uploaded it, you can download it here: https://1drv.ms/u/s!AuEBsQuFR6hBixnddXg4AG3Sn9Ln?e=8Pkk4C

### Error logs

```
Vstest.console.exe exited with code -1073741819.
**************** Completed test execution *********************
Test results files: 
##[error]Error occurred while publishing test results : MS.VS.TestService.VstestConsoleAdapter.NoTrxFoundException: No trx files found in the specified test results directory C:\Build Agent\_work\_temp\TestResults.
##[error]Skipping marking test run as complete as test run id 0 is invalid.
Completed TestExecution Model...
##[warning]Vstest failed with error. Check logs for failures. There might be failed tests.
##[error]Error: The process 'C:\Build Agent\_work\_tasks\VSTest_ef087383-ee5e-42c7-9a53-ab56c98420f9\2.170.1\Modules\DTAExecutionHost.exe' failed with exit code 1
##[error]Vstest failed with error. Check logs for failures. There might be failed tests.
```

**Comment by tomaustin700** [comment]
Apologies for the delay. Here are the logs and .diag logs for the build that hung today. I had to manually cancel it.
[LogsDiag.zip](https://github.com/microsoft/vstest/files/5696968/LogsDiag.zip)

Let me know if there is anything else you'd like.

Tom

**Comment by ChrisGuzak** [comment]
Might be related to [this issue](https://github.com/microsoft/azure-pipelines-tasks/issues/13404). In my case, a buggy native test (that called `std::terminate()`), resulted in a timeout of the test execution. it seems vstest does not consider this a test failure.

**Comment by jzabroski** [comment]
I think I have the same problem.  In my case, it's a StackOverflowException.  This is super annoying since I don't know how to get the stack trace.  Anyone know ?

```
2021-02-18T15:59:58.7183122Z ##[error]Process is terminated due to StackOverflowException.
2021-02-18T15:59:59.1923972Z Vstest.console.exe exited with code -1073741571.
```

I think we should be turning on this:

| Argument | Description |
| - | - |
| `diagnosticsEnabled` <br/> Collect advanced diagnostics in case of catastrophic failures | (Optional) Use this option to turn on collection of diagnostic data to troubleshoot catastrophic failures such as test crash.When this option is checked, a sequence XML file is generated and attached to the test run. The sequence file contains information about the sequence in which tests ran, so that a potentially culprit test can be identified.<br/>Default value: false |

It's super annoying to have to turn this on when you're using GitVersioning and publishing releases to GitHub.  Now I have a published release that is not going to refer to the right commit.

**Comment by jzabroski** [comment]
@ChrisGuzak Have you tried the `diagnosticsEnabled` flag?  I turned it on and it is producing a crash dump file, but I don't have it in my build output logs.zip - very strange design by AzureDevOps team to let you dump something and not download it easily?

**Comment by jzabroski** [comment]
Since this was closed, it reminded me I never followed up on how to use the `diagnosticsEnabled` flag. It does work, but you have to click Download logs, unzip the logs, and go inside the Job folder to find the vstest step to see the diagnostics data.
