### ISSUE TITLE
Parallelization support inside of single assembly no longer working

### ISSUE THREAD

**Issue by nm4568** [microsoft/vstest#2670]
## Description
In the process of migrating from testsettings to runsettings, I am unable to fully migrate due to limitations in vstest 
parallelization support so I am using ForcedLegacyMode as a work around.  The ability to run tests in parallel within a single dll appears to have been supported in the past but has since been changed.  Here is a blog article written by Microsoft to back this claim up.

https://devblogs.microsoft.com/devops/mstest-v2-in-assembly-parallel-test-execution/

The function 'TestEngine.VerifyParallelSettingAndCalculateParallelLevel' has since been changed and is now limiting the Parallel level by the number of files that you are passing in.  I happen to be passing in one DLL file which contains over 10,000 tests.

Please restore support for Parallelization within an assembly by restoring these two options:

1) Runsettings:

```
     <Parallelize>
      <Workers>4</Workers>
      <Scope>MethodLevel</Scope>
    </Parallelize>
```

2) Assembly decoration:
`[assembly: Parallelize(Workers = 4, Scope = ExecutionScope.MethodLevel)]`

FYI: The Parallelize attribute above still exists in the latest build of VS Test but doesn't function as described in blog article due to atomistic changes made around Parallelization.

## Expected behavior
> Should be able to run tests in parallel within a single dll

## Actual behavior
> What is the behavior observed?
The function TestEngine.VerifyParallelSettingAndCalculateParallelLevel' is changing Parallel setting from 0 to 1 since I am only testing 1dll.

**Comment by Sanan07** [comment]
Please use `/Parallel` argument. [vstest command line arguments](https://docs.microsoft.com/en-us/visualstudio/test/vstest-console-options?view=vs-2019).

**Comment by nm4568** [comment]
I did try using this /Parallel argument which made no difference.  The following function always seems to overwrite the Parallel setting to use 1.

```
private int VerifyParallelSettingAndCalculateParallelLevel(int sourceCount, string runSettings)
        {
            // Default is 1
            int parallelLevelToUse = 1;
            try
            {
                // Check the User Parallel Setting
                int userParallelSetting = RunSettingsUtilities.GetMaxCpuCount(runSettings);
                parallelLevelToUse = userParallelSetting == 0 ? Environment.ProcessorCount : userParallelSetting;
                var enableParallel = parallelLevelToUse > 1;

                EqtTrace.Verbose("TestEngine: Initializing Parallel Execution as MaxCpuCount is set to: {0}", parallelLevelToUse);

                // Verify if the number of Sources is less than user setting of parallel
                // we should use number of sources as the parallel level, if sources count is less than parallel level
                if (enableParallel)
                {
                    parallelLevelToUse = Math.Min(sourceCount, parallelLevelToUse);

                    // If only one source, no need to use parallel service client
                    enableParallel = parallelLevelToUse > 1;

                    if (EqtTrace.IsInfoEnabled)
                    {
                        EqtTrace.Verbose("TestEngine: ParallelExecution set to '{0}' as the parallel level is adjusted to '{1}' based on number of sources", enableParallel, parallelLevelToUse);
                    }
                }
            }
            catch (Exception ex)
            {
                EqtTrace.Error("TestEngine: Error occurred while initializing ParallelExecution: {0}", ex);
                EqtTrace.Warning("TestEngine: Defaulting to Sequential Execution");

                parallelLevelToUse = 1;
            }

            return parallelLevelToUse;
        }
```
