### ISSUE TITLE
TrxLogger & TestCase.Id generation

### ISSUE THREAD

**Issue by JDCain** [microsoft/vstest#2675]
I am attempting to understand how a TestCase.Id is generated and how it connects to the TestId used in the TrxLogger and the Id used within TFS for connecting test case automation to a work item.

To connect a test case to a work item in TFS the following code can be used to generate the Microsoft.VSTS.TCM.AutomatedTestId from the full test case name.
``` csharp
HashAlgorithm provider = SHA1.Create();
byte[] hash = provider.ComputeHash(System.Text.Encoding.Unicode.GetBytes("TestLogger.Common.Tests.TestTests.Test0"));
byte[] toGuid = new byte[16];
Array.Copy(hash, toGuid, 16);
var id = new Guid(toGuid); //3d1c7a33-2f24-2840-4b9d-0926f9062299
```
this code appears to be the same used to generate the hash but with some variation on the string passed into it. 

However when using a `ITestLoggerWithParameters`  the 'TestResultEventArgs' contains a `Result.TestCase.Id` which is totally different for that test: `8e2c12e9-b54b-764f-0d3d-c224ec285881`

Looking over the following areas I have attempted to follow the process and replicate it but I am unable to. 
https://github.com/microsoft/vstest/blob/57527561e6342aaaaca4012dc14d25ad08c0a326/test/Microsoft.TestPlatform.ObjectModel.UnitTests/TestCaseTests.cs#L12
https://github.com/microsoft/vstest/blob/57c4e48042efec946a993ef31b609f296fb7279c/src/Microsoft.TestPlatform.ObjectModel/TestCase.cs#L317

I've also attempted to pull down the source code for the project in order to run the tests and follow the debug output but I have been unable to get it to build correct locally.

**Comment by Haplois** [comment]
`TestId` is not only based on the fully qualified test name. It also includes executionUri and source name. 

After cloning the repository, run `.\scripts\build.ps1` in a PowerShell window; it should build it. After a full build, you can use Visual Studio as you normally would.

**Comment by JDCain** [comment]
Thank you, I will attempt to do that in order to get the project built. That additional info in the string explains part of it for me but I still am missing something with the test logger:

I have a testlogger method which looks like this:
``` csharp
private void DataCollector_TestResult(object sender, Microsoft.VisualStudio.TestPlatform.ObjectModel.Logging.TestResultEventArgs e)
        {
            Console.Out.WriteLine(e.Result.TestCase.Id);
            Console.Out.WriteLine(e.Result.TestCase.ExecutorUri.ToString() + Path.GetFileName(e.Result.TestCase.Source) + e.Result.TestCase.FullyQualifiedName);
        }
```
I attempted to have the output replicate what is happening in GetTestId
``` csharp
    private Guid GetTestId()
    {
      string path = this.Source;
      try
      {
        path = Path.GetFileName(path);
      }
      catch
      {
      }
      Uri executorUri = this.ExecutorUri;
      return EqtHash.GuidFromString(((object) executorUri != null ? executorUri.ToString() : (string) null) + path + this.FullyQualifiedName);
    }
```
Output:
```
[xUnit.net 00:00:28.12]       8e2c12e9-b54b-764f-0d3d-c224ec285881
[xUnit.net 00:00:28.12]       executor://xunit/VsTestRunner2/netcoreappTestLogger.Common.Tests.dllTestLogger.Common.Tests.TestTests.Test0
```

Running the built string through the hash returns "60663ad4-075a-4830-a7e5-51bd2a45be04" even though the actual result is " 8e2c12e9-b54b-764f-0d3d-c224ec285881"

**Comment by Haplois** [comment]
Which version of the test platform are you using? It might use `ManagedType.ManagedClass` instead of the fully equal name. 

https://github.com/microsoft/vstest/blob/57c4e48042efec946a993ef31b609f296fb7279c/src/Microsoft.TestPlatform.ObjectModel/TestCase.cs#L345-L353

**Comment by JDCain** [comment]
16.8.0
I made sure the version installed in the tests matched the version currently listed when running dotnet test.
When I decompile the references using resharper it does not look like the source code online but looks like this:
``` csharp
    private Guid GetTestId()
    {
      string path = this.Source;
      try
      {
        path = Path.GetFileName(path);
      }
      catch
      {
      }
      Uri executorUri = this.ExecutorUri;
      return EqtHash.GuidFromString(((object) executorUri != null ? executorUri.ToString() : (string) null) + path + this.FullyQualifiedName);
    }
```

**Comment by Haplois** [comment]
Yes, the code was a bit different on that version. 

https://github.com/microsoft/vstest/blob/v16.8.0/src/Microsoft.TestPlatform.ObjectModel/TestCase.cs#L213-L239

**Comment by JDCain** [comment]
Based on a test within the project I passed in the ExecutorUri, source, &  FullyQualifiedName which is outputted when the test runs. This generates a Id which matches my manual generation based on the same data, but does not match what is output when I run the test in the runner.
``` csharp
    public class Test
    {
        private TestCase _testCase;

        public Test()
        {
            _testCase = new TestCase("TestLogger.Common.Tests.TestTests.Test0", new Uri("executor://xunit/VsTestRunner2/netcoreapp"), "TestLogger.Common.Tests.dll");
        }

        [Fact]
        public void TestCaseIdIfNotSetExplicitlyShouldReturnGuidBasedOnSourceAndName()
        {
            Assert.Equal("8e2c12e9-b54b-764f-0d3d-c224ec285881", _testCase.Id.ToString());
        }
    }
```

This generates 60663ad4-075a-4830-a7e5-51bd2a45be04 I get when doing it manualy instead of 8e2c12e9-b54b-764f-0d3d-c224ec285881 which is the output of the uniquid during the run. 

Based on the other test "TestCaseIdShouldReturnIdSetExplicitlyEvenIfNameOrSourceInfoChanges" it looks like the UniqueId supports being overwritten. I suppose it's possible then that something is overwriting the default generation at some point in the execution. 

To test this I added the following code to get the defaultId and to call GetTestId via reflection
``` csharp
        private void DataCollector_TestResult(object sender, Microsoft.VisualStudio.TestPlatform.ObjectModel.Logging.TestResultEventArgs e)
        {

            var x = e.Result.TestCase;
            var defaultId = typeof(TestCase).GetField("defaultId", BindingFlags.NonPublic | BindingFlags.Instance).GetValue(x);
            var getTestId = typeof(TestCase)
                .GetMethod("GetTestId", BindingFlags.NonPublic | BindingFlags.Instance)
                .Invoke(x, Array.Empty<object>());


            Console.Out.WriteLine("defaultId: " + defaultId);
            Console.Out.WriteLine("getTestId: " + getTestId);
            Console.Out.WriteLine("Id: " + x.Id);
            Console.Out.WriteLine(e.Result.TestCase.ExecutorUri.ToString() + Path.GetFileName(e.Result.TestCase.Source) + e.Result.TestCase.FullyQualifiedName);
        }
```
The output is now:
```
defaultId: 00000000-0000-0000-0000-000000000000
getTestId: 60663ad4-075a-4830-a7e5-51bd2a45be04
Id: 8e2c12e9-b54b-764f-0d3d-c224ec285881
executor://xunit/VsTestRunner2/netcoreappTestLogger.Common.Tests.dllTestLogger.Common.Tests.TestTests.Test0
```
So manually calling 'GetTestId' generates the same result I get when manually called. However at some point the Id is being written into the TestCase by something else. Any thoughts on where this might come from?

**Comment by JDCain** [comment]
I believe I have found my answer here:
https://github.com/xunit/xunit/blob/a8614d34999c889e1c8014f679de95d20eae1304/src/xunit.runner.visualstudio/Sinks/VsDiscoverySink.cs#L89

the xUnit discovery generates a new Guid based on the executor + the uniqueId xUnit creates based on the name + parameters which is then run through a hash to get a guid. These seem to match up with TestId I see in outputs of Trx files. 

Thanks for helping me work through this.

**Comment by Haplois** [comment]
We’re planning to expose a public API for testId generation in future releases; also, keep in mind that Id generation logic is changed in v16.9 and will change further to handle some edge cases better.
