### ISSUE TITLE
Test host crashes without any errors in the logs

### ISSUE THREAD

**Issue by Nefarion** [microsoft/vstest#2710]
## Description
After running dotnet test on my project, i recieve `The active test run was aborted. Reason: Test host process crashed` in the console, and a non-zero exit code.

Everything in the logs indicates that the process ran to completion, and vstest.console did not recognize that.

Tests were run with:  
`dotnet test -verbosity:diagnostic -bl:msbuild.binlog -noconsolelogger --diag:log.txt`

when running dotnet test --blame i get a "warning" about no crashes in the tests, and thus no sequence.xml file

Project and TestProject are .Net 4.8

## Diagnostic logs
[log.txt](https://gist.github.com/Nefarion/94c18377028665f5e6b45945f07d6bc4)
[host.txt](https://gist.github.com/Nefarion/51350682345e0dabb0d29c883d03f52b)

## Environment
OS: Windows 10 Pro N, 20H2 (19042.746)
dotnet --version: 5.0.102

**Comment by Sanan07** [comment]
You can get dump file of testhost in Task Manager, right click on testhost proces -> Create Dump File and share with us.

**Comment by Nefarion** [comment]
Files are here: [Link](https://engie-my.sharepoint.com/:f:/p/gt5845/EhObEazRZQBOn_wqT8XDX_kBxX3K8JU-tg3XGpTfe_3FBw?e=mQQcBN)

**Comment by Sanan07** [comment]
I briefly looked and it did not give me anything valuable, in the same time you can debug it it [VS ](https://docs.microsoft.com/en-us/visualstudio/debugger/using-dump-files?view=vs-2019).
I will continue my investigation and will let you know.

**Comment by Nefarion** [comment]
To me, it looks like testhost.net48 exits gracefully, and vstest.console THINKS it crashed, but it did not.
In the logs, i can see the "final" transmission of the Testcases and their results, so i think testhost.net48 did his job.

**Comment by Nefarion** [comment]
I tried it with 3.1.405, same result.

I realised its one of my dependencies that does not like beeing referenced in a testproject, without it, it works!
Sorry for the trouble!

**Comment by Romout** [comment]
Sorry for bringing that back up! @Nefarion: Could you go into more detail which dependency or what kind of dependency caused that trouble as I am facing the same issue? (>100 Unit-test projects - hard to find the needle...)

**Comment by Romout** [comment]
Hm, okay. Thank you for your quick response! Unfortunately, that doesn't ring a bell but maybe it's part of a 3rd party reference which is doing something similar. I will further investigate. Thanks again!
