### ISSUE TITLE
[Windows ARM64] with NET 6 preview 1 SDK installed, Unhandled exception when running dotnet test

### ISSUE THREAD

**Issue by vdanche** [microsoft/vstest#2728]
**Repro steps:**
Install dotnet-sdk-6.0.100-preview.1.21102.16-win-arm64.exe from https://github.com/dotnet/installer under Release/6.0.1xx-preview1 branch on windows ARM64 machine
dotnet new xunit or mstest
dotnet test

**Expected behavior**
Should successfully run the test included in the template.
**Actual behavior**
![image](https://user-images.githubusercontent.com/65637796/106710570-1a8fe280-6631-11eb-9e81-b0d354e8ef53.png)

Note:
not repro on nunit

log(dotnet test --diag:log.txt) has been attached:
[log.txt](https://github.com/microsoft/vstest/files/5916690/log.txt)

AB#1274633

**Comment by vdanche** [comment]
similar reported issue [#2473](https://github.com/microsoft/vstest/issues/2473) on .NET 5 which has been fixed

**Comment by nohwnd** [comment]
https://github.com/dotnet/test-templates/pull/121 Issue is specific to 16.7.0 and 16.8.0 Test.SDK package. Fix is to manually update the project to use a newer (or <=16.6.1). We are updating the templates in the PR above.

**Comment by vdanche** [comment]
The issue has been fixed on .NET 6 preview 1 SDK: 6.0.100-preview.2.21127.3(runtime:6.0.0-preview.2.21123.7)
