### ISSUE TITLE
Is it possible to generate file instead of output to Console for switch --list-tests?

### ISSUE THREAD

**Issue by huiren-jiang** [microsoft/vstest#2740]
## Description
We hope to get the filtered test case list and process it using code, so we dotnet test could generate file (e.g. JSON) to export the case list instead of everything is output to console.

## Steps to reproduce
dotnet test --list-tests

## Expected behavior
The filtered test case list exported as specific format.

## Actual behavior
The filtered test case list is output to console.

## Diagnostic logs
N/A.

## Environment
.NET SDK 5.

**Comment by nohwnd** [comment]
Not at the moment, but you can either use vstest console wrapper to discover tests. Or write a custom logger to store your tests into a file. It's rather simple, you add a class lib that references testplatform object model, and name it *.TestLogger.dll


You also specify friendly name for the logger and handle the tests discovered event in it. Here is a quick example of a logger that saves the fully qualified names in json array in the current directory. 

```cs 
using Microsoft.VisualStudio.TestPlatform.ObjectModel;
using Microsoft.VisualStudio.TestPlatform.ObjectModel.Client;
using System.Collections.Generic;
using System.IO;
using System.Linq;

namespace JsonLogger
{
    [FriendlyName("Json")]
    [ExtensionUri("logger://JsonDiscovery")]
    public class Logger : ITestLoggerWithParameters
    {
        private string _path;

        public void Initialize(TestLoggerEvents events, Dictionary<string, string> parameters)
        {
            _path = parameters.TryGetValue("path", out string path)
                ? path
                : Path.Combine(Directory.GetCurrentDirectory(), "discoveredTests.json");
            events.DiscoveredTests += (_, e) => SaveDiscoveredTests(e.DiscoveredTestCases);
        }

        public void Initialize(TestLoggerEvents events, string testRunDirectory)
        {

        }

        private void SaveDiscoveredTests(IEnumerable<TestCase> discoveredTestCases)
        {
            var names = discoveredTestCases.Select(t => t.FullyQualifiedName).ToList();
            var json = System.Text.Json.JsonSerializer.Serialize(names);
            File.WriteAllText(_path, json);
        }
    }
}
```

```xml 
<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>netstandard2.0</TargetFramework>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.TestPlatform.ObjectModel" Version="16.8.3" />
    <PackageReference Include="System.Text.Json" Version="5.0.1" />
  </ItemGroup>

</Project>
```

You can then run it like this (when standind in a folder of a test project): 

```shell
 dotnet test --test-adapter-path "C:\t\DiscoveryLogger\JsonLogger\bin\Debug\netstandard2.0\" --logger json --list-tests
```

If you'd publish your logger as nuget or referenced it in any other way, it would get picked up automatically, and you would not need the --test-adapter-path parameter, but you'd still need --logger json to select it.

**Comment by huiren-jiang** [comment]
Hi Jakub,

Actually I'm using test logger, but I didn't know that it can discover tests even if `--list-tests` is specified. Your solution perfectly solves my problem.

Thank you so much!
