### ISSUE TITLE
Coded UI IE browser test hangs when trying to enter text in a dialog input prompt

### ISSUE THREAD

**Issue by icnocop** [microsoft/vstest#2747]
## Description
Calling `browserWindow.PerformDialogAction(BrowserDialogAction.PromptText, "input text");` will hang and not input the text in the dialog prompt.

![Internet Explorer User Prompt](https://user-images.githubusercontent.com/507649/107901467-89562100-6ef8-11eb-9186-f9f40dd4405a.PNG)

## Steps to reproduce
1. Clone repo https://github.com/icnocop/CodedUITestProject472_PerformDialogAction_PromptText
2. Open sln in Visual Studio 2019 and build
3. Run `InputTextInBrowserPrompt` test

## Expected behavior
I expected the test to automatically input text in the browser dialog input prompt.

## Actual behavior
The test hangs and doesn't complete.

## Diagnostic logs
`"C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\Common7\IDE\CommonExtensions\Microsoft\TestWindow\vstest.console.exe" CodedUITestProject472.dll --diag:log.txt`
[log.txt](https://github.com/microsoft/vstest/files/5979322/log.txt)

## Environment
Windows 10 64-bit Version 20H2 OS Build 19042.685
Internet Explorer 11.0.19041.1
Visual Studio Enterprise 2019 16.8.5
vstest.console.exe 16.0.30712.155

I also reported the issue here: https://developercommunity2.visualstudio.com/t/coded-ui-ie-browser-test-hangs-when-trying-to-ente/1339013.

**Comment by nohwnd** [comment]
@Sanan07 please have a look 🙂

**Comment by Evangelink** [comment]
Internet Explorer is no longer supported and Coded UI Tests are deprecated.
