### ISSUE TITLE
Feature request: Support TestOutcome NUnit 'Inconclusive' 

### ISSUE THREAD

**Issue by SamJongenelen** [microsoft/vstest#2755]
## Description

Currently, it appears that test NUnits'  testoutcome _Inconclusive_  is mapped to _Not Run_ in vstest. 
I would like to be able to use the _Inconclusive_ outcome in the test run reports.

## Steps to reproduce
- VS2019 +  netcore3.1 Test project  +  NUnit + NUnit3TestAdapternuget packages (see code snippets below)
- Have testmethod with `NUnit.Inconclusive("test" );`
- run test
- observe test outcome in Test explorer (see screenshot below)

### example setup
**CSproj**
```
<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>netcoreapp3.1</TargetFramework>
    <IsPackable>false</IsPackable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.NET.Test.Sdk" Version="16.5.0" />
    <PackageReference Include="NUnit" Version="3.13.1" />
    <PackageReference Include="NUnit3TestAdapter" Version="3.17.0" />
  </ItemGroup>

</Project>

```
**Testclass:**
```
using System.Collections.Generic;
using NUnit.Framework;

namespace UnitTestProject1
{
    [TestFixture]
    public class UnitTest1
    {
        [Test]
        public void TestMethod()
        {
            Assert.Inconclusive("test");
        }
    }
}

```
## Expected behavior

The TestOutcome _Inconclusive_ is shown in Test runner. 

## Actual behavior

The TestOutcome _Not Run_ is shown in Test runner. 
![image](https://user-images.githubusercontent.com/3382443/108056577-bb2ecb00-7051-11eb-9b5e-c1d209582f08.png)

## Diagnostic logs
na

## Environment
windows 10, vstest.console version na

**Comment by nohwnd** [comment]
This would help fix https://github.com/microsoft/testfx/issues/689

**Comment by nohwnd** [comment]
At the moment we can only represent the states that are listed in TestOutcome, we would have to add it there, and also add it to TestExplorer.

**Comment by Haplois** [comment]
Supporting this in Visual Studio Test Window is not on out mid-term plans; so as @nohwnd said we are limited here. We'll gather more feedback before starting the work on this.

/cc @kendrahavens
