### ISSUE TITLE
Project is unbuildable due to missing feed

### ISSUE THREAD

**Issue by thestonehead** [microsoft/vstest#2761]
## Description
  I can't build the project from source due to missing feed "https://dotnet.myget.org/F/vstest/api/v3/index.json".
Same thing if I just run dotnet restore.
When I use my browser to go to that feed it says that it doesn't exist: "Feed does not exist."

## Steps to reproduce
1. Clone or download source code
2. run build.sh or build.cmd

## Expected behavior
I expect the project to be built.

## Actual behavior

>   Determining projects to restore...
> /opt/vstest/tools/dotnet-linux/sdk/5.0.100-rc.1.20380.12/NuGet.targets(128,5): error : Unable to load the service index for source https://dotnet.myget.org/F/vstest/api/v3/index.json. [/opt/vstest/src/package/external/external.csproj]
> /opt/vstest/tools/dotnet-linux/sdk/5.0.100-rc.1.20380.12/NuGet.targets(128,5): error :   Response status code does not indicate success: 404 (Feed does not exist.). [/opt/vstest/src/package/external/external.csproj]
> ... Failed to restore packages.
> ... Build failed. Elapsed 6s.

## Environment
Tried on Debian and on Windows.

**Comment by Haplois** [comment]
Hi @thestonehead,

We replaced the package sources; which branch are you trying to build? Are you sure you have the latest commit?

**Comment by thestonehead** [comment]
You are correct.
I was building the last tagged version and not master.

My mistake.

**Comment by Haplois** [comment]
No worries, if you replace the `NuGet.config` file with the one in the `master` branch, that should successfully build as well.
