### ISSUE TITLE
Wrong error message when filtering test with a test name that does not exists

### ISSUE THREAD

**Issue by livarcocc** [Microsoft/vstest#278]
dotnet test -tcf="FullyQualifiedName=Microsoft.DotNet.ProjectJsonMigration.Tests.GivenThatIWantToMigratePublishOptions.MigratingPublishOptionsIncludeEmitsConditionalAttribute"
Build started, please wait...
Build completed.

Test run for /Users/livarcocc/Documents/git/cli/test/Microsoft.DotNet.ProjectJsonMigration.Tests/bin/Debug/netcoreapp1.0/Microsoft.DotNet.ProjectJsonMigration.Tests.dll(.NETCoreApp,Version=v1.0)
Microsoft (R) Test Execution Command Line Tool Version 15.0.0.0
Copyright (c) Microsoft Corporation.  All rights reserved.

Starting test execution, please wait...
Warning: No test is available in /Users/livarcocc/Documents/git/cli/test/Microsoft.DotNet.ProjectJsonMigration.Tests/bin/Debug/netcoreapp1.0/Microsoft.DotNet.ProjectJsonMigration.Tests.dll. Make sure that installed test discoverers & executors, platform & framework version settings are appropriate and try again.

It says that no tests exist in the dll, when it should say that the filtered test does not exist in the dll.

**Comment by mayankbansal018** [comment]
Closing this issue as it is low priority, please re-open if it is requested by more users
