### ISSUE TITLE
Could not load type 'Microsoft.VisualStudio.TestPlatform.ObjectModel.ManagedNameUtilities.ManagedNameHelper' from assembly 'Microsoft.VisualStudio.TestPlatform.ObjectModel, Version=15.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'

### ISSUE THREAD

**Issue by pcartwright81** [microsoft/vstest#2783]
## Description
When running in Windows CMD, PowerShell, or Visual Studio 2019 an exception is thrown on an empty unit test or the Microsoft sample if the NuGet package is updated to Microsoft.NET.Test.Sdk > 16.9.0-preview-20210106-01.  There are no app.configs in either location.  Since 16.9.1 is a stable version but > 16.9.0-preview-20210106-01 it is also affected.

## Steps to reproduce
Create new Unit Test Project with Microsoft.NET.Test.Sdk > 16.9.0-preview-20210106-01.

## Expected behavior
The unit tests to run when running dotnet test.

## Actual behavior
The unit tests don't run when running dotnet test, instead the below exception is thrown.

## Diagnostic logs
On MS Sample
[MSTest][Discovery][bin\Debug\netcoreapp3.1\MSTest.Project.dll] MSTestAdapter failed to discover tests in class 'MSTest.Project.ByAlphabeticalOrder' of assembly 'bin\Debug\netcoreapp3.1\MSTest.Project.dll' because Could not load type 'Microsoft.VisualStudio.TestPlatform.ObjectModel.ManagedNameUtilities.ManagedNameHelper' from assembly 'Microsoft.VisualStudio.TestPlatform.ObjectModel, Version=15.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'..
No test is available in \bin\Debug\netcoreapp3.1\MSTest.Project.dll. Make sure that test discoverer & executors are registered and platform & framework version settings are appropriate and try again.

On New .Net 5.0 Test
[MSTest][Discovery][\bin\Debug\net5.0\TestProject1.dll] MSTestAdapter failed to discover tests in class 'TestProject1.UnitTest1' of assembly '\bin\Debug\net5.0\TestProject1.dll' because Could not load type 'Microsoft.VisualStudio.TestPlatform.ObjectModel.ManagedNameUtilities.ManagedNameHelper' from assembly 'Microsoft.VisualStudio.TestPlatform.ObjectModel, Version=15.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'..
No test is available in \bin\Debug\net5.0\TestProject1.dll. Make sure that test discoverer & executors are registered and platform & framework version settings are appropriate and try again.

## Environment
Windows 10
5.0.200-preview.21079.7

**Comment by Sanan07** [comment]
@pcartwright81 You should install this nuget package : [Microsoft.TestPlatform.AdapterUtilities](https://dev.azure.com/dnceng/public/_packaging?_a=package&feed=test-tools&package=Microsoft.TestPlatform.AdapterUtilities&protocolType=NuGet&version=16.10.0-preview-20210228-03)

**Comment by pcartwright81** [comment]
My project file looks like this now, and I have the same issue.
<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net5.0</TargetFramework>
    <IsPackable>false</IsPackable>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.NET.Test.Sdk" Version="16.10.0-preview-20210219-03" />
    <PackageReference Include="Microsoft.TestPlatform.AdapterUtilities" Version="16.9.1" />
    <PackageReference Include="MSTest.TestAdapter" Version="2.2.0-preview-20210115-03" />
    <PackageReference Include="MSTest.TestFramework" Version="2.2.0-preview-20210115-03" />
    <PackageReference Include="coverlet.collector" Version="3.0.3">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
  </ItemGroup>

</Project>

**Comment by Sanan07** [comment]
@Haplois Could you please look at this?

**Comment by Haplois** [comment]
@pcartwright81, `Microsoft.TestPlatform.AdapterUtilities` has some breaking changes. You can't use that preview with it. Please wait for the release of  `v2.2.0`, or use the latest preview package from https://dev.azure.com/dnceng/public/_packaging?_a=feed&feed=test-tools.

Also, please don't mix versions if you're referencing TestPlatfrom packages explicitly. `Microsoft.NET.Test.Sdk` and `Microsoft.TestPlatform.AdapterUtilities` packages should be the same version.

**Comment by pcartwright81** [comment]
After making the project look like this, and deleting the bin, obj, and TestResults folder it is now working.
```project
<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net5.0</TargetFramework>

    <IsPackable>false</IsPackable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.NET.Test.Sdk" Version="16.9.1" />
    <PackageReference Include="MSTest.TestAdapter" Version="2.1.2" />
    <PackageReference Include="MSTest.TestFramework" Version="2.1.2" />
    <PackageReference Include="coverlet.collector" Version="3.0.3">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
  </ItemGroup>

</Project>
