### ISSUE TITLE
Data collector 'Blame' message: Could not start process dump: System.ArgumentException: Illegal characters in path.

### ISSUE THREAD

**Issue by sonnin** [microsoft/vstest#2800]
## Description
When running unittest on the command line, sometime the test fails with:
"The active test run was aborted. Reason: Test host process crashed"
This does not happen when running the tests from within Visual Studio.

When trying to identify what happens I have add /Blame:CollectDump which gives below error message.

How do I troubleshoot this?
What paths are used and my contain illegal characters? (perhaps the invalid path could be logged by the tool)

## Steps to reproduce
Complete executed command:
"C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\Common7\IDE\CommonExtensions\Microsoft\TestWindow\vstest.console.exe" /Logger:trx /Platform:x64 J:\depot\hs\project\7.36\bin\unittest.dll /testcasefilter:xxx /Blame:CollectDump

## Expected behavior
A complete and useful dump

## Actual behavior
Starting test execution, please wait...
  Passed xxx [2 ms]
The active test run was aborted. Reason: Test host process crashed
Data collector 'Blame' message: Could not start process dump: System.ArgumentException: Illegal characters in path.
   at System.IO.Path.CheckInvalidPathChars(String path, Boolean checkAdditional)
   at System.IO.Path.Combine(String path1, String path2)
   at Microsoft.TestPlatform.Extensions.BlameDataCollector.ProcDumpCrashDumper.TryGetExecutablePath(String executable, String& executablePath)
   at Microsoft.TestPlatform.Extensions.BlameDataCollector.ProcDumpCrashDumper.TryGetProcDumpExecutable(Int32 processId, String& path)
   at Microsoft.TestPlatform.Extensions.BlameDataCollector.ProcDumpCrashDumper.AttachToTargetProcess(Int32 processId, String outputDirectory, DumpTypeOption dumpType)
   at Microsoft.TestPlatform.Extensions.BlameDataCollector.ProcessDumpUtility.CrashDump(Int32 processId, String tempDirectory, DumpTypeOption dumpType, String targetFramework)
   at Microsoft.TestPlatform.Extensions.BlameDataCollector.BlameCollector.TestHostLaunchedHandler(Object sender, TestHostLaunchedEventArgs args).
Data collector 'Blame' message: All tests finished running, Sequence file will not be generated.
Results File: J:\depot\hs\project\7.36\TestResults\visnv_WSVISNV01_2021-03-05_12_57_54.trx

## Diagnostic logs
TpTrace Information: 0 : 14320, 7, 2021/03/05, 13:08:10.481, 15463290753210, vstest.console.exe, TestRequestSender: GetAbortErrorMessage: Received test host error message.
TpTrace Error: 0 : 14320, 7, 2021/03/05, 13:08:10.482, 15463290757140, vstest.console.exe, TestRequestSender: Aborting test run because Test host process crashed
TpTrace Verbose: 0 : 14320, 7, 2021/03/05, 13:08:10.482, 15463290760327, vstest.console.exe, TestRunRequest:SendTestRunMessage: Starting.
TpTrace Information: 0 : 14320, 7, 2021/03/05, 13:08:10.482, 15463290761183, vstest.console.exe, TestRunRequest:SendTestRunMessage: Completed.
TpTrace Verbose: 0 : 14320, 7, 2021/03/05, 13:08:10.491, 15463290846974, vstest.console.exe, ProxyOperationManager.Close: waiting for test host to exit for 100 ms
TpTrace Warning: 0 : 14320, 7, 2021/03/05, 13:08:10.491, 15463290847822, vstest.console.exe, ProxyOperationManager: Timed out waiting for test host to exit. Will terminate process.
TpTrace Verbose: 0 : 14320, 7, 2021/03/05, 13:08:10.492, 15463290857448, vstest.console.exe, ProxyDataCollectionManager.InvokeDataCollectionServiceAction: Starting.
TpTrace Information: 0 : 14320, 7, 2021/03/05, 13:08:10.492, 15463290860435, vstest.console.exe, ProxyDataCollectionManager.AfterTestRunEnd: Get attachment set for datacollector processId: 28512 port: 53786
TpTrace Verbose: 0 : 14320, 7, 2021/03/05, 13:08:10.492, 15463290865000, vstest.console.exe, DataCollectionRequestSender.SendAfterTestRunStartAndGetResult : Send AfterTestRunEnd message with isCancelled: False
TpTrace Verbose: 0 : 14320, 7, 2021/03/05, 13:08:10.493, 15463290867125, vstest.console.exe, DataCollectionRequestSender.SendAfterTestRunStartAndGetResult : Received message: (DataCollection.SendMessage) -> {
  "FriendlyName": "Blame",
  "Uri": "datacollector://Microsoft/TestPlatform/Extensions/Blame/v1",
  "TestCaseId": "00000000-0000-0000-0000-000000000000",
  "Message": "Could not start process dump: System.ArgumentException: Illegal characters in path.\r\n   at System.IO.Path.CheckInvalidPathChars(String path, Boolean checkAdditional)\r\n   at System.IO.Path.Combine(String path1, String path2)\r\n   at Microsoft.TestPlatform.Extensions.BlameDataCollector.ProcDumpCrashDumper.TryGetExecutablePath(String executable, String& executablePath)\r\n   at Microsoft.TestPlatform.Extensions.BlameDataCollector.ProcDumpCrashDumper.TryGetProcDumpExecutable(Int32 processId, String& path)\r\n   at Microsoft.TestPlatform.Extensions.BlameDataCollector.ProcDumpCrashDumper.AttachToTargetProcess(Int32 processId, String outputDirectory, DumpTypeOption dumpType)\r\n   at Microsoft.TestPlatform.Extensions.BlameDataCollector.ProcessDumpUtility.CrashDump(Int32 processId, String tempDirectory, DumpTypeOption dumpType, String targetFramework)\r\n   at Microsoft.TestPlatform.Extensions.BlameDataCollector.BlameCollector.TestHostLaunchedHandler(Object sender, TestHostLaunchedEventArgs args)",
  "Level": 1
}
TpTrace Verbose: 0 : 14320, 7, 2021/03/05, 13:08:10.493, 15463290869234, vstest.console.exe, TestRunRequest:SendTestRunMessage: Starting.
TpTrace Information: 0 : 14320, 7, 2021/03/05, 13:08:10.493, 15463290870074, vstest.console.exe, TestRunRequest:SendTestRunMessage: Completed.
TpTrace Verbose: 0 : 14320, 7, 2021/03/05, 13:08:10.497, 15463290910474, vstest.console.exe, DataCollectionRequestSender.SendAfterTestRunStartAndGetResult : Received message: (DataCollection.SendMessage) -> {
  "FriendlyName": "Blame",
  "Uri": "datacollector://Microsoft/TestPlatform/Extensions/Blame/v1",
  "TestCaseId": "00000000-0000-0000-0000-000000000000",
  "Message": "All tests finished running, Sequence file will not be generated",
  "Level": 1
}
TpTrace Verbose: 0 : 14320, 7, 2021/03/05, 13:08:10.497, 15463290912023, vstest.console.exe, TestRunRequest:SendTestRunMessage: Starting.

## Environment
Windows Version 10.0.18363 Build 18363
Microsoft (R) Test Execution Command Line Tool Version 16.8.0

**Comment by nohwnd** [comment]
Do you also have logs from the datacollector? They should be in the same folder as the diagnostic log you posted. You can also add "/diag:logs\log.txt"  and you will find the logs in folder called logs in your current folder.

**Comment by sonnin** [comment]
Here is the output from --diag:log.txt;tracelevel=verbose
[log.txt](https://github.com/microsoft/vstest/files/6090601/log.txt)

**Comment by sonnin** [comment]
Any ideas on which path it may be complaining about?

**Comment by nohwnd** [comment]
Dropped the ball on this one unfortuntely. The logs did not give any useful info, because they are console logs and not data collector logs. Sorry. :😢
