### ISSUE TITLE
Update Arcade to 6.0

### ISSUE THREAD

**Issue by MichaelSimons** [microsoft/vstest#2804]
The infra enabling ArPow (arcade-powered source-build) requires repos to be on Arcade 6.0.  See the [Implementation Plan](https://github.com/dotnet/source-build/blob/master/Documentation/planning/arcade-powered-source-build/implementation-plan.md) for ArPow details.

@nohwnd, Is this something that would be feasible to do?

**Comment by nohwnd** [comment]
@Haplois  what do you think?

**Comment by crummel** [comment]
@nohwnd @Haplois I made the very simple changes to restore a newer Arcade: https://github.com/microsoft/vstest/pull/2890.  This would at least get Arcade available, which would let us use a wrapper to call into the source-build tasks for now.  Does that seem like an okay change to make until you do a full Arcade switchover?

**Comment by crummel** [comment]
That'll probably be fine, when's the sprint end?  Thanks for working on the upgrade!

**Comment by Haplois** [comment]
@crummel, 31st of May.

**Comment by Haplois** [comment]
This should be fixed by #2913, please let us know if not.
