### ISSUE TITLE
Incorrect format for TestCaseFilter: Missing '|' or '&' operator

### ISSUE THREAD

**Issue by noelex** [microsoft/vstest#2807]
## Description
When I try to run tests in Visual Studio, it fails to discover tests with the following error message:
```
Incorrect format for TestCaseFilter: Missing '|' or '&' operator
```
I can run tests with manually written test case filter using `vstest.console.exe` without any problem, but not with the following filter generated by Visual Studio:
```
"FullyQualifiedName=GeographicLib.Tests.DMSTests.TestDecode|FullyQualifiedName=GeographicLib.Tests.DMSTests.TestDecode(System.Double,System.Double,System.String)"
```

## Steps to reproduce
Clone source code from [here](https://github.com/noelex/GeographicLib.NET.git) and run tests in Visual Studio, or execute `vstest.console.exe` with the filter given above.

## Expected behavior
Should be able to discover and run tests without any problem.

## Actual behavior
Test execution fails with error message
 ```
Incorrect format for TestCaseFilter: Missing '|' or '&' operator
```

## Diagnostic logs
[logs.host.21-03-09_08-59-57_60897_7.txt](https://github.com/microsoft/vstest/files/6105338/logs.host.21-03-09_08-59-57_60897_7.txt)

## Environment
Visual Studio 16.9.0
Test Execution Command Line Tool Version 16.9.1
Microsoft.NET.Test.Sdk 16.9.1
Windows 10 2004 Build 19041.804

**Comment by Sanan07** [comment]
@noelex You have brackets in your TestCaseFilter epression, you should escape them. So it should look like this : 
```
/TestCaseFilter:"FullyQualifiedName=GeographicLib.Tests.DMSTests.TestDecode|FullyQualifiedName=GeographicLib.Tests.DMSTests.TestDecode\(System.Double,System.Double,System.String\)"
```
You can read more about TestCaseFilter [here](https://github.com/Microsoft/vstest-docs/blob/master/docs/filter.md).

**Comment by noelex** [comment]
@Sanan07 Thank you for pointing out. Looks like it's a bug in [testfx](https://github.com/microsoft/testfx/issues/793), closing this issue.
