### ISSUE TITLE
dotnet test does not detect tests using Test SDK 16.9.1 and .Net Core 3.1

### ISSUE THREAD

**Issue by s-glatshtein** [microsoft/vstest#2814]
Steps to reproduce:
I created a new NUnit project with Visual Studio and .net core 3.1. It contained the following dependencies:

```
Microsoft.NET.Test.Sdk (16.9.1)
NUnit (3.13.0)
NUnit3TestAdapter
```

The project is created with a simple empty test, which I can see in the test explorer and execute through it.
However, I have CLI which uses `dotnet test` to run these tests. When I run the following command, i get no tests:
`dotnet test -t MyFirstTestProject.dll`

Downgrading Test Sdk to 16.8.3 solves this issue.

[AB#1287840](https://devdiv.visualstudio.com/0bdbc590-a062-4c3f-b0f6-9383f67865ee/_workitems/edit/1287840)

**Comment by IvanAlekseev** [comment]
@Haplois do we need to wait for .NET 6 release for a proper fix?

**Comment by Haplois** [comment]
No, We will fix this with our next release.
