### ISSUE TITLE
Bring back the 'copy all' from test results panel

### ISSUE THREAD

**Issue by zaus** [microsoft/vstest#2821]
## Description
VS2017 had a quick link to 'Copy All' from the test results panel, in addition to an 'Output' link which opened the output text in a new tab.
VS2019 instead only has a link to 'Open additional output for this result', and a right-click context option from the test-hierarchy listing to "Copy Details" which only copies the truncated details, necessitating opening the test output in a new tab > right-click > Copy All

## Steps to reproduce
Run a test

## Expected behavior
Easily-accessible "Copy All" feature.

## Actual behavior
Feature no longer obvious, buried behind a context menu, which then doesn't actually do the same thing, thus requiring additional steps anyway.

## Environment
Visual Studio 2019

Apologies if this isn't the right place for this 'feature request', I arrived from [this VS2019 Test Explorer documentation](https://docs.microsoft.com/en-us/visualstudio/test/test-explorer-faq?view=vs-2019) which suggested this repo for sorting requests.

**Comment by Sanan07** [comment]
It is not related to vstest. Please provide your suggestion here : https://developercommunity.visualstudio.com/
