### ISSUE TITLE
CodeCoverage.exe analyze running from command line should search for all coverage files 

### ISSUE THREAD

**Issue by gremlm** [microsoft/vstest#2825]
Hi All, We are trying to use Visual Studio 2019 _CodeCoverage.exe analyze_ running from command line. 
Unfortunately, support of the multiple .coverage files is very limited.

1. CodeCoverage.exe it does not accept _*.coverage_ as input! 
We get *.coverage files in directory, and instead of having something like
_CodeCoverage.exe analyze test1.coverage test2.coverage test3.coverage test4.coverage test4.coverage ..._
it would be much better to have option just to run 
_CodeCoverage.exe analyze *.coverage_ 

2. Another, better option, would be to specify root directory where CodeCoverage starts to search recursively, going to each subdirectory, for specified coverage files: 
Often test result directory has multiple sub directories named as GUIDs, containing *.coverage* files: 

TestResults
                 | -GUID1 DIR -some1.coverage                                    
                 | -GUID2 DIR - some2.coverage 
                 | -GUID3 DIR - some3.coverage
                           
  In this case we need something like _CodeCoverage.exe analyze *.coverage* --dir  .\TestResults_
  where option _--dir_ points to recursive search in the following directory. 

[AB#1344029](https://devdiv.visualstudio.com/0bdbc590-a062-4c3f-b0f6-9383f67865ee/_workitems/edit/1344029)

**Comment by jakubch1** [comment]
This logic was added to code coverage dotnet global tool. Please track it here: #2424
Closing this.
