### ISSUE TITLE
Question: Does VSTest Project have an interface to handle cancellation?

### ISSUE THREAD

**Issue by kendrahavens** [microsoft/vstest#2832]
Transferred from [Developer community](https://developercommunity.visualstudio.com/t/Does-VSTest-Project-has-interface-to-han/1355725).

Initial Feedback text from user:
> I want to clarify whether VSTest project has additional function to handle “cancel” command. So I could save some report/summary before test case terminated. Just like [TestCleanup()] or [ClassCleanup()].

**Comment by nohwnd** [comment]
There is none.
