### ISSUE TITLE
Option to log test class names or fully qualified test names

### ISSUE THREAD

**Issue by yogilad** [microsoft/vstest#2845]
VSTest results do not include the test class name which makes it hard to understand the context of a failed test from the test name alone, especially when running all product test suites which include thousands of tests.

Another interesting case we have is a base class which contains test methods testing an interface, and multiple test classes which inherit it and instantiate different implementations of said interface.
In this case there is no way to make out the context of a test from the console or TRX file.

Would it be possible to get an option to list the class name or fully qualified test name in test results (Console, TRX etc.)?
Something like
```
vstest.console mymodule /logger:[console|trx];testnames=[default|classandmethod|fqn]
...
Passed ClassName.TestName [x ms]
or
Passed FullyQualifiedTestName [y ms]
```

**Comment by nohwnd** [comment]
I think we solved this over email.
