### ISSUE TITLE
dotnet vstest does not give error if incorrect --framework is provided

### ISSUE THREAD

**Issue by codito** [Microsoft/vstest#286]
## Description
Test run if user attempts to run netcoreapp test project with `--framework:".NETFramework,Version=v4.6"`

## Steps to reproduce
```
> dotnet new -t mstest
> dotnet vstest bin\Debug\netcoreapp1.0\testapp.dll --framework:".NETFramework,Version=v4.6"
```

## Expected behavior
Error message.

## Actual behavior
Test run hangs.

## Environment
vstest repo at 9da5eb8
OS: Ubuntu 16.04

**Comment by sbaid** [comment]
on latest build - does not hang. but does not give any error.
