### ISSUE TITLE
Console logged test results are mixed together

### ISSUE THREAD

**Issue by BradBarnich** [microsoft/vstest#2899]
## Description
Console output for test results are being mixed together, causing mixed up colors incoherent output.

## Steps to reproduce
`dotnet test <the.sln> --no-build --filter "<a-filter>" --verbosity=normal`

## Expected behavior
Serial output of test results with consistent colors

## Actual behavior
test results mixed together, causing colors to leak. Can see "Passed" is printed twice in green before the name of the test, and then following test names are written in green instead of white as they are supposed to be.

![image](https://user-images.githubusercontent.com/1286709/118026337-b2872180-b32e-11eb-8b58-0850718cd812.png)

## Diagnostic logs
> Please share test platform diagnostics logs. Instructions to collect logs are [here](https://github.com/Microsoft/vstest-docs/blob/master/docs/diagnose.md#test-platform-diagnostics).  
> The logs may contain test assembly paths, kindly review and mask those before sharing.

## Environment
windows, .net 5.0.202, command prompt (but same results with windows terminal)

**Comment by Evangelink** [comment]
Duplicates of #3525
