### ISSUE TITLE
testhost.net472 leaks 4GB memory chunks when TargetPlatform=x64

### ISSUE THREAD

**Issue by RobSwDev** [microsoft/vstest#2907]
When running the tests in a specific test dll, if we set the TargetPlatform to x64, testhost.net472 private memory steps up in 4GB increments. This soon makes the OS unresponsive, and makes the tests take much longer than expected.
If I let the target platform default to x86, no such issue is observed. This is the command I use:

`vstest.console MyTest.dll /tests:SomeTests  /platform:x64`

Running 9 tests (with platform=x64) causes the active private working set to rise to 24GB. With platform=x86, the workingset stays well below 1GB. 
This does not happen with every test assembly, just a select few.

What steps can I take to diagnose this issue? We're not sure when it started, though we only noticed it recently. It's possible devs have been running the tests using x86 platform and so not noticed.
I tried connecting to the testhost process with windbg, and the managed heap is very small.

## Diagnostic logs
[log.txt](https://github.com/microsoft/vstest/files/6486545/log.txt)
[log.host.21-05-15_12-06-03_22758_1.txt](https://github.com/microsoft/vstest/files/6486546/log.host.21-05-15_12-06-03_22758_1.txt)
[log.host.21-05-15_12-06-00_14123_1.txt](https://github.com/microsoft/vstest/files/6486548/log.host.21-05-15_12-06-00_14123_1.txt)

## Environment
OS: Windows 10 Enterprise Version 1909 [18363.1500]
Version: Microsoft (R) Test Execution Command Line Tool Version 15.9.1
Target framework is Net472, though I have also observed it when targeting Net461
32 GB Ram

**Comment by RobSwDev** [comment]
I get the same results when using vstest.console from VS2019
Microsoft (R) Test Execution Command Line Tool Version 16.9.1
I also tried updating MSTest.TestFramework and MSTest.TestAdapter to 2.2.3 (were previously at 2.1.0) and this didn't help.

**Comment by Haplois** [comment]
@RobSwDev, without access to the codebase or a repro - I could only recommend you to use our [profiling tools][1] to pinpoint the moments where the memory leaks. 

Run the tests with diagnostics logs enabled, and target `testhost.net472.exe` with it. This might help us to figure out which test is actually causing this. (You can also use [`procexp` from sysinternals toolkit][2].)


[1]: https://docs.microsoft.com/en-us/visualstudio/profiling/memory-usage?view=vs-2019
[2]: https://docs.microsoft.com/en-us/sysinternals/downloads/process-explorer

**Comment by RobSwDev** [comment]
I know which individual tests call it, but because they pull our entire UI layer in, it's hard to know what specifically causes the memory allocation. 

Sadly, I can't seem to reproduce with a simple repo I can share (although it still happens every time with our commercial repo).
So I guess there's nothing you can do about it.
