### ISSUE TITLE
vstest duration, start time, end time inconsistencies in .trx file

### ISSUE THREAD

**Issue by kamahesh** [microsoft/vstest#2916]
## Description
> **IMPORTANT**: if the defect is reproduced only in a workflow from within the Visual Studio IDE then do not report the issue here - instead, please report it using Visual Studio's "Send Feedback" option that can be accessed from the Help menu OR using this link https://developercommunity.visualstudio.com.
>

The duration attribute in the UnitTestResult in the TRX output file is not equal to the difference between the start and end times

> For a defect reproducable from the vstest command line, describe the issue you've observed.

## Steps to reproduce
> What steps can reproduce the defect?
> Please share the setup, commandline for vstest.console, sample project, target
> framework etc.
1. Run the Unit Tests
2.  Open the .trx file
3.  The duration eg is  2 min 42 sec but start and end time are the same i.e startTime="2021-04-28T22:03:43.3966075+00:00" endTime="2021-04-28T22:03:43.3966075+00:00"
## Expected behavior
> Share the expected output
 The start and end time should reflect the actual duration
## Actual behavior
> What is the behavior observed?

## Diagnostic logs
> Please share test platform diagnostics logs. Instructions to collect logs are [here](https://github.com/Microsoft/vstest-docs/blob/main/docs/diagnose.md#test-platform-diagnostics).  
> The logs may contain test assembly paths, kindly review and mask those before sharing.

## Environment
> Please share additional details about the test environment.
> Operating system, Build version of vstest.console
vstest.console.exe version: Microsoft (R) Test Execution Command Line Tool Version 16.9.1

**Comment by nohwnd** [comment]
I can't reproduce this. Could you share some more details about your run? I am using 16.9.1 and the times are set correctly. 

`endTime` is only present on individual tests `<UnitTestResult>`. The whole run has `<Times>` which has `start` and `finish` attribute. Are you reporting the whole duration of the test run being incorrect or just a single test?

Can you share the trx? Can you share the diag logs? Was there any failure in the run?

**Comment by kamahesh** [comment]
The duration attribute in the UnitTestResult in the TRX output file is not equal to the difference between the start and end times. Here's an example from my .trx file. 


<UnitTestResult executionId="<ID> " testId="<ID>" testName="<TEST Name>" computerName="<machine details>" duration="00:02:42.1030000" startTime="2021-04-28T22:03:43.3966075+00:00" endTime="2021-04-28T22:03:43.3966075+00:00" testType="<ID>" outcome="Passed" testListId="<ID>" relativeResultsDirectory="<ID> " />

I cannot share/upload the exact .trx file but this UnitTestResult  is from the same file.

**Comment by kamahesh** [comment]
<UnitTestResult executionId="<ID>" testId="<ID>" testName="<Name>" computerName="<ID>" duration="00:02:42.1030000" startTime="2021-04-28T22:03:43.3966075+00:00" endTime="2021-04-28T22:03:43.3966075+00:00" testType="<ID>" outcome="Passed" testListId="8c84fa94-04c1-424b-9868-57a2d4851a1d" relativeResultsDirectory="<ID>" />

**Comment by kamahesh** [comment]
UnitTestResult executionId="<ID>" testId="<ID>" testName="<Name>" computerName="<ID>" duration="00:02:42.1030000" startTime="2021-04-28T22:03:43.3966075+00:00" endTime="2021-04-28T22:03:43.3966075+00:00" testType="<ID>" outcome="Passed" testListId="8c84fa94-04c1-424b-9868-57a2d4851a1d" relativeResultsDirectory="<ID>"

**Comment by kamahesh** [comment]
I cannot share/upload the exact .trx file but this UnitTestResult is from the same file.

**Comment by Haplois** [comment]
@kamahesh, you can zip the trx file and share it, if you don't want to share it publicly, you can reach us over twitter and we'll provide you an email address to send it us privately.

**Comment by kamahesh** [comment]
I am not comfortable sharing the .trx file.

**Comment by nohwnd** [comment]
I am trying this on 16.9.6 and newer and don't see that problem. There is some code that might change this for parallel run, but I tried running in parallel and still was not able to repro. Please try it on a newer version. Or provide a full repro project.
