### ISSUE TITLE
Future of Microsoft.QualityTools.Testing.Fakes

### ISSUE THREAD

**Issue by samsmithnz** [microsoft/vstest#2922]
## Description
when will Microsoft.QualityTools.Testing.Fakes be out of beta? Is there a roadmap for it to be out of beta? Customer prefers to use GA packages and would like some guidance.

https://www.nuget.org/packages/Microsoft.QualityTools.Testing.Fakes

**Comment by nohwnd** [comment]
@vritant24 you are the best person to answer this that I know of.

**Comment by vritant24** [comment]
Thanks for bringing this up @samsmithnz the packages are GA ready. I'll create a ticket to release a non-beta named package out soon and post an update here when it's done

**Comment by Haplois** [comment]
`Microsoft.QualityTools.Testing.Fakes` version [16.11.230815][1] is pushed, I'll be updating the references.

[1]: https://www.nuget.org/packages/Microsoft.QualityTools.Testing.Fakes/16.11.230815
