### ISSUE TITLE
Add support to DiaSession for Fields

### ISSUE THREAD

**Issue by mikeblakeuk** [microsoft/vstest#2923]
## Steps to reproduce
Using MSpec, we want to remove Cecil but can't use DiaSession as it doesn't support **Fields**, only Methods
.net 452 + netcore2.1

## Expected behavior
Remove Mono.Cecil

## Actual behavior
DiaSession is closed and support for fields doesn't exist

## Diagnostic logs
https://github.com/machine/machine.specifications/issues/436
https://github.com/machine/machine.specifications.runner.visualstudio/blob/master/src/Machine.Specifications.Runner.VisualStudio/Discovery/BuiltIn/SourceCodeLocationFinder.cs#L18

## Environment
Windows 10, 16.10 of **Microsoft.TestPlatform.ObjectModel**

![image](https://user-images.githubusercontent.com/1986660/119842137-54496980-befe-11eb-97ec-ec25caee5064.png)

**Comment by mikeblakeuk** [comment]
@mayankbansal018 thoughts?

**Comment by jakubch1** [comment]
Opened ticket here: https://developercommunity.visualstudio.com/t/Add-support-to-DiaSession-for-Fields/1445302
