### ISSUE TITLE
Type load exception after upgrading from Microsoft.NET.Test.Sdk 16.8.3 to 16.10.0

### ISSUE THREAD

**Issue by BEagle1984** [microsoft/vstest#2933]
## Description

After upgrading the reference to Microsoft.NET.Test.Sdk from version 16.8.3 to 16.10.0 the following exception is thrown when running the tests via `dotnet test`.

```
An exception occurred while invoking executor 'executor://mstestadapter/v2': Could not load file or assembly 'Microsoft.VisualStudio.TestPlatform.TestFramework, Version=14.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'. The system cannot find the file specified.
Stack trace:
   at Microsoft.VisualStudio.TestPlatform.MSTest.TestAdapter.MSTestExecutor.RunTests(IEnumerable`1 sources, IRunContext runContext, IFrameworkHandle frameworkHandle)
   at Microsoft.VisualStudio.TestPlatform.CrossPlatEngine.Execution.RunTestsWithSources.InvokeExecutor(LazyExtension`2 executor, Tuple`2 executorUriExtensionTuple, RunContext runContext, IFrameworkHandle frameworkHandle)
   at Microsoft.VisualStudio.TestPlatform.CrossPlatEngine.Execution.BaseRunTests.RunTestInternalWithExecutors(IEnumerable`1 executorUriExtensionMap, Int64 totalTests)
```

The tests are still being run but the command exits with an error code and that's an issue for the CI pipeline.

## Steps to reproduce

I'm not sure. In my case it was enough to upgrade Microsoft.NET.Test.Sdk from 16.8.3 to 16.10.0 and run the tests via CLI (`dotnet test`).

## Expected behavior

The tests are executed and the process exits with code 0.

## Actual behavior

The tests are being executed and passing but the test exits with an error code.

## Diagnostic logs

[testlog-diag.host.21-06-02_18-12-17_21961_4.txt](https://github.com/microsoft/vstest/files/6586029/testlog-diag.host.21-06-02_18-12-17_21961_4.txt)
[testlog-diag.host.21-06-02_18-12-18_61167_5.txt](https://github.com/microsoft/vstest/files/6586030/testlog-diag.host.21-06-02_18-12-18_61167_5.txt)
[testlog-diag.host.21-06-02_18-12-18_67831_6.txt](https://github.com/microsoft/vstest/files/6586031/testlog-diag.host.21-06-02_18-12-18_67831_6.txt)
[testlog-diag.host.21-06-02_18-12-18_68669_4.txt](https://github.com/microsoft/vstest/files/6586032/testlog-diag.host.21-06-02_18-12-18_68669_4.txt)
[testlog-diag.host.21-06-02_18-12-18_70356_4.txt](https://github.com/microsoft/vstest/files/6586033/testlog-diag.host.21-06-02_18-12-18_70356_4.txt)
[testlog-diag.host.21-06-02_18-12-19_75717_4.txt](https://github.com/microsoft/vstest/files/6586034/testlog-diag.host.21-06-02_18-12-19_75717_4.txt)
[testlog-diag.host.21-06-02_18-12-19_78051_6.txt](https://github.com/microsoft/vstest/files/6586035/testlog-diag.host.21-06-02_18-12-19_78051_6.txt)
[testlog-diag.host.21-06-02_18-12-19_82048_4.txt](https://github.com/microsoft/vstest/files/6586036/testlog-diag.host.21-06-02_18-12-19_82048_4.txt)
[testlog-diag.host.21-06-02_18-12-19_95102_4.txt](https://github.com/microsoft/vstest/files/6586037/testlog-diag.host.21-06-02_18-12-19_95102_4.txt)
[testlog-diag.host.21-06-02_18-12-19_95360_4.txt](https://github.com/microsoft/vstest/files/6586038/testlog-diag.host.21-06-02_18-12-19_95360_4.txt)
[testlog-diag.host.21-06-02_18-12-19_98712_4.txt](https://github.com/microsoft/vstest/files/6586039/testlog-diag.host.21-06-02_18-12-19_98712_4.txt)
[testlog-diag.host.21-06-02_18-12-20_03222_6.txt](https://github.com/microsoft/vstest/files/6586040/testlog-diag.host.21-06-02_18-12-20_03222_6.txt)
[testlog-diag.host.21-06-02_18-12-20_03230_4.txt](https://github.com/microsoft/vstest/files/6586041/testlog-diag.host.21-06-02_18-12-20_03230_4.txt)
[testlog-diag.host.21-06-02_18-12-21_38624_4.txt](https://github.com/microsoft/vstest/files/6586042/testlog-diag.host.21-06-02_18-12-21_38624_4.txt)
[testlog-diag.txt](https://github.com/microsoft/vstest/files/6586043/testlog-diag.txt)

## Environment

Both on my local machine (Windows 10, .net sdk 5.0.103) and on azure devops (ubuntu-20.04).

**Comment by Haplois** [comment]
Projects are referencing incomplete MSTest. When referencing it both [MSTest.TestFramework][1] and [MSTest.TestAdapter][2] should be referenced. Type load exception is thrown because of a missing reference to our [MSTest.TestFramework][1] package. Since you're using xunit, current references are unnecessary. See the fix https://github.com/BEagle1984/silverback/pull/131.

[1]: https://www.nuget.org/packages/MSTest.TestFramework/2.2.5-preview-20210605-01
[2]: https://www.nuget.org/packages/MSTest.TestAdapter/2.2.5-preview-20210605-01

**Comment by Haplois** [comment]
Nope, sorry. Missclick probably...
