### ISSUE TITLE
Duration still incorrect

### ISSUE THREAD

**Issue by NinoFloris** [microsoft/vstest#2936]
I'm still seeing, in 16.10, what was supposed to be fixed by
https://github.com/microsoft/vstest/pull/2739

**Comment by nohwnd** [comment]
Thanks, I will look into this.

**Comment by nohwnd** [comment]
@NinoFloris could you share more details please? 

I am trying it here with normal and minimal output, and I have 2 test assemblies, each with 2 tests that take 4 and 5 seconds to run. The assemblies run in parallel and the tests as well so the run should report duration of roughly 5s, which it does. I also tried few other variations and it seems to behave correctly. 

![image](https://user-images.githubusercontent.com/5735905/121306061-b17deb80-c8fe-11eb-8b43-b791358c51b6.png)
[TestProject8.zip](https://github.com/microsoft/vstest/files/6621596/TestProject8.zip)

```
vstest.console --parallel --logger:"console;verbosity=minimal" <dlls>
```

**Comment by NinoFloris** [comment]
Sorry must have missed the notification, is it a cli runner bug fix or a test sdk fix? I tried upgrading the Ms test SDK but I didn't yet run it against dotnet 6 preview cli tools
