### ISSUE TITLE
Feature Request: dotnet test --failing-only

### ISSUE THREAD

**Issue by TheRealPiotrP** [Microsoft/vstest#294]
@blackdwarf maybe you can help flesh out the design

We have some rather large test projects which take 3-5 mins to run. In these projects we'll sometimes make a change that breaks a few tests, creating a terrible `F5 loop` because we need to re-run the whole project to validate fixes. It would be wonderful if the test console could just re-run tests that previeously failed. One easy implementation would be for trx logs to get produced and then consumed on subsequent runs.

`--failing-only` is likely not the right option string, but gets the point across.

Thoughts?

/cc @livarcocc

**Comment by pvlakshm** [comment]
In general the console runner neither remembers nor refers-to state from a previous run. While I understand the need to be able to run only failing tests, that is a responsibility that needs to be borne by a tool/script outside of the vstest console runner.

**Comment by lauxjpn** [comment]
I use the following PowerShell command to run only the previously failed tests again, based on the newest `trx` file in `.\TestResults\`:

> dotnet vstest '.\bin\Debug\netcoreapp3.0\MyTests.dll' /Logger:trx /Tests:"$((Select-Xml -Path (gci '.\TestResults\' | sort LastWriteTime | select -last 1).FullName -Namespace @{"ns"="ht<span></span>tp://microsoft.com/schemas/VisualStudio/TeamTest/2010" -XPath "//ns:UnitTestResult[@<span></span>outcome='Failed']/@<span></span>testName"}).Node.Value | % {$_ -replace '^My\\.Long\\.And\\.Tedious\\.Namespace\\.', ''} | % {$_ -replace '^(.\*?)\\(.\*$','$1'} | Join-String -Separator ','))"

Beware, that there is a character limit on the maximum command line length, that can easily be hit when many tests have previously failed.
Us the `% {$_ -replace '^My\.Long\.And\.Tedious\.Namespace\.', ''}` part, to get rid of long and unimportant namespace prefixes if you can.

**Comment by ManikandanMani** [comment]
Is this feature impleted in dotnet test commad?

**Comment by nohwnd** [comment]
It is not.

**Comment by joaoopereira** [comment]
I have built a tool that can help with this. It calls dotnet test, after the run analyses the trx and automatic rerun all tests with the outcome “Failed”.

It's still on early days, but take a look :)

https://github.com/joaoopereira/dotnet-test-rerun

**Comment by jkone27** [comment]
can this be reopened?
`grep Failed!` does something but not awesome, e.g all error logs in files and traces are not displayed correctly
