### ISSUE TITLE
Test Adapter for non-dotnet projects

### ISSUE THREAD

**Issue by tdctaz** [microsoft/vstest#2945]
## Description
Is it possible to write a vstest adapter in .net 5 that execute non-dotnet related tests?

I have been trying to write an adapter that runs tests for a native executable. The adapter is written in .net framework 4.7.2 and starts the test process and opens a socket to the process for communication and translate the messages back and forth from the domain specific test to `TestCase`s and `TestResult`s.

Executing vstest console with .net core 3.1 or .net 5 both gives an error, while the same project targeting .net framework 4.7.2 does not.

For example:
`vstest.console.exe /TestAdapterPath:path/to/custom/adapter /framework:".NETCoreApp,Version=v3.1" path/to/domain/specific/test/executable.exe`

```
Unable to find different/path/to/executable.deps.json. Make sure test project has a nuget reference of package "Microsoft.NET.Test.Sdk".
```

Is there a way to specify a path to the `Microsoft.NET.Test.Sdk` and ignore the `deps.json` I just want vstest to execute my adapter and not care about the container it is executing.

**Comment by nohwnd** [comment]
> Executing vstest console with .net core 3.1 or .net 5 both gives an now, while the same project targeting .net framework 4.7.2 does not.

It gives what? :) Is there a typo?

TestHost for .NET Core is trying to run using the same setup as the tested executable / dll would. This means it needs to pick up deps.json and runtimeconfig.json, there is no option to ignore deps.json or runtimeconfig.json, that is simply how this testhost provider works. You can implement your own testhost provider from scratch by using ITestRuntimeProvider2 or ITestRuntimeProvider but that is way more involved than adding an adapter.

**Comment by tdctaz** [comment]
Yes it was a typo :) - it gives an error.

Thank you - i'll look into the ITestRuntimeProvider and see if that is a route we want to go.
