### ISSUE TITLE
Document the full arguments and syntax for `--blame-crash-dump-type`

### ISSUE THREAD

**Issue by KirillOsenkov** [microsoft/vstest#2957]
Neither the command line help for `dotnet test` nor the docs mention what the arguments for `--blame-crash-dump-type` should be.

![image](https://user-images.githubusercontent.com/679326/123524429-064f8f00-d67f-11eb-8dbe-9814fe5d3c04.png)

It also doesn't mention the path where the dump file will be saved to, nor does it mention whether the user has control over the output path for the dump.

If I'm investigating a crash of `dotnet test` in AzDO CI it's highly non-obvious how to configure it in such a way that the dump is automatically uploaded as an artifact attached to a failing build.

**Comment by KirillOsenkov** [comment]
The docs are also not clear whether having procdump.exe on the PATH is still required for .NET 5 (it appears so).

I wish this was taken care of automatically. Now all users need to figure this out for themselves. Any recipes on how people usually do this?

**Comment by KirillOsenkov** [comment]
I found a sample here:
https://github.com/microsoft/vstest-docs/blob/master/RFCs/0028-BlameCollector-Hang-Detection.md

```
# The procdump tool and env var is required for dotnet test to collect hang/crash dumps of tests.
- powershell: |
    choco install procdump
    Write-Host "##vso[task.setvariable variable=PROCDUMP_PATH;]$env:ProgramData\chocolatey\bin\"
  displayName: Install procdump
  condition: and(succeeded(), eq(variables['Agent.OS'], 'Windows_NT'))
```

**Comment by KirillOsenkov** [comment]
The sample was later replaced with:
https://github.com/AArnott/Library.Template/commit/e9dcc410b3a0cc01d48927253a66e9e3e8eb0a21#diff-ef2c77be1d247a13cd80a218a1be4473cbb7f412d031e1df0f907b3569daabff

**Comment by KirillOsenkov** [comment]
It's unfortunate that everyone has to follow along on this quest to just get the basic functionality working. Wish procdump.exe was just shipped in the AzDO VM image and didn't need to be installed.

**Comment by nohwnd** [comment]
@KirillOsenkov documentation is here: https://docs.microsoft.com/en-us/dotnet/core/tools/dotnet-test#options

See `--blame-crash` there. I agree with you, it is still difficult to setup because we were not able to ship procdump with test platform, and there are multiple combinations of how to dump a given process based on the runtime, and operating system. 

> was just shipped in the AzDO VM image and didn't need to be installed.

That's a good idea, do you know who can help us with that? Or maybe it is already in the image, we are just not looking in the right path. Investigating that now.


> It also doesn't mention the path where the dump file will be saved to, nor does it mention whether the user has control over the output path for the dump.
> If I'm investigating a crash of dotnet test in AzDO CI it's highly non-obvious how to configure it in such a way that the dump is automatically uploaded as an artifact attached to a failing build. 

Your dumps should be automatically uploaded as attachments, as long as you don't force TP to not do that by using `VSTEST_DUMP_PATH` which specifies a custom path, and won't handle the files as attachments.

**Comment by KirillOsenkov** [comment]
@nohwnd yes, the docs are there, but:

> Neither the command line help for dotnet test nor the docs mention what the arguments for --blame-crash-dump-type should be.

I don't know who'd be a good person to track down shipping procdump.exe in the image by default, but we should absolutely do it. You can ask on the internal 1ES talk mailing list. I won't be surprised if it's already being included.

**Comment by nohwnd** [comment]
I listed all files on windows-2019 hosted agent and procdump is nowhere to be found there. We deploy it with our vstest task automatically (see https://github.com/microsoft/vstest/issues/2972#issuecomment-871301167 for how to enable crash dumps through that). But it would not hurt if it was in the image directly available on PATH.

**Comment by KirillOsenkov** [comment]
Do you agree that the dump type argument strings are not mentioned anywhere?

**Comment by JoshLove-msft** [comment]
What is the default value for --blame-crash-dump-type if it is omitted and you only add --blame-crash?

**Comment by nohwnd** [comment]
The default is full for both. 

Updated the values in help, here and here: 

https://github.com/dotnet/docs/pull/30482
https://github.com/dotnet/sdk/pull/26963/files

**Comment by nohwnd** [comment]
The actual help page https://docs.microsoft.com/en-us/dotnet/core/tools/dotnet-test#options , also available by `dotnet help test`.
