### ISSUE TITLE
Video Data Collector doesn't capture fullscreen if display resolution is scaled

### ISSUE THREAD

**Issue by Exoow** [microsoft/vstest#2970]
## Description
When display resolution scaling isn't at 100% the video data collector doesn't record the entire screen, instead it makes a backward calculation that is incorrect.

## Steps to reproduce
1. Set Windows Display Resolution to a 1920x1080 resolution and 125% scaling.
2. Create a unit test
3. Create a RunSettings file with Video Adapter data collector configured.
4. Run test
5. Watch video attachment

## Expected behavior
Full screen recorded, recording has 1920x1080 resolution

## Actual behavior
Part of screen recorded with video having 1536x1080 (this is scaling back from 125% to 100% starting at 1920x1080).

**Comment by Evangelink** [comment]
@cvpoienaru Could you look at this issue?

**Comment by cvpoienaru** [comment]
This issue was fixed in VS 17.7, closing it.
