### ISSUE TITLE
Unable to find C:\Source\SauceLabs\simple_sauce\dotnet\SimpleSauce.Test\bin\Debug\netstandard2.1\testhost.dll. Please publish your test project and retry.

### ISSUE THREAD

**Issue by nadvolod** [microsoft/vstest#3032]
## Description
Here's the error.

```
Unable to find C:\Source\SauceLabs\simple_sauce\dotnet\SimpleSauce.Test\bin\Debug\netstandard2.1\testhost.dll. Please publish your test project and retry.
```

This happens when running the `dotnet test` command

Here's the full console message

```
Passed!  - Failed:     0, Passed:    54, Skipped:     0, Total:    54, Duration: 16 s - Sauce.Bindings.Test.dll (net5.0)
Test run for C:\Source\SauceLabs\simple_sauce\dotnet\SimpleSauce.Test\bin\Debug\netstandard2.1\Sauce.Bindings.Test.dll (.NETStandard,Version=v2.1)
Microsoft (R) Test Execution Command Line Tool Version 16.11.0
Copyright (c) Microsoft Corporation.  All rights reserved.

Starting test execution, please wait...
A total of 1 test files matched the specified pattern.
Unable to find C:\Source\SauceLabs\simple_sauce\dotnet\SimpleSauce.Test\bin\Debug\netstandard2.1\testhost.dll. Please publish your test project and retry.

Test Run Aborted.
Test run for C:\Source\SauceLabs\simple_sauce\dotnet\SimpleSauce.Test\bin\Debug\netstandard2.0\Sauce.Bindings.Test.dll (.NETStandard,Version=v2.0)
Microsoft (R) Test Execution Command Line Tool Version 16.11.0
Copyright (c) Microsoft Corporation.  All rights reserved.

Starting test execution, please wait...
A total of 1 test files matched the specified pattern.
Unable to find C:\Source\SauceLabs\simple_sauce\dotnet\SimpleSauce.Test\bin\Debug\netstandard2.0\testhost.dll. Please publish your test project and retry.

Test Run Aborted.
```

## Steps to reproduce
1. Pull down [this repo](https://github.com/saucelabs/sauce_bindings/tree/net5). Make sure your testing the code in the `net5` branch.
2. cd simple_sauce\SimpleSauce.Test
3. dotnet test

## Expected behavior
All of the tests to run successfully on .NET, .net standard 2.0 and 2.1

## Actual behavior
Only .NET5 tests actually run

## Diagnostic logs
[log.txt](https://github.com/microsoft/vstest/files/7101015/log.txt)

## Environment
Mac and Windows
https://github.com/saucelabs/sauce_bindings/actions/runs/1195266449

**Comment by nohwnd** [comment]
.NET Standard dlls are not supported as the test projects, you should make them netcoreapp2.1 and netcoreapp2.0, or any newer compatible runnable target framework, like net5.0. Is there a particular reason you need those **test** projects as netstandard?

**Comment by nadvolod** [comment]
@nohwnd no particular reason. I think I don't fully comprehend how to target .NET Core users and up, which is ultimately my goal for my Nuget package. So if that's my goal, you're recommending `net5.0;netcoreapp2.1;netcoreapp2.0` as my targets instead?

**Comment by nadvolod** [comment]
> @nohwnd no particular reason. I think I don't fully comprehend how to target .NET Core users and up, which is ultimately my goal for my Nuget package. I want to make sure that everyone using .NET Core and up can use my Nuget. So if that's my goal, you're recommending `net5.0;netcoreapp2.1;netcoreapp2.0` as my targets instead?

I updated my targets here and notice that the only one not working now is `notecoreapp2.0`. I also notice a warning that says it won't receive any more security updates. Hence, are there any benefits/drawbacks to supporting `notecoreapp2.0`?

**Comment by nohwnd** [comment]
Your test project needs to target some runnable TFM, e.g. net5.0. Unless you have particular needs regarding compatibility for your test project, target net5.0. 

Your product project (the one that is being tested), can remain as it was and target net5.0;netstandard2.0;netstandard2.1.

**Comment by Haplois** [comment]
Closing the issue, @nadvolod if your issue is not fixed yet please feel free to comment here.
