### ISSUE TITLE
Should testhost.exe be used for executing .NET (any cpu) tests

### ISSUE THREAD

**Issue by sbaid** [Microsoft/vstest#304]
## Description
Should testhost.exe (x64 bit) be used (by default) for executing .NET (any cpu) tests? That can potentially give largeaddressspace for running tests

## Steps to reproduce
1. Build a .net desktop test project with (Any Cpu)
2. Run the test
3. Launches tests in testhost.x86.exe

**Comment by pvlakshm** [comment]
We will live with this; there are no semantic issues with using the x86 exe for AnyCpu-targeting tests.
