### ISSUE TITLE
DataCollectors TestResults logs hitting MAXPATH errors

### ISSUE THREAD

**Issue by NGloreous** [microsoft/vstest#3102]
## Description

Seeing the below error related to a log file attached from a custom data collector. The issue occurs when vstest tries to copy the file [here](https://github.com/microsoft/vstest/blob/ad32654bc155a059fda263f0ec99b445058d84ea/src/Microsoft.TestPlatform.Common/DataCollection/DataCollectionAttachmentManager.cs#L302).

The root cause is that the resulting path to copy to is longer than MAXPATH.

For now we will work around this by reducing the length of the file name. We'd like to keep including the test name in the file name as it's useful later on when debugging issues but we can't control how long people name their tests. 

It would be great if vstest could work around the max path issue or at least have an option to shorten the directories it creates (currently files get copied to `<ResultsDirector>/TestResults/<GUID>/<GUID>/<filename>`).

## Steps to reproduce
Create a data collector which creates a file where the resulting path to copy the file will be longer than MAXPATH.

## Expected behavior
No failures, and logs properly copied.

## Actual behavior
vstest fails to copy the logs with the below error and returns a non-zero exit code. 

```
Data collector 'FiddlerClientDataCollector' message: System.IO.DirectoryNotFoundException: Could not find a part of the path 'D:\data\CHT\a7a84089\JWD_7b08af31\TestResults\181ee68a-56fb-4daf-8e91-df7e289796cb\8d76b1a3-21aa-df30-9ab3-a0c62348ecc3\Process_32200_Test_EnsureCrossTenantUser_NativeClientSignInWithoutOidAndPuidInToken_Access__Positive_Test_Async_8d76b1a3-21aa-df30-9ab3-a0c62348ecc3.SAZ'.
   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.File.InternalCopy(String sourceFileName, String destFileName, Boolean overwrite, Boolean checkHost)
   at Microsoft.VisualStudio.TestPlatform.Common.DataCollector.DataCollectionAttachmentManager.<>c__DisplayClass21_0.<AddNewFileTransfer>b__0().
```

**Comment by nohwnd** [comment]
I would like to eventually do this by providing a common templating service that will allow us and you to specify the path in similar way as you outlined, but in all extensions not just in one specific one as it is done now. Saving this issue to a design doc. But we won't fix right now.
