### ISSUE TITLE
Unable to run test. Test run getting aborted

### ISSUE THREAD

**Issue by oeademola** [microsoft/vstest#3127]
Issue Type: <b>Bug</b>

On a breakdown I have created an empty mstest project with default template then run dotnet test in cmd. To troubleshoot this error I clonned a test project I created I wrote years go and tried to run it unfortunately its same error. I have proceeded to do this on a VM and a colleague PC this same test ran without issues. Even creating a clean test project based off the default template did not run on my machine. Since it appears to mostly likely be a PC issue I decided to reset my PC removing everything and cleaning the drive, however this still did not resolve this as it threw the same error of test getting aborted. I have also downloaded the latest Dotnet SDK 3.1 LTS. Could my windows 10 OS be the issue? Here is my OS build Windows 10 Home-21H1-19043.1288. 

Error Message: vstest.console process failed to connect to testhost process after 90 seconds. This may occur due to machine slowness, please set environment variable VSTEST_CONNECTION_TIMEOUT to increase timeout.

Test Run Aborted.

To get more info about the error I used the --diag:log.txt  to collect the trace of the issue. Below is the trace info: 
//Trace/diagnostics
TpTrace Information: 0 : 1152, 1, 2021/10/25, 08:41:37.219, 113951680590, testhost.dll, DefaultEngineInvoker.Invoke: Testhost process started with args :[--port, 61223],[--endpoint, 127.0.0.1:061223],[--role, client],[--parentprocessid, 3804],[--diag, C:\Users\green\Desktop\Projects\.NetCoreMoviesAPI\MoviesAPI.Tests\log.host.21-10-25_08-41-36_92830_6.txt],[--tracelevel, 4],[--telemetryoptedin, false]
TpTrace Information: 0 : 1152, 1, 2021/10/25, 08:41:37.231, 113951775101, testhost.dll, Setting up debug trace listener.
TpTrace Verbose: 0 : 1152, 1, 2021/10/25, 08:41:37.231, 113951780138, testhost.dll, TestPlatformTraceListener.Setup: Replacing listener 0 with TestHostTraceListener.
TpTrace Verbose: 0 : 1152, 1, 2021/10/25, 08:41:37.232, 113951784617, testhost.dll, TestPlatformTraceListener.Setup: Added test platform trace listener.
TpTrace Information: 0 : 1152, 1, 2021/10/25, 08:41:37.232, 113951791247, testhost.dll, DefaultEngineInvoker.SetParentProcessExitCallback: Monitoring parent process with id: '3804'
TpTrace Information: 0 : 1152, 1, 2021/10/25, 08:41:37.244, 113951911807, testhost.dll, DefaultEngineInvoker.GetConnectionInfo: Initialize communication on endpoint address: '127.0.0.1:061223'
TpTrace Information: 0 : 1152, 1, 2021/10/25, 08:41:37.266, 113952132095, testhost.dll, SocketClient.Start: connecting to server endpoint: 127.0.0.1:061223
TpTrace Information: 0 : 1152, 1, 2021/10/25, 08:41:37.275, 113952218076, testhost.dll, DefaultEngineInvoker.Invoke: Start Request Processing.

TpTrace Information: 0 : 3804, 1, 2021/10/25, 08:41:36.704, 113946517947, vstest.console.dll, Using .Net Framework version:.NETCoreApp,Version=v3.1
TpTrace Information: 0 : 3804, 1, 2021/10/25, 08:41:36.767, 113947139483, vstest.console.dll, FilePatternParser: The given file C:\Users\green\Desktop\Projects\.NetCoreMoviesAPI\MoviesAPI.Tests\bin\Debug\netcoreapp3.1\MoviesAPI.Tests.dll is a full path.
TpTrace Verbose: 0 : 3804, 1, 2021/10/25, 08:41:36.775, 113947215543, vstest.console.dll, TestPluginCache.DiscoverTestExtensions: finding test extensions in assemblies ends with: RuntimeProvider.dll TPluginInfo: Microsoft.VisualStudio.TestPlatform.Common.ExtensionFramework.Utilities.TestRuntimePluginInformation TExtension: Microsoft.VisualStudio.TestPlatform.ObjectModel.Host.ITestRuntimeProvider
TpTrace Verbose: 0 : 3804, 1, 2021/10/25, 08:41:36.775, 113947221593, vstest.console.dll, TestPluginCache.GetExtensionPaths: Filtered extension paths: 
TpTrace Verbose: 0 : 3804, 1, 2021/10/25, 08:41:36.775, 113947222888, vstest.console.dll, TestPluginCache.GetExtensionPaths: Added default extension paths: C:\Program Files\dotnet\sdk\3.1.414\Extensions\Microsoft.Diagnostics.NETCore.Client.dll
C:\Program Files\dotnet\sdk\3.1.414\Extensions\Microsoft.TestPlatform.Extensions.BlameDataCollector.dll
C:\Program Files\dotnet\sdk\3.1.414\Extensions\Microsoft.TestPlatform.Extensions.EventLogCollector.dll
C:\Program Files\dotnet\sdk\3.1.414\Extensions\Microsoft.TestPlatform.TestHostRuntimeProvider.dll
C:\Program Files\dotnet\sdk\3.1.414\Extensions\Microsoft.VisualStudio.TestPlatform.Extensions.Html.TestLogger.dll
C:\Program Files\dotnet\sdk\3.1.414\Extensions\Microsoft.VisualStudio.TestPlatform.Extensions.Trx.TestLogger.dll
TpTrace Verbose: 0 : 3804, 1, 2021/10/25, 08:41:36.775, 113947223721, vstest.console.dll, TestPluginCache.GetExtensionPaths: Added unfilterableExtensionPaths: 
TpTrace Information: 0 : 3804, 1, 2021/10/25, 08:41:36.776, 113947231412, vstest.console.dll, AssemblyResolver.ctor: Creating AssemblyResolver with searchDirectories C:\Program Files\dotnet\sdk\3.1.414\Extensions,C:\Program Files\dotnet\sdk\3.1.414
TpTrace Verbose: 0 : 3804, 1, 2021/10/25, 08:41:36.777, 113947243068, vstest.console.dll, TestPluginCache.DiscoverTestExtensions: Discovering the extensions using extension path.
TpTrace Verbose: 0 : 3804, 1, 2021/10/25, 08:41:36.778, 113947245818, vstest.console.dll, TestPluginCache.GetExtensionPaths: Filtered extension paths: 
TpTrace Verbose: 0 : 3804, 1, 2021/10/25, 08:41:36.778, 113947246317, vstest.console.dll, TestPluginCache.GetExtensionPaths: Added default extension paths: C:\Program Files\dotnet\sdk\3.1.414\Extensions\Microsoft.Diagnostics.NETCore.Client.dll
C:\Program Files\dotnet\sdk\3.1.414\Extensions\Microsoft.TestPlatform.Extensions.BlameDataCollector.dll
C:\Program Files\dotnet\sdk\3.1.414\Extensions\Microsoft.TestPlatform.Extensions.EventLogCollector.dll
C:\Program Files\dotnet\sdk\3.1.414\Extensions\Microsoft.TestPlatform.TestHostRuntimeProvider.dll
C:\Program Files\dotnet\sdk\3.1.414\Extensions\Microsoft.VisualStudio.TestPlatform.Extensions.Html.TestLogger.dll
C:\Program Files\dotnet\sdk\3.1.414\Extensions\Microsoft.VisualStudio.TestPlatform.Extensions.Trx.TestLogger.dll
TpTrace Verbose: 0 : 3804, 1, 2021/10/25, 08:41:36.778, 113947246770, vstest.console.dll, TestPluginCache.GetExtensionPaths: Added unfilterableExtensionPaths: 
TpTrace Verbose: 0 : 3804, 1, 2021/10/25, 08:41:36.778, 113947247614, vstest.console.dll, TestPluginCache.DiscoverTestExtensions: Discovering the extensions using allExtensionPaths: C:\Program Files\dotnet\sdk\3.1.414\Extensions\Microsoft.Diagnostics.NETCore.Client.dll
C:\Program Files\dotnet\sdk\3.1.414\Extensions\Microsoft.TestPlatform.Extensions.BlameDataCollector.dll
C:\Program Files\dotnet\sdk\3.1.414\Extensions\Microsoft.TestPlatform.Extensions.EventLogCollector.dll
C:\Program Files\dotnet\sdk\3.1.414\Extensions\Microsoft.TestPlatform.TestHostRuntimeProvider.dll
C:\Program Files\dotnet\sdk\3.1.414\Extensions\Microsoft.VisualStudio.TestPlatform.Extensions.Html.TestLogger.dll
C:\Program Files\dotnet\sdk\3.1.414\Extensions\Microsoft.VisualStudio.TestPlatform.Extensions.Trx.TestLogger.dll
TpTrace Information: 0 : 3804, 1, 2021/10/25, 08:41:36.778, 113947249560, vstest.console.dll, AssemblyResolver.AddSearchDirectories: Adding more searchDirectories C:\Program Files\dotnet\sdk\3.1.414\Extensions,C:\Program Files\dotnet\sdk\3.1.414
TpTrace Information: 0 : 3804, 1, 2021/10/25, 08:41:36.778, 113947250288, vstest.console.dll, AssemblyResolver.AddSearchDirectories: Adding more searchDirectories C:\Program Files\dotnet\sdk\3.1.414\Extensions,C:\Program Files\dotnet\sdk\3.1.414
TpTrace Information: 0 : 3804, 1, 2021/10/25, 08:41:36.778, 113947250829, vstest.console.dll, AssemblyResolver.AddSearchDirectories: Adding more searchDirectories C:\Program Files\dotnet\sdk\3.1.414\Extensions,C:\Program Files\dotnet\sdk\3.1.414
TpTrace Information: 0 : 3804, 1, 2021/10/25, 08:41:36.778, 113947251229, vstest.console.dll, AssemblyResolver.AddSearchDirectories: Adding more searchDirectories C:\Program Files\dotnet\sdk\3.1.414\Extensions,C:\Program Files\dotnet\sdk\3.1.414
TpTrace Information: 0 : 3804, 1, 2021/10/25, 08:41:36.778, 113947251607, vstest.console.dll, AssemblyResolver.AddSearchDirectories: Adding more searchDirectories C:\Program Files\dotnet\sdk\3.1.414\Extensions,C:\Program Files\dotnet\sdk\3.1.414
TpTrace Information: 0 : 3804, 1, 2021/10/25, 08:41:36.778, 113947252046, vstest.console.dll, AssemblyResolver.AddSearchDirectories: Adding more searchDirectories C:\Program Files\dotnet\sdk\3.1.414\Extensions,C:\Program Files\dotnet\sdk\3.1.414
TpTrace Information: 0 : 3804, 1, 2021/10/25, 08:41:36.779, 113947256725, vstest.console.dll, AssemblyResolver.OnResolve: Microsoft.Diagnostics.NETCore.Client: Resolving assembly.
TpTrace Information: 0 : 3804, 1, 2021/10/25, 08:41:36.780, 113947267479, vstest.console.dll, AssemblyResolver.OnResolve: Resolved assembly: Microsoft.Diagnostics.NETCore.Client, from path: C:\Program Files\dotnet\sdk\3.1.414\Extensions\Microsoft.Diagnostics.NETCore.Client.dll
TpTrace Information: 0 : 3804, 1, 2021/10/25, 08:41:36.780, 113947273942, vstest.console.dll, AssemblyResolver.OnResolve: Microsoft.TestPlatform.Extensions.BlameDataCollector: Resolving assembly.
TpTrace Information: 0 : 3804, 1, 2021/10/25, 08:41:36.781, 113947282383, vstest.console.dll, AssemblyResolver.OnResolve: Resolved assembly: Microsoft.TestPlatform.Extensions.BlameDataCollector, from path: C:\Program Files\dotnet\sdk\3.1.414\Extensions\Microsoft.TestPlatform.Extensions.BlameDataCollector.dll
TpTrace Information: 0 : 3804, 1, 2021/10/25, 08:41:36.782, 113947287430, vstest.console.dll, AssemblyResolver.OnResolve: Microsoft.TestPlatform.Extensions.EventLogCollector: Resolving assembly.
TpTrace Information: 0 : 3804, 1, 2021/10/25, 08:41:36.782, 113947293716, vstest.console.dll, AssemblyResolver.OnResolve: Resolved assembly: Microsoft.TestPlatform.Extensions.EventLogCollector, from path: C:\Program Files\dotnet\sdk\3.1.414\Extensions\Microsoft.TestPlatform.Extensions.EventLogCollector.dll
TpTrace Information: 0 : 3804, 1, 2021/10/25, 08:41:36.784, 113947308509, vstest.console.dll, AssemblyResolver.OnResolve: Microsoft.TestPlatform.TestHostRuntimeProvider: Resolving assembly.
TpTrace Information: 0 : 3804, 1, 2021/10/25, 08:41:36.785, 113947316442, vstest.console.dll, AssemblyResolver.OnResolve: Resolved assembly: Microsoft.TestPlatform.TestHostRuntimeProvider, from path: C:\Program Files\dotnet\sdk\3.1.414\Extensions\Microsoft.TestPlatform.TestHostRuntimeProvider.dll
TpTrace Information: 0 : 3804, 1, 2021/10/25, 08:41:36.787, 113947335182, vstest.console.dll, AssemblyResolver.OnResolve: Microsoft.VisualStudio.TestPlatform.Extensions.Html.TestLogger: Resolving assembly.
TpTrace Information: 0 : 3804, 1, 2021/10/25, 08:41:36.787, 113947343468, vstest.console.dll, AssemblyResolver.OnResolve: Resolved assembly: Microsoft.VisualStudio.TestPlatform.Extensions.Html.TestLogger, from path: C:\Program Files\dotnet\sdk\3.1.414\Extensions\Microsoft.VisualStudio.TestPlatform.Extensions.Html.TestLogger.dll
TpTrace Information: 0 : 3804, 1, 2021/10/25, 08:41:36.788, 113947346783, vstest.console.dll, AssemblyResolver.OnResolve: Microsoft.VisualStudio.TestPlatform.Extensions.Trx.TestLogger: Resolving assembly.
TpTrace Information: 0 : 3804, 1, 2021/10/25, 08:41:36.789, 113947355034, vstest.console.dll, AssemblyResolver.OnResolve: Resolved assembly: Microsoft.VisualStudio.TestPlatform.Extensions.Trx.TestLogger, from path: C:\Program Files\dotnet\sdk\3.1.414\Extensions\Microsoft.VisualStudio.TestPlatform.Extensions.Trx.TestLogger.dll
TpTrace Verbose: 0 : 3804, 1, 2021/10/25, 08:41:36.790, 113947373823, vstest.console.dll, TestPluginCache: Discovered the extensions using extension path ''.
TpTrace Verbose: 0 : 3804, 1, 2021/10/25, 08:41:36.791, 113947374863, vstest.console.dll, TestPluginCache: Discoverers are ''.
TpTrace Verbose: 0 : 3804, 1, 2021/10/25, 08:41:36.791, 113947375258, vstest.console.dll, TestPluginCache: Executors are ''.
TpTrace Verbose: 0 : 3804, 1, 2021/10/25, 08:41:36.791, 113947375581, vstest.console.dll, TestPluginCache: Executors2 are ''.
TpTrace Verbose: 0 : 3804, 1, 2021/10/25, 08:41:36.791, 113947375924, vstest.console.dll, TestPluginCache: Setting providers are ''.
TpTrace Verbose: 0 : 3804, 1, 2021/10/25, 08:41:36.791, 113947376312, vstest.console.dll, TestPluginCache: Loggers are ''.
TpTrace Information: 0 : 3804, 1, 2021/10/25, 08:41:36.796, 113947427055, vstest.console.dll, RunTestsArgumentProcessor:Execute: Test run is starting.
TpTrace Verbose: 0 : 3804, 1, 2021/10/25, 08:41:36.796, 113947428741, vstest.console.dll, RunTestsArgumentProcessor:Execute: Queuing Test run.
TpTrace Information: 0 : 3804, 1, 2021/10/25, 08:41:36.796, 113947431584, vstest.console.dll, TestRequestManager.RunTests: run tests started.
TpTrace Information: 0 : 3804, 1, 2021/10/25, 08:41:36.807, 113947541895, vstest.console.dll, AssemblyMetadataProvider.GetFrameWork: Determined framework:'.NETCoreApp,Version=v3.1' for source: 'C:\Users\green\Desktop\Projects\.NetCoreMoviesAPI\MoviesAPI.Tests\bin\Debug\netcoreapp3.1\MoviesAPI.Tests.dll'
TpTrace Information: 0 : 3804, 1, 2021/10/25, 08:41:36.808, 113947544608, vstest.console.dll, Determined framework for all sources: .NETCoreApp,Version=v3.1
TpTrace Information: 0 : 3804, 1, 2021/10/25, 08:41:36.816, 113947627418, vstest.console.dll, AssemblyMetadataProvider.GetArchitecture: Determined architecture:AnyCPU info for assembly: C:\Users\green\Desktop\Projects\.NetCoreMoviesAPI\MoviesAPI.Tests\bin\Debug\netcoreapp3.1\MoviesAPI.Tests.dll
TpTrace Information: 0 : 3804, 1, 2021/10/25, 08:41:36.817, 113947643933, vstest.console.dll, Determined platform for all sources: X64
TpTrace Information: 0 : 3804, 1, 2021/10/25, 08:41:36.820, 113947665523, vstest.console.dll, Compatible sources list : 
TpTrace Information: 0 : 3804, 1, 2021/10/25, 08:41:36.820, 113947666255, vstest.console.dll, C:\Users\green\Desktop\Projects\.NetCoreMoviesAPI\MoviesAPI.Tests\bin\Debug\netcoreapp3.1\MoviesAPI.Tests.dll
TpTrace Information: 0 : 3804, 1, 2021/10/25, 08:41:36.822, 113947688531, vstest.console.dll, InferRunSettingsHelper.IsTestSettingsEnabled: Unable to navigate to RunSettings/MSTest. Current node: RunSettings
TpTrace Information: 0 : 3804, 1, 2021/10/25, 08:41:36.823, 113947697923, vstest.console.dll, AssemblyResolver.OnResolve: Microsoft.VisualStudio.TestPlatform.Fakes: Resolving assembly.
TpTrace Information: 0 : 3804, 1, 2021/10/25, 08:41:36.823, 113947703712, vstest.console.dll, AssemblyResolver.OnResolve: Microsoft.VisualStudio.TestPlatform.Fakes: Failed to load assembly.
TpTrace Information: 0 : 3804, 1, 2021/10/25, 08:41:36.866, 113948125800, vstest.console.dll, Failed to create newly implemented Fakes Configurator. Reason:System.IO.FileNotFoundException: Could not load file or assembly 'Microsoft.VisualStudio.TestPlatform.Fakes, Version=16.0.0.0, Culture=neutral, PublicKeyToken=null'. The system cannot find the file specified.
File name: 'Microsoft.VisualStudio.TestPlatform.Fakes, Version=16.0.0.0, Culture=neutral, PublicKeyToken=null'
   at System.Reflection.RuntimeAssembly.nLoad(AssemblyName fileName, String codeBase, RuntimeAssembly assemblyContext, StackCrawlMark& stackMark, Boolean throwOnFileNotFound, AssemblyLoadContext assemblyLoadContext)
   at System.Reflection.RuntimeAssembly.InternalLoadAssemblyName(AssemblyName assemblyRef, StackCrawlMark& stackMark, AssemblyLoadContext assemblyLoadContext)
   at System.Reflection.Assembly.Load(String assemblyString)
   at Microsoft.VisualStudio.TestPlatform.Common.Utilities.FakesUtilities.TryGetFakesCrossPlatformDataCollectorConfigurator()

 
TpTrace Verbose: 0 : 3804, 1, 2021/10/25, 08:41:36.867, 113948139839, vstest.console.dll, TestPluginCache: Update extensions started. Skip filter = False
TpTrace Verbose: 0 : 3804, 1, 2021/10/25, 08:41:36.867, 113948142594, vstest.console.dll, TestPluginCache: Using directories for assembly resolution 'C:\Users\green\.nuget\packages\coverlet.collector\1.2.1\build\netstandard1.0'.
TpTrace Verbose: 0 : 3804, 1, 2021/10/25, 08:41:36.867, 113948143128, vstest.console.dll, TestPluginCache: Updated the available extensions to 'C:\Users\green\.nuget\packages\coverlet.collector\1.2.1\build\netstandard1.0\coverlet.collector.dll'.
TpTrace Information: 0 : 3804, 1, 2021/10/25, 08:41:36.891, 113948380309, vstest.console.dll, TestPluginManager.CreateTestExtension: Attempting to load test extension: Microsoft.VisualStudio.TestPlatform.CrossPlatEngine.Hosting.DefaultTestHostManager
TpTrace Information: 0 : 3804, 1, 2021/10/25, 08:41:36.891, 113948383288, vstest.console.dll, TestPluginManager.CreateTestExtension: Attempting to load test extension: Microsoft.VisualStudio.TestPlatform.CrossPlatEngine.Hosting.DotnetTestHostManager
TpTrace Verbose: 0 : 3804, 1, 2021/10/25, 08:41:36.892, 113948389324, vstest.console.dll, TestEngine: Initializing Parallel Execution as MaxCpuCount is set to: 1
TpTrace Information: 0 : 3804, 1, 2021/10/25, 08:41:36.892, 113948391660, vstest.console.dll, InferRunSettingsHelper.IsTestSettingsEnabled: Unable to navigate to RunSettings/MSTest. Current node: RunSettings
TpTrace Verbose: 0 : 3804, 1, 2021/10/25, 08:41:36.900, 113948473432, vstest.console.dll, TestRequestSender is acting as server
TpTrace Verbose: 0 : 3804, 1, 2021/10/25, 08:41:36.902, 113948492558, vstest.console.dll, TestRunRequest.ExecuteAsync: Creating test run request.
TpTrace Verbose: 0 : 3804, 1, 2021/10/25, 08:41:36.903, 113948503260, vstest.console.dll, TestRunRequest.ExecuteAsync: Starting.
TpTrace Information: 0 : 3804, 1, 2021/10/25, 08:41:36.904, 113948506761, vstest.console.dll, TestRunRequest.ExecuteAsync: Starting run with settings:TestRunCriteria:
   KeepAlive=False,FrequencyOfRunStatsChangeEvent=10,RunStatsChangeEventTimeout=00:00:01.5000000,TestCaseFilter=,TestExecutorLauncher=
   Settingsxml=<RunSettings>
  <RunConfiguration>
    <ResultsDirectory>C:\Users\green\Desktop\Projects\.NetCoreMoviesAPI\MoviesAPI.Tests\TestResults</ResultsDirectory>
    <TargetPlatform>X64</TargetPlatform>
    <TargetFrameworkVersion>.NETCoreApp,Version=v3.1</TargetFrameworkVersion>
    <TestAdaptersPaths>C:\Users\green\.nuget\packages\coverlet.collector\1.2.1\build\netstandard1.0\</TestAdaptersPaths>
    <DesignMode>False</DesignMode>
    <CollectSourceInformation>False</CollectSourceInformation>
  </RunConfiguration>
  <LoggerRunSettings>
    <Loggers>
      <Logger friendlyName="Console" uri="logger://microsoft/TestPlatform/ConsoleLogger/v1" assemblyQualifiedName="Microsoft.VisualStudio.TestPlatform.CommandLine.Internal.ConsoleLogger, vstest.console, Version=15.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a" codeBase="C:\Program Files\dotnet\sdk\3.1.414\vstest.console.dll" enabled="True" />
    </Loggers>
  </LoggerRunSettings>
</RunSettings>

TpTrace Verbose: 0 : 3804, 1, 2021/10/25, 08:41:36.904, 113948507389, vstest.console.dll, TestRunRequest.ExecuteAsync: Wait for the first run request is over.
TpTrace Verbose: 0 : 3804, 1, 2021/10/25, 08:41:36.904, 113948511782, vstest.console.dll, ParallelProxyExecutionManager: Start execution. Total sources: 1
TpTrace Information: 0 : 3804, 1, 2021/10/25, 08:41:36.905, 113948521259, vstest.console.dll, ProxyParallelExecutionManager: Triggering test run for next source: C:\Users\green\Desktop\Projects\.NetCoreMoviesAPI\MoviesAPI.Tests\bin\Debug\netcoreapp3.1\MoviesAPI.Tests.dll
TpTrace Verbose: 0 : 3804, 6, 2021/10/25, 08:41:36.905, 113948524169, vstest.console.dll, ParallelProxyExecutionManager: Execution started. Started clients: 1
TpTrace Verbose: 0 : 3804, 1, 2021/10/25, 08:41:36.906, 113948524737, vstest.console.dll, ProxyParallelExecutionManager: No sources available for execution.
TpTrace Information: 0 : 3804, 1, 2021/10/25, 08:41:36.906, 113948525746, vstest.console.dll, TestRunRequest.ExecuteAsync: Started.
TpTrace Verbose: 0 : 3804, 1, 2021/10/25, 08:41:36.906, 113948526842, vstest.console.dll, TestRunRequest.WaitForCompletion: Waiting with timeout -1.
TpTrace Verbose: 0 : 3804, 6, 2021/10/25, 08:41:36.906, 113948529506, vstest.console.dll, ProxyExecutionManager: Test host is always Lazy initialize.
TpTrace Verbose: 0 : 3804, 6, 2021/10/25, 08:41:36.907, 113948535362, vstest.console.dll, TestRequestSender.InitializeCommunication: initialize communication. 
TpTrace Information: 0 : 3804, 6, 2021/10/25, 08:41:36.924, 113948710613, vstest.console.dll, SocketServer.Start: Listening on endpoint : 127.0.0.1:61223
TpTrace Verbose: 0 : 3804, 6, 2021/10/25, 08:41:36.929, 113948760401, vstest.console.dll, DotnetTestHostmanager: Adding  --runtimeconfig "C:\Users\green\Desktop\Projects\.NetCoreMoviesAPI\MoviesAPI.Tests\bin\Debug\netcoreapp3.1\MoviesAPI.Tests.runtimeconfig.json" in args
TpTrace Verbose: 0 : 3804, 6, 2021/10/25, 08:41:36.929, 113948761966, vstest.console.dll, DotnetTestHostmanager: Adding  --depsfile "C:\Users\green\Desktop\Projects\.NetCoreMoviesAPI\MoviesAPI.Tests\bin\Debug\netcoreapp3.1\MoviesAPI.Tests.deps.json" in args
TpTrace Verbose: 0 : 3804, 6, 2021/10/25, 08:41:36.929, 113948764222, vstest.console.dll, DotnetTestHostManager: Testhost.exe/testhost.x86.exe found at path: C:\Users\green\Desktop\Projects\.NetCoreMoviesAPI\MoviesAPI.Tests\bin\Debug\netcoreapp3.1\testhost.exe
TpTrace Verbose: 0 : 3804, 6, 2021/10/25, 08:41:36.930, 113948764745, vstest.console.dll, DotnetTestHostmanager: Full path of host exe is C:\Users\green\Desktop\Projects\.NetCoreMoviesAPI\MoviesAPI.Tests\bin\Debug\netcoreapp3.1\testhost.exe
TpTrace Verbose: 0 : 3804, 4, 2021/10/25, 08:41:36.931, 113948774544, vstest.console.dll, DotnetTestHostManager: Starting process 'C:\Users\green\Desktop\Projects\.NetCoreMoviesAPI\MoviesAPI.Tests\bin\Debug\netcoreapp3.1\testhost.exe' with command line ' --runtimeconfig "C:\Users\green\Desktop\Projects\.NetCoreMoviesAPI\MoviesAPI.Tests\bin\Debug\netcoreapp3.1\MoviesAPI.Tests.runtimeconfig.json" --depsfile "C:\Users\green\Desktop\Projects\.NetCoreMoviesAPI\MoviesAPI.Tests\bin\Debug\netcoreapp3.1\MoviesAPI.Tests.deps.json" --port 61223 --endpoint 127.0.0.1:061223 --role client --parentprocessid 3804 --diag "C:\Users\green\Desktop\Projects\.NetCoreMoviesAPI\MoviesAPI.Tests\log.host.21-10-25_08-41-36_92830_6.txt" --tracelevel 4 --telemetryoptedin false'
TpTrace Verbose: 0 : 3804, 4, 2021/10/25, 08:41:36.966, 113949128337, vstest.console.dll, Test Runtime launched
TpTrace Verbose: 0 : 3804, 6, 2021/10/25, 08:41:36.967, 113949137184, vstest.console.dll, TestRequestSender.WaitForRequestHandlerConnection: waiting for connection with timeout: 90000
TpTrace Verbose: 0 : 3804, 6, 2021/10/25, 08:43:06.982, 114849294719, vstest.console.dll, Test host failed to start Test host launched:True test host exited: False
TpTrace Error: 0 : 3804, 6, 2021/10/25, 08:43:06.986, 114849325647, vstest.console.dll, ProxyExecutionManager.StartTestRun: Failed to start test run: Microsoft.VisualStudio.TestPlatform.ObjectModel.TestPlatformException: vstest.console process failed to connect to testhost process after 90 seconds. This may occur due to machine slowness, please set environment variable VSTEST_CONNECTION_TIMEOUT to increase timeout.
   at Microsoft.VisualStudio.TestPlatform.CrossPlatEngine.Client.ProxyOperationManager.ThrowExceptionOnConnectionFailure(Int32 connTimeout)
   at Microsoft.VisualStudio.TestPlatform.CrossPlatEngine.Client.ProxyOperationManager.SetupChannel(IEnumerable`1 sources, String runSettings)
   at Microsoft.VisualStudio.TestPlatform.CrossPlatEngine.Client.ProxyExecutionManager.StartTestRun(TestRunCriteria testRunCriteria, ITestRunEventsHandler eventHandler)
TpTrace Verbose: 0 : 3804, 6, 2021/10/25, 08:43:07.038, 114849845345, vstest.console.dll, TestRunRequest:SendTestRunMessage: Starting.
TpTrace Information: 0 : 3804, 6, 2021/10/25, 08:43:07.038, 114849847057, vstest.console.dll, TestRunRequest:SendTestRunMessage: Completed.
TpTrace Verbose: 0 : 3804, 6, 2021/10/25, 08:43:07.054, 114850005415, vstest.console.dll, TestRequestSender.EndSession: Sending end session.
TpTrace Verbose: 0 : 3804, 6, 2021/10/25, 08:43:07.054, 114850006298, vstest.console.dll, ProxyOperationManager.Close: waiting for test host to exit for 100 ms
TpTrace Warning: 0 : 3804, 6, 2021/10/25, 08:43:07.154, 114851014417, vstest.console.dll, ProxyOperationManager: Timed out waiting for test host to exit. Will terminate process.
TpTrace Verbose: 0 : 3804, 6, 2021/10/25, 08:43:07.156, 114851034491, vstest.console.dll, ParallelProxyExecutionManager: HandlePartialRunComplete: Total completed clients = 1, Run complete = True, Run canceled: False.
TpTrace Verbose: 0 : 3804, 6, 2021/10/25, 08:43:07.167, 114851143870, vstest.console.dll, TestRunRequest:TestRunComplete: Starting. IsAborted:True IsCanceled:False.
TpTrace Verbose: 0 : 3804, 6, 2021/10/25, 08:43:07.168, 114851146277, vstest.console.dll, TestLoggerManager.HandleTestRunComplete: Ignoring as the object is disposed.
TpTrace Information: 0 : 3804, 6, 2021/10/25, 08:43:07.168, 114851147853, vstest.console.dll, TestRunRequest:TestRunComplete: Completed.
TpTrace Verbose: 0 : 3804, 1, 2021/10/25, 08:43:07.168, 114851148428, vstest.console.dll, TestRunRequest.Dispose: Starting.
TpTrace Information: 0 : 3804, 1, 2021/10/25, 08:43:07.168, 114851149056, vstest.console.dll, TestRunRequest.Dispose: Completed.
TpTrace Information: 0 : 3804, 1, 2021/10/25, 08:43:07.168, 114851149493, vstest.console.dll, TestRequestManager.RunTests: run tests completed.
TpTrace Information: 0 : 3804, 1, 2021/10/25, 08:43:07.168, 114851150962, vstest.console.dll, RunTestsArgumentProcessor:Execute: Test run is completed.
TpTrace Verbose: 0 : 3804, 1, 2021/10/25, 08:43:07.168, 114851151659, vstest.console.dll, Executor.Execute: Exiting with exit code of 1

Mitigation steps I have tried:
1)Reinstalling windows 10 afresh.
2)https://developercommunity.visualstudio.com/t/vstestconsole-process-failed-to-connect-to-testhos/503193
3) https://github.com/microsoft/vstest/issues/1544
4) https://medium.com/@daniel.sagita/fatal-error-when-debugging-unit-test-from-visual-studio-6466d3983251
5) 

VS Code version: Code 1.61.2 (6cba118ac49a1b88332f312a8f67186f7f3c1643, 2021-10-19T14:57:20.575Z)
OS version: Windows_NT x64 10.0.19043
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-8265U CPU @ 1.60GHz (8 x 1800)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|7.78GB (1.79GB free)|
|Process Argv|. --crash-reporter-id 3819e720-273b-4aeb-a557-fcd6dc6704b4|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (8)</summary>

Extension|Author (truncated)|Version
---|---|---
bracket-pair-colorizer|Coe|1.0.61
vscode-eslint|dba|2.2.2
prettier-vscode|esb|9.0.0
dotnet-test-explorer|for|0.7.7
csharpextensions|jch|1.3.1
csharp|ms-|1.23.16
material-icon-theme|PKi|4.10.0
vscodeintellicode|Vis|1.2.14

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383:30185418
pythonvspyt602:30300191
vspor879:30202332
vspor708:30202333
vspor363:30204092
pythonvspyt639:30300192
pythontb:30283811
pythonptprofiler:30281270
vsdfh931cf:30280410
vshan820:30294714
vstes263cf:30335440
vscorecescf:30384386
pythondataviewer:30285071
pythonvsuse255:30340121
vscod805cf:30301675
pythonvspyt200:30340761
binariesv615:30325510
vsccppwtct:30382698
pythonvssor306:30344512
bridge0708:30335490
pygetstartedt3:30385195
dockerwalkthru:30377721
bridge0723:30353136
pythonrunftest32:30373476
pythonf5test824:30373475
javagetstartedc:30364665
pythonvspyt187:30373474
vsqsis200:30386379
vsaa593:30376534
vssld246cf:30386378
vscrecpromptt3:30387013

```

</details>

<!-- generated by issue reporter --
[log.host.21-10-25_08-41-36_92830_6.txt](https://github.com/microsoft/vstest/files/7408641/log.host.21-10-25_08-41-36_92830_6.txt)
[log.txt](https://github.com/microsoft/vstest/files/7408651/log.txt)
>

**Comment by Evangelink** [comment]
@oeademola Are you still experiencing the issue with newer versions of the Test Platform?

**Comment by oeademola** [comment]
Hi @Evangelink. It is resolved now. Thank you 🙂

**Comment by Evangelink** [comment]
Thanks for the confirmation @oeademola!

**Comment by logany-hi** [comment]
Cool; that was a significant amount of my time taken to read this issue utterly wasted...
