### ISSUE TITLE
Data driven test discovered and running in Visual Studio Test Explorer are not running in pipeline Visual Studio Test version 2

### ISSUE THREAD

**Issue by maheshbommireddi** [microsoft/vstest#3129]
## Description
Data driven test discovered and running in Visual Studio Test Explorer are not running in pipeline  Visual Studio Test version 2

With the latest update from 
MSTest.TestAdapter 2.2.3 to 2.2.7 
MSTest.TestFramework 2.2.3 to 2.2.7

Data driven tests with multiple iterations are shown in test explorer(as child items), and when run locally or through command prompt (vstest.console.exe) running all the iterations and generating a .trx file with test results of all iterations.

But when I try to run the same test in Release pipeline with Visual Studio Test version 2, only the first iteration (only one) is running and reporting test result status. (it should run all iterations not just one)
Rest of the iterations in data driven test are not running in pipeline

This issue occurs only when I try to run the tests through release pipeline. When we run the same test in test explorer all iterations are running

Test is in below format
public async Task testname(int iteration)

## Visual Studio Test explorer: showing all 6 iterations:
![image](https://user-images.githubusercontent.com/42587118/138727193-6171987b-e22e-435a-9e9f-0c9fcdbcbada.png)

## Visual Studio Test Version 2 : only one iteration (Identified / run)
![image](https://user-images.githubusercontent.com/42587118/138727876-34a42e40-74fc-43ce-a58d-2a38758a471f.png)

## Package
    PackageReference Include="Microsoft.NET.Test.Sdk" Version="16.11.0" /
    PackageReference Include="MSTest.TestAdapter" Version="2.2.7" /
    PackageReference Include="MSTest.TestFramework" Version="2.2.7" /

## Expected behavior
All test iterations should be run

## Actual behavior
Only first iteration is run and test result is updated in test plan (through visual studio test version 2)
All iteration run (in Visual Studio Test explorer)
All iterations run (developer cmd prompt (vstest.console.exe))

**Comment by MartinHatch80** [comment]
I was having exactly the same behaviour. 

Switched to nUnit and the tests started running again.
Weirdly the tests executed fine in the Build Pipeline, but not the Release Pipeline, so I'm guessing it's an issue with the agent pool somewhere?

**Comment by Evangelink** [comment]
We have been fixing a lot of issues with data driven tests on mstest so we recommend you to update to latest version available.

We are going to close this ticket but if you are still experiencing any issue please feel free to post back.

**Comment by maheshbommireddi** [comment]
with the latest vesion 

    <PackageReference Include="MSTest.TestAdapter" Version="2.2.10" />
    <PackageReference Include="MSTest.TestFramework" Version="2.2.10" />
    <PackageReference Include="Microsoft.NET.Test.Sdk" Version="17.2.0" />

Tests running in release stages are not updating test output status




![image](https://user-images.githubusercontent.com/42587118/182397611-3796851a-8474-43ae-b42f-fa41d51fdda5.png)

Run on agent is marked as bellow but test result not updated

Logs shows data driven test as passed but not marked them as passed in test plans

![image](https://user-images.githubusercontent.com/42587118/182398008-c3078433-8f8b-47e9-ba31-87c083d6c6af.png)

**Comment by narensrinivas** [comment]
I'm Getting the same issue which is posted above when running with below version.

<PackageReference Include="MSTest.TestAdapter" Version="2.2.10" />
<PackageReference Include="MSTest.TestFramework" Version="2.2.10" />

I can see testcase in others and it has the attribute with [DataTestMethod][DynamicData(nameof(Methodname), DynamicDataSourceType.Method))]

Also, testcase without attribute [DynamicData]. These test cases are showing under passed or failed category but only 1st iteration alone running.

Now I have upgraded to version

<package id="MSTest.TestAdapter" version="3.0.2" targetFramework="net48" />
<package id="MSTest.TestFramework" version="3.0.2" targetFramework="net48" />

[DataTestMethod]
[DataRow(True)]
[DataRow(False)]
public void DispayResult(bool input)
{
Asset.IsTrue(input);
}

Result:
Here the testcase are not falling under others category but only first iteration is executed and total testcase count is mismatching.

Expected Testcase count: 2 but getting as 1.
LogDetails: In log I can see "2023-02-07T11:25:37.8760918Z Passed    DispayResult(System.Boolean)    DispayResult(True)"

**Comment by dannyclarke** [comment]
I am also getting the same issue when trying to run my test code via a release pipeline. With only the first iteration being executed with data driven tests.  

I am currently on the latest version available which is current v3.1.1
```
<PackageReference Include="MSTest.TestAdapter" Version="3.1.1" />
<PackageReference Include="MSTest.TestFramework" Version="3.1.1" />
```

When running the same code through a build pipeline all the data driven test are running as expected so this issue looks to be specific to the release pipeline

**Comment by nohwnd** [comment]
@rasunkar from the description above this looks like issue with the batching done by the vstest task, can someone from your team please have a look?

**Comment by nohwnd** [comment]
I believe this is a Azure DevOps issue, please file an issue on https://github.com/microsoft/azure-pipelines-tasks if your problem still persists.
