### ISSUE TITLE
Documentation Issues

### ISSUE THREAD

**Issue by harshjain2** [Microsoft/vstest#313]
## Description
> 1. Extra whitespace in logger help after "trx"
https://github.com/Microsoft/vstest/blob/77f351fd73adf6b70be8f1912d1891c9cf0f5a52/src/vstest.console/Resources/Resources.resx#L237
`
/logger:trx [;LogFileName=<Defaults to unique file name>]`
![image](https://cloud.githubusercontent.com/assets/13763032/21610960/d362e642-d1f0-11e6-84df-d59966cbb3a8.png)

> 2. Add sample usage for cli runsettings arguments. Additionally improve the documentation of cli runsettings arguments.

> 3. Support dotnet vstest -h
Currently typing this command gives this message:
```
Microsoft (R) Test Execution Command Line Tool Version 15.0.0.0
Copyright (c) Microsoft Corporation.  All rights reserved.

Error: The test source file "-h" provided was not found.
```

**Comment by pvlakshm** [comment]
There are 3 issues here:
**(1) The extra white space after /logger:trx:** this causes a malformed commandline if you then provide a LogFileName. Therefore, **Fix this** by just removing that extra space.
**(2) Add sample usage for the CLI runsettings arguments:** Only the most common arguments ought to be shown on the command line help. Providing runsettings arguments in the commandline is arguably an advanced scenario and the user ought to consult our documentation for that. Therefore, **Won't Fix here**. 
**(3) Support dotnet vstest -h:** If you provide -h in addition to the error mentioned above, we also emit the over help content. That is fine. Therefore, **Wont'fix here**.

**Comment by harshjain2** [comment]
Issue **(1)** is already fixed.
