### ISSUE TITLE
Getting skipped_function with reason=has_external_branch 

### ISSUE THREAD

**Issue by julaudo** [microsoft/vstest#3142]
## Description
I'm collecting a native C++ application coverage. I noticed that some functions/methods are ignored, and when analyzing, the xml says the methode has external branches, which is not the case.

## Steps to reproduce
```
CodeCoverage.exe collect /verbose /output:output.coverage MyExe.exe
CodeCoverage.exe analyze /include_skipped_functions /output:output.xml output.coverage
```

## Expected behavior
Should not get a has_external_branch 

## Actual behavior
> What is the behavior observed?

## Diagnostic logs
I cannot release full code but here is a function causing this problem

```
void Picture::OnType(ControlGridViewItem* lpgvi)
{
  int m_dwStyle = 0;
  switch((LPARAM)lpgvi)
  {
  case 0:
    m_dwStyle |= 8;
    break;
  case 1:
    m_dwStyle |= 7;
    break;
  case 2:
    m_dwStyle |= 6;
    break;
  case 3:
    m_dwStyle |= 5;
    break;
  case 4:
    m_dwStyle |= 4;
    break;
  case 5:
    m_dwStyle |= 3;
    break;
  }
}
```
I get this error : `<skipped_function id="758528" name="OnType" type_name="Picture" reason="has_external_branch" />`
Now if I remove the last case, it's ok:
`<function id="758528" name="OnType" type_name="Picture" block_coverage="0.00" line_coverage="0.00" blocks_covered="0" blocks_not_covered="12" lines_covered="0" lines_partially_covered="0" lines_not_covered="13">`

I've got the same issue on many function, and **they all contain a switch statement**.

I check into the pdb file, it seems correct, the lines appear in the file.

Could not reproduce this on a minimal project.

## Environment
Microsoft Visual Studio Community 2019
Version 16.11.5

Tried CodeCoverage.exe **17.0.21471.247101** and **16.0.21158.215801**, same results

**Comment by jakubch1** [comment]
Currently this is limitation of our dynamic code coverage. The workaround is to use VSInstr: https://docs.microsoft.com/en-us/visualstudio/profiling/vsinstr?view=vs-2017. 
We are working on providing static code coverage for native code. This should resolve this issue. I will let you know when this is ready.

**Comment by jakubch1** [comment]
We created static C++ code coverage which is available in our new tool `Microsoft.CodeCoverage.Console` which is replacing `CodeCoverage.exe`. There is no `has_external_branch` issue anymore in it.

More info: https://docs.microsoft.com/en-us/visualstudio/test/microsoft-code-coverage-console-tool?view=vs-2022
