### ISSUE TITLE
Tests aborted when .NET Framework version is <4.6

### ISSUE THREAD

**Issue by natemcmaster** [Microsoft/vstest#315]
Runs of 'dotnet test' on AppVeyor crash with this error:

```
> dotnet test --configuration Debug --framework net451
Build started, please wait...
Build completed.
Test run for C:\projects\common\test\Microsoft.Extensions.CommandLineUtils.Tests\bin\Debug\net451\Microsoft.Extensions.CommandLineUtils.Tests.dll(.NETFramework,Version=v4.5.1)
Microsoft (R) Test Execution Command Line Tool Version 15.0.0.0
Copyright (c) Microsoft Corporation.  All rights reserved.
Starting test execution, please wait...
Error: The active Test Run was aborted
```

See https://ci.appveyor.com/project/aspnetci/common/build/1.0.797#L618 for example.

This only happens on AppVeyor's machines, and appears to only occur when VSTest is running a .NET Framework test run. It doesn't repro our internal CI agents, dev machines, or Linux boxes. Any suggestions on getting more details about why this failed?

**Details**
Using dotnet-CLI 1.0.0-preview4-004233
Using Microsoft.NET.Test.Sdk 15.0.0-preview-20161123-03

**Comment by codito** [comment]
Closing this since it has been solved.
