### ISSUE TITLE
Reuse testhost for parallel .net framework discovery/execution

### ISSUE THREAD

**Issue by Sanan07** [microsoft/vstest#3193]
Currently when we discovering/execution .net framework test projects, vstest.console.exe will spawn new testhost for each test assembly.
By its shared design, in .net framework test projecst we can reuse testhost for the next source, instead of closing it and creating new one.

It was discovered as part of this issue #3192.
This change should also take in consideration new implemented testsession work.

**Comment by cvpoienaru** [comment]
@Sanan07 I assigned this to me and I'll probably fix it as part of the next phase of perf improvements. If you'd like to work on it yourself though please let me know.
