### ISSUE TITLE
v17.0.0 fails to run test on Windows on ARM where 16.11.0 works

### ISSUE THREAD

**Issue by rustedwizard** [microsoft/vstest#3203]
I am having a simple class library project targeting net6.0 and I created test project targeting net6.0 as well. When I install ```Microsoft.NET.Test.Sdk``` v16.11.0 run tests in Context on VSCode works on both regular Windows 10 (Surface laptop AMD64) and ARM64 (Surface pro x). 

However, when I upgrade to v17.0.0, it runs on regular Windows 10(Surface laptop AMD64) without any issue (both VS and VSCode). But couldn't run tests on VSCode on Windows On ARM(Surface pro x). I got following error:

```
Microsoft.VisualStudio.TestPlatform.ObjectModel.TestPlatformException: Testhost process exited with error: Unhandled exception. System.BadImageFormatException: Could not load file or assembly 'c:\Users\chens\source\vscoderepos\DataStructure\HeapTest\bin\Debug\net6.0\testhost.dll'. An attempt was made to load a program with an incorrect format.
File name: 'c:\Users\chens\source\vscoderepos\DataStructure\HeapTest\bin\Debug\net6.0\testhost.dll'
. Please check the diagnostic logs for more information.
   at Microsoft.VisualStudio.TestPlatform.CrossPlatEngine.Client.ProxyOperationManager.ThrowOnTestHostExited(Boolean testHostExited)
   at Microsoft.VisualStudio.TestPlatform.CrossPlatEngine.Client.ProxyOperationManager.SetupChannel(IEnumerable`1 sources, String runSettings)
   at Microsoft.VisualStudio.TestPlatform.CrossPlatEngine.Client.ProxyDiscoveryManager.DiscoverTests(DiscoveryCriteria discoveryCriteria, ITestDiscoveryEventsHandler2 eventHandler)
----- Test Execution Summary -----

Total tests: 0. Passed: 0. Failed: 0. Skipped: 0
```

Please help!

**Comment by Krumelur** [comment]
Confirmed here on Windows 11 ARM build (Insider Preview)

**Comment by Evangelink** [comment]
@rustedwizard @Krumelur Are you still experiencing this issue with newer version of the test sdk?

**Comment by Krumelur** [comment]
Sorry. I cannot verify as I don’t have the project around anymore.

**Comment by Evangelink** [comment]
No worries! Thank you for taking the time to reply!

**Comment by rustedwizard** [comment]
I still have a small test project around, I will try this on weekend.

**Comment by rustedwizard** [comment]
@Evangelink, Sorry for late response, I tested again on Surface Pro X (ARM64 based) with v17.2.0 and it works now. So close this issue.

**Comment by jjschlesinger** [comment]
FYI, I was still getting this issue on VS 17.4 preview 1. I upgraded my package `Microsoft.NET.Test.Sdk` from 17.0 to 17.3 and this fixed my issue.
