### ISSUE TITLE
Question: Why does vstest command line and Visual Studio run tests in different order

### ISSUE THREAD

**Issue by Cjewett** [microsoft/vstest#3209]
When running unit tests from the command line using dotnet test, dotnet vstest, and vstest.console.exe it will run tests in a different order than if you run them in Visual Studio from the GUI. I'm wondering why there is a discrepancy between the two and how would I go about narrowing down why that difference exists? I've tried turning on diagnostic logging to hopefully see the output of the command line that Visual Studio uses to run the tests but didn't see it anywhere.

Edit: First glance suggests Visual Studio will run tests in alphabetical order. vstest cli will run test methods in the order that they are declared in the file. Does that sound correct? 

The reason this is important to us is because developers will use Visual Studio to run tests. However, in the build system it will use vstest from the command line. The specific command can differ based on the applications target framework (.NET Framework or .NET Core). We have unreliable tests in the build process and order of the tests matter. I understand that it is bad practice to have tests rely on order but being able to run the tests in the same order as the build system is important so we can debug and fix those issues. The problem is that telling developers to run 10,000 tests isn't a good solution because it takes too long, so we want to provide them a subset of those 10,000 tests that they can try to run and replicate the issue. Vstest does not have a test playlist parameter from what I can tell, so we can't tell them to run a command line with the playlist. Then Visual Studio's test playlist functionality does not run tests in the same order as vstest from the command line.

**Comment by nohwnd** [comment]
The reason for this is in console we scan the dll and pick up the methods, but in VS we give that info to Test Explorer and it orders the tests by alphabet (probably because then partial updates won't change order of the tests). When they send back the work we just take it in the order they give it to us.
