### ISSUE TITLE
VSTest 17.0.0 with `/EnableCodeCoverage` skips some DLLs in `.coverage` file

### ISSUE THREAD

**Issue by blmbyd** [microsoft/vstest#3213]
## Description
We have Azure DevOps agent deployed on own machine. After updating VS2019 to VS2022 we discovered change in code coverage reports. Pipeline is configured to build ~20 solutions and run tests for all of them.

## Steps to reproduce
Set test platform version to `Visual Studio 2019` and run pipeline, then set test platform to `Latest` and run pipeline again. Compare produced `coverage` files for each run.

## Expected behavior
List of files in each raport should be this same.

## Actual behavior
Some files (DLLs) are not included in reports.

## Example
![image](https://user-images.githubusercontent.com/7525439/145064877-489696f5-ff59-4fd9-a1af-f04276a7b7b0.png)

## Environment
Azure DevOps Agent v.2.195.0
Microsoft (R) Test Execution Command Line Tool Version 16.11.0
Microsoft (R) Test Execution Command Line Tool Version 17.0.0
Windows Server 2012 R2

**Comment by jakubch1** [comment]
Few questions:
1) Do you have .NET core or .NET framework projects?
2) Do you have any C++/CLI code?

Could you please send your .coverage file? If some data you don't want to be public you can generate new feedback here: https://developercommunity.visualstudio.com/

Could you please try to rerun your scenario using this latest package: https://dev.azure.com/dnceng/public/_packaging?_a=package&feed=test-tools&package=Microsoft.TestPlatform&protocolType=NuGet&version=17.2.0-preview-20211210-01&view=overview ?

**Comment by jakubch1** [comment]
Closing as no data provided. Please reopen if needed.
