### ISSUE TITLE
Version 17 BadImageFofrmatException with dotnet x86

### ISSUE THREAD

**Issue by jtleaming** [microsoft/vstest#3220]
## Description
> When running `dotnet test` from the command line, with Microsoft.NET.Test.Sdk 17, test runner throws exception System.BadImageFormatException. 
When using 16.11.0 tests run just fine.

## Steps to reproduce
Here is the csproj set up for my test project.

<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net6.0</TargetFramework>
    <Nullable>enable</Nullable>
    <IsPackable>false</IsPackable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="FluentAssertions" Version="6.2.0" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Sqlite" Version="6.0.0" />
    <PackageReference Include="Microsoft.AspNetCore.TestHost" Version="6.0.0" />
    <PackageReference Include="Microsoft.NET.Test.Sdk" Version="17.0.0" />
    <PackageReference Include="Moq" Version="4.16.1" />
    <PackageReference Include="xunit" Version="2.4.1" />
    <PackageReference Include="xunit.runner.visualstudio" Version="2.4.3" />
    <PackageReference Include="coverlet.collector" Version="3.1.0" />
  </ItemGroup>
</Project>

run `dotnet test` from powershell. Specifically running the x86 version of the dotnet cli. If I run dotnet from 'ProgramFiles' the tests run as expected.

If I change the Microsoft.NET.Test.Sdk version to 16.11, tests run as expected.

## Expected behavior
> Share the expected output
Tests run succesfully

## Actual behavior
> What is the behavior observed?
Test runner throws exception 

TestHostManagerCallbacks.ExitCallBack: Testhost processId: 13448 exited with exitcode: -532462766 error: 'Unhandled exception. System.BadImageFormatException: Could not load file or assembly 'C:\Code\bin\Debug\net6.0\testhost.dll'. An attempt was made to load a program with an incorrect format.
File name: 'C:\Code\bin\Debug\net6.0\testhost.dll'

## Diagnostic logs
...
TpTrace Warning: 0 : 23956, 1, 2021/12/13, 13:23:50.808, 605815734364, vstest.console.dll, TestPluginDiscoverer: Failed to get types from assembly 'Microsoft.Diagnostics.NETCore.Client, Version=0.2.4.21401, Culture=neutral, PublicKeyToken=31bf3856ad364e35'.  Skipping test extension scan for this assembly.  Error: System.Reflection.ReflectionTypeLoadException: Unable to load one or more of the requested types.
Could not load file or assembly 'Microsoft.Bcl.AsyncInterfaces, Version=1.0.0.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51'. The system cannot find the file specified.
   at System.Reflection.RuntimeModule.GetTypes(RuntimeModule module)
   at System.Reflection.Assembly.GetTypes()
   at Microsoft.VisualStudio.TestPlatform.Common.ExtensionFramework.TestPluginDiscoverer.GetTestExtensionsFromAssembly[TPluginInfo,TExtension](Assembly assembly, Dictionary`2 pluginInfos)
System.IO.FileNotFoundException: Could not load file or assembly 'Microsoft.Bcl.AsyncInterfaces, Version=1.0.0.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51'. The system cannot find the file specified.
File name: 'Microsoft.Bcl.AsyncInterfaces, Version=1.0.0.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51'
 ---> System.IO.FileNotFoundException: Could not load file or assembly 'Microsoft.Bcl.AsyncInterfaces, Culture=neutral, PublicKeyToken=null'. The system cannot find the file specified.
...

## Environment
Windows 11 10.0.222000 
Microsoft.NET.Test.Sdk Version=17.0.0
Dotnet 6.0.100
xunit 2.4.1

**Comment by Haplois** [comment]
Hi,

Can you share your project with us, clarify `net6.0 enable false` this line. A small repro would also be useful if possible...

**Comment by jtleaming** [comment]
[Test project here](https://gitlab.com/disperdercreare/net-six) I tried with this simple project and got the same results.

Sorry, I thought I had pasted the XML from my project file, but it looks like it wrote out as `net6.0 enable false`. Unsure of what happened.

**Comment by Evangelink** [comment]
Hi @jtleaming,

I just tried to clone your repro and run `dotnet test` and it worked. I think issue was fixed in the meantime.

I will move forward by closing this issue but feel free to comment if you are still facing some issue.
