### ISSUE TITLE
VSTest is not on the probing path, so NGEN will fail for any component dependent on their binariies

### ISSUE THREAD

**Issue by tannergooding** [Microsoft/vstest#330]
This will require a two part fix.

First, the extension needs to be installed into a well known location (currently it gets installed into `Common7\IDE\Extensions\<random-name>`). You will need to add the following properties to your VSIX csproj:
```
<ExtensionInstallationRoot>CommonExtensions</ExtensionInstallationRoot>
<ExtensionInstallationFolder>SomeFolderPath</ExtensionInstallationFolder>
```

For an example, see the Live Unit Testing setup here: https://github.com/dotnet/testimpact/blob/master/src/VisualStudio/VisualStudioSetup/VisualStudioSetup.csproj#L26
Our settings cause us to be installed to `CommonExtensions\Microsoft\ManagedLanguages\VBCSharp\LiveUnitTesting`.

The second is to add the well known install folder to the DevEnv probing path: https://devdiv.visualstudio.com/DevDiv/_git/VS?path=%2Fsrc%2Fappid%2Fdevenv%2Fstub%2Fdevenv.urt.config.tt&version=GBdev%2Fvslsnap%2Finsertions%2Fd15prerel.20170106175543&_a=contents&line=61&lineStyle=plain&lineEnd=62&lineStartColumn=1&lineEndColumn=1

**Comment by pvlakshm** [comment]
Closing this; we are now way beyond the point where such a change may be considered.
