### ISSUE TITLE
Very bad performance of large playlists 

### ISSUE THREAD

**Issue by MaceWindu** [microsoft/vstest#3337]
## Description

We have many tests (hundreds of thousands) and sometimes we need to create and manage playlists for them.
While Visual Studio currently (VS 17.0.5) able to work with such amount of tests just fine in general, working with playlists with thousands of tests is pure nightmare when you need e.g. to remove some tests from such playlist. It could take many minutes to perform this operation and consume a lot of memory/CPU during process. And bigger playlist - bigger delay you have.

It would be great to have painless experience to work with big playlists.

## Steps to reproduce
- create playlist with e.g. 10k tests (or more for more pain)
- select several tests and select remove from playlist option from context menu for them

## Expected behavior
- Visual Studio remove selected records from playlist xml in several seconds (at worst)

## Actual behavior
- Visual Studio use all available resources for several minutes

## Environment
> VS 17.0.5

**Comment by MaceWindu** [comment]
Made some tests with sample test project and have additional details. When you create playlist and don't save it (so it is only in memory) - performance is not bad (couple of seconds on 100k tests). But after you save playlist to file, removal of single test takes minutes.

```cs
// nunit testcase to generate a lot of tests
[TestFixture]
    public class MyFixture
    {
        private static int[] _cases = Enumerable.Range(1, 100000).Select(i => i).ToArray();
        [TestCaseSource(nameof(_cases))]
        public void Test(int id)
        {
        }
    }
```

**Comment by Evangelink** [comment]
Note for self: Create a ticket on Test Window side. 
cc @drognanar
