### ISSUE TITLE
Add option to `dotnet test` to generate playlist for failed tests

### ISSUE THREAD

**Issue by MaceWindu** [microsoft/vstest#3338]
## Description

Consider following scenario when running tests on test server/CI results in some failing tests. As developer I would like to get playlist with failed tests as additional test run artifact so I can load it and debug/fix failing tests.

As workaround currently we use own tool to parse trx file and generate playlist from it.

**Comment by Piedone** [comment]
This would be great!

Can you disclose something about how you do it with the TRX parsing? Perhaps do you have a GitHub Actions action for it?

**Comment by JinsPeter** [comment]
I, as a developer  would really appreciate such a feature

**Comment by nohwnd** [comment]
This is a new feature and won't be implemented, we are focusing on adding new features to Testing.Platform instead.  https://learn.microsoft.com/en-us/dotnet/core/testing/unit-testing-platform-intro?tabs=dotnetcli
