### ISSUE TITLE
UX: dotnet-test filtering syntax is difficult to discover

### ISSUE THREAD

**Issue by natemcmaster** [Microsoft/vstest#334]
Given current design, I would expect many new dotnet users will struggle to figure out how to use dotnet-test arguments, such as the `--filter` syntax on command line. Even after reading docs, looking at examples, and fiddling with dotnet-test, it took a dozen tries to figure out how to get it right.

Here's a summary of what happened in the first 10 minutes I tried to use dotnet-test.

## Setup
Install dotnet-cli 1.0.0-preview5-004478
`dotnet new -t xunittest`
`dotnet restore`

### What happened next
`dotnet test` ✅  Yay, it worked! Now let's see if I can filter to just one method.

`dotnet test -method Tests.Tests.Test1` :x: Tried the syntax that worked in dotnet-test-xunit
> MSBUILD : error MSB1001: Unknown switch.
Switch: -method
For switch syntax, type "MSBuild /help"

`dotnet test /help` :x:
> Wall of text. MSBuild spits out 237 lines of how to use MSBuild. Nothing in there is relevant to dotnet-test

`dotnet test --help` 👍  getting closer. NB: I had to **guess** this was right. Nothing in the previous lines of output suggested this was available.
> (Correct dotnet-test help output).

(Skims help output, sees `--filter` is available. *Here is where I made a mistake.* If I had read _all_ of the help output, I might have figured it out sooner. But I didn't. My eyes were drawn to the left side of the help output which shows args, not the right side which included some examples of how to use --filter.

Attempt to use --filter. :x:
```sh
dotnet test --filter Test1
dotnet test --filter Name=Test1
dotnet test --filter "Name=~Test1"
dotnet test -f Tests.Tests.Test1 # this one actually collides with --framework...
dotnet test --filter Tests.Tests.Test1
dotnet test --filter "Name~Tests.Tests.Test1"
```
Most of the time, dotnet-test show this

> Starting test execution, please wait...
Warning: No test is available in /Users/namc/dev/msbuild-demos/netcore/2-test/bin/Debug/netcoreapp1.0/2-test.dll. Make sure that installed
 test discoverers & executors, platform & framework version settings are appropriate and try again.

Revisit `dotnet test --help` again. Finally discover that the correct syntax to filter is this:
`dotnet test --filter FullyQualifiedName=Tests.Tests.Test1`

**Next steps**
Create a shell script to invoke this because typing `FullyQualifiedName=` repeatedly will be a pain.

**Comment by Dima4ka** [comment]
Now it's even different - `dotnet test --testCaseFilter FullyQualifiedName=NameSpace.Class.Method`

**Comment by natemcmaster** [comment]
@Dima4ka I think `--testCaseFilter` is for `dotnet vstest`, and `--filter` is for `dotnet test`

**Comment by Dima4ka** [comment]
@natemcmaster Here is the help from `dotnet test -help`

```
dotnet test --help
.NET Test Driver

Usage: dotnet test [arguments] [options]

Arguments:
  <PROJECT>  The project to test, defaults to the current directory.

Options:
  -h|--help                             Show help information
  -s|--settings <SettingsFile>          Settings to use when running tests.
  -lt|--listTests                       Lists discovered tests
  -tcf|--testCaseFilter <Expression>    Run tests that match the given expression.
                                        Examples:
                                        --testCaseFilter:"Priority = 1"
                                        --testCaseFilter: "(FullyQualifiedName~Nightly | Name = MyTestMethod)"
  -tap|--testAdapterPath                Use custom adapters from the given path in the test run.
                                        Example: --testAdapterPath:<pathToCustomAdapters>
  -l|--logger <LoggerUri/FriendlyName>  Specify a logger for test results.
                                        Example: --logger:trx
  -c|--configuration <configuration>    Configuration under which to build, i.e. Debug/Release
  -f|--framework <FrameworkVersion>     Looks for test binaries for a specific framework
  -o|--output <OutputDir>               Directory in which to find the binaries to be run
  -d|--diag <PathToLogFile>             Enable verbose logs for test platform.
                                        Logs are written to the provided file.
  --noBuild                             Do not build project before testing.
```

Although, I still cannot get it run a single test in xUnit... Even with `dotnet test --testCaseFilter FullyQualifiedName=NameSpace.Class.Method`.

**Comment by natemcmaster** [comment]
@Dima4ka oh, you have an older version of CLI. This was renamed a couple months ago: https://github.com/dotnet/cli/pull/5032

**Comment by Dima4ka** [comment]
@natemcmaster Wow, thanks for catching that! How do I update to the latest?

**Comment by natemcmaster** [comment]
@Dima4ka https://github.com/dotnet/core/blob/master/release-notes/rc4-download.md

**Comment by Dima4ka** [comment]
@natemcmaster Wow, it now works perfectly! Thank you!

This `dotnet test --filter "FullyQualifiedName=NameSpace.Class.Method"` now executes single test in xUnit.

**Comment by codito** [comment]
`FullyQualifiedName` seems to be the most frequent use case. Should `dotnet test --filter xyz` map to a LIKE match `dotnet test --filter FullyQualifiedName~xyz`? This will match all tests that have `xyz` in their FQN.

It will help reduce typing effort and also cover the cases where user knows a `class`, `method` or `namespace`. It's up to user to make the search as specific as they want it to (`Namespace.Class.TestMethod` being the most complex case). Thoughts?

**Comment by natemcmaster** [comment]
+1. Inferring `FullyQualifiedName` seems like is a sensible default. I'm assuming this can be done while while still allowing more advanced filter syntaxes, like `dotnet test --filter TestCategory!=SomeValue`, right?

**Comment by blackdwarf** [comment]
This would be really good. Though I'm split between overloading `--filter` like this and maybe introducing something new like `--name` or similar.

**Comment by codito** [comment]
Updated documentation is here: https://github.com/Microsoft/vstest-docs/blob/master/docs/filter.md

**Comment by smadala** [comment]
Made `FullyQualifiedName` as default property and `~` as default operator. 4089254869067867cad459aa2ccc8a66636473aa

**Comment by natemcmaster** [comment]
Terrific, thanks for the docs and the improved syntax 👍

**Comment by chriswolf-nrg** [comment]
`dotnet test --filter "FullyQualifiedName=NS.Demo.TestMethod` doesn't work at all for me.   Also when I try `--no-build`, (after building at least once) it reports, `MSBUILD : error MSB1001: Unknown switch. Switch: --nobuild`
`dotnet --version == 2.1.200`

**Comment by dbogatov** [comment]
@chriswolf-nrg 

That's the script I use with the latest distribution

```bash
#!/usr/bin/env bash

set -e
shopt -s globstar

# Ensure that the CWD is set to script's location
cd "${0%/*}"
CWD=$(pwd)

dotnet restore --disable-parallel
dotnet build --no-restore

if [ -n "$1" ]
then
	echo "Running test $1 ..."
	dotnet test --no-build --no-restore --filter "FullyQualifiedName~$1"
else
	echo "Running dotnet tests..."
	dotnet test --no-build --no-restore --verbosity n
fi

echo "Testing completed!"
```

**Comment by chriswolf-nrg** [comment]
Thanks for the script, but the filter is still not working for me.
```
NUnit3TestExecutor converted 229 of 229 NUnit test cases
Skipping assembly - no matching test cases found
NUnit Adapter 3.9.0.0: Test execution complete
```

**Comment by dbogatov** [comment]
I guess, my script is specific for xUnit.
I assume NUnit may have slightly different syntax in filter.
