### ISSUE TITLE
Hot to get TFM information inside custom datacollector?

### ISSUE THREAD

**Issue by daveMueller** [microsoft/vstest#3360]
Hi,

is there any information on how to get TFM inside our datacollector? As I have seen this issue here [https://github.com/microsoft/vstest/issues/2592](https://github.com/microsoft/vstest/issues/2592), the information must be available. Is it somehow possible to get this information inside the collector so we can pass it to the filename ([https://github.com/coverlet-coverage/coverlet/issues/1276](https://github.com/coverlet-coverage/coverlet/issues/1276))?

**Comment by daveMueller** [comment]
After going through the `vstest` code I figured out I can do something like this as a workaround.
```csharp
string framework = _configurationElement["Framework"]?.InnerText;
string tfm = string.IsNullOrEmpty(framework) ? "" : NuGetFramework.Parse(framework).ToString();
```
With this approach I would have to add another dependency to our code just to parse back the tfm. Is there any plan on changing the runsettings `Framework` value to the actual tfm? Or additionally expose the tfm?

**Comment by MarcoRossignoli** [comment]
Hi @daveMueller,

at the moment we don't have any plan for what I know, I think we can add that deps to coverlet...with this fix https://github.com/coverlet-coverage/coverlet/pull/1243 shouldn't be an issue anymore.

**Comment by nohwnd** [comment]
This is a new feature and won't be implemented, we are focusing on adding new features to Testing.Platform instead.  https://learn.microsoft.com/en-us/dotnet/core/testing/unit-testing-platform-intro?tabs=dotnetcli
