### ISSUE TITLE
Console logger has a hardcoded path separator for the source

### ISSUE THREAD

**Issue by MarinAtanasov** [microsoft/vstest#3376]
## Description
`vstest` console logger has a hardcoded path separator for the source: https://github.com/microsoft/vstest/blob/f67ad493f406b20de05ec066d8b027c0d7f2a837/src/vstest.console/Internal/ConsoleLogger.cs#L744

## Steps to reproduce
1. Checkout https://github.com/MarinAtanasov/AppBrix
2. Run `./Test.ps -Build`
3. Look at the output in the console

## Expected behavior
On Linux, Windows and MacOS, the output should be the same:
```
Passed!  - Failed:     0, Passed:    20, Skipped:     0, Total:    20, Duration: 77 ms - AppBrix.Tests.dll (net6.0)
```

## Actual behavior
On Linux and MacOS, the output contains the full path to the test assembly:
```
Passed!  - Failed:     0, Passed:    20, Skipped:     0, Total:    20, Duration: 100 ms - /home/runner/work/AppBrix/AppBrix/Tests/AppBrix.Tests/bin/Release/net6.0/AppBrix.Tests.dll (net6.0)
```
The issue will probably be reproduced if Windows is set to use a different path separator.

## Diagnostic logs
Not necessary.

## Environment
I am running this [GitHub action](https://github.com/MarinAtanasov/AppBrix/blob/0.28.0/.github/workflows/build.yml), which is using `ubuntu-latest`, `windows-latest` and `macOS-latest` with `dotnet-version: 6.0.x`

**Comment by Evangelink** [comment]
Thank you for reporting this @MarinAtanasov. I confirm that I can reproduce the issue:
```
Passed!  - Failed:     0, Passed:   120, Skipped:     0, Total:   120, Duration: 51 ms - /home/amaury/src/AppBrix/Tests/AppBrix.Permissions.Tests/bin/Debug/net6.0/AppBrix.Permissions.Tests.dll (net6.0)
```
