### ISSUE TITLE
`TestCase.CodeFilePath` and `TestCase.LineNumber` are always `null` and `0`, respectively

### ISSUE THREAD

**Issue by GeorchW** [microsoft/vstest#3417]
I'm trying to use a custom logger to improve the testing experience in vscode-dotnet-test-explorer. The extension is quite popular; I've been contributing to it before.

It seems like `TestCase.CodeFilePath` is always `null` in the event `TestLoggerEvents.DiscoveredTests`. The same holds true for `TestCase.LineNumber`, which always seems to be `0`.

## Steps to reproduce

1. Clone this repository: https://github.com/GeorchW/vstest-codefilepath-demo
2. Build the logger:

```sh
cd logger
dotnet publish
```

3. Try listing the tests with the logger attached:

```sh
cd tests
dotnet test --test-adapter-path=../logger/bin/Debug/net6.0/publish/ --logger=MyLogger --list-tests
```

4. Inspect the file `tests/output.txt`.

## Expected output

```
FullyQualifiedName: tests.UnitTest1.Test1
Location: ./UnitTest1.cs:8
```

## Actual output

```patch
FullyQualifiedName: tests.UnitTest1.Test1
-Location: ./UnitTest1.cs:8
+Location: <null>:0
```

## Comments

The logger is very minimalist. The test project has been created with `dotnet new xunit`, with no further changes.

This might be a duplicate to #2280, but I hope to give a simpler reproduction.

My environment is Linux, but I suspect that this problem is platform-independent. #2280 seems to have the same (or a similar) problem on Windows.

This is kind of a blocker for a better .NET test integration in VSCode. We currently have to rely on the workspace symbol provider (i.e. OmniSharp) to give us the necessary source information, which 

1. is not always available after tests have been discovered and 
2. might give inconsistent results.

**Comment by nohwnd** [comment]
This reproes for me, but I don't see the locations being collected with netcoreapp2.1. You can force collecting source info by setting RunConfiguration.CollectSourceInformation=true, e.g. like this: 


`vstest.console.exe MSTest2.dll --listtests -- RunConfiguration.CollectSourceInformation=true`
