### ISSUE TITLE
Add timeout for the data collector events

### ISSUE THREAD

**Issue by MarcoRossignoli** [microsoft/vstest#3421]
## Description

If data collectors hang on events like test end we don't timeout and everything is blocked forever.

## Steps to reproduce

```cs
using Microsoft.VisualStudio.TestPlatform.ObjectModel.DataCollection;
using System.Diagnostics;
using System.Xml;

namespace hangcollector
{
    [DataCollectorFriendlyName("HangDataCollector")]
    [DataCollectorTypeUri("datacollector://HangDataCollector")]
    public class HangCollector : DataCollector
    {
        DataCollectionLogger logger;
        DataCollectionEnvironmentContext environmentContext;
        public override void Initialize(XmlElement configurationElement, DataCollectionEvents events, DataCollectionSink dataSink, DataCollectionLogger logger, DataCollectionEnvironmentContext environmentContext)
        {
            events.TestCaseEnd += Events_TestCaseEnd;
            this.logger = logger;
            this.environmentContext = environmentContext;
        }

        private void Events_TestCaseEnd(object sender, TestCaseEndEventArgs e)
        {
            this.logger.LogWarning(this.environmentContext.SessionDataCollectionContext, "Events_TestCaseEnd");
            System.Threading.Thread.Sleep(int.MaxValue);
        }
    }
}
```

## Expected behavior

After some time it should fail with timeout exception unblocking tests.

## Actual behavior

It hangs forever

**Comment by Evangelink** [comment]
I think that's a good suggestion, my only question/concern would be what is a good timeout. Like do we expect collectors to be doing everything in minutes? hours? Shall we consider an option to "extend" the default timeout if we create a specific collector that would be known for being slow (too many items to process or some heavy lift operations)?

**Comment by MarcoRossignoli** [comment]
We could chose the more or less default of CI of <~1h but should be configurable for sure(runsettings).

**Comment by nohwnd** [comment]
This is a new feature and won't be implemented, we are focusing on adding new features to Testing.Platform instead.  https://learn.microsoft.com/en-us/dotnet/core/testing/unit-testing-platform-intro?tabs=dotnetcli
