### ISSUE TITLE
Feature Request: Add `TestLoggerEvents.TestStarting` event

### ISSUE THREAD

**Issue by GeorchW** [microsoft/vstest#3432]
Currently, the following events are observable by a logger during a test run:

- TestLoggerEvents.TestRunStarted - when the entire test run is started, i.e. when the `dotnet test` process is started
- TestLoggerEvents.TestResult - when a single test has finished
- TestLoggerEvents.TestRunFinished - when the entire test run is finished, i.e. when the `dotnet test` process terminates.

I'm missing an event that indicates that an individual test is starting to run. 

## Context

I am working on vscode-dotnet-test-explorer right now, and the VSCode testing API differentiates between "enqueued" and "started" tests. Right now, we can't provide this information. Many other testing extensions, e.g. Jest (for JavaScript), Go or Microsoft's own Test Runner for Java have this capability.

It would certainly be possible to gather this information via a DataCollector instead, but a DataCollector 
1. won't provide information on discovered tests (when running with `dotnet test --list-tests`) and 
2. its [TestCaseEnd event](https://github.com/microsoft/vstest/blob/98098ad51f9aab7f49e799535e783b77411017f3/src/Microsoft.TestPlatform.ObjectModel/DataCollector/Events/DataCollectionEvents.cs#L45) only [provides the test outcome](https://github.com/microsoft/vstest/blob/98098ad51f9aab7f49e799535e783b77411017f3/src/Microsoft.TestPlatform.ObjectModel/DataCollector/Events/TestCaseEvents.cs#L203) (and no additional data, like error messages).

## Proposed API

```csharp
class TestLoggerEvents
{
    // ...
    public event EventHandler<TestStartingEventArgs> TestStarting;
}
class TestStartingEventArgs
{
    public TestCase TestCase { get; init; }
}
```

**Comment by nohwnd** [comment]
@GeorchW How do you solve debugging tests from vscode test api? I think that will push you towards using vstest.console as a server ( the same approach as VS and omnisharp-roslyn uses). Are you also aware of this effort in omnisharp-vscode? https://github.com/OmniSharp/omnisharp-vscode/pull/5054

**Comment by GeorchW** [comment]
Oh damn, no, I wasn't aware of the OmniSharp work at all. That renders my work obsolete, I guess.

To nevertheless answer your question: vscode-dotnet-test-explorer is pretty hacky. For debugging, it uses the following technique:

1. Start `dotnet test` with [the following environment variables](https://github.com/formulahendry/vscode-dotnet-test-explorer/blob/0b996b0541e6f5c53de874bdd6c4c5c8fa173b18/src/executor.ts#L48):
   - `DOTNET_CLI_UI_LANGUAGE=en`
   - `VSTEST_HOST_DEBUG=1`
2. [Look for](https://github.com/formulahendry/vscode-dotnet-test-explorer/blob/0b996b0541e6f5c53de874bdd6c4c5c8fa173b18/src/debug.ts#L17) the string `Waiting for debugger to attach...` in the output, also use the regex `/Process Id: (.*),/gm` to find the process ID
3. [Start](https://github.com/formulahendry/vscode-dotnet-test-explorer/blob/0b996b0541e6f5c53de874bdd6c4c5c8fa173b18/src/executor.ts#L87) a new [OmniSharp debugging session](https://github.com/formulahendry/vscode-dotnet-test-explorer/blob/0b996b0541e6f5c53de874bdd6c4c5c8fa173b18/src/debug.ts#L36-L41) that attaches to the process.

Patterns like these are pretty common in the extension. Honestly, I'm surprised about its stability.

**Comment by nohwnd** [comment]
Oh gotcha. I kinda like this approach, and wrote a variation on it in the past as well, when I tried to get a simplified support for running and debugging tests when you are not using omnisharp. Problem was that it is only useful for the basic scenarios, and once you are writing a full extension with language server, there is no reason not to use vstest.console as a server and just wait till it asks you to attach debugger.

**Comment by nohwnd** [comment]
Closing this as won't fix, because there are better ways to solve this.

**Comment by GeorchW** [comment]
Thx for the quick replies!
