### ISSUE TITLE
Consider replacing calls to BuildMultipleAssemblyPath when passing only one source

### ISSUE THREAD

**Issue by Evangelink** [microsoft/vstest#3510]
There is no need to use `BuildMultipleAssemblyPath` if we pass only one source, instead we could use `GetASsetFullPath`.

_Originally posted by @Evangelink in https://github.com/microsoft/vstest/pull/3459#discussion_r832439372_

**Comment by daveMueller** [comment]
Is it OK if I work on this and contribute a PR?

**Comment by nohwnd** [comment]
Thanks @daveMueller!
