### ISSUE TITLE
dotnet test logs to console with verbosity set to quiet

### ISSUE THREAD

**Issue by MarinAtanasov** [microsoft/vstest#3525]
## Description
I have a solution with several test projects. I am using this command to run them:
```PowerShell
dotnet test <list of compiled assemblies> --nologo --verbosity minimal
```

Ever since support for running `dotnet test` on a solution has been added, I have wanted to use it. Especially since it is significantly faster than the previous command.
```PowerShell
dotnet test <solution>.sln --nologo --verbosity minimal
```

The problem is that the output of a run is very messy with console messages that I cannot silence in any way. They are even overlapping because different projects are printing concurrently. Sometimes the test result summary gets split or the console color gets stuck and I have to open a new console window:
```
Test run for <assembly>.dll (.NETCoreApp,Version=v6.0)
Starting test execution, please wait...
A total of 1 test files matched the specified pattern.
```

I have tried setting the verbosity to quiet. I have even tried creating my own console logger in the hopes that I can skip those messages. I have not found a way to get a clean output when running the tests by pointing to the solution.

## Steps to reproduce
I am using this project: [AppBrix](https://github.com/MarinAtanasov/AppBrix/tree/0.29.0)
Run `dotnet build`. Then run this command several times:
```PowerShell
dotnet test AppBrix.sln --nologo --verbosity minimal
```

## Expected behavior
The output should be the same as when running the `Test.ps1` script after building. Or the messages should be ordered so that all test result summaries are printed at the end in a nice clean way.

## Actual behavior
There are a lot of unwanted messages. All of the test projects are printing to the console concurrently. Sometimes the console color becomes stuck after the test execution.

## Diagnostic logs
Not needed.

## Environment
I am using Windows 10 with dotnet sdk version 6.0.201.

**Comment by nohwnd** [comment]
This is a new feature and won't be implemented, we are focusing on adding new features to Testing.Platform instead.  https://learn.microsoft.com/en-us/dotnet/core/testing/unit-testing-platform-intro?tabs=dotnetcli

But we've simplified the banner of vstest at least #5013
