### ISSUE TITLE
Code Coverage: Co-working with code coverage profiler fails with System.InvalidProgramException

### ISSUE THREAD

**Issue by ivo-stoilov** [microsoft/vstest#3534]
Hello there,

Starting with CodeCoverage 16.10.0 we are experiencing issues working together with the profiler that comes with that version. Briefly, the problem occurs in attempts to instrument the already processed IL code by the code coverage profiler on the JIT phase, and that results in System.InvalidProgramException. We have made various experiments without success. Even simply inserting a single NOP instruction at a random position triggers the exception. The issue is not observed with CodeCoverage 16.9.4 (or previous) and other third-party profilers. Please assist us in determining what is causing the issue.

The reproduction use case is not trivial, since it requires a dedicated part of our product, if you need a sample project please let us know, we will provide it.

**Comment by jakubch1** [comment]
Are you able to repro issue using: https://www.nuget.org/packages/Microsoft.CodeCoverage/17.1.0 ?
If yes then we need sample project repro. 
Feel free to report it also on: https://developercommunity.visualstudio.com/home
You are able to provide there privately some dlls of your project if it is an option.

**Comment by ivo-stoilov** [comment]
Hello @jakubch1, many thanks for following up. With CodeCoverage 17.1.0 the described issue is no longer reproducible on the command line, which is great. However, I am still wondering how can we address the issue inside Visual Studio Enterprise (2019+), it seems that the version of the CodeCoverage used internally is one of those which is still causing troubles. Is there a chance to have a fixed CodeCoverage with some of the next updates to the Visual Studio Enterprise?

**Comment by ivo-stoilov** [comment]
Hello @jakubch1, I will try to put as many as I can details while answering your questions:

> Which version of VS you have?

As I mentioned before, we have troubles with enterprise versions of Visual Studio 2019 and 2022 when using **Analyze Code Coverage** option. More details on the use case can be found on our feedback portal, take a look at this [item](https://feedback.telerik.com/justmock/1536589). Earlier today, I updated Visual Studio versions on my machine to the latest versions (respectively 16.11.11 and 17.1.3) and now the issue is reproducible only with the 2019 version.

> Is your test project .NET Framework or .NET Core?

The issue is reproducible only with .NET Core/5/6 test projects.

> Do you use runsettings?

The problematic use case does not use run settings explicitly, but behind the scenes, it uses some in fact. Our Visual Studio extension has a MEF component that modifies runsettings if the code coverage is enabled. This way we make possible to co-work with build-in code coverage. You can find the exact runsettings in the test platform logs [28828_04_06_2022_12_17_18.zip](https://github.com/microsoft/vstest/files/8425537/28828_04_06_2022_12_17_18.zip) captured from the single run.

I hope the provided details help you, please let me know if any other relevant info is needed.

**Comment by jakubch1** [comment]
Thanks for the logs @ivo-stoilov. I see in it that you are configuring your own profiler:
`[CORECLR_PROFILER_PATH_32, C:\Program Files (x86)\Progress\Telerik JustMock\Libraries\CodeWeaver\32\Telerik.CodeWeaver.Profiler.dll],`

but our code coverage is trying configure:
`[CORECLR_PROFILER_PATH_32, C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\Common7\IDE\CommonExtensions\Platform\InstrumentationEngine\x86\MicrosoftInstrumentationEngine_x86.dll]`

at the end your Telerik profiler is used and it's obvious why code coverage will not work. Maybe before version 16.10.0 there was different order and code coverage was earlier configured and whole test run was choosing other profiler.

You can fix it in 2 ways (to get code coverage):
1) Both profilers can cooperate if they are based on CLR Instrumentation Engine: https://github.com/microsoft/CLRInstrumentationEngine. So you could remake your profiler to CLR IE instrumentation method.
2) Disable your profiler. Basically do not configure environment variables for profiling. If you don't use CLR IE there is no way for those profiles to work together.

**Comment by jakubch1** [comment]
So probably you created your own version of coprofiler. Still I recommend switching to CLR Instrumentation Engine as it will make your life easier in future :)

For now resolution for you is to add into config `<CLRIEInstrumentationNetCore>False</CLRIEInstrumentationNetCore>`.
This made your example fixed for 16.10.0.
 For example:
```
  <DataCollectionRunSettings>
    <DataCollectors>
      <DataCollector friendlyName="Code Coverage Wrapper">
        <Configuration>
          <SinkDataCollector friendlyName="Code Coverage" uri="datacollector://Microsoft/CodeCoverage/2.0" isLinked="true">
            <Configuration>
              <CLRIEInstrumentationNetCore>False</CLRIEInstrumentationNetCore>
              <CoverageFileName>result.coverage</CoverageFileName>
            </Configuration>
          </SinkDataCollector>
        </Configuration>
      </DataCollector>
    </DataCollectors>
  </DataCollectionRunSettings>
```

Probably in 16.10.0 we started to use CLR Instrumentation Engine for instrumentation. They had some bug which was causing InvalidProgramException and probably was recently fixed. Above flag is disabling CLR IE instrumentation and fallback to old instrumentation code. Keep in mind that this flag was removed in 17.1.0 and we support now instrumentation only using CLR IE.

Your logic is very interesting and if you want we could set up a meeting and discuss it.

**Comment by ivo-stoilov** [comment]
Hey @jakubch1, great news! Thank you so much for providing the insides and handy solution! We will find a way to incorporate it into our VS extension and make it available to our customers. Regarding CRL Instrumentation Engine, we are planning a deeper study for sure, it seems promising indeed. Sharing knowledge and experience in person would be great, please feel free to reach me using the info in my profile.

At this point, the issue could be considered finally resolved.

**Comment by jakubch1** [comment]
Thanks. I will get back to you after my vacation so we can discuss more.
