### ISSUE TITLE
MSTest: Constructor runs for every test (rather than once for the class) during Debug

### ISSUE THREAD

**Issue by davkean** [Microsoft/vstest#360]
_From @MarkMichaelis on January 16, 2017 21:14_

If you Debug an MSTest with one or more test methods, the constructor runs once for every test (rather than once for the entire class).  This does not seem to occur when running (not debugging).  The following code demonstrates the issue - failing when debugging (successful when not debugging):

`using System;
using Microsoft.VisualStudio.TestTools.UnitTesting;

namespace UnitTestProject1
{
    [TestClass]
    public class TestBase
    {

    }

    [TestClass]
    public class UnitTestSample
    {
        static public int ConstructorCount { get; set; }

        public UnitTestSample()
        {
            ConstructorCount++;
        }

        [TestMethod]
        public void TestMethod1()
        {
        }

        [TestMethod]
        public void TestMethod2()
        {
        }

        [ClassCleanup]
        static public void ClassCleanup()
        {
            Assert.AreEqual<int>(1, ConstructorCount);
        }
    }
}
`
@jinujoseph @GrantErickson @morrisjoe 

_Copied from original issue: dotnet/roslyn-project-system#1192_

**Comment by davkean** [comment]
_From @srivatsn on January 16, 2017 21:21_

@dotnet/vstest can you take a look?

**Comment by codito** [comment]
Tracked at https://github.com/Microsoft/testfx/issues/32

**Comment by davkean** [comment]
That is a non-public repro.

**Comment by AbhitejJohn** [comment]
MSTest creates a new instance of the test class for every test method by-design. On 1.1.11 Framework and Adapter both Run and Debug behave similarly. Trying to justify this behavior: This helps isolate test methods without the need of an initialize and cleanup. Changing this behavior would cause a breaking change from legacy. Hence leaving this as is.

**Comment by SoniaKaudjhis** [comment]
I have issue with [CodedUITest], How can I apply fix in my test solutions

**Comment by pi3k14** [comment]
> MSTest creates a new instance of the test class for every test method by-design. On 1.1.11 Framework and Adapter both Run and Debug behave similarly. Trying to justify this behavior: This helps isolate test methods without the need of an initialize and cleanup. Changing this behavior would cause a breaking change from legacy. Hence leaving this as is.

Could you then please remove TestInitialize and TestCleanup attributes and instructs users to use ctor/Dispose instead.
How many would you guess have mistakenly optimized their test by moving common setup to ctor to no avail?

**Comment by OlegLevitsky** [comment]
That obviously a bug. It makes necessary to create a static members to share a data between the test methods. Tests isolation is my own business

**Comment by nohwnd** [comment]
This is by design for MSTest, if you don't agree, please file an issue on https://github.com/testfx, but I don't think it will change, NUnit does not create new instance per test and it is a frequent source of complaints.

**Comment by davkean** [comment]
@nohwnd, I presume you mean https://github.com/microsoft/testfx/ which has been made public after my above comment.

**Comment by OlegLevitsky** [comment]
@nohwnd greetings, thanks for the link!
