### ISSUE TITLE
.NET Core xUnit tests have no SourceInformation

### ISSUE THREAD

**Issue by davkean** [Microsoft/vstest#361]
_From @gulbanana on November 28, 2016 6:43_

When using xUnit in VS2017, the relationship between unit tests and their source code is not discovered. This means that the Test Explorer toolwindow categorises them as "external", and features like rightclick -> run test and Live Unit Testing do not work. 

To reproduce: File -> New Project -> "xUnit Test Project (.NET Core)" or check out https://github.com/gulbanana/repro-netcore-diasym. Then, build the solution and observe the consequences in Test Explorer.

_Copied from original issue: dotnet/roslyn-project-system#826_

**Comment by davkean** [comment]
_From @gulbanana on November 28, 2016 7:0_

Potentially related fix for an older issue (this one was about discovering sourceinformation for referenced libraries in an older tooling version): https://github.com/xunit/xunit/pull/924

**Comment by davkean** [comment]
_From @srivatsn on December 13, 2016 22:7_

@codito - can you please comment on this?

**Comment by davkean** [comment]
_From @gulbanana on December 16, 2016 11:35_

I am still experiencing this problem in RC Refresh.

**Comment by davkean** [comment]
_From @codito on December 16, 2016 14:48_

@gulbanana created https://github.com/xunit/xunit/issues/1054 to track this.

**Comment by davkean** [comment]
_From @onovotny on December 20, 2016 16:18_

@srivatsn we have a fix but uncovered an issue with the TestPlatform ObjectModel lib: https://github.com/xunit/xunit/pull/1055#issuecomment-268281826. The PortableSymbolReader isn't getting data for async state machine stuff. Affects both MSTest and xUnit (and anything else that wants the data). Not sure who owns that but I'd think it should be an RC3 blocker.

**Comment by davkean** [comment]
_From @srivatsn on December 20, 2016 19:0_

Thanks Oren. @dotnet/vstest owns this code. I'll track this for RC3.

**Comment by davkean** [comment]
_From @pvlakshm on January 9, 2017 13:6_

This issue is fixed with https://github.com/dotnet/sdk/commit/e4eb65dee3fa7b4a5bf21a9b73f74171511b89f6. You can try the fix by updating Test.SDK version in csproj as shown below.

`<PackageReference Include="Microsoft.NET.Test.Sdk" Version="15.0.0-preview-20170106-08" />`

**Comment by davkean** [comment]
_From @onovotny on January 9, 2017 14:3_

@pvlakshm before the templates are cut for RC3, can the xunit runner version be updated to the compatible version, 2.2.0-beta4-build1216, or later?

/cc @bradwilson

**Comment by davkean** [comment]
_From @bradwilson on January 9, 2017 16:53_

I'm going to run beta5 builds (these should've been renamed long ago), so give me ~ 20 minutes to get you a beta5 build# for both `xunit` and `xunit.runner.visualstudio`.

**Comment by davkean** [comment]
_From @bradwilson on January 9, 2017 19:58_

I haven't provided build #s yet, because the current Visual Studio runner package is broken. Still working on a fix.

**Comment by davkean** [comment]
_From @bradwilson on January 9, 2017 22:40_

Please use:
- `xunit` version `2.2.0-beta5-build3474`
- `xunit.runner.visualstudio` version `2.2.0-beta5-build1225`

Thanks!

**Comment by davkean** [comment]
_From @srivatsn on January 9, 2017 22:43_

Tagging @dotnet/vstest.

Can someone send a PR to update the templates here - https://github.com/dotnet/sdk/tree/master/src/Templates/ProjectTemplates/CSharp/.NETCore/CSharpXUnitTest

**Comment by davkean** [comment]
_From @bradwilson on January 9, 2017 23:50_

I'll do it.

**Comment by davkean** [comment]
_From @bradwilson on January 9, 2017 23:56_

https://github.com/dotnet/sdk/pull/615

**Comment by codito** [comment]
netcoreapp1.0 support was addressed with dotnet/sdk#615
netcoreapp1.1 support is fixed with dc71b0a42dadf59b61dd7c365d75030bfd4b9610. It will be part of next insertion.
