### ISSUE TITLE
New project system does not discover net461 tests

### ISSUE THREAD

**Issue by davkean** [Microsoft/vstest#362]
_From @gulbanana on November 28, 2016 7:8_

Steps to reproduce:
1) Create a new "xUnit test project"
2) Change it to target net461, adding a RID and removing the netcore.app package
Or, check out https://github.com/gulbanana/repro-netcore-netfxtest

Build; observe that no tests are discovered. This may be due to an SDK issue - I see warnings about the testhost architecture - but `dotnet test` isn't working yet so I can't check.

_Copied from original issue: dotnet/roslyn-project-system#827_

**Comment by davkean** [comment]
_From @srivatsn on December 13, 2016 22:6_

@codito - can you comment on this?

**Comment by davkean** [comment]
_From @gulbanana on December 16, 2016 11:37_

In RC Refresh, this problem no longer applies when RID `win7-x86` is used with a single TargetFramework, but still occurs for RID `win7-x64`, which is also suggested by the IDE.

**Comment by davkean** [comment]
_From @codito on December 16, 2016 14:41_

@gulbanana for test projects targeting desktop framework, the `OutputType` property need not be set (i.e. Library by default). If the `OutputType` is library, a RID is not required.

A test project that multitargets to desktop and netcore could define the `OutputType` under a conditional. E.g. `<OutputType Condition=" '$(TargetFramework)' == 'netcoreapp1.0' ">Exe</OutputType>`

**Comment by davkean** [comment]
_From @gulbanana on December 17, 2016 2:30_

In that case the only remaining work will be to document this or add templates/gui settings for it (since i don't think anyone is going to guess that solution :)).

**Comment by davkean** [comment]
_From @codito on December 17, 2016 3:15_

Agree, we should document this or possibly get rid of this requirement.

**Comment by davkean** [comment]
_From @codito on December 21, 2016 1:41_

Update: we will fix the Microsoft.NET.Test.Sdk package to take care of conditional OutputType.

Thanks @gulbanana for reporting this. Please keep the feedback coming :)

**Comment by davkean** [comment]
_From @gulbanana on December 21, 2016 4:2_

no problem, thanks for looking into it

**Comment by davkean** [comment]
_From @codito on January 9, 2017 3:16_

As of https://github.com/dotnet/sdk/commit/e4eb65dee3fa7b4a5bf21a9b73f74171511b89f6, `Microsoft.Net.Test.Sdk` can handle `OutputType` mismatch between net4x and netcoreapp targets. `OutputType` tag need not be specified in the test project.

This fix should be available in next VS update.

**Comment by davkean** [comment]
_From @gulbanana on January 9, 2017 7:43_

cool, i'll try it out when available

**Comment by codito** [comment]
Fixed with 374328038847d091858d76ae984dcab4ae236e50.

This is available in latest dotnet-cli dev builds, should be part of next VS release.
