### ISSUE TITLE
System.IO.File in .NET Standard library fails when run in unit test

### ISSUE THREAD

**Issue by davkean** [Microsoft/vstest#363]
_From @gulbanana on December 16, 2016 11:28_

Possibly this issue should be in a vstest repository but I can't find one.
Repro: https://github.com/gulbanana/repro-netstandard-systemio

When using System.IO in a .NET Standard 1.4 class library, unit tests referencing the library fail. The error is
`Message: System.IO.FileLoadException : Could not load file or assembly 'System.IO.FileSystem, Version=4.0.1.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' or one of its dependencies. The located assembly's manifest definition does not match the assembly reference. (Exception from HRESULT: 0x80131040)`

_Copied from original issue: dotnet/roslyn-project-system#975_

**Comment by davkean** [comment]
_From @srivatsn on December 16, 2016 20:31_

@codito

**Comment by davkean** [comment]
_From @srivatsn on December 20, 2016 22:57_

@dotnet/vstest

**Comment by davkean** [comment]
_From @codito on December 21, 2016 12:50_

We're investigating this issue. As a workaround, please use `<PackageReference Include="NETStandard.Library" Version="1.6.0" />` instead of `1.6.1` in netstdlib.csproj.

**Comment by davkean** [comment]
_From @gulbanana on December 21, 2016 13:47_

I've verified that the workaround works on my system (until I want to use a nuget package which references 1.6.1 :-) )

**Comment by smadala** [comment]
There is mismatch between version number of `.nuget\packages\system.io.filesystem\4.3.0\ref\netstandard1.3\System.IO.FileSystem.dll (4.0.1)` and `.nuget\packages\system.io.filesystem\4.3.0\lib\net46\System.IO.FileSystem.dll(4.0.2)`.
There is no .nuget\packages\system.io.filesystem\4.3.0\lib\netstandard1.3\System.IO.FileSystem.dll file.

Due this mismatch System.IO.FileSystem 4.0.1 getting bind in compile time. which is not found in runtime.

This issue can be repro with simple console app referring netstdlib.

[Sln with console app - repro-netstandard-systemio.zip](https://github.com/Microsoft/vstest/files/787770/repro-netstandard-systemio.zip)

**Comment by codito** [comment]
@smadala packaging issue in corefx?

**Comment by smadala** [comment]
Could be, moving to corefx.

**Comment by smadala** [comment]
This issue was moved to dotnet/corefx#16322
