### ISSUE TITLE
ManagedNameHelper.GetManagedMethodName returns managedMethodName with unexpected single quote escape characters

### ISSUE THREAD

**Issue by shyamnamboodiripad** [microsoft/vstest#3630]
Expected:<TestClasses.IImplementation<T>.ImplMethod>
Actual:<'TestClasses.IImplementation<T>.ImplMethod'>.

**Comment by shyamnamboodiripad** [comment]
FYI @Haplois

**Comment by Evangelink** [comment]
@Haplois I believe this is fixed through PR #3704 (see these tests https://github.com/microsoft/vstest/pull/3704/files#diff-59cd2a534d129b12a0f316a0f618a8b1d2ad513bc9bd92952404385fe90af109R453). Could you confirm?
