### ISSUE TITLE
Run parameterized unit test (PUT) by specifying the test name and its parameters

### ISSUE THREAD

**Issue by yinfangchen** [microsoft/vstest#3640]
## Description
Are we able to run a specific parameterized unit test (PUT) by specifying the test name and its parameters? For instance, if I use `vstest.console.exe --ListTests`, I can see a list of PUTs with their parameters like:
```
testA(p0, p1, p2)
testA(p3, p4, p5)
testA(p6, p7, p8)
...
```

What if I only want to run `testA` with `p0, p1, p2` as its parameters? Can I achieve this by specifying the `/TestCaseFilter:FullyQualifiedName=`?

## Steps to reproduce
I have tried to specify the parameters in the test name but all failed:
`vstest.console.exe Tests.dll /TestCaseFilter:"FullyQualifiedName='testA(p0, p1, p2)'"`
`vstest.console.exe Tests.dll /TestCaseFilter:"FullyQualifiedName=&'testA(p0, p1, p2)'"`
`vstest.console.exe Tests.dll /TestCaseFilter:"FullyQualifiedName='testA%28p0%2C%20p1%2C%20p2%29'"`

## Expected behavior
Running the unit test with specific parameters.

## Actual behavior
```
An exception occurred while invoking executor 'executor://nunit3testexecutor/': Incorrect format for TestCaseFilter
Error: Invalid Condition 'FullyQualifiedName='xxx''. Specify the correct format and try again. 
Note that the incorrect format can lead to no test getting executed.

Test Run Failed.
```

## Environment
Windows
`Microsoft (R) Test Execution Command Line Tool Version 17.0.0`

**Comment by nohwnd** [comment]
We cannot fix this, the filter is implemented by the adapter, and relies on its data.
