### ISSUE TITLE
UWP Logs don't go to expected location

### ISSUE THREAD

**Issue by michael-hawker** [microsoft/vstest#3649]
## Description
UWP Test apps have a 'secret' location which is unexpected compared to when other test runs are done, for instance with the WinAppSDK. This make it harder to diagnose issues when the log can't be found.

## Steps to reproduce
> What steps can reproduce the defect?
1. Create a UWP Unit Test App
2. run `vstest.console.exe ./bin/**/projectname.build.appxrecipe /Framework:FrameworkUap10 /Diag:logoutput.txt`

## Expected behavior
> see both `logoutput.txt` for client/runner log and `logoutput.host.timestamp.txt` for host log.

## Actual behavior
> host log is output to 'unknown'/unspecified location in UWP app directory:

  C:\Users\<username>\AppData\Local\Packages\<packageid>\AC\Temp

## Environment
> Please share additional details about the test environment.

Windows 10 19044
> Operating system, Build version of vstest.console version 17.2.0-preview-20220401-07 (not sure why preview version when I have vs 17.2.0 stable installed...)

## Suggestion

Since this is due to the UWP sandbox, it'd be great for vstest.console.exe to just copy the file to the expected output path/name after test failure/exception/completion so that it can be found where specified on the commandline (Visual Studio too if custom arguments are provided to enable the diag flag).

**Comment by michael-hawker** [comment]
@nohwnd, if this is completed can you share details on which commit fixes this issue and in which release it was fixed in? Thanks!

**Comment by nohwnd** [comment]
I don't know if it was fixed, we don't own this component, it is part of VS. I asked the owner of this component Luke Westendorf and he told me I can just close this. Please discuss it with him internally if this is still an issue. And sorry for closing without explanation.
