### ISSUE TITLE
Code coverage should respect assembly level ExcludeFromCodeCoverage attribute

### ISSUE THREAD

**Issue by devlie** [microsoft/vstest#3669]
## Description
We would like to exclude our test binaries from code coverage, and the only options we have today are either decorating each and every class with `[ExcludeFromCodeCoverage]` or have crazy regexes in our `runsettings.json`. `testfx` should respect **assembly level** `ExcludeFromCodeCoverage` instead. This is related to https://github.com/microsoft/vstest/issues/1050.

## Steps to reproduce
1. Create a simple Hello World project.
2. Create a unit test project that calls Hello World and specify this in csproj:

```xml
  <ItemGroup>
        <AssemblyAttribute Include="System.Diagnostics.CodeAnalysis.ExcludeFromCodeCoverageAttribute" />
    </ItemGroup>
```
3. Run unit test with code coverage enabled.

## Expected behavior
The test binary is **not** included in coverage results.

## Actual behavior
The test binary is included in coverage results.

## Environment
>  - OS: Windows 11
>  - Build version of vstest.console: VS2022.
>  - Package version of MSTest framework and adapter: 2.2.3

**Comment by jakubch1** [comment]
This is already available in our latest package: https://dev.azure.com/dnceng/public/_artifacts/feed/test-tools/NuGet/Microsoft.CodeCoverage/overview/17.3.0-preview-20220601-01
