### ISSUE TITLE
Tests fail to run even though the right shared framework is installed.

### ISSUE THREAD

**Issue by livarcocc** [Microsoft/vstest#368]
## Description
I am running dotnet test under a project with this format:
```
<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>netcoreapp1.1</TargetFramework>
    <AssemblyName>Microsoft.AspNetCore.Mvc.Razor.ViewCompilation.Design.Test</AssemblyName>
    <PackageId>Microsoft.AspNetCore.Mvc.Razor.ViewCompilation.Design.Test</PackageId>
    <GenerateRuntimeConfigurationFiles>true</GenerateRuntimeConfigurationFiles>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\src\Microsoft.AspNetCore.Mvc.Razor.ViewCompilation.Tools\Microsoft.AspNetCore.Mvc.Razor.ViewCompilation.Tools.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.NET.Test.Sdk" Version="15.0.0-preview-20170106-08" />
    <PackageReference Include="xunit.runner.visualstudio" Version="2.2.0-beta5-build1225" />
    <PackageReference Include="xunit" Version="2.2.0-beta5-build3474" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.NETCore.App" Version="1.1.0" />
  </ItemGroup>

</Project>
```
I get this error which seems to indicate that I do not have the shared framework installed.
```
Test run for E:\git\MvcPrecompilation\test\Microsoft.AspNetCore.Mvc.Razor.ViewCompilation.Design.Test\bin\Debug\netcoreapp1.1\Microsoft.AspNetCore.Mvc.Razor.ViewCompilation.Design.Test.dll(.NETCoreApp,Version=v1.1)
Microsoft (R) Test Execution Command Line Tool Version 15.0.0.0
Copyright (c) Microsoft Corporation.  All rights reserved.

Starting test execution, please wait...
Error: Failed to initialize client proxy: could not connect to test process.
```
## Steps to reproduce
Just run dotnet test in a project with a similar csproj as the above.

## Expected behavior
Tests executed successfully.

## Actual behavior
Tests fail to start.

## Environment
.NET Command Line Tools (1.0.0-rc4-004578)

Product Information:
 Version:            1.0.0-rc4-004578
 Commit SHA-1 hash:  93a94e652b

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.14393
 OS Platform: Windows
 RID:         win10-x64

**Comment by codito** [comment]
Can you please attach `log.*txt` generated by following command: `dotnet test -d:log.txt`

The `log,txt` file also contains the full path of dotnet.exe and args used for launching test host. We can get more info we run the command directly on a shell.

**Comment by niemyjski** [comment]
I was also seeing this.

**Comment by niemyjski** [comment]
I wonder if this is related (https://github.com/dotnet/cli/issues/5548)

**Comment by natemcmaster** [comment]
[log.txt](https://github.com/Microsoft/vstest/files/778622/log.txt)

For anyone else hitting this, the error message comes more apparent if you open up log.txt and find the line that shows the arguments passed to dotnet.exe, starting with "exec --runtimeconfig..."

When you run this on command line, the actual error becomes visible. In our case, the error has been caused by issues in .NET Core 2.0 and the SDK, which are external to VSTest:

> dotnet.exe exec --runtimeconfig "C:\dev\Universe\DependencyInjection\test\Microsoft.Extensions.DependencyInjection.Tests\bin\Debug\netcoreapp1.1\Microsoft.Extensions.DependencyInjection.Tests.runtimeconfig.json" --depsfile "C:\dev\Universe\DependencyInjection\test\Microsoft.Extensions.DependencyInjection.Tests\bin\Debug\netcoreapp1.1\Microsoft.Extensions.DependencyInjection.Tests.deps.json" "C:\Users\namc\.nuget\packages\microsoft.testplatform.testhost/15.0.0-preview-20170210-02\lib/netstandard1.5/testhost.dll" --diag log.host.17-02-15_15-08-41_35809_5.txt

> Unhandled Exception: System.IO.FileLoadException: Could not load file or assembly 'System.Runtime, Version=4.2.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'. The located assembly's manifest definition does not match the assembly reference. (Exception from HRESULT: 0x80131040)
   at Microsoft.VisualStudio.TestPlatform.ObjectModel.EqtTrace.Error(String format, Object[] args)
   at Microsoft.VisualStudio.TestPlatform.TestHost.Program.Main(String[] args)
