### ISSUE TITLE
Tests not discovered before manually opening Test Explorer

### ISSUE THREAD

**Issue by tmat** [Microsoft/vstest#371]
## Steps to reproduce
- Create a new xUnit .NET Core Test project.
- Use menu Test > Run > All Tests to run all tests

## Expected behavior
Tests should be executed.

## Actual behavior
Nothing happens.

## Environment
VS D15Rel build 26116.0

Note: Using Run All command from Test Explorer works.

**Comment by codito** [comment]
@navin22 could this be related to the async package load issue? For netcore test projects, TestWindow package may not have been initialized.

**Comment by navin22** [comment]
I am able to reproduce this issue at my end.
Will look into it.

**Comment by sbaid** [comment]
It is issue with test window package auto load which is not triggered on creation of .NET core UT project creation if test window is not pinned. It is triggered when Test>Run>All Test is clicked first time. Next click of the same command works. secondly - right click context menu in the code editor also shows run test, debug tests menu items after test window package is loaded.

once a test discovery happens for a test project - thereafter this issue does not show up again for the same project later.

**Comment by Faizan2304** [comment]
@navin22 Is there is any TODO on us for this bug?

**Comment by navin22** [comment]
Now we are treating the .Net core UT projects also as test project from 15.3. So this will be fixed from VS 15.3.
