### ISSUE TITLE
Truncated or corrupted coverage data leading to many broken test runs

### ISSUE THREAD

**Issue by AArnott** [microsoft/vstest#3724]
## Description

I get a surprisingly high number of test runs that fail because of [this error](https://dev.azure.com/devdiv/DevDiv/_build/results?buildId=6255223&view=logs&j=0bc77094-9fcd-5c38-f6e4-27d2ae131589&t=f29c65c5-111e-5e1e-605e-ff26e95de907&l=58), after an otherwise successful test run:

```
Calculating coverage result...
D:\a\_work\_temp\.nuget\packages\coverlet.msbuild\3.1.2\build\coverlet.msbuild.targets(71,5): error : Unable to read beyond the end of the stream. [D:\a\_work\1\s\test\Microsoft.VisualStudio.Composition.Analyzers.Tests\Microsoft.VisualStudio.Composition.Analyzers.Tests.csproj]
D:\a\_work\_temp\.nuget\packages\coverlet.msbuild\3.1.2\build\coverlet.msbuild.targets(71,5): error :    at System.IO.BinaryReader.InternalRead(Int32 numBytes) [D:\a\_work\1\s\test\Microsoft.VisualStudio.Composition.Analyzers.Tests\Microsoft.VisualStudio.Composition.Analyzers.Tests.csproj]
D:\a\_work\_temp\.nuget\packages\coverlet.msbuild\3.1.2\build\coverlet.msbuild.targets(71,5): error :    at Coverlet.Core.Coverage.CalculateCoverage() in /_/src/coverlet.core/Coverage.cs:line 414 [D:\a\_work\1\s\test\Microsoft.VisualStudio.Composition.Analyzers.Tests\Microsoft.VisualStudio.Composition.Analyzers.Tests.csproj]
D:\a\_work\_temp\.nuget\packages\coverlet.msbuild\3.1.2\build\coverlet.msbuild.targets(71,5): error :    at Coverlet.Core.Coverage.GetCoverageResult() in /_/src/coverlet.core/Coverage.cs:line 161 [D:\a\_work\1\s\test\Microsoft.VisualStudio.Composition.Analyzers.Tests\Microsoft.VisualStudio.Composition.Analyzers.Tests.csproj]
D:\a\_work\_temp\.nuget\packages\coverlet.msbuild\3.1.2\build\coverlet.msbuild.targets(71,5): error :    at Coverlet.MSbuild.Tasks.CoverageResultTask.Execute() in /_/src/coverlet.msbuild.tasks/CoverageResultTask.cs:line 83 [D:\a\_work\1\s\test\Microsoft.VisualStudio.Composition.Analyzers.Tests\Microsoft.VisualStudio.Composition.Analyzers.Tests.csproj]
```

Any idea why? Could it be that the process running the tests terminates before coverage data has been flushed to disk?

## Diagnostic logs

[testResults-Windows.zip](https://github.com/microsoft/vstest/files/8856327/testResults-Windows.zip)

## Environment

Azure Pipelines

**Comment by MarcoRossignoli** [comment]
It's a known issue of coverlet that relies on process exits to save probes. You should move to the datacollector integration https://github.com/coverlet-coverage/coverlet/blob/master/Documentation/KnownIssues.md#vstest-stops-process-execution-early

**Comment by MarcoRossignoli** [comment]
We added a workaround a pair of months ago https://github.com/microsoft/vstest/blob/main/src/Microsoft.TestPlatform.CrossPlatEngine/Client/ProxyOperationManager.cs#L311 where you can setup the `VSTEST_TESTHOST_SHUTDOWN_TIMEOUT` environment variable to extend the defaul 100ms timeout. 
@nohwnd do you remember know in what version was been shipped?

**Comment by AArnott** [comment]
Thanks, @MarcoRossignoli. Your first link ultimately leads me to https://github.com/coverlet-coverage/coverlet#vstest-integration-preferred-due-to-known-issue-supports-only-net-core-application, which says it only works on .NET Core. I need to test and collect code coverage for .NET Framework too. So should I use the options in your second paragraph instead? I'm thinking adding `--collect "Code Coverage;Format=cobertura"` to my existing `dotnet test` command will be super simple. 

Are there any other changes I should make?
My test projects typically contain:
```xml
    <PackageReference Include="coverlet.msbuild" Version="3.1.2" />
    <PackageReference Include="Microsoft.NET.Test.Sdk" Version="17.2.0" />
</ItemGroup>
<PropertyGroup>
    <CoverletOutputFormat>cobertura</CoverletOutputFormat>
    <Exclude>[xunit.*]*</Exclude>
    <!-- Ensure we preserve each coverlet output file per target framework: https://github.com/tonerdo/coverlet/issues/177 -->
    <CoverletOutput>$(OutputPath)/</CoverletOutput>
```

**Comment by MarcoRossignoli** [comment]
> which says it only works on .NET Core. I need to test and collect code coverage for .NET Framework too. 

Sorry it's not up to date...it's working also with .NET Framework(we moved collector to netstandard2.0)

The setup for collector is here https://github.com/coverlet-coverage/coverlet/blob/master/Documentation/VSTestIntegration.md you can remove `coverlet.msbuild` that is used only to inject MSBuild Tasks.

> And I spawn dotnet test with the -p:CollectCoverage=true switch. Should I continue to do that?

Nope with collector you should use runsettings https://github.com/coverlet-coverage/coverlet/blob/master/Documentation/VSTestIntegration.md#coverlet-options-supported-by-vstest-integration

> I'm thinking adding --collect "Code Coverage;Format=cobertura" to my existing dotnet test command will be super simple.

If you move to dotnet-coverage the settings are described here https://docs.microsoft.com/en-us/dotnet/core/additional-tools/dotnet-coverage#settings

**Comment by AArnott** [comment]
`dotnet-coverage merge` is buggy. It drops covered lines that are in at least some of the input reports. Where should I file that bug?

**Comment by AArnott** [comment]
I can't find the repo with the dotnet-coverage tool source code in it, but I see plenty of issues with that tool filed in this repo, so I filed https://github.com/microsoft/vstest/issues/3732.

**Comment by MarcoRossignoli** [comment]
I'm going to close this one because the correct issue for the merge is already opened.
