### ISSUE TITLE
Source info not available for desktop projects if it created from netcore template

### ISSUE THREAD

**Issue by smadala** [Microsoft/vstest#373]
## Description
> Source info not available for tests.

## Steps to reproduce
> Create netcore unit test project from VS templates
> Change `TargetFramework` from netcoreapp1.0 to net46 in csproj file.

## Expected behavior
> Source info should be available.

## Actual behavior
> Source info not available.

## Workaround 
> Add following PropertyGroup to test csproj file.
```
<PropertyGroup>
    <DebugType Condition="'$(TargetFramework)' != '' AND !$(TargetFramework.StartsWith('netcoreapp'))">Full</DebugType>
</PropertyGroup>
```

**Comment by codito** [comment]
This is happening because there's an [assumption](https://github.com/Microsoft/vstest/blob/master/src/Microsoft.TestPlatform.ObjectModel/Navigation/DiaSession.cs#L50) that projects that target desktop can only build with Full PDBs.

**Comment by smadala** [comment]
Add following PropertyGroup to test csproj file.
```
<PropertyGroup>
    <DebugType Condition="'$(TargetFramework)' != '' AND !$(TargetFramework.StartsWith('netcoreapp'))">Full</DebugType>
</PropertyGroup>
```

**Comment by Faizan2304** [comment]
This has been fixed with https://github.com/Microsoft/vstest/pull/528

**Comment by tmat** [comment]
Reopening this issue. The problem has not been fixed fully. 

The SDK still has the following lines, which break debugging tests built with embedded PDBs:

```xml
  <!--
     In IDE scenario for full CLR projects default test platform is v1, which expects full pdbs for source information.
     This can be removed once TPv2 is default for full CLR. Related issue https://github.com/Microsoft/vstest/issues/373.
   -->
  <PropertyGroup>
    <DebugType Condition="'$(TargetFrameworkIdentifier)' != '.NETCoreApp'">Full</DebugType>
  </PropertyGroup>
```

Note that this actually completely breaks these tests -- the targets file sets ```DebugType``` after it has been used by the SDK to determine whether symbols need to be copied to the output directory. If the project sets ```DebugType``` to ```embedded``` the SDK determines that no PDBs need to be copied but then the test SDK overwrites ```DebugType``` value which makes the compiler to produce Windows PDB. This PDB is not copied to the output directory. XUnit will not find it there when displaying stack traces so the stack traces will miss line and file information.

**Comment by johnwc** [comment]
This may still be an issue. I have the latest VS 2019 installed. Created two .net standard libraries targeting 2.0/2.1. The created a xUnit test project, the only code coverage that was appearing was in the unit test project. I had to add `DebugType` like mentioned above in order for the other two libraries showed up in code coverage.
