### ISSUE TITLE
First class support for GitHub Actions

### ISSUE THREAD

**Issue by adamralph** [microsoft/vstest#3730]
A [third-party logger](https://github.com/Tyrrrz/GitHubActionsTestLogger) exists for this purpose:

> Custom logger for `dotnet test` that integrates with GitHub Actions.
> When using this logger, failed tests are listed in job annotations and highlighted in code diffs.
> Additionally, this logger also generates a job summary that contains detailed information about the executed test run.

This feels like something that shouldn't require a third-party package, and should instead be built into `dotnet test`.

**Comment by nohwnd** [comment]
There are great tools, as the one mentioned here. At the moment we don't have any plans to create our own for vstest.
