### ISSUE TITLE
`dotnet-coverage merge` drops covered lines from merged report

### ISSUE THREAD

**Issue by AArnott** [microsoft/vstest#3732]
## Description

The `merge` command drops coverage data for some lines.

## Steps to reproduce

I have multiple cobertura coverage reports that I want to use `dotnet-coverage merge` to merge into one. The reports are regarding the same files, but are from unique runs that cover different lines in those files. 

Consider these coverage files: 
[TestResults.zip](https://github.com/microsoft/vstest/files/8865454/TestResults.zip)

```
dotnet-coverage TestResults\*xml -r -o merged.cobertura.xml -f cobertura
```

## Expected behavior

I expect the merged report to represent the union of all covered lines.
In particular, the merged product should report that the `{reporoot}\test\Library.Tests\CalculatorTests.cs` file's lines 18 **and** 20 were covered. 
Line 18 was covered in VssAdministrator_fv-az333-29_2022-06-08.22_25_24.cobertura.xml
Line 20 was covered by VssAdministrator_fv-az333-29_2022-06-08.22_25_20.cobertura.xml

I get the expected result when merging with the `dotnet-reportgenerator-globaltool` dotnet CLI tool.

## Actual behavior

The merged.cobertura.xml file reports only Line 20 was covered. Line 18 was missing:

```xml
          <lines>
            <line number="9" hits="1" branch="False" />
            <line number="11" hits="1" branch="False" />
            <line number="20" hits="1" branch="False" />
            <line number="22" hits="1" branch="False" />
          </lines>
```

## Environment

The original cobertura files were taken from the `coverageResult-*` artifacts in [this pipeline](https://dev.azure.com/andrewarnott/OSS/_build/results?buildId=6641&view=artifacts&pathAsName=false&type=publishedArtifacts). 
I'm using the dotnet-coverage 17.3.2 tool.

**Comment by fhnaseer** [comment]
@AArnott Line 18 is not merged because there is mismatch of line numbers in both files.
File1:
``` 
           <method line-rate="1" branch-rate="1" complexity="1" name="AddOrSubtract" signature="()">
              <lines>
                <line number="20" hits="1" branch="False" />
                <line number="22" hits="0" branch="False" />
              </lines>
            </method>
```
File2:
```
            <method line-rate="1" branch-rate="1" complexity="1" name="AddOrSubtract" signature="()">
              <lines>
                <line number="18" hits="1" branch="False" />
                <line number="22" hits="1" branch="False" />
              </lines>
            </method>
```
`dotnet-coverage` will merge result only if line number is matching in both files. In the above case, line number 18 and 20 will not be merged (depending on file order one will show in final result) and line number 22 will be merged with result 1.
Maybe `reportgenerator` is not comparing line number before merging and only checks if both methods have equal line count, then merge `first.lines[i]` with `second.lines[i]`.

Can you please try to run `reportgenerator` with following file combinations? And check results?
`reportgenerator "-reports:first.cobertura.xml;second.cobertura.xml" "-targetdir:coveragereport" -reporttypes:Cobertura`
`reportgenerator "-reports:second.cobertura.xml;first.cobertura.xml" "-targetdir:coveragereport" -reporttypes:Cobertura`

**Comment by fhnaseer** [comment]
If you open merged report (from reportgenerator) in visual studio, does it show both lines as covered?

**Comment by AArnott** [comment]
An interesting question. First off, my pipeline doesn't upload the merged result as anything besides html, so there's nothing to open in VS. But when I repeat the steps locally and use `reportgenerator` to merge the result, and pick xml as the output type, VS _crashes_ when I import the resulting xml files. It has no problem importing the original test output with just one run in it. I'll have to file a bug on the crash at least.

It would be great if I could start producing any kind of merged result that VS could then load up.

**Comment by AArnott** [comment]
When I use `-reporttypes:Cobertura` instead of `-reporttypes:xml`, VS can load it, and _shows all lines as covered_, as I would want. But the Cobertura.xml file _doesn't_ define the method twice. It actually merges all the lines into one 'method' within the file, so I guess it's no surprise that VS shows all lines as covered.

```xml
<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE coverage SYSTEM "http://cobertura.sourceforge.net/xml/coverage-04.dtd">
<coverage line-rate="1" branch-rate="1" lines-covered="9" lines-valid="9" branches-covered="0" branches-valid="0" complexity="4" version="0" timestamp="1655277732">
  <sources />
  <packages>
    <package name="Library" line-rate="1" branch-rate="1" complexity="2">
      <classes>
        <class name="Library.Calculator" filename="C:\git\Lib.Template\src\Library\Calculator.cs" line-rate="1" branch-rate="1" complexity="2">
          <methods>
            <method name="Add" signature="(...)" line-rate="1" branch-rate="1" complexity="1">
              <lines>
                <line number="17" hits="1" branch="false" />
              </lines>
            </method>
            <method name="Subtract" signature="(...)" line-rate="1" branch-rate="1" complexity="1">
              <lines>
                <line number="25" hits="2" branch="false" />
              </lines>
            </method>
          </methods>
          <lines>
            <line number="17" hits="1" branch="false" />
            <line number="25" hits="2" branch="false" />
          </lines>
        </class>
      </classes>
    </package>
    <package name="Library.Tests" line-rate="1" branch-rate="1" complexity="2">
      <classes>
        <class name=".CalculatorTests" filename="C:\git\Lib.Template\test\Library.Tests\CalculatorTests.cs" line-rate="1" branch-rate="1" complexity="2">
          <methods>
            <method name=".ctor" signature="()" line-rate="1" branch-rate="1" complexity="1">
              <lines>
                <line number="9" hits="3" branch="false" />
                <line number="10" hits="3" branch="false" />
                <line number="11" hits="3" branch="false" />
              </lines>
            </method>
            <method name="AddOrSubtract" signature="()" line-rate="1" branch-rate="1" complexity="1">
              <lines>
                <line number="15" hits="3" branch="false" />
                <line number="18" hits="1" branch="false" />
                <line number="20" hits="2" branch="false" />
                <line number="22" hits="3" branch="false" />
              </lines>
            </method>
          </methods>
          <lines>
            <line number="9" hits="3" branch="false" />
            <line number="10" hits="3" branch="false" />
            <line number="11" hits="3" branch="false" />
            <line number="15" hits="3" branch="false" />
            <line number="18" hits="1" branch="false" />
            <line number="20" hits="2" branch="false" />
            <line number="22" hits="3" branch="false" />
          </lines>
        </class>
      </classes>
    </package>
  </packages>
</coverage>
```

**Comment by fhnaseer** [comment]
`-reporttypes:xml` is some other format which we don't support. I tried opening a cobertura file with duplicate methods, but VS showed only one method.

**Comment by fhnaseer** [comment]
> reportgenerator doesn't merge the _methods_. It merges the file and lists the two `AddOrSubtract` methods separately. But as a result, a code coverage report will color in both lines and report 100% code coverage. Ideally I'd like it to merge the method nodes too, so the report doesn't show the method twice in the methods listing.

> When I use `-reporttypes:Cobertura` instead of `-reporttypes:xml`, VS can load it, and _shows all lines as covered_, as I would want. But the Cobertura.xml file _doesn't_ define the method twice. It actually merges all the lines into one 'method' within the file, so I guess it's no surprise that VS shows all lines as covered.

So reportgenerator has different behaviors? In ADO it adds duplicate methods, but CLI merges into one single method?

**Comment by AArnott** [comment]
In AzP, the same version of the tool produces a different result (two AddOrSubtract methods). But in AzP the merged product's inputs come from 9 files (3 per OS) whereas in my local test it was just 3 inputs from Windows. I'll drill more into that to understand better.

But at least I can tell you now what VS's behavior is when a method appears twice: it only shows one of them. Here is the merged product as it is produced within AzP:

```xml
    <package name="Library.Tests" line-rate="1" branch-rate="1" complexity="3">
      <classes>
        <class name=".CalculatorTests" filename="D:\a\1\s\test\Library.Tests\CalculatorTests.cs" line-rate="1" branch-rate="1" complexity="3">
          <methods>
            <method name=".ctor" signature="()" line-rate="1" branch-rate="1" complexity="1">
              <lines>
                <line number="9" hits="5" branch="false" />
                <line number="11" hits="5" branch="false" />
              </lines>
            </method>
            <method name="AddOrSubtract" signature="()" line-rate="1" branch-rate="1" complexity="1">
              <lines>
                <line number="20" hits="3" branch="false" />
                <line number="22" hits="5" branch="false" />
              </lines>
            </method>
            <method name="AddOrSubtract" signature="()" line-rate="1" branch-rate="1" complexity="1">
              <lines>
                <line number="18" hits="2" branch="false" />
                <line number="20" hits="3" branch="false" />
                <line number="22" hits="5" branch="false" />
              </lines>
            </method>
          </methods>
          <lines>
            <line number="9" hits="5" branch="false" />
            <line number="11" hits="5" branch="false" />
            <line number="18" hits="2" branch="false" />
            <line number="20" hits="3" branch="false" />
            <line number="22" hits="5" branch="false" />
          </lines>
        </class>
      </classes>
    </package>
```

And here is how VS renders that when I download that file:
![image](https://user-images.githubusercontent.com/3548/173850277-9f3b2424-b172-4617-85a6-618e20c8bd1b.png)

**Comment by AArnott** [comment]
The difference in AzP producing *two* methods in the merged report and my local run merging into just one method is because of the configuration. When I merge reports from a Release build, I get two methods, whereas reports based on a Debug build produce just one method. I haven't figured out why yet.

**Comment by MarcoRossignoli** [comment]
@AArnott you can try with the new version https://www.nuget.org/packages/dotnet-coverage/17.4.1

**Comment by AArnott** [comment]
I tested with 17.4.3 and it includes the union of covered lines from all reports. Thank you.
