### ISSUE TITLE
Plan to open-source Microsoft.VisualStudio.QualityTools.UnitTestFramework ?

### ISSUE THREAD

**Issue by hickford** [Microsoft/vstest#374]
Hi. Do Microsoft plan to open source Microsoft.VisualStudio.QualityTools.UnitTestFramework , either here or elsewhere?

This assembly defines the Assert and CollectionAssert classes https://msdn.microsoft.com/en-us/library/microsoft.visualstudio.testtools.unittesting.assert.aspx

**Comment by codito** [comment]
@hickford yes, it is planned.

**Comment by codito** [comment]
MSTest framework is now open source at https://github.com/microsoft/testfx.

**Comment by hickford** [comment]
Great!
