### ISSUE TITLE
VSTest v17.2.0 on macOS does not respect DOTNET_CLI_UI_LANGUAGE = 'zh-TW'.

### ISSUE THREAD

**Issue by ShikiSuen** [microsoft/vstest#3785]
When I tried adding the nushell environment variable `DOTNET_CLI_UI_LANGUAGE = 'zh-TW', the dotnet CLI successfully turned into Traditional Chinese. However, VSTest doesn't, and is in Simplified Chinese.

VSTest version: 17.2.0.

It is obvious to see DOTNET_CLI_UI_LANGUAGE malfunctions since the highlighted line:
(Yellow texts are my Console.Writeline-generated texts which are not related to this issue.)
<img width="880" alt="image" src="https://user-images.githubusercontent.com/3164826/174531882-d922b6d2-25c1-42f9-96f8-04d34dcc63c5.png">

**Comment by ShikiSuen** [comment]
Related issue: https://github.com/microsoft/vstest/issues/821

**Comment by Evangelink** [comment]
@ShikiSuen Sorry I am not super familiar with Chinese. Are you saying it's falling back to `zh-Hant` instead of `zh-Hans`?

**Comment by ShikiSuen** [comment]
@Evangelink It's showing zh-Hans in lieu of the specified zh-Hant.
I am not sure whether this is a fallback behavior or another type of mistake.

**Comment by Evangelink** [comment]
I will have a look, thanks for the clarification!

**Comment by ShikiSuen** [comment]
@Evangelink It looks like the issue has gone.

**Comment by ShikiSuen** [comment]
Thanks for the fix.
