### ISSUE TITLE
Unit test project templates should set IsPackable as false

### ISSUE THREAD

**Issue by codito** [Microsoft/vstest#380]
Setting `IsPackable=false` should disable the Pack property pages.

See https://github.com/NuGet/Home/issues/4323 for more details.

**Comment by codito** [comment]
This could be added in https://github.com/Microsoft/vstest/blob/master/src/package/nuspec/Microsoft.NET.Test.Sdk.props.

For validation, replace `https://github.com/Microsoft/vstest/blob/master/src/package/nuspec/Microsoft.NET.Test.Sdk.props` with modified one and verify if package property pages don't show up in IDE and `dotnet pack` should be no-op from the dotnet cli.

**Comment by tintoy** [comment]
Just FYI, some people do still want to be able to pack their test projects:

https://github.com/dotnet/templating/issues/376#issuecomment-282531196

As long as it can be overridden I imagine they're fine with it.

**Comment by tintoy** [comment]
Oops, just saw your other reply, never mind :)

**Comment by snkota** [comment]
This is being tracked external to this repo here:
https://developercommunity.visualstudio.com/content/problem/145934/unit-test-project-templates-should-set-ispackable.html
