### ISSUE TITLE
I wanted to open the solution in VS 2013 or VS 2015 and I got long list of errors.

### ISSUE THREAD

**Issue by SayusiAndo** [Microsoft/vstest#382]
## Description
> Describe the issue you've observed

long list of errors when opening solution in VS 2013 or VS 2015
I assume I did something wrong

## Steps to reproduce
> What steps can reproduce the defect?
> Please share the setup, commandline for vstest.console, sample project, target
> framework etc.

git clone the repository
open the solution in VS 2013 or VS 2015

## Expected behavior
> Share the expected output

Open the solution without problem

## Actual behavior
> What is the behavior observed?

c:\PRIVAT\github.com\vstest\src\Microsoft.TestPlatform.CoreUtilities\Microsoft.TestPlatform.CoreUtilities.csproj : error  : The attribute "Update" in element <Compile> is unrecognized.  c:\PRIVAT\github.com\vstest\src\Microsoft.TestPlatform.CoreUtilities\Microsoft.TestPlatform.CoreUtilities.csproj

c:\PRIVAT\github.com\vstest\test\Microsoft.TestPlatform.CoreUtilities.UnitTests\Microsoft.TestPlatform.CoreUtilities.UnitTests.csproj : error  : The default XML namespace of the project must be the MSBuild XML namespace. If the project is authored in the MSBuild 2003 format, please add xmlns="http://schemas.microsoft.com/developer/msbuild/2003" to the <Project> element. If the project has been authored in the old 1.0 or 1.2 format, please convert it to MSBuild 2003 format.  c:\PRIVAT\github.com\vstest\test\Microsoft.TestPlatform.CoreUtilities.UnitTests\Microsoft.TestPlatform.CoreUtilities.UnitTests.csproj

c:\PRIVAT\github.com\vstest\src\datacollector\datacollector.csproj : error  : The default XML namespace of the project must be the MSBuild XML namespace. If the project is authored in the MSBuild 2003 format, please add xmlns="http://schemas.microsoft.com/developer/msbuild/2003" to the <Project> element. If the project has been authored in the old 1.0 or 1.2 format, please convert it to MSBuild 2003 format.  c:\PRIVAT\github.com\vstest\src\datacollector\datacollector.csproj

c:\PRIVAT\github.com\vstest\src\datacollector.x86\datacollector.x86.csproj : error  : The default XML namespace of the project must be the MSBuild XML namespace. If the project is authored in the MSBuild 2003 format, please add xmlns="http://schemas.microsoft.com/developer/msbuild/2003" to the <Project> element. If the project has been authored in the old 1.0 or 1.2 format, please convert it to MSBuild 2003 format.  c:\PRIVAT\github.com\vstest\src\datacollector.x86\datacollector.x86.csproj

c:\PRIVAT\github.com\vstest\src\Microsoft.TestPlatform.Build\Microsoft.TestPlatform.Build.csproj : error  : The default XML namespace of the project must be the MSBuild XML namespace. If the project is authored in the MSBuild 2003 format, please add xmlns="http://schemas.microsoft.com/developer/msbuild/2003" to the <Project> element. If the project has been authored in the old 1.0 or 1.2 format, please convert it to MSBuild 2003 format.  c:\PRIVAT\github.com\vstest\src\Microsoft.TestPlatform.Build\Microsoft.TestPlatform.Build.csproj

c:\PRIVAT\github.com\vstest\src\Microsoft.TestPlatform.Client\Microsoft.TestPlatform.Client.csproj : error  : The default XML namespace of the project must be the MSBuild XML namespace. If the project is authored in the MSBuild 2003 format, please add xmlns="http://schemas.microsoft.com/developer/msbuild/2003" to the <Project> element. If the project has been authored in the old 1.0 or 1.2 format, please convert it to MSBuild 2003 format.  c:\PRIVAT\github.com\vstest\src\Microsoft.TestPlatform.Client\Microsoft.TestPlatform.Client.csproj

c:\PRIVAT\github.com\vstest\src\Microsoft.TestPlatform.Common\Microsoft.TestPlatform.Common.csproj : error  : The default XML namespace of the project must be the MSBuild XML namespace. If the project is authored in the MSBuild 2003 format, please add xmlns="http://schemas.microsoft.com/developer/msbuild/2003" to the <Project> element. If the project has been authored in the old 1.0 or 1.2 format, please convert it to MSBuild 2003 format.  c:\PRIVAT\github.com\vstest\src\Microsoft.TestPlatform.Common\Microsoft.TestPlatform.Common.csproj

c:\PRIVAT\github.com\vstest\src\Microsoft.TestPlatform.CommunicationUtilities\Microsoft.TestPlatform.CommunicationUtilities.csproj : error  : The default XML namespace of the project must be the MSBuild XML namespace. If the project is authored in the MSBuild 2003 format, please add xmlns="http://schemas.microsoft.com/developer/msbuild/2003" to the <Project> element. If the project has been authored in the old 1.0 or 1.2 format, please convert it to MSBuild 2003 format.  c:\PRIVAT\github.com\vstest\src\Microsoft.TestPlatform.CommunicationUtilities\Microsoft.TestPlatform.CommunicationUtilities.csproj

c:\PRIVAT\github.com\vstest\src\Microsoft.TestPlatform.CrossPlatEngine\Microsoft.TestPlatform.CrossPlatEngine.csproj : error  : The project file could not be loaded. There is no Unicode byte order mark. Cannot switch to Unicode.  c:\PRIVAT\github.com\vstest\src\Microsoft.TestPlatform.CrossPlatEngine\Microsoft.TestPlatform.CrossPlatEngine.csproj

c:\PRIVAT\github.com\vstest\src\Microsoft.TestPlatform.ObjectModel\Microsoft.TestPlatform.ObjectModel.csproj : error  : The default XML namespace of the project must be the MSBuild XML namespace. If the project is authored in the MSBuild 2003 format, please add xmlns="http://schemas.microsoft.com/developer/msbuild/2003" to the <Project> element. If the project has been authored in the old 1.0 or 1.2 format, please convert it to MSBuild 2003 format.  c:\PRIVAT\github.com\vstest\src\Microsoft.TestPlatform.ObjectModel\Microsoft.TestPlatform.ObjectModel.csproj

c:\PRIVAT\github.com\vstest\src\Microsoft.TestPlatform.Utilities\Microsoft.TestPlatform.Utilities.csproj : error  : The default XML namespace of the project must be the MSBuild XML namespace. If the project is authored in the MSBuild 2003 format, please add xmlns="http://schemas.microsoft.com/developer/msbuild/2003" to the <Project> element. If the project has been authored in the old 1.0 or 1.2 format, please convert it to MSBuild 2003 format.  c:\PRIVAT\github.com\vstest\src\Microsoft.TestPlatform.Utilities\Microsoft.TestPlatform.Utilities.csproj

c:\PRIVAT\github.com\vstest\src\Microsoft.TestPlatform.Extensions.TrxLogger\Microsoft.TestPlatform.Extensions.TrxLogger.csproj : error  : The project file could not be loaded. There is no Unicode byte order mark. Cannot switch to Unicode.  c:\PRIVAT\github.com\vstest\src\Microsoft.TestPlatform.Extensions.TrxLogger\Microsoft.TestPlatform.Extensions.TrxLogger.csproj

c:\PRIVAT\github.com\vstest\src\Microsoft.TestPlatform.VsTestConsole.TranslationLayer\Microsoft.TestPlatform.VsTestConsole.TranslationLayer.csproj : error  : The default XML namespace of the project must be the MSBuild XML namespace. If the project is authored in the MSBuild 2003 format, please add xmlns="http://schemas.microsoft.com/developer/msbuild/2003" to the <Project> element. If the project has been authored in the old 1.0 or 1.2 format, please convert it to MSBuild 2003 format.  c:\PRIVAT\github.com\vstest\src\Microsoft.TestPlatform.VsTestConsole.TranslationLayer\Microsoft.TestPlatform.VsTestConsole.TranslationLayer.csproj

c:\PRIVAT\github.com\vstest\src\testhost\testhost.csproj : error  : The default XML namespace of the project must be the MSBuild XML namespace. If the project is authored in the MSBuild 2003 format, please add xmlns="http://schemas.microsoft.com/developer/msbuild/2003" to the <Project> element. If the project has been authored in the old 1.0 or 1.2 format, please convert it to MSBuild 2003 format.  c:\PRIVAT\github.com\vstest\src\testhost\testhost.csproj

c:\PRIVAT\github.com\vstest\src\testhost.x86\testhost.x86.csproj : error  : The default XML namespace of the project must be the MSBuild XML namespace. If the project is authored in the MSBuild 2003 format, please add xmlns="http://schemas.microsoft.com/developer/msbuild/2003" to the <Project> element. If the project has been authored in the old 1.0 or 1.2 format, please convert it to MSBuild 2003 format.  c:\PRIVAT\github.com\vstest\src\testhost.x86\testhost.x86.csproj

c:\PRIVAT\github.com\vstest\src\vstest.console\vstest.console.csproj : error  : The default XML namespace of the project must be the MSBuild XML namespace. If the project is authored in the MSBuild 2003 format, please add xmlns="http://schemas.microsoft.com/developer/msbuild/2003" to the <Project> element. If the project has been authored in the old 1.0 or 1.2 format, please convert it to MSBuild 2003 format.  c:\PRIVAT\github.com\vstest\src\vstest.console\vstest.console.csproj

c:\PRIVAT\github.com\vstest\src\Microsoft.TestPlatform.VSIXCreator\Microsoft.TestPlatform.VSIXCreator.csproj : error  : The default XML namespace of the project must be the MSBuild XML namespace. If the project is authored in the MSBuild 2003 format, please add xmlns="http://schemas.microsoft.com/developer/msbuild/2003" to the <Project> element. If the project has been authored in the old 1.0 or 1.2 format, please convert it to MSBuild 2003 format.  c:\PRIVAT\github.com\vstest\src\Microsoft.TestPlatform.VSIXCreator\Microsoft.TestPlatform.VSIXCreator.csproj

c:\PRIVAT\github.com\vstest\test\datacollector.x86.UnitTests\datacollector.x86.UnitTests.csproj : error  : The default XML namespace of the project must be the MSBuild XML namespace. If the project is authored in the MSBuild 2003 format, please add xmlns="http://schemas.microsoft.com/developer/msbuild/2003" to the <Project> element. If the project has been authored in the old 1.0 or 1.2 format, please convert it to MSBuild 2003 format.  c:\PRIVAT\github.com\vstest\test\datacollector.x86.UnitTests\datacollector.x86.UnitTests.csproj

c:\PRIVAT\github.com\vstest\test\Microsoft.TestPlatform.Client.UnitTests\Microsoft.TestPlatform.Client.UnitTests.csproj : error  : The default XML namespace of the project must be the MSBuild XML namespace. If the project is authored in the MSBuild 2003 format, please add xmlns="http://schemas.microsoft.com/developer/msbuild/2003" to the <Project> element. If the project has been authored in the old 1.0 or 1.2 format, please convert it to MSBuild 2003 format.  c:\PRIVAT\github.com\vstest\test\Microsoft.TestPlatform.Client.UnitTests\Microsoft.TestPlatform.Client.UnitTests.csproj

c:\PRIVAT\github.com\vstest\test\Microsoft.TestPlatform.Common.UnitTests\Microsoft.TestPlatform.Common.UnitTests.csproj : error  : The default XML namespace of the project must be the MSBuild XML namespace. If the project is authored in the MSBuild 2003 format, please add xmlns="http://schemas.microsoft.com/developer/msbuild/2003" to the <Project> element. If the project has been authored in the old 1.0 or 1.2 format, please convert it to MSBuild 2003 format.  c:\PRIVAT\github.com\vstest\test\Microsoft.TestPlatform.Common.UnitTests\Microsoft.TestPlatform.Common.UnitTests.csproj

c:\PRIVAT\github.com\vstest\test\Microsoft.TestPlatform.CommunicationUtilities.UnitTests\Microsoft.TestPlatform.CommunicationUtilities.UnitTests.csproj : error  : The default XML namespace of the project must be the MSBuild XML namespace. If the project is authored in the MSBuild 2003 format, please add xmlns="http://schemas.microsoft.com/developer/msbuild/2003" to the <Project> element. If the project has been authored in the old 1.0 or 1.2 format, please convert it to MSBuild 2003 format.  c:\PRIVAT\github.com\vstest\test\Microsoft.TestPlatform.CommunicationUtilities.UnitTests\Microsoft.TestPlatform.CommunicationUtilities.UnitTests.csproj

c:\PRIVAT\github.com\vstest\test\Microsoft.TestPlatform.CrossPlatEngine.UnitTests\Microsoft.TestPlatform.CrossPlatEngine.UnitTests.csproj : error  : The default XML namespace of the project must be the MSBuild XML namespace. If the project is authored in the MSBuild 2003 format, please add xmlns="http://schemas.microsoft.com/developer/msbuild/2003" to the <Project> element. If the project has been authored in the old 1.0 or 1.2 format, please convert it to MSBuild 2003 format.  c:\PRIVAT\github.com\vstest\test\Microsoft.TestPlatform.CrossPlatEngine.UnitTests\Microsoft.TestPlatform.CrossPlatEngine.UnitTests.csproj

c:\PRIVAT\github.com\vstest\test\Microsoft.TestPlatform.ObjectModel.UnitTests\Microsoft.TestPlatform.ObjectModel.UnitTests.csproj : error  : The default XML namespace of the project must be the MSBuild XML namespace. If the project is authored in the MSBuild 2003 format, please add xmlns="http://schemas.microsoft.com/developer/msbuild/2003" to the <Project> element. If the project has been authored in the old 1.0 or 1.2 format, please convert it to MSBuild 2003 format.  c:\PRIVAT\github.com\vstest\test\Microsoft.TestPlatform.ObjectModel.UnitTests\Microsoft.TestPlatform.ObjectModel.UnitTests.csproj

c:\PRIVAT\github.com\vstest\test\Microsoft.TestPlatform.TestUtilities\Microsoft.TestPlatform.TestUtilities.csproj : error  : The project file could not be loaded. There is no Unicode byte order mark. Cannot switch to Unicode.  c:\PRIVAT\github.com\vstest\test\Microsoft.TestPlatform.TestUtilities\Microsoft.TestPlatform.TestUtilities.csproj

c:\PRIVAT\github.com\vstest\test\Microsoft.TestPlatform.Utilities.UnitTests\Microsoft.TestPlatform.Utilities.UnitTests.csproj : error  : The default XML namespace of the project must be the MSBuild XML namespace. If the project is authored in the MSBuild 2003 format, please add xmlns="http://schemas.microsoft.com/developer/msbuild/2003" to the <Project> element. If the project has been authored in the old 1.0 or 1.2 format, please convert it to MSBuild 2003 format.  c:\PRIVAT\github.com\vstest\test\Microsoft.TestPlatform.Utilities.UnitTests\Microsoft.TestPlatform.Utilities.UnitTests.csproj

c:\PRIVAT\github.com\vstest\test\Microsoft.TestPlatform.VsTestConsole.TranslationLayer.UnitTests\Microsoft.TestPlatform.VsTestConsole.TranslationLayer.UnitTests.csproj : error  : The default XML namespace of the project must be the MSBuild XML namespace. If the project is authored in the MSBuild 2003 format, please add xmlns="http://schemas.microsoft.com/developer/msbuild/2003" to the <Project> element. If the project has been authored in the old 1.0 or 1.2 format, please convert it to MSBuild 2003 format.  c:\PRIVAT\github.com\vstest\test\Microsoft.TestPlatform.VsTestConsole.TranslationLayer.UnitTests\Microsoft.TestPlatform.VsTestConsole.TranslationLayer.UnitTests.csproj

c:\PRIVAT\github.com\vstest\test\testhost.UnitTests\testhost.UnitTests.csproj : error  : The default XML namespace of the project must be the MSBuild XML namespace. If the project is authored in the MSBuild 2003 format, please add xmlns="http://schemas.microsoft.com/developer/msbuild/2003" to the <Project> element. If the project has been authored in the old 1.0 or 1.2 format, please convert it to MSBuild 2003 format.  c:\PRIVAT\github.com\vstest\test\testhost.UnitTests\testhost.UnitTests.csproj

c:\PRIVAT\github.com\vstest\test\vstest.console.UnitTests\vstest.console.UnitTests.csproj : error  : The default XML namespace of the project must be the MSBuild XML namespace. If the project is authored in the MSBuild 2003 format, please add xmlns="http://schemas.microsoft.com/developer/msbuild/2003" to the <Project> element. If the project has been authored in the old 1.0 or 1.2 format, please convert it to MSBuild 2003 format.  c:\PRIVAT\github.com\vstest\test\vstest.console.UnitTests\vstest.console.UnitTests.csproj

c:\PRIVAT\github.com\vstest\test\Microsoft.TestPlatform.Extensions.TrxLogger.UnitTests\Microsoft.TestPlatform.Extensions.TrxLogger.UnitTests.csproj : error  : The default XML namespace of the project must be the MSBuild XML namespace. If the project is authored in the MSBuild 2003 format, please add xmlns="http://schemas.microsoft.com/developer/msbuild/2003" to the <Project> element. If the project has been authored in the old 1.0 or 1.2 format, please convert it to MSBuild 2003 format.  c:\PRIVAT\github.com\vstest\test\Microsoft.TestPlatform.Extensions.TrxLogger.UnitTests\Microsoft.TestPlatform.Extensions.TrxLogger.UnitTests.csproj

c:\PRIVAT\github.com\vstest\samples\Microsoft.TestPlatform.E2ETest\Microsoft.TestPlatform.E2ETest.csproj : error  : The default XML namespace of the project must be the MSBuild XML namespace. If the project is authored in the MSBuild 2003 format, please add xmlns="http://schemas.microsoft.com/developer/msbuild/2003" to the <Project> element. If the project has been authored in the old 1.0 or 1.2 format, please convert it to MSBuild 2003 format.  c:\PRIVAT\github.com\vstest\samples\Microsoft.TestPlatform.E2ETest\Microsoft.TestPlatform.E2ETest.csproj

c:\PRIVAT\github.com\vstest\samples\Microsoft.TestPlatform.TranslationLayer.E2ETest\Microsoft.TestPlatform.TranslationLayer.E2ETest.csproj : error  : The default XML namespace of the project must be the MSBuild XML namespace. If the project is authored in the MSBuild 2003 format, please add xmlns="http://schemas.microsoft.com/developer/msbuild/2003" to the <Project> element. If the project has been authored in the old 1.0 or 1.2 format, please convert it to MSBuild 2003 format.  c:\PRIVAT\github.com\vstest\samples\Microsoft.TestPlatform.TranslationLayer.E2ETest\Microsoft.TestPlatform.TranslationLayer.E2ETest.csproj

c:\PRIVAT\github.com\vstest\samples\UnitTestProject\UnitTestProject.csproj : error  : The default XML namespace of the project must be the MSBuild XML namespace. If the project is authored in the MSBuild 2003 format, please add xmlns="http://schemas.microsoft.com/developer/msbuild/2003" to the <Project> element. If the project has been authored in the old 1.0 or 1.2 format, please convert it to MSBuild 2003 format.  c:\PRIVAT\github.com\vstest\samples\UnitTestProject\UnitTestProject.csproj

c:\PRIVAT\github.com\vstest\test\Microsoft.TestPlatform.AcceptanceTests\Microsoft.TestPlatform.AcceptanceTests.csproj : error  : The default XML namespace of the project must be the MSBuild XML namespace. If the project is authored in the MSBuild 2003 format, please add xmlns="http://schemas.microsoft.com/developer/msbuild/2003" to the <Project> element. If the project has been authored in the old 1.0 or 1.2 format, please convert it to MSBuild 2003 format.  c:\PRIVAT\github.com\vstest\test\Microsoft.TestPlatform.AcceptanceTests\Microsoft.TestPlatform.AcceptanceTests.csproj

c:\PRIVAT\github.com\vstest\test\Microsoft.TestPlatform.SmokeTests\Microsoft.TestPlatform.SmokeTests.csproj : error  : The default XML namespace of the project must be the MSBuild XML namespace. If the project is authored in the MSBuild 2003 format, please add xmlns="http://schemas.microsoft.com/developer/msbuild/2003" to the <Project> element. If the project has been authored in the old 1.0 or 1.2 format, please convert it to MSBuild 2003 format.  c:\PRIVAT\github.com\vstest\test\Microsoft.TestPlatform.SmokeTests\Microsoft.TestPlatform.SmokeTests.csproj

c:\PRIVAT\github.com\vstest\test\Microsoft.TestPlatform.PerformanceTests\Microsoft.TestPlatform.PerformanceTests.csproj : error  : The default XML namespace of the project must be the MSBuild XML namespace. If the project is authored in the MSBuild 2003 format, please add xmlns="http://schemas.microsoft.com/developer/msbuild/2003" to the <Project> element. If the project has been authored in the old 1.0 or 1.2 format, please convert it to MSBuild 2003 format.  c:\PRIVAT\github.com\vstest\test\Microsoft.TestPlatform.PerformanceTests\Microsoft.TestPlatform.PerformanceTests.csproj

c:\PRIVAT\github.com\vstest\test\Microsoft.TestPlatform.ObjectModel.PlatformTests\Microsoft.TestPlatform.ObjectModel.PlatformTests.csproj : error  : The default XML namespace of the project must be the MSBuild XML namespace. If the project is authored in the MSBuild 2003 format, please add xmlns="http://schemas.microsoft.com/developer/msbuild/2003" to the <Project> element. If the project has been authored in the old 1.0 or 1.2 format, please convert it to MSBuild 2003 format.  c:\PRIVAT\github.com\vstest\test\Microsoft.TestPlatform.ObjectModel.PlatformTests\Microsoft.TestPlatform.ObjectModel.PlatformTests.csproj

c:\PRIVAT\github.com\vstest\src\package\package.csproj : error  : The default XML namespace of the project must be the MSBuild XML namespace. If the project is authored in the MSBuild 2003 format, please add xmlns="http://schemas.microsoft.com/developer/msbuild/2003" to the <Project> element. If the project has been authored in the old 1.0 or 1.2 format, please convert it to MSBuild 2003 format.  c:\PRIVAT\github.com\vstest\src\package\package.csproj

c:\PRIVAT\github.com\vstest\test\TestAssets\SimpleTestProject\SimpleTestProject.csproj : error  : The project file could not be loaded. There is no Unicode byte order mark. Cannot switch to Unicode.  c:\PRIVAT\github.com\vstest\test\TestAssets\SimpleTestProject\SimpleTestProject.csproj

c:\PRIVAT\github.com\vstest\test\TestAssets\SimpleTestProject2\SimpleTestProject2.csproj : error  : The project file could not be loaded. There is no Unicode byte order mark. Cannot switch to Unicode.  c:\PRIVAT\github.com\vstest\test\TestAssets\SimpleTestProject2\SimpleTestProject2.csproj

c:\PRIVAT\github.com\vstest\test\TestAssets\NUTestProject\NUTestProject.csproj : error  : The default XML namespace of the project must be the MSBuild XML namespace. If the project is authored in the MSBuild 2003 format, please add xmlns="http://schemas.microsoft.com/developer/msbuild/2003" to the <Project> element. If the project has been authored in the old 1.0 or 1.2 format, please convert it to MSBuild 2003 format.  c:\PRIVAT\github.com\vstest\test\TestAssets\NUTestProject\NUTestProject.csproj

c:\PRIVAT\github.com\vstest\test\TestAssets\XUTestProject\XUTestProject.csproj : error  : The project file could not be loaded. There is no Unicode byte order mark. Cannot switch to Unicode.  c:\PRIVAT\github.com\vstest\test\TestAssets\XUTestProject\XUTestProject.csproj

c:\PRIVAT\github.com\vstest\test\TestAssets\PerfTestProject\PerfTestProject.csproj : error  : The project file could not be loaded. There is no Unicode byte order mark. Cannot switch to Unicode.  c:\PRIVAT\github.com\vstest\test\TestAssets\PerfTestProject\PerfTestProject.csproj

c:\PRIVAT\github.com\vstest\test\TestAssets\SimpleDataCollector\SimpleDataCollector.csproj : error  : The project file could not be loaded. There is no Unicode byte order mark. Cannot switch to Unicode.  c:\PRIVAT\github.com\vstest\test\TestAssets\SimpleDataCollector\SimpleDataCollector.csproj

c:\PRIVAT\github.com\vstest\samples\Microsoft.TestPlatform.Protocol\Microsoft.TestPlatform.Protocol.csproj : error  : The default XML namespace of the project must be the MSBuild XML namespace. If the project is authored in the MSBuild 2003 format, please add xmlns="http://schemas.microsoft.com/developer/msbuild/2003" to the <Project> element. If the project has been authored in the old 1.0 or 1.2 format, please convert it to MSBuild 2003 format.  c:\PRIVAT\github.com\vstest\samples\Microsoft.TestPlatform.Protocol\Microsoft.TestPlatform.Protocol.csproj

c:\PRIVAT\github.com\vstest\test\Microsoft.TestPlatform.Build.UnitTests\Microsoft.TestPlatform.Build.UnitTests.csproj : error  : The default XML namespace of the project must be the MSBuild XML namespace. If the project is authored in the MSBuild 2003 format, please add xmlns="http://schemas.microsoft.com/developer/msbuild/2003" to the <Project> element. If the project has been authored in the old 1.0 or 1.2 format, please convert it to MSBuild 2003 format.  c:\PRIVAT\github.com\vstest\test\Microsoft.TestPlatform.Build.UnitTests\Microsoft.TestPlatform.Build.UnitTests.csproj

c:\PRIVAT\github.com\vstest\test\TestAssets\SimpleTestProject3\SimpleTestProject3.csproj : error  : The project file could not be loaded. There is no Unicode byte order mark. Cannot switch to Unicode.  c:\PRIVAT\github.com\vstest\test\TestAssets\SimpleTestProject3\SimpleTestProject3.csproj

c:\PRIVAT\github.com\vstest\test\TestAssets\SimpleClassLibrary\SimpleClassLibrary.csproj : error  : The default XML namespace of the project must be the MSBuild XML namespace. If the project is authored in the MSBuild 2003 format, please add xmlns="http://schemas.microsoft.com/developer/msbuild/2003" to the <Project> element. If the project has been authored in the old 1.0 or 1.2 format, please convert it to MSBuild 2003 format.  c:\PRIVAT\github.com\vstest\test\TestAssets\SimpleClassLibrary\SimpleClassLibrary.csproj

## Environment
> Please share additional details about the test environment.
> Operating system, Build version of vstest.console

Windows 10
VS 2015/VS 2013 Enterprise/Ultimate

**Comment by csoltenborn** [comment]
Same here, even, with VS2017RC: If I open the solution with VS2015, I get errors like the above. With VS2017RC, I get different errors - [build_output.txt](https://github.com/Microsoft/vstest/files/734536/build_output.txt) is attached (this is from building master (commit a08f6943f0e) with any outgoing changes). Any idea?

**Comment by codito** [comment]
This repo takes a dependency on dotnet project system which is available on `VS 2017 RC 26124.00` onwards. It is available for download here: https://www.visualstudio.com/vs/visual-studio-2017-rc/

Building the repo is also supported in the command line (without VS installation). You can use your favorite editor and with these build scripts. Instructions are in [contribution guide](https://github.com/Microsoft/vstest-docs/blob/master/docs/contribute.md).

**Comment by csoltenborn** [comment]
@codito Thanks for your instructions! I had read the contribution guide, but building via scripts was not an option for me, since I'm mainly interested in investigating the source (I'm one of the authors of the [GoogleTestAdapter](https://github.com/csoltenborn/GoogleTestAdapter)). After upgrading VS2017 RC to 26127.0 the solution builds with only a couple of warnings.

**Comment by codito** [comment]
@csoltenborn thanks for confirmation.
