### ISSUE TITLE
GitHub Advisory for Newtonsoft.Json versions less than 13.0.1

### ISSUE THREAD

**Issue by asasine** [microsoft/vstest#3837]
From https://github.com/advisories/GHSA-5crp-9r3c-p9vr, there is a high severity vulnerability with Newtonsoft.Json versions prior to 13.0.1. We're receiving an alert in our CI process stemming from the Microsoft.NET.Test.Sdk package.

The advisory suggests one of two mitigations: upgrade to Netwonsoft.Json >= 13.0.1 or add a `MaxDepth = 128` to `JsonSerializerSettings` everywhere serializing methods are called.

**Comment by Evangelink** [comment]
Hi @asasine, we recently updated to 13.0.1 (see #3815). The new version isn't yet released but it's on its way.

**Comment by lechacon** [comment]
@Evangelink Is there any issue we can subscribe to for knowing when the new version is released?

**Comment by Evangelink** [comment]
This will be available in 17.4. You can tweak the [notification to be aware of releases](https://docs.github.com/en/account-and-profile/managing-subscriptions-and-notifications-on-github/setting-up-notifications/configuring-notifications#configuring-your-watch-settings-for-an-individual-repository).

**Comment by Evangelink** [comment]
@asasine @lechacon It's released :) https://github.com/microsoft/vstest/releases/tag/v17.4.0-preview-20220707-01
