### ISSUE TITLE
MSTestv2 does not support console output for .NET core unit test projects

### ISSUE THREAD

**Issue by sbaid** [Microsoft/vstest#384]
## Description
MSTestv2 support capturing the console output for .NET projects but not for .NET CORE projects.
https://developercommunity.visualstudio.com/content/problem/13477/test-explorer-does-not-display-console-output-of-n.html

## Steps to reproduce
> What steps can reproduce the defect?
> Please share the setup, commandline for vstest.console, sample project, target
> framework etc.

## Expected behavior
> Share the expected output

## Actual behavior
> What is the behavior observed?

## Environment
> Please share additional details about the test environment.
> Operating system, Build version of vstest.console

**Comment by AbhitejJohn** [comment]
Tracked at Microsoft/testfx#18

**Comment by codito** [comment]
Closing since already tracked in testfx repo.
