### ISSUE TITLE
Update projects to build net7.0 TFM

### ISSUE THREAD

**Issue by MichaelSimons** [microsoft/vstest#3846]
Source build requires projects to build with the current TFM or a supported netstandard TFM. vstest currently targets net6.0. Ideally this would be updated to net7.0. If that is not possible, the TFM could be conditioned for source-build but ideally the regular and source build would be identical.

cc @Haplois 

[AB#1568715](https://devdiv.visualstudio.com/0bdbc590-a062-4c3f-b0f6-9383f67865ee/_workitems/edit/1568715)

**Comment by nohwnd** [comment]
Fixed by https://github.com/microsoft/vstest/commit/d18720133f78f78142c87468275ee0694673a4cd
