### ISSUE TITLE
FailWhenNoTestsFound option (specified in docs) for vstest does not work

### ISSUE THREAD

**Issue by vritant24** [microsoft/vstest#3848]
in the [documentation](https://docs.microsoft.com/visualstudio/test/vstest-console-options?view=vs-2022) an option is provided `/FailWhenNoTestsFound` which when used doesn't work. 
When used, I see the following error:
```The argument /FailWhenNoTestsFound:true is invalid. Please use the /help option to check the list of valid arguments.```
On seeing [this comment](https://github.com/microsoft/vstest/pull/2610#issuecomment-942113882) in the merged PR I was able to find the right option.
The docs might need to be updated

[AB#1865130](https://devdiv.visualstudio.com/0bdbc590-a062-4c3f-b0f6-9383f67865ee/_workitems/edit/1865130)

**Comment by nohwnd** [comment]
Adding to spring because it is a small self contained change. Maybe it is already fixed.

**Comment by nohwnd** [comment]
The mention of the option was removed. `<TreatNoTestsAsError>true</TreatNoTestsAsError>` in runsettings is the way to force this behavior.
