### ISSUE TITLE
DisableAppDomain seems not taken in account while spawning testhost

### ISSUE THREAD

**Issue by andysoftdev** [microsoft/vstest#3869]
It seems the run configuration DisableAppDomain is not taken in account while spawning testhost, see here
https://github.com/microsoft/vstest/blob/b96a5d840cb0fa2ce6de25865cbc8f2f2aa1dec3/src/Microsoft.TestPlatform.TestHostProvider/Hosting/DefaultTestHostManager.cs#L338

therefore !Shared equals DisabledAppDomain, which results in passing the --testsourcepath argument to the testhost, see here

https://github.com/microsoft/vstest/blob/b96a5d840cb0fa2ce6de25865cbc8f2f2aa1dec3/src/Microsoft.TestPlatform.TestHostProvider/Hosting/DefaultTestHostManager.cs#L180-L185

a new AppDomain is created through AppDomainEngineInvoker by the testhost if the --testsourcepath argument is available, see here
https://github.com/microsoft/vstest/blob/b96a5d840cb0fa2ce6de25865cbc8f2f2aa1dec3/src/testhost.x86/Program.cs#L68-L88

if initializing the Shared property like following `Shared = runConfiguration.DisableAppDomain; ` then no new app domain is created by the testhost

The issue have been observed using Window 10, .net framework, x64, vstest.console

**Comment by nohwnd** [comment]
DisableAppDomain option won't disable all usage of appdomains in the process. The process still needs to start up (which creates a default appdomain), and then create another appdomain to be able to use the respective app.config file, so your test dll can run. Disable appdomain will prevent sharing the host, and isolating multiple dlls in appdomains.
