### ISSUE TITLE
Allow custom datacollector host process

### ISSUE THREAD

**Issue by MarcoRossignoli** [microsoft/vstest#3886]
Today we have a way to run tests inside custom test host but we don't have a way to run out of process datacollectors with custom host.
This would be a good addition because it "could" solve issues related to test platform direct and transitive dependency and allow agnostic language implementation of it.

cc: @jakubch1 @fhnaseer

**Comment by nohwnd** [comment]
This is a new feature and won't be implemented, we are focusing on adding new features to Testing.Platform instead.  https://learn.microsoft.com/en-us/dotnet/core/testing/unit-testing-platform-intro?tabs=dotnetcli
