### ISSUE TITLE
InIsolation flag throws error "The test source file "/InIsolation" provided was not found"

### ISSUE THREAD

**Issue by mayankbansal018** [Microsoft/vstest#389]
## Description
> vstest does not accept /InIsolation as command

## Steps to reproduce
> run vstest.console unitest.dll /InIsolation

## Expected behavior
> The test should run

## Actual behavior
> Error: The test source file "/InIsolation" provided was not found

**Comment by codito** [comment]
In current test platform, `InIsolation` is always true. Running tests without isolation is not supported.

Probably we should add an argument processor to maintain compat and inform the user about it is true by default.

**Comment by mayankbansal018** [comment]
PR: https://github.com/Microsoft/vstest/pull/414
