### ISSUE TITLE
Newtonsoft Vulnerabilty, need to upgrade to 13.0.1

### ISSUE THREAD

**Issue by david-hoekman-ms** [microsoft/vstest#3910]
There is a vulnerability with Newtonsoft.Json V 9.0.1 which this uses. 

Can we please get an upgrade to Newtonsoft V 13.0.1 in the nuget package with the next release?

**Comment by Evangelink** [comment]
Hi @david-hoekman-ms,

This was fixed in #3815, it's already available as preview package and will be available in 17.4.
