### ISSUE TITLE
Overloaded test methods result in InvalidOperationException

### ISSUE THREAD

**Issue by pranavkm** [Microsoft/vstest#392]
## Description
We were migrating an existing project.json based xunit test project to MSBuild. One of the test classes had a overloaded method - one as a `Fact` with no arguments and the other a `Theory` with `InlineData`. Once migrated, the test runner fails while running one of the overloaded method.

## Steps to reproduce
> What steps can reproduce the defect?
```xml
<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>netcoreapp1.0</TargetFramework>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Microsoft.NET.Test.Sdk" Version="15.0.0-*" />
    <PackageReference Include="xunit.runner.visualstudio" Version="2.2.0-*" />
    <PackageReference Include="xunit" Version="2.2.0-*" />
  </ItemGroup>
</Project>
```

```c#
using Xunit;

namespace ConsoleApp
{
    public class Test
    {
        [Fact]
        public void TestMethod()
        {
            Assert.True(true);
        }

        [Theory]
        [InlineData(true)]
        public void TestMethod(bool value)
        {
            Assert.True(value);
        }
    }
}
```

## Expected behavior
Overloaded tests work

## Actual behavior
```
Starting test execution, please wait...
Error Message:
Failed   ConsoleApp.Test.TestMethod(???: True)
 System.InvalidOperationException : The test method expected 0 parameter values, but 1 parameter value was provided.

Passed   ConsoleApp.Test.TestMethod

Total tests: 2. Passed: 1. Failed: 1. Skipped: 0.
```

## Environment
> Please share additional details about the test environment.
`dotnet --info`:
```
.NET Command Line Tools (1.0.0-rc3-004522)

Product Information:
 Version:            1.0.0-rc3-004522
 Commit SHA-1 hash:  4e0b465093

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.14393
 OS Platform: Windows
 RID:         win10-x64
```

**Comment by codito** [comment]
Appears to be a known limitation in xunit adapter. See https://github.com/xunit/xunit/issues/1042.

**Comment by NTaylorMullen** [comment]
Did this work in project.json world because the xunit there wasn't using the visual studio runner?

**Comment by pranavkm** [comment]
@NTaylorMullen - yeah both overloads were working with project.json.

**Comment by Faizan2304** [comment]
This is xunit issue: https://github.com/xunit/xunit/issues/1042

**Comment by NTaylorMullen** [comment]
I'm shocked; how did this work in project.json land? It used xunit as well.
