### ISSUE TITLE
Please re-include msdia140typelib_clr0200.dll in the NuGet package Microsoft.TestPlatform.17.4.x

### ISSUE THREAD

**Issue by arvindshmicrosoft** [microsoft/vstest#3922]
## Description
[Microsoft.TestPlatform.17.4.0-preview-20220707-01](https://www.nuget.org/packages/Microsoft.TestPlatform/17.4.0-preview-20220707-01) is missing msdia140typelib_clr0200.dll. In past releases of this NuGet (the latest prior one I can see is 17.3.0-preview-20220612-01), this typelib is present in tools/net451/Common7/IDE/Extensions/TestPlatform/msdia140typelib_clr0200.dll.

Please bring back the msdia140typelib_clr0200.dll as it breaks existing app and test code which uses the DIA SDK from C# and needs this typelib.

## Steps to reproduce
N/A

## Expected behavior
The Microsoft.TestPlatform will include msdia140typelib_clr0200.dll under tools/net451/Common7/IDE/Extensions/TestPlatform/msdia140typelib_clr0200.dll

## Actual behavior
[Microsoft.TestPlatform.17.4.0-preview-20220707-01](https://www.nuget.org/packages/Microsoft.TestPlatform/17.4.0-preview-20220707-01) is missing msdia140typelib_clr0200.dll. 

## Diagnostic logs
N/A

## Environment
N/A

**Comment by Evangelink** [comment]
cc @MarcoRossignoli and @nohwnd

**Comment by Evangelink** [comment]
@arvindshmicrosoft Would you mind sharing with us the scenario in which you are using it? Ideally if you have a repro that would be awesome. Is it that you were relying on the fact this dll was shipped with test platform?

We removed this dependency because it's not used anywhere in our code.

**Comment by arvindshmicrosoft** [comment]
Thanks @Evangelink for sharing the reason behind this change. Let me share the scenario behind this issue:
- `msdia140.dll` is part of the [DIA SDK](https://docs.microsoft.com/en-us/visualstudio/debugger/debug-interface-access/debug-interface-access-sdk?view=vs-2022) within Visual Studio and is a COM library.
- In order to use DIA from within managed applications we need a typelib, which can typically by running `midl` and `typelib` against the `%VSINSTALLDIR%\DIA SDK\idl\dia2.idl` provided by the DIA SDK.
- However, *at least* since VS 2015, `msdia140typelib_clr0200.dll` is shipped with Visual Studio (the exact location has changed, initially I remember it used to be under `Common7\IDE\CommonExtensions\Microsoft\TestWindow`, now of course in 2022 it is under `Common7\IDE\Extensions\TestPlatform`) has provided a ready-to-use typelib.
- The ready-to-use `msdia140typelib_clr0200.dll` eliminating the need for manually running `midl` and `typelib` to generate the "wrapper" needed to use `msdia140.dll` from within managed apps.

I can work around by now proceeding to run `midl` and `typelib` to generate the equivalent of `msdia140typelib_clr0200.dll` but having `msdia140typelib_clr0200.dll` as part VS 2022 and in the VSTest NuGet saves some steps for devs trying to use DIA from managed code.

Though - I totally understand and respect if you stay with the change and do not choose to include `msdia140typelib_clr0200.dll` anymore in this NuGet. Feel free to close the issue with that note, if the decision is final.

**Comment by nohwnd** [comment]
@arvindshmicrosoft Thanks for the context, we are not going to ship that library anymore, because it was made to support .NET Framework 2.0 and we don't have any use for it anymore because we replaced it with p/Invoke.

I've added you to the original thread that explains the details and motivated the removal of this library, hopefully there is alternative library already shipped with VS. Or you can add additional nuget to their build pipeline to create and ship it for you.

I admittedly don't know enough about how this works. From what I understand we moved to using PInvoke with msdia140, to consume it from our C# code. Is not generating a typelib for it, and using that a lost opportunity for us?

**Comment by arvindshmicrosoft** [comment]
@nohwnd - the explanations on this Issue are clear and I will close this issue. I understand why the typelib was removed from VSTest. We will generate the typelib using MIDL and tlbimp for now. Hopefully in the future we will have some other cleaner way for MSDIA interop for all.

**Comment by arvindshmicrosoft** [comment]
Thank you @Evangelink - unfortunately my requirement is solely for native PDBs, so DIA is the only way out.

**Comment by Evangelink** [comment]
Just in case this could help, according to their readme:

> The implementation of these interfaces for Windows PDBs is provided by [Microsoft.DiaSymReader.Native](https://www.nuget.org/packages/Microsoft.DiaSymReader.Native) package
