### ISSUE TITLE
Occasional error when running in Azure DevOps: TF298509

### ISSUE THREAD

**Issue by Tiberriver256** [microsoft/vstest#3925]
We've started seeing the following error crop up in Azure DevOps occasionally. Re-running the build usually makes the run go through fine but I'm wondering if there's anything I can do to troubleshoot the issue aside from just leaving debug logs on until an issue happens.

```
##[error]Data collector 'Screen and Voice Recorder' message: Data collector caught an exception of type 'Microsoft.VisualStudio.TestTools.DataCollection.MediaRecorder.MediaRecorderException': 'Failed to establish communication with the screen recorder process'. More details: TF298509 : An error occurred while starting the screen recorder. Media will not be recorded. Review the log file for more details...
```

**Comment by Evangelink** [comment]
Hi @Tiberriver256,

Are you still experiencing the issue? If so could you let us know the versions (task, Test Platform, extensions) you are using? Could you provide full logs of a build reproducing the error? You can refer to this link to enable diag logs: https://github.com/microsoft/vstest-docs/blob/main/docs/troubleshooting.md#azure-devops

**Comment by Evangelink** [comment]
Ping @Tiberriver256

**Comment by Tiberriver256** [comment]
I'm using the Azure DevOps task to run VSTest, and this problem and a few others have been solved by turning on the `customBatchSize` and setting `customBatchSizeValue` to `1000`. At this point, I apologize, I can't remember where or who made that suggestion to me, but it's been working over the last 6 months or so 🤷‍♂️.

Feel free to close this if you like.

**Comment by Evangelink** [comment]
Do not apologize when we have been slow to answer on our side! Thanks for lettting me know, I will close the issue.
