### ISSUE TITLE
Incorrect numbers for condition-coverage 

### ISSUE THREAD

**Issue by X9VoiD** [microsoft/vstest#3940]
## Description
The branch coverage produced by `dotnet test --collect:"Code Coverage"` seems to be a bit incorrect for snippets of code that looks like this:

```cs
int someNumber = GetProbablyNullInt() ?? 69;
```

It would show on the cobertura xml file that there's *four* possible branches to visit in this code, but there really is only two (the two only possible condition being either null or not null). Covering for only one of the conditions results in 2 out of 4 branches visited. So for one condition, it always yields two branches visited. If I cover both conditions, it says 4 out of 4.

tl;dr, The end result is correct in that all possible branches are covered but the number of possible branches is incorrect and misleading.

## Steps to reproduce
[SmolRepro.zip](https://github.com/microsoft/vstest/files/9315145/SmolRepro.zip)

This is a minimal reproduction project that exhibits said behaviour. I provided a script to run the tests and generate a code coverage report.
> The zip also includes the results of when I ran the script in case other people got different results

1. Extract zip to any writeable directory.
2. Run `./generate_coverage.sh`
3. Open `./coverage_report/index.html`

## Expected behavior
I expected to see "2 out of 2 branches are covered"

## Actual behavior
But instead, what I see is this:

![image](https://user-images.githubusercontent.com/10338031/184324328-6ccb75f1-85ef-4113-bfad-5ae489a5e616.png)

## Further Information

So I tried my own little investigation, and took a look at the generated IL to see if there was really two conditional branches to create those 4 possible branches. Here's the [sharplab.io](https://sharplab.io/#v2:C4LglgNgNAJiDUAfAAgBgATIIwDoBKArgHbBgC2ApjgMID2ZADpBQE4DKrAbmAMYUDOAbgCwAKDEBiIgQgQAhgCMIFdBSKLlYscgDMmAEzpq6AN5j0FzHuQAWdAFkAFAEpT5yx7AkA/OjnoAXnQAcQpgADU5CAIKFxFRDw9OORZ0BUC/dG9fADYATniPAF93C1L0AG17MIALWhgASUYIR2rgOsbmgHkGUloifhwAOVoGoggvLwBzZwBdct10L2BfUIiomJdyswTEi2QAdnRpWULLEtELoA==) link to follow along.

![image](https://user-images.githubusercontent.com/10338031/184324815-c61b3fcc-aed9-4c91-b553-5d916ee790c9.png)

If I'm interpreting this correctly, `IL_0011` is the only conditional jump, and so the total branches should still only be 2 instead of 4. `IL_0015` is an unconditional jump.

## Environment

NixOS 22.05

[AB#1689957](https://devdiv.visualstudio.com/0bdbc590-a062-4c3f-b0f6-9383f67865ee/_workitems/edit/1689957)

**Comment by Evangelink** [comment]
@jakubch1 Could you please have a look at this one?

**Comment by jakubch1** [comment]
@X9VoiD thanks for reporting this. I've fixed the issue so it will be available in next release of Microsoft.CodeCoverage (17.5.0). If you need it sooner, please let me know and I will post preview package.
