### ISSUE TITLE
[loc][Query][VSTest] Please clarify translatability

### ISSUE THREAD

**Issue by mkyjakova** [Microsoft/vstest#395]
Hi, we have a question from our translator. Can you help please? Thanks!

Source:
Args:
      Any extra arguments that should be passed to adapter. Arguments may be specified as name-value pair of the form <n>=<v>, where <n> is the argument name, and <v> is the argument value. Use a space to separate multiple arguments.

File Name:
Resources.de

Query:
Can you please clarify whether "Args" is translatable in this case or whether it should stay in English? Thanks!

**Comment by Faizan2304** [comment]
"Args" should stay in English.

**Comment by mkyjakova** [comment]
Thanks!
