### ISSUE TITLE
JSON protocol is verbose

### ISSUE THREAD

**Issue by pvlakshm** [Microsoft/vstest#396]
Filing on behalf of **@citizenmatt**.

1. The JSON interface is very verbose, and we're very concerned about performance, especially with a larger test run. The amount of information passed for a single test case is huge, and multiply that by hundreds, thousands or tens of thousands, and we'll see a lot of memory traffic, in-process with the IDE. It seems that the format could be a lot shorter, without each property having a full type descriptor passed with it. This would also make deserialization faster.
2. We don't see a need for the properties to be self-describing. If we need to make use of the data, we will already know the property ID, display name and value type. Describing it seems unnecessary, and leads to the verbosity.
3. Should Attributes include values such as "Hidden"? This feels like a UI concern, but in the reporting protocol.
4. We don't understand the use of the .NET type name for the ValueType field - what is the purpose of using "System.Collections.Generic.KeyValuePair`2[[System.String],[System.String]][]"? The type name doesn't help us - we can't create a new instance of the class to help deserialise, so it seems to be used as a key or identifier, and a very verbose one at that.

**Comment by codito** [comment]
This is fixed in master, available in dev builds of dotnet-cli.

Specification is here: https://github.com/Microsoft/vstest-docs/blob/master/RFCs/0009-Editors-API-RevisionUpdate.md
