### ISSUE TITLE
JSON protocol needs versioning

### ISSUE THREAD

**Issue by pvlakshm** [Microsoft/vstest#397]
Filing on behalf of **@citizenmatt**.

By making the protocol so loosely coupled, with self-describing properties, it's very easy to misuse - instead of modifying message definitions and increasing the protocol version, it is now very easy to simply add new properties into the same protocol. Without knowledge that the protocol version has changed, we would need to test for the existence of properties before using them, complicating the implementation.

**Comment by codito** [comment]
This is fixed in master, available in latest dev builds of `dotnet-cli`.

Specification is updated here: https://github.com/Microsoft/vstest-docs/blob/master/RFCs/0009-Editors-API-RevisionUpdate.md
