### ISSUE TITLE
Need control over batching

### ISSUE THREAD

**Issue by pvlakshm** [Microsoft/vstest#398]
Filing on behalf of **@citizenmatt**.

Test runs are batched, but there are no details about the batching, or if we can control the batching threshold. Our test runner displays what tests are currently running, and will show output (if available) as the test runs.

**Comment by singhsarab** [comment]
This is a good feedback. We should be able to provide control over batching.
Current batching mechanism uses batch size (=10) and timeout(=500ms).

**Comment by AbhitejJohn** [comment]
There was a /batchsize argument that the Dev14 vstest.console used to take. That should fit in well here. I'm not sure how the timing was controlled though.

**Comment by singhsarab** [comment]
Made the batch size configurable via runsettings. 
```
<RunSettings>  
     <RunConfiguration>  
          <BatchSize>15</BatchSize>  
      </RunConfiguration>
</RunSettings> 
```
Associated commit https://github.com/Microsoft/vstest/commit/d62c0059892102134e616b8104b5fb81a8421b60
