### ISSUE TITLE
Source-build behavior control update

### ISSUE THREAD

**Issue by mmitche** [microsoft/vstest#3983]
### Description

**This issue is dependent on https://github.com/dotnet/source-build/issues/2974 and is a placeholder for .NET 8 required work in product repositories.**

Instructions for implementation will be updated once https://github.com/dotnet/source-build/issues/2974 but will likely be a mechanical shift of properties in this repo. In a general sense, this is scaffolding work for expanding the set of source-built platforms beyond Linux.

**Comment by mmitche** [comment]
This is .NET 8 work

**Comment by Evangelink** [comment]
@mmitche Is there something we need to do on our side or are you going to handle it?

**Comment by mmitche** [comment]
For vstest, it'll probably be transparent to this repo. We don't have a design yet.

**Comment by mmitche** [comment]
Blocked on move to net9 arcade

**Comment by nohwnd** [comment]
We are on net9 arcade, is there anything to do?

**Comment by mmitche** [comment]
It looks like the update was already completed.
