### ISSUE TITLE
Separation of concerns between completion events Test results message

### ISSUE THREAD

**Issue by pvlakshm** [Microsoft/vstest#399]
Filing on behalf of **@citizenmatt**.

The TestDiscovery.Completed and TestExecution.Completed events also carry the last batch of results. The protocol is so verbose in other areas that it would be a better separation of concerns to simply send an extra test results message.

**Comment by singhsarab** [comment]
This is just an optimization to send just one message instead of two in the end.
But then as per SRP, this seems to be a good feedback. 

Also, I guess we might need it for data collector support as well. @harshjain2 share your thoughts.

**Comment by Faizan2304** [comment]
After discussion we came out that we will maintain current flow. That is `HandleDiscoveryCompleted` will have last chunk ( If there are some tests that didn't get send through  HandleDiscoveredTests).

### Benefit of having last chunk in HandleDiscoveryCompleted
TestPlatform send HandleDiscoveredTests if number of discovered test is more than a particular size(default is 10 (and this is customizable through run setting)) or time elapsed from last call of HandleDiscoveryCompleted is more than 1.5 second [Code here](https://github.com/Microsoft/vstest/blob/master/src/Microsoft.TestPlatform.CrossPlatEngine/Discovery/DiscoveryResultCache.cs#L128)

If any test left after above check we send it in last chunk of HandleDiscoveryCompleted [Code here](https://github.com/Microsoft/vstest/blob/master/src/Microsoft.TestPlatform.CrossPlatEngine/Discovery/DiscoveryManager.cs#L124)

Now consider a scenario where there is only one tests in test project:
We need to call only one event of HandleDiscoveryCompleted with last chunk which will have one test. Now if we don't want to send test in last chunk then we have to make two call 
a) HandleDiscoveredTests with one test
b) HandleDiscoveryCompleted with last chunk null. 

The same way it will benefit in test run scenario.
