### ISSUE TITLE
17.3.0 cannot resolve Antlr4.Runtime

### ISSUE THREAD

**Issue by nohwnd** [microsoft/vstest#3991]
I don't know if this is a similiar problem as described above. When changing from 17.2.0 to 17.3.0 we started to get this error:
```
2022-08-30T08:44:38.2254917Z Testhost process exited with error: Error:
2022-08-30T08:44:38.2255816Z   An assembly specified in the application dependencies manifest (PRI.Solvency.Web.UI.Tests.deps.json) was not found:
2022-08-30T08:44:38.2256217Z     package: 'Antlr4.Runtime', version: '4.6.6'
2022-08-30T08:44:38.2256622Z     path: 'lib/netstandard1.1/Antlr4.Runtime.dll'

```
The test project (PRI.Solvency.Web.UI.Tests.csproj) lists the application project (PRI.Solvency.Web.UI.csproj) as a dependency and that project in turn references `Antlr4.Runtime`. Both those projects target .NET 6.0 while all the other projects within the solution target .NET Framework 4.8.

We only inlcude test projects as test assemblies. The `dotnet.exe restore` command reports no warnings for both projects.

_Originally posted by @matsovef in https://github.com/microsoft/vstest/issues/3939#issuecomment-1231710096_

**Comment by nohwnd** [comment]
@matsovef I guess your project is not public right? Could you make a simple repro please?

**Comment by matsovef** [comment]
@nohwnd No, the project is not public.

We have been digging deeper in the solution and identified an alteration that must be made to the `PRI.Solvency.Web.UI.Tests.csproj` file for successfully using version 17.3.0. A consequence of switching from Net Framework 4.8 to Net Core 6 and from VS2019 to VS2022.

This issue can be closed.
