### ISSUE TITLE
How to co-operatively cancel/abort discovery and execution

### ISSUE THREAD

**Issue by pvlakshm** [Microsoft/vstest#400]
Filing on behalf of **@citizenmatt**.

Various messages indicate that discovery and execution can be aborted or cancelled, but there is no description of how we can cooperatively cancel or forcibly abort a test run.

**Comment by singhsarab** [comment]
Cancel for discovery is not currently supported. We already have an issue tracking it https://github.com/Microsoft/vstest/issues/149.
Adding the documentation for Cancel/Abort execution via Microsoft/vstest-docs#22
