### ISSUE TITLE
Question about TestRunEventsHandler changes pushed with 17.3

### ISSUE THREAD

**Issue by Bterry14** [microsoft/vstest#4004]
The `IVsTestConsoleWrapper` has a few methods that take in `ITestRunEventsHandler`. Before 17.3.0 we have been using the [TestRunEventsHandler](https://github.com/Evangelink/vstest/blob/493a0e2ff925cbd4f5d218bda5f4f0f937fa9efc/src/Microsoft.TestPlatform.CommunicationUtilities/EventHandlers/TestRunEventsHandler.cs) to be passed into those methods.
This is the method we are using from `IVsTestConsoleWrapper`:
`RunTests(IEnumerable<TestCase> testCases, string runSettings, TestPlatformOptions options, ITestRunEventsHandler testRunEventsHandler)`.

The issue is now that the `TestRunEventsHandler` [was updated](https://github.com/Evangelink/vstest/commit/27ea06b7240b9c67431b2995b48f43fbe2c86db0#diff-09ecaa09c135410d21df6600437fef2fb2b8b589916e337bb0ea411e6e74a859)  to inherit `ITestRunEventsHandlerInternal` instead of `ITestRunEventsHandler` we have to impliment our own test runner (We could just copy the previous logic from the `TestRunEventsHandler` class into our own class that inherits the `ITestRunEventsHandler`).

<img width="741" alt="image" src="https://user-images.githubusercontent.com/28708334/189375898-c1f04164-d985-48ca-8985-2d0cc5de33ce.png">

Was this intended?

**Comment by Bterry14** [comment]
After looking at the code for the TestRunEventsHandler I realized that it isn't doing much besides just a wrapping the TestRunEventsHandler. Given the interface name I assume it was never intended to be used externally.

**Comment by nohwnd** [comment]
Yes, there are many types that should have been marked as internal but are public. We sadly cannot change that.
