### ISSUE TITLE
How are nested exceptions serialized?

### ISSUE THREAD

**Issue by pvlakshm** [Microsoft/vstest#402]
Filing on behalf of **@citizenmatt**.

**Comment by singhsarab** [comment]
There is nothing special for serialization of the nested exceptions.
It is reported like 
"Test method UnitTestProject7.UnitTest1.TestMethod1 threw exception: \r\nSystem.Exception: DummyException ---> System.Exception: DummyInnerException"

The result also contains the StackTrace
"at UnitTestProject7.UnitTest1.Foo() in C:\\Users\\userA\\Documents\\Visual Studio 2017\\Projects\\UnitTestProject1\\UnitTestProject1\\UnitTest1.cs:line 19\r\n--- End of inner exception stack trace ---\r\n    at UnitTestProject1.UnitTest1.Foo() in C:\\Users\\userA\\Documents\\Visual Studio 2017\\Projects\\UnitTestProject1\\UnitTestProject1\\UnitTest1.cs:line 23\r\n   at UnitTestProject1.UnitTest1.TestMethod1() in C:\\Users\\userA\\Documents\\Visual Studio 2017\\Projects\\UnitTestProject1\\UnitTestProject1\\UnitTest1.cs:line 12\r\n"
