### ISSUE TITLE
Problem with v17.3.1 : The active test run is aborted due to System.TimeSpan deserialization

### ISSUE THREAD

**Issue by Farnaz-Ansari** [microsoft/vstest#4029]
## Description
> Tests fail due to this reason: Cannot deserialize the current JSON object (e.g. {"name":"value"}) into type '`System.TimeSpan`' 
> Downgrading to Microsoft.NET.Test.Sdk v17.0.0 resolves this issue.

## Steps to reproduce
> The integration tests are for RestfulApi Controllers and are deriving from `IClassFixture<WebTestFixture<Startup>>`
A fake repository is mocked which returns an object containing a  `System.TimeSpan` property.

## Actual behavior
> When debugging the tests ,they run successfully until the end without breaking, and there is no indication that the test passed or failed. Output shows System.Exception is thrown from `Newtonsoft.Json.Serialization`.

## Diagnostic logs
> The active test run was aborted. Reason: Cannot deserialize the current JSON object (e.g. {"name":"value"}) into type 'System.TimeSpan' because the type requires a JSON primitive value (e.g. string, number, boolean, null) to deserialize correctly.
To fix this error either change the JSON to a JSON primitive value (e.g. string, number, boolean, null) or change the deserialized type so that it is a normal .NET type (e.g. not a primitive type like integer, not a collection type like an array or List<T>) that can be deserialized from a JSON object. JsonObjectAttribute can also be added to the type to force it to deserialize from a JSON object.
Path 'Payload.TestRunCompleteArgs.ElapsedTimeInRunningTests.ticks', line 17, position 16.
Results File: /home/vsts/work/_temp/_fv-az158-963_2022-09-28_03_34_37.trx

> Test Run Aborted with error System.Exception: One or more errors occurred.
 ---> System.Exception: Cannot deserialize the current JSON object (e.g. {"name":"value"}) into type 'System.TimeSpan' because the type requires a JSON primitive value (e.g. string, number, boolean, null) to deserialize correctly.
To fix this error either change the JSON to a JSON primitive value (e.g. string, number, boolean, null) or change the deserialized type so that it is a normal .NET type (e.g. not a primitive type like integer, not a collection type like an array or List<T>) that can be deserialized from a JSON object. JsonObjectAttribute can also be added to the type to force it to deserialize from a JSON object.
Path 'Payload.TestRunCompleteArgs.ElapsedTimeInRunningTests.ticks', line 17, position 16.
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateObject(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateValueInternal(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.SetPropertyValue(JsonProperty property, JsonConverter propertyConverter, JsonContainerContract containerContract, JsonProperty containerProperty, JsonReader reader, Object target)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.PopulateObject(Object newObject, JsonReader reader, JsonObjectContract contract, JsonProperty member, String id)

## Environment
> 

- Microsoft.NET.Test.Sdk 17.3.1
- TargetFramework net6.0
- xunit.runner.visualstudio 2.4.5
- xunit 2.4.2
- coverlet.msbuild 3.1.2

**Comment by Evangelink** [comment]
Could you try to bump to `17.4.0` and let us know if you are still having the issue? If so, would it be possible to create a small repro?

**Comment by barbarosalp** [comment]
I am on version 17.4.1 and still getting the error;
```
Microsoft (R) Test Execution Command Line Tool Version 17.4.0 (x64)
Copyright (c) Microsoft Corporation.  All rights reserved.

Starting test execution, please wait...
A total of 1 test files matched the specified pattern.
The active test run was aborted. Reason: Error converting value "PT0.002328S" to type 'System.TimeSpan'. Path 'Payload.NewTestResults[0].Duration', line 1, position 865.

```

**Comment by barbarosalp** [comment]
Downgrading to Microsoft.NET.Test.Sdk v17.0.0 resolves this issue for me as well.
