### ISSUE TITLE
What is the policy for reusing dotnet-vstest process?

### ISSUE THREAD

**Issue by pvlakshm** [Microsoft/vstest#403]
Filing on behalf of **@citizenmatt**.

The policy of reusing dotnet-vstest process is also not described. Now, you specify the project(s) to run/discover in ‘TestDiscovery.Start’ and ‘TestExecution.RunAllWithDefaultHost’ messages. What happens if an error occurs during either process? Does the process have to be abandoned and the session terminated or is it okay to reuse it for a different discovery/run?

**Comment by singhsarab** [comment]
dotnet-vstest is reusable.
Errors/Exceptions usually happen in the host process where the actual test is running and those cases are handled in dotnet-vstest.
Also, most exceptions even if they occur in dotnet-vstest. get safely handled and reported back to the IDE. 
So, after the first request completes, consequent request can be sent to the same dotnet-vstest.

**Comment by estrizhok** [comment]
Can a single instance of dotnet-vstest service multiple request simultaneously? For example, run two discovery at the same time? And if so, how one can tell whether a response relates to the first or the second discovery without looking deep into the message, i.e without looking at TestCase.Source and TestCase.ExecutorUri properties?

**Comment by singhsarab** [comment]
Currently, single instance of dotnet-vstest services only one request at a given instance.
