### ISSUE TITLE
Cannot disable cover metrics in console

### ISSUE THREAD

**Issue by SamHuoJudiAi** [microsoft/vstest#4038]
## Description
Hi,

I am using the following nuget package versions:

- coverlet.msbuild: v2.9.0
- Microsoft.CodeCoverage: v16.9.1

I am trying to figure out how to disable cover metrics in the console when I run dotnet test but still output the file. The reason why I am trying to do this is to reduce the information that is being captured on the console when we run Test/Coverage on GitHub Actions.

Thanks!

## Steps to reproduce
- coverlet.msbuild: v2.9.0
- Microsoft.CodeCoverage: v16.9.1

1) Run dotnet test in console

**Comment by MarcoRossignoli** [comment]
Can you please share your test command line?

In steps I see two references, can you pls share the csproj to be able to repro in my local?
