### ISSUE TITLE
Is there a test start event, which our runner expects to show what test(s) are currently running.

### ISSUE THREAD

**Issue by pvlakshm** [Microsoft/vstest#405]
Filing on behalf of **@citizenmatt**.

Is there is no test start event, which our runner expects to show what test(s) are currently running.

**Comment by singhsarab** [comment]
There are no such events per test. But user can rely on ActiveTests property in Test Run Statistics response payload to get the currently running/active tests.

Fixed the documentation for Test Run Statistics via https://github.com/Microsoft/vstest-docs/pull/22
Reference : https://github.com/Microsoft/vstest-docs/blob/f606f0c6f4ab05602889f95aebd02579fc972e49/RFCs/0007-Editors-API-Specification.md#test-run-statistics-response

**Comment by estrizhok** [comment]
Thanks for the update. That will suffice.
