### ISSUE TITLE
Spurious warnings on Linux source-build

### ISSUE THREAD

**Issue by crummel** [microsoft/vstest#4068]
## Description
The VSTest source-build on Linux produces some errors that do not affect the build but can still confuse users.

## Steps to reproduce
clone https://github.com/dotnet/installer
./build.sh /p:ArcadeBuildTarball=true /p:TarballDir=/path/to/tarball
cd /path/to/tarball
./prep.sh
./build.sh
check artifacts/logs/vstest.log

## Expected behavior
There should be no warnings or errors that do not affect the build.  These appear to all be related to Windows or other files that do not exist in source-build.

## Actual behavior
A couple different types of errors:
```cp: cannot stat '/<<PKGBUILDDIR>>/src/vstest/artifacts/source-build/self/package-cache/[microsoft.visualstudio.coverage.io/17.0.0-beta.21471.1/lib/netstandard2.0/**': No such file or directory```
```cp: cannot stat '/<<PKGBUILDDIR>>/src/vstest/artifacts/source-build/self/package-cache/system.diagnostics.eventlog/7.0.0-rtm.22507.1/runtimes/win/**': No such file or directory```

## Environment
> Please share additional details about the test environment.
Seen on Ubuntu 22.04 by a customer and RHEL8 by me.

**Comment by nohwnd** [comment]
Hopefully fixed by https://github.com/microsoft/vstest/commit/d18720133f78f78142c87468275ee0694673a4cd

**Comment by Evangelink** [comment]
@crummel Would you mind confirming that this issue is now correctly fixed?

**Comment by Evangelink** [comment]
ping @crummel

**Comment by Evangelink** [comment]
I will move forward by closing this issue. Please feel free to comment or reopen if you can provide more information.
