### ISSUE TITLE
Desktop test projects with class fixtures can fail to find tests.

### ISSUE THREAD

**Issue by NTaylorMullen** [Microsoft/vstest#408]
## Description
Running semi-complex test projects that utilize advanced class fixtures can result in tests failing to run. I've tried to repro this on smaller projects but to no avail. There's something unique about the MVC functional tests that trigger the issue. I've gone ahead and created a branch for bug investigation.

I was able to create a brand new test project with a single test that had the same csproj as the MVC functional tests and bring in the MvcTestFixture and use it to repro the issue.

## Steps to reproduce
- git clone git@github.com:aspnet/Mvc.git
- cd Mvc
- git fetch
- git checkout nimullen/migration.desktoptestbug
- cd test/Microsoft.AspNetCore.Mvc.FunctionalTests
- dotnet restore
- dotnet test -f net451

## Expected behavior
Tests are run

## Actual behavior
```
Microsoft (R) Test Execution Command Line Tool Version 15.0.0.0
Copyright (c) Microsoft Corporation.  All rights reserved.

Starting test execution, please wait...
Warning: No test is available in C:\Users\nimullen\Documents\GitHub\Mvc\test\Microsoft.AspNetCore.Mvc.FunctionalTests\bin\Debug\net451\Microsoft.AspNetCore.Mvc.FunctionalTests.dll. Make sure that installed test discoverers & executors, platform & framework version settings are appropriate and try again.
```

**Comment by codito** [comment]
@NTaylorMullen, the test discovery is failing because of following issue.
```
Warning: [xUnit.net 00:00:18.9600000] Skipping: Microsoft.AspNetCore.Mvc.FunctionalTests (could not find dependent assembly 'SecurityWebSite, Version=1.0.0')
```

Finding these errors is quite hard currently, they are not showing up on stdout because of #300. Working on fixing it.

**Comment by NTaylorMullen** [comment]
@codito I see! I'm glad it's a duplicate bit then. Thanks!!

**Comment by NTaylorMullen** [comment]
@codito how did you get those logs? Having another issue similar to this and trying to find the underlying cause.

**Comment by natemcmaster** [comment]
@NTaylorMullen not sure if this is how @codito  did it, but `dotnet test -d:log.txt` usually works for me.

**Comment by NTaylorMullen** [comment]
@natemcmaster nah, doesn't provide enough info 😢 . I was able to get the info needed by building source locally and updating my test host. Looks like they fixed this in newer builds

**Comment by codito** [comment]
@NTaylorMullen with #300 fixed, the issues from adapter have started showing up. Please update Test.Sdk reference to https://www.nuget.org/packages/Microsoft.NET.Test.Sdk/15.0.0-preview-20170210-02 to get the fix.
