### ISSUE TITLE
VS adds 'Service' item to csproj

### ISSUE THREAD

**Issue by natemcmaster** [Microsoft/vstest#409]
Running tests in VS 2017 always adds `<Service Include="{82a7f48d-3b50-4b1e-b82e-3ada8210c358}" />` to the csproj. This value doesn't appear to be necessary for vstest.console. Is this item necessary to run tests in VS? If not, can we stop adding this automatically to projects?

The best information I can find is that is was a perf optimization for opening test explorer. http://stackoverflow.com/questions/18614342/what-is-service-include-in-a-csproj-file-for/22917902#22917902. If so, could this be added implicitly to a project when Microsoft.NET.Test.Sdk is referenced?

**Comment by codito** [comment]
Yes, test explorer uses this information to consider a project as test project. I agree, we should be able to provide a better marker from Microsoft.NET.Test.Sdk. Will close this issue in favor of related issue #394.
