### ISSUE TITLE
CodeCoverage excludes C++ lambda functions

### ISSUE THREAD

**Issue by kmaddock** [microsoft/vstest#4092]
## Description
CodeCoverage excludes C++ lambda functions from coverage.

https://github.com/microsoft/vstest/blob/main/src/vstest.console/Processors/EnableCodeCoverageArgumentProcessor.cs excludes functions using the pattern ".*::__.*" which is too broad, and excludes lambdas

        @"              <Exclude>" + Environment.NewLine +
        @"                <Function>.*::__.*</Function>" + Environment.NewLine +
        @"              </Exclude>" + Environment.NewLine +

## Expected behavior
C++ lambdas should be included

## Log
        <skipped_function id="171392" name="operator()&lt;std::pair&lt;unsigned int,std::string&gt; &gt;(const struct std::pair&lt;unsigned int,std::string&gt; &amp; const)" type_name="MyClass::myFunction::__l62::&lt;lambda_a342563fd4ec416721c684c2aae87989&gt;::()::__l2::&lt;lambda_094dc3e11df301c124e259645bf2a542&gt;" reason="name_excluded" />

**Comment by kmaddock** [comment]
I suggest the pattern: `.*::__(?!l\d+).*` might work?

**Comment by jakubch1** [comment]
I've made change to not exclude lambda functions for static native instrumentation. Unfortunately, we have to keep it for dynamic native instrumentation as changing it can cause crashes. More about static and dynamic native instrumentation: https://learn.microsoft.com/en-us/visualstudio/test/customizing-code-coverage-analysis?view=vs-2022#static-and-dynamic-native-instrumentation
