### ISSUE TITLE
Binding redirects for adapters

### ISSUE THREAD

**Issue by wasabii** [microsoft/vstest#4097]
I'm trying to figure out the proper solution for a test adapter's .NET 4 output. I have a test adapter which depends on a number of other assemblies. I need binding redirects for these assemblies. Deploying a .dll.config alongside the test adapter doesn't seem to cut it. I suspect it doesn't read from this.

What is the guidance on this?

**Comment by wasabii** [comment]
The solution I'm going to try is to split my adapter into two assemblies. One for the adapter. And another for the actual logic. And have the adapter spawn up an explicit AppDomain to run the logic in, specifically setting the .dll.config for the engine.

**Comment by MarcoRossignoli** [comment]
We don't have today isolation of adapters inside the host, so your solution to go by your own and setup custom appdomain in your adapter is a good one.

**Comment by wasabii** [comment]
My solution did work. But getting the test cases and test results across the app domain barrier was a mess. Had to define an entire class hierarchy separate from the Microsoft stuff for it to isolate the child domain from attempting to load the test host assemblies.

And then another sightly different version of the whole thing for Core.

**Comment by josesimoes** [comment]
That really sounds messy! 
This should be handled by the host...

**Comment by wasabii** [comment]
AppDomain solution no longer works for me for various reasons. Now have to find a better solution. Sigh.
