### ISSUE TITLE
Command line switch to pause vstest after all tests have finished

### ISSUE THREAD

**Issue by Anton-V-K** [microsoft/vstest#4099]
## Description
I'm running vstest from VS2022 for debugging purposes as an external program, passing it my DLL as a parameter:
`$(VSInstallDir)Common7\IDE\CommonExtensions\Microsoft\TestWindow\vstest.console.exe $(TargetPath)`
Everything works fine, but I can't review the console output after all tests are done - VS2022 IDE just closes the console ignoring the option 'Automatically close the console when debugging stops' (I guess, it may affects only the native debugger).

## Steps to reproduce
1. Create a UnitTest DLL in C++ in VS2022.
2. Set up custom debugging for it.
3. Run/Debug

## Expected behavior
If vstest supported an extra command line switch like `/pause` (or anything else), I would be able to review console output after all tests are done.

## Actual behavior
The console is closed after all tests are done.

## Environment
`Test Execution Command Line Tool Version 17.3.0-preview-20220626-01 (x64)`
VS2022 17.3.4
OS: Windows 10 Pro (Version	10.0.19043 Build 19043)

**Comment by nohwnd** [comment]
This seems too have very narrow functionality, and I would prefer to close it as won't implement. It is simple, but it is yet another special thing to do.

**Comment by Evangelink** [comment]
Marking as won't fix as suggested by @nohwnd.
