### ISSUE TITLE
System.Exception: Unable to read beyond the end of the stream on Azure Ubuntu Pipeline Agent

### ISSUE THREAD

**Issue by dstankovic95** [microsoft/vstest#4117]
## Description
> Hello, I'm facing a problem during the Integration Tests Job on the Azure CI/CD pipeline, project is the .NET Core 6 application.

The jobs are being run by a pool of the Build agents that are **Linux Ubuntu** machines, version **20.04**. The confusing part is that tests (Xunit) are all green when they have been run on the local Windows machine, but for some reason, execution pipeline has been broken on Linux Ubuntu with very generic message -> 

`Test Run Aborted with error System.Exception: One or more errors occurred.
 ---> System.Exception: Unable to read beyond the end of the stream.
   at System.IO.BinaryReader.Read7BitEncodedInt()
   at System.IO.BinaryReader.ReadString()
   at Microsoft.VisualStudio.TestPlatform.CommunicationUtilities.LengthPrefixCommunicationChannel.NotifyDataAvailable()
   at Microsoft.VisualStudio.TestPlatform.CommunicationUtilities.TcpClientExtensions.MessageLoopAsync(TcpClient client, ICommunicationChannel channel, Action 1 errorHandler, CancellationToken cancellationToken)
   --- End of inner exception stack trace ---.`

Is there any way to make the given message more verbose, containing more details about the error?

## Steps to reproduce
> Pipeline task definition:  - task: DotNetCoreCLI@2
    displayName: Integration tests
    inputs:
      command: test
      projects: '**/*Tms.Tests.Integration/*.csproj'
      arguments: -v=normal --logger:"console;verbosity=normal" --blame --no-build --configuration $(BuildConfiguration)
      publishTestResults: false.

## Expected behavior
> Test project is not aborted regardless of the results.

## Actual behavior
> Test project is aborted without any concrete message.

## Environment
> OS: Linux Ubuntu, 20.04
> Xunit testing framework - 2.4.2
> Microsoft.AspNetCore.TestHost - 6.0.11

**Comment by MarcoRossignoli** [comment]
You can enable verbose logging using the `--diag` argument like in the sample https://github.com/Microsoft/vstest-docs/blob/main/docs/troubleshooting.md#dotnetcorecli2-task
The sample explain how to take a dump of the host process too.
