### ISSUE TITLE
Make discovery cancellable (cooperative cancellation)

### ISSUE THREAD

**Issue by wasabii** [microsoft/vstest#4130]
I've got a custom adaptor. My discovery process can take awhile (minutes). There's nothing on the DiscoverTests method I can implement, that I can find, to initiate a cancel of discovery.

As such, when I cancel it, I have to wait a couple minutes for the Test Explorer to give up. Tests keep feeding in the whole time.

Is there something about cancellation I'm missing?

**Comment by Evangelink** [comment]
For discovery, there is no explicit cancellation but Test Explorer (inside of VS) used a specific API from the translation layer package we ship to cancel discovery. Using this, we are simply killing the process doing discovery so there is nothing specific a custom adapter needs to implement.

> As such, when I cancel it, I have to wait a couple minutes for the Test Explorer to give up. Tests keep feeding in the whole time.

That's not a normal behavior, the discovery should kick in quite quickly.

Which version of Visual Studio are you using?

**Comment by wasabii** [comment]
17.4

The issue is limited to remote tests: Windows running VS, using WSL Linux remote testing environment.

**Comment by Evangelink** [comment]
I see. I think that's related to how messages are batched during remote execution not allowing us to do streamed response and so to do faster discovery cancellation (cc @drognanar).

I am afraid there is nothing we can do in short term to help there.

**Comment by wasabii** [comment]
Bummer. At this point it literally takes 10 minutes to cancel.

My test adapter is a wrapper for JTreg, which ends up exposing the entire test suite of OpenJDK. Over 30,000 tests.

It takes a long time.

**Comment by Evangelink** [comment]
Let me change the title and mark this as improvement request.

**Comment by nohwnd** [comment]
This is a new feature and won't be implemented, we are focusing on adding new features to Testing.Platform instead. learn.microsoft.com/en-us/dotnet/core/testing/unit-testing-platform-intro?tabs=dotnetcli
