### ISSUE TITLE
Feature request - add custom data to TRX result output - extend TestResultType

### ISSUE THREAD

**Issue by robdalsanto** [microsoft/vstest#4157]
We have some automated tests we are trying to use to measure and track functional performance in a specific area. Some of what we want is already in the TRX file, e.g. "Duration". It would be helpful if we could add additional properties, so we are not trying to parse the StdOut of the TRX. 

One mechanism I could imagine is to extend the TestContext to have an additional Dictionary<K,V>, say ResultProperties, which would be included in the TRX. We are considering a custom TFS Dashboard widget to extract and display this information.

**Comment by nohwnd** [comment]
This is a new feature and won't be implemented, we are focusing on adding new features to Testing.Platform instead. https://aka.ms/testingplatform
