### ISSUE TITLE
Unhelpful/misleading error message

### ISSUE THREAD

**Issue by matkoch** [microsoft/vstest#4194]
- After install of .NET 7
- Projects with `net5.0`
- Macbook M1

```
Could not find 'dotnet' host for the 'X64' architecture.

You can resolve the problem by installing the 'X64' .NET.

The specified framework can be found at:
  - https://aka.ms/dotnet-download
```

**Comment by DamianSuess** [comment]
On my windows machine, I do have the .NET 6 x64 installed and I'm getting the same error message. Or, am I missing something?

```
Runtime Environment:
 OS Name:     ubuntu
 OS Version:  20.04
 OS Platform: Linux
 RID:         ubuntu.20.04-x64
 Base Path:   /usr/share/dotnet/sdk/6.0.406/

Host:
  Version:      6.0.14
  Architecture: x64
  Commit:       2a90daa2cc

.NET SDKs installed:
  3.1.421 [/usr/share/dotnet/sdk]
  5.0.408 [/usr/share/dotnet/sdk]
  6.0.406 [/usr/share/dotnet/sdk]
```

**Comment by MarcoRossignoli** [comment]
> On my windows machine

The `dotnet --info` you've posted looks like is from Linux.

**Comment by vitek-karas** [comment]
@DamianSuess could you please specify in more detail what you're trying to run (and where) and when do you get the failure?
And also - how did you install the .NET SDK?

**Comment by DamianSuess** [comment]
This occurs when attempting to run unit tests on VS2022 v17.5.0 Enterprise using the `testEnvironments.json` feature wired to my WSL2 Ubuntu-20.04 distribution.

* The test environment was configured using the steps found on: https://learn.microsoft.com/en-us/visualstudio/test/remote-testing?view=vs-2022
* Installed .NET SDK using, `sudo apt-get update && sudo apt-get install -y dotnet-sdk-6.0`

The `testEnvironment.json` contains:

```json
{
  "version": "1",
  "environments": [
    {
      "name": "WSL Ubuntu",
      "type": "wsl",
      "wslDistribution": "Ubuntu-20.04"
    }
  ]
}
```

Output from "Tests" after attempting to run any unit test:

```
Building Test Projects
Executing test method: MyNameSpace.TestNameHere
========== Starting test run ==========
Could not find 'dotnet' host for the 'X64' architecture.

You can resolve the problem by installing the 'X64' .NET.

The specified framework can be found at:
  - https://aka.ms/dotnet-download

Could not find 'dotnet' host for the 'X64' architecture.

You can resolve the problem by installing the 'X64' .NET.

The specified framework can be found at:
  - https://aka.ms/dotnet-download

========== Test run aborted: 0 Tests (0 Passed, 0 Failed, 0 Skipped) run in < 1 ms ==========
```

**Comment by vitek-karas** [comment]
@MarcoRossignoli this is something you will have to look at, I have no idea how the testhost resolution works with the WSL target.

**Comment by MarcoRossignoli** [comment]
>Correct, ran from Windows using WSL2
Let me know if you need any more info; happy to help.

Oh sorry I've misunderstood, now it's clear. 

@AbhitejJohn do you have some info on it?

**Comment by AbhitejJohn** [comment]
@DamianSuess : Could you also set logging level under Test->Options to "Diagnostics" and share the contents of Output->Tests with us please? Please feel free to log a [developer community feedback ticket](https://developercommunity.visualstudio.com/home) so uploading some of this information is easier in terms of privacy.

**Comment by DamianSuess** [comment]
I wish I had seen this request before shutting down yesterday because this morning it's "magically" working again. As a fellow dev, it bugs me to provide that kind of response & I'm trying to shake the tree w/ WSL and VSTest to reproduce the issue.
