### ISSUE TITLE
Expand results by default in html log output or make expand button more visible

### ISSUE THREAD

**Issue by SrS2225a** [microsoft/vstest#4197]
## Describe the bug

So I am using the MSTest for framework for visual studio 2022 to run a few tests for QA. I want the data in a html format to easily keep track of the tests. It would show the failed test results just fine, but I want it to show which tests were ran as well, which are not displayed.

I found that the data I want is there in the html file, but for some reason MSTest would hide that data by default. How can I get MSTest to show this data? This is what it shows and what I actually want: https://imgur.com/a/LCW3zyR

## Steps To Reproduce

Provide the steps to reproduce the behavior:
1. Enable html logging in your .runsettings file https://learn.microsoft.com/en-us/visualstudio/test/configure-unit-tests-by-using-a-dot-runsettings-file?view=vs-2022#loggerrunsettings-element
2. In the test explorer, click on "Run all tests"
3. Open the saved html file in the root of the project under the folder "TestResults"
4. No data will be displayed showing each test result

## Expected behavior
MSTest shows each test ran

## Actual behavior
MSTest instead would hide this data

## Additional context
MSTest hides this data by adding a css property `display: none` to the div that holds each test ran. It should not add such a property but it does

**Comment by SrS2225a** [comment]
Yes, that is exactly right. The list will not be expanded by default. The only way how is to change the display property that is hiding it as you said

**Comment by nohwnd** [comment]
It looks like this now, expanding it by default would change the behavior for people who want it closed.

![image](https://github.com/microsoft/vstest/assets/5735905/018fd39a-c287-4389-b189-83fbf0b24fb5)


This is a new feature and won't be implemented, we are focusing on adding new features to Testing.Platform instead. learn.microsoft.com/en-us/dotnet/core/testing/unit-testing-platform-intro?tabs=dotnetcli
