### ISSUE TITLE
Test Execution Command Line Tool Version 15.9.0 is unable to execute TestRunParameter option.

### ISSUE THREAD

**Issue by samibinsami** [microsoft/vstest#4201]
## Test Execution Command Line Tool Version 15.9.0 is unable to execute TestRunParameter option.

The command to pass TestRunParameter is mentioned [here](https://github.com/microsoft/vstest/blob/main/docs/RunSettingsArguments.md).

Using this doc i am executing the command in cmd:
dotnet test  -- TestRunParameters.Parameter(name=\"target_branch\", value=\"dev\")

but this command is returning error saying 'One or more runsettings provided contain invalid token'

## Steps to reproduce
 
install dotnet core 2.1.56 sdk.
Add an MsTest project. 
Now from cmd, execute the command: dotnet test  -- TestRunParameters.Parameter(name=\"target_branch\", value=\"dev\")
The above command will throw an exception on cmd which will say 'One or more runsettings provided contain invalid token'

## Expected behavior

The above mentioned command should pass TestRunParameters to TestContext.Properties dictionary.

## Actual behavior

Command is returning error 'One or more runsettings provided contain invalid token'

## Diagnostic logs

'One or more runsettings provided contain invalid token'

## Environment

.NET Core SDK (reflecting any global.json):
 Version:   2.1.526
 Commit:    26a950bee8

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.19045
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\2.1.526\

Host (useful for support):
  Version: 2.1.30
  Commit:  5e17f34de8

.NET Core SDKs installed:
  2.1.526 [C:\Program Files\dotnet\sdk]

.NET Core runtimes installed:
  Microsoft.AspNetCore.All 2.1.30 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.App 2.1.30 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 2.1.30 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]

**Comment by MarcoRossignoli** [comment]
can you try to escape like:
```bash
dotnet test -- TestRunParameters.Parameter(name=\"target_branch\", value=\"dev\")
```

PS. I see you're using a no more supported version of .NET Core and you're on a very old version of the test tool(15.9.0), my advice is to move the the new supported versions 17.4.0 and .NET 6.0 

Here you can see the official lifecycle learn.microsoft.com/en-us/lifecycle/products/microsoft-net-and-net-core

**Comment by MarcoRossignoli** [comment]
I'm going to update the documentation excluding netcore2.1 from the support of this feature.

**Comment by samibinsami** [comment]
Also can we make it clear somewhere that if you want to pass parameter to test project in .net core 2.1 sdk then you need to use dotnet vstest command and pass runsettings file. There is no way to pass TestRunParameter through dotnet vstest command in .net core 2.1 sdk.

**Comment by MarcoRossignoli** [comment]
`dotnet vstest` it's been superseded by `dotnet test` https://learn.microsoft.com/en-us/dotnet/core/tools/dotnet-vstest and as said above we don't usually update documentation for non supported runtimes. In this case we forgot to add the "starting version" for the feature.
