### ISSUE TITLE
FrameworkReferenceResolution fails with new Microsoft.NET.Test.Sdk

### ISSUE THREAD

**Issue by bernd5** [microsoft/vstest#4212]
## Description

See e.g. https://stackoverflow.com/questions/73126958/cannot-read-the-external-namespaces-microsoft-aspnetcore-mvc-in-roslyn-in

## Steps to reproduce

Try to load a cs project with `Microsoft.Build.Locator`.

## Expected behavior

It should work like in a non-test project.

## Actual behavior

Following (or similar) error is reported:
```
System.IO.FileNotFoundException: Could not load file or assembly 'NuGet.Frameworks, Version=5.11.1.5, Culture=neutral, PublicKeyToken=31bf3856ad364e35'. The system cannot find the file specified.

File name: 'NuGet.Frameworks, Version=5.11.1.5, Culture=neutral, PublicKeyToken=31bf3856ad364e35'
   at Microsoft.NET.Build.Tasks.ProcessFrameworkReferences.ExecuteCore()
   at Microsoft.NET.Build.Tasks.TaskBase.Execute()
...
```

**Comment by MarcoRossignoli** [comment]
I think it's a dup of https://github.com/microsoft/vstest/issues/3154 I'll investigate soon to confirm.

**Comment by bernd5** [comment]
It could be the case

**Comment by MarcoRossignoli** [comment]
I cannot repro in local(if you've a full repro would be good) but can you try to override the deps with the needed one? Like:
```xml
<PackageReference Include="NuGet.Frameworks" Version="5.11.1.5" />
```
And yes we take dependency on `Nuget.Framework` today https://www.nuget.org/packages/Microsoft.TestPlatform.ObjectModel/

**Comment by bernd5** [comment]
Here: https://github.com/bernd5/test_sdk_issue_4212 you can find a repo.
You would need only to adjust the csproj path...

**Comment by bernd5** [comment]
It seems to work if I reference `<PackageReference Include="NuGet.Frameworks" Version="6.3.0" />` explicitly

**Comment by MarcoRossignoli** [comment]
> It seems to work if I reference <PackageReference Include="NuGet.Frameworks" Version="6.3.0" /> explicitly

I think at the moment it's the only solution we have, we don't have plat to remove it.

Feel free to close if solved.
