### ISSUE TITLE
aka.ms/vstest-*** links to the archived `vstest-docs` repository.

### ISSUE THREAD

**Issue by teo-tsirpanis** [microsoft/vstest#4215]
They should link to the corresponding file in https://github.com/microsoft/vstest/tree/main/docs/.

**Comment by Evangelink** [comment]
Hi @teo-tsirpanis, thanks for letting us know.

**Comment by Evangelink** [comment]
Hi @teo-tsirpanis, links are now fixed! Thank you for letting us know!
