### ISSUE TITLE
TrxLogger throws a NullReferenceException when using TrxLogger.Initialize(TestLoggerEvents, string)

### ISSUE THREAD

**Issue by Saeras** [microsoft/vstest#4224]
## Description

`TrxLogger.Initialize(TestLoggerEvents, string)` does not set the `_parametersDictionary` prior to exit. This dictionary is only set in the Dictionary overload on [this line](https://github.com/microsoft/vstest/blob/main/src/Microsoft.TestPlatform.Extensions.TrxLogger/TrxLogger.cs#L149). This causes the TrxLogger to fail to complete and throw a `NullReferenceException` when it finds that the `_parametersDictionary` is null in `TrxLogger.AcquireTrxFileNamePath(out bool)` on [this line](https://github.com/microsoft/vstest/blob/main/src/Microsoft.TestPlatform.Extensions.TrxLogger/TrxLogger.cs#L483).

It appears that this issue was introduced under #282 when the `ITestLoggerWithParameters` interface was originally applied to the TrxLogger type.

## Steps to reproduce

Create a sample test:
```
[TestClass]
public class TrxLoggerTests
{
    public TestContext TestContext { get; set; }

    [TestMethod]
    public void TrxLogger_Creates_File_With_ITestLoggerWithParameters_Initialize()
    {
        var logger = new TrxLogger();
        var events = new MyEvents();
        string output = Path.Combine(TestContext.TestRunDirectory, nameof(ITestLoggerWithParameters));
        logger.Initialize(events, new Dictionary<string, string?>
        {
            [DefaultLoggerParameterNames.TestRunDirectory] = output
        });

        Directory.CreateDirectory(output);
        Assert.IsFalse(Directory.EnumerateFiles(output, "*.trx").Any());
        events.Report();
        Assert.IsTrue(Directory.EnumerateFiles(output, "*.trx").Any());
    }

    [TestMethod]
    public void TrxLogger_Creates_File_With_ITestLogger_Initialize()
    {
        var logger = new TrxLogger();
        var events = new MyEvents();
        string output = Path.Combine(TestContext.TestRunDirectory, nameof(ITestLogger));
        logger.Initialize(events, output);

        Directory.CreateDirectory(output);
        Assert.IsFalse(Directory.EnumerateFiles(output, "*.trx").Any());
        events.Report();
        Assert.IsTrue(Directory.EnumerateFiles(output, "*.trx").Any());
    }
}
```

Creating a sample `TestLoggerEvents` implementation as follows:
```
public class MyEvents : TestLoggerEvents
{
    public override event EventHandler<TestRunMessageEventArgs> TestRunMessage;
    public override event EventHandler<TestRunStartEventArgs> TestRunStart;
    public override event EventHandler<TestResultEventArgs> TestResult;
    public override event EventHandler<TestRunCompleteEventArgs> TestRunComplete;
    public override event EventHandler<DiscoveryStartEventArgs> DiscoveryStart;
    public override event EventHandler<TestRunMessageEventArgs> DiscoveryMessage;
    public override event EventHandler<DiscoveredTestsEventArgs> DiscoveredTests;
    public override event EventHandler<DiscoveryCompleteEventArgs> DiscoveryComplete;

    public void Report()
    {
        TestRunStart?.Invoke(this,
            new TestRunStartEventArgs(
                new TestRunCriteria(new[] { "my_source" }, 500)));
        var testCase = new TestCase("passing_test", new Uri("sample://uri"), "source");
        TestResult?.Invoke(this,
            new TestResultEventArgs(
                new Microsoft.VisualStudio.TestPlatform.ObjectModel.TestResult(testCase)
                {
                    Outcome = TestOutcome.Passed
                }));
        TestRunComplete?.Invoke(this,
            new TestRunCompleteEventArgs(
                new TestRunStatistics(new Dictionary<TestOutcome, long>
                {
                    [TestOutcome.Passed] = 1
                }),
                false,
                false,
                null,
                new System.Collections.ObjectModel.Collection<AttachmentSet>(),
                TimeSpan.FromMilliseconds(13)));
    }
}
```

## Expected behavior

- `TrxLogger_Creates_File_With_ITestLoggerWithParameters_Initialize` creates a trx file.
- `TrxLogger_Creates_File_With_ITestLogger_Initialize` creates a trx file.

## Actual behavior

- `TrxLogger_Creates_File_With_ITestLoggerWithParameters_Initialize` creates a trx file.
- `TrxLogger_Creates_File_With_ITestLogger_Initialize` throws a `NullReferenceException` from `TrxLogger.AcquireTrxFileNamePath(out bool)` when executing.

## Diagnostic logs

Stack trace from the NullReferenceException:
```
   at Microsoft.VisualStudio.TestPlatform.Extensions.TrxLogger.TrxLogger.AcquireTrxFileNamePath(Boolean& shouldOverwrite)
   at Microsoft.VisualStudio.TestPlatform.Extensions.TrxLogger.TrxLogger.ReserveTrxFilePath()
   at Microsoft.VisualStudio.TestPlatform.Extensions.TrxLogger.TrxLogger.TestRunCompleteHandler(Object sender, TestRunCompleteEventArgs e)
   at TestProject1.UnitTest1.MyEvents.Report() in C:\Development\Git\TestProject1\TestProject1\UnitTest1.cs:line 36
```

## Environment

Windows 10 21H2
VS 2022 v17.2.6
Microsoft.TestPlatform.Extensions.TrxLogger v17.4.1

**Comment by Evangelink** [comment]
Hi @Saeras , thank you for the bug report. We will investigate it soon and get back to you.

**Comment by MarcoRossignoli** [comment]
@Saeras do you have a "production" use case for this exception?
In case of `ITestLogger ` and current implementation we can throw but we don't have any case at the moment because it won't be never created for the `TrxLogger` for what I see https://github.com/microsoft/vstest/blob/main/src/Microsoft.TestPlatform.CrossPlatEngine/Client/TestLoggerManager.cs#L588-L602

**Comment by Saeras** [comment]
The tests I put into the initial issue description were intended to duplicate a "production" use case that I was working through. I ran across the NRE while putting those tests together. Thanks for the fix!
