### ISSUE TITLE
Run tests with specified datacollector loads unexpected assembly

### ISSUE THREAD

**Issue by daveMueller** [microsoft/vstest#4226]
## Description

This is more a question than an actual issue. I would like to know how `vstest` loads `datacollectors`? Even though I specify the friendly name of the collector to use, `vstest` loads another assembly that ends with the name `*collector`. 
Sure I've seen the note about the DataCollector Assembly Naming Convention [here](https://github.com/Microsoft/vstest-docs/blob/main/docs/extensions/datacollector.md#extend-datacollector), but still I don't really get, why `vstest` loads the assembly for the whole test run even when the specified friendly name doesn't match. And even though the assembly doesn't have a type extending `TestPlatform.ObjectModel.DataCollection.DataCollector` at all.

I ask this because we have an issue related to that [https://github.com/coverlet-coverage/coverlet/issues/1386](https://github.com/coverlet-coverage/coverlet/issues/1386).  Our actual datacollector tries to load the `*collector` assembly which now fails because the `*collector` assembly is already loaded by `vstest`.

## Steps to reproduce

1. Clone repo [https://github.com/daveMueller/CoverletIssue1386Repro](https://github.com/daveMueller/CoverletIssue1386Repro)
2. Run  `dotnet test --collect:"XPlat Code Coverage"` 

## Expected behavior

`vstest` only loads data collector specified by the friendly name parameter for the test run.

## Actual behavior

`vstest` loads all assemblies that end with `*collector` for the whole test run.

## Diagnostic logs

```
...
TpTrace Information: 0 : 14104, 1, 2022/12/25, 01:58:00.252, 44863654672, datacollector.dll, AssemblyResolver.AddSearchDirectories: Adding more searchDirectories D:\Repos\CoverletIssue1386Repro\Issue1386Tests\bin\Debug\net6.0,C:\Program Files\dotnet\sdk\7.0.101
TpTrace Information: 0 : 14104, 1, 2022/12/25, 01:58:00.252, 44863654910, datacollector.dll, AssemblyResolver.AddSearchDirectories: Adding more searchDirectories C:\Users\David\.nuget\packages\coverlet.collector\3.2.0\build\netstandard1.0,C:\Program Files\dotnet\sdk\7.0.101
TpTrace Information: 0 : 14104, 1, 2022/12/25, 01:58:00.252, 44863655369, datacollector.dll, AssemblyResolver.AddSearchDirectories: Adding more searchDirectories C:\Program Files\dotnet\sdk\7.0.101\Extensions,C:\Program Files\dotnet\sdk\7.0.101
TpTrace Information: 0 : 14104, 1, 2022/12/25, 01:58:00.252, 44863655604, datacollector.dll, AssemblyResolver.AddSearchDirectories: Adding more searchDirectories C:\Program Files\dotnet\sdk\7.0.101\Extensions,C:\Program Files\dotnet\sdk\7.0.101
TpTrace Information: 0 : 14104, 1, 2022/12/25, 01:58:00.252, 44863658159, datacollector.dll, AssemblyResolver.OnResolve: Issue1386collector: Resolving assembly.
TpTrace Information: 0 : 14104, 1, 2022/12/25, 01:58:00.252, 44863658576, datacollector.dll, AssemblyResolver.OnResolve: Issue1386collector: Searching in: 'D:\Repos\CoverletIssue1386Repro\Issue1386Tests\bin\Debug\net6.0'.
TpTrace Information: 0 : 14104, 1, 2022/12/25, 01:58:00.256, 44863698905, datacollector.dll, AssemblyResolver.OnResolve: Issue1386collector: Loading assembly 'D:\Repos\CoverletIssue1386Repro\Issue1386Tests\bin\Debug\net6.0\Issue1386collector.dll'.
TpTrace Information: 0 : 14104, 1, 2022/12/25, 01:58:00.256, 44863700681, datacollector.dll, AssemblyResolver.OnResolve: Resolved assembly: Issue1386collector, from path: D:\Repos\CoverletIssue1386Repro\Issue1386Tests\bin\Debug\net6.0\Issue1386collector.dll
...
TpTrace Warning: 0 : 14104, 1, 2022/12/25, 01:58:00.331, 44864451463, datacollector.dll, [coverlet]Unable to instrument module: D:\Repos\CoverletIssue1386Repro\Issue1386Tests\bin\Debug\net6.0\Issue1386collector.dll
System.IO.IOException: The process cannot access the file 'D:\Repos\CoverletIssue1386Repro\Issue1386Tests\bin\Debug\net6.0\Issue1386collector.dll' because it is being used by another process.
   at Microsoft.Win32.SafeHandles.SafeFileHandle.CreateFile(String fullPath, FileMode mode, FileAccess access, FileShare share, FileOptions options)
   at Microsoft.Win32.SafeHandles.SafeFileHandle.Open(String fullPath, FileMode mode, FileAccess access, FileShare share, FileOptions options, Int64 preallocationSize, Nullable`1 unixCreateMode)
   at System.IO.Strategies.OSFileStreamStrategy..ctor(String path, FileMode mode, FileAccess access, FileShare share, FileOptions options, Int64 preallocationSize, Nullable`1 unixCreateMode)
   at System.IO.Strategies.FileStreamHelpers.ChooseStrategyCore(String path, FileMode mode, FileAccess access, FileShare share, FileOptions options, Int64 preallocationSize, Nullable`1 unixCreateMode)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access)
   at Coverlet.Core.Helpers.FileSystem.NewFileStream(String path, FileMode mode, FileAccess access) in /_/src/coverlet.core/Helpers/FileSystem.cs:line 52
   at Coverlet.Core.Instrumentation.Instrumenter.InstrumentModule() in /_/src/coverlet.core/Instrumentation/Instrumenter.cs:line 211
   at Coverlet.Core.Instrumentation.Instrumenter.Instrument() in /_/src/coverlet.core/Instrumentation/Instrumenter.cs:line 153
   at Coverlet.Core.Coverage.PrepareModules() in /_/src/coverlet.core/Coverage.cs:line 135
```
[log.datacollector.22-12-25_01-58-00_08558_1.txt](https://github.com/microsoft/vstest/files/10299305/log.datacollector.22-12-25_01-58-00_08558_1.txt)

**Comment by Evangelink** [comment]
Hi @daveMueller, thank you for the bug report. We will investigate it soon and get back to you. @MarcoRossignoli could you please have a look?

**Comment by MarcoRossignoli** [comment]
> I would like to know how vstest loads datacollectors? 

Hi @daveMueller 😄 

unfortunately 

`vstest only loads data collector specified by the friendly name parameter for the test run.`

is not the current behavior. 

When the datacollector process starts it will go through "some" folders and it will load all "files" that end with  `@"Collector.dll";` it will load it in "some order" and only one version will be loaded and used(if there're more than one version for the same collector we will load the first/newest and all others will be discarded). We don't "unload" unused libraries/extensions because we're in the main appdomain.

The next step is to "check and setup the enabled ones".

So if you need to test don't create assemblies that end with  `@"Collector.dll";` or it will be recognized as file that contains some datacollectors.

**Comment by daveMueller** [comment]
> When the datacollector process starts it will go through "some" folders and it will load all "files" that end with @"Collector.dll"; 

Thanks @MarcoRossignoli 😃, is there a way to make an exclusion to this automatic loading of `*collector.dll`? Because for `coverlet` we can't really prevent the users from naming their assemblies `*collector.dll`. And if they do we get the exception mentioned above.

**Comment by MarcoRossignoli** [comment]
> is there a way to make an exclusion to this automatic loading of *collector.dll

nope for what I know...current test platform is by design based on "dynamic loading using file naming convention".

@nohwnd do you know some workaround?

**Comment by nohwnd** [comment]
There isn't an option for loading exclusions. In hindsight I can see how that would be useful.
