### ISSUE TITLE
Test built with MSTest V1 adapter using DeploymentItem Attribute fail

### ISSUE THREAD

**Issue by mayankbansal018** [Microsoft/vstest#423]
## Description
> Test using DeploymentItem attribute abort

## Steps to reproduce
> Create unit test using legacy mstest v1 framework
> Add deploymentitem attribute to it, & run test

## Expected behavior
> Test should pass

## Actual behavior
> Test fail Error: The active Test Run was aborted

**Comment by mayankbansal018** [comment]
PR raised internally against lab/vsualm https://devdiv.visualstudio.com/DevDiv/_git/VS/pullrequest/55574?path=%2Fsrc&_a=overview

**Comment by sbaid** [comment]
@mayankbansal018 see that PR is committed. pl verify & close.

**Comment by mayankbansal018** [comment]
yes it is commited, closing this issue
