### ISSUE TITLE
Clean up documentation-related code warnings

### ISSUE THREAD

**Issue by stan-sz** [microsoft/vstest#4236]
## Description

In #4231 documentation generation is enabled and some warnings related to code documentation are suppressed. This issue is about cleaning up these suppressions.

**Comment by nohwnd** [comment]
Related PR was merged.

**Comment by Evangelink** [comment]
@nohwnd the related PR add a couple of diagnostic suppression. The goal of this ticket was to remove these suppressions and actually fix code instead.
