### ISSUE TITLE
vstest Maestro publishing fails to push MergedManifest.xml correctly

### ISSUE THREAD

**Issue by mmitche** [microsoft/vstest#4256]
## Description

Vstest builds do not download correctly for .NET's release infrastructure. https://dev.azure.com/dnceng/internal/_build/results?buildId=2086434&view=logs&j=40e1e683-ea82-5be9-b25e-899b65e1c0cb&t=6e491791-6ce2-572a-3132-c49a3995e637&l=1861

```
Downloading asset assets/manifests/microsoft-vstest/17.5.0-ci/MergedManifest.xml
    Failed to download asset, errors shown below:
```

The version number here is wrong (should be the non-stable version number of vstest. Please work with dnceng FR to resolve.

**Comment by nohwnd** [comment]
@mmitche are there any common causes of this? Like the package not being on the feed. I have no idea what to check and you probably know.

**Comment by mmitche** [comment]
@nohwnd It's a bit odd since vstest doesn't use YAML for its builds, but I think what is happening is that the step that publishes to BAR (https://dev.azure.com/devdiv/DevDiv/_build/results?buildId=7160053&view=logs&j=fd490c07-0b22-5182-fac9-6d67fe1e939b&t=1e77462e-7711-551f-cf20-c31b880b493a) does not pass an official build ID, or tell the task that the build is an official build.

https://github.com/dotnet/arcade/blob/main/src/Microsoft.DotNet.Arcade.Sdk/tools/SdkTasks/PublishBuildAssets.proj#L11-L15

This causes the versioning code in arcade to use a dev/ci version, rather than an official version, which causes the manifest to be uploaded to the incorrect spot.

I think the fix would be to pass: OfficialBuildId=<build id> (e.g. 20230106-01) to the task.

**Comment by nohwnd** [comment]
@mmitche Added.

**Comment by nohwnd** [comment]
https://dev.azure.com/devdiv/DevDiv/_build/results?buildId=7207780&view=logs&j=fd490c07-0b22-5182-fac9-6d67fe1e939b&t=1e77462e-7711-551f-cf20-c31b880b493a

Here is a build using the property, does it go to the right place now?

**Comment by mmitche** [comment]
It looks better, but it's not in the right place. The system is claiming that the xml file is in the "dotnet-tools" feed. It looks like vstest skips the promotion pipeline which would do all the uploading to the right places. I think the right thing to do is probably to remove the dotnet-tools push and allow Maestro to do the promotion properly.

**Comment by mmitche** [comment]
@nohwnd The infra looks like it could use a lot of work here.
- Each vstest build generates two different BAR ids, one for source build and one for the other build. It should only generate one with, with a manifest that is a merge of both.
- I don't think it should be manually generating the asset manifest. Instead it should use PushToAzureDevOpsArtifacts for each build job (source build and then the normal build), and the publish to build the asset registry should pick up both sets of packages nicely.

https://github.com/NuGet/NuGet.Client/blob/dev/build/publish.proj#L56 has an example of how NuGet does it. I can give it a shot if you give me access to push to the repo. Unfortunately, though, because your pipelines aren't YAML (is this on your radar?) it will be a bit of a challenge to make upgrades without porting the code changes back to all branches.

**Comment by Evangelink** [comment]
>  because your pipelines aren't YAML (is this on your radar?) 

We are doing the full onboarding to arcade as we speak but it will take some time.

**Comment by mmitche** [comment]
> > because your pipelines aren't YAML (is this on your radar?)
> 
> We are doing the full onboarding to arcade as we speak but it will take some time.

What is your timeline? Including a switch to YAML? If so, then I'd say you should avoid working on this issue (it doesn't currently cause major issues, except delays in staging pipeline approval). The full switch to arcade will resolve the issue. When you switch, all of your manual manifest generation and BAR pushes should disappear.

**Comment by Evangelink** [comment]
> What is your timeline? Including a switch to YAML?

We expect a couple of weeks to a month.

**Comment by Evangelink** [comment]
We are on it and making good progresses (I can point you to the branch if you want).

**Comment by Evangelink** [comment]
Fixed by https://github.com/microsoft/vstest/commit/d18720133f78f78142c87468275ee0694673a4cd
