### ISSUE TITLE
Localization is disabled in Linux builds

### ISSUE THREAD

**Issue by NikolaMilosavljevic** [microsoft/vstest#4305]
## Description

There is an issue with localization in Linux builds - the following property would be initialized to `false`: https://github.com/microsoft/vstest/blob/4cf1986ee6f2c7ec42efdbbda84d16a0435f741b/scripts/build.sh#L149

It seems that specifying `-noloc` would turn on localization, which is the opposite of the switch intent.

On Windows builds, this is working fine as the code is correct: https://github.com/microsoft/vstest/blob/4cf1986ee6f2c7ec42efdbbda84d16a0435f741b/scripts/build.ps1#L97

This affects production of localized vstest binaries in source-build - on Linux machines.

## Steps to reproduce

Run the build on linux machines - do not specify `-noloc`.

## Expected behavior

Localized binaries are produced and packaged together with neutral binaries.

## Actual behavior

No localized binaries are produced.

## Environment

This repros in regular Linux builds, but also in source-build.

**Comment by Evangelink** [comment]
Hi @NikolaMilosavljevic,

We are working on porting our infra to arcade at the moment so I hope this will be automatically fixed once we are done.

**Comment by nohwnd** [comment]
Fixed by https://github.com/microsoft/vstest/commit/d18720133f78f78142c87468275ee0694673a4cd
