### ISSUE TITLE
vstest console wrapper seems to not receive DiscoveryComplete event since 17.2.0

### ISSUE THREAD

**Issue by rouke-broersma** [microsoft/vstest#4326]
## Description

In stryker-net we have not been able to upgrade the TestPlatform since 17.2.0 due to an infinite hang during test discovery.
We had not been able to investigate properly because it was only failing on azure devops for some reason.
I have finally had time to figure out why we weren't getting proper logs in the pipeline, and have found that the reason for the hang is that vstest.console.exe does seem to send the DiscoveryComplete but our wrapper is not receiving it.

## Steps to reproduce

https://github.com/stryker-mutator/stryker-net/pull/2221
https://dev.azure.com/stryker-mutator/Stryker/_build/results?buildId=12695&view=results

## Diagnostic logs

[TestDiscoverer_VsTest-log.txt](https://github.com/microsoft/vstest/files/10837532/TestDiscoverer_VsTest-log.txt)

## Environment

Azure Pipelines hosted agent - windows latest
dotnet framework 4.8

**Comment by nohwnd** [comment]
@rouke-broersma have you been able to ever repro locally?

**Comment by rouke-broersma** [comment]
I haven't tried recently, but as far as I remember from past attempts no, it only fails in the pipeline.

**Comment by nohwnd** [comment]
I've updated the packages to 17.5.0 and I am running .CLI directly from your repo against your xunit test project in your integration tests. 

```diff
diff --git a/src/Directory.Packages.props b/src/Directory.Packages.props
index b7e74947..01eee8fe 100644
--- a/src/Directory.Packages.props
+++ b/src/Directory.Packages.props
@@ -22,15 +22,15 @@
     <PackageVersion Include="Spectre.Console.Analyzer" Version="0.46.0" />
     <PackageVersion Include="System.Net.Http.Json" Version="7.0.0" />
     <PackageVersion Include="Microsoft.CodeAnalysis.CSharp" Version="4.5.0" />
-    <PackageVersion Include="Microsoft.TestPlatform" Version="17.2.0" />
-    <PackageVersion Include="Microsoft.TestPlatform.ObjectModel" Version="17.2.0" />
-    <PackageVersion Include="Microsoft.TestPlatform.Portable" Version="17.2.0" />
-    <PackageVersion Include="Microsoft.TestPlatform.TranslationLayer" Version="17.2.0" />
+    <PackageVersion Include="Microsoft.TestPlatform" Version="17.5.0" />
+    <PackageVersion Include="Microsoft.TestPlatform.ObjectModel" Version="17.5.0" />
+    <PackageVersion Include="Microsoft.TestPlatform.Portable" Version="17.5.0" />
+    <PackageVersion Include="Microsoft.TestPlatform.TranslationLayer" Version="17.5.0" />
     <PackageVersion Include="TestableIO.System.IO.Abstractions.Wrappers" Version="19.1.18" />
     <PackageVersion Include="Microsoft.Extensions.Logging" Version="7.0.0" />
   </ItemGroup>
   <ItemGroup>
-    <PackageVersion Include="Microsoft.NET.Test.Sdk" Version="17.3.2" />
+    <PackageVersion Include="Microsoft.NET.Test.Sdk" Version="17.5.0" />
     <PackageVersion Include="coverlet.collector" Version="3.2.0" />
     <PackageVersion Include="coverlet.msbuild" Version="3.2.0" />
     <PackageVersion Include="Moq" Version="4.18.4" />
```

I am hitting the breakpoint on DiscoveryEventHandler. Any tips how to repro?

**Comment by rouke-broersma** [comment]
The xunit project is dotnet core, it is only not working on dotnet framework. The dotnet framework integration test project is here: https://github.com/stryker-mutator/stryker-net/tree/master/integrationtest/TargetProjects/NetFramework/FullFrameworkApp.Test

**Comment by rouke-broersma** [comment]
Did you manage to repro with these instructions?

**Comment by rouke-broersma** [comment]
@nohwnd If I can help in any way let me know :)

**Comment by nohwnd** [comment]
I've spent a month trying to move our repo to new infra. Now I can get back to this.

**Comment by rouke-broersma** [comment]
No worries, I appreciate whatever time you can find! Just making sure there isn't something I can do to help or that I'm not the one blocking a successful investigation.

**Comment by rouke-broersma** [comment]
Unrelated changes in https://github.com/stryker-mutator/stryker-net/pull/2400 seem to have fixed the issue for some reason, we are no longer blocked. However I want to note that we have been blocked with the exact same behavior in the past before.

**Comment by voroninp** [comment]
Hm... I have the same issue with `dotnet test -l` when runing it locally.

[NotAllEvents.zip](https://github.com/microsoft/vstest/files/15118946/NotAllEvents.zip)

run from `root` directory `dotnet test -t -l json ./tools/Json.TestLogger.Tests` and see that `DiscoveryComplete` is not called.
