### ISSUE TITLE
ITestExecutor Cancel does not appear to be called

### ISSUE THREAD

**Issue by jpribele** [microsoft/vstest#4329]
## Description

The Cancel method of an ITestExecutor does not appear to be called

## Steps to reproduce

Create an implementation of ITestExecuter
Create a long running test that test executer would execute
Run a the long running test
Hit the cancel button in the text explorer

## Expected behavior

Cancel method is invoke

## Actual behavior

Nothing

## Environment

Visual Studio 2022 Version 17.5.0

**Comment by MikeSchulze** [comment]
I run into the same issue `public void Cancel()` is not called when pressing the stop button on Test Explorer

**Comment by nohwnd** [comment]
This is by-design (or rather: too late to change it now).

**Comment by nohwnd** [comment]
I am not, this was done to keep the interactive experience in VS responsive. When abort is pressed everything tears down as fast as possible.

**Comment by MikeSchulze** [comment]
The problem is that if a test hangs for some unknown reason, it must be possible to cancel the test execution. Otherwise, this would mean I would have to close and reopen the IDE to solve the problem, which is very inconvenient.
