### ISSUE TITLE
Marking .trx unit tests as retried?

### ISSUE THREAD

**Issue by AndrewCraswell** [microsoft/vstest#4334]
## Description

Apologies if this is not the correct place for this question. I am working on a end-to-end testing plugin for Playwright to allow test results to be exported as VSTest `.trx` files to be uploaded the Azure Pipelines test report. Allowing us to use this format would give options that aren't available to alternative test result formats like JUnit. Namely, we want to support attachments (images, video, diagnostics) which JUnit doesn't support. We've got this functionality built out but are having a couple problems understanding the .trx file schema.

I want to be able to identify when a specific test failed and was retried. Playwright allows us to configure how many retry attempts should be made, but we aren't seeing that detail when opening the file in Visual Studio Test Explorer or viewing the report in Azure Pipelines. I want to be able to identify flaky tests, but not sure if that can be done by using just the `.trx` schema. I couldn't find the actual schema definition for `.trx` files, so am not sure how to proceed.

**Comment by Evangelink** [comment]
The trx file format is quite old and inherited but sadly we don't have its specification/schema. Because of the many tools parsing it, we usually avoid any change to it.

@nohwnd Any extra info we could provide here?

**Comment by nohwnd** [comment]
This is a new feature and won't be implemented, we are focusing on adding new features to Testing.Platform instead. https://aka.ms/testingplatform
