### ISSUE TITLE
`dotnet test` leaves residual folders

### ISSUE THREAD

**Issue by RussKie** [microsoft/vstest#4344]
Running `dotnet-coverage collect` generates a lot of empty folders, which pollute the drive.

```
dotnet dotnet-coverage collect --settings ./eng/CodeCoverage.config --output ./artifacts/TestResults/ "build.cmd -test -bl"
```

![image](https://user-images.githubusercontent.com/4403806/225175816-99cfd4ae-3c60-4a39-934d-008d99f01226.png)

```powershell
PS D:\dev> dotnet dotnet-coverage --version
Microsoft (R) Code Coverage Command Line Tool (x64)
Copyright (c) Microsoft Corporation. All rights reserved.

17.6.9+3b0f2ec653d1973d7d140557f01122da5acfc444
```

**Comment by RussKie** [comment]
> Those folders are generated by Test Platform not by dotnet-coverage tool. You will see those even when you run `build.cmd -test -bl`.

Indeed, thank you.
Is this still the right repo to report the issue? Or should I raise it somewhere else?

**Comment by jakubch1** [comment]
I've transferred it to vstest already.

**Comment by MarcoRossignoli** [comment]
@RussKie  by design the test platform creates a random folder(guid) to avoid to override previous test sessions. It's a by-design behavior.
There's already an open issue for this behavior but at the moment we didn't reach an internal agreement on the design https://github.com/microsoft/vstest/issues/2378

**Comment by RussKie** [comment]
@MarcoRossignoli the issue is not the folder name, I fully understand the need for a random name. 

We have several hundred of projects that multi-target up-to 7 TFMs. The issue is that I have hundreds upon hundreds of **empty folders** polluting my repo every time I run tests. Those should be cleaned up.

**Comment by MarcoRossignoli** [comment]
> We have several hundred of projects that multi-target up-to 7 TFMs. The issue is that I have hundreds upon hundreds of empty folders polluting my repo every time I run tests. Those should be cleaned up.

folders shouldn't be 'empty' I suppose that `build.cmd`(arcade) is doing some duty at the end moving files around. We don't clean for the above reason users can run and compare different test run so we cannot "impose a cleanup workflow".

**Comment by RussKie** [comment]
I've run some tests on a non-Arcade repo, and all the "guid"-folders had cobertura.xml in them. So, it does look like something the Arcade is doing. I'll dig in to it when I have some spare time.

Thank you for your time.
