### ISSUE TITLE
dotnet test in RC4 has the working directory set to the output directory

### ISSUE THREAD

**Issue by pranavkm** [Microsoft/vstest#435]
## Description
Not entirely sure if this belongs here, but I specifically see the issue as part of test runs and not while running (`dotnet run`) the application.
As part of upgrading AspNetCore's repositories to use the RC4 CLI, I noticed that the current directory during test runs is set to the output directory (`AppRoot\bin\Debug\netcoreapp1.1`) as opposed to the directory from which the test command is called.

## Steps to reproduce
> What steps can reproduce the defect?
1. Create a test project 
```xml
<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>netcoreapp1.0</TargetFramework>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.NET.Test.Sdk" Version="15.0.0-*" />
    <PackageReference Include="xunit.runner.visualstudio" Version="2.2.0-*" />
    <PackageReference Include="xunit" Version="2.2.0-*" />
  </ItemGroup>
</Project>
```

```C#
using System;
using System.IO;
using Xunit;

namespace ConsoleApp
{
    public class Test
    {
        [Fact]
        public void TestMethod()
        {
            Assert.False(true, "Expected path " + Directory.GetCurrentDirectory());
        }
    }
}
```

2. Run the test using the RC3 CLI (`dotnet test`). The test failure should print out the working directory path which would be the project directory.
3. Run the test using an RC4 CLI. The working directory in the test is `$projectDirectory\bin\Debug\netcoreapp1.0`.
4. I don't see the same issue if I simply print `Directory.GetCurrentDirectory()` as part of `dotnet run` using the two CLI.

> Please share the setup, commandline for vstest.console, sample project, target

RC3 CLI: `1.0.0-rc3-004530`
RC4 CLI: `1.0.0-rc4-004756`

**Comment by pranavkm** [comment]
cc @natemcmaster

**Comment by natemcmaster** [comment]
Should be the directory containing the csproj, if I understood correctly the intent of https://github.com/Microsoft/vstest/pull/346.

**Comment by pranavkm** [comment]
@natemcmaster #346 makes it seem like this was intentionally changed to point to the output directory.

**Comment by NTaylorMullen** [comment]
With how it is today (path not being next to csproj) if you want to work around https://github.com/Microsoft/vstest/issues/196 you must treat the xunit.runner.json as content so it makes its way to the output directory. If it's changed to be at the csproj level you do not need that extra workaround.

**Comment by natemcmaster** [comment]
@pranavkm good point. The PR description says "source directory" which at first I though was the project dir, but the code changes ensure working directory is the test assembly location.

@NTaylorMullen good to know. Requiring the build to copy xunit.runner.json to output is consistent with how it worked in project.json

**Comment by smadala** [comment]
Closing this as behavior change was intentional.
