### ISSUE TITLE
vstest server mode, vstest.console in-process mode etc.. Suggestions for reducing vstest time cost during multiple sessions

### ISSUE THREAD

**Issue by rouke-broersma** [microsoft/vstest#4355]
## Description

Recently I've seen some references to a vstest server mode, vstest.console in-process mode etc. These new features seem extremely relevant to stryker.net. Our biggest concern is duration of a mutation testrun, because we run a project's unit tests many many times for all different possible mutants in a project (thousands of times for medium to large projects). We use the vstest console wrapper to communicate with vstest so we can discover test results. However due to the way vstest works it takes us seconds per mutant to spin up and down a vstest session. We do reuse the vstest.console sessions but as far as we know there is no way to reuse the testhost and other processes used during a test session.

These new features appear to be sort of related to keeping a testhost around for longer. Perhaps I'm wrong though.
Or perhaps there are existing features that could help us out reduce the time impact of using vstest.

Any hints to reducing the time used by up a single vstest session would have immense impact on our project.

**Comment by nohwnd** [comment]
None of these features are good candidate for you unfortunately. in-process vstest.console is meant to make the amount serialization smaller, by avoiding serialization between testwindowstorehost (what backs up TestExplorer) and vstest.console, by moving it in process. Pre-start of test hosts, makes the run a bit more optimized for serial run on multi core computers by starting and initializing the next testhost while the active testhost is running tests. And then there is testhost pool which makes you reuse the same testhost between single discovery, and a single run of the same dll, but not between multiple runs, or between different assemblies.

**Comment by rouke-broersma** [comment]
@nohwnd pre-start of test host sounds extremely useful actually! We don't need to recompile between test sessions, we change which mutants are active based on environment variables we pass to the test session and we change which tests run but it's the same assemblies.

Are there any docs for how we could try this?

**Comment by nohwnd** [comment]
It won't work for the same assembly, vstest internally reshuffles the tests and groups them by assembly, so you can't really run the same dll on two testhosts in the same session. For multiple assemblies it is automatic (iirc) when parallelization is disabled, (on the process level = maxcpucount = 1).

**Comment by nohwnd** [comment]
This is a new feature and won't be implemented, we are focusing on adding new features to Testing.Platform instead. https://aka.ms/testingplatform
