### ISSUE TITLE
HTML logger use <summary> tag instead of JavaScript in template

### ISSUE THREAD

**Issue by mingyaulee** [microsoft/vstest#4365]
## Description

Currently in the HTML logger template there is a JavaScript which helps to expand and collapse the test result.

https://github.com/microsoft/vstest/blob/ac4adfabc6df702c8ee0ce028599960ff7b3399f/src/Microsoft.TestPlatform.Extensions.HtmlLogger/Html.xslt#L14-L24

## Steps to reproduce

`dotnet test --logger html`

## Expected behavior

Test result page does not use additional JavaScript to enable interactions so that it can be used as a test summary page in GitHub actions.

## Actual behavior

The script tag and its contents are rendered as text in the GitHub actions summary.

## Diagnostic logs

None

## Environment

Build version: current version (code is in main branch)

**Comment by Evangelink** [comment]
@nohwnd Are you aware of any scenario that would get broken by such change in the html report? I am not sure if we consider the shape of the html report as some kind of public API that cannot be changed or if that's just a by product we can update as we pleased.

**Comment by nohwnd** [comment]
I can't see why someone would want to rely on the format of that html output, and it support of `<summary>` and `<details>` tags seems ok. So I think we can go for it: 

https://caniuse.com/details

**Comment by nohwnd** [comment]
https://github.com/microsoft/vstest/commit/21b92590f6bf0836e7d5596c67585698f820fa03

This was merged in 17.9.0, the logger comes with dotnet/sdk, please check which version of dotnet sdk you are using on your systems. Based on the versions inserted into VS, 17.9 should be in net 8.0.200 SDK , so you need at least that version.

https://learn.microsoft.com/en-us/dotnet/core/porting/versioning-sdk-msbuild-vs#supported-net-versions

When running tests with dotnet test you should see the version of vstest.console on the top.
