### ISSUE TITLE
vstext.console Could not load file or assembly 'System.Runtime, Version=4.2.2.0

### ISSUE THREAD

**Issue by Cugtyt** [microsoft/vstest#4382]
## Description

I am trying to use vstext.console to run project test on linux. I downloaded the nuget package `microsoft.testplatform.portable.17.5.0.nupkg`, unzip it and run `./vstest.console.dll` on my wsl on windows:

```
Unhandled Exception: System.IO.FileNotFoundException: Could not load file or assembly 'System.Runtime, Version=4.2.2.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' or one of its dependencies. The system cannot find the file specified.
```

## Steps to reproduce

./vstest.console.dll

or

./vstest.console.dll mytest.dll

## Expected behavior

It should run vstest just like run dotnet test mytest.dll

```
Microsoft (R) Test Execution Command Line Tool Version 17.3.1 (x64)
Copyright (c) Microsoft Corporation.  All rights reserved.

Starting test execution, please wait...
Logging Vstest Diagnostics in file: /path/to/log.txt
A total of 1 test files matched the specified pattern.

Passed!  - Failed:     0, Passed:     1, Skipped:     0, Total:     1, Duration: 24 ms
```

## Actual behavior

```
Unhandled Exception: System.IO.FileNotFoundException: Could not load file or assembly 'System.Runtime, Version=4.2.2.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' or one of its dependencies. The system cannot find the file specified.
```

## Diagnostic logs

```
Microsoft (R) Test Execution Command Line Tool Version 17.3.1 (x64)
Copyright (c) Microsoft Corporation.  All rights reserved.

Starting test execution, please wait...
Logging Vstest Diagnostics in file: /path/to/log.txt
A total of 1 test files matched the specified pattern.

Passed!  - Failed:     0, Passed:     1, Skipped:     0, Total:     1, Duration: 48 ms
```

## Environment

WSL ubuntu, 
microsoft.testplatform.portable.17.5.0.nupkg tools/netcoreapp3.1

**Comment by Cugtyt** [comment]
https://github.com/microsoft/vstest/blob/040f4eb8ecc1e21833f62e4b8172474e0397e272/src/vstest.console/vstest.console.csproj#L30-L33

Not sure, but is this missing for netcoreapp3.1?

**Comment by Evangelink** [comment]
Hi @Cugtyt,

You are mentionning that you are using v17.5 of the package but the log is showing 17.3.1 (`Microsoft (R) Test Execution Command Line Tool Version 17.3.1 (x64)`). Are you sure you are running the correct vstest.console?

**Comment by Cugtyt** [comment]
Hi @Evangelink , the vstest.console never run successful from my side, the `Microsoft (R) Test Execution Command Line Tool Version 17.3.1 (x64)` is the dotnet test command result for expected result, it is not vstest.console output, it is expected behavior, not actual behavior

**Comment by Evangelink** [comment]
I confirm that I can repro the issue on Linux using this package.

Out of curiosity, is there anything preventing you to be using `dotnet test`? We are not aware of many people using this package.

**Comment by Cugtyt** [comment]
The case is we need to run vstest inside the dotnet runtime container in the service pod, in which the dotnet cmd is not avaiable. I don't know if there are other ways to run the test dll

**Comment by nohwnd** [comment]
Executing .dll directly in WSL will make it fallback to the underlying Windows, just like when you run Calc.exe, it will start Windows calculator. Vstest.console is not able to handle that scenario, and will crash, and the output will be directed back to your WSL console, so it seems like you are running in linux but you are not.

This is from Windows point of view (via procexp):
![image](https://user-images.githubusercontent.com/5735905/231399684-699efc0b-a4d5-4b89-8f23-fd8a0d661f79.png)

 To correctly run vstest.console you need to run it via `dotnet` command, because we don't ship an executable. So prefix your vstes.console.dll with `dotnet` or `dotnet exec`. 
 
 In a containter you cannot vstest.console run without dotnet runtime.
