### ISSUE TITLE
"dotnet.exe vstest.console.dll testDllName.dll" always return with exitcode 1

### ISSUE THREAD

**Issue by Faizan2304** [Microsoft/vstest#44]
## Description

"dotnet.exe vstest.console.dll testDllName.dll" always return with exit-code 1
## Steps to reproduce

run a .net core test with vstest.console runner.
## Expected behavior

The process should exit with exit-code 0

**Comment by pvlakshm** [comment]
What is the impact of this behaviour?

**Comment by Faizan2304** [comment]
I tried with latest build and the behavior is as follows:
```
1) If all test pass "dotnet vstest.console testdll" will return 0.
2) If at least one  test fail"dotnet vstest.console testdll" will return 1.
```

and the above two behavior is expected.
