### ISSUE TITLE
Enable source-build pre-built detection

### ISSUE THREAD

**Issue by NikolaMilosavljevic** [microsoft/vstest#4405]
Part of https://github.com/dotnet/source-build/issues/3017

Enable source-build pre-build detection on the current repository and resolve any pre-build issues discovered

**Comment by NikolaMilosavljevic** [comment]
@MarcoRossignoli @Evangelink this is something I'm working on. It should be assigned to me, but I don't have permissions to do that.

**Comment by MarcoRossignoli** [comment]
What permission do you need?

**Comment by NikolaMilosavljevic** [comment]
> What permission do you need?

Not sure how those are tracked in this repo, but it would be nice to be able to add reviewers to PRs I create. It's not very important, though.

**Comment by MarcoRossignoli** [comment]
Feel free to open PR we can approve, or do you need some specific reviewer?

**Comment by Evangelink** [comment]
@NikolaMilosavljevic I have assigned you the task and gave you some permission (hopefully they are enough, if not feel free to ping me).
