### ISSUE TITLE
Use of obsolete API for Exception constructor

### ISSUE THREAD

**Issue by mthalman** [microsoft/vstest#4424]
When using the latest build of .NET 8 Preview 4 SDK to build the vstest repo, it results in the following analyzer error:

```
/repos/dotnet/src/vstest/artifacts/source-build/self/src/src/Microsoft.TestPlatform.AdapterUtilities/ManagedNameUtilities/InvalidManagedNameException.cs(14,93): error SYSLIB0051: 'Exception.Exception(SerializationInfo, StreamingContext)' is obsolete: 'This API supports obsolete formatter-based serialization. It should not be called or extended by application code.' (https://aka.ms/dotnet-warnings/SYSLIB0051) [/repos/dotnet/src/vstest/artifacts/source-build/self/src/src/Microsoft.TestPlatform.AdapterUtilities/Microsoft.TestPlatform.AdapterUtilities.csproj::TargetFramework=net8.0]
```

This was caught by the Source-build bootstrapping build workflow which uses a source-built version of the latest SDK to build the product's repos.

**Comment by Evangelink** [comment]
@vitek-karas We are multi-targetting our builds to the various tfms. What's the recommended approach here? Shall we exclude all serialization exception ctors for NET8+? Shall we start before that? Shall we ignore this issue at the moment?

**Comment by vitek-karas** [comment]
@GrabYourPitchforks should know what to do.

**Comment by Evangelink** [comment]
This issue https://github.com/dotnet/docs/issues/34893 contains all the informations about how to be fixing this issue properly.
