### ISSUE TITLE
Running from Console gives Invalid Framework Issue (Developer Command Prompt)

### ISSUE THREAD

**Issue by zmckinnon** [Microsoft/vstest#443]
## Description
When running unit tests from the command line with Framework parameter, I get invalid framework error.

## Steps to reproduce
Run:
```
"C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\Common7\IDE\CommonExtensions\Microsoft\TestWindow\vstest.console.exe" C:\agent\_work\1\s\Future150.Business.Tests\bin\Release\netcoreapp1.1\netcoreapp1.1\Future150.Business.Tests.dll "/TestCaseFilter:Category!=\"Integration Tests\"" /EnableCodeCoverage "/Framework:\".NetCoreApp,Version=v1.1\"" /logger:trx
```

## Expected behavior
Tests run

## Actual behavior
I get the following error:
```
Error: Invalid .Net Framework version:".NetCoreApp,Version=v1.1". Supported .Net Framework versions are Framework35, Framework40 and Framework45.
Vstest failed with error. Check logs for failures. There might be failed tests.
Error: C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\Common7\IDE\CommonExtensions\Microsoft\TestWindow\vstest.console.exe failed with return code: 1
No results found to publish.
Vstest exited with return code: 1.
```

## Environment
I was able to reproduce this on my dev machine from the command line & on my CI build.

**Comment by zmckinnon** [comment]
It seems I need a specific version of vstest.console.  It is sorta mentioned in this post: https://blogs.msdn.microsoft.com/visualstudioalm/2016/11/29/evolving-the-test-platform-part-3-net-core-convergence-and-cross-plat/

When it says:

```
C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\Common7\IDE\Extensions is the folder where extensions are installed, remember? Locate vstest.console.exe under this folder.
```

There has to be an easier way to do that, right?

**Comment by smadala** [comment]
@zmckinnon `C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\Common7\IDE\CommonExtensions\Microsoft\TestWindow\vstest.console.exe` (TPv1)  doesn't support Netcore app.

Please use vstest.console.exe(TPv2), which is under ` C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\Common7\IDE\Extensions\<random_folder>\`. Built to support both Full CLR and NetCore assemblies.

Please notice currently TPv2 doesn't support /EnableCodeCoverage.

**Comment by codito** [comment]
We should include the `vstest.console.exe` from TPv2 in `PATH` set in *Developer Command Prompt*.
