### ISSUE TITLE
Missing subscriptions for dependent repos

### ISSUE THREAD

**Issue by NikolaMilosavljevic** [microsoft/vstest#4439]
https://github.com/microsoft/vstest/pull/4419 enabled prebuilt detection in this repo, which required additional repo dependencies:

`https://github.com/dotnet/source-build-reference-packages`
`https://github.com/dotnet/source-build-externals`

These dependencies should be kept up to date, with recurring repo flow/subscriptions.

Here are the commands that should be used:
`darc add-subscription --channel ".NET Eng - Latest" --source-repo https://github.com/dotnet/source-build-reference-packages --target-repo https://github.com/microsoft/vstest --target-branch main --update-frequency everyWeek`

`darc add-subscription --channel ".NET 8" --source-repo https://github.com/dotnet/source-build-externals --target-repo https://github.com/microsoft/vstest --target-branch main --update-frequency everyWeek`

I don't have enough permissions to add new subscriptions in this repo.

**Comment by Evangelink** [comment]
I just tried to enable them and got a 403 for both. I will create a First Responder issue and will let you know.

**Comment by ali-turan7** [comment]
Subscriptions were added. Could you please try again?

**Comment by Evangelink** [comment]
@ali-turan7 I am still having 403 issue on my side

**Comment by Evangelink** [comment]
Done

**Comment by ali-turan7** [comment]
I believe if your GitHub token has SSO enabled, you will be able to add subscriptions.
