### ISSUE TITLE
Inconsistent info in https://learn.microsoft.com/dotnet/core/tools/dotnet-test

### ISSUE THREAD

**Issue by RussKie** [microsoft/vstest#4462]
## Description

The docs state that `--blame` option creates an xml under TestResults folder:
![image](https://github.com/microsoft/vstest/assets/4403806/56c8d3d8-afe3-4982-a2ba-1db831d33cea)

* **Issue 1:** the actual behaviour appears to be prefixing the xml instead of suffixing it contrary to the docs.
```
Attachments:
  D:\a\_work\1\s\artifacts\TestResults\Release\89d70f10-a445-4c26-a094-515472157d6e\testhost_5976_20230516T231756_hangdump.dmp
  D:\a\_work\1\s\artifacts\TestResults\Release\89d70f10-a445-4c26-a094-515472157d6e\Sequence_bf6d3d9d410343239c27a27f99f8bf10.xml
```

* **Issue 2:** The docs do not specify which option creates the dmp file.

**Comment by Evangelink** [comment]
Hi @RussKie,

Thanks for the feedback! We will review the doc and conditions and update the doc,

> * **Issue 2:** The docs do not specify which option creates the dmp file.

@MarcoRossignoli Can you help here?

**Comment by nohwnd** [comment]
it is --blame-crash or /Blame:CollectDump
