### ISSUE TITLE
Duplicated crash dumps

### ISSUE THREAD

**Issue by RussKie** [microsoft/vstest#4463]
.NET SDK: 8.0.100-preview.5.23261.16
dotnet-coverage: v17.6.9

## Description

It appears the same crash dump is being placed in different folders. 
![image](https://github.com/microsoft/vstest/assets/4403806/3c6ffe69-1704-4fe3-9018-4921a1664821)

I discovered this while publishing `*_hangdump.dmp` and `Sequence_*.xml` files for further investigation. 
The build: https://dev.azure.com/dnceng/internal/_build/results?buildId=2182052&view=artifacts&pathAsName=false&type=publishedArtifacts. You can grab the test.binlog from there as well, if necessary.

The test process is started with the following command line:
```
D:\a\_work\1\s/.dotnet/dotnet dotnet-coverage collect --settings D:\a\_work\1\s/eng/CodeCoverage.config --output D:\a\_work\1\s/artifacts/TestResults/Release/ "D:\a\_work\1\s/build.cmd -ci -NativeToolsOnMachine -test -configuration Release /bl:D:\a\_work\1\s/artifacts/log/Release//tests.binlog "
```

Each test project is started with the following command line:
```
"D:\a\_work\1\s\.dotnet\dotnet.exe" test D:\a\_work\1\s\artifacts\bin\xyz.Tests\Release\net8.0\xyz.Tests.dll --logger:"console%3Bverbosity=normal" --logger:"trx%3BLogFileName=xyz.Tests_net8.0_x64.trx" --logger:"html%3BLogFileName=xyz_net8.0_x64.html" "--ResultsDirectory:D:\a\_work\1\s\artifacts\TestResults\Release" "--Framework:.NETCoreApp,Version=v8.0"  --blame --blame-crash --blame-hang --blame-hang-timeout 6m >> "D:\a\_work\1\s\artifacts\log\Release\TestLogs\xyz.Tests_net8.0_x64.log" 2>&1
```

Note: we're using the Arcade SDK, but I don't think it has any capabilities to capture crash dumps on its own.

## Steps to reproduce

Not sure.

**Comment by MarcoRossignoli** [comment]
> "D:\a\_work\1\s\.dotnet\dotnet.exe" test D:\a\_work\1\s\artifacts\bin\xyz.Tests\Release\net8.0\xyz.Tests.dll --logger:"console%3Bverbosity=normal" --logger:"trx%3BLogFileName=xyz.Tests_net8.0_x64.trx" --logger:"html%3BLogFileName=xyz_net8.0_x64.html" "--ResultsDirectory:D:\a\_work\1\s\artifacts\TestResults\Release" "--Framework:.NETCoreApp,Version=v8.0"  --blame --blame-crash --blame-hang --blame-hang-timeout 6m >> "D:\a\_work\1\s\artifacts\log\Release\TestLogs\xyz.Tests_net8.0_x64.log" 2>&1

I see that the trx is enabled and that could be the culprit. Trx is moving tests artifacts(all files produced by the run) under custom folder and it's linking it to the trx(xml) content. So every time it's enabled that's the default behavior.

You can repro with a simple test like
```cs
namespace reproissue;

[TestClass]
public class UnitTest1
{
    [TestMethod]
    public void TestMethod1()
    {
        System.Threading.Thread.Sleep(60_000);
    }
}
```
and run with
```bash
dotnet test --collect: "Code Coverage" --logger trx --blame-hang --blame-hang-timeout 5s
```
Inside the TestResults you'll see duplicated dump files, one inside a folder(guid name) and one inside a folder with the same name of the trx file.

**Comment by RussKie** [comment]
Thank you for explaining this.

Since this by design, feel free to close. 
I implemented a workaround by looking at GUID-like folders only searching for crash dumps.
