### ISSUE TITLE
Improve the console message related to /diag switch

### ISSUE THREAD

**Issue by singhsarab** [Microsoft/vstest#448]
## Description
>While running tests via dotnet vstest and using the diag switch, there are 2 files getting generated, but only one is being reported.
> Add the information for the other file as well. 

## Steps to reproduce
> Just run dotnet vstest for given testcontainer with diag switch.
dotnet vstest <path_to_dll> /diag:foo.txt 

## Expected behavior
`Information:`
`Logging VsTest Diagnostics in file: foo.txt`
`Logging TestHost Diagnostics in file: foo.host.17-02-06_04-21-41_75662_4.txt`

## Actual behavior
Starting test execution, please wait...
`Information: Logging TestHost Diagnostics in file: foo.host.17-02-06_04-21-41_75662_4.txt`

**Comment by Faizan2304** [comment]
Fixed!!
