### ISSUE TITLE
docs unclear on what version to use for Microsoft.NET.Test.Sdk

### ISSUE THREAD

**Issue by Applesauce314** [microsoft/vstest#4510]
## Description

The version numbers of `Microsoft.NET.Test.Sdk` are close to the version numbers of Visual Studio. This would seem to indicate that you should use a version of `Microsoft.NET.Test.Sdk` that lines up with the  major/minor version of vs you are using (e.g. vs 17.4.4 should use `Microsoft.NET.Test.Sdk` 17.4.0 or 17.4.1.
However I could not find any documentation that confirms or disproves this assumption, and today I misremembered the VS version number when updating references and updated to a higher version and it seems to be working fine, but maybe I have bugs waiting to come out at a later date I have not found yet.

It would be helpful to document the relationship (or lack thereof) between these versions.

**Comment by nohwnd** [comment]
Good point. 

You don't have to keep them in sync, the communication protocol between them is pretty stable, ideally you would be at the same minor version as your VS. E.g. 17.4.x. But both older and newer versions should work.

**Comment by nohwnd** [comment]
We don't have a strict suggestion on what version to use, we test with old versions and new versions to ensure compatibility, other than to update regularly and keep the version more or less aligned to the version of VS you are using. 

MSTest meta package <https://www.nuget.org/packages/MSTest> takes dependency on the recommended version (the one we test MSTest with).
