### ISSUE TITLE
Test Explorer should allow user to see tests included for LUT (Live unit testing)

### ISSUE THREAD

**Issue by sbaid** [Microsoft/vstest#453]
## Description
Live Unit Testing support including/excluding tests through code editor & solution explorer. User can not see the currently included tests anywhere.

Suggestion is to expose it through Test Explorer Playlist->Live Unit Testing (like readonly Playlist->All Tests)

![capture](https://cloud.githubusercontent.com/assets/19462879/22724725/3377a748-edee-11e6-888d-77cf1f402044.PNG)

let's close the spec here.

**Comment by sbaid** [comment]
@pvlakshm @tmat @ManishJayaswal @saikrishnav @genlu

**Comment by ManishJayaswal** [comment]
This view should be the default view when LUT is on. User should be able to change it to other playlists and if he does that then we should honor that.

**Comment by pvlakshm** [comment]
Closing this - track via VSFeedback.
