### ISSUE TITLE
Autogenerated Code should be excluded automatically from test coverage

### ISSUE THREAD

**Issue by kenziewritescode** [microsoft/vstest#4531]
## Description

The Autogenerated Program files should automatically be excluded from code coverage. It looks like a [similar issue ](https://github.com/microsoft/vstest/issues/813)was opened before, however, when getting code coverage on our builds, we had an issue where an auto-generated file appeared. There may be an additional issue with coverlet that we're brought up there, but I wouldn't think we'd ever want these files included.

![image](https://github.com/microsoft/vstest/assets/92125472/23686dd0-20bb-4f31-b17a-614a6f019028)

## Steps to reproduce

1. We created our projects in Visual Studio from their test product with generic unit tests.
2. dotnet test ./Solution.sln --logger trx --results-directory ${{ github.workspace }}/TestResults --settings:./test.runsettings --collect:"XPlat Code Coverage"

## Expected behavior

The auto-generated code shouldn't be allowed to be included in coverage.

## Diagnostic logs

I can include binlogs if necessary. 

## Environment

We were using an older package but now use the latest 17.6.2 with .NET Core. This command is executed in a Github Action with .NET Core with Ubuntu
 22.04.2, but I can reproduce this on my Windows 10 machine.

**Comment by jakubch1** [comment]
@MarcoRossignoli this is coverlet related.

**Comment by MarcoRossignoli** [comment]
@kenziewritescode you should open this issue here https://github.com/coverlet-coverage/coverlet/issues

**Comment by kenziewritescode** [comment]
I think there's still an issue here, because this is only generated for one of our projects. And no others are excluded (because of a coverlet issue)
