### ISSUE TITLE
Clean up EqtTrace

### ISSUE THREAD

**Issue by mayankbansal018** [Microsoft/vstest#454]
## Description
> Remove partial Interfaces: this will require us to break from SetupRemoteEqtTraceListeners() functionality
> Remove TraceLevel set,& get, or change them to PlatformTraceLevel set,& get

**Comment by codito** [comment]
This will be a breaking change for any adapters using `RemoteEqtTraceListener`.

While we're at it, shouldn't EqtTrace be internal? All adapters should use `IFrameworkHandle.SendMessage`.

/cc @AbhitejJohn

**Comment by AbhitejJohn** [comment]
Is there an alternative? Can we use IFrameworkHandle across app domains?

**Comment by pvlakshm** [comment]
This is a breaking change. We can live with the current state. Reactivate if you disagree.
