### ISSUE TITLE
Invalid Preview version breaking VSTS

### ISSUE THREAD

**Issue by abheda30** [microsoft/vstest#4544]
Getting the exception : Invalid version string for TestPlatformVersion 17.7.0-preview.23280.1+94103c3f3198fe6f1405e1cb8fe486d6cd7132fd

I think the version number is somewhat messing up the VS Installer Task.

**Comment by akshaybheda** [comment]
![image](https://github.com/microsoft/vstest/assets/22575879/89210dd1-59f2-46e2-a4c7-113d7c52a736)
![image](https://github.com/microsoft/vstest/assets/22575879/8879dca3-e86f-4f68-8ed7-15407ed3ffe6)

**Comment by amupaaru29** [comment]
We had the same issue today. Solved by changing Version to "Latest Stable" in the VS TestPlatform installer task. 

![image](https://github.com/microsoft/vstest/assets/25026052/5bd7694e-7a0d-4f79-ac0c-9afb29e000d9)

**Comment by akshaybheda** [comment]
Yes but we have 100's of pipelines. We will have to change for each

**Comment by Aspro1** [comment]
> We had the same issue today. Solved by changing Version to "Latest Stable" in the VS TestPlatform installer task.
> 
> ![image](https://user-images.githubusercontent.com/25026052/245375621-5bd7694e-7a0d-4f79-ac0c-9afb29e000d9.png)

I can confirm that this solves the issue.

**Comment by akshaybheda** [comment]
Yes it works but need to change each pipeline

**Comment by nohwnd** [comment]
Thanks for the report, I've unlisted the package. We've recently changed how we package our nugets, to be using the same approach as other teams (e.g. dotnet/runtime), and that brought a change in the versioning schema, and appended +<commitid>, which is causing issues with the installer task.

**Comment by nohwnd** [comment]
You should not get 17.6.2 resolved when you re-run your pipeline that is choosing `latest preview`.

**Comment by nohwnd** [comment]
@akshaybheda 17.6.2 should be the version that resolves now when you use Latest or Latest preview. So no-need to change your hundreds of pipelines. I've tried on my pipeline. Please confirm if possible.

**Comment by akshaybheda** [comment]
Yes it is resolving to 17.6.2 now. Thanks
