### ISSUE TITLE
Why the Nuget package license differs from the repository license?

### ISSUE THREAD

**Issue by max-ieremenko** [microsoft/vstest#4587]
## Description

The license for the vstest repository is [MIT](https://github.com/microsoft/vstest/blob/main/LICENSE).

The [Microsoft.NET.Test.Sdk](https://www.nuget.org/packages/Microsoft.NET.Test.Sdk/) package as well as dependencies [Microsoft.TestPlatform.ObjectModel](https://www.nuget.org/packages/Microsoft.TestPlatform.ObjectModel), [Microsoft.TestPlatform.TestHost](https://www.nuget.org/packages/Microsoft.TestPlatform.TestHost) and [Microsoft.CodeCoverage](https://www.nuget.org/packages/Microsoft.CodeCoverage) have license "MICROSOFT .NET LIBRARY".

**package.nuspec**

```xml
<package xmlns="http://schemas.microsoft.com/packaging/2013/05/nuspec.xsd">
  <metadata>
    <license type="file">LICENSE_NET.txt</license>
    <repository type="git" url="https://github.com/microsoft/vstest" />
  </metadata>
</package>
```

**LICENSE_NET.txt**

```text
MICROSOFT SOFTWARE LICENSE TERMS

MICROSOFT .NET LIBRARY
...
```

Why are package licenses and repository licenses different, MIT vs MICROSOFT .NET LIBRARY ?

**Comment by nohwnd** [comment]
This is answered here: https://github.com/microsoft/vstest/issues/3871#issuecomment-1383721037

Together with the code built from this repository, the nuget packages ship additional files, which are not all MIT licensed.

**Comment by max-ieremenko** [comment]
Thank you for the explanation.
