### ISSUE TITLE
Async APIs not working

### ISSUE THREAD

**Issue by Cyberboss** [microsoft/vstest#4592]
## Description

`VsTestConsoleWrapper.StartSessionAsync()` never succeeds.

You're awaiting the handshake task here:
https://github.com/microsoft/vstest/blob/e9b28ec4abce22c685eb91c0bf197dd50e2d1c08/src/Microsoft.TestPlatform.VsTestConsole.TranslationLayer/VsTestConsoleRequestSender.cs#L136-L139

Before actually starting the console process here:
https://github.com/microsoft/vstest/blob/e9b28ec4abce22c685eb91c0bf197dd50e2d1c08/src/Microsoft.TestPlatform.VsTestConsole.TranslationLayer/VsTestConsoleWrapper.cs#L595

## Steps to reproduce

```cs
var testConsoleWrapper = new VsTestConsoleWrapper(executable);
await testConsoleWrapper.StartSessionAsync();
```

## Expected behavior

The `Task` returned by `StartSessionAsync()` eventually completes.

## Actual behavior

The `Task` returned by `StartSessionAsync()` eventually never completes.

## Diagnostic logs

None

## Environment

vstest.console.exe version: `17.0.33007.217`
Target .NET version: `net472`
```
PS C:\Users\Cyberboss> dotnet --list-sdks
1.1.10 [C:\Program Files\dotnet\sdk]
1.1.14 [C:\Program Files\dotnet\sdk]
2.1.202 [C:\Program Files\dotnet\sdk]
2.1.526 [C:\Program Files\dotnet\sdk]
5.0.202 [C:\Program Files\dotnet\sdk]
5.0.214 [C:\Program Files\dotnet\sdk]
5.0.404 [C:\Program Files\dotnet\sdk]
5.0.408 [C:\Program Files\dotnet\sdk]
6.0.313 [C:\Program Files\dotnet\sdk]
6.0.410 [C:\Program Files\dotnet\sdk]
7.0.100 [C:\Program Files\dotnet\sdk]
7.0.304 [C:\Program Files\dotnet\sdk]
```

[AB#1865062](https://devdiv.visualstudio.com/0bdbc590-a062-4c3f-b0f6-9383f67865ee/_workitems/edit/1865062)

**Comment by nohwnd** [comment]
We are discussing if we should make a breaking change and fix them, or make them obsolete, because in the current form you don't get any additional benefit of using them, they do async over sync.
