### ISSUE TITLE
InlineData attribute with certain characters (e.g. 'ä','ö',etc.) breaks VS Test Explorer

### ISSUE THREAD

**Issue by albpi** [microsoft/vstest#4595]
## Description

The program uses the `File.Exists` method to check that the passed filename value is actually present at the specified path. While it works fine when running in the Console App, it fails when setting up a test with VS Test explorer, if the value contains characters like 'ä' or 'ö' (and I suppose it will fail for other special characters) .

I think this issue is identical to [this one](https://github.com/xunit/visualstudio.xunit/issues/289).

## Steps to reproduce
I am using .NET 7 and here is the test project setup:
<img width="291" alt="image" src="https://github.com/microsoft/vstest/assets/12641608/1d839d9f-6771-4849-b4ed-44806657e967">

I want to check that a file with name `testä.xml` exists. I have it in a folder and the relative path to it is `..\..\testä.xml`
The method that fails in VS Test explorer is `File.Exists .".\..\testä.xml"`.
It also fails when using `dotnet test`, that I believe is what VS Test uses under the hood.

## Expected behavior
The result of `File.Exists "..\..\testä.xml"` should be **true** and the test should then succeed.

## Actual behavior
The result of `File.Exists ".\..\testä.xml"`is **false** and the test then fails.

## Environment
Windows OS 11
VS 2022

[AB#1850367](https://devdiv.visualstudio.com/0bdbc590-a062-4c3f-b0f6-9383f67865ee/_workitems/edit/1850367)

**Comment by MasonFI** [comment]
I encountered this bug also. This should be fixed asap.

**Comment by nohwnd** [comment]
Used the repro linked in xunit, and this looks fixed: 
![image](https://github.com/microsoft/vstest/assets/5735905/b07e0524-f202-45a2-bf88-f10d0f3215aa)
