### ISSUE TITLE
Why is Microsoft.NET.Test.Sdk a NuGet rather than an MSBuild SDK?

### ISSUE THREAD

**Issue by Deatomizeer** [microsoft/vstest#4599]
I am in the process of migrating to `.NET Core` and one of the things I had to do was to add a `Microsoft.NET.Test.Sdk` reference in order for the tests to be discoverable. However, I do not fully understand why it is being distributed as a NuGet package and cannot be referenced like other SDKs in the `<Project>` tag, like `<Project Sdk="Microsoft.NET.Sdk>`.

**Comment by nohwnd** [comment]
The other issue is still open, and is a better place to offer your opinion I think.
