### ISSUE TITLE
Unable to discover some unit test projects

### ISSUE THREAD

**Issue by srivatsn** [Microsoft/vstest#460]
_From @niemyjski on February 8, 2017 17:2_

Since the latest VS2017  RC3 update I'm unable to discover all of my unit test projects...
 Just clone (https://github.com/exceptionless/foundatio) and try building different projects / run the Foundatio.Redis tests (they aren't found or listed in the test runner). I haven't tried via the command line

_Copied from original issue: dotnet/sdk#839_

**Comment by niemyjski** [comment]
I tried to run the tests via the command line and they ran.. so it appears to be just a VS issue

**Comment by codito** [comment]
The tests are not discovered because following dependencies are not present in `Foundatio.Redis.Tests` csproj:

```
    <PackageReference Include="Microsoft.NET.Test.Sdk" Version="15.0.0-*" />
    <PackageReference Include="xunit" Version="2.2.0-*" />
    <PackageReference Include="xunit.runner.visualstudio" Version="2.2.0-*" />
```

After adding them, tests show up.

**Comment by codito** [comment]
Closing this. Please reopen if you still observe this behavior.
