### ISSUE TITLE
Consider setting Console.OutputEncoding for `dotnet test` and friends

### ISSUE THREAD

**Issue by bradwilson** [microsoft/vstest#4605]
There was a change in Windows Terminal 1.17 that causes .NET applications that output Unicode characters to the console to have them garbled, because of the default output encoding. This does not happen in prior versions of Windows Terminal, nor in classic "conhost.exe" console windows.

xUnit.net uses characters which are corrupted now when run on Windows Terminal through `dotnet test` and friends.

Output from `xunit.console.exe`:

![image](https://github.com/microsoft/vstest/assets/16944/32557214-96c1-49bd-98ab-6df192aa5007)

Output from `dotnet test` (in Windows Terminal-hosted Powershell):

![image](https://github.com/microsoft/vstest/assets/16944/d51723ef-eae9-4ea0-bb70-4bbc409d5d0b)

Output from `dotnet test` (in conhost-hosted Powershell):

![image](https://github.com/microsoft/vstest/assets/16944/8355e789-3ce4-4751-9e47-3884eb33f304)

While strictly speaking this isn't a bug in VSTest (or xUnit.net), we opted fixed this in https://github.com/xunit/xunit/commit/c4b6ed0f41bb87aa3a92042bcb4f6bbc4694c12d on our side. I would recommend that you consider doing this as well, so that any output from testing frameworks which is outside of ASCII can be presented properly in Windows Terminal.

[AB#1865057](https://devdiv.visualstudio.com/0bdbc590-a062-4c3f-b0f6-9383f67865ee/_workitems/edit/1865057)

**Comment by nohwnd** [comment]
Thanks for the tip!

**Comment by nohwnd** [comment]
We will need to check with someone using some exotic system (like chinese) to see if everything looks okay and then implement this.
