### ISSUE TITLE
Backport #4610 to 17.7.0?

### ISSUE THREAD

**Issue by JamesNK** [microsoft/vstest#4627]
https://github.com/microsoft/vstest/pull/4610 fixes a regression in .NET 8: https://github.com/microsoft/vstest/issues/4549

However, it doesn't look like the fix is in 17.7.0, which is what .NET 8 uses. Should the changes be backported to 17.7.0 to fix the .NET 8 regression?

**Comment by nohwnd** [comment]
We should probably move to inserting 17.8 into .NET 8. @cvpoienaru please have a look.

**Comment by nohwnd** [comment]
We started inserting 17.8 into .NET 8. 

Backported to 17.7 in #4632 which won't affect net8, but will affect net7.0.4xx.
