### ISSUE TITLE
Problem Referencing `Microsoft.NET.Test.Sdk` in Projects That Also Reference an Analyzer That Reads Additional Files

### ISSUE THREAD

**Issue by JasonBock** [microsoft/vstest#4685]
## Description

When I reference `Microsoft.NET.Test.Sdk` with an analyzer that views additional files, I get unexpected errors.

## Steps to reproduce

* Create a solution with two projects:
  * One that references `Microsoft.CodeAnalysis.Analyzers` and `Microsoft.CodeAnalysis.CSharp`
  * One that references the first project with `OutputItemType` set to `Analyzer`, and also has a package reference to `Microsoft.NET.Test.Sdk` version `17.7.2`
* The first project should have a class that inherits from `DiagnosticAnalyzer`, and in `Initialize()`, make this call: `context.RegisterAdditionalFileAction(AnalyzeAdditionalFile);`.
* In `AnalyzeAdditionalFile()`, do this:

```csharp
private void AnalyzeAdditionalFile(AdditionalFileAnalysisContext context)
{
  var text = context.AdditionalFile.GetText();

  if (text is not null)
  {
    /* do something with the text */
  }
}
```

## Expected behavior

Additional file analysis doesn't cause a compilation error.

## Actual behavior

I see two `CS2015` errors, something like this for both `testhost.exe` and `testhost.dll`:

```
CS2015	'C:\...\.nuget\packages\microsoft.testplatform.testhost\17.7.2\build\netcoreapp3.1\x64\testhost.exe' is a binary file instead of a text file
```

I can change my analyzer to look at the additional file's extension and filter out .dlls and .exes. But this was unexpected, in that just by referencing this package, these two files are considered to be part of the "additional files" collection during a compilation. I'd rather not try to filter out binary files, because there's no full-proof way to do it.

Side note: I wish the analyzers wouldn't automatically add a `CS2015` diagnostic just by calling `GetText()`; rather, it would be nice to have a `TryGetText()`, or some other way not to have the diagnostic created. But that doesn't exist right now.

**Comment by nohwnd** [comment]
We use those additional files to be able to run tests. Unfortunately you will have to ignore or suppress them.
