### ISSUE TITLE
Vstest loads Dlls in system folder before the ones in the application folder

### ISSUE THREAD

**Issue by danyaalk123** [microsoft/vstest#4700]
Describe the issue
I'm facing an issue when using the onnxruntime.ml.microsoft package with native MSTest unit tests. When I run the tests, it seems the package loads the onnxruntime from the System32 directory rather than the application's output folder. This behavior is not observed with Google Tests.

Workaround:
I discovered that by disabling SafeDllSearchMode, the behavior can be corrected. The process is outlined in the official Microsoft documentation [here](https://learn.microsoft.com/en-us/windows/win32/dlls/dynamic-link-library-search-order#standard-search-order-for-desktop-applications).

Possible Root Cause:
I suspect the underlying cause might be how vstest starts up within the Visual Studio environment. It seems like it might be starting from a Visual Studio program folder, which causes it to prioritize the loading of DLLs from System32 over the project's output folder.

To reproduce
Create a new MSTest project and add the Microsoft.ML.OnnxRuntime package.
Write a test case that utilizes onnxruntime functionality.
Run the test case.
Urgency
No response

Platform
Windows

OS Version
Windows 10

ONNX Runtime Installation
Released Package

ONNX Runtime Version or Commit ID
1.16.0

ONNX Runtime API
C++

Architecture
X64

Execution Provider
Default CPU

Execution Provider Library Version
No response

**Comment by nohwnd** [comment]
@Evangelink this looks like a mstest issue rather than vstest. Please have a look.

**Comment by Evangelink** [comment]
Hi @danyaalk123,

Would you mind providing a simple repro? I have created the project but I don't know what you are doing with the ML model to have your error.

**Comment by danyaalk123** [comment]
https://drive.google.com/file/d/1nLqX2MEGBZXra8jvWxrPX8FPlFeykwWR/view?usp=sharing

Old version so might have to update onnxruntime nuget package version

.Net Tests will run and pass but the native test 1 wont pass due to the wrong onnxruntime.dll being loaded.

If I was to swtich to google tests it would pass

**Comment by avivhu** [comment]
I'm having the same problem with vstest.

onnxruntime.dll in System32 takes precedence over the onnxruntime.dll in the directory of the tested DLL.
The SafeDllSearchMode reg edit workaround also works for me.
The DLL loading order in vstest is not as I would expect, why is that?

**Comment by Evangelink** [comment]
Hi @avivhu, would it be possible for you to provide us with a repro project?

**Comment by danyaalk123** [comment]
@Evangelink 
https://gofile.io/d/Plyo7b

**Comment by avivhu** [comment]
@Evangelink I tried to make an isolated repro but got bogged down in the complexity. Try @danyaalk123  's repro first.

**Comment by danyaalk123** [comment]
@Evangelink Any Updates?

**Comment by Evangelink** [comment]
I am able to see an issue with `UnitTest1.TestMethod`:
![image](https://github.com/microsoft/vstest/assets/11340282/dece5211-1da1-4fda-8049-da295a7fc5c2)

Doing some debugging with Process Monitor, I see that the search pattern is correct according to https://learn.microsoft.com/en-us/windows/win32/dlls/dynamic-link-library-search-order#standard-search-order-for-packaged-apps. Steps 1 to 6 nothing is specified, for step 7 the calling process is started from VS folder so resolution is tried from this folder
![image](https://github.com/microsoft/vstest/assets/11340282/318abdcf-62e6-4dfa-b0fb-3c88e9c9a308)
and then we get to step 8, loading from system32
![image](https://github.com/microsoft/vstest/assets/11340282/d8b93aac-22eb-477b-840c-55936676cd04).

FYI, you are not using MSTest test framework but cpp unit testing framework and there is no bug on vstest.console.exe logic either. This means that if something is indeed wrong, this is on cpp unit testing side so you would need to open a bug in https://developercommunity.visualstudio.com/home to have it triaged to the correct team.
