### ISSUE TITLE
"No test sources found matching the given filter '**\*,!**\obj\**' " error message is shown after automated tests with Azure Test Cases

### ISSUE THREAD

**Issue by prakashfinezoom** [microsoft/vstest#4702]
## Describe the bug

**Step:1** 
I have created the azure repo with test file, playwright.snl file, playwright.csproj and yml file..

pool:
  vmImage: windows-latest

steps:
- task: UseDotNet@2
  inputs:
    packageType: sdk
    version: '7.0.x'
  displayName: 'Use .NET SDK'
- script: dotnet build --configuration Release
  displayName: 'Build'
- script: pwsh bin/Release/net7.0/playwright.ps1 install --with-deps
  displayName: 'Install Playwright browsers'
- script: dotnet test --configuration Release
  displayName: 'Run tests'

**Step 2:**
Created the pipeline and ran the yaml file.

**Step 3:** 
Have followed the below link to create the release.

https://marcusfelling.com/blog/2020/associating-automated-tests-with-azure-test-cases/

**Step 4:**
Done associating the testcase using visual studio and executed the test case.

## Expected behavior

Test case should fail or pass

## Actual behavior

Test case is in "In progress" status.

No Test source found warning occurs after executing the test case.

**Comment by nohwnd** [comment]
Are you sure the dll is there? Running with debugging enabled https://learn.microsoft.com/en-us/azure/devops/pipelines/troubleshooting/review-logs?view=azure-devops#configure-verbose-logs usually lists all the files. You might also list them yourself by adding a separate step into the job. 

You are searching in d:\a\r1\a, please list all the files there.
