### ISSUE TITLE
Problems with null in DataRow

### ISSUE THREAD

**Issue by jmagaram** [Microsoft/vstest#471]
## Description
Occasionally my unit tests fail to run and display a very cryptic message in the output. I've narrowed the problem down to using null values inside a DataRow. The error message is completely unhelpful and the fix is unexpected. I can't believe this is by-design.

    [DataTestMethod]
    [DataRow(false, "abc")]
    [DataRow(true, "")]
    [DataRow(true, "   ")]
    [DataRow(true, null)]
    public void IsStringNullOrWhitespace(bool expectedResult, string s)
    {
        bool result = String.IsNullOrWhiteSpace(s);
        Assert.AreEqual(expectedResult, result);
    }

The error message is `Error in executing test. No result returned by extension. If using extension of TestMethodAttribute then please contact vendor.`

The "fix" is to replace the last row with...

    [DataRow(true, (string)null)]

When I do this, Visual Studio recommends removing the unnecessary cast. I've tried labeling the datarow parameters but can't seem to make this work.

## Steps to reproduce
Try running the unit test above in the RC version of Visual Studio 2017.

## Expected behavior
I expect the test to run and give me correct results. Or a much more helpful error message.

**Comment by jmagaram** [comment]
I just ran into this problem again today working on a unit test where a DataRow contains a int? column and I wanted to try null. I can't be the only one bumping into this.

**Comment by AbhitejJohn** [comment]
@jmagaram Here is a more convenient workaround until this gets fixed:
Add another dummy argument to your test methods where you can pass in a non-null value. So if you have something like:
```
[DataRow(true, null)]
public void IsStringNullOrWhitespace(bool expectedResult, string s)
{
    bool result = String.IsNullOrWhiteSpace(s);
    Assert.AreEqual(expectedResult, result);
}
```
Make that
```
[DataRow(true, "", null)]
public void IsStringNullOrWhitespace(bool expectedResult, string dummy, string s)
{
    bool result = String.IsNullOrWhiteSpace(s);
    Assert.AreEqual(expectedResult, result);
}
```

Hope that gets rid of most of the inconvenience. This should be fixed in an up-coming update.

**Comment by AbhitejJohn** [comment]
This has been fixed in MSTest.TestFramework (1.1.14) and MSTest.TestAdapter (1.1.14). Release notes are [here](https://github.com/Microsoft/testfx-docs/blob/master/docs/releases.md#1114). Thanks for reporting this.
