### ISSUE TITLE
Consider DisableAppDomains=true by default

### ISSUE THREAD

**Issue by nohwnd** [microsoft/vstest#4726]
I am considering to set DisableAppDomains option by default to true. 

This would only affect .NET Framework, and would disable appdomain isolation as it is implemented by the respective frameworks, most importantly MSTest, NUnit and Xunit.

I saw significant perf improvements in discovery and execution speed across frameworks. And and in XUnit 2.5.0 and newer the switch works correctly thanks to Brad.

## Users

You can test if this breaks you by running with:  
```
dotnet test -- RunConfiguration.DisableAppDomain=true

vstest.console.exe yourTests.dll -- RunConfiguration.DisableAppDomain=true
```

Or  this runsetting: 
```xml 
<RunSettings>
  <RunConfiguration>
    <DisableAppDomain>true</DisableAppDomain>
  </RunConfiguration>
</RunSettings>
```

Are you relaying on it? Would this break you?

## Maintainers 

Framework maintainers, do you see problems with this? @OsirisTerje @bradwilson @Evangelink

**Comment by bradwilson** [comment]
We're not depending on it (that I'm aware of).

I really have no idea how many tests in the wild depend on have app domains in place. Even asking users whether they depend on them probably won't help because many are unlikely to know, simply depending on the default behavior.

**Comment by nohwnd** [comment]
This change was proposed to testing platform, here we won't do it because it would change how dlls are loaded. I've accidentally did it in unrelated change, and lot of code bases started to break.
