### ISSUE TITLE
Tests failing in vstest.console.unittests

### ISSUE THREAD

**Issue by harshjain2** [Microsoft/vstest#473]
## Description
> Two test cases are failing in vstest.console.unittests project for netcoreapp1.0 TFM.

## Steps to reproduce
> Run dotnet test vstest.console.unittests.csproj -f netcoreapp1.0

## Expected behavior
> All tests should pass.

## Actual behavior
> Two test cases failed
1. CancelTestRunShouldWaitForCreateTestRunRequest
2. AbortTestRunShouldWaitForCreateTestRunRequest

## Workaround
Added [Ignore] tag for these two tests cases so that PR build completes successfully.

Related to : https://github.com/Microsoft/vstest/issues/224

**Comment by mayankbansal018** [comment]
Tests have been fixed in https://github.com/Microsoft/vstest/commit/0514a9e7672bfcca2cf5f7772cf5074ee7b98d46#diff-206b8e1eda3ed805009e86364ccbdd2b
