### ISSUE TITLE
ITestLoggerWithParameters | ITestLogger async issue

### ISSUE THREAD

**Issue by nbalu** [microsoft/vstest#4749]
## Description

Using the following interface types there's no way that you can garatnee that a service can "finish" it's work if there's no sync alternative.

Event handlers were fine before Tasks but if you would write (async void) anything that will reach the first await will treat the event as returned.

## Steps to reproduce

```
public class ShameOnYouLogger : ITestLoggerWithParameters
{
    public void Initialize(TestLoggerEvents events, Dictionary<string, string?> parameters)
    {
        events.DiscoveryStart += Events_DiscoveryStart;
    }

    private async void Events_DiscoveredTests(object? sender, DiscoveredTestsEventArgs e)
    {
        var message = JsonConvert.SerializeObject(e);

        await Task.Delay(10000);
        Console.WriteLine("This will never show up if your descovery not takes at least 10 sec");
    }
}
```

## Expected behavior
Console should be reached.

## Actual behavior
Won't be logging.

## Diagnostic logs
⏹️ 

## Environment
🌎 

## Proposal

There are couple of ways to solve it:
- Interface should be marked as IDisposable + IAsyncDisposable and the loggers should be disposed along with the EventHandler
- Introduce a new abstract class to introduce "calls" to both sync / async function instead of dispatching events (UI obsession) like:
virtual void DiscoveredTests(DiscoveredTestsEventArgs e) { return; }
virtual Task DiscoveredTests(DiscoveredTestsEventArgs e) { return Task.Completed; }

Or feel free to come up with any proper solution you might like. But this is not a very fortunate situation...

**Comment by nbalu** [comment]
I'd like use a lib that I'd like to trigger on messages. But the API surface only supports async methods.

I'm not saying that you should redesign it. Though I would recommend to introduce a new interface which can be used for extensibility that supports async methods. This should apply to Collectors / Adapters / Discoverer / Executer and whatever extensibility point exists within vstest.

For now I would say it would be sufficient to have a Listener upgraded for my case for now... But I would be happy to see that the lookup would look for additional new generation types that are capable to handle async workloads.

From implementation perspective I don't think it would be a huge deal to introduce these types.

**Comment by nohwnd** [comment]
Unfortunately that is not so easy. The design where commands (as method calls) flow one way and responses flow as events the other way is common in the whole codebase. For your approach we would have to switch to a message bus or something and then "emulate" the events. I would be up for it, but it would have to be used extensively throughout the whole codebase, and this big refactoring is not something we want to do right now.

**Comment by nohwnd** [comment]
Installed it from here: 

https://www.firegiant.com/docs/heatwave/

Created new project: 

![image](https://github.com/microsoft/vstest/assets/5735905/ed4fd5c7-c468-4ad6-9bc1-ede202ecce26)


Build. 

11:06:20:466	[20/11/2023 11:06:20.342 am]  System.ArgumentException: FrameworkName is invalid.
11:06:20:466	Parameter name: frameworkName
11:06:20:466	   at System.Runtime.Versioning.FrameworkName..ctor(String frameworkName)
11:06:20:466	   **at Microsoft.VisualStudio.TestWindow.ShellServices.ProjectDataImpl.<GetTargetFrameworkInfoAsync>d__39.MoveNext()**
11:06:20:466	[20/11/2023 11:06:20.358 am]  Loading Project 1bd73629-bb69-4b30-a804-b0bda74f54ad [1] => 

Is shown in Tests window. 

@peterwald looks like an issue in TE.

**Comment by nohwnd** [comment]
Thanks for the suggestions. We can come up with a lot of workarounds, but I would like to avoid introducing a one off solutions that are not building on a solid foundation. The internal architecture is different and does not mesh well with async workloads.

**Comment by nohwnd** [comment]
We don't plan to change the internal architecture.  Please consider moving to testing platform, where we are considering async first, and use a more modern architecture: https://aka.ms/testingplatform

extension dev docs live here: https://github.com/microsoft/testfx/blob/main/docs/testingplatform/Index.md and the source code in the same repo in Platform.

**Comment by nbalu** [comment]
Sorry for being cocky here but that whole framework still depends uppon the current VSTest - ObjectModel implementation.

So making a console app that runs MSTests from my console app is just a snap (same for XUnit / NUnit). But to be able to observe or extend it the reference to the TestApplicationBuilder is essential. That framework is currently unable to lookup interface implementations out of box. There's the MSBuild adapter which they are using to hook up the testbridge and create entrypoints dynamicly. And the entrypoint is invoked by the MS adapter, which implements the interfaces within this repository.

So the NUnitAdapter was even changed to use the Microsoft.Testing.Extensions.VSTestBridge behind the scene :)
[nuget/net462/NUnit3TestAdapter.props](https://github.com/nunit/nunit3-vs-adapter/pull/1153/files#diff-6372de20a9f24d362984e52bb22c74951548ef54bf32a12d5bea7dabcf466a5b)

The whole entrypoint is generated in build time. It's a redicoulously hard to extend that if you have 0 control over that.

So overall thanks for the nice suggetion that I should use something that's currently not extendable at all. At least not by simply having a sidecar nuget to the test suite of anyone.

For sure I'll open up a ticket for the other team to please solve the lookup problem as probably anyone who expects to derive from the IDataConsumer is expecting that they should be picked up as-is. Currently it's not the case.

**Comment by nohwnd** [comment]
Thanks for your feedback, we will be trying to lift the things that are blocking you. 

> Sorry for being cocky here but that whole framework still depends uppon the current VSTest - ObjectModel implementation.

This is true, the new testing platform, and MSTest depend on object model, but not by our choice, it was simply the fastest way to get to a goal, while making it easier for nunit and xunit to onboard into the new model. 

> So overall thanks for the nice suggetion that I should use something that's currently not extendable at all. At least not by simply having a sidecar nuget to the test suite of anyone.

The new platform completely builds on being extensible by installing a nuget, if I understand what you said here correctly.

An extension is able to register a "hook" like this one to make it's code run when the autogenerated exe entrypoint is created:
https://github.com/microsoft/testfx/blob/main/src/Platform/Microsoft.Testing.Extensions.CrashDump/buildMultiTargeting/Microsoft.Testing.Extensions.CrashDump.props

From there you can consume the data that are coming on the message bus, rather than being constrained by the extension points we provided in vstest.

I will be glad to hear from you on microsoft/testfx. 

You can also find issues that were previously filed to create an extension to the new platform here: https://github.com/microsoft/testfx/issues?q=author%3Athomhurst 

Thom has been very helpful in helping us shape the new platform, and I hope we will get some valuable feedback from you as well.
