### ISSUE TITLE
Does Microsoft.CodeCoverage require any SKU of Visual Studio?

### ISSUE THREAD

**Issue by paulomorgado** [microsoft/vstest#4759]
Is any SKU of Visual Studio required to use [Microsoft.CodeCoverage](https://www.nuget.org/packages/Microsoft.CodeCoverage)?

**Comment by nohwnd** [comment]
I don't think so, it is included in the TestPlatform nuget package as well. https://www.nuget.org/packages/Microsoft.TestPlatform/17.9.0-preview-23531-01

**Comment by paulomorgado** [comment]
Thanks, @nohwnd.

How can I know for sure that a license is not required?

This is used like `coverlet`, right? Just add the NuGet package to the project.

**Comment by nohwnd** [comment]
The package is distributed via nuget, it's closed source, but free. You don't need to buy VisualStudio to use it.

**Comment by paulomorgado** [comment]
This is used like `coverlet`, right? Just add the NuGet package to the project.

**Comment by nohwnd** [comment]
@jakubch1 do you have some getting started guide for Microsoft.CodeCoverage?

**Comment by Evangelink** [comment]
This might be a good starting point: https://github.com/microsoft/codecoverage

**Comment by paulomorgado** [comment]
That's where I started, @evangelink.

But I found nothing related to licensing. Can you point me to a more specific doc?

I did find some usage docs at https://github.com/microsoft/codecoverage/tree/main/docs

**Comment by Evangelink** [comment]
@jakubch1 is owning the tool and will provide the 100% safe answer but as far as I can see from the NuGet package license file https://www.nuget.org/packages/Microsoft.CodeCoverage/17.9.0-preview-23531-01/License it's a simple MIT so there should be no problem using it.

**Comment by jakubch1** [comment]
@paulomorgado  There is no problem using it. It is also dependency of https://www.nuget.org/packages/Microsoft.NET.Test.SDK so you don't need to reference directly in csproj.

**Comment by paulomorgado** [comment]
Thanks @jakubch1.

So, I just need to remove coverlet and run `dotnet test --collect "Code Coverage;Format=cobertura"`.
