### ISSUE TITLE
Upgrade to .NET 9 SDK

### ISSUE THREAD

**Issue by mthalman** [microsoft/vstest#4779]
This repo should be targeting the .NET 9 SDK from the global.json file. This is a requirement necessary for .NET source build in order to target the `net9.0` TFM. If necessary, this change can be made after the first public preview release.

Related to https://github.com/dotnet/source-build/issues/3770

**Comment by Evangelink** [comment]
Hi @mthalman,

Is it supposed to be a manual update or is darc supposed to auto-update this repo?

**Comment by ViktorHofer** [comment]
Auto-updated via a Arcade dependency update when Arcade itself updates to the .NET 9 SDK. That said, you might need to do some manual work to unblock that dependency update then.

**Comment by nohwnd** [comment]
> this change can be made after the first public preview release.

Let's wait for .NET 9 preview 1 then. (or for new year when I am fully back at work, unless someone wants to commit to doing this).

**Comment by ViktorHofer** [comment]
Got fixed via https://github.com/microsoft/vstest/pull/4795

**Comment by Evangelink** [comment]
I wasn't sure if there was anything else to do. Cool then, moving forward by closing the issue (thanks @ViktorHofer).
