### ISSUE TITLE
TestCategory no longer works for VsTest

### ISSUE THREAD

**Issue by aaronportier** [microsoft/vstest#4782]
I changed my appium dotnet version and had to add yaml run settings files for the cloud provider I am using.  I am running this in Azure Pipeline with VsTest. The output seems like it knows how many tests should run with the Category but gives this message:
 now IsValidServiceResponse: Received None command..Service Workflow is not active
Creating run for selected test assemblies with following parameters
SourceFilter: ThisWontBeUsed TestCaseFilter: TestCategory=UserSubscription
Run title: TestRun_TestAutomationBSIntegration_Release-598

Why will it not be used? I even tried adding to the Runsettigns filter <TestCaseFilter>(TestCategory = UserSubscription)</TestCaseFilter> but that still gives me the same error

**Comment by nohwnd** [comment]
I don't think I follow what is not working. Can you please give a simple steps to reproduce this?

**Comment by aaronportier** [comment]
For a repo of steps just use the above chnages to your appium project and then TestCategory added in Test Criteria for vsTest will no longer work.
I can see in the logs it says "This Wont Be Used" but why will it not be used? 
</RunSettings>
Creating run for selected test assemblies with following parameters
SourceFilter: ThisWontBeUsed TestCaseFilter: TestCategory=UserSubscription
Run title: TestRun_TestAutomationBSIntegration_Release-606

**Comment by aaronportier** [comment]
Does anyone know where this line SourceFilter: ThisWontBeUsed might be coming from? In the past I never saw it now I have run setting files but they should not be doing anything to source filters.

**Comment by aaronportier** [comment]
I was able to get everything to run by turning Batch off. Unfortunately turning off Batch options makes my pipeline unable to re-run failed tests.I know that was a work around was the issue ever fixed.

**Comment by aaronportier** [comment]
Is anyone else experiencing or reporting this issue. It was working but now its not and I cant figure out why? The batching if clicked will not run using your Category Filter but If you turn batching off it will not re-run failed tests. Saying that it could not find them.

**Comment by aaronportier** [comment]
This is the state of my VSTest any ideas on next steps?

**Comment by nohwnd** [comment]
Could you sum this up into a simple repro please? 

I think what is happening is that running with batches is running your tests with DTAgent, and that ignores commandline parameters like the filter. 

Are you setting the filter on commandline or in runsettings file?

**Comment by aaronportier** [comment]
Command line. It is being run in Vstest with the filter in the test.

**Comment by nohwnd** [comment]
Please share a repro project and a command that shows the problem.
