### ISSUE TITLE
Make no test discovered an error instead of warning

### ISSUE THREAD

**Issue by pakrym** [Microsoft/vstest#479]
In most cases inability to discover tests should be an error rather then warning. Right now we have an issue when discovering tests for net451 fails but `dotnet test` returns zero exit code and build silently continues. 

```
> dotnet --version
1.0.0-rc4-004771

> dotnet test -f net451
Build started, please wait...
Build completed.

Test run for D:\github\aspnet\Testing\test\Microsoft.AspNetCore.Testing.Tests\bin\Debug\net451\Microsoft.AspNetCore.Testing.Tests.dll(.NETFramework,Version=v4.5.1)
Microsoft (R) Test Execution Command Line Tool Version 15.0.0.0
Copyright (c) Microsoft Corporation.  All rights reserved.

Starting test execution, please wait...
Warning: No test is available in D:\github\aspnet\Testing\test\Microsoft.AspNetCore.Testing.Tests\bin\Debug\net451\Microsoft.AspNetCore.Testing.Tests.dll. Make sure that installed test discoverers & executors, platform & framework version settings are appropriate and try again.

> $LASTEXITCODE
0

```

**Comment by natemcmaster** [comment]
We've run into this frequently on .NET Core, not just .NET Framework. Test discovery continues to be buggy. For example, see this build: https://ci.appveyor.com/project/aspnetci/websockets/build/1.0.335. It appeared to pass even though all tests failed to run.

**Comment by codito** [comment]
@sbaid @pvlakshm @Faizan2304 @smadala thoughts?

**Comment by pvlakshm** [comment]
Closing this; reactivate if still required.

**Comment by pakrym** [comment]
This is still a feature that would be nice to have.
