### ISSUE TITLE
Staircase in logger seems not to be properly fixed

### ISSUE THREAD

**Issue by 0xced** [microsoft/vstest#4802]
I see that commit 2850ac50f5dc1fc4bc69fe36eb000b0c9be58f6c from pull request #4756 is part of the [v17.9.0-preview-23577-04](https://github.com/microsoft/vstest/releases/tag/v17.9.0-preview-23577-04) tag, yet even after upgrading the `Microsoft.NET.Test.Sdk` package to version `17.9.0-preview-23577-04` I'm still seeing the staircase issue. 🤔

Reproduction steps are the same as in the original bug report (#4754) with the following command between step 2 and 3:

```
dotnet add tests/Serilog.Formatting.Log4Net.Tests.csproj package Microsoft.NET.Test.Sdk --version 17.9.0-preview-23577-04
```

**Comment by nohwnd** [comment]
The loggers don't come with the test.sdk package, the fix is propagated with vstest.console update, meaning you need to get it by upgrading your dotnet sdk / Visual Studio / TestPlatform package. 

It will come with 8.0.2xx sdk: https://github.com/dotnet/sdk/blob/release/8.0.2xx/eng/Versions.props

**Comment by 0xced** [comment]
I'm not sure in what exact version of the SDK this was fixed but I confirm that the staircases are gone with the dotnet SDK 8.0.204.
