### ISSUE TITLE
Official builds are failing

### ISSUE THREAD

**Issue by ViktorHofer** [microsoft/vstest#4811]
https://dnceng.visualstudio.com/internal/_build?definitionId=1222&_a=summary

Looks like test failures. Started happening on Saturday.

**Comment by ViktorHofer** [comment]
We would like to consume a new build asap to get diagnostics updated in the VMR.

**Comment by Evangelink** [comment]
Build (tests) seem good for me locally so I assume this is just another round of flaky unlucky runs.... I have restarted pipeline, let's see.

**Comment by Evangelink** [comment]
CI build is now green, closing as fixed
