### ISSUE TITLE
Don't combine PackageLicenseExpression and PackageLicenseFile (only use PackageLicenseExpression for MIT licensed packages)

### ISSUE THREAD

**Issue by szimmer-dap** [microsoft/vstest#4816]
## Description

We are currently adapting a package approval workflow, where packages are approved or blocked based on certain criteria. One very important criterion is the package's license. There is a list of approved licenses (like MIT, Apache, BSD, ...) and a list of licenses that can not be used (like GPL).

Although the Microsoft.Testplatform Nuget packages are under MIT license, it's hard to auto-approve them, because they use an embedded license file instead of an SPDX tag (https://spdx.github.io/spdx-spec/v2-draft/SPDX-license-list/). As a result, the license does not show up in the package's metadata.

The reason for this might be that Directory.Build.props has both a `<PackageLicenseExpression>` **and** a `<PackageLicenseFile>` property (and an additional `<PackageLicenseFullPath>` property): 

https://github.com/microsoft/vstest/blob/17723493fc8befbb889db2ff17b1ac98ba7b7c48/Directory.Build.props#L72-L74

However, nuspec supports only one **or** the other, but not both at the same time. It seems that the `<PackageLicenseExpression>` property is omitted during the build process.

## Steps to reproduce

Compare the "About" page of [Microsoft.TestPlatform](https://www.nuget.org/packages/Microsoft.TestPlatform/17.9.0-release-23619-01) with [Microsoft.Data.SqlClient](https://www.nuget.org/packages/Microsoft.Data.SqlClient), where the latter clearly states the package's license, while Microsoft.TestPlatform does not. Another example would be [Microsoft.NET.Test.Sdk](https://www.nuget.org/packages/Microsoft.NET.Test.Sdk/17.9.0-release-23619-01)

## Expected behavior

I would expect the corresponding nuspec files within the Nuget packages to contain a line like `<license type="expression">MIT</license>` and tools to be able to display "MIT" as the license of those packages.

## Actual behavior

The nuspec file contains the line `<license type="file">LICENSE_MIT.txt</license>` and tools (including nuget.org) are not able to determine the license from that.

**Comment by nohwnd** [comment]
This is probably because until recently this package was not under MIT, would you consider creating a PR to fix this?

**Comment by nohwnd** [comment]
>  I also can't build this repository and verify the effect of any changes without getting into the Acrcade build infrastructure first,

You can run `.\build.cmd -pack` in the main folder, and you will find the packages in artifacts\packages folder. You don't need to install anything special to get into "arcade" mode.

**Comment by Evangelink** [comment]
Self-assigning, I will have a look next week.

**Comment by lahma** [comment]
Created #4890 to fix the issue.

**Comment by Evangelink** [comment]
Thanks @lahma! And sorry, it's alread been 3 weeks and I didn't handle it... I have been really busy with many other requests and releases.
