### ISSUE TITLE
https://aka.ms/vstest-report redirects to archived vstest-docs repository

### ISSUE THREAD

**Issue by KalleOlaviNiemitalo** [microsoft/vstest#4829]
## Description

<https://aka.ms/vstest-report> redirects to <https://github.com/Microsoft/vstest-docs/blob/master/docs/report.md#syntax-of-default-loggers>, which is in an archived repository.
Seems it should redirect to <https://github.com/microsoft/vstest/blob/main/docs/report.md#syntax-of-default-loggers> instead.
That would make it similar to how <https://aka.ms/vstest-collect> redirects to <https://github.com/microsoft/vstest/blob/main/docs/analyze.md>.

## Steps to reproduce

Run `dotnet test --help`.
It outputs the following, as part of the description of the `-l, --logger <LOGGER>` option:

> See https://aka.ms/vstest-report for more information on logger arguments.

Follow the link to <https://aka.ms/vstest-report>.

## Expected behavior

The link should redirect to <https://github.com/microsoft/vstest/blob/main/docs/report.md#syntax-of-default-loggers>, which is in a maintained repository.

## Actual behavior

The link redirects to <https://github.com/Microsoft/vstest-docs/blob/master/docs/report.md#syntax-of-default-loggers>, which is in a repository that was archived on Dec 5, 2022.

## Diagnostic logs

```
$ curl --head https://aka.ms/vstest-report
HTTP/1.1 301 Moved Permanently
Server: Kestrel
Location: https://github.com/Microsoft/vstest-docs/blob/master/docs/report.md#syntax-of-default-loggers
Request-Context: appId=cid-v1:9b037ab9-fa5a-4c09-81bd-41ffa859f01e
X-Response-Cache-Status: True
Content-Length: 0
Expires: Tue, 16 Jan 2024 00:14:14 GMT
Cache-Control: max-age=0, no-cache, no-store
Pragma: no-cache
Date: Tue, 16 Jan 2024 00:14:14 GMT
Connection: keep-alive
Strict-Transport-Security: max-age=31536000 ; includeSubDomains
```

## Environment

.NET SDK 8.0.101

**Comment by Evangelink** [comment]
Thanks @KalleOlaviNiemitalo!

We will work on fixing that asap.

**Comment by Evangelink** [comment]
@nohwnd Could you please fix the redirect and ideally allow the team to edit this redirect link?

**Comment by nohwnd** [comment]
done
