### ISSUE TITLE
Regression with console logger in .NET 9

### ISSUE THREAD

**Issue by rolfbjarne** [microsoft/vstest#4852]
## Description

It seems the output from the console logger is parsed, and may case tests to fail.

## Steps to reproduce

Project file:

```xml
<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="nunit" Version="3.12.0" />
    <PackageReference Include="NUnit3TestAdapter" Version="3.15.1" />
    <PackageReference Include="Microsoft.NET.Test.Sdk" Version="17.4.1" />
  </ItemGroup>
</Project>
```

Test file:

```cs
using System;
using NUnit.Framework;

namespace MyTests {
	[TestFixture ()]
	public class TestSuite {
		[Test]
		public void Something ()
		{
			Console.Error.WriteLine ("error BI1117: bgen: The member 'SomeMethod' is decorated");
		}
	}
}
```

Running just `dotnet test` works fine:

```shell
$ dotnet test
Restore complete (0.2s)
You are using a preview version of .NET. See: https://aka.ms/dotnet-support-policy
  testcase succeeded (0.1s) → bin/Debug/net9.0/testcase.dll

Build succeeded in 1.0s
```

Making the console logger's verbosity detailed does not:

```shell
$ dotnet test '--logger:console;verbosity=detailed'
Restore complete (0.2s)
You are using a preview version of .NET. See: https://aka.ms/dotnet-support-policy
  testcase succeeded (0.1s) → bin/Debug/net9.0/testcase.dll
  testcase failed with errors (0.0s)
    VSTESTTASK2 : error BI1117: bgen: The member 'SomeMethod' is decorated
    VSTESTTASK2 : Standard error Messages: 
    VSTESTTASK2 : error BI1117: bgen: The member 'SomeMethod' is decorated

Build failed with errors in 1.0s
```

## Expected behavior

Enabling detailed verbosity shouldn't affect test results.

## Actual behavior

Enabling detailed verbosity makes tests fail.

## Environment

This is with .NET 9.0.100-preview.2.24074.1.

In particular this regressed in this range: https://github.com/microsoft/vstest/compare/1c68c247cc3d69ad04afeb574c3d0bc352ff16e5...53df73d3373e7964f6fb37f4437bda2720a75ef2

So I'm guessing this is the culprit: https://github.com/microsoft/vstest/commit/6d400ab388ab7321586b4bad16d4ca4be1e5bb31

CC @nohwnd

**Comment by nohwnd** [comment]
Thanks, working on fixing it.

You can opt out from the new logger using `-p:VSTestUseMSBuildOutput=false`.

**Comment by nohwnd** [comment]
Thanks for your analysis, it was spot on. I forwarded unrecognized messages to the base ToolTask, which calls into CanonicalError to figure out if the received message is an error, and will write any message with "error" string in it into the ErrorStream. 

base.LogEventsFromTextOutput => Log.LogMessageFromText => CanonicalError.Parts messageParts = CanonicalError.Parse(lineOfText);
https://github.com/dotnet/msbuild/blob/e7a44d757e097eb17dcac5a8436645dc612fec4b/src/Shared/TaskLoggingHelper.cs#L1365

**Comment by nohwnd** [comment]
This was merged and will be released in net9-preview1.
