### ISSUE TITLE
EventLogContainer Index is out of bounds

### ISSUE THREAD

**Issue by hankweber** [microsoft/vstest#4873]
## Description

We are currently running into an issue running vstest in ADO pipelines where the runs will execute all of our tests, but then wait because ADO hasn't received data about all tests. We have telemetry and logs that make us believe that test execution is actually completing but then something in VSTest is preventing the results from being sent to ADO. When looking into some logs we found that the EventLogCollector/Container is repeatedly hitting an Index is out of bounds issue during the OnTestSessionEnd event until the test session times out.

## Steps to reproduce

This issue doesn't repro 100% of the time. We usually hit the issue a few times a day out of 100s of runs.

## Expected behavior

Test session should end successfully.

## Actual behavior

Test session continues indefinitely due to the EventLogDataCollector hitting an error.

## Diagnostic logs

[Slice-Execution-29529552_vwn0nr.datacollector.24-01-26_23-44-45_57554_6-SHORT.txt](https://github.com/microsoft/vstest/files/14116494/Slice-Execution-29529552_vwn0nr.datacollector.24-01-26_23-44-45_57554_6-SHORT.txt) - NOTE: the exception on line 18769 happens repeatedly until our test session times out and the original diag file repeats this error for 4+ hrs. I cut out the repeated errors to trim down file size.

[Slice-Execution-29572449_t1fmhp.datacollector.24-02-01_01-42-10_22148_6-Good_Example.txt](https://github.com/microsoft/vstest/files/14127845/Slice-Execution-29572449_t1fmhp.datacollector.24-02-01_01-42-10_22148_6-Good_Example.txt) - Example from a run where we do not experience the issue

## Environment

OS: Windows 11
vstest: 17.8

**Comment by nohwnd** [comment]
I see there is real problem with the logger. It tries to handle the clearing of the log, but does not do it correctly and so the underlying "windows" api throws.

**Comment by nohwnd** [comment]
This was fixed by removing the event logger from the run
