### ISSUE TITLE
Print adapter missing error messages in Tests output pane

### ISSUE THREAD

**Issue by codito** [Microsoft/vstest#488]
Tests are not discovered if the adapter is missing in test project. This could happen if `*.TestAdapter.dll` is missing in output directory, or Test Adapter is not referenced in test project, or test adapter vsix is missing.

Tests output pane should provide guidance to users in such cases.

Related #442.

**Comment by snkota** [comment]
This is being tracked external to this repo here:
https://developercommunity.visualstudio.com/content/problem/145938/print-adapter-missing-error-messages-in-tests-outp.html
