### ISSUE TITLE
Microsoft.NET.Test.Sdk as transitive dependency?

### ISSUE THREAD

**Issue by thomhurst** [microsoft/vstest#4896]
Is there a way for this to flow through to a project if it's referenced by my library?

Currently if I include it as a dependency, the test explorer doesn't find anything.

The consuming project has to explicitly install it.

If that has to be the case, then so be it, but it'd be easier for a consumer to not have to worry about pulling this in.

Thanks

**Comment by nohwnd** [comment]
We briefly did make it transitive, and that caused issues so we reverted before releasing it. See https://github.com/microsoft/vstest/issues/3227
