### ISSUE TITLE
Test Hang in ADO

### ISSUE THREAD

**Issue by bupafloreggian** [microsoft/vstest#4897]
## Description

When a set of unit tests run in azure pipelines the VSTest task does not complete, it hangs then times out. I have extracted as much logs as possible and I will attach them. 

I have not been able to reproduce this on my local machine, but it is reproducible in the ADO pipeline. I have verified that it isnt the same test which causes the hang.

## Expected behavior

VSTest task completes and publishes test results.

## Actual behavior

VSTest task does not complete, seems to hang then timesout. 

## Diagnostic logs
[log.datacollector.24-02-14_15-57-40_50569_4.log](https://github.com/microsoft/vstest/files/14289403/log.datacollector.24-02-14_15-57-40_50569_4.log)
[log2.log](https://github.com/microsoft/vstest/files/14289407/log2.log)

## Environment

I am not 100% sure of the agents we have in our pool, I am currently reaching out to our devops team to get this information.

**Comment by nohwnd** [comment]
How are you executing your tests, and how long is your longest test? I see you have crash dumps set to always collect a dump, can you disable that and instead collect a hang dump ? (e.g. by specifiyng `dotnet test --blame-hang-timeout 10min`) ?

**Comment by bupafloreggian** [comment]
Ill try the hang dump thank you

**Comment by bupafloreggian** [comment]
We are executing the tests with a command similar to this:

`& "C:\Program Files\Microsoft Visual Studio\2022\Enterprise\Common7\IDE\Extensions\TestPlatform\vstest.console.exe" /Enablecodecoverage /Settings:"$(System.DefaultWorkingDirectory)/CodeCoverage.runsettings" /Diag:"$(Agent.TempDirectory)\TestResults\logger.log"  /Logger:"trx" $_.FullTestName`

**Comment by bupafloreggian** [comment]
When running in my local the longest test is around 15 seconds

**Comment by bupafloreggian** [comment]
I have managed to find the issue. The issue was a combination of how the unit tests were written and the xunit config that was being used on the build agent. Setting this value to false solved my issue:
![MicrosoftTeams-image](https://github.com/microsoft/vstest/assets/160075512/7cb7d1ae-465e-466c-96dc-997bc0387bc8)
