### ISSUE TITLE
When running Tests if I use Test Category it is ignored when running Batch Mode

### ISSUE THREAD

**Issue by aaronportier** [microsoft/vstest#4910]
IsValidServiceResponse: Received None command..Service Workflow is not active
Creating run for selected test assemblies with following parameters
SourceFilter: ThisWontBeUsed TestCaseFilter: TestCategory=UserSubscription
The above is the log and All my tests run not just the UserSubscription ones.

**Comment by nohwnd** [comment]
duplicate of https://github.com/microsoft/vstest/issues/4782
