### ISSUE TITLE
testhost.dll is double written

### ISSUE THREAD

**Issue by Youssef1313** [microsoft/vstest#4911]
## Description

See https://github.com/KirillOsenkov/MSBuildStructuredLog/wiki/Double%20write%20detection and https://www.meziantou.net/detecting-double-writes-in-msbuild-using-the-binlog.htm for info about double writes.

In a binlog from a private repo, I'm seeing testhost is double written.

![image](https://github.com/microsoft/vstest/assets/31348972/42823142-2e88-4e24-a191-a8af091109a6)

## Steps to reproduce

I didn't try to produce a minimal repro, but basically, the package props (https://github.com/microsoft/vstest/blob/39c7dd12c7ec24d0552513e84d95476f2077ca33/src/package/Microsoft.TestPlatform.TestHost/Microsoft.TestPlatform.TestHost.props) is marking `testhost.dll` in `build/netcoreapp3.1/x64` directory as `<CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>`. However, MSBuild also adds the `testhost.dll` from `lib` directory to `ReferenceCopyLocalPaths`.

## Expected behavior

No double writes. It's a bit discouraged.

## Actual behavior

Double writes.

**Comment by nohwnd** [comment]
@drognanar I think you were investigating similar issue in the past, do you remember if it was resolved?

**Comment by nohwnd** [comment]
repeating the steps above I no longer see any double writes.
