### ISSUE TITLE
Listing tests broken with terminal logger

### ISSUE THREAD

**Issue by akoeplinger** [microsoft/vstest#4914]
## Description

Using .NET 9 Preview 1 SDK which enabled the terminal logger in VSTest it's no longer possible to list tests from an assembly

## Steps to reproduce

```
$ dotnet new mstest
$ dotnet test --list-tests
```

## Expected behavior

List the tests in the assembly.

## Actual behavior

```
$ dotnet test --list-tests
Restore complete (0,2s)
You are using a preview version of .NET. See: https://aka.ms/dotnet-support-policy
  vstest succeeded (4,7s) → bin/Debug/net9.0/vstest.dll

Build succeeded in 5,6s
```

A workaround is to disable the terminal logger in VSTest by passing `-p:VsTestUseMSBuildOutput=false`

## Environment

macOS 14, dotnet SDK 9.0 preview1

/cc @nohwnd

**Comment by nohwnd** [comment]
This is an issue that is common to all terminal logger enabled workloads I think. @baronfel I think there is issue on msbuild about not outputting the console, we would see the same here for logs, or for additional xunit output that it writes to console. I cannot find the issue, do you know which one I mean, please?

**Comment by Evangelink** [comment]
Ping @baronfel

**Comment by baronfel** [comment]
Thanks for the ping - discussing with the team now.

**Comment by nohwnd** [comment]
This will be solved in the latest insertion to SDK (it did not make it in preview6 :( )

![image](https://github.com/microsoft/vstest/assets/5735905/3e697e54-e1db-482f-ad1f-3d418b7dfc72)

**Comment by baronfel** [comment]
@JakubJares which insertion? preview6 branch creation was delayed to today
so it may be possible to get this in.

**Comment by nohwnd** [comment]
https://github.com/dotnet/sdk/pull/41674 this one should be it.

**Comment by nohwnd** [comment]
It is already merged to main.
