### ISSUE TITLE
Hardcoded TFM is wrong when building from source

### ISSUE THREAD

**Issue by ViktorHofer** [microsoft/vstest#4919]
https://github.com/microsoft/vstest/blob/5b4caa41eb39d624cd90563d9f24e23186c18a52/src/Microsoft.TestPlatform.TestHostProvider/Hosting/DotnetTestHostManager.cs#L301

Unless I'm mistaken, the TFM here isn't net6.0 anymore but either net9.0 or net8.0.

cc @nohwnd @MichaelSimons

**Comment by nohwnd** [comment]
I don't see this PR https://github.com/microsoft/vstest/pull/4856/files touching the host project, and net6.0 is the minimal tfm the nuget should target, are you seeing some errors?

**Comment by ViktorHofer** [comment]
The project wasn't touched in that PR because source-build overwrites all TFMs in the repo in Directory.Build.targets: https://github.com/microsoft/vstest/blob/82c581ff79a09354ce2ab007713319f629568aa9/Directory.Build.targets#L6-L20
