### ISSUE TITLE
Eliminate unapproved prebuild exclusions

### ISSUE THREAD

**Issue by nohwnd** [microsoft/vstest#4927]
https://github.com/dotnet/source-build/issues/4188

After updating arcade I am seeing new prebuilts, which are not in baseline.

[microsoft/vstest#4915 (checks)](https://github.com/microsoft/vstest/pull/4915/checks?check_run_id=22383316793)

.packages/microsoft.dotnet.arcade.sdk/9.0.0-beta.24156.2/tools/SourceBuild/AfterSourceBuild.proj#L80
.packages/microsoft.dotnet.arcade.sdk/9.0.0-beta.24156.2/tools/SourceBuild/AfterSourceBuild.proj(80,5): error : (NETCORE_ENGINEERING_TELEMETRY=AfterSourceBuild) 3 new pre-builts discovered! Detailed usage report can be found at /__w/1/s/artifacts/sb/prebuilt-report/baseline-comparison.xml.
See [aka.ms/dotnet/prebuilts](https://aka.ms/dotnet/prebuilts) for guidance on what pre-builts are and how to eliminate them.
Package IDs are:
Microsoft.AspNetCore.App.Ref.8.0.1
Microsoft.NETCore.App.Host.linux-x64.8.0.1
Microsoft.NETCore.App.Ref.8.0.1

This is becuase 8.0.0 of those were added to prebuilts.xml in our repo, when they should not have been, in https://github.com/microsoft/vstest/pull/4856/files PR. 

Investigate how to get rid of them. 

@evangelink if you have any ideas I am all ears.

**Comment by Evangelink** [comment]
I am just seeing the comments on the related PR so I see that what I said is not accurate. I have no idea how to fix that.

**Comment by Evangelink** [comment]
@nohwnd I think this issue is now stale.

**Comment by nohwnd** [comment]
Yup. the exclusions were okayed, because we are excluding net8 bits when building for net9, and we cannot avoid restoring the net8 bits.
