### ISSUE TITLE
dotnet test requires 1.0.x runtime framework to be installed

### ISSUE THREAD

**Issue by eerhardt** [Microsoft/vstest#494]
## Description
> Describe the issue you've observed
In the dotnet/cli `master` branch, we have moved the CLI to .NET Core 2.0 runtime.  However, we still need to install .NET Core 1.0.x because dotnet test requires 1.0.x to be present in order to work.

The reason 1.0.x needs to be installed is because the `vstest.console.runtimeconfig.json` file gets installed into the `sdk` folder, and it explicitly references 1.0.0.

We need to re-structure how we are bringing in the Test Platform dependencies into the CLI in order for the CLI to pick the runtime, dependency closure, etc. of the application.  This should follow the same model we are already using for MSBuild, Roslyn C# compiler, NuGet, etc.  The Test Platform nupkg shouldn't be dropping all these assemblies and assets as "contentFiles" the way it does today.

## Steps to reproduce
Install a `2.0.0-alpha` .NET Core SDK build, uninstall/delete the `1.0.x` runtime that comes with it, and try to run `dotnet test`.

## Expected behavior
`dotnet test` should be able to run with just `2.0.0` of the .NET Core runtime installed.

## Actual behavior
`dotnet test` fails because the `1.0.x` runtime is not installed.

/cc @livarcocc @piotrpMSFT

**Comment by piotrpMSFT** [comment]
Once agreed on the approach, please open a CLI issue. We alerady do a bunch of runtimeconfig generation and can do one more for this instance.

**Comment by codito** [comment]
I think we were using `contentFiles` since there is a requirement for an additional folder to be copied for vstest.console (the `Extensions` folder). Probably there is a better way. /cc: @smadala @Faizan2304

**Comment by codito** [comment]
`vstest.console` is now built for netcoreapp2.0, it is inserted with https://github.com/dotnet/cli/commit/d42602e3774149136d6fb2866225764f88ad0db6 in dotnet-cli repository.
