### ISSUE TITLE
TestLogger/DataCollector can't be used to log Test Case Start

### ISSUE THREAD

**Issue by davidmatson** [microsoft/vstest#4950]
## Description

I'm trying to use VSTest extensibility to integrate with another logging system that needs to report as soon as a test case starts. ITestLogger allows me to log on TestCaseEnd, but it doesn't provide any indication when a test case starts. This functionality is important especially for long-running test cases.

I tried using DataCollector and InProcessDataCollection, but neither of those help either - neither receive other messages as a test is running, unlike ITestLogger. Even using all in combination, I still can't get all the events as they happen - InProcessDataCollection doesn't have a way to log messages out; DataCollector can only log warnings or errors, but even these aren't sent to the ITestLogger right away - the platform appears to buffer any logged messages after the first one, so sending a "test case start" message from a DataCollector to an ITestLogger also does not work.

This scenario might be possible by replacing vstest.console.exe entirely with my own code, but that's far more code than I'd like to own just to be notified of and log TestStart events.

This is a feature request to add a TestStart event to TestLoggerEvents.

**Comment by nohwnd** [comment]
Hello, are you using some specific testing framework? Or this is a for a "service" and needs to take all testing frameworks into account?

**Comment by davidmatson** [comment]
This is a for a service and needs to take all testing frameworks into account.

**Comment by ravigneaux-1** [comment]
I would also be interested in this, the use case being the attribution of received messages to the test cases that sent them via `IFrameworkHandle.SendMessage()`. This might require to forward events to the test loggers unbuffered, though, and I don't think that's the case at the moment.

@davidmatson, when you say

> ITestLogger allows me to log on TestCaseEnd

are you referring to the [`TestLoggerEvents.TestResult`](https://github.com/microsoft/vstest/blob/v17.9.0/src/Microsoft.TestPlatform.ObjectModel/Logger/TestLoggerEvents.cs#L35) event?

**Comment by davidmatson** [comment]
> @davidmatson, when you say
> ITestLogger allows me to log on TestCaseEnd
> are you referring to the [`TestLoggerEvents.TestResult`](https://github.com/microsoft/vstest/blob/v17.9.0/src/Microsoft.TestPlatform.ObjectModel/Logger/TestLoggerEvents.cs#L35) event?

Yes. I was originally thinking of how test framework adapters call [RecordEnd](https://github.com/microsoft/vstest/blob/2588f022c1c4a12e159e0ed07f5a5ea3f3c9eaa8/src/Microsoft.TestPlatform.ObjectModel/Adapter/Interfaces/ITestExecutionRecorder.cs#L37) but [RecordResult](https://github.com/microsoft/vstest/blob/2588f022c1c4a12e159e0ed07f5a5ea3f3c9eaa8/src/Microsoft.TestPlatform.ObjectModel/Adapter/Interfaces/ITestExecutionRecorder.cs#L21) is probably more accurate.

**Comment by nohwnd** [comment]
This is a new feature and won't be implemented, we are focusing on adding new features to Testing.Platform instead. https://aka.ms/testingplatform
