### ISSUE TITLE
Unable to find a datacollector with friendly name 'Screen and Voice Recoder'

### ISSUE THREAD

**Issue by sampath-ganesan** [microsoft/vstest#5001]
I am using dot net 8.0 as targetversion and using specflow+mstest to run test cases. i added .runsetting with this data collector and 

<DataCollector uri="datacollector://microsoft/VideoRecorder/1.0" assemblyQualifiedName="Microsoft.VisualStudio.TestTools.DataCollection.VideoRecorder.VideoRecorderDataCollector, Microsoft.VisualStudio.TestTools.DataCollection.VideoRecorder, Version=15.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a" friendlyName="Screen and Voice Recorder">
    <Configuration>
        <MediaRecorder sendRecordedMediaForPassedTestCase="true"  xmlns="">           ​
            <ScreenCaptureVideo bitRate="512" frameRate="2" quality="20" />​
        </MediaRecorder>​
    </Configuration>
</DataCollector>

when i run it with visual studio its working fine i am able to get the recoding for the test execution. but when i use dotnet vstest "path\to\dll\file\project.dll" /Settings: "path\to\setting\file\.runsetting" /Logger: "trx" /TestAdaptor: "path\to\testadaptor\" 

i am getting Data Collection : Unable to find a datacollector with friendly name 'Screen and Voice Recorder'

**Comment by nohwnd** [comment]
The collector is shipped with VS only.
