### ISSUE TITLE
Missing .trx Files in Azure Build Pipeline from VSTest task

### ISSUE THREAD

**Issue by purnravip** [microsoft/vstest#5007]
Dear Sir/Madam,

This is regarding the issue we've encountered in our Azure build pipeline setup. 

We have configured our Azure build pipeline with Visual Studio Test (Version 1.0.98). However, we have noticed that only the .coverage attachment is generated, and no .trx file is being produced.

Here is the path to the .coverage attachment:

D:\Agents\V2\2.126.0\_work\xxxx\s\TestResults\xxxx\svc_tfs_xxxx 2024-04-29 16_32_27.coverage
Upon reviewing the logs, we observed the following entry:

Testing leaf: 'C:\Program Files (x86)\Microsoft Visual Studio\2017\BuildTools\Common7\IDE\CommonExtensions\Microsoft\TestWindow\vstest.console.exe'
Does not exist.

The vstestconsole.exe didnt exist on our build agent, please let us know if this is causing the issue and the next steps on how to install this.

Subsequently, the next task in our pipeline, Run Code Analysis (Version 4.23.1), is unable to locate the .trx files. Below are the relevant log lines:

Attempting to locate a test results (.trx) file...
Looking for TRX files in: D:\Agents\V2\2.126.0\_work\xxxx\TestResults, D:\Agents\V2\2.126.0\_work\xxxx\s\TestResults
No test results files found
Did not find any binary coverage files in the expected location.
As a consequence, our code coverage for SonarQube is currently showing 0.0%. We would greatly appreciate your assistance in identifying why the .trx files are missing and resolving this issue promptly.

Thank you for your attention to this matter.

Would you be so kind to explore the issue and let me know where the problem is?

**Comment by nohwnd** [comment]
Hello, if you are using VS2017, the support of that version has ended. Extended support is available, but you have to contact your extended support contact.

**Comment by purnravip** [comment]
Thanks

**Comment by purnravip** [comment]
Thank you!
