### ISSUE TITLE
Thread safety is not working properly on .net 6.0 and .net 8.0 for mstest

### ISSUE THREAD

**Issue by sampath-ganesan** [microsoft/vstest#5011]
## Description
I am running mstest test case in multiple thread and when i do that data from one thread to another thread

## Steps to reproduce
1. create mstest + reqnroll project
2. set Parallelize this is the one i am using 
`<Parallelize>
<Workers>2</Workers>
<Scope>MethodLevel</Scope>
</Parallelize>`
3. and in the Hooks class file i am initializing scenariocontext which is from reqnroll
[Binding]
public class Binding
{
    private readonly ScenarioContext scenarioContext;

    public Binding(ScenarioContext scenarioContext)
    {
        this.scenarioContext = scenarioContext;
    }
}
4. when i use scenario context in the other hooks like this
public class Binding
{
    private readonly ScenarioContext scenarioContext;

    public Binding(ScenarioContext scenarioContext)
    {
        this.scenarioContext = scenarioContext;
    }
    
    [AfterStep]
    public AfterStep()
   {
      Console.WriteLine(this.scenarioContext.StepContext.StepInfo.Text)
   }
}

another example

    private readonly ScenarioContext scenarioContext;
    private int randomValue;

    public Binding(ScenarioContext scenarioContext)
    {
        this.scenarioContext = scenarioContext;
    }
    
    [BeforeScenario]
    public BeforeScenario()
    {
        this.randomValue = Randomizer.GetRandomNumberInRange(0, 100); //I am using custom package in my project to generate random numbers
    }

    [AfterStep]
    public AfterStep()
    {
      Console.WriteLine($"Random Number: {this.radomValue}"); 
      Console.WriteLine($"Thread.CurrentThread.ManagedThreadId");
    }

when its printing the value both are getting mixed up for example 
thread Id 14 assign randomValue as 1
thread Id 15 assign randomValue as 85

when its running thread id 14 its taking randomValue as 85 instead of 1

**Comment by nohwnd** [comment]
This does not look like mstest code, `AfterStep` or similar attributes are not use by mstest. Which testing framework are you actually using?  

I am also not sure what you are showing in your example, the code is most likely running by using Tasks, which won't translate 1:1 to threads.

**Comment by sampath-ganesan** [comment]
i am using specflow testing framework

**Comment by sampath-ganesan** [comment]
in this example, where i am setting the random value on each thread and that should be isolated right? but when Parallelize on .runsettings its picking up the last threads value instead of its own thread value 

private readonly ScenarioContext scenarioContext;
private int randomValue;

public Binding(ScenarioContext scenarioContext)
{
    this.scenarioContext = scenarioContext;
}

[BeforeScenario]
public BeforeScenario()
{
    this.randomValue = Randomizer.GetRandomNumberInRange(0, 100); //I am using custom package in my project to generate random numbers
}

[AfterStep]
public AfterStep()
{
  Console.WriteLine($"Random Number: {this.radomValue}"); 
  Console.WriteLine($"Thread.CurrentThread.ManagedThreadId");
}
