### ISSUE TITLE
VSTest after 1st Run will re-run failed tests but instead runs all tests

### ISSUE THREAD

**Issue by aaronportier** [microsoft/vstest#5016]
I am running the Latest. I have a Category that's set to Filter by. I have 1 test it fails and when Its supposed to rerun that failed test it runs all the tests?
Its in Batch Mode 1 Test.

IsValidServiceResponse: Received None command..Service Workflow is not active
Creating run for selected test assemblies with following parameters
SourceFilter: ThisWontBeUsed TestCaseFilter: TestCategory=Notifications

Does anyone know why this is happening?

**Comment by nohwnd** [comment]
This is a VSTest task issue, vstest itself (this repo) does not do batching in this way, please file an issue on the VSTest task: https://github.com/microsoft/azure-pipelines-tasks
