### ISSUE TITLE
Update maxversiontested so xaml islands can be used in vstest.console.exe

### ISSUE THREAD

**Issue by ChrisGuzak** [microsoft/vstest#5041]
## Description

This is a variation of #4887 that I missed when I fix that (that I've verified via updated VS).

vstest.console.exe needs the same manifest update.

but I took a look at the source and see it has been updated. need to investigate further.

## Steps to reproduce

see linked issue for repo and details

**Comment by nohwnd** [comment]
Would you post a PR for this please?

**Comment by ChrisGuzak** [comment]
[The code](https://github.com/search?q=repo%3Amicrosoft%2Fvstest%20maxversiontested&type=code) in this project is correct. 

I'm guessing the ingestion `vstest.console.exe` into the VS installer is not following the same path as `testhost.exe`. I see the files are in different locations. 

`C:\Program Files\Microsoft Visual Studio\2022\Enterprise\Common7\IDE\CommonExtensions\Microsoft\TestWindow\vstest.console.exe`
`C:\Program Files\Microsoft Visual Studio\2022\Enterprise\Common7\IDE\Extensions\TestPlatform\testhost.exe`

I also installed these tools using the [BuildTools install location](https://visualstudio.microsoft.com/downloads/#remote-tools-for-visual-studio-2022). and that ended up in a different location from those mentioned above.

'C:\Program Files (x86)\Microsoft Visual Studio\2022\BuildTools\Common7\IDE\CommonExtensions\Microsoft\TestWindow\vstest.console.exe'

Do you know who owns the VS ingestion process for these binaries? I think we need to ask them why this binary has not kept up with testhost.exe.

**Comment by nohwnd** [comment]
You've got mail. CommonExtensions\Microsoft\TestWindow\vstest.console.exe is a wrapper of the real vstest.console for backwards compat reasons. It won't have your manifest changes, and so that is why it does not work.

**Comment by nohwnd** [comment]
This needs to be solved for the wrapper that Test Explorer owns, information was sent via email because that project is internal.
