### ISSUE TITLE
Some times build is stuck  and never completes  

### ISSUE THREAD

**Issue by jinujoseph** [Microsoft/vstest#509]
**Repro Steps**
- Create a new Unit Test Project  ( .Net Core) 
- Add few test cases 
- Build and Run tests
- Now close the solution and reopen 
- Build again 

**Expected** 
Builds successfully 

**Actual**
Build/Rebuild  never completes 
![image](https://cloud.githubusercontent.com/assets/12449387/23033350/8f172e68-f42c-11e6-8f2e-762a12962a53.png)

Sample projects
\\mlangfs1\public\Jinuj\TestCases\UnitTestBuildNeverCompletes

Note: If it doesn't repro, try a few rounds of closing solution and reopening again.

Build: RTW+26214.1

**Comment by jinujoseph** [comment]
@srivatsn  pointed out that this might be actually associated with https://github.com/NuGet/Home/issues/4486 , though i never saw the restore command being started.

**Comment by MiaomiaoHuangfu** [comment]
The issue is not repro on d15rel.26227.01 and d15rel.26224.01.

**Comment by jinujoseph** [comment]
Closing this as verified in recent builds
