### ISSUE TITLE
Running Test from the code editor discovers no tests

### ISSUE THREAD

**Issue by jinujoseph** [Microsoft/vstest#510]
**Repro Steps**
- Copy the solution from \\mlangfs1\public\Jinuj\TestCases\ConnectProductivityDemoOn.NETCore to your machine 
- open sln 
- Build and run the tests from the test explorer
- Now pick one test from the code editor and run 

**Expected**
![image](https://cloud.githubusercontent.com/assets/12449387/23034204/e25bc572-f42f-11e6-99d1-6a8e56ae4ada.png)

**Actual** 
![image](https://cloud.githubusercontent.com/assets/12449387/23034235/06befbfa-f430-11e6-9951-05ba4f3f9a05.png)

**Build** 
RTW.26214.1

**Comment by codito** [comment]
We may want to investigate this for RTM, it looks like a serious one. /cc @sbaid

**Comment by MiaomiaoHuangfu** [comment]
After updating the references to following, "Run Tests" from code editor succeeded as expected.
  <ItemGroup>
    <PackageReference Include="Microsoft.NET.Test.Sdk" Version="15.0.0" />
    <PackageReference Include="MSTest.TestAdapter" Version="1.1.13" />
    <PackageReference Include="MSTest.TestFramework" Version="1.1.13" />
  </ItemGroup>

Tested and verified on d15rel.26321.00.

**Comment by MiaomiaoHuangfu** [comment]
After updating the references to following, "Run Tests" from code editor succeeded as expected.
```
  <ItemGroup>
    <PackageReference Include="Microsoft.NET.Test.Sdk" Version="15.0.0" />
    <PackageReference Include="MSTest.TestAdapter" Version="1.1.13" />
    <PackageReference Include="MSTest.TestFramework" Version="1.1.13" />
  </ItemGroup>
```
Tested and verified on d15rel.26321.00.
