### ISSUE TITLE
IFrameworkHandle.LaunchProcessWithDebuggerAttached needs ability to control ProcessStartInfo

### ISSUE THREAD

**Issue by bradwilson** [microsoft/vstest#5171]
## Description

I am trying to replace a situation with the xUnit.net v3 VSTest adapter where I launch the test project (out of process) and then attach via `IFrameworkHandle2.AttachDebuggerToProcess`. Ideally I'd use `IFrameworkHandle.LaunchProcessWithDebuggerAttached`.

However, I need the ability to redirect StandardInput and StandardOutput: https://github.com/xunit/xunit/blob/f529cc6fc0d3950daba1bcfeb7a95d88bcf1f374/src/xunit.v3.runner.utility/Frameworks/v3/Xunit3.cs#L376-L381

If I can't do that, then I can't use `LaunchProcessWithDebuggerAttached`.

**Comment by nohwnd** [comment]
This API `LaunchProcessWithDebuggerAttached` will request visual studio (or whatever the client is) to start the process on your behalf with debugger attached and will hand you back the PID. I don't think that it is possible to consume the output from the original process, when it was actually VS, who started the process.

The new api `AttachDebuggerToProcess`, asks the client to attach to a process you started, and in that case this is possible.

I've read the linked issue, but I did not get why you are reverting to the older api?

**Comment by bradwilson** [comment]
There was concern that me launching + attaching could cause some scenarios where optimization might get turned on, which you wouldn't want to code you're debugging. So I was looking at making this switch so that you would launch the process under the debugger rather than attaching after the fact.

That said, I felt like it's _probably_ an edge case, since who is debugging unit tests with a Release build of their test project? Additionally, we stop the test process and wait for the debugger to attach at a very early point in time, before any of the user's unit test classes would've been referenced, so even then the chance that their tests would've already been JITted with optimizations on seems fairly low.

Do you agree with my analysis? If so, then you can consider this feature request pretty low priority; if you think the users are right to be worried about optimizations, then I guess we'll need the ability to launch the process with stdin/stdout redirected.

FWIW, I believe that it shouldn't be a problem for you to override the settings in `LaunchProcessWithDebuggerAttached` (or a hypothetical new API) because you're controlling the `ProcessStartInfo` values here:

https://github.com/microsoft/vstest/blob/dc1e4f67aaa590b3e77588919bf44b775d7d89a6/src/Microsoft.TestPlatform.CrossPlatEngine/Adapter/FrameworkHandle.cs#L87-L93

(I'm assuming whatever closed source debugger APIs you're using wouldn't throw exceptions if those flags were set.)

A new interface + method is probably better than changing the existing method, not only because it would be a behavioral breaking change, it would also be much harder for us to know whether we're running in the context of a "fixed" version of `LaunchProcessWithDebuggerAttached` or not, vs. just testing for `IFrameworkHandle3`.

**Comment by bradwilson** [comment]
Alright, we can close this. Thanks for the feedback. 👍🏼
