### ISSUE TITLE
Unable to specify path to a custom logger on 'dotnet test' command line

### ISSUE THREAD

**Issue by tmat** [Microsoft/vstest#522]
There is no way to specify a full path to a custom logger on command line. Loggers are only discovered from ```sdk\{version}\Extensions``` directory. This makes it cumbersome to use a custom logger from a nuget package.

Proposal:

When the logger name passed to --logger is a path to an existing .dll use that. Otherwise look it up by name in the Extension directory.

```--logger:"C:\users\user\.nuget\packages\mylogger\lib\mylogger.dll";parameters```

**Comment by codito** [comment]
Another option is to look up loggers from nuget packages directly. It is straight forward in case of `netcoreapp` targets since the logger nuget package will be in dependency closure of the test project. For `net45` targets, vstest.console could look up loggers from the test project output directory.

So the nuget package should copy test loggers to output directory on build (similar to adapters).

In case multiple assemblies are passed to vstest.console, e.g. `vstest.console /logger:aLogger c:\tmp\a\a.dll c:\tmp\b\b.dll`, the runner should load loggers from both `c:\tmp\a` and `c:\tmp\b`. However the logger specified in `/logger:`  will be enabled, in this example it will be `aLogger`.

Thoughts?

/cc @pvlakshm @sbaid @blackdwarf @piotrpMSFT

**Comment by tmat** [comment]
Why would the project depend on the logger? That certainly doesn't need to be true.

**Comment by sbaid** [comment]
syntax like this will be good.
```
--logger:appveyor;custom-parameters-for-logger
```
`appveyor` here is the friendly name of the logger. It is specified as a custom attribute on top of custom `ITestLogger` impl. e.g. [TrxLogger](https://github.com/Microsoft/vstest/blob/master/src/Microsoft.TestPlatform.Extensions.TrxLogger/TrxLogger.cs)

There is a need to `acquire` & `load assembly` containing the impl for the custom logger. @tmat do u have a suggestion there? 
@natemcmaster looping in the discussion

**Comment by tmat** [comment]
@sbaid 

```
--logger:"C:\users\user\.nuget\packages\mylogger\lib\mylogger.dll";parameters
```

**Comment by sbaid** [comment]
@tmat 2) it will be long cmdline to type. 2) mylogger.dll may have further package/assembly dependencies

**Comment by sbaid** [comment]
acquisition through nuget of the `extensions` will probably be saner. That way - nuget restore takes care of acquisition. runner takes up loading the right extension.

**Comment by codito** [comment]
In CI machines, specifying an exact path to logger assembly is challenging. This scenario is similar to `-TestAdapterPath` for test adapters; CI tasks ended up writing custom logic to find `TestAdapters` first and then call vstest.console :(

**Comment by tmat** [comment]
@codito I'm actually writing a build script that runs in CI and I don't see any problem in finding the logger.

The toolset packages used by the build are restored by a standalone proj file:

https://github.com/dotnet/symreader-converter/blob/master/build/Toolset.proj#L11

And then referenced like so:
https://github.com/tmat/roslyn-tools/blob/STNuPkg/src/RepoToolset/Build.proj#L40

See NuGetPackageRoot variable is defined like so:
https://github.com/tmat/roslyn-tools/blob/STNuPkg/src/RepoToolset/NuGet.props

**Comment by tmat** [comment]
Perhaps there is a better way to do this but the --logger parameter should just allow me to specify path. If we have some other mechanism that's fine. But the most straightforward way should just work.

**Comment by sbaid** [comment]
@tmat this scenario is that test logger is self contained set of dlls in the same folder & user want to just specify it directly?

**Comment by codito** [comment]
Specifying the path is required for cases where nuget is not supported in project system, e.g. C++ or Javascript. These will soon become mainline scenarios for TPv2. This will show up for other extension types as well: data collector, runtime providers etc., may be we should solve this holistically.

@tmat thanks, the example helps. Glad to know that we already have a xunit xml logger working 👍. Here's the other example that injects all test adapters found in nuget directories (in vstest vso task).
https://github.com/Microsoft/vsts-tasks/blob/44843fdace107f23bb9351c05e0d5789aea3164e/Tasks/VsTest/vstest.ts#L159
https://github.com/Microsoft/vsts-tasks/blob/44843fdace107f23bb9351c05e0d5789aea3164e/Tasks/VsTest/vstest.ts#L824

**Comment by tmat** [comment]
@codito 

>  Glad to know that we already have a xunit xml logger working 

If at all possible I think it would be better if test platform could use the logger already implemented in xunit itself. Would it be possible to pass thru parameters to xunit runner to make it so?

**Comment by natemcmaster** [comment]
> would be better if test platform could use the logger already implemented in xunit 

+1. Xunit already has loggers for TeamCity, AppVeyor, HTML, and others. Would be nice we could use them from dotnet-test. cref https://github.com/Microsoft/vstest/issues/254.

**Comment by codito** [comment]
> If at all possible I think it would be better if test platform could use the logger already implemented in xunit itself. Would it be possible to pass thru parameters to xunit runner to make it so?

Yes, it should be possible. `dotnet test -- xunit.xml=c:\tmp\foo.xml xunit.key=value` will pass the path as a setting (in `RunSettings`) to xunit adapter.

**Comment by Faizan2304** [comment]
An xunit logger is available at https://www.nuget.org/packages/XunitXml.TestLogger. Source code is available [here](https://github.com/Faizan2304/LoggerExtensions).

With `15.0-rtm` builds, user can specify logger with `dotnet test -a:. -l:<loggername>` to run tests with reporting. We've removed the need to specify `-a:.` in `15.1+`.

**Comment by maciejw** [comment]
OMG I'll add this info here, in case someone in on a verge of nervous breakdown and is looking for this info like me:)

if you have a custom logger and you want to use friendlyName, or url to specify logger you want to use, you have to put your logger in assembly that ends with ```.TestLogger.dll``` for example ```my.TestLogger.dll``` without it you have to use I think setting file and specify CodeBase and AssemblyQualifiedName to load your logger.

**Comment by nohwnd** [comment]
Yup it's also in the docs: 


https://github.com/Microsoft/vstest-docs/blob/master/docs/report.md#create-a-test-logger 


## Create a test logger
Go through the following steps to create your own logger
1) Add a nuget reference of package `Microsoft.TestPlatform.ObjectModel`.
2) Implement ITestLoggerWithParameters (or ITestLogger, if your logger is not expecting any parameter). [Logger Example](https://github.com/spekt/xunit.testlogger/blob/master/src/Xunit.Xml.TestLogger/XunitXmlTestLogger.cs#L19)
3) Name your logger assemlby `*.testlogger.dll`. [Detailed](https://github.com/Microsoft/vstest-docs/blob/master/docs/report.md#naming)

**Comment by voroninp** [comment]
>  dotnet test -t -logger:.\tools\Json.TestLogger\published\Json.TestLogger.dll .\MediaFlowService.sln
MSBUILD : error MSB1020: The logger was not found. Check the following: 
1.) The logger name specified is the same as the name of the logger class.
2.) The logger class is "public" and implements the **Microsoft.Build.Framework.ILogger** interface.
3.) The path to the logger assembly is correct, or the logger can be loaded using only the assembly name provided.
Switch: .\tools\Json.TestLogger\published\Json.TestLogger.dll

- Docs say nothing about which .NET I should target. 
- Why `Еhe logger name specified is the same as the name of the logger class.` ?
- Why `Microsoft.Build.Framework.ILogger` ?

Code of the logger:
```
using System.Text.Json;
using Microsoft.VisualStudio.TestPlatform.ObjectModel;
using Microsoft.VisualStudio.TestPlatform.ObjectModel.Client;

namespace Json.TestLogger;

public sealed class JsonTestLogger : ITestLogger
{
    private readonly List<TestCase> _discoveredTestCases = new List<TestCase>();

    public void Initialize(TestLoggerEvents events, string testRunDirectory)
    {
        events.DiscoveredTests += DiscoveredTests;
        events.DiscoveryComplete += TestsDiscoveryCompleted;
    }

    private void TestsDiscoveryCompleted(object? sender, DiscoveryCompleteEventArgs e)
    {
        var jsonStr = JsonSerializer.Serialize(_discoveredTestCases, new JsonSerializerOptions
        {
            WriteIndented = true,
        });

        Console.WriteLine(jsonStr);
    }

    private void DiscoveredTests(object? sender, DiscoveredTestsEventArgs e)
    {
        _discoveredTestCases.AddRange(e.DiscoveredTestCases ?? Array.Empty<TestCase>());
    }
}
```

**Comment by voroninp** [comment]
What am I doing wrong here?

```
 dotnet test -t -l:.\tools\Json.TestLogger\published\Json.TestLogger.dll .\MediaFlowService.sln
```
> Could not find a test logger with AssemblyQualifiedName, URI or FriendlyName '.\tools\Json.TestLogger\published\Json.TestLogger.dll'.
