### ISSUE TITLE
VSTest reporting Inconclusive as Error

### ISSUE THREAD

**Issue by nigurr** [Microsoft/vstest#525]
Please refer this issue for more details:
https://github.com/nunit/nunit3-vs-adapter/issues/219
https://github.com/Microsoft/vsts-tasks/issues/3024

**Comment by nigurr** [comment]
@pvlakshm

**Comment by AbhitejJohn** [comment]
We made a change in the trx logger to fix this post VS 2017 RTM. These tests should start showing up as "Not Executed" with the ability to see any diagnostic messages in the trx viewer in VS.

**Comment by ekumlin** [comment]
@AbhitejJohn What version is this fix in? This is considered a blocking issue for our team.

As of *15.0.0+26228.10*, I still get `Message: Assert.Inconclusive failed.`.

**Comment by AbhitejJohn** [comment]
@ekumlin : This is currently flowing out post the 15.1/15.2 release trains. 
/cc: @sbaid, @pvlakshm on the blocking part.

**Comment by tomkerkhove** [comment]
@AbhitejJohn Thanks for the update, what's the ETA for that?

**Comment by strangesource** [comment]
Any news on this? We would need this ASAP.

**Comment by ekumlin** [comment]
Additional info: Interestingly, doing `Assert.Inconclusive` in a `[ClassInitialize]` method produces the desired results. In a `[TestMethod]` method, it fails the test.

**Comment by AbhitejJohn** [comment]
This should be available in the preview builds of 15.3. 
@ekumlin : I cannot repro that on my end. Can you please file an issue with a repro at https://github.com/Microsoft/testfx/issues

**Comment by tomkerkhove** [comment]
Is this available on VSTS then already?

**Comment by AbhitejJohn** [comment]
@tomkerkhove: I guess you are referring to VSTS Hosted agents, which should have it when 15.3 goes RTM.

**Comment by tomkerkhove** [comment]
@AbhitejJohn Thank you, we'll wait for that then

**Comment by abatishchev** [comment]
What is the current status? Inconclusive tests fail build while they shouldn't (in my opinion, the classic behavior).

**Comment by jakobehn** [comment]
Installing VS2017 15.3+ solves this problem. Now the explicit tests are marked as "Others", the pass percentage still reflects that not all tests were executed.

![image](https://user-images.githubusercontent.com/847244/30804254-fe2b1792-a1ec-11e7-8dfc-7ba33351a149.png)
