### ISSUE TITLE
Spam in the issues

### ISSUE THREAD

**Issue by Eric1243123** [microsoft/vstest#5263]
_from @nohwnd _

Commenting here, because I asked github team to delete all issues starting since the spam storm started last week. 

# ℹ️  Sorry about the spam. 

Sorry about the spam, I notified github team that we are being targetted, I've set interaction limits to hopefully avoid further spam until this is resolved.

---

## Description

As I'm sure y'all have seen, a lot of spam advertisements for livesteams are all over the issues, and it makes it hard to find real comments. Along with this, it blows up the email of those subscribed with a bunch of this spam

## Expected behavior

I don't expect this spam to be here

## Actual behavior

![image](https://github.com/user-attachments/assets/6962c945-0943-4b4c-8153-ea093b7f8513)

**Comment by Raseliqbal100** [comment]
trysiucs

**Comment by nohwnd** [comment]
Thanks, I am trying to find a way to block them automatically. I've removed tens of them in the last few days already, but there are more and more coming every day.

**Comment by filzrev** [comment]
What's about temporary enabling [`Temporary interaction limits`](https://docs.github.com/en/communities/moderating-comments-and-conversations/limiting-interactions-in-your-repository) settings.

If enabling `Limit to existing users` setting.
Almost of spam issue/comment can not be posted. 

> Limit to existing users:
> Limits activity for users with accounts that are less than 24 hours old who do not have prior contributions and are not collaborators

**Comment by nohwnd** [comment]
We are fighting this as hard as we can.

**Comment by nohwnd** [comment]
Thanks for the tips.
