### ISSUE TITLE
Run vstest.console without args should print help

### ISSUE THREAD

**Issue by codito** [Microsoft/vstest#53]
## Description

VSTest runner does not print help message when run without any arguments.
## Steps to reproduce

Run `vstest.console.exe` without any args
## Expected behavior

A help message is shown.
## Actual behavior

Just copyright message is shown and the runner exits.
## Environment

vstest.console.exe version from 53689b0 commit.

**Comment by pvlakshm** [comment]
Fixed with PR [#1110](https://github.com/Microsoft/vstest/pull/1110).
