### ISSUE TITLE
TestExplorer GUI shows incomplete progress bar when test run is Cancelled midway

### ISSUE THREAD

**Issue by jayaranigarg** [Microsoft/vstest#546]
## Description
If a solution has large number of tests and we do a Cancel right after doing RunAll, then GUI shows an incomplete progress bar.

## Steps to reproduce
1.	Build -> Build solution
2.	Test Explorer -> Run All
3.	Click “Cancel” right away. Usually a few tests run quickly. When clicking “cancel”, test explorer GUI will still show an incomplete progress bar.

**Comment by snkota** [comment]
This is being tracked external to this repo here:
https://developercommunity.visualstudio.com/content/problem/145935/testexplorer-gui-shows-incomplete-progress-bar-whe.html
