### ISSUE TITLE
Providing an in-proc VsTestConsole

### ISSUE THREAD

**Issue by genlu** [Microsoft/vstest#559]
Currently to consume the results of test discovery/execution from test platform, user can use `VsTestConsoleWrapper`. However, this still ends up launching a separate vstest.console process, which in turns launches testhost process. The overhead on serializing test objects between those three processes is quite high. 

As a starter, maybe we can make an in-proc version of vstest.console, which hopefully can get rid of up to 50% of effort on serialization.

**Comment by codito** [comment]
The objects are not serialized/deserialized across three processes. They are serialized once in `testhost`, just passed-thru `vstest.console` as it is to the `VstestConsoleWrapper` where they are deserialized once.

**Comment by genlu** [comment]
Ah, I see. I had assumed vstest.console was doing that based on the fact that you can use vstest.console to run test in commandline. Do you guys have numbers on perf tests for test platform? Especially the overhead on communication. If not, I'd be happy to run some quick tests myself. My gut feeling is making vstest.console in-proc might be the simplest change we can make to get some noticeable improvement on perf.

**Comment by snkota** [comment]
This is being tracked external to this repo here:
https://developercommunity.visualstudio.com/content/problem/145943/providing-an-in-proc-vstestconsole.html

**Comment by KevinH-MS** [comment]
@pvlakshm can we re-activate this?  This is test platform, so I think the issue belongs here rather than VS feedback.
