### ISSUE TITLE
Test discovery is SLOW

### ISSUE THREAD

**Issue by davidfowl** [Microsoft/vstest#560]
## Description
Test discovery in VS2017 in very slow for large solutions

## Steps to reproduce

```
git clone https://github.com/dotnet/corefxlab
```
build it in visual studio and wait for it to discover tests

## Expected behavior
Test discovered in less than 2 minutes

## Actual behavior
Test discovered in > 2 minutes

## Environment
VS2017 RC4 xunit tests

**Comment by davkean** [comment]
@codito are there plans to make inroads on this? From my own project (http://github.com/dotnet/roslyn-project-system) - it's takes VS a long time to discover tests, and then after I click Run All - it takes >52 seconds to run the tests. If I do it via command-line, my entire test time is 16 seconds, that means it's 325% slower to inside VS than via the command-line.

**Comment by NickCraver** [comment]
I'm seeing this on very small projects as well, things with only a few thousand lines of code and under a dozen *very* small projects...only one or two of which are test projects.

Also, why do we have to build again after just building to discover tests? Hitting build on the solution, clicking run, then building again is crazy to me. How can we help?

**Comment by mattzink** [comment]
@davkean @NickCraver I was just about to submit a related bug, where if either the `<OutputPath>` or `<OutDir>` msbuild properties are changed from the default, discovery times in both CLI and VS goes from a few seconds to several minutes for us. Just mentioning this in case this is what you are running into.

**Comment by Faizan2304** [comment]
@NickCraver : 
>Also, why do we have to build again after just building to discover tests? Hitting build on the solution, clicking run, then building again is crazy to me. How can we help?

This may help to get you answer. https://github.com/Microsoft/vstest/issues/696#issuecomment-292431981

**Comment by snkota** [comment]
This is being tracked external to this repo here:
https://developercommunity.visualstudio.com/content/problem/145942/test-discovery-is-slow.html
