### ISSUE TITLE
Code coverage on .NET Core

### ISSUE THREAD

**Issue by twsouthwick** [Microsoft/vstest#579]
## Description
Code coverage does not work in .NET Core

## Steps to reproduce
Run `vstest.console.exe /enablecodecoverage /framework:netcoreapp`

## Expected behavior
Runs the tests with code coverage enabled on .NET Core

## Actual behavior
```
Error: Invalid .Net Framework version:netcoreapp11. Supported .Net Framework versions are Framework35, Framework40 and Framework45.
```

## Environment
VS 2017 RTM
Windows 10 14393.693

**Comment by smadala** [comment]
Code coverage support not available in 15.0.0. [Doc](https://github.com/Microsoft/vstest-docs/blob/595365bea52c00c4843f589d987f4a194d7a5efc/docs/analyze.md).

Please use /Framework:FrameworkCore10 for .Net core apps.

**Comment by smadala** [comment]
Error message should display as follows:
`Error: Invalid .Net Framework version:netcoreapp11. Supported .Net Framework versions are Framework35, Framework40, Framework45 and FrameworkCore10.`

**Comment by twsouthwick** [comment]
What is the timeline to support .NET Core

**Comment by codito** [comment]
@twsouthwick this will likely come in the next release (15.1 or 15.2 preview). We're still working out the details. Current thought process:
* In console, code coverage will show up as a data collector (spec is [here](https://github.com/Microsoft/vstest-docs/blob/master/docs/analyze.md)). User may install the code coverage nuget package, and use it like `dotnet test --collect:coverage`
* In VS, it will show up as the existing `Analyze Code Coverage` in test explorer

We're first enabling the infrastructure (data collectors), this will allow the community to author code coverage extensions for dotnet test. VS code coverage support will use the same infra.

**Comment by robalexclark** [comment]
I was struggling with this, but found Microsoft.CodeCoverage started working when I added <debugtype>Full/> to the project containing the assembly to have coverage:

I'm using Microsoft.CodeCoverage 1.0.2, xunit 2.2.0, Ms.Test.sdk 15.0. The project under test is .net framework 4.5.1 and uses nuget packages for .net core 1.1.1 throughout

Can someone else please check and confirm?
 
  <PropertyGroup>
    <TargetFramework>net452</TargetFramework>
    <RuntimeIdentifier>win7-x86</RuntimeIdentifier>
    <PreserveCompilationContext>true</PreserveCompilationContext>
    <AssemblyName>ExtranetManager</AssemblyName>
    <OutputType>Exe</OutputType>
    <DebugType>Full</DebugType>
    <PackageId>ExtranetManager</PackageId>
  </PropertyGroup>

**Comment by twsouthwick** [comment]
@robalexclark your test is running on .NET Framework which is supported at the moment. The `debugtype` had to be changed because by default it builds with the new portable format, which is currently unsupported with vstest. If you switched your test to run as a .netcoreapp you won't see any coverage results.

> uses nuget packages for .net core 1.1.1 throughout

This is probably not what you think it means. The nuget packages may support .NET Core 1.1.1, but are either targeting .NET Standard or have a .NET Framework version. These are then being selected when running on .NET Framework. The goal of .NET Standard is to allow the same binary to run on multiple runtimes (.NET Core and .NET Framework are two distinct runtimes).

If the project is one you can share, we can verify if this is the case based on the project files and packages.

**Comment by robalexclark** [comment]
Apologies yes you are right - I am running on .net 4.5.1 as runtime.

**Comment by twsouthwick** [comment]
Easy mistake to make in some projects!

**Comment by baor** [comment]
Hi all! 
Do you have any plans about implementation code coverage for dotNetCore for Linux?

If you have any PR or subtasks, I am ready to help.

**Comment by nperno** [comment]
@codito I would like to try out the "dotnet test --collect:coverage" for my dotnet core VSTS builds. Do you have any insight/guidance as to when that will be available and we will need to do to get it working? 

Thanks for your help!

**Comment by markvincze** [comment]
Hi all,

Is there any update on whether there will be .NET Core code coverage support for Linux too?

Thanks,
Mark

**Comment by HaroonSaid** [comment]
Any update - VS 2017 is expensive product one of key features is code coverage

**Comment by raffaeu** [comment]
Guys just yesterday I found a new Nuget Package:
**Microsoft.CodeCoverage** version **1.0.3**

I updated the package into my XUnit test project and run Tests + Code Coverage in VS 2017 Ultimate.
The tests are executed but the **Code Coverage** is not even triggered:

![image](https://cloud.githubusercontent.com/assets/1304736/25738046/3be2f696-317b-11e7-826d-ffb22c0a9b60.png)

So, what's going on? Any official Docs yet?

**Comment by raffaeu** [comment]
Also if I pass `dotnet test --collect:coverage`

This is what we get **NOT IMPLEMENTED** 

```
MSBUILD : error MSB1001: Unknown switch.
Switch: --collect:coverage
For switch syntax, type "MSBuild /help"
Process completed with exit code 1.
```

**Comment by codito** [comment]
This feature hasn't shipped yet. We're pretty close though, will provide an update soon :)

**Comment by codito** [comment]
In `15.3 Preview 1`, code coverage for .NET core is available in VS. Instructions are here: https://github.com/Microsoft/vstest-docs/blob/master/docs/analyze.md#coverage. Please try it out.

We're working on bringing coverage to `dotnet test` command line.

**Comment by raffaeu** [comment]
@codito we just tried with these versions:

- Visual Studio 2017 15.2
- xunit  2.2.0
- Microsoft.NET.Test.Sdk" Version="15.3.0-preview-20170502-03"

Tests run and they are green but Code Coverage is not triggered.
Is it working only with MsTest? I hope we don't have to re-write all our tests 😢

**Comment by codito** [comment]
@raffaeu it is available in `VS 2017 15.3 preview 1`, you can get the build from https://www.visualstudio.com/vs/preview/. It works with all frameworks :)

**Comment by raffaeu** [comment]
Oh, thanks I will try then with the *preview* version
Thank you

**Comment by codito** [comment]
Currently known issues are tracked here: https://github.com/Microsoft/vstest/labels/exp%3A%20coverage

**Comment by cdie** [comment]
Hey, finally, great !
Nice to have it again with preview version. And I should also notice that this preview version (15.3) seems to works better than currently supported one (15.2) ...
Can't wait to use it every day

**Comment by twgraham** [comment]
@codito presumably the `dotnet test` version of the coverage runner you speak won't be the same as that vstest uses right? When you say something like that I get hopeful for those like me on mac/linux. Is there seperate issues for the `dotnet test` coverage support?

**Comment by codito** [comment]
@twgraham test code coverage is VS enterprise and windows only so far, current plan is to get the same level of support in `dotnet test` (windows + VS enterprise). Mac/linux support isn't in our immediate backlog. /cc @pvlakshm @sbaid to consider the feedback for prioritization.

**Comment by aKabirKhan** [comment]
Any update on this? we need test coverage to work in .net core application, stranded a bit. I installed the Visual Studio 2017 version 15.3 preview in the hopes of this getting done but still code coverage is missing. When I run my unit tests code coverage result comes back empty wtih message: "Empty results generated: No binaries were instrumented....". I know that this is in progress but will code coverage be part of 15.3?

**Comment by npasqua** [comment]
@codito Furthermore, is it the plan to include support of `dotnet test` code coverage in 15.3 / 2.0 initial versions or should I be exploring other avenues for the time being? If not the previous versions, is there a proposed time/release for this behavior? (so I may explain to others the decision to use 3rd party tools instead of wait for official MSFT tools)

**Comment by amattie** [comment]
@codito Do you have high-level timing you can share for when `dotnet test` with code coverage will be cross-platform? Q3? Q4? 2018? It'd be nice to know just for planning purposes.

**Comment by Alxandr** [comment]
I tried out `dotnet test --collect:coverage` on .NET CLI `2.1.0-preview1-006547`, and this is what I got:

`dotnet exec needs a managed .dll or .exe extension. The application specified was 'C:\Program'`

Seems someone needs to quote a path somewhere :P

**Comment by harshjain2** [comment]
Hi @Alxandr 
I tried to repro this using .NET CLI `2.1.0-preview1-006567`. It seems to be working as expected for me.

![image](https://user-images.githubusercontent.com/13763032/27517981-64140448-598a-11e7-99d5-c792504b0ff8.png)

![image](https://user-images.githubusercontent.com/13763032/27517982-7a2ccde6-598a-11e7-83bf-1f40a7fb21b6.png)

If it is a consistent repro, please share repro steps so that we can look into the issue.

**Comment by Alxandr** [comment]
Huh. That's weird. I'll try to do some more testing with it.

**Comment by dnelly** [comment]
I'm getting a similar error that that's giving me an object reference not set to an instance of an object.

     1>Done building target "ShowCallOfVSTestTaskWithParameter" in project "UnitTestProject1.csproj".
       Done executing task "CallTarget".
       Using "Microsoft.TestPlatform.Build.Tasks.VSTestTask" task from assembly "C:\Program Files\dotnet\sdk\2.0.0-preview1-005977\Microsoft.TestPlatform.Build.dll".
       Task "Microsoft.TestPlatform.Build.Tasks.VSTestTask"
Object reference not set to an instance of an object.
Object reference not set to an instance of an object.

       Done executing task "Microsoft.TestPlatform.Build.Tasks.VSTestTask" -- FAILED.
     1>Done building target "VSTest" in project "UnitTestProject1.csproj" -- FAILED.
     1>Done Building Project "C:\code\bitbucket\CITestProject\UnitTestProject1\UnitTestProject1.csproj" (VSTest target(s)) -- FAILED.

**Comment by harshjain2** [comment]
@dnelly Please consider upgrading to latest version of CLI.
@Alxandr also faced similar issues in `2.1.0-preview1-006547` which are not there in `2.1.0-preview1-006567`.
Do let us know if you face these issues even after upgrading to latest version.

**Comment by Alxandr** [comment]
Stil lsame error.

![image](https://user-images.githubusercontent.com/112334/27686821-af5112d2-5cd4-11e7-8259-6642e535370e.png)

**Comment by dnelly** [comment]
@harshjain2 Yeah, it was still the same for me as well. 

Here's the current version 2.0.0-preview2-006497

**Comment by dnelly** [comment]
the error seems to come from this Test Execution Command Line Tool Version 15.3.0-dev

**Comment by harshjain2** [comment]
@dnelly @Alxandr Created an issue https://github.com/Microsoft/vstest/issues/902 for investigating this further.

**Comment by dnelly** [comment]
Thank you!

**Comment by mstephens-adig** [comment]
Is there a way to get the code coverage flags to work on VSTS?  The best I can tell VSTS only has 15.0 available and not any of the pre-releases.
Everything works fantastic locally. Thanks for all the hard work!

**Comment by harshjain2** [comment]
Created a separate issue for providing support for dotnet test --collect:"Code Coverage" https://github.com/Microsoft/vstest/issues/981 as this issue is for code coverage support for `vstest.console.exe`

**Comment by Mardoxx** [comment]
Still doesn't work in VS2017 15.3. My coverage only shows for my test library, coverage for the tested library is not shown.

**Comment by harshjain2** [comment]
@mstephens-adig VS 2017 15.3 is released now.  
https://blogs.msdn.microsoft.com/visualstudio/2017/08/14/visual-studio-2017-version-15-3-released/ 
Upgrading to latest released version in VSTS should solve your problem.

**Comment by bdominguez** [comment]
@harshjain2 it's still happening on my end with 15.3.

**Comment by harshjain2** [comment]
@Mardoxx Thanks for trying it out. This workaround is required for code coverage to work on .NET Core

**Comment by harshjain2** [comment]
Please try code coverage and let us know if there is any feedback/issues.
I am closing this issue for now.

**Comment by cdie** [comment]
@harshjain2 Is the nuget package a temporary workaround or a permanent one, aka I don't want to spent a lot of time adding it now to remove it in two months

**Comment by cdie** [comment]
It seems it's not working with .NET Core 2.0 ?
Or maybe it's with xunit 2.2.0 ?

**Comment by IvanAlekseev** [comment]
Coverage is still not working in VSTS, at least I can get the test results
https://github.com/Microsoft/vsts-tasks/issues/5066

**Comment by Mardoxx** [comment]
I would imagine this is because your agent is not up to date. Check what version of VS2017 your agent is using. Any >15.3 should work.

**Comment by IvanAlekseev** [comment]
@Mardoxx It is Hosted VS 2017, they updated to 15.3 recently

**Comment by Mardoxx** [comment]
Ah! Now I look, mine don't have coverage either!

**Comment by harshjain2** [comment]
>@harshjain2 Is the nuget package a temporary workaround or a permanent one ? I mean I don't want to spent a lot of time adding it now to remove it in two months...
We are tracking the issue to remove need to manually add nuget package here. 
https://github.com/Microsoft/vstest/issues/852. 
We will prioritize it soon.

**Comment by a0z0ra** [comment]
Hi, we followed all above, and still no luck.  Found different paths from log: 

2017-08-24T22:58:11.1157918Z Attachments:
2017-08-24T22:58:11.1157918Z   d:\a\1\s\TestResults\**672524f6-3c0c-4dc4-86c9-4b58f01c9577\buildguest_FACTORYVM-AZ220 2017-08-24 22_58_06.coverage**
2017-08-24T22:58:11.1157918Z 
2017-08-24T22:58:11.1157918Z Total tests: 1. Passed: 1. Failed: 0. Skipped: 0.
2017-08-24T22:58:11.1157918Z Test Run Successful.
2017-08-24T22:58:11.1167892Z Test execution time: 4.6567 Seconds
2017-08-24T22:58:11.1508492Z Results File: d:\a\1\s\TestResults\buildguest_FACTORYVM-AZ220_2017-08-24_22_58_11.trx
2017-08-24T22:58:13.3673473Z ##[section]Async Command Start: Telemetry
2017-08-24T22:58:13.3673473Z ##[section]Async Command End: Telemetry
2017-08-24T22:58:13.3673473Z ##[section]Async Command Start: Telemetry
2017-08-24T22:58:13.3673473Z ##[section]Async Command End: Telemetry
2017-08-24T22:58:13.3673473Z ##[section]Async Command Start: Telemetry
2017-08-24T22:58:13.3673473Z ##[section]Async Command End: Telemetry
2017-08-24T22:58:13.3673473Z ##[section]Async Command Start: Telemetry
2017-08-24T22:58:13.3673473Z ##[section]Async Command End: Telemetry
2017-08-24T22:58:13.3673473Z ##[section]Async Command Start: Publish test results
2017-08-24T22:58:13.8241527Z Publishing test results to test run '59'
2017-08-24T22:58:13.8241527Z Test results remaining: 1. Test run id: 59
2017-08-24T22:58:14.1399971Z ##[warning]Skipping attachment as it exceeded the maximum allowed size or not available on disk: d:\a\1\s\TestResults\**buildguest_FACTORYVM-AZ220_2017-08-24_22_58_11\In\FACTORYVM-AZ220\buildguest_FACTORYVM-AZ220 2017-08-24 22_58_06.coverage**

Could this be the case why codecoverage not published?

Also, once it's published, should it be visible under Code Coverage?

**Comment by harshjain2** [comment]
CC @nigurr for vstest-task

**Comment by nigurr** [comment]
Hi,

We are fixing this issue as part of this https://github.com/Microsoft/vsts-agent/pull/1149/files
Will update the thread once we release the fix. 

Sorry for the trouble.

**Comment by xperiandri** [comment]
https://developercommunity.visualstudio.com/comments/84459/view.html

**Comment by Oceanswave** [comment]
Getting similar results as folks above

<PackageReference Include="Microsoft.CodeCoverage" Version="1.0.3" />

is referenced in my test project.

```
dotnet test --collect:coverage
```

```
Microsoft (R) Test Execution Command Line Tool Version 15.3.0-preview-20170628-02
Copyright (c) Microsoft Corporation.  All rights reserved.

Starting test execution, please wait...
dotnet exec needs a managed .dll or .exe extension. The application specified was 'C:\Program'

Object reference not set to an instance of an object.
Object reference not set to an instance of an object.
```

**Comment by davidreher** [comment]
even if I use vstest.console.exe like described in https://github.com/Microsoft/vstest-docs/blob/master/docs/analyze.md#coverage like this:
```
vstest.console.exe --collect:"Code Coverage" --framework:".NETCoreApp,Version=v2.0" bin\Debug\netcoreapp2.0\some.tests.dll
```

I am getting:
```
Microsoft (R) Test Execution Command Line Tool Version 15.0.26929.2
Copyright (c) Microsoft Corporation.  All rights reserved.

Error: The test source file "--collect:Code Coverage" provided was not found.
Error: The test source file "--framework:.NETCoreApp,Version=v2.0" provided was not found.
```
I am running VS2017 Enterprise V15.4.1

**Comment by davidreher** [comment]
@sbaid: Thank you so much, this works now :)

**Comment by davidreher** [comment]
Is there a way to pass the `--collect:"Code Coverage"` switch to `dotnet vstest` instead of using `vstest.console.exe`?

**Comment by mundhras** [comment]
I get the below error. Has any one see/resolved this.

Test run will use DLL(s) built for framework NETCoreApp,Version=v2.0 and platform X86. Following DLL(s) do not match framework/platform settings.
<Assemble>.Test.dll is built for Framework 2.0 and Platform X86.

C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\Common7\IDE\Extensions\TestPlatform\vstest.console.exe" F:\Vsts\agent-1\_work\14\a\Release\Deploy\Publications\<folder>\<asembly>.Test.dll /EnableCodeCoverage /logger:trx "/TestAdapterPath:\"F:\Vsts\agent-1\_work\14\a\"" /Framework:NETCoreApp,Version=v2.0 /logger:console;verbosity=normal

**Comment by BlitzkriegSoftware** [comment]
This is still an issue for XUnit on .NET Core 2.0 projects. Why is this closed?

**Comment by IvanAlekseev** [comment]
Thats the latest update from Microsoft I believe - https://github.com/Microsoft/vstest-docs/blob/master/RFCs/0021-CodeCoverageForNetCore.md

**Comment by swati-jain13** [comment]
Is there a solution available now for dotnet test --collect:Code Coverage for linux containers?
