### ISSUE TITLE
Code coverage does not include main module (VS 2017 RTM)

### ISSUE THREAD

**Issue by ekumlin** [Microsoft/vstest#587]
## Description
When using migrated `net452` projects which were built using `xproj` (in VS 2015), all `*.coverage` files produced by VS 2017 are missing the main library module. They include only test modules.

This is observed with both of these methods:
- *Analyze Code Coverage for Selected Tests* when selecting tests in `MyTest.dll`
- `vstest.console.exe "C:\path\to\MyTest.dll" /EnableCodeCoverage /UseVsixExtensions:true /logger:trx /Settings:"TestSettingsX64.runsettings"`

**This is a regression. This behavior worked in VS 2015 with `xproj` by executing `vstest.console.exe` against `project.json`, or by using the IDE's Test Explorer.**

## Steps to reproduce
A project created using the steps below is available from [this link](https://drive.google.com/open?id=0B8JHaidj6UhEVUJZdmNnVWUtb0E).

1. Create new **Class Library (.NET Core)**.
1. Add a new static method to `Class1` that can be called from an external module.
1. Right-click the solution and add a new **Unit Test Project (.NET Core)** project to it.
1. Right-click the unit test project and add the library as a reference.
1. Add an assertion test to the unit test project.
1. Update both `csproj` target frameworks to `net452`.
1. Build the solution.
1. Execute tests with code coverage, through the IDE or command line:
    `vstest.console.exe "C:\path\to\bin\Debug\net452\MyTest.dll" /EnableCodeCoverage /UseVsixExtensions:true /logger:trx`

This is the output I got when running the above command, which looks valid.

	Microsoft (R) Test Execution Command Line Tool Version 15.0.26228.0
	Copyright (c) Microsoft Corporation.  All rights reserved.

	Starting test execution, please wait...
	Warning: Using Isolation mode to run the tests as diagnostic data adapters were enabled in the runsettings. Use the /inIsolation parameter to suppress this warning.
	Passed   TestMethod1
	Results File: C:\...\TestResults\erickum_DESKTOP-QSAGH1O 2017-03-09 14_01_11.trx

	Attachments:
	  C:\...\TestResults\a51cb48f-2e15-4952-9495-787d15e36f36\erickum_DESKTOP-QSAGH1O 2017-03-09 14_01_07.coverage

	Total tests: 1. Passed: 1. Failed: 0. Skipped: 0.
	Test Run Successful.
	Test execution time: 3.5669 Seconds

I have also tried adding `netstandard1.6` and `netcoreapp1.1` to the library and test modules, respectively, but when running these tests I just get `No test is available in C:\...\bin\Debug\netcoreapp1.1\MyTest.dll`. (But that's a bug for another thread.)

And I have also tried explicitly including the main module via the `runsettings` file. This has no effect except excluding the test module.

Also, I have see #579 and tried `/Framework:FrameworkCore10`, but this has no effect.

## Expected behavior
I would expect the code coverage file to contain results for the main module (`MyLibrary.dll`). If it contained both the main module and test module, that would be fine, as I can exclude the test module through `runsettings`.

## Actual behavior
![Observed code coverage results](https://cloud.githubusercontent.com/assets/1350074/23773066/77b2e878-04d2-11e7-8328-3161a5fc6d4e.png)

## Environment
- Windows 10 (15031 Insider build)
- Visual Studio 2017 RTM 15.0.0-RTW+26228.4
- `vstest.console.exe` 15.0.26228.0

**Comment by harshjain2** [comment]
@ekumlin This is known issue (https://github.com/Microsoft/vstest/issues/373).
As a workaround, you can add following property group to your product code (mylibrary.csproj in sample shared by you)

```
<PropertyGroup>
    <DebugType Condition="'$(TargetFramework)' != '' AND !$(TargetFramework.StartsWith('netcoreapp'))">Full</DebugType>
</PropertyGroup>
```

**Comment by ekumlin** [comment]
@harshjain2 Thank you, that workaround will mitigate the issue for us.
