### ISSUE TITLE
Create Unit Test Context Menu Missing (.net core projects)

### ISSUE THREAD

**Issue by rahulpaw** [Microsoft/vstest#592]
The code editor Context Menu is missing many options including "Create Unit Test" while clicking on a menu.
This a .Net Standard 1.4 Class Library in Visual Studio 2017.

**Comment by oddyseus** [comment]
same problem here. Standard .net solution. Create Test Units context menu is missing

**Comment by vector-man** [comment]
I'm also missing it in my Windows Forms applications.

**Comment by AbhitejJohn** [comment]
@vector-man : That's interesting. Is this community? and what VS build is this on?

**Comment by vector-man** [comment]
@AbhitejJohn It's the RTM build of Visual Studio 2017. Note: I did do an upgrade from RC using the installer. Should I try completely uninstalling and reinstalling from scratch?

**Comment by vector-man** [comment]
@AbhitejJohn It's the RTM build of Visual Studio Community 2017. Note: I did do an upgrade from the final RC using the installer. Should I try completely uninstalling and reinstalling from scratch?

**Comment by AbhitejJohn** [comment]
Yes, Community is the default free version. You can check in Help -> About as well.
Here is the download link: https://www.visualstudio.com/downloads/ for all the VS SKUs. 

That said the 'Create Unit Tests' context menu not appearing in Windows Forms Apps in VS 2017 Community edition is a bug that we are tracking for an upcoming release.

**Comment by leonziegler** [comment]
I experience the same problem with standard .net solution in Vs Professional 2017. Create Test Units context menu is missing.

**Comment by vector-man** [comment]
Yeah, I forgot to mention, it's a problem for all regular .NET projects for me too.

**Comment by codito** [comment]
Thanks for feedback everyone. We've a fix for this issue. It will be part of the next `15.1.x` preview of VS 2017.

**Comment by codito** [comment]
Fix is available for regular .NET projects https://blogs.msdn.microsoft.com/visualstudio/2017/04/05/visual-studio-2017-update/

Keeping this issue open to track Create Unit Test support for .NET core projects.

**Comment by vector-man** [comment]
Time to switch to 2017 then. Thanks :).

**Comment by nancykaystudios** [comment]
I installed the latest update for VS 2017 (Microsoft Visual Studio Community 2017 Version 15.1 (26403.7) Release) and the 'Create Unit Test' menu item is back in the context menu. Thanks!

**Comment by laarmen** [comment]
Any news on the .Net Core/Standard support?

**Comment by markved** [comment]
Is IntelliTest available for .NET core and/or .NET Standard yet? I am using VS Enterprise 2017 and I don't see IntelliTest for .NET core/standard projects. However, I do see it for ASP.NET Web Application targeting .NET normal framework.

**Comment by pvlakshm** [comment]
@markved, create a separate issue for IntelliTest support on .NET Core and/or .NET Standard, please.

**Comment by SteadyMitch** [comment]
Are there plans to support the Create Unit Tests menu option for .NET Core/.NET Standard in the future?  Currently I'm still unable to use this feature against a .NET Core project using Visual Studio 2017 Enterprise

**Comment by pvlakshm** [comment]
Clearing the 'bug' tag - tagging this as an enhancement, since that it what it would be to get this supported for .NET Core projects.

**Comment by snkota** [comment]
This is being tracked external to this repo here:
https://developercommunity.visualstudio.com/content/problem/145930/create-unit-test-context-menu-missing-net-core-pro.html

**Comment by gabriel-society** [comment]
I am using vs2017 version 15.5 and the problem persists with .net core unit test project

**Comment by SteadyMitch** [comment]
@gabriel-society Please click on the link below and vote for the feature.  Microsoft is no longer tracking this issue on GitHub and will not add the feature into Visual Studio until the community has shown interest

https://developercommunity.visualstudio.com/content/problem/145930/create-unit-test-context-menu-missing-net-core-pro.html
