### ISSUE TITLE
Code Coverage does not work in the IDE with netcoreapp1.x projects (VS 2017 RTM)

### ISSUE THREAD

**Issue by ekumlin** [Microsoft/vstest#597]
## Description
A class library and unit test project built on `netcoreapp1.1` will not produce code coverage result files through the IDE. (Unable to test through the console due to #596.)

## Steps to reproduce
The same project can be used as the one from another issue filed, #596. The steps to create it are copied below.

1. Create new **Class Library (.NET Core)**.
1. Add a new static method to `Class1` that can be called from an external module.
1. Right-click the solution and add a new **Unit Test Project (.NET Core)** project to it.
1. Right-click the unit test project and add the library as a reference.
1. Add an assertion test to the unit test project.
1. Build the solution. (The test in your test project should show up in the VS Test Explorer.)

Once you have the project created, do either of the following:

- Right-click the test that appears and click *Analyze Code Coverage for Selected Tests"*
- Go to *Test > Analyze Code Coverage > All Tests*

The same thing happens whether or not Live Unit Testing is running.

## Expected behavior
A code coverage file should be produced and loaded into the Code Coverage Results view.

## Actual behavior
The test runs, but no code coverage is executed.

## Environment
- Windows 10 (15031 Insider build)
- Visual Studio 2017 RTM 15.0.0-RTW+26228.4
- `vstest.console.exe` 15.0.26228.0

**Comment by harshjain2** [comment]
@ekumlin code coverage is currently not implemented for netcore projects. This support requires datacollectors infrastructure (https://github.com/Microsoft/vstest/issues/309). The work is in progress for supporting datacollectors.

**Comment by ekumlin** [comment]
@harshjain2 Thank you for the reference.

The issue #309 was set for a milestone slated to be completed by January 27th. In what release is this issue currently set to be pushed?

**Comment by harshjain2** [comment]
@ekumlin The work on this issue is in progress, it will come as part of post RTW releases.

**Comment by codito** [comment]
This issue is same as https://github.com/Microsoft/vstest/issues/579. Keeping #579 open and closing this as duplicate to help track better.

**Comment by raffaeu** [comment]
Guys it's April 20, any update on this?
How come we can't still have Code Coverage on NET CORE?
