### ISSUE TITLE
dotnet test does not pass additional arguments to xunit

### ISSUE THREAD

**Issue by mishra14** [Microsoft/vstest#599]
Ported from - https://github.com/dotnet/cli/issues/6002

# Steps - 

`dotnet test -- notrait="platform=darwin"`

# Expected - 

`notrait="platform=darwin"` should be passed to xunit.

# Actual - 

`dotnet test` does not seem to be sending this to xunit.

**Comment by smadala** [comment]
Currently new platform doesn't support passing args directly to xunit. From [docs](https://github.com/Microsoft/vstest-docs/blob/master/docs/filter.md), please use `dotnet test --filter platform!=darwin`.

**Comment by codito** [comment]
Closing this issue since the adapter already supports filtering with traits.
