### ISSUE TITLE
vstest console existing with -1073741819

### ISSUE THREAD

**Issue by livarcocc** [Microsoft/vstest#600]
This is happening for the CLI CI for windows x86.

You can see that here: https://ci.dot.net/job/dotnet_cli/job/master/job/debug_windows_nt_x86_prtest/490/console.

**Comment by livarcocc** [comment]
@Faizan2304 @codito can you guys help me out?

**Comment by codito** [comment]
@livarcocc can we try pulling the latest changes from `dotnet-cli/master` into `enable_more_distros` branch and build? /cc @smadala

**Comment by codito** [comment]
The PR https://github.com/dotnet/cli/pull/5990 is green and merged. Closing this issue. It was possibly fixed by the netcoreapp2.0 move :)
