### ISSUE TITLE
TranslationLayer sample project fails to connect to vstest.console

### ISSUE THREAD

**Issue by YuriGuzun** [Microsoft/vstest#602]
## Description
TranslationLayer sample project fails to connect to vstest.console.exe. But it works fine with vstest instance I take from '\src\package\package\bin\Debug\net46\win7-x64\vstest.console.exe'.

## Steps to reproduce
Build and run '/samples/Microsoft.TestPlatform.TranslationLayer.E2ETest' project. It fails for both Release and Debug configurations.

## Expected behavior
It works fine with vstest instance I take from '\src\package\package\bin\Debug\net46\win7-x64\vstest.console.exe'.

## Actual behavior
It fails with following error:
Microsoft.TestPlatform.VsTestConsole.TranslationLayer.TransationLayerException: 'Error connecting to Vstest Command Line'

## Environment
Win10x64. VS2017 Community edition

**Comment by singhsarab** [comment]
Thanks @YuriGuzun. Fixed it with https://github.com/Microsoft/vstest/commit/51a74a639a18a087e0dbd1b139f1d324203d24ee
