### ISSUE TITLE
TypeInitializationException thrown on accessing TestResult.Outcome property when using TranslationLayer nuget package

### ISSUE THREAD

**Issue by YuriGuzun** [Microsoft/vstest#604]
## Description
I have been playing with TranslationLayer nuget package and TranslationLayer.E2ETest sample project as per https://github.com/Microsoft/vstest-docs/blob/master/RFCs/0005-Test-Platform-SDK.md

## Steps to reproduce

1. Download TranslationLayer.E2ETest sample project - https://github.com/Microsoft/vstest/tree/master/samples/Microsoft.TestPlatform.TranslationLayer.E2ETest
2. Install TranslationLayer nuget package from myget feed - https://dotnet.myget.org/F/vstest/api/v3/index.json

## Expected behavior
It should be possible to get test outcome

## Actual behavior
Exception thrown:
   at Microsoft.VisualStudio.TestPlatform.ObjectModel.TestProperty.Register(String id, String label, String category, String description, Type valueType, ValidateValueCallback validateValueCallback, TestPropertyAttributes attributes, Type owner)
   at Microsoft.VisualStudio.TestPlatform.ObjectModel.TestResultProperties..cctor()

## Environment
I'm using vstest.console and sample test project built by TestPlatform solution and latest TranslationLayer nuget package available in myget feed.

**Comment by singhsarab** [comment]
Thanks for reporting the issue @YuriGuzun.
This has been fixed via https://github.com/Microsoft/vstest/commit/2e3da4b3aeaebdf9dd2ace7c2d55413ae4318b2e
