### ISSUE TITLE
dotnet test produces console output that is not in sync with the test execution

### ISSUE THREAD

**Issue by livarcocc** [Microsoft/vstest#612]
> From @ChristophB125 at https://github.com/dotnet/cli/issues/6031

## Steps to reproduce
Have e.g. 3 MsTest tests that write to the Console for logging purposes, which is sometimes essential for understanding failures on build machines. The 2nd test fails and later on we want to see the test log of this test.
[TestMethod]
public void TestMethod1()
{
    Console.WriteLine("TestMethod1");
}
[TestMethod]
public void TestMethod2()
{
    Console.WriteLine("TestMethod2");
    Assert.Fail();
}
[TestMethod]
public void TestMethod3()
{
    Console.WriteLine("TestMethod3");
}

## Expected  behavior
I expect to see the log from the failing test 'TestMethod2' together with its failure in the log so that I know they belong together to enable me understand the failure better and make use of the logging to the Console. It should look as follows (ideally, dotnet test should also log successful tests)
TestMethod1
Passed UnitTestProject3.UnitTest1.TestMethod1
TestMethod2
Failed   UnitTestProject3.UnitTest1.TestMethod2
Error Message:
 Assert.Fail failed.
Stack Trace:
   at UnitTestProject3.UnitTest1.TestMethod2() in E:\VSProjects\UnitTestProject3\UnitTestProject3\UnitTest1.cs:line 19
TestMethod3
Passed UnitTestProject3.UnitTest1.TestMethod3

## Actual behavior
All the logs are at the top and in a more realistic scenario I would not be able to tell what the log output of the failing test was:
TestMethod1
TestMethod2
TestMethod3
Failed   UnitTestProject3.UnitTest1.TestMethod2
Error Message:
 Assert.Fail failed.
Stack Trace:
   at UnitTestProject3.UnitTest1.TestMethod2() in E:\VSProjects\UnitTestProject3\UnitTestProject3\UnitTest1.cs:line 19

## Environment data
.NET Command Line Tools (1.0.1)

Product Information:
 Version:            1.0.1
 Commit SHA-1 hash:  005db40cd1

Runtime Environment:
 OS Name:     Windows
 OS Version:  6.1.7601
 OS Platform: Windows
 RID:         win7-x64
 Base Path:   C:\Program Files\dotnet\sdk\1.0.1

**Comment by codito** [comment]
The `Passed` tests no longer show up in default output. Please see #301 #478 for context. It can be enabled with `--logger:console;verbosity=normal`.

I still think this problem will show up though, the `Console.WriteLine` are directly coming from the stdout of child-process (`testhost`), where as the `Passed`, `Failed` events come asynchronously (from adapter) through message logger. @AbhitejJohn @smadala thoughts?

**Comment by AbhitejJohn** [comment]
So atleast MSTest Adapter listens to all Console.Writeline messages and adds to them to TestResult.Messages [here](https://github.com/Microsoft/testfx/blob/master/src/Adapter/MSTest.CoreAdapter/ObjectModel/UnitTestResult.cs#L147) and from the code [here](https://github.com/Microsoft/vstest/blob/ba594a8f2d461f2e2351a0694b02771cbe367a3e/src/vstest.console/Internal/ConsoleLogger.cs#L232) the console logger seems to be doing the right thing.

**Comment by ChristophB125** [comment]
Thanks for looking into it.
@codito : Running the test using`dotnet test --logger:console;verbosity=normal`does not output passing tests.

**Comment by smadala** [comment]
@ChristophB125 Did you try with `"`, `dotnet test --logger:"console;verbosity=normal"`.

**Comment by ChristophB125** [comment]
@smadala Yes, I actually used quotes the way how you specified it (I accidentally removed them in my last comment)

**Comment by ChristophB125** [comment]
Note that when using XUnit instead of MSTest, the behaviour is the same, if not even worse because the order of the Console output is reversed on Windows and completely random Linux (RHEL7.2)

**Comment by cltshivash** [comment]
Below is the behavior in VS 2017.5 update.

Microsoft (R) Test Execution Command Line Tool Version 15.5.0
Copyright (c) Microsoft Corporation.  All rights reserved.

Starting test execution, please wait...
Passed   TestMethod1
Standard Output Messages:
 TestMethod1

Failed   TestMethod2
Error Message:
 Assert.Fail failed.
Stack Trace:
   at UnitTestProject7.UnitTest1.TestMethod2() in C:\Users\shivash\Documents\Visual Studio 2017\Projects\UnitTestProject7\UnitTestProject7\UnitTest1.cs:line 19

Standard Output Messages:
 TestMethod2

Passed   TestMethod3
Standard Output Messages:
 TestMethod3


Total tests: 3. Passed: 2. Failed: 1. Skipped: 0.
Test Run Failed.
Test execution time: 4.2828 Seconds

**Comment by bergmeister** [comment]
Thanks

**Comment by ashewani** [comment]
Hi Team,

Currently facing the same issue using Microsoft (R) Test Execution Command Line Tool Version 15.7.0.

From the above comment posted by @cltshivash , it seems that it was fixed in 15.5.0 but that;s not the case for 15.7.0, the console is generating the failed logs in a random manner.  Happy to provide more info, is there anything that needs to be done from my side?

Attached are the images for your reference. 

1. The finished message is shown before the passed unit test case.

![Snag_121fe4](https://user-images.githubusercontent.com/37093828/100199320-1f5d5980-2f51-11eb-80a1-97145a31d42f.png)

2. The failed test case name is not shown along with it's status. The same error is shown properly down the line.

![Snag_13c825](https://user-images.githubusercontent.com/37093828/100199494-60556e00-2f51-11eb-9579-58c5369242dc.png)

**Comment by Sanan07** [comment]
@ashewani Please update Test Platform to latest stable16.8.0 version, so you should not see such behavior.

**Comment by ashewani** [comment]
> @ashewani Please update Test Platform to latest stable16.8.0 version, so you should not see such behavior.

Quick question, can that be updated independently? My code is based on .net core 2.1 (VS 2017).

**Comment by Sanan07** [comment]
Yes, you can update it. You can install latest .NET SDK 5.0 and it should be fine.

**Comment by ashewani** [comment]
> Yes, you can update it. You can install latest .NET SDK 5.0 and it should be fine.

Thanks will try it out soon!

**Comment by ashewani** [comment]
@Sanan07 , Tried out with MS Test execution command line tool version 16.8.0 (dotnet sdk 5.0.100), the output is the same, they are still out of sync.

![image](https://user-images.githubusercontent.com/37093828/100306307-35255a00-2ff7-11eb-9e39-4cc463f85335.png)

![image](https://user-images.githubusercontent.com/37093828/100306329-466e6680-2ff7-11eb-9df9-e529b5c1652b.png)

![image](https://user-images.githubusercontent.com/37093828/100306391-67cf5280-2ff7-11eb-9ca9-6f2fcadc9735.png)

Is there anything else that can be done? Or should I log it as a new issue?

**Comment by Sanan07** [comment]
@ashewani Please also try to update Microsoft.NET.Test.Sdk nuget package to latest one and see if it fixes it for you. I tried and got this output : 
![xunit](https://user-images.githubusercontent.com/8465726/100353472-d4921f00-2fee-11eb-986e-e1651e94c5ef.PNG)

It also confusing for me. From my perspective we do not above part of output. Only results where it shows which tests are passed and which are failed.

If it does not fix for you, so please open new issue with description and screenshots.

**Comment by ashewani** [comment]
Thanks @Sanan07 , the latest version of Microsoft.NET.Test.Sdk (v16.8.0) isn't compatible with .net core 2.0 so I had to create a new .net core 2.1 test project with the latest NuGet packages and the result is still the same.

![Snag_9111478](https://user-images.githubusercontent.com/37093828/100402494-86ddeb00-30b0-11eb-8970-0a49df13be57.png)

![Snag_9100cfb](https://user-images.githubusercontent.com/37093828/100402449-60b84b00-30b0-11eb-8012-7d6bf30119e7.png)

I will open a new issue with the descriptions and screenshots.
