### ISSUE TITLE
Running dotnet test on projects that reference Newtonsoft.Json < 9.0.0.0 throws exception

### ISSUE THREAD

**Issue by arkasha** [Microsoft/vstest#613]
## Description
Running dotnet test on projects that reference Newtonsoft.Json < 9.0.0.0 causes test to throw exception.

## Steps to reproduce
Create a library project targetting .NET 4.5:
```xml
<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net45</TargetFramework>
    <OutputType>Library</OutputType>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Newtonsoft.Json" Version="6.0.5" />
  </ItemGroup>
</Project>
```

Create unit test project referencing the library project and mstest:
```xml
<?xml version="1.0" encoding="utf-8"?>
<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net45</TargetFramework>
    <OutputType>Library</OutputType>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="MSTest.TestFramework" version="1.1.13" />
    <PackageReference Include="MSTest.TestAdapter" version="1.1.13" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="Library.csproj" />
  </ItemGroup>
</Project>
```

Execute `dotnet test Library.Test.csproj`

## Expected behavior
> Test run succeeds

## Actual behavior
Test run fails with the following exception:
Error Message:
>Test method Foo threw exception:
System.IO.FileNotFoundException: Could not load file or assembly 'Newtonsoft.Json, Version=9.0.0.0, Culture=neutral, PublicKeyToken=30ad4fe6b2a6aeed' or one of its dependencies. The system cannot find the file specified. ---> System.IO.FileNotFoundException: Could not load file or assembly 'Newtonsoft.Json, Version=6.0.0.0, Culture=neutral, PublicKeyToken=30ad4fe6b2a6aeed' or one of its dependencies. The system cannot find the file specified.

## Environment
Microsoft (R) Test Execution Command Line Tool Version 15.0.0.0
.NET Command Line Tools (1.0.1)

Product Information:
 Version:            1.0.1
 Commit SHA-1 hash:  005db40cd1

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.14393
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\1.0.1

**Comment by arkasha** [comment]
@livarcocc @piotrpMSFT

**Comment by codito** [comment]
@arkasha a `PackageReference` to `Microsoft.NET.Test.Sdk` is missing in test project. Can you please add it? It will allow nuget to compute dependencies closure/binding redirects appropriately.

You may hit into #428, this workaround will help https://github.com/Microsoft/vstest/issues/428#issuecomment-276801928

**Comment by arkasha** [comment]
I did that. It didn't fix the issue.

**Comment by Faizan2304** [comment]
@arkasha: I tried to repro it but no luck. Can you please share a repro project.

Can you also try this:
Add following line in your test project and run the test
```xml
<PropertyGroup>
  <AutoGenerateBindingRedirects>true</AutoGenerateBindingRedirects>
  <GenerateBindingRedirectsOutputType>true</GenerateBindingRedirectsOutputType>
</PropertyGroup>
```
