### ISSUE TITLE
Times shown in Output window, is too precise

### ISSUE THREAD

**Issue by davkean** [Microsoft/vstest#614]
The time that is shown in the Output window is too precise, to the degree that marks it harder to read:

![image](https://cloud.githubusercontent.com/assets/1103906/23927270/c50670ba-096c-11e7-848b-0816b304dc98.png)

I'm not sure why it needs to show this much precision, it's makes the output so much harder to parse in my head.

**Comment by codito** [comment]
Copied to https://github.com/xunit/xunit/issues/1164 since the adapter provides this output.
