### ISSUE TITLE
Load an extension from sources' paths

### ISSUE THREAD

**Issue by NikolayPianikov** [Microsoft/vstest#616]
## Description
It will be good to try finding and to load extensions from the directories specified in sources' paths - to have ability to add my extension as reference to a NuGet package for a test project.

## Steps to reproduce
`dotnet test -l=teamcity`
for netcoreapp1.0 test projects

See [this solution](https://github.com/JetBrains/TeamCity.VSTest.TestAdapter/tree/master/Samples) to reproduce.

## Expected behavior
For example when I run tests using my custom logger `dotnet test -l=teamcity` it works for net45. And it is good.

## Actual behavior
But when I run similar tests using my custom logger for netcoreapp1.0. it does not work.

And I should run tests as `dotnet test -l=teamcity -a=.` Only in this case the extension for my logger is loaded as I wish.

## Environment
VS 2017
Microsoft.NET.Test.Sdk version="15.0.0"
Windows 10

**Comment by codito** [comment]
@NikolayPianikov this is recently fixed in master (#557). Will update when a package is available to play with.

**Comment by NikolayPianikov** [comment]
@codito thank you
