### ISSUE TITLE
"Profile Test" fails on .NET Core xUnit test due to "Unknown test framework"

### ISSUE THREAD

**Issue by tmeschter** [Microsoft/vstest#617]
## Description

When attempting to profile a .NET Core xUnit test, running the test fails due to an "unknown test framework".

## Steps to reproduce

1. Create a xUnit Test Project (.NET Core) project; 
2. Click the “Run Tests After Build” icon on the “Test Explorer” window; 
3. Right click the solution in “Solution Explorer” and click “Build Solution”.
4. Wait for the build to complete and the test run to pass 
5. In the "Test Explorer" window, right-click on the unit test and select "Profile Test".

## Expected behavior

Test runs and is profiled.

## Actual behavior

The following is printed to the "Tests" pane of the Output window:

![outputwindow](https://cloud.githubusercontent.com/assets/10506730/23971761/7b4697f0-098c-11e7-875f-f9744a26b5b1.png)

**Comment by harshjain2** [comment]
@tmeschter profile tests is not implemented for netcore projects yet. This support requires datacollectors infrastructure (https://github.com/microsoft/vstest/issues/309). It will come post RTW.

**Comment by tonyferrell** [comment]
Is profiling still unsupported for netcore projects?

**Comment by smadala** [comment]
@codito @sudiptadmsft @pvlakshm @mayankbansal018

**Comment by pvlakshm** [comment]
We just ran out of schedule-room in the present 15.5 cycle to get to this in a meaningful way. Having said that we will take this up for the immediately following cycle.

**Comment by snkota** [comment]
This is being tracked external to this repo here:
https://developercommunity.visualstudio.com/content/problem/145926/profile-test-fails-on-net-core-xunit-test-due-to-u.html

**Comment by rschiefer** [comment]
1.5 years later, any updates?

**Comment by stephengeorgewest-navitaire** [comment]
Update from https://developercommunity.visualstudio.com/content/problem/145926/profile-test-fails-on-net-core-xunit-test-due-to-u.html "A fix for this issue has been internally implemented and is being prepared for release. We'll update you once it becomes available for download."
