### ISSUE TITLE
test assembly skipped with weird message.  netcoreapp1.1 and net452

### ISSUE THREAD

**Issue by rykr** [Microsoft/vstest#619]
I have a library and a test library.  The test library references the library.  They are both using multitargeting of net452 and netcoreapp1.1.   The netcoreapp1.1 side tests fine.  The net452 gives me a weird error.

When do the following:

dotnet test testlib.csproj -f net452

I get this:

Skipping:  testlib (could not find dependent assembly 'testlib, version 6.10.2')

It's saying it's going to skip testlib because it can't find testlib.  But testlib is there with what seems to be all the necessary aux files in the net452 folder.

Any idea what might be going on here?

This is with VS 2017 RTM and .NET core 1.1

**Comment by codito** [comment]
@rykr does diagnostic logs say anything? `dotnet test testlib.csproj -f net452 -d:log.txt`; the `log.host.*.txt` file generated may have interesting information.

**Comment by rykr** [comment]
Here is my log file.    Do you see anything weird?  I see one area where there is a failure to enumerate some types.
[log.txt](https://github.com/Microsoft/vstest/files/851474/log.txt)

**Comment by codito** [comment]
@rykr can you please share `log.host.17-03-17_13-44-08_89009_1.txt` file too?

**Comment by Faizan2304** [comment]
@rykr are you still facing this issue? or it get resolved?

**Comment by rykr** [comment]
we got it resolved.  not sure what the team did but don't think it's still an issue for us.
