### ISSUE TITLE
Cannot run specific test from code editor...

### ISSUE THREAD

**Issue by KevinH-MS** [Microsoft/vstest#620]
I'm not sure if this bug goes here, but...

## Description
> When I right-click on a specific test or do Ctrl + R, T, a different test runs (or perhaps it's all the tests in the file).  The only way I can run a specific test is by finding it in Test Explorer.

d15rel.26228.0

**Comment by codito** [comment]
Same issue as https://github.com/xunit/xunit/issues/1140. Closing as external.

Please feel free to reopen if this is coming up for non xunit frameworks too.
