### ISSUE TITLE
Code coverage for .net core applications

### ISSUE THREAD

**Issue by piotrpMSFT** [Microsoft/vstest#621]
_From @srini1978 on March 11, 2017 11:5_

## Steps to reproduce

1. Run .net core application with VSTS
2. Choose Analyze test with code coverage

## Expected  behavior

Code coverage should come up for each of the dlls

## Actual behavior

Multiple resultssets show up skewing up code coverage. Some internal dlls report code coverage multiple times

## Environment data
`dotnet --info` output:

_Copied from original issue: dotnet/cli#6010_

**Comment by piotrpMSFT** [comment]
_From @ChristophB125 on March 13, 2017 16:54_

@srini1978  I am trying to get code coverage working at the moment as well. Can you please share how you invoke dotnet test and which NuGet package you use for code coverage (I assume Microsoft.CodeCoverage). 
Possible duplicate of #1995 ?

**Comment by piotrpMSFT** [comment]
_From @shanselman on March 14, 2017 23:41_

@piotrpMSFT Did this ship with 1.0 or is this not done?

**Comment by piotrpMSFT** [comment]
_From @livarcocc on March 14, 2017 23:51_

I don't think this was explicitly done.

@codito @Faizan2304 Will this work out of the box because of vstest?

**Comment by codito** [comment]
Code coverage will not work in 15.0. We're working on bringing up the infrastructure for next release.

**Comment by codito** [comment]
Same as #579. Keeping #579 open and closing this issue to help track better.
