### ISSUE TITLE
VSTest fails to read source information if DebugType is embedded

### ISSUE THREAD

**Issue by onovotny** [Microsoft/vstest#622]
For both .NET 4.6 and .NET Core App tests, if the `DebugType` is set to be `embedded` all tests show up as External in the Test Explorer. It does not appear that the test tools support reading embedded ppdb's yet.

**Comment by mattzink** [comment]
I disagree with marking this with the "question" label. This is indeed a serious defect, since embedded PDB's are considered the best practice for .NET Core class libraries.

**Comment by snkota** [comment]
This is being tracked external to this repo here:
https://developercommunity.visualstudio.com/content/problem/145925/vstest-fails-to-read-source-information-if-debugty.html
