### ISSUE TITLE
Can't see the currently running test in Test Explorer

### ISSUE THREAD

**Issue by codito** [Microsoft/vstest#626]
(Created from #623).

## Description
> I can't see the active test being run. There are situations where I want to see the current test being run (both on the command line and in visual studio) so I can tell which one is hanging (if it hangs). It would have saved me so many hours if there was a simple way to show the active test being run in both the test explorer and on the command line.

While test explorer supports showing the current running test. `Passed Tests` or `Failed Tests` group shows first in the UI, followed by `Not Run Tests`. If the number of tests is high, the `Not Run` group can get easily outside the screen real estate of test explorer.

Is there a better way for user to get feedback on which test is running (if they have several thousand unit tests).

**Comment by codito** [comment]
@davkean mentioned in https://github.com/Microsoft/vstest/issues/623#issuecomment-287280338

I remember correctly about the "current" running test, I filed this back in VS 2012 when the Test Explorer was added, the reason they don't show current progress was the communication back to VS to update the "current" test was slowing down the test run. However, I really only want to see "current" when the test > a couple of seconds, by which case you could make it to only communicate "current" when running tests that takes a while.

**Comment by codito** [comment]
@ckurt mentioned in https://github.com/Microsoft/vstest/issues/623#issuecomment-287274705

6a. Please update the icon used for "test currently running". Ideally to an icon that moves, but at least to an icon that is not mainly green the same color indicating passed tests. This also make the currently running test very hard to find, especially if it is in a list of tests you already ran and passed.

**Comment by snkota** [comment]
This is being tracked external to this repo here:
https://developercommunity.visualstudio.com/content/problem/145923/cant-see-the-currently-running-test-in-test-explor.html
