### ISSUE TITLE
Test Explorer fails to show tests. dotnet test works

### ISSUE THREAD

**Issue by onovotny** [Microsoft/vstest#629]
## Description
VS 2017 fails to see unit tests while running `dotnet test` on the command line properly sees and executes the tests.

## Steps to reproduce
checkout Ix.NET from here:
https://github.com/Reactive-Extensions/Rx.NET
commit: 01d73a4da3497fcf79194106e18f7757186ffb6a
Solution: /Ix.NET/Source/Ix.Net.sln

## Expected behavior
Test Explorer should discover the tests in the 'Tests' project

## Actual behavior
Discover runs but no test displayed

After a build, running `dotnet test --no-build` from the Tests directory works correctly.

**Comment by mayankbansal018** [comment]
@onovotny I tried these steps on latest VS2017.5 & could not reproduce the issue. Can you please try it again on latest VS 2017, & see if it still repro's at your end.

**Comment by onovotny** [comment]
Seems to be working for me now as well.
