### ISSUE TITLE
dotnet test [project] should look for csproj

### ISSUE THREAD

**Issue by livarcocc** [Microsoft/vstest#630]
_From @lukasz-pyrzyk on March 17, 2017 11:30_

My solution looks like:
```
Kronos.Sln
/Src/Kronos.Client
/Tests/Kronos.Client.Tests
```

## Steps to reproduce
`dotnet test Tests\Kronos.Client.Tests`

## Expected  behavior
`dotnet test` should automatically find single csproj in given path

## Actual behavior
> **Couldn't **find** a project to run test from**. Ensure a project exists in C:\Dev\Kronos.
> Or pass the path to the project

## Environment data
```
.NET Command Line Tools (1.0.1)

Product Information:
 Version:            1.0.1
 Commit SHA-1 hash:  005db40cd1

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.10586
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\1.0.1
```

I would suggest following points:
- Print information about given path
- If user passed a directory, try to find a csproj

_Copied from original issue: dotnet/cli#6057_

**Comment by codito** [comment]
Thanks for the feedback @lukasz-pyrzyk.

This fix will likely require a change in the logic to find csproj in `dotnet-test`: https://github.com/dotnet/cli/blob/master/src/dotnet/commands/dotnet-test/Program.cs#L184

**Comment by Lavinski** [comment]
I ran into this upgrading from .proj to .csproj

**Comment by MeikTranel** [comment]
@codito am i correct that the entire csproj compatible logic is happening in the CLI itself?
This sounds like its gonna use shared resolution logic from the cli. Does this issue belong here? It sounds like it could have lots of impact on the entire dotnet cli.

**Comment by singhsarab** [comment]
This is fixed. Validated with dotnet cli version 3.0.100-preview-010184
