### ISSUE TITLE
dotnet test -parallel N

### ISSUE THREAD

**Issue by livarcocc** [Microsoft/vstest#631]
_From @lukasz-pyrzyk on March 17, 2017 14:39_

How to disable parallel run for xunit tests? 

I found similar issues (#1447, #401), but they look out of date. There is no `-diagnostics`` flag.

Should I use `-s` and create some configuration file?

## Steps to reproduce
`dotnet test Project.csproj -parallel None`
or
`dotnet test Project.csproj -parallel none`

## Expected  behavior
Disable parallel execution of the tests

## Actual behavior
```
MSBUILD : error MSB1001: Unknown switch.
Switch: -parallel
```

## Environment data
```
.NET Command Line Tools (1.0.1)

Product Information:
 Version:            1.0.1
 Commit SHA-1 hash:  005db40cd1

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.10586
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\1.0.1
```

_Copied from original issue: dotnet/cli#6059_

**Comment by codito** [comment]
In the new test platform, it is possible to pass args to adapters using the `dotnet test -- xunit.someconfig=somevalue` syntax. I think you can use parallelizeAssembly and parallelizeTestCollections options in xunit.runner.json (https://xunit.github.io/docs/configuring-with-json.html). A sample project with xunit.runner.json is available here: https://github.com/Reactive-Extensions/Rx.NET/blob/develop/Ix.NET/Source/Tests/Tests.csproj.

Created https://github.com/xunit/xunit/issues/1169 to discuss if this is an interesting feature for xunit adapter to support.
