### ISSUE TITLE
Dotnet Core test executed in Visual Studio 2017 - Assembly.Load() is incorrectly able to load assemblies from Visual Studio Extensions

### ISSUE THREAD

**Issue by jonstelly** [Microsoft/vstest#632]
## Description
Attempting to execute dotnet core unit/integration tests that use RavenDB 3.5.3 client.  These tests execute and pass using the dotnet CLI, or the ReSharper Test Runner in Visual Studio, but using the Test Explorer, they fail with an error about log4net and AppDomain.add_ProcessExit:

> Message: Test method ProcessExitException.RavenException.InitializeStore threw exception: System.TypeInitializationException: The type initializer for 'log4net.Core.LoggerManager' threw an exception. ---> System.MethodAccessException: Attempt by method 'log4net.Core.LoggerManager.RegisterAppDomainEvents()' to access method 'System.AppDomain.add_ProcessExit(System.EventHandler)' failed.

From debugging, I found that the ravendb client attempts to load log4net using Assembly.Load(...).  If it's able to load then it uses that library for logging.  The issue is that it's finding log4net from the directory of an installed Visual Studio extension.  When debugging, I can see that the CodeBase for the log4net assembly loaded by my test is:

> file:///C:/Program Files (x86)/Microsoft Visual Studio/2017/Enterprise/Common7/Ide/Extensions/XSNRCEZZ.l1M/log4net.dll

I don't believe test code should be able to load assemblies from extensions loaded into Visual Studio, and I bet in this case, this log4net assembly is built against the full runtime, and not dotnet core or one of the netstandard targets.  I believe that explains the message I included above.

This extension directory is the powershell tools for Visual Studio.  When I removed that component for Visual Studio, the tests started passing.

## Steps to reproduce
1. Install Visual Studio 2017 and include the PowerShell component when installing
2. Extract and load the following project
[ProcessExitException.zip](https://github.com/Microsoft/vstest/files/852186/ProcessExitException.zip)
3. Run the RavenException.InitializeStore test inside Visual Studio

## Expected behavior
The test should pass

## Actual behavior
It fails as noted above

## Environment
Windows 10 15025+
Visual Studio 2017 (with the PowerShell component installed)

## Workaround
Remove the PowerShell component (and probably also Xamarin/Mobile tools, I see log4net.dll in that extension also)

**Comment by jonstelly** [comment]
![image](https://cloud.githubusercontent.com/assets/967068/24069270/d95f43a0-0b71-11e7-8218-cff2d6d6118a.png)
This screenshot was taken during the execution of the tests before I removed PowerShell and Xamarin.  That's a pretty painful workaround as I need to do some Xamarin development also.

**Comment by jonstelly** [comment]
Is this issue not clearly worded?  Just wondering since it doesn't seem to have been triaged.  To try and simplify I've attached a simpler test that doesn't use the ravendb client.

[AssemblyLoadExample.zip](https://github.com/Microsoft/vstest/files/870160/AssemblyLoadExample.zip)

    [TestClass]
    public class AssemblyLoadTests
    {
        [TestMethod]
        public void LoadLogForNet()
        {
            Assert.ThrowsException<FileNotFoundException>(() =>
            {
                var log = Assembly.Load(new AssemblyName("log4net"));
            });
        }
    }

This test project has no reference to log4net, so this test should pass.  But if the 'PowerShell Tools' extension is installed in Visual Studio, the log4net assembly is found in the extension directory mentioned above, and the assembly is loaded (though it's not even a dotnet core/standard assembly, so any usage of that library fails).

A test passing or failing should not depend on an unrelated Visual Studio extension being installed or not.  During test execution, assemblies should not be loaded from extension directories.

**Comment by AbhitejJohn** [comment]
Interesting. I guess this is happening because of the powershell tools test adapter that the test platforms assembly resolution is automatically pointing to. Since this is .Net core there isn't a separate appdomain where tests are loaded and run from. It looks like the test adapter assembly resolver is creeping into the test run. We need to turn it off after the adapter is loaded.

**Comment by spati2** [comment]
I am facing a similar issue. What is the resolution here?

**Comment by himanshu-trivedi-spider** [comment]
I had same issue, and to move on, I installed dependency of log4net and that fixed the issue.

**Comment by spati2** [comment]
That will work, but what if I dont want to use log4net?moreover the version of log4net being used in incompatible with netcore, should that reference even be loaded? Also is there a way we can prevent test adapter assembly resolver from kicking in? @AbhitejJohn ?

**Comment by codito** [comment]
Thanks @jonstelly @spati2 for reporting this.

@Faizan2304 is this issue same as the desktop adapters nuget? We shouldn't be passing the powershell adapter to netcore test runs.

**Comment by spati2** [comment]
Thanks @codito for responding. So can I expect a fix from you guys on this? Customers on AWS SDK dot net toolkit are encountering this very issue and I am afraid any fix that we add to our sdk would not be a foolproof solution

**Comment by codito** [comment]
Yes, we will fix this.

**Comment by Faizan2304** [comment]
>@Faizan2304 is this issue same as the desktop adapters nuget? We shouldn't be passing the powershell adapter to netcore test runs.
@codito : This is not adapter nuget issue.
This looks like what @AbhitejJohn explaining in [this comment](https://github.com/Microsoft/vstest/issues/632#issuecomment-289359283)

**Comment by Faizan2304** [comment]
Fixed will come in next preview of visual studio.

**Comment by somildutt** [comment]
Hello 

I am getting below mentioned errors when implementing Log4Net in Xamarine Visual Studio 2017 project.
Can we use log4net for UWP or Xamarine ?

***********
System.TypeInitializationException occurred
  HResult=0x80131534
  Message=The type initializer for 'CoroBoreController.CatchInfo' threw an exception.
  Source=<Cannot evaluate the exception source>
Inner Exception 1:
TypeInitializationException: The type initializer for 'log4net.Core.LoggerManager' threw an exception.
Inner Exception 2:
MethodAccessException: Attempt by method 'log4net.Core.LoggerManager.RegisterAppDomainEvents()' to access method 'System.AppDomain.add_ProcessExit(System.EventHandler)' failed.
**************************************

**Comment by spati2** [comment]
When will the preview be available?
@Faizan2304
