### ISSUE TITLE
/testcasefilter through translation layer

### ISSUE THREAD

**Issue by AbhitejJohn** [Microsoft/vstest#633]
## Description
There is no way currently for a consumer of the vstest.console translation layer to pass in arguments like /testcasefilter to vstest.console. It can only communicate through runsettings which does not understand filtering. This blocks consumers who do not store TestCase objects or those that tend to follow a command driven approach.

## Steps to reproduce
* Instantiate an instance of VSTestConsoleWrapper.
* Attempt to Run Tests via the RunTests(IEnumerable<string> sources, string runSettings, ITestRunEventsHandler testRunEventsHandler) API.

## Expected behavior
That there would be some way of providing test case filtering information to the test run.

## Actual behavior
None available.

## Environment
vstest.console: 15.0.0

**Comment by AbhitejJohn** [comment]
@codito, @singhsarab : Thoughts?

**Comment by smadala** [comment]
Addressed via https://github.com/Microsoft/vstest/pull/1052
