### ISSUE TITLE
"Open Test" from Test Explorer window does not work with .NET Core project.

### ISSUE THREAD

**Issue by tmeschter** [Microsoft/vstest#638]
## Description

"Open Test" from Test Explorer window does not work with .NET Core project.

## Steps to reproduce

1. Download [DemoOn.NETCore.zip](https://github.com/Microsoft/vstest/files/856234/DemoOn.NETCore.zip) and extract it.
2. Open the solution.
3. Build the solution.
4. Open the Test Explorer window.
5. Right-click on one of the tests and select "Open Test" (or hit F12).

## Expected behavior

The test is opened in the editor.

## Actual behavior

Nothing happens.

## Environment
VS Build: D15Rel 26317.1

**Comment by codito** [comment]
@tmeschter the `TrainerTests` test project was referring older versions of NET.Test.Sdk. Able to use `Open Test` after updating the references to following. Tested on VS 2017 RTM build.

```
  <ItemGroup>
    <PackageReference Include="Microsoft.NET.Test.Sdk" Version="15.0.0" />
    <PackageReference Include="MSTest.TestAdapter" Version="1.1.13" />
    <PackageReference Include="MSTest.TestFramework" Version="1.1.13" />
  </ItemGroup>
```

**Comment by MiaomiaoHuangfu** [comment]
After updating the references to the above according to codito, "Open Test" from Test Explorer window works. 
Verified on d15rel.26320.00.

**Comment by codito** [comment]
Thanks for update @MiaomiaoHuangfu
