### ISSUE TITLE
Evaluate data interchange constructs in test platform

### ISSUE THREAD

**Issue by codito** [microsoft/vstest#648]
Currently test platform uses JSON messages over sockets to communicate between runner and testhost.

Following scenarios must be supported for communication
* Runner and testhost are both in the same machine
* Runner and testhost are on different machines (remote scenarios). A variation is testhost running on attached devices
* Editor and IDEs must be able to control runner on a JSON protocol
* Runner, testhost and editors could be on different languages/runtimes
* Implementation must be cross platform (available on all platforms supported by .net core)

Evaluate following options:
* Compare JSON serializers (jil, netjson, json.net)
* Compare inter process options (shared memory, sockets)
* Compare other random access/zero copy data interchange formats (protobuf, capnproto etc.)

Related to #623.

**Comment by Evangelink** [comment]
We are currently investigating other solutions.
