### ISSUE TITLE
Live Unit Tests menu option is missing.

### ISSUE THREAD

**Issue by MrClyfar** [Microsoft/vstest#652]
## Description
When I installed VS 2017 Enterprise, after it was released earlier in March, I was able to try out the Live Unit test feature without a hitch. At some point, which I'm not certain of, I've noticed that the Live Unit Test menu option is now missing. It's not displayed in the IDE at all. I cannot find the command in the menu bar customize dialog either. It's simply vanished.

I have re-run the VS installer and can confirm that 'Live Unit Test' was ticked in the component selection.

I recall that I did install a VS 2017 product update (via Extensions and Updates) about two weeks ago. Whether the menu item went missing after this is unclear.

For reference, I mentioned about this here:(https://developercommunity.visualstudio.com/content/problem/8275/live-unit-testing-menu-option-missing.html)

## Steps to reproduce
Open a unit test project in Visual Studio 2017 Enterprise.
Click the 'Test' menu.

## Expected behavior
In the 'Test' menu a 'Live Unit Tests' option should appear.

## Actual behavior
There is no 'Live Unit Tests' option visible in the 'Test' menu.

## Environment
Microsoft Visual Studio Enterprise 2017
Version 15.0.26228.9 D15RTWSVC
Microsoft .NET Framework
Version 4.6.01038

NCrunch 3.5.0.1 (Though uninstalling this did not result in the Live Unit Tests menu option appearing).
Windows 10 v1511

**Comment by MrClyfar** [comment]
Er, OK this is weird.

I just started VS 2017 now, and opened the unit test project I mentioned, and the  'Live Unit Tests' menu option has suddenly just appeared again in the 'Test' menu. However, when I click 'Start' I'm seeing a message

"Expected 1 export(s) with contract name 'Microsoft.CodeAnalysis.LiveUnitTesting.Orchestrator' but found 0 after applying application constraints"

I'm going to Goole that error now, to see what it could be. But it's was really weird that the live unit tests menu option finally turned up after another VS restart. It would be better if it was enabled all the time, less confusing. Ah well.

**Comment by MrClyfar** [comment]
As a test, I just closed VS 2017 and re-opened the unit test project again. The 'Live Unit Test' menu option has vanished again. I give up. This is doing my head in.

**Comment by codito** [comment]
@ManishJayaswal

**Comment by ManishJayaswal** [comment]
This is likely because the MEF cache is dirty. Can you please run Developer Command Prompt for VS 2017 as administrator and run the following command - "devenv /clearcache /setup"
