### ISSUE TITLE
Live unit testing support for .NET Core

### ISSUE THREAD

**Issue by natemcmaster** [Microsoft/vstest#654]
.NET Core test projects don't support live unit testing yet. 

**Steps to reproduce**
Test > Live Unit Testing > Start

**Expected**
It works

**Actual**
Log shows

> Live Unit Testing does not yet support .NET Core

**Environment**
VS 15.0 RTW

To triage team: I'm sure this is already a known issue, but I couldn't find an issue on GitHub or in VSTS to track this.

**Comment by Suriman** [comment]
Please, we need it!. It is a very practical tool!.
Thanks!

**Comment by alarimer** [comment]
Still unavailable in VS 15.2

**Comment by Suriman** [comment]
It is in VS 15.3 (still in preview).

**Comment by codito** [comment]
Closing this since it shipped in 15.3-preview release!
