### ISSUE TITLE
Failed to load System.Runtime when tests run from Test Explorer in VS 2017

### ISSUE THREAD

**Issue by caleblloyd** [Microsoft/vstest#655]
## Description

When running tests from Visual Studio Test Explorer, my `net462` tests fail with the exception:

```
System.IO.FileLoadException : Could not load file or assembly 'System.Runtime, Version=4.1.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' or one of its dependencies. The located assembly's manifest definition does not match the assembly reference. (Exception from HRESULT: 0x80131040)
```

When I run `dotnet test` from the command line, they work fine.  Additionally, they ran fine from the Test Explorer in previous versions of Visual Studio 2017.

## Steps to reproduce

The exception happens right when the test project calls into another `net462` console project.  Here is my `.csproj` file for the test project.

```
<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net462</TargetFramework>
    <AssemblyName>test</AssemblyName>
    <RuntimeIdentifier>win10-x64</RuntimeIdentifier>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\another-net462-console-project\another-net462-console-project.csproj" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="Microsoft.DotNet.InternalAbstractions" Version="1.0.0" />
    <PackageReference Include="Microsoft.NET.Test.Sdk" Version="15.0.0" />
    <PackageReference Include="Microsoft.TestPlatform.TestHost" Version="15.0.0" />
    <PackageReference Include="xunit" Version="2.2.0" />
    <PackageReference Include="xunit.runner.visualstudio" Version="2.2.0" />
  </ItemGroup>
  <ItemGroup>
    <Reference Include="System" />
    <Reference Include="System.Runtime" />
    <Reference Include="Microsoft.CSharp" />
  </ItemGroup>
</Project>
```

## Expected behavior

Running tests from the Test Explorer should work with no exceptions if it works from the console with no exceptions.

## Actual behavior

Running tests from the Test Explorer gives this exception.  Running tests from the console works fine.

## Environment

Visual Studio Community 2017
VisualStudio/15.0.0+26228.9

```
> dotnet --info
.NET Command Line Tools (1.0.0)

Product Information:
 Version:            1.0.0
 Commit SHA-1 hash:  e53429feb4

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.14393
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\1.0.0
```

**Comment by caleblloyd** [comment]
If I add the following to my `test.csproj`, the tests will  run in the Test Explorer, however I get a bunch of "package downgrade warnings"

```
    <PackageReference Include="System.Runtime" Version="4.1.0" />
    <PackageReference Include="System.IO" Version="4.1.0" />
```

![image](https://cloud.githubusercontent.com/assets/2414837/24268384/ffc0cb74-0fe3-11e7-8ef6-1bbebbb74994.png)

**Comment by caleblloyd** [comment]
It appears that the root problem is that my `net462` console application references an upstream package that is only build for `netstandard1.5`, which contains `4.3.0` references for all of it's `System` libraries.

I have rebuilt the upstream package separately for `net462` and the issue goes away.  Why is this just now becoming an issue, and why does it only affect the VS 2017 Test Explorer?  I thought `net462` was supposed to be able to seamlessly consume `netstandard1.5` packages.

**Comment by gulbanana** [comment]
i have a similar issue, but i cannot recompile the upstream package because it is Microsoft.CodeAnalysis.Compilers. how can we run net461 tests for a lib which targets such a package now?

**Comment by pvlakshm** [comment]
This is outside the scope of this repo. Please file this using the VSFeedback tool available in VS frm the Help menu.
