### ISSUE TITLE
After dotnet publish, Could not find testhost.dll for source

### ISSUE THREAD

**Issue by saikatguha** [Microsoft/vstest#657]
## Description
After running `dotnet publish` on a test project that includes a reference to Microsoft.TestPlatform.TestHost, and then deploying the published binaries to another host, running `dotnet vstest <project.dll>` throws the error `Could not find testhost.dll for source` even though `testhost.dll` is in the published directory. 

Deleting `<project>.runtimeconfig.dev.json` makes `dotnet vstest <project.dll>` work fine.

This is because of a probing bug in `GetTestHostPath` in https://github.com/Microsoft/vstest/blob/master/src/Microsoft.TestPlatform.CrossPlatEngine/Hosting/DotnetTestHostManager.cs 

On line 320, if `<project>.runtimeconfig.dev.json` is present, it probes for the relative path at a number of locations including `/root/.nuget/packages` folder. However, when the published directory is deployed on a different host (which does not have a .nuget cache), the probing fails.

However, line 368 is meant to handle this scenario of testing after publish. Except the if condition is skipped because the package reference was found, and `testHostPath` was set in line 344. 

## Fix
Add `testHostPath = null;` to Line 366.

**Comment by Faizan2304** [comment]
@saikatguha : Thank you for opening the issue with us. I have created a PR to fix this issue.
I have a question here... as per my understanding publish folder shouldn't have `<project>.runtimeconfig.dev.json`. So I got confused here how your publish folder is having `<project>.runtimeconfig.dev.json`.  
Am I missing here something?

**Comment by Faizan2304** [comment]
Fixed!!!

**Comment by saikatguha** [comment]
@Faizan2304: `<project>.runtimeconfig.dev.json` might have been put there by `dotnet vstest -o <publishDir> ...` when building or something else in the build script. Either way, the fix works. Thanks!!
