### ISSUE TITLE
Tests & Performance Profiler

### ISSUE THREAD

**Issue by tom3m** [Microsoft/vstest#660]
Hello team!

Currently it is not possible to run all or just several tests from test explorer under perfomance profiler.
So, it makes it impossible at all to understand main bottlenecks in a set of tests.
Resharper allows that option and it usefull so I don't see why it cannot/should not be done out of the box in the VS.

Thanks
Regards
Yahor Sinkevich

**Comment by pvlakshm** [comment]
This is outside the scope of this repo. Please file this using the VSFeedback tool available in VS frm the Help menu.
