### ISSUE TITLE
Add VS Unit testing templates for .NET core 2.0

### ISSUE THREAD

**Issue by sbaid** [Microsoft/vstest#664]
## Description
Based on the outcome of the discussion https://github.com/dotnet/roslyn-project-system/issues/1836
Add new templates or update existing .NET core 1.1 templates

## Steps to reproduce
> What steps can reproduce the defect?
> Please share the setup, commandline for vstest.console, sample project, target
> framework etc.

## Expected behavior
> Share the expected output

## Actual behavior
> What is the behavior observed?

## Environment
> Please share additional details about the test environment.
> Operating system, Build version of vstest.console

**Comment by smadala** [comment]
fixed in: https://github.com/dotnet/sdk/pull/1067
