### ISSUE TITLE
Add test coverage for the netcoreapp2.0 in acceptance tests

### ISSUE THREAD

**Issue by sbaid** [Microsoft/vstest#667]
## Description
This will by default include the package fallback folder coverage. 

https://github.com/dotnet/cli/issues/6100
https://github.com/dotnet/cli/issues/5575
https://github.com/NuGet/Home/wiki/%5BSpec%5D-Fallback-package-folders

## Steps to reproduce
> What steps can reproduce the defect?
> Please share the setup, commandline for vstest.console, sample project, target
> framework etc.

## Expected behavior
> Share the expected output

## Actual behavior
> What is the behavior observed?

## Environment
> Please share additional details about the test environment.
> Operating system, Build version of vstest.console

**Comment by sbaid** [comment]
@livarcocc do u see any other work in `dotnet test` apart from validation of scenario.

**Comment by smadala** [comment]
Fixed in: f20e81ca2d6247cc465c627d005d9b091abcff71
