### ISSUE TITLE
Fix additional arguments help in dotnet test

### ISSUE THREAD

**Issue by sbaid** [Microsoft/vstest#687]
## Description
dotnet test -h displays this in help.
```
Usage: dotnet test [arguments] [options] [args]
...
Additional Arguments:
Any extra commandline runsettings arguments that should be passed to vstest. See 'dotnet vstest 
--help' for available options.
                                        Example: -- RunConfiguration.ResultsDirectory="C:\users\user\desktop\Results Directory" MSTest.DeploymentEnabled=false
```
suggest change first line to 
```
Usage: dotnet test [arguments] [options] [[--] <args>...]]
...
args: 
      Any extra arguments that should be passed to test adapter. Arguments may be specified as name-value pair of the form <n>=<v>, where <n> is the argument name, and <v> is the argument value. Use a space to separate multiple arguments.
    Example:  MSTest.DeploymentEnabled=false

<add  a aka.ms link that details out additional arguments documentation with example>
```

This help caused the confusion referenced in this https://github.com/dotnet/cli/issues/5659

## Steps to reproduce
> What steps can reproduce the defect?
> Please share the setup, commandline for vstest.console, sample project, target
> framework etc.

## Expected behavior
> Share the expected output

## Actual behavior
> What is the behavior observed?

## Environment
> Please share additional details about the test environment.
> Operating system, Build version of vstest.console

**Comment by Faizan2304** [comment]
Fixed!!
