### ISSUE TITLE
Default test adapters not available for testhost, due to unavailable of Extensions folder.

### ISSUE THREAD

**Issue by smadala** [Microsoft/vstest#689]
## Description
- Extensions folder not available testhost.x86.exe in artifacts\Debug\net46\win7-x64\TestHost.
- This cause failure of `CPPRunAllTestExecution` acceptance test failure.

## Steps to reproduce
> Run CPPRunAllTestExecution acceptance test.

## Expected behavior
> Test should pass.

## Actual behavior
> Test failed with `No test discoverer is registered to perform discovery of test cases. Register a test discoverer and try again.`

**Comment by Faizan2304** [comment]
Fixed!!
