### ISSUE TITLE
Can't build the project using visual studio 2017

### ISSUE THREAD

**Issue by luis-cortina** [Microsoft/vstest#695]
## Description
After doing a git clone, when trying to build the project NugetPackages can't be restored with the following error "The operation failed as details for project SimpleTestProject3 could not be loaded" . If I do a dotnet restore I get timeouts for all the package sources.

## Steps to reproduce
Using VS2017 latest version git clone the master branch, try to build with VS or do dotnet restore.

## Environment
Windows 10, Visual Studio Community 2017 latest version (15.0.0+26228.12)

**Comment by smadala** [comment]
@luis-cortina Thanks for raising issue. 
Tracking fix for this: https://github.com/Microsoft/vstest/pull/703
Mean while you can try out repo at commit: 6924402e13817bd2c749d6ff5027db62ca61225c
