### ISSUE TITLE
"Run All" builds projects again, even immediately after a build.

### ISSUE THREAD

**Issue by NickCraver** [Microsoft/vstest#696]
## Description
When a user has just built their solution to discover tests, upon running a test (or all tests) another build occurs. Why?

## Steps to reproduce
Pull any repo with tests - I'm using MiniProfiler right now: https://github.com/MiniProfiler/dotnet
1. Open `MiniProfiler.sln` in VS 2017 15.1
2. Build solution (Ctrl+Shift+B)
3. Open Test Explorer
4. Click "Run All"

## Expected behavior
The tests run, without performing an additional, unnecessary build.

## Actual behavior
All projects with tests and all dependencies are built again.

## Environment
VS 2017 15.1 (26403.0)

cc @davkean

**Comment by codito** [comment]
@NickCraver test explorer depends on "Build" to provide knowledge of test projects (and test containers - the output binaries that have tests) added/removed/updated. It expects "Build" to be a no-op if the solution was just built. My understanding is https://github.com/dotnet/project-system/issues/62 is making "Build" do a full solution build again.

Will this be good idea to let the user decide if they want to "just" run or always use the latest binaries (i.e. Build) for running tests? My 2 cents: when I am coding, this decision point to "build" or "not build" is an interrupt to my flow.

**Comment by NickCraver** [comment]
@codito Ideally? There'd be no prompt at all, Visual Studio should just be aware that it just built. *But that doesn't work*, so at the moment? Yes a prompt would be much better. 

I used to think people abandoning the Test Explorer and running all of their stuff from the CLI even when inside Visual Studio working were nuts, but I've just become one of them because it's *so much faster*. I'm very disappointed the fixes for this are pushed out months now, from 15.1 to 15.3 - so it looks like I'm at the command line for a while now. For large projects, this set of bugs is a huge time sink and regression from VS 2015.

Remember that those of us who helped with project.json and such are forced to change IDEs when updating the project type - we can't just continue using VS 2015. We're stick with the situation of exactly one IDE or the other...so these bugs which greatly affect efficiency are more important than ever.

**Comment by codito** [comment]
@NickCraver appreciate your feedback. Sorry for the pain this is causing. I already see that dotnet/project-system#62 is scheduled for next VS update, we will update this issue once it's fixed.

In the context of scaling test explorer for big solutions, there's a proposal at https://github.com/Microsoft/vstest/issues/674. Please do vote and share your thoughts.

**Comment by davkean** [comment]
@NickCraver Are you saying that VS 2015 was faster in this regard? It didn't even have incremental build support in _dotnet build_...

**Comment by davkean** [comment]
@NickCraver Can you do the following and I can quickly see if there's something else running during this second build that shouldn't be:

1. Open Solution
2. Tools -> Options -> Project and Solutions -> Build and Run -> MSbuild project build output verbository -> Diagnostic
3. Build the solution
4. Clear the Output window -> build category
5. Build the solution (not rebuild)
6. Copy that Output, put it in a file and share it out to me

This will tell me if there are targets that are running that shouldn't be slowing down your up-to-date build.

**Comment by NickCraver** [comment]
@davkean I'm trying to do this, but I can't get the output window to capture it, it's obviously exceeding the buffer capacity. Is there a way to up it, or redirect the output?

The log I captured is 62MB with an unknown amount missing from the front - happy to email that (1.3MB zipped), or preferably: the above - is there a any way to get the output from the way VS invokes it?

**Comment by davkean** [comment]
@NickCraver There's no way I know to increase the buffer. Instead of the solution, just build one of the projects.

**Comment by NickCraver** [comment]
MiniProfiler was a beast here, but I have the exact same behavior with a far simpler solution: [StackExchange.Exceptional (current commit link)](https://github.com/NickCraver/StackExchange.Exceptional/tree/b3a512c9a082f11abae4df80e59f826542eb466f/src). When re-running tests (or any build - not rebuild), I get the following behavior:

<img width="906" alt="screen shot 2017-09-16 at 12 22 57" src="https://user-images.githubusercontent.com/454813/30513916-dab8a60e-9ad9-11e7-90dc-b5e5e53fd5f7.png">

For some reason, these projects *always* build:
- StackExchange.Exceptional.Tests
- StackExchange.Exceptional.Tests.AspNetCore
- Samples.Console
- Samples.AspNetCore

Maybe noteworthy: some of these have embedded resources in the project and copies, e.g.:
```xml
  <ItemGroup>
    <None Update="*.json" CopyToOutputDirectory="Always" />
    <EmbeddedResource Include="*Config.json" />
    <EmbeddedResource Include="..\..\DBScripts\*.sql" />
  </ItemGroup>
```
...but changing `Always` to `PreserveNewest` doesn't have any effect.

A build of everything is too large, but here's a build log of StackExchange.Exceptional.Tests, using the instructions above for building a single project:

[StackExchange.Exceptional.Tests.build.log.zip](https://github.com/Microsoft/vstest/files/1308450/StackExchange.Exceptional.Tests.build.log.zip)

**Comment by NickCraver** [comment]
In case it helps save some time analyzing, here's a structured log as well (entire solution this time since it's compact): [StackExchange.Exceptional.Tests.buildstructured.zip](https://github.com/Microsoft/vstest/files/1308490/StackExchange.Exceptional.Tests.buildstructured.zip)

**Comment by wpostma** [comment]
According to a blog post I read recently, an Always copy is designed to cause a rebuild by design.  But the MVCE above shows that even a non-always copy is doing this?

https://blog.oz-code.com/visual-studio-keeps-rebuilding-projects-no-good-reason/

**Comment by davkean** [comment]
@NickCraver @wpostma I suspect you are running into this: https://github.com/dotnet/project-system/pull/2786.

**Comment by davkean** [comment]
This fix should be in 15.4 Preview 2.

**Comment by NickCraver** [comment]
@davkean I'm afraid I'm already on 15.4 Preview 2 and seeing the same behavior as the logs above, upgraded soon as it came out last week or so :(

**Comment by davkean** [comment]
If this still occurs when changing Always -> PreserveNewest on 15.4 Preview 2, can you open an issue over on http://github.com/dotnet/project-system? I suspect it's our issue not test.

1. Turn on Tools -> Options -> Project and Solutions -> .NET Core -> Logging Level -> Verbose
2. Build StackExchange.Exceptional.Tests once
3. Clear Output window
4. Build StackExchange.Exceptional.Tests again
5. Attach that log. We need the up-to-date log, not build log to figure out what's going on.

**Comment by snkota** [comment]
This is being tracked external to this repo here:
https://developercommunity.visualstudio.com/content/problem/145920/run-all-builds-projects-again-even-immediately-aft.html
