### ISSUE TITLE
vstest.executionengine.exe has stopped working 

### ISSUE THREAD

**Issue by nigurr** [Microsoft/vstest#704]
Ref: https://github.com/Microsoft/vsts-tasks/issues/3926

Process dumps:  https://ufile.io/c1db21

**Comment by smadala** [comment]
@k3flo Can you please provide user mode dump, follow the instructions from https://msdn.microsoft.com/en-us/library/windows/desktop/bb787181(v=vs.85).aspx.
use `DumpType 2: Full dump`

**Comment by k3flo** [comment]
@smadala I created a dump file in user mode:
http://ertelt.us/Upload/vstest.executionengine.exe.3160.zip

**Comment by smadala** [comment]
@k3flo Thanks for dump.
![crystalreport](https://cloud.githubusercontent.com/assets/4337332/24957546/aa69545e-1fa9-11e7-8147-96867e364773.png)
Seems like issue with Crystal Reports, which causing 
`Unhandled exception at 0x000007FEFE6D32B2 (oleaut32.dll) in vstest.executionengine.exe.3160.dmp: 0xC0000005: Access violation reading location 0x000000025F79EEA0.`

Can you please check any test that not using Crystal Reports as it suppose to?

**Comment by k3flo** [comment]
@smadala 
We disabled the Crystal Report tests and executed a test run. Everything worked fine.
What shall we do to get our Crystal Report tests working? If we execute the tests with the Visual Studio IDE on our local machines all crystal report tests are running without any problems. Thanks for your help.

**Comment by smadala** [comment]
Identify what are the particular Crystal report test(s) causing failure using vstest.console.exe and /testcasefilter switch. (Ex: vstest.console.exe <path_to_test_dll> /framework:<framework> /testcasefilter:FullyQualifiedName~<namespace/testname> /testadapterpath:<path_to_testadapter>).
Check the anything suspicious about same test cases.

What are VS IDE, Crystal Report and vstest.executionengine.exe versions in local and build server.

**Comment by k3flo** [comment]
@smadala
We executed all Crystal Report tests using vstest.console.exe on the virtual machine with the following command:
`"C:\Program Files (x86)\Microsoft Visual Studio 14.0\Common7\IDE\CommonExtensions\Microsoft\TestWindow\vstest.console.exe"
"C:\IntegrationTestBinaries\labs.ETL.Domain.IntegrationTests.dll" /Settings:"C:\Runsettings\integrationtests.runsettings" 
/Platform:x64 /Framework:framework45 /inIsolation /Tests:CrystalReport_`

**The test runner didn't crash.**

After that we restarted another build and deployment job and it failed again. After the testagent crashed we found this errors in the eventviewer:
[event_viewer_errors.txt](https://github.com/Microsoft/vstest/files/972607/event_viewer_errors.txt)

![eventviewer_errors](https://cloud.githubusercontent.com/assets/12381373/25650495/88e24856-2fdd-11e7-8cde-75e4ea513b69.PNG)

![exception](https://cloud.githubusercontent.com/assets/12381373/25650501/8fb18ce6-2fdd-11e7-800d-6c7dbecc87e2.PNG)

As you can see in our build task we don't use a testfilter. In our build job we distingiush between unit and integration tests and we do that by the naming of the test dll's. So our unit tests are named *UnitTests.dll and our integration tests are in assemblies named *IntegrationTests.dll.

Here you can see the configuration of the "Run functional tests"-Task:

![build_integration_test_configuration](https://cloud.githubusercontent.com/assets/12381373/25650560/1ce8da42-2fde-11e7-8c53-8d5c85de2279.PNG)

These are the versions running on our virtual test machine:
We use Crystal Reports version 13.0.18.2192. The vstest.executionengine.exe has version 14.0.25463,0.

**Comment by k3flo** [comment]
Hi @smadala ,
after we deactivated the Crystal Report Tests the Testrunner didn't crash immediately. But after executing our Build & Deployment Job two or three times it crashes again. I have the feeling that it only works correct if I restart our VM where the Tests are executed every day. But I am not really sure about it. It's only a feeling.

Attached you see the errors from the Event Viewer after the crash happened. Also I attached several screenshots. 

Can you please urgent adress and solve this problem. We need to execute our Integration Tests every Evening and we have soon a new release where we need a running test environment.

We really like the new Build vNext, but why it is so unstable?

[Event Viewer Errors.txt](https://github.com/Microsoft/vstest/files/1006834/Event.Viewer.Errors.txt)

![errors overview](https://cloud.githubusercontent.com/assets/12381373/26142413/af74ab5e-3ae0-11e7-9a0d-ee4300919d6c.PNG)

![crashed windows view](https://cloud.githubusercontent.com/assets/12381373/26142416/b2a327b0-3ae0-11e7-83a0-60893d73ee6b.PNG)


With kind regards
Flo

**Comment by nigurr** [comment]
@k3flo can you also share whether your are using VSTS or On-Prem TFS and the file version of DTAExecutionHost, vstest.executionengine.exe?

**Comment by smadala** [comment]
@k3flo Can you please share dump for DTAExecutionHost and vstest.executionengine.exe whenever it crashed?

**Comment by k3flo** [comment]
@nigurr @smadala
Versions:
vstest.executionengine.exe: 14.0.25463.0
DTAExecutionHost: 14.102.25729.0

We are using VSTS with our own build agent on a virtual machine.

Dumps:
[http://ertelt.us/Upload/dumps.zip](http://ertelt.us/Upload/dumps.zip)

**Comment by smadala** [comment]
@k3flo From dumps it seems like issue with test code `labs.ETL.Domain.IntegrationTests.dll!labs.ETL.Domain.IntegrationTests.Tasks.ETLLoadDataTaskTests.ETLLoadDataTaskCanLoadDataFrom_VARIABLE_to_ACCESS()`.
![etlloaddata](https://cloud.githubusercontent.com/assets/4337332/26817006/446c9b28-4ab2-11e7-9890-492457cf4781.png)

You can open dump in VS and do "Debug with *" action, to find call stack where the process crashed.
Can you please check that the process crashed at same test always?
If it is failing on different test every time it's most likely issue with machine. 

Follow [this blog](https://www.raymond.cc/blog/disable-program-has-stopped-working-error-dialog-in-windows-server-2008/) to prevent Error Dialog which may cause delay in build failure.

**Comment by Faizan2304** [comment]
@k3flo are you still facing this issue? or this got resolve?

**Comment by Faizan2304** [comment]
@k3flo : Please feel free to reopen this issue if you have open question.
