### ISSUE TITLE
Incorrect Project Icon for NetCore UnitTestProject in SolutionExplorer

### ISSUE THREAD

**Issue by jayaranigarg** [Microsoft/vstest#716]
## Description
On creating NetCore UnitTestProject, we should get a Test icon for the Project in solution explorer.

## Expected behavior
Project icon should be a test icon(one with beaker)

## Actual behavior
Project icon is that of ClassLibrary.

## Environment
VS 2015 (26403.0 d15rel)

**Comment by codito** [comment]
Duplicate of https://github.com/Microsoft/vstest/issues/394?

**Comment by Faizan2304** [comment]
Closing as a duplicate of https://github.com/Microsoft/vstest/issues/908
