### ISSUE TITLE
Test Explorer improvements

### ISSUE THREAD

**Issue by pvlakshm** [Microsoft/vstest#725]
Place holder for improvements to the Test Explorer covering the presentation of large suite of tests.

**Comment by PureKrome** [comment]
Any particular improvements? I have a few suggestions which I listed in #623 and can discuss them in here?

**Comment by snkota** [comment]
This is being tracked external to this repo here:
https://developercommunity.visualstudio.com/content/problem/145919/test-explorer-improvements.html
