### ISSUE TITLE
Add a -debug option to vstest.console to debug tests

### ISSUE THREAD

**Issue by AbhitejJohn** [Microsoft/vstest#732]
## Description
The ask here is to support a commandline option for debugging tests. This is currently possible via the `VSTEST_RUNNER_DEBUG` environment variable as detailed [here](https://github.com/Microsoft/vstest-docs/blob/master/docs/diagnose.md#debug-test-platform-components). However, the users intention here is to debug tests in a given session not every session that runs on the machine. So something like below would serve well
```
vstest.console /debug <TestContainers>
```

**Comment by pvlakshm** [comment]
I don't think this falls under the intended scope of vstest. Closing this; reactivate if you still think necessary.
