### ISSUE TITLE
Calls to CallContext.LogicalSetData made in external libraries during tests error out in VS IDE

### ISSUE THREAD

**Issue by ekumlin** [Microsoft/vstest#744]
## Description

When calling `CallContext.LogicalSetData` in an external library during a test method, the VS IDE will return the following error:

> An exception occurred while invoking executor 'executor://mstestadapter/v2': Unable to find assembly 'External.Library.Name, Version=2.0.5.0, Culture=neutral, PublicKeyToken=null'.

I expect this issue would happen with calls other than `LogicalSetData`, but this is the reliable repro we found first.

### Notes
- This is **a regression** from Visual Studio 2015.
- This **only** happens in the VS IDE. If I run `vstest.console.exe` on the DLLs, there is no error and the test passes.

## Steps to reproduce

*(Note: I had some issues getting a .NET Core sample set up. My sample projects all use the `net452` framework.)*

1. Create a solution with a *Class Library (.NET Standard)* called *External.Library.Name*.
1. Add a class called `Foo` with the following code:
    ```
    namespace External.Library.Name
    {
        using System;
        using System.Runtime.Remoting.Messaging;

        [Serializable]
        public class Foo
        {
            private static readonly string ValueKey = typeof(Foo).FullName;

            public static Foo B()
            {
                return CallContext.LogicalGetData(ValueKey) as Foo ?? new Foo();
            }

            public static void A(Foo value)
            {
                CallContext.LogicalSetData(ValueKey, value);
            }
        }
    }
    ```
1. Build and package the project as a NuGet: `msbuild /t:pack External.Library.Name.csproj`
1. Move the packaged NuGet to a local NuGet feed (that is referenced by Visual Studio).
1. Create a solution with a *Console App (.NET Core)* called *FooAppX*.
1. Add a *Class Library (.NET Standard)* called *Test.FooAppX*.
    1. Via the NuGet Package Manager UI, add the appropriate *Microsoft.NET.Test.Sdk*, *MSTest.TestAdapter*, and *MSTest.TestFramework* packages. (We have tried with latest `15.0.0` and `1.1.14` versions.)
    1. Via the NuGet Package Manager UI, add the local *External.Library.Name* package.
1. Add a test class called `Tests` with the following code:
    ```
    namespace Test.FooAppX
    {
        using External.Library.Name;
        using Microsoft.VisualStudio.TestTools.UnitTesting;

        [TestClass]
        public class Tests
        {
            [TestMethod]
            public void Test()
            {
                Foo.A(Foo.B());
            }
        }
    }
    ```
1. Run the test.

### Sample project

[**ExternalLibraryVsTestExecutorError.zip**](https://github.com/Microsoft/vstest/files/944962/ExternalLibraryVsTestExecutorError.zip)

Includes:
- *FooAppX* project
- *External.Library.Name* project
- *External.Library.Name* `nupkg` file

## Expected behavior

The test should pass with no errors.

## Actual behavior

The test does not run. The error below is shown in the output window.

> An exception occurred while invoking executor 'executor://mstestadapter/v2': Unable to find assembly 'External.Library.Name, Version=2.0.5.0, Culture=neutral, PublicKeyToken=null'.

The test will also halt execution; that is, if other tests are available in the app after this test, they will not run either.

## Environment

- Windows 10 x64
- Visual Studio 15.1 (26403.7); the bug was first seen in 26403.3

**Comment by ekumlin** [comment]
Just following up on this after a couple weeks.

Is this issue being actively triaged or worked on? Currently our only workaround for this is to run tests from the console instead of the IDE, which is a significant workflow change.

Thanks.

**Comment by smadala** [comment]
This issue was moved to Microsoft/testfx#180
