### ISSUE TITLE
Run All should not discover tests if they are discovered (.net core)

### ISSUE THREAD

**Issue by codito** [Microsoft/vstest#77]
## Description

If the tests are already discovered and available in the test explorer. Run All should not discover them again.
## Steps to reproduce
- Create a new unit test project
- Add the 10k tests ([10KTests.zip](https://github.com/Microsoft/vstest/files/491550/10KTests.zip))
- Build the tests
- After the tests are discovered, Run All
## Expected behavior

Tests should directly run and results are displayed.
## Actual behavior

Tests are discovered again. This makes the user wait for two minutes (for the 10k tests project).
## Environment

VS: alm/25722.00
TestPlatform:  d9dbd28

**Comment by singhsarab** [comment]
dotnet/sdk#464 has been fixed. Verified. Closing this one.
