### ISSUE TITLE
Test run aborts instead of failing

### ISSUE THREAD

**Issue by sbaid** [Microsoft/vstest#771]
## Description
Test run Aborts instead of failing

## Steps to reproduce
https://github.com/sbaid/samples/tree/master/NetCoreCrashTest

## Expected behavior
test fails

## Actual behavior
test run aborts

## Environment
d15prerel latest build

**Comment by singhsarab** [comment]
@sbaid 
The crash is bound to happen, I am not sure if TP can do anything to prevent it.
Debug.Assert failure in NetCore throws DebugAssertException and fails fast. https://github.com/dotnet/coreclr/blob/d8250b52fc596cc9c13d6abbc5aa85dd1440b0d9/src/mscorlib/src/System/Diagnostics/Debug.Windows.cs

This can be reproed via a console app or even directly writing this code in the test.

**Comment by codito** [comment]
Closing this since this is a non issue.
