### ISSUE TITLE
Run tests on published test project

### ISSUE THREAD

**Issue by damienpontifex** [Microsoft/vstest#775]
## Description
I'm trying to publish tests and then run them in the Release stage using VSTS Release Management. I would like to copy over the test project publish output to run in the release pipeline.

My project is:
```xml
<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>netcoreapp1.1</TargetFramework>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Microsoft.NET.Test.Sdk" Version="15.0.0" />
    <PackageReference Include="xunit" Version="2.2.0" />
    <PackageReference Include="xunit.runner.visualstudio" Version="2.2.0" />
  </ItemGroup>
</Project>
```

## Steps to reproduce

Steps with the dotnet cli are:
```cmd
dotnet new xunit
dotnet restore
dotnet publish -c Release -o test-output
cd test-output
dotnet .\my-test-project.dll
```
The result of this just returns with no output

Steps with VSTest.console.exe:
```cmd
dotnet new xunit
dotnet restore
dotnet publish -c Release -o test-output
cd test-output
VSTest.Console.exe /UseVsizExtensions:true /logger:trx /TestAdapterPath:. my-test-project.dll
```
The result of this is the warning: "Warning: No test is available in my-test-project.dll. Make sure that installed test discoverers & executors, platform & framework version settings are appropriate and try again."

> What steps can reproduce the defect?
> Please share the setup, commandline for vstest.console, sample project, target
> framework etc.

## Expected behavior
Test a published dll that contains XUnit `Fact` definitions just from the dll. 

It would seem at this stage I need to publish the whole folder with the csproj and source and then restore, and test from Release Management?

## Actual behavior
Errors or no results

## Environment
1. Windows 10, VS2017 (latest with updates)
2. VSTS Hosted 2017 build images

**Comment by codito** [comment]
@damienpontifex can you please try the `dotnet vstest` command?

```
dotnet new xunit
dotnet restore
dotnet publish -c Release -o test-output
cd test-output
dotnet vstest .\my-test-project.dll
```

**Comment by damienpontifex** [comment]
Thanks @codito that did it. Will close.

Out of interest, is this command different from VSTest.console.exe that is used by the Test task in VSTS or from the VS dev command line in windows?
