### ISSUE TITLE
No tests discovered

### ISSUE THREAD

**Issue by aggieben** [Microsoft/vstest#780]
## Description
I converted a project to the new .csproj format recently as a part of an effort to port to .NET Core, and after I did that and got everything building, the vstest runner stopped being able to find tests in the project.  The strangest thing to me is that I can run individual tests in VS2017, but when I try to run with "Run all tests", the runner fails to find any.

The Xunit runner _does_ work, however.  When I run `dotnet xunit`, it finds all the tests and I get the expected behavior.

## Steps to reproduce
I'm not entirely sure what I did to get in this state, but the project is accessible here: 
https://github.com/aggieben/dbup/tree/release/4.0.0

Access is open.  Please `git clone https://github.com/aggieben/dbup; cd dbup; git checkout release/4.0.0` to get the project(s) in question.

## Expected behavior
VS2017 test runner should show discovered tests in test explorer, and when "run all tests" is selected, it should run the tests.  Similarly, `dotnet test` should execute all the tests for both targets (`netcoreapp1.0` and `net46`).

As mentioned above, the Xunit runner does produce the expected results.

## Actual behavior
When running with `dotnet test`, this is the output:

```
C:\Users\ben\proj\oss\DbUp\src\dbup-tests [release/4.0.0 ≡]
λ dotnet test
Build started, please wait...
Engine\SqlScript.cs(15,33): warning CS0169: The field 'SqlScript.name' is never used [C:\Users\ben\proj\oss\DbUp\src\dbup-core\dbup-core.csproj]
Engine\SqlScript.cs(15,33): warning CS0169: The field 'SqlScript.name' is never used [C:\Users\ben\proj\oss\DbUp\src\dbup-core\dbup-core.csproj]
Helpers\NullJournalTests.cs(21,33): warning CS0618: 'SqlServerExtensions.SqlDatabase(SupportedDatabases, Func<IDbConnection>, string)' is obsolete: 'Pass connection string instead, then use .WithTransaction() and .WithTransactionPerScript() to manage connection behaviour' [C:\Users\ben\proj\oss\DbUp\src\dbup-tests\dbup-tests.csproj]
DeployChangesBuilderTests.cs(21,33): warning CS0618: 'SqlServerExtensions.SqlDatabase(SupportedDatabases, Func<IDbConnection>, string)' is obsolete: 'Pass connection string instead, then use .WithTransaction() and .WithTransactionPerScript() to manage connection behaviour' [C:\Users\ben\proj\oss\DbUp\src\dbup-tests\dbup-tests.csproj]
DeployChangesBuilderTests.cs(41,33): warning CS0618: 'SqlServerExtensions.SqlDatabase(SupportedDatabases, Func<IDbConnection>)' is obsolete: 'Pass connection string instead, then use .WithTransaction() and .WithTransactionPerScript() to manage connection behaviour' [C:\Users\ben\proj\oss\DbUp\src\dbup-tests\dbup-tests.csproj]
DeployChangesBuilderTests.cs(61,33): warning CS0618: 'SqlServerExtensions.SqlDatabase(SupportedDatabases, Func<IDbConnection>)' is obsolete: 'Pass connection string instead, then use .WithTransaction() and .WithTransactionPerScript() to manage connection behaviour' [C:\Users\ben\proj\oss\DbUp\src\dbup-tests\dbup-tests.csproj]
DeployChangesBuilderTests.cs(84,37): warning CS0618: 'SqlServerExtensions.SqlDatabase(SupportedDatabases, Func<IDbConnection>)' is obsolete: 'Pass connection string instead, then use .WithTransaction() and .WithTransactionPerScript() to manage connection behaviour' [C:\Users\ben\proj\oss\DbUp\src\dbup-tests\dbup-tests.csproj]
Build completed.

Test run for C:\Users\ben\proj\oss\DbUp\src\dbup-tests\bin\x64\Debug\netcoreapp1.0\dbup-tests.dll(.NETCoreApp,Version=v1.0)
Microsoft (R) Test Execution Command Line Tool Version 15.0.0.0
Copyright (c) Microsoft Corporation.  All rights reserved.

Starting test execution, please wait...
No test is available in C:\Users\ben\proj\oss\DbUp\src\dbup-tests\bin\x64\Debug\netcoreapp1.0\dbup-tests.dll. Make sure that installed test discoverers & executors, platform & framework version settings are appropriate and try again.



Test run for C:\Users\ben\proj\oss\DbUp\src\dbup-tests\bin\x64\Debug\net46\dbup-tests.dll(.NETFramework,Version=v4.6)
Microsoft (R) Test Execution Command Line Tool Version 15.0.0.0
Copyright (c) Microsoft Corporation.  All rights reserved.

Starting test execution, please wait...
[xUnit.net 00:00:00.9516916]   Discovering: dbup-tests
[xUnit.net 00:00:01.2040971]   Discovered:  dbup-tests
[xUnit.net 00:00:01.2348628] dbup-tests: Catastrophic failure: System.ArgumentException: An item with the same key has already been added.
   at System.ThrowHelper.ThrowArgumentException(ExceptionResource resource)
   at System.Collections.Generic.Dictionary`2.Insert(TKey key, TValue value, Boolean add)
   at Xunit.Runner.VisualStudio.TestAdapter.VsTestRunner.RunTestsInAssembly(IRunContext runContext, IFrameworkHandle frameworkHandle, LoggerHelper logger, TestPlatformContext testPlatformContext, IMessageSinkWithTypes reporterMessageHandler, AssemblyRunInfo runInfo)
No test is available in C:\Users\ben\proj\oss\DbUp\src\dbup-tests\bin\x64\Debug\net46\dbup-tests.dll. Make sure that installed test discoverers & executors, platform & framework version settings are appropriate and try again.
```

## Environment
```
C:\Users\ben\proj\oss\DbUp\src\dbup-tests [release/4.0.0 ≡]
λ dotnet --info
.NET Command Line Tools (1.0.3)

Product Information:
 Version:            1.0.3
 Commit SHA-1 hash:  37224c9917

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.15063
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\1.0.3
```

Test runner-related packages from the `.csproj`:

```
<ItemGroup>
    <PackageReference Include="Microsoft.NET.Test.Sdk" Version="15.0.0-preview-20170106-08" />
    <PackageReference Include="xunit" Version="2.3.0-beta1-build3642" />
    <PackageReference Include="xunit.runner.visualstudio" Version="2.3.0-beta1-build1309" />
    <PackageReference Include="Shouldly" Version="2.8.1" />
    <PackageReference Include="TestStack.BDDfy" Version="4.3.1" />
    <!--<PackageReference Include="xunit.core" Version="2.2.0-beta2-build3300" />-->
    <DotNetCliToolReference Include="dotnet-xunit" Version="2.3.0-beta1-build3642"/>
  </ItemGroup>
```

**Comment by bradwilson** [comment]
This looks likely to be a bug in xUnit.net, not VSTest. There is a dictionary in our VS adapter which maps unique IDs to test cases that is probably being tripped up here. The question will be to figure out how you ended up with two test cases with the same unique ID,

**Comment by aggieben** [comment]
I see that from the output of the runner against the `net46` target output, but do you think that's the case for the `netcoreapp1.0` target as well?

**Comment by bradwilson** [comment]
Until I can poke around inside and see what's going on, I don't know. It could be that VSTest is handling the two scenarios differently (hiding the bug in one, exposing it in the other, but not running any tests in either case).

**Comment by Faizan2304** [comment]
@aggieben Please use latest version of package `Microsoft.NET.Test.Sdk` which is `15.3.0-preview-20170502-03`
`<PackageReference Include="Microsoft.NET.Test.Sdk" Version="15.3.0-preview-20170502-03" />`

With new package you will see that error message which adapter is sending is coming to console.

with latest version you will get following output:
```
PS C:\Enlistment\Customer\dbup\src\dbup-tests> dotnet test
Build started, please wait...
Build completed.

Test run for C:\Enlistment\Customer\dbup\src\dbup-tests\bin\Debug\netcoreapp1.0\dbup-tests.dll(.NETCoreApp,Version=v1.0)
Microsoft (R) Test Execution Command Line Tool Version 15.3.0-preview-20170502-03
Copyright (c) Microsoft Corporation.  All rights reserved.

Starting test execution, please wait...
[xUnit.net 00:00:01.7501199]   Discovering: dbup-tests
[xUnit.net 00:00:02.1956541]   Discovered:  dbup-tests
[xUnit.net 00:00:02.3184782] dbup-tests: Catastrophic failure: System.ArgumentException: An item with the same key has already been added. Key: 9b4bc40fde591750f3097c5f4b22a610ad581cda
   at System.ThrowHelper.ThrowAddingDuplicateWithKeyArgumentException(Object key)
   at System.Collections.Generic.Dictionary`2.Insert(TKey key, TValue value, Boolean add)
   at Xunit.Runner.VisualStudio.TestAdapter.VsTestRunner.RunTestsInAssembly(IRunContext runContext, IFrameworkHandle frameworkHandle, LoggerHelper logger, TestPlatformContext testPlatformContext, IMessageSinkWithTypes reporterMessageHandler, AssemblyRunInfo runInfo)
No test is available in C:\Enlistment\Customer\dbup\src\dbup-tests\bin\Debug\netcoreapp1.0\dbup-tests.dll. Make sure that test discoverer & executors are registered and platform & framework version settings are appropriate and try again.

Test run for C:\Enlistment\Customer\dbup\src\dbup-tests\bin\Debug\net46\dbup-tests.dll(.NETFramework,Version=v4.6)
Microsoft (R) Test Execution Command Line Tool Version 15.3.0-preview-20170502-03
Copyright (c) Microsoft Corporation.  All rights reserved.

Starting test execution, please wait...
[xUnit.net 00:00:00.9311691]   Discovering: dbup-tests
[xUnit.net 00:00:01.2564212]   Discovered:  dbup-tests
[xUnit.net 00:00:01.3457598] dbup-tests: Catastrophic failure: System.ArgumentException: An item with the same key has already been added.
   at System.ThrowHelper.ThrowArgumentException(ExceptionResource resource)
   at System.Collections.Generic.Dictionary`2.Insert(TKey key, TValue value, Boolean add)
   at System.Collections.Generic.Dictionary`2.Add(TKey key, TValue value)
   at Xunit.Runner.VisualStudio.TestAdapter.VsTestRunner.RunTestsInAssembly(IRunContext runContext, IFrameworkHandle frameworkHandle, LoggerHelper logger, TestPlatformContext testPlatformContext, IMessageSinkWithTypes reporterMessageHandler, AssemblyRunInfo runInfo)
No test is available in C:\Enlistment\Customer\dbup\src\dbup-tests\bin\Debug\net46\dbup-tests.dll. Make sure that test discoverer & executors are registered and platform & framework version settings are appropriate and try again.
```

**Comment by Faizan2304** [comment]
Only run all scenario ( From both commandline and visual studio) is busted here. 
I am closing this bug as this is a bug in xunit adapter and @bradwilson is tracking it in xunit repo.

**Comment by MarkHerhold** [comment]
I am running into this exact issue except I am using the latest versions of everything. Is this still an outstanding issue with `xunit` or was it determined to be `vstest`?

**Comment by smadala** [comment]
@MarkHerhold Issue was determined as xunit adapter's.  Can you share repro project, logs(https://github.com/Microsoft/vstest-docs/blob/master/docs/diagnose.md) and explicitly provide the versions of (dotnet --info, VS, xunit and Microsoft.NET.Test.Sdk)?

**Comment by MarkHerhold** [comment]
@smadala The strange thing is that the tests work just fine when run from VS Community Edition. Luckily, the project is open source and brand new, so that should make things simple.

- Locally, I'm running VS Community Edition 2017 v14.4.5 (new install) with .NET Framework v4.7.02556 (came with new VS install).
- xunit v2.3.1 [defined here](https://github.com/BadgeUp/badgeup-dotnet-client/blob/d177a24c9527dc2eca9a053be4a960781cfc011d/BadgeUpClient.Tests/BadgeUpClient.Tests.csproj#L9)
- Microsoft.NET.Test.Sdk v15.5.0 [defined here](https://github.com/BadgeUp/badgeup-dotnet-client/blob/d177a24c9527dc2eca9a053be4a960781cfc011d/BadgeUpClient.Tests/BadgeUpClient.Tests.csproj#L7)

## `dotnet --info` (local)

```
PS D:\badgeup-dotnet-core-client> dotnet --info
.NET Command Line Tools (2.0.3)

Product Information:
 Version:            2.0.3
 Commit SHA-1 hash:  12f0c7efcc

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.16299
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\2.0.3\

Microsoft .NET Core Shared Framework Host

  Version  : 2.0.3
  Build    : a9190d4a75f4a982ae4b4fa8d1a24526566c69df
```

I also have the project running in [AppVeyor](https://ci.appveyor.com/project/MarkHerhold/badgeup-dotnet-core-client) with the same failures. Here's a [link to the repo](https://github.com/BadgeUp/badgeup-dotnet-client).

**Comment by smadala** [comment]
@MarkHerhold I couldn't repro it. See the below image. Share all log.*.txt files. 
![vstest_xunit_exception](https://user-images.githubusercontent.com/4337332/33537394-50a84e74-d8e1-11e7-9f3e-14973fd5c809.PNG)

**Comment by MarkHerhold** [comment]
@smadala I see one thing you did differently is you CC'd to the Test project directory. Could you try running the tests at the directory above that?

**Comment by smadala** [comment]
Running tests for `sln`, not yet supported from vstest(https://github.com/Microsoft/vstest/issues/1129). I tried running from above directory. See the below image. Did you face issue with `dotnet test \path\to\BadgeUpClient.Tests.csproj`, If so share log.txt and log.host.*.txt too.
![vstest_xunit_exception_2](https://user-images.githubusercontent.com/4337332/33562226-c4b9014c-d93a-11e7-9572-15537734f7f8.PNG)

**Comment by MarkHerhold** [comment]
@smadala Ah, that's the issue! Thanks so much for your help! 😀
