### ISSUE TITLE
Stackoverflow in test method causes "dotnet test" hanging in release configuration for .Net core 

### ISSUE THREAD

**Issue by smadala** [Microsoft/vstest#784]
## Description
- dotnet test is hanging in release configuration if test method throws StackOverflowException in .Net core test project.

## Steps to reproduce
- run `dotnet new mstest`
- Cahnge content of UnitTest.cs to following:
```cs
using Microsoft.VisualStudio.TestTools.UnitTesting;

namespace rel_sof
{
    [TestClass]
    public class UnitTest1
    {
        [TestMethod]
        public void TestMethod1()
        {
          TestMethod1();
        }
    }
}

``` 
- dotnet restore
- dotnet test -c release
> framework: .net core (netcoreapp1.0, netcoreapp2.0)

## Expected behavior
> The active test run was aborted. Reason: Process is terminating due to StackOverflowException.

## Actual behavior
> `dotnet test` commnad never completes.

## Environment
- dotnet --info
.NET Command Line Tools (2.0.0-preview1-005945)

Product Information:
 Version:            2.0.0-preview1-005945
 Commit SHA-1 hash:  7f414b0666

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.14393
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Users\samadala\Downloads\dotnet-dev-win-x64.latest (1)\sdk\2.0.0-preview1-005945\

Microsoft .NET Core Shared Framework Host

  Version  : 2.0.0-preview1-002106-00
  Build    : 86fe9816c8ba782241c441c3228c665e393c3ef3

**Comment by Faizan2304** [comment]
### What is the issue:
for configuration `release` the compiler is doing some magic and  the method TestMethod1() keep calling itself recursively without throwing `StackOverflowException` exception. As a result of this TestHost never get `StackOverflowException` and hence test keep running.

This is getting repro for console application as well for code
``` cSharp
using System;
namespace console
{
    class Program
    {
        static void Main(string[] args)
        {
            Console.WriteLine("Hello World!");
	    Recurse();
        }
	public static void Recurse()
	{
	    Recurse();
	}
    }
}

```

The above code keep executing without throwing `StackOverflowException` exception.

**Comment by Faizan2304** [comment]
Closing this bug as this is not the bug in vstest but the way dotnet behave.
