### ISSUE TITLE
Cannot pass parameters to underlying test runner

### ISSUE THREAD

**Issue by StrangeWill** [Microsoft/vstest#786]
## Description
Summarized in https://github.com/dotnet/cli/issues/3114. Basically runners like Xunit have the ability to change behavior based on command line parameters, this is a _must have_ and worked before the move to VSTest.

This used to be accomplished by passing in the args after a double hypen, eg:

`dotnet test myproj.csproj -- -teamcity -xml myfile.xml`

## Steps to reproduce
1) Try to pass parameters to any VSTest enabled XUnit project, (eg: `-teamcity`, or `-xml output.xml`).

## Expected behavior
XUnit to receive parameters passed after the double hyphen.

## Actual behavior
Everything after the double hyphen is ignored.

## Environment
Happens on all environments.

**Comment by codito** [comment]
@StrangeWill with the move to vstest, the adapters do get these parameters as run settings. I am not sure if xunit adapter understands these parameters and provides the functionality.

From your example, it looks like the scenario is to produce xunit xml results and enable teamcity integration. It is possible to achieve this using following logger extensions:
https://github.com/Faizan2304/LoggerExtensions
https://github.com/JetBrains/TeamCity.VSTest.TestAdapter

**Comment by StrangeWill** [comment]
I guess due to the backwards-compatible breaking changes made they opted to use their own build command as of 2.3 to get off the dependency of VSTest and any further disruption to the platform:

https://github.com/xunit/xunit/issues/1154#issuecomment-295184454
https://xunit.github.io/docs/getting-started-dotnet-core

Is there a reason that VSTest broke this established syntax?

**Comment by codito** [comment]
One of the guiding principles for vstest is to provide an uniform user experience (across CLI, IDE/Editors, CI) to run tests irrespective of the test frameworks used, and provide great extensibility for developers (e.g. adapters, loggers etc.). We're evolving the platform towards that. This comment also summarizes the thought process: https://github.com/dotnet/cli/issues/4921#issuecomment-265051207.

**Comment by bradwilson** [comment]
We (@xunit) have always viewed VSTest as a way to get integration with Visual Studio. The availability of `vstest.console.exe` in desktop CLR and `dotnet test` (or `dotnet vstest`) in .NET Core is a down-level experience, a common denominator runner platform that does not offer xUnit.net-specific features. For that, we have `xunit.console.exe` for desktop CLR and `dotnet xunit` in .NET Core. These things aren't mutually exclusive; they simply serve different purposes.

FYI: Since test adapters that write to VSTest are easier to automate, they're also easier to consume by other third party runners which are also looking to provide a common denominator runner platform (for example, Resharper or VS Code).

**Comment by StrangeWill** [comment]
@bradwilson yeah just noticed that the new beta has `dotnet xunit` functionality, which I know has been talked about since .NET Core dropped the ability to pass parameters onto `xunit.console.exe` prior to the VSTest changes.

This comment: https://github.com/dotnet/cli/issues/4921#issuecomment-281677977 suggests that's probably have 3rd party testing frameworks will work entirely moving forward anyway. So I'll just pull all the bleeding-edge stuff for xunit and rework my CI around the new functionality.

>FYI: Since test adapters that write to VSTest are easier to automate

Funny enough due to this change the _only_ thing that has broken is automation, specifically with static code analysis platforms being as they're no longer receiving the expected Xunit output from the CLI (and trx reports are no good).

**Comment by bradwilson** [comment]
I meant automation from a code perspective (i.e., using our VSTest adapter as an API that they can program against, by simulating the Visual Studio APIs themselves). 😉

**Comment by StrangeWill** [comment]
Guess I'm going to close it with these notes:

VSTest is primarily to create a unified API for communicating with test runners, this relies on runsettings for any specific configuration for the test runners (and support for such). This exposes 3rd party testing frameworks to tools like Resharper and whatnot easily.

Libraries like xUnit are putting out their _own_ test runners so that they can expose their own _specific_ tooling behaviors. This will probably be best for CI setups. While this issue has made upgrading our projects to 1.1 frustrating it looks like xUnit has been hard at work at resolving it.

I guess the most aggravating part for most of us is breaking the CLI out of the gate from commands that worked fine in the 1.0 release and us being a little high and dry for a few months but I guess the issue is coming to a close anyway.

**Comment by bradwilson** [comment]
Unfortunately, it took me some time to get `dotnet xunit` working the way I wanted it to, which left us in this in-between state for a while. The beta releases of xUnit.net are generally speaking very stable, and you should feel comfortable using the beta runners in CI scenarios (I have personally used almost exclusively beta builds for the last 10 years, on primarily large codebases (including CodePlex and ASP.NET MVC/Web API). On the rare occasions that issues are discovered in beta builds, we almost always immediately fix them and offer new builds right away.

**Comment by StrangeWill** [comment]
Yeah I had been on beta xunit for awhile before 2.2 hit stable, it was always good to me, I just didn't check for a beta again because I didn't even know that 2.3 was in the works or what was coming with it.

Thanks for the work on Xunit though. 👍

**Comment by ChrisProlls** [comment]
I faced with this issue today. Any news about it ? Is there any version that fix this ?
Thanks !

**Comment by codito** [comment]
@ChrisProlls there's a xunit logger for `dotnet test` available here: https://github.com/Faizan2304/LoggerExtensions. More information on loggers (teamcity etc.) are documented here: https://github.com/Microsoft/vstest-docs/blob/master/docs/report.md.

Pre 1.0 dotnet-cli versions used to support passing args to the underlying test runners directly. This is no longer the case with 1.0 and later versions. Current architecture is a single runner with adapters for variety of test frameworks. It supports configuring the test framework specific configuration with a run settings (which can be configured from command line as well). The reporting aspects are configured directly with the runner (independent of the test framework adapter).
