### ISSUE TITLE
.NET Core Console App & Class Library projects not detecting tests

### ISSUE THREAD

**Issue by vsccarl** [Microsoft/vstest#790]
## Description
Adding xunit or mstest tests to a .NET Core Console app or Class Library are not being detected by Test Explorer

## Steps to reproduce
1. Create a new .NET Core Console App
2. Add Xunit and Xunit.runner.visualstudio NuGet packages to the project.
3. Add a test to the project
4. Open Test Explorer and select Run All

## Expected behavior
Tests in the project should be shown in Test Explorer

## Actual behavior
![image](https://cloud.githubusercontent.com/assets/12900364/25825231/21494208-33f7-11e7-8a51-8c9519ef545e.png)

## Environment
Windows 10, latest build from vsuml branch

**Comment by codito** [comment]
@vsccarl the test projects for .net core should target an app runtime (netcoreX.Y) and include `Microsoft.NET.Test.Sdk` package, it will bring the test host dependency used to discover/execute tests.

**Comment by vsccarl** [comment]
@codito adding the package causes an error when building:

```
Error	CS0017	Program has more than one entry point defined. Compile with /main to specify the type that contains the entry point.	ConsoleApp8	c:\users\v-sccarl\documents\visual studio 2017\Projects\ConsoleApp8\ConsoleApp8\Program.cs	7	Active
```
Looking in the project properties, I can't set/select any other entry points.

**Comment by smadala** [comment]
@vsccarl .Net core test projects are console apps. `Microsoft.NET.Test.Sdk` has a target which creates auto generated entry point [here](https://github.com/Microsoft/vstest/blob/333752b3009468ceffe02238df948609019bce5c/src/package/nuspec/Microsoft.NET.Test.Sdk.targets#L66). You can't have any other entry point in your project when you add `Microsoft.NET.Test.Sdk`.
