### ISSUE TITLE
the default Output type should be Class Library for both mstest and xunit

### ISSUE THREAD

**Issue by MiaomiaoHuangfu** [Microsoft/vstest#791]
## Description
> 

- the Output type of UnitTest (.NET Core) and xunit (.NET Core) project are both Class Library, but give "Console Application". It failed to update the output type.

## Steps to reproduce
> 
- Create a Unit Test Project (.NET Core) or xUnit Test Project (.Net Core);
- Right click the project and click "properties", the default Output type is "Console Application", which should be "Class Library".
- Change the Output value from "Console Application" to "Class Library".
- Click the "Save" icon;
- Close the "Properties";
- Reopen the "Properties" page

## Expected behavior
> 
- the default Output type should be Class Library for both mstest and xunit. 
- Changing the value of output type should keep the updated value

## Actual behavior
>  
- Tdefault Output type for both mstest and xunit are "Console Application";
- Change the value of output type, it will reverse to the previous value and cannot keep the updated value.
![wrongoutputformstestxunit](https://cloud.githubusercontent.com/assets/22901391/25840618/0870b6b6-34cf-11e7-9aa1-d9e5642aacdf.png)
## Environment
> 
- OS: Windows 10 X64; 
- Test on d15rel.26507.00
- VS: VS 2017 d15rel Version 15.3 (26507.0-Preview) d15rel d15rel
- vstest.console: 15.0.26504.0

**Comment by smadala** [comment]
@MiaomiaoHuangfu Thanks for reporting issue.
.Net core unit test project suppose to be Console application as per discussion [here](https://github.com/dotnet/sdk/issues/201). `Microsoft.NET.Test.Sdk` package makes sure the same.

**Comment by xwu-ndsc** [comment]
Change the project output type from 'Console' to 'Library' did cause one change on the .csproj file.  It introduced three extra properties in the PropertyGroup which will not get  removed even after the Output Type on project Application property tab get reset back to Console.

![image](https://user-images.githubusercontent.com/77012477/108727210-edc34280-74ed-11eb-99b2-378574fe8dcb.png)
