### ISSUE TITLE
Cannot easily launch the feature for debugging

### ISSUE THREAD

**Issue by sharwell** [Microsoft/vstest#798]
## Description

It is not currently possible to "clone and go" with this repository.

## Steps to reproduce

1. Clone the repository
1. Open **TestPlatform.sln**
1. Right click on a project and select **Set as StartUp Project**
1. Press <kbd>F5</kbd> (Debug &rarr; Start Debugging)

## Expected behavior

The solution builds, and an experimental instance of Visual Studio 2017 opens with the new local build of the test platform installed and enabled.

## Actual behavior

There is no such project in the solution.

## Environment

Windows 10, Visual Studio 2017 15.1

**Comment by codito** [comment]
The vsix project today doesn't include project references to other product projects (they are all multi targeted, and don't play nice with project references in a vsix). This definitely makes getting started harder.

It is possible to generate a vsix in command line:
```
> build
> ls artifacts\Debug\VSIX\TestPlatform.vsix
```

It can be installed into any VS instance.

**Comment by pvlakshm** [comment]
Closing this; reactive is still necessary.

**Comment by sharwell** [comment]
@pvlakshm I don't understand?
