### ISSUE TITLE
Include stack traces into Error messages

### ISSUE THREAD

**Issue by DavidKarlas** [Microsoft/vstest#804]
## Description
In case TestAdaptor crashes all host gets is error message without stacktrace example:  https://github.com/Microsoft/vstest/blob/5f5e5ce/src/Microsoft.TestPlatform.CrossPlatEngine/Discovery/DiscovererEnumerator.cs#L142-L148
What I had to do is connect with debugger to figure out what happens, could be more annoying if only customer could reproduce problem.

If you disagree with me, no problem close issue, just wanted to raise issue...

## Steps to reproduce
Make TestAdapter crash somehow and not get StackTrace

## Expected behavior
See StackTrace

## Actual behavior
No StackTrace

## Environment
Nothing special

**Comment by smadala** [comment]
@DavidKarlas Thanks for raising issue.
We can get Sacktrace from /diag:log.txt option which creates `log.*.host.txt` file. The `log.*.host` contains the stacktrace.
Yeah, We should show the StackTrace directly on console. Please feel free to raise the PR for it. (by changing e.Message to e.ToString() in all usages).

**Comment by DavidKarlas** [comment]
You are probably correct about I should use `/diag:log.txt`, hence closing
