### ISSUE TITLE
dotnet test: TypeInitializationException in PlatformEqtTrace

### ISSUE THREAD

**Issue by qmfrederik** [Microsoft/vstest#806]
## Description
I'm running dotnet test on .NET Core 2.0 Preview 1.

## Steps to reproduce

1. Make sure you've got .NET Core 2.0 Preview installed
2. Clone https://github.com/corecompat/system.drawing
3. Run the `.\clone-mono.ps1` script to make sure the project can build
4. Do dotnet restore of the solution
5. Run `dotnet test --filter "TestCategory != NotWorking" test/CoreCompat.System.Drawing.Tests/CoreCompat.System.Drawing.Tests.csproj`

You can see the CI output here:
https://travis-ci.org/CoreCompat/System.Drawing/builds/231595518
https://ci.appveyor.com/project/qmfrederik/system-drawing/build/1.0.128

## Expected behavior
Tests to run & test results to be displayed

## Actual behavior
An error occurs:

```
dotnet test --filter "TestCategory != NotWorking" test/CoreCompat.System.Drawing.Tests/CoreCompat.System.Drawing.Tests.csproj
Build started, please wait...
Build completed.
Test run for C:\projects\system-drawing\test\CoreCompat.System.Drawing.Tests\bin\Debug\netcoreapp2.0\CoreCompat.System.Drawing.Tests.dll(.NETCoreApp,Version=v2.0)
Microsoft (R) Test Execution Command Line Tool Version 15.3.0-preview-20170502-03
Copyright (c) Microsoft Corporation.  All rights reserved.
Starting test execution, please wait...
Testhost process exited with error: Unhandled Exception: System.TypeInitializationException: The type initializer for 'Microsoft.VisualStudio.TestPlatform.ObjectModel.PlatformEqtTrace' threw an exception. ---> System.TypeLoadException: Could not load type 'System.Threading.Monitor' from assembly 'System.Threading, Version=4.0.12.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'.
   at System.Diagnostics.TraceSource..ctor(String name, SourceLevels defaultLevel)
   at Microsoft.VisualStudio.TestPlatform.ObjectModel.PlatformEqtTrace..cctor()
   --- End of inner exception stack trace ---
   at Microsoft.VisualStudio.TestPlatform.ObjectModel.PlatformEqtTrace.ShouldTrace(PlatformTraceLevel traceLevel)
   at Microsoft.VisualStudio.TestPlatform.ObjectModel.EqtTrace.Error(String format, Object[] args)
   at Microsoft.VisualStudio.TestPlatform.TestHost.Program.Main(String[] args)
Command exited with code 1
```

## Environment
> Please share additional details about the test environment.

.NET Core 2.0 preview 1
Reproduces on both Windows & Linux (Travis & AppVeyor)

**Comment by Faizan2304** [comment]
@qmfrederik :
It seems like the culprit here is the content of csproj file `CoreCompat.System.Drawing.Tests.csproj `
 https://github.com/CoreCompat/System.Drawing/blob/master/test/CoreCompat.System.Drawing.Tests/CoreCompat.System.Drawing.Tests.csproj#L4 

Changing the csproj content from 
```xml
<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>netcoreapp2.0</TargetFramework>
    <TargetFrameworks>netcoreapp2.0;net462</TargetFrameworks>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>

    <IsPackable>false</IsPackable>
  </PropertyGroup>
```

To 

```xml
<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>netcoreapp2.0</TargetFramework>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>

    <IsPackable>false</IsPackable>
  </PropertyGroup>
```

is solving the problem.

Can you please change as mentioned above and try to run your test.

**Comment by qmfrederik** [comment]
@Faizan2304 Thanks I'll give that a try.

I'm a bit confused, though. I want to be able to run tests on both net462 and netstandard2.0; why would specifying mutiple TargetFrameworks be invalid?

**Comment by codito** [comment]
@qmfrederik these two lines below are conflicting.
```
    <TargetFramework>netcoreapp2.0</TargetFramework>
    <TargetFrameworks>netcoreapp2.0;net462</TargetFrameworks>
```

At a time, the project can have either `TargetFramework` where we're indicating this is a single targeted project, or it can have `TargetFrameworks` indicating `build` and `test` for multiple frameworks.

**Comment by Faizan2304** [comment]
@qmfrederik  I hope your issue has been resolved. I am closing the issue. Please revert back if you have any query.
