### ISSUE TITLE
executor holds on to dll after test run

### ISSUE THREAD

**Issue by jmarolf** [Microsoft/vstest#807]
## Description
Unable to build because vstest.executionengine.x86 holds on to dlls after test run completes

## Steps to reproduce
Right click on a test class and select "Debug Test" from the right click menu.

## Expected behavior
Project rebuilds and debugs test

## Actual behavior
Build fails because dlls cannot be copied

## Environment
dotnetcore 2.0 project
Visual Studio 2017.3 Preview1

**Comment by smadala** [comment]
Can you please share csproj, Theoretically `vstest.executionengine.x86` should not be involved in dotnetcore 2.0 project. I was unable to repro for net452 framework by following repro steps.
