### ISSUE TITLE
Code coverage should exclude auto generated entrypoint

### ISSUE THREAD

**Issue by codito** [Microsoft/vstest#813]
## Description
Code coverage for .net core projects is including `AutoGeneratedProgram` in coverage metrics. It should be excluded.

## Steps to reproduce
1. Use these instructions to run code coverage for .net core in test explorer: https://github.com/Microsoft/vstest-docs/blob/master/docs/analyze.md#working-with-code-coverage

## Expected behavior
Coverage includes user code only.

## Actual behavior
![image](https://cloud.githubusercontent.com/assets/28766/26091510/58179bd0-3a29-11e7-853c-ecd70d178e1d.png)

## Environment
VS 2017 15.3 Preview 1

**Comment by codito** [comment]
Might get fixed with #792 which will remove auto generated code from test projects.

**Comment by codito** [comment]
Adding all coverage impacting issues for 15.5.

**Comment by samsmithnz** [comment]
I just came across this today. I believe it's related to #519.

Does marking it as an enhancement mean it's not going to be fixed (this is typically what enhancement means at my organization :P)

**Comment by mayankbansal018** [comment]
CodeCoverage does not know that a certain code is autogenerated if it does not have "CompilerGenerate" Attribute on top of them.

This is by design

**Comment by peteri** [comment]
The code is autogenerated by the msbuild step in vstest/src/package/nuspec/Microsoft.NET.Test.Sdk.targets installed by the nuspec package so an attribute should either be added as part of the autogenerated file or the autogeneration should be removed.

**Comment by mayankbansal018** [comment]
@peteri reopening this issue. I'll take further look to understand why we need code, or how can we add the attribute

**Comment by peteri** [comment]
[This issue](https://github.com/dotnet/roslyn/issues/16856) added the comments so style cop ignores it, I suspect that it probably just needs the attribute adding.

The other comments on the roslyn issue seem to suggest the autogenerated program.cs is still needed.

**Comment by samsmithnz** [comment]
It should have the GeneratedCodeAttribute attribute, not CompilerGeneratedAttribute though, right? Reference: https://blogs.msdn.microsoft.com/codeanalysis/2007/04/27/correct-usage-of-the-compilergeneratedattribute-and-the-generatedcodeattribute/

**Comment by mayankbansal018** [comment]
@samsmithnz , thanks for bringing it up. I agree it should be GenerateCodeAttribute, we plan to resolve this in next release to Test Platform.,

**Comment by gingters** [comment]
@mayankbansal018 Any further infos on that?

**Comment by mayankbansal018** [comment]
@gingters I've raised required PR's for this issue. We are hoping to resolve this in 15.6 RTM

**Comment by mayankbansal018** [comment]
@gingters, For VS IDE we missed the deadline for 2017 update 6, this will get fixed in update 7
However, it is fixed for vstest xcopy nuget package that we ship

**Comment by mayankbansal018** [comment]
fixed in latest Microsoft.Net.Test.SDK(15.8) VS 2017

**Comment by juniormayhe** [comment]
I think msbuild (or whatever visual studio 2019 uses) is not excluding from code coverage auto generated programs. 

I was expecting to test project produces: 
```
// <auto-generated> This file has been auto generated. </auto-generated>
using System;
[System.Diagnostics.CodeAnalysis.ExcludeFromCodeCoverage]
[Microsoft.VisualStudio.TestPlatform.TestSDKAutoGeneratedCode]
class AutoGeneratedProgram {static void Main(string[] args){}}
```

but I got:

```
// <auto-generated> This file has been auto generated. </auto-generated>
using System;
[Microsoft.VisualStudio.TestPlatform.TestSDKAutoGeneratedCode]
class AutoGeneratedProgram {static void Main(string[] args){}}
```

is it possible to excluded from code coverage test project autogenerated (Program) files? Code Metrics results keeps on showing these files with 0% code coverage.
