### ISSUE TITLE
Namespace Microsoft.VisualStudio.TestPlatform.Client not exists in nuget package Microsoft.NET.Test.Sdk 

### ISSUE THREAD

**Issue by VanKrock** [Microsoft/vstest#815]
Namespace Microsoft.VisualStudio.TestPlatform.Client not exists in nuget package Microsoft.NET.Test.Sdk last version 15.3.0-preview-20170502-03
How can I get Microsoft.VisualStudio.TestPlatform.Client? Or how can I create instance of ITestPlatform?

**Comment by Faizan2304** [comment]
@VanKrock Nuget package Microsoft.NET.Test.Sdk doesn't have assembly which has ITestPlatform interfaces. It has all the things which is needed at the time of building and running test project project.

Can you please let us know how are you going to use ITestPlatform. This is not supposed to be get user outside out test engine. 
If you are looking for a programmatic way to run tests then use translation layer [docs here](https://github.com/Microsoft/vstest-docs/blob/master/RFCs/0008-TranslationLayer.md)

**Comment by VanKrock** [comment]
@Faizan2304 I want to run my tests programmatically for example on rest request. I want to create web api service for manage testRuns on remote desktops. Microsoft.TestPlatform.Client seemd to me the best solution. I can do this using console wrappers such as sample, but Microsoft.TestPlatform.Client seems better for my tasks.

**Comment by Faizan2304** [comment]
@VanKrock : Console wrapper (Translation layer) is the suggested way to go hear. We don't expose ITestPlatform  to outside world. I hope translation layer will fulfill all your requirement.
