### ISSUE TITLE
Cleanup windows specific code for net46

### ISSUE THREAD

**Issue by singhsarab** [Microsoft/vstest#820]
## Description
> There is bunch of code for Net46 that is specific to windows. It should be made platform neutral.
1. https://github.com/Microsoft/vstest/blob/master/src/Microsoft.TestPlatform.ObjectModel/Navigation/DiaSession.cs#L50
2. https://github.com/Microsoft/vstest/blob/master/src/Microsoft.TestPlatform.ObjectModel/Utilities/XmlRunSettingsUtilities.cs#L44
3.	https://github.com/Microsoft/vstest/blob/master/src/Microsoft.TestPlatform.CoreUtilities/Helpers/DotnetHostHelper.cs#L45

## Environment
> OS: MAC, Framework: Net46

**Comment by yaakov-h** [comment]
For #3, shouldn't we use `System.IO.Path.PathSeparator`?

**Comment by codito** [comment]
@yaakov-h :+1: fixed in #851
