### ISSUE TITLE
Tool tips do not match display text for tests

### ISSUE THREAD

**Issue by sharwell** [Microsoft/vstest#822]
## Description

When working with a `[Theory]` test in xUnit, the tool tip shown for the test(s) in Test Explorer do not match the text printed for the name. Here is an example from Microsoft/perfview#222.

![image](https://cloud.githubusercontent.com/assets/1408396/26188730/84405cd6-3b66-11e7-8027-fe7af0d01c33.png)

## Steps to reproduce

1. Add a `[Theory]` test with `[InlineData]`

    ```csharp
    namespace Microsoft.Diagnostics.Tracing.Analysis.Example
    {
      public class MyTestClass
      {
        [Theory]
        [InlineData("Name")]
        public void MyTheory(string value)
        {
        }
      }
    }
    ```

2. Build the project and wait for tests to show in Test Explorer

3. Locate the new test

4. Make the Test Explorer window wider in hopes of seeing the full name of the test

5. Since the Test Explorer window responded in the previous step by placing the output to the right of the test names instead of below, again make the test window wider so you can *actually* see the full name of the test

## Expected behavior

1. Test explorer shows the test as the following:

    > Microsoft.Diagnostics.Tracing.Analysis.Example.MyTestClass.MyTheory(value: "Name")

2. The tool tip for the test is the same as the display name

## Actual behavior

1. The display name for the test shows correctly.
2. The tool tip shows a meaningless number instead of the test arguments.

## Environment

Visual Studio 2017 (15.2), Windows 10, XUnit 2.2.0

**Comment by snkota** [comment]
This is being tracked external to this repo, here: 
https://developercommunity.visualstudio.com/content/problem/145928/tool-tips-do-not-match-display-text-for-tests.html

**Comment by stijnherreman** [comment]
@snkota There's also the linked xunit/xunit#1454 and https://developercommunity.visualstudio.com/content/problem/113694/the-tooltip-of-a-test-in-the-test-explorer-should.html
