### ISSUE TITLE
[Question] appx test discovery not working with self-compiled vstest.console.exe

### ISSUE THREAD

**Issue by marc-mueller** [Microsoft/vstest#825]
## Description
> We are currently investigating the tcp communication between the vstest.console.exe and the UnitTestClient in an appx unit test package. Therefore we wanted to change the socket binding to accept calls from a different execution host. Currently we are not able to run appx unit tests locally with the compiled master branch.

## Steps to reproduce
> Checkout master branch
> Run build.cmd
> Execute tests ````vstest.console.exe <pathtoappx>\myappxunittests.appx```

## Expected behavior
> We are expecting that the tests is run the same way as the released version of vstest.console.exe

## Actual behavior
```
...
Starting test execution, please wait...
No test is available in C:\Temp\UWPPlayground\UnitTestProject1\AppPackages\UnitTestProject1_1.0.0.0_x86_Debug_Test\UnitTestProject1_1.0.0.0_x86_Debug.appx. Make sure that test discoverer & executors are registered and platform & framework version settings are appropriate and try again.
```

What do we need to do, to be able to run the tests from within the self-compiled version of the vstest.console.exe?

Thanks for your help!
Marc

**Comment by codito** [comment]
@marc-mueller the support for UWP is not available yet, we're tracking the work with #684.

I assume you meant the `UnitTestClient` that ships in current UWP unit test templates. Unfortunately it uses WCF to communicate back with VS/vstest.console.exe. It will not work as it is since the vstest.console (in this repo) uses json over sockets.

**Comment by Faizan2304** [comment]
Hi @marc-Mueller, 
Did you get the answer which you are looking for? If yes, can I close this as completed?

**Comment by codito** [comment]
Closing this issue since we're tracking devices support in #684 (it is marked for 15.5 VS release)
