### ISSUE TITLE
How to run Multi-Targeted Tests in VS 2017.3 Testrunner

### ISSUE THREAD

**Issue by RickStrahl** [Microsoft/vstest#826]
I have an SDK Test Project that uses both `netcoreapp2.0` and `net452` as a target. Tests run properly from the command line with dotnet test, running tests for both frameworks.

I have target frameworks set and configured each target with its appropriate dependencies and constants etc.

```xml
<TargetFrameworks>netstandard2.0;net45</TargetFrameworks>
```

It works from the command line, but inside of Visual Studio however, I cannot get tests to work unless the target is `netcoreapp2`.  

If I shuffle around the two targets in the TargetFrameworks tag (looks like the first one is the one used to run tests?), but when the target is 452 tests appear to not be found. 

If I run with the netcoreapp2.0 target I get the following for running an individual test:

```
[5/20/2017 2:55:55 PM Informational] ------ Discover test started ------
[5/20/2017 2:55:55 PM Informational] ========== Discover test finished: 125 found (0:00:00.7495551) ==========
[5/20/2017 2:55:56 PM Informational] ------ Run test started ------
[5/20/2017 2:55:57 PM Informational] ========== Run test finished: 1 run (0:00:00.720457) ==========
```

If I run individual tests for 452 I get:
```
[5/20/2017 2:55:19 PM Informational] ------ Run test started ------
[5/20/2017 2:55:19 PM Informational] ========== Run test finished: 0 run (0:00:00.0309849) ==========
```

IOW, it looks like it's not finding anything.  The tests in the UI also all low-light like this:

![image](https://cloud.githubusercontent.com/assets/1374013/26279433/90a945f6-3d68-11e7-88a8-6768d1c2f97f.png)

If I run for netcoreapp2.0 then the test is found and executed.

I've also tried using  different test runners - nunit and xunit - and see the same behavior.

Is there any way to make this work at this point? Or am I missing some magic framework tooling combination that does work :-)

Current use case is porting an old class library to net2.0 and need to be able to run individual tests for each platform. 

Also: What is the plan on how to handle multi-targeted tests in the IDE?

FWIW, here's the .csproj I'm using:

```xml
<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<TargetFrameworks>netcoreapp2.0;net452</TargetFrameworks>

		<IsPackable>false</IsPackable>
	</PropertyGroup>

	<ItemGroup>
		<PackageReference Include="Microsoft.CSharp" Version="4.3.0" />
		<PackageReference Include="Microsoft.NET.Test.Sdk" Version="15.3.0-preview-20170427-09" />
		<PackageReference Include="MSTest.TestAdapter" Version="1.1.17" />
		<PackageReference Include="MSTest.TestFramework" Version="1.1.17" />
		<PackageReference Include="Newtonsoft.Json" Version="10.0.2" />		
	</ItemGroup>

	<ItemGroup>
		<ProjectReference Include="..\Westwind.Utilities.Core\Westwind.Utilities.csproj" />
	</ItemGroup>


	<ItemGroup Condition=" '$(TargetFramework)' == 'net452' ">		
		<Reference Include="mscorlib" />
		<Reference Include="System" />
		<Reference Include="System.Core" />		
		<Reference Include="System.Data" />
		<Reference Include="System.Web" />
		<Reference Include="System.Drawing" />
		<Reference Include="System.Security" />
		<Reference Include="System.Xml" />
		<Reference Include="System.Web" />		
		<Reference Include="System.Configuration" />
		<Reference Include="System.ComponentModel.Annotations" />
	</ItemGroup>
	<PropertyGroup Condition=" '$(TargetFramework)' == 'net452'">
		<DefineConstants>NET45;NETFULL</DefineConstants>
	</PropertyGroup>

	<ItemGroup>
	  <Service Include="{82a7f48d-3b50-4b1e-b82e-3ada8210c358}" />
	</ItemGroup>

	<ItemGroup>
	  <Folder Include="Properties\" />
	</ItemGroup>

	<ItemGroup Condition="'$(TargetFramework)'=='netcoreapp2.0'">
	</ItemGroup>
	<PropertyGroup Condition=" '$(TargetFramework)' == 'netcoreapp2.0'">
		<DefineConstants>NETSTANDARD2_0;NETCORE;NETSTANDARD;</DefineConstants>
	</PropertyGroup>

</Project>
```

**Comment by Faizan2304** [comment]
@RickStrahl Currently multi-targeting is not supported from Visual studio. Its in our priority list and we are actively working on it to bring it in VS but under which mile stone this will come is not decided. 

>If I run individual tests for 452 I get:
> ```
>[5/20/2017 2:55:19 PM Informational] ------ Run test started ------
>[5/20/2017 2:55:19 PM Informational] ========== Run test finished: 0 run (0:00:00.0309849) >==========
>```
>

What version of VS you are using?
Are you able to repro the above issue with a blank unit test project targeting net452?

**Comment by RickStrahl** [comment]
I'm using the current preview with support for netcore 2.0.

Standalone full framework test works (totally different story). Standalone netcore test works too.

Creating a netcore 2 project, then changing the target to net452 **does not work**. The following tells me no tests were run:

```xml
<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net452</TargetFramework>

    <IsPackable>false</IsPackable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.NET.Test.Sdk" Version="15.3.0-preview-20170427-09" />
    <PackageReference Include="MSTest.TestAdapter" Version="1.1.17" />
    <PackageReference Include="MSTest.TestFramework" Version="1.1.17" />
  </ItemGroup>

  <ItemGroup>
    <Service Include="{82a7f48d-3b50-4b1e-b82e-3ada8210c358}" />
  </ItemGroup>

</Project>
```

So it looks like the problem here is that net452 in an SDK project.

The blocking issue for me here is that I can't test 452 inside of Visual Studio in an SDK project in any way. 

Tests do run correctly from the command line with `dotnet test` - including running multiple targets.

I'm OK with having only one target run at a time for the time being but not being able to debug into the 452 target is a blocking issue.

**Comment by Faizan2304** [comment]
@RickStrahl I am assuming packages are getting restore properly and build is working fine for net452. Having said that can you please try running net452 tests from command line
```
"C:\Program Files (x86)\Microsoft Visual Studio 15.0\Common7\IDE\Extensions\TestPlatform\vstest.console.exe" Full-Path-Of-Net452-Test-dll /TestAdapterpath:Path-Where-Net452-Test-dll-Is
```


I am also interested in getting following information. It will help me to root cause the issue
1) Version of visual studio 
2) Version of TestPlatform.vsix (Tools -> Extensions and Updates.. -> Microsoft Visual Studio Test Platform)

**Comment by RickStrahl** [comment]
Sorry - forgot in the last message. Version is latest preview of 2017.3. (26510.0-Preview).
Test Extension Version: 15.3.2017042709


As I mentioned tests run fine from the command line with `dotnet test` for both targets which I presume is using the above runner you mention.

**Comment by Faizan2304** [comment]
@RickStrahl Did you get a chance to look into it?

**Comment by RickStrahl** [comment]
Apologies...

Couple of things. Folder where the test driver lives is:
C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\Common7\IDE\Extensions\TestPlatform

& "C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\Common7\IDE\Extensions\TestPlatform\vstest.console.exe" "C:\projects2010\Westwind.Utilities\Westwind.Utilities.Test\bin\Release\net452\Westwind.Utilities.Test.dll" /TestAdapterpath:"C:\projects2010\Westwind.Utilities\Westwind.Utilities.Test\bin\Release\net452"

As expected - the tests run.

**Comment by Faizan2304** [comment]
@RickStrahl : Apologies.. I couldn't look into this issue as I was busy in other work.

I tried creating local repro but unfortunately no luck.
I think I need repro project here. 
Meanwhile can you please help me get some logs..
please follow the following step to collect log.

### Test Explorer log.  
1) Go to `Tools -> options -> Test -> Logging` and select logging level diagnostic.
It will provide you logs in Test hub of output pane.

### vstest.console.exe log
1) Edit the config file ""C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\Common7\IDE\Extensions\TestPlatform\testplatform.config" to change the value of key key="feature.net40" and key="feature.datacollector" to true.
2) collect it using https://github.com/Microsoft/vstest-docs/blob/master/docs/diagnose.md#collect-trace-using-config-file

**Comment by onovotny** [comment]
@RickStrahl as a less-than-ideal workaround, you can change the order of the `TargetFrameworks`. The Test Explorer will use the first one.

**Comment by RickStrahl** [comment]
Yes that works as I mentioned - sort of. 

The switching the targets around appears to switch, but the 4.5 tests do not run inside of VS. Looks like the test runner is simply doing nothing. The NETCORE tests run. Runs from the command line.

FWIW, either way tests are very, very slow to start up. There's about 10+ secs just for warmup with SDK projects, where old project tests run in under 2 secs total.

**Comment by Faizan2304** [comment]
Hi @RickStrahl. Did you get chance to collect logs. I tried locally but I am not able to repro it.

**Comment by RickStrahl** [comment]
Just a heads up - I installed the latest preview and it looks now tests for full framework run.

Startup for tests also seems to have greatly improved in this update.
