### ISSUE TITLE
Tests not discovered when BaseIntermediateOutputPath changed from default

### ISSUE THREAD

**Issue by mattzink** [Microsoft/vstest#828]
## Description
> We set custom `<OutputPath>` and `<BaseIntermediateOutputPath>` in our csproj files so that compiling does not litter up the source directory hierarchy. When we change `<BaseIntermediateOutputPath>` to anything but the default path (`obj\`), then xunit tests are no longer discovered in dotnet test or VS2017 15.3 preview. This was originally filed against xunit (https://github.com/xunit/xunit/issues/1296), but I was notified this was a vstest issue.

## Steps to reproduce
1. Execute `dotnet new xunit`
2. Edit csproj, adding `<BaseIntermediateOutputPath>obj2\</BaseIntermediateOutputPath>`
3. Delete existing `obj` sub-directory
4. Execute `dotnet restore`
5. Execute `dotnet test`

## Expected behavior
> The included default test is executed

## Actual behavior
> The following error is displayed:
```
Starting test execution, please wait...
No test is available in C:\Users\mattzink\Documents\Visual Studio 2017\Projects\core2test\source\test\bin\Debug\netcoreapp2.0\test.dll. Make sure test project has a nuget reference of package "Microsoft.NET.Test.Sdk" and framework version settings are appropriate and try again.
```

## Environment
> Windows 10 (x64)
> .NET Core 2.0 preview 1
> xunit 2.2.0 or 2.3.0-beta3-build3699

**Comment by Faizan2304** [comment]
@mattzink  This is not the issue with vstest but msbuild and sdk.
Here is the solution of your problem https://github.com/dotnet/sdk/issues/980#issuecomment-285957284
