### ISSUE TITLE
Test explorer refreshes often and loses status of test runs

### ISSUE THREAD

**Issue by twsouthwick** [Microsoft/vstest#833]
## Description
I often will run my tests, determine the failure ones, and start working on fixing them. After some time, when I go to run a failed test, the project will rebuild, and then test explorer will refresh. At this point, all tests appear to not have run; I have to do a full run (which take a lot longer) in order to see the failed tests again. 

## Steps to reproduce
1. Do a test run
2. Work for a while
3. Build solution

## Expected behavior
Should retain the list of test failures/passes

## Actual behavior
Sometimes (may have to repeat steps 2&3), the test explorer refreshes and loses status of test pass

## Environment
VS 15.2

**Comment by Faizan2304** [comment]
@twsouthwick This is very strange. This is not the expected behavior of TestExplorer. I tried locally with VS15.2 machine but no luck. This is what I did.
1) Create a C# unit test project.
2) Added couple of passed and failed test.
3) Run All test.
4) Added a new test (TestMethod5)
5) Rebuild the solution.
6) Got below result
![image](https://cloud.githubusercontent.com/assets/19184362/26481853/64015dac-4201-11e7-818d-5e532509c607.png)

Can you please give us some more info:
1) SKU and version of visual studio used.
2) information about test project(language, target framework)

**Comment by twsouthwick** [comment]
This issue is very non-deterministic. It happens regularly, but no easy repro and no single root cause that I've seen.  Are there any logs I could try to capture?

- Sku and version of VS: VS 15.2 Enterprise
- The structure of the project is the following:

```
|- src
  |- .NET Standard 1.3 library with new csproj
  |- .NET 4.6 library with new csproj
  |- .NET 4.6 library with old csproj
  |- .NET 4.6 application with new csproj
|- test
  |- .NET 4.6 xunit test with new csproj
  |- .NET 4.6 xunit test with new csproj
```

**Comment by twsouthwick** [comment]
@Faizan2304 Are there any specific diagnostics I can try to capture?

**Comment by Faizan2304** [comment]
@twsouthwick 
Sorry for replying so late. I was in vacation.
Please help me to get the answer of following question.
1) What is the xunit version you are using? Does moving to newer version of xunit solving your problem?
2) How are you running the failed test? Are you running it from TestExplorer or from context menu (ctrl+R, T)

To collect TestExplorer log set the value of environment variable `VS_UTE_DIAGNOSTICS` to `1`. This will log data in Test pane of output window.

**Comment by axelheer** [comment]
@Faizan2304 I'm facing similar issues (only when updating `Microsoft.NET.Test.SDK` from `15.0.0` to `15.3.0`) and want to gather more information, but setting `VS_UTE_DIAGNOSTICS` to `1` doesn't add more details. What else can I do?

**Comment by twsouthwick** [comment]
I haven't seen this since updating to 15.4, but @Faizan2304 are you setting the environment variable and then launching VS? VS most likely won't pick up on it if you set the environment variable after launching.

**Comment by snkota** [comment]
This is being tracked external to this repo, here: 
https://developercommunity.visualstudio.com/content/problem/145927/test-explorer-refreshes-often-and-loses-status-of.html

**Comment by axelheer** [comment]
Additionally, my Test Explorer "loses" the current test run after 8, 48, 96 or so successfully executed tests on one of my two machines (it just stops reporting the progress of all the other tests). To troubleshoot this problem (I'm unable to practically use Test Explorer on the affected machine) I've tried setting `VS_UTE_DIAGNOSTICS` to `1`.

But there's no additional diagnostics stuff to find in the output window, only the "ordinary" xUnit stuff. Thus, my original question, what else I can do to troubleshoot Test Explorer issues.  BTW, the environment variable is still set on the affected machine, so there's no restart / reboot issue.

**Comment by pvlakshm** [comment]
This is being tracked external to this repo, here:
https://developercommunity.visualstudio.com/content/problem/145927/test-explorer-refreshes-often-and-loses-status-of.html
