### ISSUE TITLE
testhost.x86.exe should be able to handle large addresses.

### ISSUE THREAD

**Issue by harshjain2** [microsoft/vstest#834]
## Description
There could be scenarios where testhost.x86.exe requires more than 2 GB of memory. In those cases, current testhost.x86.exe could fail with StackOverFlowException/OutOfMemoryException as 32-bit programs receive only 2 GB of address space.

We should consider using /LARGEADDRESSAWARE flag in testhost.x86.exe. 
When this flag is used while compiling, testhost.x86.exe can use up to 4GB of address space. 

We also need to investigate the same has to be applied in DataCollector.exe and vstest.console.exe as well.

**Comment by harshjain2** [comment]
cc @codito @smadala @Faizan2304 @singhsarab

**Comment by Faizan2304** [comment]
### Current Status: 
Currently dotnet tooling doesn't have support to use /LARGEADDRESSAWARE for cross plat[Related Issue](https://github.com/dotnet/roslyn/issues/9209)

### Workaround: 
User can run their test for platform x64.

### Action:
Moving this bug from milestone 15.5 and will address once the above issue will get fixed.

**Comment by sharwell** [comment]
The required compiler feature is already implemented going back to the first VS2015 release. See my comment in the linked issue.

**Comment by fifthgearonline** [comment]
this appears to have been fixed in VS 2019
![unknown](https://user-images.githubusercontent.com/21365801/58711906-1bb13c80-8385-11e9-803a-28f67ddb89a5.png)

**Comment by sharwell** [comment]
Weird. I refiled this as #1985 and then fixed it in #1986.

**Comment by singhsarab** [comment]
@sharwell Cool! Thanks. 
@fifthgearonline Thanks for confirmation.
