### ISSUE TITLE
Native code debugging not working

### ISSUE THREAD

**Issue by rwatjen** [Microsoft/vstest#838]
## Description
When testing a class library that calls native code, the test runner cannot debug the native code. It ignores breakpoints, and steps over calls to native functions.

## Steps to reproduce
VS2017 solution contains three projects:

1. Native C++ DLL project
2. Class library which contains code that calls into the native DLL with P/Invoke.
3. Unit test project

The class library and unit test projects are both with the new "SDK Style" csproj format.

Setting a breakpoint inside the native C++ code does not break when debugging. 
Setting a breakpoint in the managed code, and then F11-stepping into the native code, just steps over the native method call.

There is no checkbox in the class library or unit test project properties to "Enable native code debugging", but it has been added to the csproj files using
```
  <PropertyGroup>
    <EnableUnmanagedDebugging>true</EnableUnmanagedDebugging>
  </PropertyGroup>
```

## Expected behavior
I expected the debugger to break on breakpoints in the native code.

## Actual behavior
Breakpoints in native code are ignored.

## Workaround
Converting the unit test project to a "regular" csproj file brings back the "Enable native code debugging" checkbox in project properties, and native mode debugging works as expected.

## Environment
VS 2017.2 (26430.12)

**Comment by Faizan2304** [comment]
@rwatjen : Can you please provide me a repro project. I tried on visual studio 2017 update3 preview 3 and it worked. I will try tomorrow on visual studio 2017.2

**Comment by rwatjen** [comment]
[MixedModeDebuggingTest.zip](https://github.com/Microsoft/vstest/files/1080490/MixedModeDebuggingTest.zip)

I have attached a solution that contains a native C DLL, a C# Classlibrary that uses it, and two unit test projects. One is "Classic" with a regular csproj file, and the other has the "SDK style" csproj. VS chooses testhost.x86.exe as the test runner for the latter.

To build the project, you need to build "NativeDLL" first (it seems to ignore the project build order in the solution).

Place a breakpoint in native.c in the single return statement, and then debug the unit test in the UnitTests.Classic project to see that it does indeed break. Then debug the unit test in the UnitTests.SdkStyle project to see that it ignores the breakpoint.

This happens with VS version 15.2 (26430.13) and VS 15.3.0 preview 2.0

**Comment by dlemstra** [comment]
I am experiencing the same issue in one of my projects and I would love to be able to debug my native project again. I have tried the test project from @rwatjen with VS2017 15.3.0 Preview 3.0. I can debug the Classis unit test but I cannot debug the SdkStyle unit test. What did you do to make it work @Faizan2304?

**Comment by snkota** [comment]
This is being tracked external to this repo here:
https://developercommunity.visualstudio.com/content/problem/145916/native-code-debugging-not-working.html

**Comment by ashish2rathi** [comment]
I am also facing the same issue while debugging with native code. I tried this with visual studio 2017  version 15.8.4. The native projects are migrated from visual studio 2008 to visual studio 2017 directly. The applications runs perfectly but when I try to debug it just step over the native function call.
