### ISSUE TITLE
.NET Core XUnit project in .Net Core raises warnings on TypeLoadException

### ISSUE THREAD

**Issue by MiaomiaoHuangfu** [Microsoft/vstest#840]
## Description
> For .NET Core xUnit test project, Run tests and display a warning in the output window: 
`Exception discovering tests: System.TypeLoadException: Could not load type 'System.Runtime.Remoting.Channels.IChannel' from assembly 'mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089'.
   at Xunit.RemotingUtility.CleanUpRegisteredChannels()
   at Xunit.Runner.VisualStudio.TestAdapter.VsTestRunner.DiscoverTests[TVisitor](IEnumerable`1 sources, LoggerHelper logger, Func`4 visitorFactory, Action`4 visitComplete)`

## Steps to reproduce
> Create a xUnit Test project (.NET Core);
> build the project;
1) In Test Explorer, right click the test and click "Run Selected Tests"
2) In code editor, right click the test and click "Run Tests"

## Expected behavior
> Run passed with no error or warning

## Actual behavior
> There is a warning is output window: 
![xunitwarning](https://cloud.githubusercontent.com/assets/22901391/26778086/5ad7dce2-4a12-11e7-8c5a-dde066d447d7.PNG)

## Environment
> Install d15prerel.26604.01
> Install latest CLI/SDK 2.0. from https://github.com/dotnet/cli/tree/release/2.0.0 
> Operating system: Windows 10 x64 ENU
> Build version of vstest.console: 15.0.26604.1
> dotnet --info
`.NET Command Line Tools (2.0.0-preview2-006341)

Product Information:
 Version:            2.0.0-preview2-006341
 Commit SHA-1 hash:  19d305783b

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.14393
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\2.0.0-preview2-006341\

Microsoft .NET Core Shared Framework Host

  Version  : 2.0.0-preview2-25402-02
  Build    : 3c440c8947e7776b2c7772bcb98b3bc73e1b9193`

**Comment by Faizan2304** [comment]
@MiaomiaoHuangfu : Can you please provide me repro machine ?

**Comment by MiaomiaoHuangfu** [comment]
Repro machine name: E2E-008
Login account: Redmond\corbvt

**Comment by Faizan2304** [comment]
Fix will come in next preview of visual studio, most probably visual studio 2017 update3 preview3 will have it.

**Comment by Liero** [comment]
Still having the same problem: 

Microsoft Visual Studio Enterprise 2017 
Version 15.2 (26430.16) Release
VisualStudio.15.Release/15.2.0+26430.16
Microsoft .NET Framework
Version 4.7.02046
ASP.NET and Web Tools 2017   15.0.30503.0

**Comment by codito** [comment]
@Liero can you please try latest `15.3 preview` builds of VS, they can be downloaded from https://www.visualstudio.com/vs/preview/

**Comment by Liero** [comment]
Unfortunatelly I can't try preview right now but I will install it as soon as stable version will be released. Meanwhile, is there some workaround?

**Comment by jasel-lewis** [comment]
FWIW, clearing the Visual Studio Test Explorer Extensions folder solved this problem for me.  Instructions can be found [here](https://xunit.github.io/docs/getting-started-dotnet-core.html) (scroll down to the red/pink box immediately under the **Running tests with Visual Studio** section).

**Comment by berdon** [comment]
At some point, the cache folder stopped existing in my %TEMP% directory. Doing a rm -rf **/bin **/obj in the project directory fixed the issue.

**Comment by MarkKharitonov** [comment]
I do not have the directory VisualStudioTestExplorerExtensions in my temp and I cleaned the workspace with `git clean -qdfX` yet I still get the exact same error:
```
C:\xyz\code [master ≡]> git clean -qdfx
C:\xyz\code [master ≡]> Test-Path $env:temp\VisualStudioTestExplorerExtensions
False
C:\xyz\code [master ≡]> Test-Path $pwd\UnitTests\Gateway.UnitTests\bin\Release\netcoreapp2.2\Gateway.UnitTests.dll
False
C:\xyz\code [master ≡]> dir .\Platform.sln,.\Services.sln,.\Gateway.sln |% { dotnet build -v:q -c Release -p:RunTests=$false $_ }
Microsoft (R) Build Engine version 16.3.0+0f4c62fea for .NET Core
Copyright (C) Microsoft Corporation. All rights reserved.


Build succeeded.
    0 Warning(s)
    0 Error(s)

Time Elapsed 00:00:01.49
Microsoft (R) Build Engine version 16.3.0+0f4c62fea for .NET Core
Copyright (C) Microsoft Corporation. All rights reserved.


Build succeeded.
    0 Warning(s)
    0 Error(s)

Time Elapsed 00:00:01.08
Microsoft (R) Build Engine version 16.3.0+0f4c62fea for .NET Core
Copyright (C) Microsoft Corporation. All rights reserved.


Build succeeded.
    0 Warning(s)
    0 Error(s)

Time Elapsed 00:00:02.29
C:\xyz\code [master ≡]> dotnet vstest $pwd\UnitTests\Gateway.UnitTests\bin\Release\netcoreapp2.2\Gateway.UnitTests.dll -lt
Microsoft (R) Test Execution Command Line Tool Version 16.3.0
Copyright (c) Microsoft Corporation.  All rights reserved.

The following Tests are available:
An exception occurred while test discoverer 'NUnitTestDiscoverer' was loading tests. Exception: Could not load type 'System.Runtime.Remoting.Channels.IChannel' from assembly 'mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089'.
Test run in progress.    UnitTests.ServicesTests.AccountServiceTests.TestRegisterForProgramProduct_WithGlobalId_ReturnsResult
    UnitTests.ServicesTests.AccountServiceTests.TestRegisterForProgramProduct_WithGlobalId_PerformIdentityCheckException
    UnitTests.ServicesTests.AccountServiceTests.TestRegisterForProgramProduct_WithGlobalId_SaveEntityException
    UnitTests.ServicesTests.AccountServiceTests.TestRegisterForProgramProduct_WithGlobalId_SaveEntityContactException
    UnitTests.ServicesTests.AccountServiceTests.TestRegisterForProgramProduct_WithGlobalId_SaveEntityGoveIdException
    UnitTests.ServicesTests.AccountServiceTests.TestGetUserInfo_ReturnsResult
    UnitTests.ServicesTests.AccountServiceTests.TestGetUserInfo_ThrowError
C:\xyz\code [master ≡]>
```
Please, reopen the issue.
