### ISSUE TITLE
Run All showing conflicting adapter(s) for .NET Core xunit projects

### ISSUE THREAD

**Issue by MiaomiaoHuangfu** [Microsoft/vstest#843]
## Steps to reproduce
1. > create a xUnit Test (.NET Core) project;
2. > click "Test Explorer" window under Test menu;
3. > build the projects succeeded;
4. > Click "Run All" under Test explorer window

## Expected behavior
> Test passed with no warning in output window;

## Actual behavior
> There is warning in output window"Multiple test adapters with the same uri 'executor://xunit/VsTestRunner2' were found. Ignoring adapter 'Xunit.Runner.VisualStudio.TestAdapter.VsTestRunner'. Please uninstall the conflicting adapter(s) to avoid this warning."
   ![runall](https://cloud.githubusercontent.com/assets/22901391/26824045/6e2f41e2-4ae2-11e7-9681-57f817e0d8ed.PNG)

## Environment
> Install d15prerel.26605.02;
> Install latest CLI/SDK 2.0. from https://github.com/dotnet/cli/tree/release/2.0.0
> Build version of vstest.console: 15.0.26605.02
> dotnet --info
```
.NET Command Line Tools (2.0.0-preview2-006341)

Product Information:
 Version:            2.0.0-preview2-006341
 Commit SHA-1 hash:  19d305783b

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.14393
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\2.0.0-preview2-006341\

Microsoft .NET Core Shared Framework Host

  Version  : 2.0.0-preview2-25402-02
  Build    : 3c440c8947e7776b2c7772bcb98b3bc73e1b9193
```

**Comment by Faizan2304** [comment]
This is happening due to same reason as https://github.com/Microsoft/vstest/issues/840 is happening. 
Closing it as duplicate.
