### ISSUE TITLE
PowerShell Tools for Visual Studio 2017 pulls in incompatible assembly references

### ISSUE THREAD

**Issue by spati2** [Microsoft/vstest#844]
I am using a netcore project and I noticed that the Powershell extension pulls in reference to log4net (v2.0.3) which is incompatible with netcore for a a Xunit test case

## Steps to reproduce
> Please follow steps in https://github.com/Microsoft/vstest/issues/632
> Use the test repo https://github.com/ddrinka/aws-sdk-net-log4net-bug

## Expected behavior
> The XUnit test case should execute without issues

## Actual behavior
> Test fails

## Environment
> Visual Studio 2017 (with the PowerShell component installed)
> Operating system, Build version of vstest.console

**Comment by codito** [comment]
Likely same root cause as #632.

**Comment by Faizan2304** [comment]
Fix will come in next preview of visual studio, most probably visual studio 2017 update3 preview3 will have it.

**Comment by stefanbalan** [comment]
.NET 4.6 project, when debugging tests:
> System.IO.FileNotFoundException: 'Could not load file or assembly 'Microsoft.VisualStudio.Shell.Interop, Version=7.1.40304.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' or one of its dependencies. The system cannot find the file specified.'
Continuing execution, the tests are executed and pass or fail without regard for the above exception.

- Visual Studio Community 2017 - ver 15.4.1 
- PowerShell Tools for Visual Studio 2017 - ver 3.0.552
Disabling the "PowerShell Tools" extension makes the exception go away.
