### ISSUE TITLE
Tests aren't showing up in 15.2 or 15.3 Preview 2 

### ISSUE THREAD

**Issue by onovotny** [Microsoft/vstest#850]
Trying to use the Test Explorer with Ix.NET, I see the tests show up momentarily and then disappear.

I've tried this with 15.2.2 and 15.3 preview 2.

To repro:
Clone https://github.com/Reactive-Extensions/Rx.NET,
Checkout develop, fa19894bb71a902f44feb3cc2df62895d3cdaf75
Open up Ix.NET\source\Ix.NET.sln and build

Tests aren't showing up in the test explorer window

**Comment by onovotny** [comment]
I've recorded this while it's happening here:
https://developercommunity.visualstudio.com/content/problem/67373/tests-arent-showing-up-in-test-explorer.html

**Comment by gulbanana** [comment]
i'm also experiencing this symptom

**Comment by Faizan2304** [comment]
I got the local repro and on debugging it got to be known [issue](https://github.com/Microsoft/vstest/issues/847)
we have fixed it and fix will come in next VS preview. To unblock yourself, you can install this [TestPlatform vsix](https://vsdrop.corp.microsoft.com/file/v1/Products/DevDiv/Microsoft/vstest/15.3-rtm/20170609-02;/TestPlatform.vsix)

**Comment by gulbanana** [comment]
thanks, trying that today

**Comment by gulbanana** [comment]
hi, @Faizan2304 - that URL is not public. could you please make the extension available somewhere I can download it? we are pretty much totally blocked here by being unable to run tests in the latest VS

**Comment by codito** [comment]
Rename attached file to vsix and try. [TestPlatform.vsix.zip](https://github.com/Microsoft/vstest/files/1082526/TestPlatform.vsix.zip)
Please take a backup of `C:\Program Files (x86)\Microsoft Visual Studio\Preview\Enterprise\Common7\IDE\Extensions\TestPlatform` just in case.

**Comment by gulbanana** [comment]
will do, thanks
