### ISSUE TITLE
Inconsistent VS Test Explorer integration of Code Coverage for .NET Framework and .NET Core

### ISSUE THREAD

**Issue by pvlakshm** [Microsoft/vstest#852]
For .NET Framework projects, the code coverage context menu command from the Test Explorer  just works.
However for .NET Core projects, it works ONLY if the project has a NuGet reference to “Microsoft CodeCoverage”. If not, then the context menu item silently does nothing.

Several options:
(1) Give an error dialog and point to the help page that tells the user to add the reference.
(2) Do not enable the command unless the test project is appropriately configured.
(3) Have the command add the reference to the test project(s).
(4) Have the .NET Core test project template already have a reference to the NuGet package. This would make the behaviour consistent.

I suggest (4).

**Comment by terrajobst** [comment]
I don't think (2) is the right choice as it's just masking the problem making it equally hard for customers to find out what's wrong. I think a combination of (4) and (3) would be idealy.

**Comment by codito** [comment]
Adding all coverage impacting issues for 15.5.

**Comment by harshjain2** [comment]
@pvlakshm @terrajobst Thanks for providing feedback. 
I have fixed this issue through approach (4) in https://github.com/Microsoft/vstest/pull/1020.
