### ISSUE TITLE
Deps File Missing Throwing NoTestHostFileExist Error

### ISSUE THREAD

**Issue by vagisha-nidhi** [Microsoft/vstest#855]
## Description
Missing deps file is throwing a NoTestHostFileExist error in vstest.

## Steps to reproduce
To reproduce the error -
1. Create .Net Core Unit Test Project from template in VS
2. Build
Execute Command Line -
`vstest.console.exe C:\UniteTestProject1\obj\Debug\net46\UnitTestProject1.dll /framework:FrameworkCore10`

## Expected behavior
```
Microsoft (R) Test Execution Command Line Tool Version 15.3.0-dev
Copyright (c) Microsoft Corporation.  All rights reserved.

Starting test execution, please wait...
Deps File does not exist. 
```

## Actual behavior
It is showing a Nuget Package Reference error at present.
```
Microsoft (R) Test Execution Command Line Tool Version 15.3.0-dev
Copyright (c) Microsoft Corporation.  All rights reserved.

Starting test execution, please wait...
No test is available in C:\Users\t-vanidh\Source\Repos\UnitTestProject1\UnitTestProject1\obj\Debug\net46\UnitTestProject1.dll. Make sure test project has a nuget reference of package "Microsoft.NET.Test.Sdk" and framework version settings are appropriate and try again.
```

**Comment by Faizan2304** [comment]
@vagisha-nidhi : It seems you are trying to run test assembly build against target framework net46 by passing target framework netcoreapp 

Below command will solve your issue.
`vstest.console.exe C:\UniteTestProject1\obj\Debug\net46\UnitTestProject1.dll /TestadapterPath:"C:\UniteTestProject1\obj\Debug\net46"`

You can skip target framework here as default target framework is Framework40 when you are running test from vstest.console.exe.

You can also use `dotnet test` command to run test. It will take care of all the necessary things which is required to run the test. For this command will be `dotnet test C:\UniteTestProject1\UnitTestProject1.csproj`
