### ISSUE TITLE
VisualStudio 2017 preview 2 doesn't load Unit tests with .NET Core 2.0.0-preview2-006391

### ISSUE THREAD

**Issue by livarcocc** [Microsoft/vstest#858]
_From @piolo94 on June 13, 2017 13:19_

In the last two days I've had some trouble with Unit Testing in VS 2017 preview 2. Yesterday I've installed the last version of .NET core, I've updated every package inside my project and, since then, I haven't been able to see not a single test in VisualStudio's Test Explorer . If run the command "dotnet test" in the PowerShell everything works and I receive the information of test's execution. What can I do? Thanks!

_Copied from original issue: dotnet/cli#6848_

**Comment by Faizan2304** [comment]
@piolo94: How did you install latest .NET core? I mean did you use scrip or you used installer?
What is the version of .NET core you have installed?

Are you able to run test from newly created  .NET core unit test project from Visual studio?

**Comment by piolo94** [comment]
@Faizan2304: Good Morning! I've installed first the 1.0.4 version, then the 2.0.0-preview1-05977 and finally the 2.0.0-preview2-006391. All the versions are been installed using the installer apllication.  VS is @15.3.0 preview2.
The output of "dotnet --version" is:  2.0.0-preview2-006391
I've created a new UnitTestProject and I've added a couple of test case, but none is shown.
I've also created a new solution with a console project with a test project, but still no progress. 
Thanks for your help!

**Comment by Faizan2304** [comment]
@piolo94 : I got the local repro and on debugging it got to be known [issue](https://github.com/Microsoft/vstest/issues/847)
we have fixed it and fix will come in next VS preview. To unblock yourself, you can install this [TestPlatform vsix](https://vsdrop.corp.microsoft.com/file/v1/Products/DevDiv/Microsoft/vstest/15.3-rtm/20170609-02;/TestPlatform.vsix)

**Comment by piolo94** [comment]
Thanh You very much! I've noticed that the link you gave me doesn't work. Can you check it again? Thanks!!

**Comment by codito** [comment]
@piolo94 sorry, that link is not accessible. Please try the following:
* Rename attached file to vsix and try. [TestPlatform.vsix.zip](https://github.com/Microsoft/vstest/files/1082526/TestPlatform.vsix.zip)
* Please take a backup of `C:\Program Files (x86)\Microsoft Visual Studio\Preview\Enterprise\Common7\IDE\Extensions\TestPlatform` just in case.

**Comment by RGH-LaksThiru** [comment]
I had this issue for past 2 days, finally, I solved it.
Tools -> NuGet Package Manager -> Manage NuGet Package for Solution , select all packages to update your project repository.
