### ISSUE TITLE
There are unlocalized messages in execution of dotnet test

### ISSUE THREAD

**Issue by nguerrera** [Microsoft/vstest#861]
The build started and completed messages are hard-coded in English

https://github.com/Microsoft/vstest/blob/c701070abb126853b58800cedd7554482471ac7d/src/Microsoft.TestPlatform.Build/Tasks/BuildLogTask.cs#L23-L31

**Comment by nguerrera** [comment]
Here too: https://github.com/Microsoft/vstest/blob/a76f69b8a4501b3d3335f6febf934540f74af40f/src/Microsoft.TestPlatform.Build/Tasks/VSTestTask.cs#L117

**Comment by Faizan2304** [comment]
Fixed!!
