### ISSUE TITLE
dotnet test should not build if project already built

### ISSUE THREAD

**Issue by livarcocc** [Microsoft/vstest#863]
_From @ardalis on June 14, 2017 16:47_

## Steps to reproduce
Run dotnet test. It will build.
Run dotnet test again. It will build. It doesn't need to.

## Expected  behavior
Run dotnet test. It will build (if necessary).
Run dotnet test. It will simply run tests.

## Actual behavior
See above.

## Environment data
`dotnet --info` output:

_Copied from original issue: dotnet/cli#6868_

**Comment by singhsarab** [comment]
@livarcocc I am not sure how this can we handled on the test platform side. This would actually require dotnet verb design change.

When dotnet test is called, dotnet build gets called implicitly. Is there a way for dotnet test command to be aware of the state of the build. and then skip?
Ideally, build should get invoked as expected and this decision should be with the build command.
But then, I am not sure if build has the capability to identify if the new build request is redundant.

Can you please share your thoughts ?

**Comment by livarcocc** [comment]
While build is invoked, it should not be changing assemblies as incremental build should kick in and skip compilation and additional build work. So, build is already deciding when to actually build or not. However, many things may contribute to force a build to happen. I am not sure that test is doing such a thing or not. if you are confident it is not, I would just close this issue.

Also, dotnet test supports the --no-build flag, if the user does not want even incremental builds to run, then pass that flag.

**Comment by singhsarab** [comment]
Yes, I just verified the behavior, it just prints build started, and completed. It skips the compilation if it is not required.

And yes --no-build flag works as expected.

Validated using dotnet version = 3.0.100-preview-010184
Closing this issue now.
