### ISSUE TITLE
UX: Simple use cases are failing for testing in multi-targetting projects on VS2017 for win10-x64

### ISSUE THREAD

**Issue by fir3pho3nixx** [Microsoft/vstest#864]
## Steps to reproduce

Please clone https://github.com/fir3pho3nixx/nunit-adapter-vs-xunit/tree/missing-package-with-error-message-that-is-simply-wrong

Then run: `build.bat`

## Expected  behavior

It does *NOT* kick out: `Make sure test project has a nuget reference of package "microsoft.testplatform.testhost"`. This is the wrong package, in my case I was missing a package reference to: 

```xml
<PackageReference Include="Microsoft.NET.Test.Sdk" Version="15.0.0" />
``` 

This happens for both NUnit and XUnit. You can observe this by commenting out this [line](https://github.com/fir3pho3nixx/nunit-adapter-vs-xunit/blob/master/build.bat#L4). 

## Actual behavior

It kicks out: `Make sure test project has a nuget reference of package "microsoft.testplatform.testhost"`. 

## Environment data
`dotnet --info` output:

.NET Command Line Tools (1.0.4)

Product Information:
 Version:            1.0.4
 Commit SHA-1 hash:  af1e6684fd

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.14393
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\1.0.4

## More info

Please see https://github.com/dotnet/cli/issues/6856 for some background.

**Comment by Faizan2304** [comment]
Thanks @fir3pho3nixx for opening this issue with us. Its a known issue and we have fixed it. [PR](https://github.com/Microsoft/vstest/pull/691)

The new message looks like
`
No test is available in TestprojectName.dll. Make sure test project has a nuget reference of package "Microsoft.NET.Test.Sdk" and framework version settings are appropriate and try again.
`

**Comment by fir3pho3nixx** [comment]
Good stuff! Look forward to it being released 👍
