### ISSUE TITLE
Relative path bug in TranslationLayer.E2ETest demo

### ISSUE THREAD

**Issue by JakenVeina** [Microsoft/vstest#872]
## Description
> A rather small bug I noticed.
> The given sample program for utilizing TranslayionLayer attempts to use "log.txt" as the vstest.console.exe log file, via ConsoleParameters.LogFilePath, which doesn't properly support relative paths from the current working directory.

## Steps to reproduce
> Compile and run Microsoft.TestPlatform.TranslationLayer.E2ETest.exe with any valid set of parameters I used the following:

`--runner:"C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\Common7\IDE\Extensions\TestPlatform\vstest.console.exe" --testadapterpath:"C:\Users\Jake\Documents\Visual Studio 2017\Projects\10kUnitTests\packages\MSTest.TestAdapter.1.1.11\build\_common\Microsoft.VisualStudio.TestPlatform.MSTest.TestAdapter.dll" --testassembly:"C:\Users\Jake\Documents\Visual Studio 2017\Projects\vstest\test\TestAssets\SimpleTestProject\bin\Debug\net46\SimpleTestProject.dll"
`
## Expected behavior
> Sample program should execute without errors, demonstrating successful use of the API.

## Actual behavior
> ArgumentException is thrown by Microsoft.VisualStudio.TestPlatform.TranslationLayer.ConsoleParameters.LogFilePath setter. Path.GetDirectoryName(value) for value = "log.txt" returns "", causing fileHelper.Exists() to return false.

## Environment
> Running Windows 8.1 Pro, x64
> Running vstest.console.exe version 15.0.0.0.

Will have a PR for this momentarily.

**Comment by codito** [comment]
Fixed with cdcdf901bcb624e1ce529e58cd22ab702679cfaf. Thanks @JakenVeina!
