### ISSUE TITLE
Tests results not aggregating result for each targetFrameworks

### ISSUE THREAD

**Issue by livarcocc** [microsoft/vstest#880]
_From @bhugot on June 20, 2017 9:50_

## Steps to reproduce

Create a test project with 2 targetFrameworks and 1 Test

run Dotnet Test  --logger "trx;LogFileName=abc.trx"

## Expected  behavior

The file abc.trx should contains 2 lines, one for each target framework

## Actual behavior

There is only one line for the last targetFramework used.

## Environment data
`dotnet --info` output:
.NET Command Line Tools (2.0.0-preview2-006127)

Product Information:
 Version:            2.0.0-preview2-006127
 Commit SHA-1 hash:  946ea7980a

Runtime Environment:
 OS Name:     Windows
 OS Version:  6.1.7601
 OS Platform: Windows
 RID:         win7-x64
 Base Path:   C:\Users\bhugot100316\.dotnet\x64\sdk\2.0.0-preview2-006127\

Microsoft .NET Core Shared Framework Host

  Version  : 2.0.0-preview1-002111-00
  Build    : 1ff021936263d492539399688f46fd3827169983

_Copied from original issue: dotnet/cli#6951_

**Comment by codito** [comment]
`dotnet test` is overriding the previous trx log file. Merging the log files will break the schema since it supports a single test run today.

Can we suffix the target framework to trx filename for a MTFM project if user provides a log filename? E.g. <user-provided-name>.net46.trx and <user-provided-name>.netcoreapp1.0.trx

**Comment by jnm2** [comment]
I'm sad to see this removed from the 15.5 milestone. Is there any workaround for this today?

**Comment by jnm2** [comment]
Another issue I'm having today is that AppVeyor ignores all but the first `trx` file. Perhaps this is because the tests are identically named? Right now `dotnet test`'s TRX can't be used in any form with AppVeyor if your tests target multiple frameworks. What would you do to solve that?

**Comment by mayankbansal018** [comment]
@pvlakshm Pratap, it seems to me that we need to spec it out,

- If users provides trx file name, then we will overwrite the 1st trx file,
- If no file name is created then we generate 2 separate trx file, each containing data of individual run based on target frameworks.

Unfortunately we cannot re-use trx file from 1st run, & append the data for 2nd. As proposed by Arun we can rename trx file by appending the targetframework name, or we can show user a clear warning that his trx file will be overwritten.

**Comment by mayankbansal018** [comment]
While overwriting the message we show is "WARNING: Overwriting results file: C:\Users\maban\source\repos\UnitTestProject32\UnitTestProject32\TestResults\abc.trx"

**Comment by pvlakshm** [comment]
Removing the bug tag, and marking it an enhancement. We will use this as input when we do planning for Q2 of next year.

**Comment by GraemeF** [comment]
Same problem occurs with multiple test projects. For example, I have an `IntegrationTests.sln` with two projects in it so that I can easily run them in a single command, however the second project gives the `WARNING: Overwriting results file` message and overwrites the first project's results.

**Comment by sherland** [comment]
@pvlakshm It's now more than two years later. Can you share some details about when we can expect a fix/ enhancement on this?

**Comment by singhsarab** [comment]
We tried to resolve this issue via https://github.com/microsoft/vstest/pull/2140 
Please refer to description for the usage.

**Comment by Jsparham777** [comment]
Even using the prefix switch I still get the overwrite warning. This is due to the resolution of the timestamp. Is there a way to insert the test project name into the filename? This would stop it from overwriting or is there another way to overcome this?

**Comment by nohwnd** [comment]
@Jsparham777  Medeni was fixing this in https://github.com/microsoft/vstest/pull/2508  which is shipped in 16.8.

**Comment by jnm2** [comment]
AltCover is cool. When I run `dotnet test /p:AltCover=true` with AltCover in the test project, it outputs `coverage.netcoreapp3.1.xml` and `coverage.net5.0.xml`. Why can't .trx output be more like AltCover?

**Comment by Prodigio** [comment]
I have a similair issue when running following command
```
dotnet test --filter "Name!~IntegrationTest&Name!~Base&Name~Test" --logger "trx;LogFileName=TestResults_Unit.xml" --results-directory "C:\output\TestResults"
```

This overrides the test file on each test run. Is there a way to specify that each test run should create a new test result file? Or can I specify the file type when using `LogFilePrefix`?

**Comment by Haplois** [comment]
@Prodigio, which version of the Test Platform are you using? This issue should be fixed by #2508 and shipped with v16.8 as mentioned by @nohwnd.

**Comment by Prodigio** [comment]
> 
> 
> @Prodigio, which version of the Test Platform are you using? This issue should be fixed by #2508 and shipped with v16.8 as mentioned by @nohwnd.

@Haplois I was using v16.7.1 when I wrote the first post, but updated to v16.8.3 recently. Still the file get's overriden on every test execution.

**Comment by Haplois** [comment]
> This overrides the test file on each test run. Is there a way to specify that each test run should create a new test result file? Or can I specify the file type when using `LogFilePrefix`?

It's possible not to customize the extension when using the `LogFilePrefix` option.


> In the end, this is the command which get's executed

When you specify the exact filename using the `LogFileName` option, the TRX log gets overridden if it's already there. You need to use the `LogFilePrefix` option to keep the log file from getting overridden, unfortunately as I said, we don't support customizing the extension in this case.

**Comment by nohwnd** [comment]
This is a new feature and won't be implemented, we are focusing on adding new features to Testing.Platform instead. https://aka.ms/testingplatform
