### ISSUE TITLE
Microsoft.TestPlatform only discovers .NET Core unit tests

### ISSUE THREAD

**Issue by yaakov-h** [Microsoft/vstest#881]
## Description
This follows on from #808.

I can successfully discover and run tests in the following configurations:
* NUnit 3 (NUnit3TestAdapter 3.8.0.0-alpha1) targeting `netcoreapp1.1`
* XUnit (default .NET Core test project) targeting `netcoreapp1.1`
* MSTest (default .NET Core test project) targeting `netcoreapp1.1`

In the following configurations, `VSTestConsoleWrapper` does not discover any tests:

* NUnit 3 (NUnit3TestAdapter 3.8.0-alpha1) targeting `net45`
* NUnit 3 (NUnit3TestAdapter 3.8.0-alpha1) targeting `net46`
* Universal Windows Unit Testing Application using default MSTest adapter
    * The target framework this appears to be baked in as .NET Core 5.0
* MSTest (default .NET Core test project) targeting `net46`

## Steps to reproduce
I've uploaded a copy of my test client code to https://gist.github.com/yaakov-h/19f4cc856d4b83e606c19005ba36b961

Using:
* Microsoft.TestPlatform (from MyGet)
* Microsoft.TestPlatform.TranslationLayer (from NuGet)

You can create a new Unit Test Project from the template in VS, then modify the csproj to have `<TargetFrameworks>netcoreapp1.1;net46</TargetFrameworks>` to use as a test for the two MSTest configurations listed above.

Then, run the sample client, giving it the path to `vstest.console.exe` and the path to the compiled unit-test assembly.

## Expected behavior
```
C:\temp\VSTest>"D:\Team Data\Spike\VSTest\VSTest\bin\Debug\VSTest.exe" "C:\Temp\VSTest\packages\Microsoft.TestPlatform.15.0.0\tools\net46\vstest.console.exe" C:\Temp\UnitTestRepro\UnitTestProject1\bin\Debug\net46\UnitTestProject1.dll
Target Framework Version: .NETFramework,Version=v4.6
Log message: [Informational] Logging TestHost Diagnostics in file: C:\temp\VSTest\VSTestLog_20170622-150806.host.17-06-22_15-08-06_74174_1.log
Discovered 1 tests.
- TestMethod1
Log message: [Informational] Logging TestHost Diagnostics in file: C:\temp\VSTest\VSTestLog_20170622-150815.host.17-06-22_15-08-17_01148_4.log
-  Passed

C:\temp\VSTest>"D:\Team Data\Spike\VSTest\VSTest\bin\Debug\VSTest.exe" "C:\Temp\VSTest\packages\Microsoft.TestPlatform.15.0.0\tools\net46\vstest.console.exe" C:\Temp\UnitTestRepro\UnitTestProject1\bin\Debug\netcoreapp1.1\UnitTestProject1.dll
Target Framework Version: .NETCoreApp,Version=v1.1
Log message: [Informational] Logging TestHost Diagnostics in file: C:\temp\VSTest\VSTestLog_20170622-150815.host.17-06-22_15-08-16_23948_4.log
Discovered 1 tests.
- TestMethod1
Log message: [Informational] Logging TestHost Diagnostics in file: C:\temp\VSTest\VSTestLog_20170622-150815.host.17-06-22_15-08-17_01148_4.log
-  Passed

C:\temp\VSTest>
```

## Actual behavior
```
C:\temp\VSTest>"D:\Team Data\Spike\VSTest\VSTest\bin\Debug\VSTest.exe" "C:\Temp\VSTest\packages\Microsoft.TestPlatform.15.0.0\tools\net46\vstest.console.exe" C:\Temp\UnitTestRepro\UnitTestProject1\bin\Debug\net46\UnitTestProject1.dll
Target Framework Version: .NETFramework,Version=v4.6
Log message: [Informational] Logging TestHost Diagnostics in file: C:\temp\VSTest\VSTestLog_20170622-150806.host.17-06-22_15-08-06_74174_1.log
Discovered 0 tests.

C:\temp\VSTest>"D:\Team Data\Spike\VSTest\VSTest\bin\Debug\VSTest.exe" "C:\Temp\VSTest\packages\Microsoft.TestPlatform.15.0.0\tools\net46\vstest.console.exe" C:\Temp\UnitTestRepro\UnitTestProject1\bin\Debug\netcoreapp1.1\UnitTestProject1.dll
Target Framework Version: .NETCoreApp,Version=v1.1
Log message: [Informational] Logging TestHost Diagnostics in file: C:\temp\VSTest\VSTestLog_20170622-150815.host.17-06-22_15-08-16_23948_4.log
Discovered 1 tests.
- TestMethod1
Log message: [Informational] Logging TestHost Diagnostics in file: C:\temp\VSTest\VSTestLog_20170622-150815.host.17-06-22_15-08-17_01148_4.log
-  Passed

C:\temp\VSTest>
```

## Environment
Windows 10.0.15063.332 (v1703 "Creator's Update") (i.e. w/ .NET Framework 4.7)
Microsoft Visual Studio Enterprise 2017 15.2.26430.13

**Comment by luis-cortina** [comment]
I might be experiencing the same thing. This is what I'm doing.

1. Clone vstest repo and build
2. On the samples project I set Microsoft.TestPlatform.Protocol as my startup project
3. Set the testAssembly, testAdapterPath to the corresponding dlls on samples/UnitTestProject/bin/Debug/.netcoreapp1.0
4. Run the program and all test cases are found
5. If I switch to samples/UnitTestProject/bin/Debug/net46, and set the framework to .NETFramework,Version=v4.6, no tests are discovered.

Any idea why is this happening? Same settings as above.

Luis

**Comment by codito** [comment]
@yaakov-h I think you need to update the InitializeExtensions call ([here](https://gist.github.com/yaakov-h/19f4cc856d4b83e606c19005ba36b961#file-vstest-cs-L39)) to include the test adapter path. It can be the output directory of test project, send a list of `*.testadapter.dll` files. This is required only for `net46`, for netcore projects adapters are picked up automatically by the test platform.

@luis-cortina for the net46 scenario, are you also setting the testadapter path? It is possible to generate diagnostic logs by modifying [this line](https://github.com/Microsoft/vstest/blob/master/samples/Microsoft.TestPlatform.Protocol/RunnerProcessManager.cs#L55), add `--diag log.txt` to the process args. At end of run, it will generate 2 files `log.txt` and `log.host*.txt`, these will have more information on internals of vstest.

**Comment by luis-cortina** [comment]
I was using the wrong adapter. It works ok now.

Btw the `--diag log.txt` was hanging the app, I switch to `/diag:log.txt ` and worked. All good on my side.

**Comment by yaakov-h** [comment]
Thanks @codito, that's nearly got me all the way.

Interestingly, in my test cases:

* NUnit 3 adapter for .NET Core calls `HandleDiscoveredTests` with tests, then HandleDiscoveryComplete with `lastChunk` of `null`.
* NUnit 3 adapter for .NET Framework calls `HandleDiscoveredTests` with tests, then `HandleDiscoveryComplete` with `lastChunk` being the same tests already discovered.

I assume that's an adapter issue to take up with the NUnit team?

Also, the MSTest adapter has an odd error for UWP, then returns 0 tests:

> [Warning] File does not exist: C:\Workspace\DevTools\bin\NetCoreSampleTests\UWP\UniversalWindowsMSTestTests.exe

The file does exist. Is this one a bug for the MSTest team?

**Comment by codito** [comment]
> NUnit 3 adapter for .NET Framework calls HandleDiscoveredTests with tests, then HandleDiscoveryComplete with lastChunk being the same tests already discovered.

Looks like a bug in vstest. Can you please create an issue to track this?

> Also, the MSTest adapter has an odd error for UWP, then returns 0 tests:

It shouldn't be working :) UWP support is not available yet in test platform. We're working to add it in near future.

**Comment by yaakov-h** [comment]
@codito ah, dangit. Any ETA on UWP?

**Comment by Faizan2304** [comment]
We are tracking UWP work [here](https://github.com/Microsoft/vstest/issues/684)
