### ISSUE TITLE
No dump location message appears on testhost crash

### ISSUE THREAD

**Issue by smadala** [Microsoft/vstest#886]
## Description
> No dump location message appears on testhost crash

## Steps to reproduce
> Enable User-Mode full dump following instructions from https://msdn.microsoft.com/en-us/library/windows/desktop/bb787181(v=vs.85).aspx
> Create a Stackoverflow test method.
>  Run tests

## Expected behavior
> Error: The active Test Run was aborted because the execution process exited unexpectedly. The test execution process crashed while running the tests. To investigate further, open file:///C:/Users/samadala/AppData/Local/CrashDumps/dotnet.exe.57036.dmp file in Visual Studio and choose "Debug in mixed mode".

## Actual behavior
> The active test run was aborted. Reason: Process is terminated due to StackOverflowException.

## Environment
> TPv2

**Comment by codito** [comment]
It is planned for the blame data collector? /cc: @singhsarab @vagisha-nidhi

**Comment by smadala** [comment]
Addressed via https://github.com/Microsoft/vstest/pull/1474
