### ISSUE TITLE
Error while running dotnet test --collect:coverage

### ISSUE THREAD

**Issue by harshjain2** [Microsoft/vstest#902]
## Description
Errors are observed while using `--collect:coverage`.
>Error messages :
 1>Done building target "ShowCallOfVSTestTaskWithParameter" in project "UnitTestProject1.csproj".
   Done executing task "CallTarget".
   Using "Microsoft.TestPlatform.Build.Tasks.VSTestTask" task from assembly "C:\Program Files\dotnet\sdk\2.0.0-preview1-005977\Microsoft.TestPlatform.Build.dll".
   Task "Microsoft.TestPlatform.Build.Tasks.VSTestTask"

2> dotnet exec needs a managed .dll or .exe extension. The application specified was 'C:\Program'

## Steps to reproduce
> Run `dotnet test --collect:coverage

## Expected behavior
> Test should run with a message `Could not find data collector "coverage"`

## Actual behavior
> Error message is logged and test run fails.

Reported by  @Alxandr @dnelly  [here](https://github.com/Microsoft/vstest/issues/579)

**Comment by codito** [comment]
Triaging this for 15.5 since code coverage experience is incomplete without this.
