### ISSUE TITLE
PropertyDataComparer.GetHashCode is allocating ~5% of data of open solution

### ISSUE THREAD

**Issue by davkean** [Microsoft/vstest#903]
PropertyDataComparer<T>.GetHashCode is allocating ~1% (10 MB)~ 5% (53 MB) of the data of opening http://github.com/dotnet/project-system.

GetHashCode should not be allocating, this method should be rewritten to avoid the String.Concat:
![image](https://user-images.githubusercontent.com/1103906/27727995-06168ba2-5dc4-11e7-8932-50907a367b7d.png)

**Comment by davkean** [comment]
Apologies, it's actually allocating 5% of open solution:

![image](https://user-images.githubusercontent.com/1103906/27727995-06168ba2-5dc4-11e7-8932-50907a367b7d.png)

**Comment by davkean** [comment]
@navin22 this is another one that is showing up on the radar.

**Comment by codito** [comment]
Created https://devdiv.visualstudio.com/DevDiv/_workitems/edit/460083 to track this. Will close this workitem since it is specific to test explorer (better tracked in devdiv repo).
