### ISSUE TITLE
Make Microsoft.Testplatform nuget package available in nuget.org

### ISSUE THREAD

**Issue by Faizan2304** [Microsoft/vstest#910]
## Description
> Currently if user wants to use Microsoft.Testplatform nuget package, he/she has to consume it from Myget using myget feed https://dotnet.myget.org/F/vstest/api/v3/index.json. 

## Expected behavior
> This package should be available in nuget.org

**Comment by pvlakshm** [comment]
What is the intent here? Is it to be able to run tests on a machine without taking a dependency on Visual Studio being installed on the machine?

**Comment by luis-cortina** [comment]
@pvlakshm Yes.

**Comment by codito** [comment]
The challenge is `Microsoft.TestPlatform.CLI` package is published in nuget.org but has only netcoreapp2.0 bits. Either we can provide net46 binaries in the same package, or publish `Microsoft.TestPlatform` package.

This will be consumed by users who want to run tests in a portable console runner, or they are developing on top of vstest translation layer.

**Comment by pvlakshm** [comment]
Done: [Microsoft.TestPlatform 15.6.0-preview-20171108-02](https://www.nuget.org/packages/Microsoft.TestPlatform/15.6.0-preview-20171108-02)
