### ISSUE TITLE
Console.Error hang on .net core test

### ISSUE THREAD

**Issue by treziac** [Microsoft/vstest#918]
## Description
Console.Error may deadlock when used in test

## Steps to reproduce
Create a unit test project targeting netcoreapp1.1

```csharp
    [TestClass]
    public class UnitTest1
    {
        [TestMethod]
        public void TestMethod1()
        {
            Task[] tasks = new Task[10];
            for (int i = 0; i < 10; i++)
            {
                tasks[i] = Task.Factory.StartNew(() =>
                {
                    for (int j = 0; j < 100; j++)
                    {
                        Console.Error.WriteLine("test");
                    }
                });
            }
            Task.WaitAll(tasks);
        }
    }
```

Run test from test explorer or 
`"C:\Program Files (x86)\Microsoft Visual Studio\2017\Professional\Common7\IDE\Extensions\TestPlatform\VSTest.Console" /Framework:FrameworkCore10 bin\Debug\netcoreapp1.1\UnitTestProject1.dll`

## Expected behavior
Test succeed

## Actual behavior
Test hangs. It works with Console.WriteLine or when debugging test, either in Debug or Release. I assume there is a deadlock somewhere

This works properly on "desktop" unit test (netframework, either old csproj or newcsproj targeting net461 launched from test explorer or standard vstest.console)

Also, using Console.SetError(new StringWriter()) solve the issue

## Environment
Microsoft Visual Studio Professional 2017 
Version 15.2 (26430.14) Release
VisualStudio.15.Release/15.2.0+26430.14
vstest version 15.0.0.0

**Comment by Faizan2304** [comment]
@treziac : I am able to repro it with Visual studio 2017 version 15.2 (26430.16) with mstest package of version `1.1.11`.
But after updating mstest pacakge version to `1.1.18`, it is not getting repro. 
I am closing this as fixed.
