### ISSUE TITLE
Test Run level timeout

### ISSUE THREAD

**Issue by AbhitejJohn** [Microsoft/vstest#919]
The test platform should have the ability for users to specify a test run level timeout which allows users to terminate a test session when it exceeds a given timeout. This ensures that resources are well consumed and test sessions are constrained to a set time. A proposal for having this setting could be in the runsettings:
```
<Runsettings>
  <RunConfiguration>
     <!-- Specify timeout in ms -->
     <TestSessionTimeout>10000</TestSessionTimeout>
  </RunConfiguration>
</Runsettings>
```
Users could also pass this in as a command line argument as follows:
```
vstest.console <testContainersList> -- RunConfiguration.TestSessionTimeout=10000
```

**Comment by Faizan2304** [comment]
Completed. Will come in next release of Visual Studio/Dotnet cli.

**Comment by Faizan2304** [comment]
For detailed info about this feature https://github.com/Microsoft/vstest-docs/blob/master/RFCs/0011-Test-Session-Timeout.md
