### ISSUE TITLE
.NET standard 1.4 librarys are unable to load Microsoft.NET.Test.SDK nuget packages v15.0 or newer

### ISSUE THREAD

**Issue by mattscheffer** [Microsoft/vstest#926]
## Description
> Attempting to install Microsoft.NET.Test.SDK nuget package to new C# .Net standard 1.4 class library fails with an unspecified error. Attempt was made so that Live Unit Testsing could be ran from the .NET Standard project rather than a test project like how .NET Core projects work.

## Steps to reproduce
> Using latest VS 2017 d15rel builds with .NET Desktop Development and .NET Core workloads.
> Create a new C# .Net Standard class library.
> Navigate to the NuGet project manager, browse for Microsoft.NET.Test.Sdk and attempt to install it.

## Expected behavior
> The package installs successfully.

## Actual behavior
> The following output appears
>
>Restoring packages for C:\Users\v-masche\source\repos\ClassLibrary1\ClassLibrary1\ClassLibrary1.csproj...
  GET https://api.nuget.org/v3-flatcontainer/microsoft.net.test.sdk/index.json
  OK https://api.nuget.org/v3-flatcontainer/microsoft.net.test.sdk/index.json 262ms
  GET https://api.nuget.org/v3-flatcontainer/microsoft.net.test.sdk/15.0.0/microsoft.net.test.sdk.15.0.0.nupkg
  OK https://api.nuget.org/v3-flatcontainer/microsoft.net.test.sdk/15.0.0/microsoft.net.test.sdk.15.0.0.nupkg 6ms
  GET https://api.nuget.org/v3-flatcontainer/microsoft.testplatform.testhost/index.json
  OK https://api.nuget.org/v3-flatcontainer/microsoft.testplatform.testhost/index.json 245ms
  GET https://api.nuget.org/v3-flatcontainer/microsoft.testplatform.testhost/15.0.0/microsoft.testplatform.testhost.15.0.0.nupkg
  OK https://api.nuget.org/v3-flatcontainer/microsoft.testplatform.testhost/15.0.0/microsoft.testplatform.testhost.15.0.0.nupkg 6ms
Installing Microsoft.TestPlatform.TestHost 15.0.0.
Installing Microsoft.NET.Test.Sdk 15.0.0.
Package restore failed. Rolling back package changes for 'ClassLibrary1'.
Time Elapsed: 00:00:02.4604549
========== Finished ==========

## Environment
> Windows 10 x64 Pro. Version 1703 OSBuild 15063.413
> D15Rel 26709.00

**Comment by mattscheffer** [comment]
Additional context from @ManishJayaswal from original bug in Testimpact repo:

>.NET standard is just a standard. It does not mention what runtime to use at execution time. The idea was that the app referencing the lib should mention a runtime that is compatible with .NET Standard version mentioned in the lib. Then the lib will run on the same runtime as the app.
As far as testing for .NET standard lib by itself is concerned, there is currently a gap, in the sense that there is no good way to test it. For e.g. if you do what I have mentioned above ( where the app is a test project) then the lib will only run on the runtime mentioned in the app. However that does not mean that lib has been tested against all runtimes which the given version of .NET standard supports. We are trying to design an experience which can address this gap i.e. also have a .NET standard test project and users can specify what runtime they want the tests to use when they execute the tests.

**Comment by codito** [comment]
How do we expose this in the CLI? Could it be `dotnet test -p:DeployTargetFrameworks=net46` to target a netstandard test project to run with net46 runtime, or probably a separate switch to dotnet test. The `publish` should be triggered from `dotnet test` in this flow.

Keeping @livarcocc @pvlakshm in this discussion.

**Comment by jaredpar** [comment]
At the CLI level I would expect to be able to essentially `publish` a NS library now. This proposal at its core essentially allows `publish` to apply to libraries for now.

There is some discussion about how we pre-restore the various TF. But assuming they are present, then `publish` should just work.

**Comment by snkota** [comment]
This is being tracked external to this repo here: 
https://developercommunity.visualstudio.com/content/problem/145915/net-standard-14-librarys-are-unable-to-load-micros.html
