### ISSUE TITLE
Debug Tests does not work as expected

### ISSUE THREAD

**Issue by MiaomiaoHuangfu** [Microsoft/vstest#931]
## Steps to reproduce
> Create a .net core xunit project;
> Add 2 test methods to the projects, set Test1 as failed, Test2 as passed;
> Right click Test2 and click "Debug Tests"

## Expected behavior
> Debug Test2

## Actual behavior
> Test1 is debugged and throw an exception.
![debugnotexpectedtests](https://user-images.githubusercontent.com/22901391/28160892-1fd1236a-67f4-11e7-802a-0dad437afb70.PNG)

## Environment
> Install d15rel.26711.01 and CLI/SDK 2.0 on windows 10 x64.
> vstest.console: 15.0.26711.1
> dotnet --info
```
.NET Command Line Tools (2.0.0-preview3-006743)

Product Information:
 Version:            2.0.0-preview3-006743
 Commit SHA-1 hash:  f84e41a7d3

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.10586
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\2.0.0-preview3-006743\

Microsoft .NET Core Shared Framework Host

  Version  : 2.0.0-preview3-25512-01
  Build    : 6e7dadfdaed031624319dfd61415b2ce3498aa51
```

**Comment by Faizan2304** [comment]
No repro on 15.3.0 Preview 4.0[26712.d15rel]

**Comment by MiaomiaoHuangfu** [comment]
Close this bug and track https://github.com/Microsoft/vstest/issues/537.
