### ISSUE TITLE
Removing .net framework and add it back to a Multi-TFM solution causes test discovery miss

### ISSUE THREAD

**Issue by jimmy9988** [Microsoft/vstest#932]
## Description
In Live Unit Testing, we use the api in TestPlatform.TranslationLayer to discover tests.
With a Multi-TFM solution, test won't be discovered after removing .net framework and add it back.
More detailed info is on https://github.com/dotnet/testimpact/issues/2032
## Steps to reproduce
Use the solution: \\\mlangfs1\public\enhsu\MTFM

1. Start LUT
2. Edit MTFM.csproj
3. Remove net461 from TargetFrameworks
4. Add net461 to TargetFrameworks

## Expected behavior
1 test is discovered in net461\UnitTestProject1.dll file
## Actual behavior
0 test is discovered

## Environment
Microsoft.TestPlatform.TranslationLayer: 15.3.0-preview-20170609-03
VS: 15.3.0-preview4 26711.1.d15rel

**Comment by Faizan2304** [comment]
The issue is with the testdll on which testplatform try to discover test. 
There is no code inside the test dll. It seems some issue with how we are building testproject here.
