### ISSUE TITLE
How to properly decorate custom data collector(InProcDataCollector)

### ISSUE THREAD

**Issue by luis-cortina** [Microsoft/vstest#937]
Hi:

I was reading the docs on how to create and enable a custom data collector for the tests. 
I haven't been able to properly get it to work and I need some help. By my reading, there are two places to specify the data collector information:

- RunSettingsFile. According to VS2017 this is a sample DataCollector declaration:

`<DataCollector uri="dataCollector://Samples/SampleCollector/1.0" assemblyQualifiedName="Samples.SampleCollector.SampleDataCollector, SampleCollectors, Version=1.0.0.0, Culture=neutral, PublicKeyToken=1111111111111111" friendlyName="sampleCollector">`

-Decorating the DataCollector class
I'm inheriting from InProcDataCollection and I was using this attributes:
- [FriendlyName("XLogCollector")]  for the friendlyName setting on the runsetting file
- [ExtensionUri("")] for the uri setting (I don't know if this one makes sense, no documentation about it I could find)

Anyway can you guys help me to figure out the right settings to make my custom datacollector work?

Luis

**Comment by codito** [comment]
Here's a sample: https://github.com/Microsoft/vstest/tree/master/test/TestAssets/SimpleDataCollector

Here's the integration test which uses it: https://github.com/Microsoft/vstest/blob/5675491e4067cda6d5fdb74b4f7f653c864d449f/test/Microsoft.TestPlatform.SmokeTests/DataCollectorTests.cs#L16 (`GetInProcDataCollectionRunsettingsFile` has an example of a runsettings which may help).

**Comment by luis-cortina** [comment]
Thanks for the reply but still not working for me.
This is my scenario:

- VS2017 15.2(26430.14)
- I have a .Net4.6.2 Class Library project that contains the CustomDataCollector
- I have a .Net4.6.2 Test Project that contains the test that uses the data collector, this project references the ClassLibrary
- I created a .runsettings file in the Test Project (And told VS to use it)and updated it based on you example like this:

```
<?xml version="1.0" encoding="utf-8"?>
<RunSettings>
  <InProcDataCollectionRunSettings>
    <InProcDataCollectors>
      <InProcDataCollector
        friendlyName='Test Impact' uri='InProcDataCollector://Microsoft/TestImpact/1.0'
        assemblyQualifiedName="MyAssembly.FullNameSpace.DataCollectorClassName, MyAssemblyName, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null"
        codebase="MyAssemblyName.dll">
        <Configuration>
          <Port>4312</Port>
        </Configuration>
      </InProcDataCollector>
    </InProcDataCollectors>
  </InProcDataCollectionRunSettings>
</RunSettings>
```

A few points:

- How does the **friendlyName** and **uri** settings gets set?
- Do I need the configuration Element for this to work?
- Is there a problem in my process? Ideally I would want to use this workflow to Debug my Custom Data Collector

Thanks in advance,

Luis

**Comment by luis-cortina** [comment]
Here is a sample project based on my previous comment. Cna you please take a look at it and maybe point me in the right direction?

Thanks in advance,

Luis
[InProcTest.zip](https://github.com/Microsoft/vstest/files/1157380/InProcTest.zip)

**Comment by luis-cortina** [comment]
Any news on this?

**Comment by luis-cortina** [comment]
Nevermind, my runsettings were incorrect. 
Thanks for the pointers.
