### ISSUE TITLE
Request for Merge TRX functionality

### ISSUE THREAD

**Issue by nigurr** [Microsoft/vstest#939]
## Description
> In distributed test execution, set of tests can be run in parallel across different machines, which will result in multiple TRX files being generated.
Since it's single test run (distributed), we need to have consolidated TRX (single).

Platform should expose/ship the nuget package to merge multiple TRX files into single one.

**Comment by abhishkk** [comment]
As VSTS pipeline is moving away from trx, we are not enhancing the platform with trx merge functionality. We will revisit the ask in case such request comes for different scenarios.

**Comment by boga5** [comment]
Hey guys!
It would be great if we get this functionality in Azure DevOps.
Let me know if there are any workarounds at least!
