### ISSUE TITLE
 "C:\Program Files\dotnet\sdk\2.0.0-preview2-006497\TestHost\datacollector.exe".Error in manifest or policy file "C:\Program Files\dotnet\sdk\2.0.0-preview2-006497\TestHost\datacollector.exe.Config" 

### ISSUE THREAD

**Issue by davkean** [Microsoft/vstest#942]
## Description
> Event View contains a error: 

Activation context generation failed for "C:\Program Files\dotnet\sdk\2.0.0-preview2-006497\TestHost\datacollector.exe".Error in manifest or policy file "C:\Program Files\dotnet\sdk\2.0.0-preview2-006497\TestHost\datacollector.exe.Config" on line 1. Invalid Xml syntax.

Looks like there's a comment on line 1 of datacollector.exe.config which is causing this.

**Comment by harshjain2** [comment]
This issue is fixed through this PR https://github.com/Microsoft/vstest/pull/900
