### ISSUE TITLE
Test fails when using /InIsolation parameter

### ISSUE THREAD

**Issue by RobertFromBerlin** [Microsoft/vstest#947]
## Description
I have a test where the garbage collector is under heavy usage. When testing at the command line using vstest.console.exe without the /InIsolation parameter tests succeeds. Running with the /InIsolation paramter or inside Visual Studio test fails.

## Steps to reproduce
* Compile attached project (x86, no matter if Debug or Release)
* Run test: vstest.console.exe MemPressure.dll /platform:x86  /InIsolation

## Expected behavior
Test should succeed.

## Actual behavior
* Test fails. I think the error message is wrong. I have a similar test for our internal suite. Here the test just hangs.
* Test also does not fail if number of iterations (UnitTest1.cs, line 12) is lower (for example 2500).

## Environment
* Win10 (10.0.15063), vstest 15.0.26228.0 (Visual Studio 2017)
[MemPressure.zip](https://github.com/Microsoft/vstest/files/1161738/MemPressure.zip)

**Comment by RobertFromBerlin** [comment]
So you can reproduce this? What's happen next?

Just curios - Robert

**Comment by Faizan2304** [comment]
@RobertFromBerlin, i didnt try yet. After reading the issue its seems a bug in TestPlatform. Will update you once i will strat working on it.

**Comment by mayankbansal018** [comment]
@RobertFromBerlin "InIsolation" switch was added in latest vstest.console.

Also I debugged your repro project in VS IDE, & if the count is set 25000, the test method is causing "Out Of Memory" exception. Since we cannot OOM Exception all the time, you are getting an invalid error message.

Can you please try and debug this in latest VS 2017.5

**Comment by mayankbansal018** [comment]
@RobertFromBerlin I've provided my analysis above, please go through it & see if it resolves the issue for you or not.

I'll close this thread for now, feel free to re-open if you still encounter this issue.
