### ISSUE TITLE
Test is not getting discover/run from testproject with <?...?> in app.config file

### ISSUE THREAD

**Issue by Faizan2304** [Microsoft/vstest#951]
## Description
Test is not getting discover/run from testproject with <?...?> in app.config file

## Steps to reproduce
[ReproProject.zip](https://github.com/Microsoft/vstest/files/1169490/ReproProject.zip)

## Expected behavior
Test should run.

## Actual behavior
Test is failing with message:
```
No test is available in D:\Work\Bug\ConfigFileIssue\AssemblyLoadUnitTestProject\DesktopUnitTestProject11\UnitTestProject2\bin\Debug\UnitTestProject2.dll. Make sure that test discoverer & executors are registered and platform & framework version settings are appropriate and try again.
```
This is a deceiving message as its hiding the actual reason. We have created a bug in testfx to improve message  https://github.com/Microsoft/testfx/issues/203

## Environment
All version of vstest.console

**Comment by pvlakshm** [comment]
Closing this; this is a testfx issue and outside the scope of this repo.
