### ISSUE TITLE
Get errors when run .netcore unit tests 

### ISSUE THREAD

**Issue by tingting0929** [Microsoft/vstest#959]
Use Version 2.* to Run a test suite. In this test suite, there're some test cases associated to some .net Core unit test methods. It will get the error:
![platform](https://user-images.githubusercontent.com/18899739/28658912-00608556-72e0-11e7-9f46-63369beb5f6e.png)

![3](https://user-images.githubusercontent.com/18899739/28658953-2797dbba-72e0-11e7-9ea6-695fb70b3177.png)

It will get the error:
`Error : Could not load file or assembly 'Microsoft.VisualStudio.TestPlatform.Utilities, Version=15.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' or one of its dependencies. The system cannot find the file specified.`

If I do the exact same setup with a .NET Framework unit test project, the testing runs passes successfully. This seems to be a problem with .NETCoreApp 1.1 only.

**Comment by Faizan2304** [comment]
@tingting0929 do you have access to the machine where its running test?
If yes can you go to the machine and run `"C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\Common7\IDE\Extensions\TestPlatform\vstest.cosole.exe" Path-to-test-dll /framework:".NETCoreApp,Version=v1.1"`

/UseVsixExtension is not supported with vstest.console.exe version 2

**Comment by Zazzmatazz** [comment]
Good morning @Faizan2304,
I am the one behind this issue (see [here](https://developercommunity.visualstudio.com/content/problem/69284/cant-associate-to-test-case-on-tfs.html) and, more recently, [here](https://developercommunity.visualstudio.com/content/problem/86088/cannot-run-vsts-on-demand-testing-on-net-core-11.html))

I have run the command on the test machine, and it runs successfully:  One test was found successfully.

One of the main errors found was here:
```System.MissingMethodException: Method not found: 'Microsoft.VisualStudio.TestPlatform.ObjectModel.DataCollectorSettings Microsoft.VisualStudio.TestPlatform.ObjectModel.Utilities.XmlRunSettingsUtilities.CreateFakesDataCollectorSettings()'.```

The error also references multi-agent phase: "Other console options is not supported when using the multi-agent phase setting. This option will be ignored." I only have one test agent running on one controller running on one build agent.

The only references I can find on the multi-agent phase are found in the I18n JSON files in this repository.

**Comment by Faizan2304** [comment]
Sorry @Zazzmatazz for replying so late. I missed this thread. 
Please help me to get the answer of some question
1) Are you using `VSTS` or `TFS onprem`?
2) Are you using `Build` or `Release` definition?
3) Which task you are using to run task? Is it `Run Functional test` or `Visual studio Test`?
4) What is the version of visual studio install on the machine where test is running?

@nigurr: Its seems like an issue in task as he is hitting this error
`The error also references multi-agent phase: "Other console options is not supported when using the multi-agent phase setting. This option will be ignored." I only have one test agent running on one controller running on one build agent.`
Can you please guide us to collect right info from client.

**Comment by nigurr** [comment]
@Zazzmatazz Currently .net core test support is not available in vstest task. It's on our backlog and we will be addressing it soon. 
Please use "dotnet" task to run the .net core tests.

**Comment by pvlakshm** [comment]
Closing this.
