### ISSUE TITLE
Still doesn't support specifying a logger path on the command-line

### ISSUE THREAD

**Issue by IanKemp** [Microsoft/vstest#968]
Refer to #522, which was closed without actually implementing the requested solution for no good reason that I can see.

I need to be able to run

`vstest.console.exe MyTestContainer.dll /Logger:"C:\path\to\my\custom\logger.dll";params`

because I can't copy my custom DLL into `Common7\IDE\CommonExtensions\Microsoft\TestWindow` due to permissions, plus the logger DLL can and will change and redeploying it every time it changes is not feasible.

**Comment by Faizan2304** [comment]
Thanks @IanKemp for opening the issue with us. We have addressed the request of Issue #522. 
 
You will be happy to know that we have enabled logger extensibility in TestPlatform V2 ( You can use it in visual studio 2017 update3 preview1 onwards).
For detailed information about how to use logger extensibility to create and use your own logger [here]( https://github.com/Microsoft/vstest-docs/blob/master/docs/report.md#test-loggers) 

Having said that now you can use your logger as follows

`Common7\IDE\Extensions\TestPlatform\vstest.console.exe  MyTestContainer.dll /Logger:"FriendlyNameOfYourTestLogger;params" /TestAdapterPath:"C:\path\to\my\custom"`

* The new vstest.console (we call it TPV2/TestPlatformV2) get ship as a vsix with visual studio and it reside in `Common7\IDE\Extensions\TestPlatform`.
* You can specify the location of logger dll using `TestAdapterPath` argument.

I hope it will solve your problem. Please do let us know if you have any concern or query.

**Comment by Faizan2304** [comment]
@IanKemp : I am closing this issue. Please feel free to reopen it, if you have any concern or query.
