### ISSUE TITLE
Incorrect reporting of data driven nunit tests in trx.

### ISSUE THREAD

**Issue by AbhitejJohn** [Microsoft/vstest#972]
> From @arielcloud 

## Description
I have nunit test like this:

`protected static TimeRange[] TestCaseX = new TimeRange[] 
        {
            new TimeRange(new DateTime(2016, 2, 3), new DateTime(2016, 2, 4)),
            new TimeRange(new DateTime(2016, 2, 3), new DateTime(2016, 3, 3))
        };`

`[Test, TestCaseSource(nameof(TestCaseX))]
        public void testFoo(TimeRange time)`

TimeRange exists in Infra.Services

when runnig tests with "dotnet test --logger:trx" it output the trx file with:
"className="BL.Tests.services.OneTimeTests.testFoo(infra.Services" 

probably because it see the test as 
"BL.Tests.services.OneTimeTests.testFoo(infra.Services.TimeRange)"

and it is trying to take the className by splice(".") and taking the first part till the dot, which is not correct in this case when we have dots also in the test name.

is exists any fix for that?

10x!

**Comment by cltshivash** [comment]
There's no first class mechanism today for an adapter to pass the class name. This needs to be an enhancement.

**Comment by smadala** [comment]
Related to https://github.com/Microsoft/vstest/pull/1677

**Comment by smadala** [comment]
@abhishkk Can we close this?

**Comment by abhishkk** [comment]
Fixed issue with PR: https://github.com/Microsoft/vstest/pull/1677
