### ISSUE TITLE
dotnet test for .net core mstest or xunit project from CLI outputs unreadable text

### ISSUE THREAD

**Issue by MiaomiaoHuangfu** [Microsoft/vstest#977]
## Description
> dotnet test for .net core mstet or xunit project from CLI will output unreadable text

## Steps to reproduce

- md CSNC11xUnitTest & cd CSNC11xUnitTest;
- Dotnet new xUnit -> succeeded;
- Dotnet restore  -> succeeded;
- Dotnet build  -> succeeded;
- Dotnet test

## Expected behavior
> dotnet test passed and output readable text

## Actual behavior
> dotnet test outputs unreadable text:
```
c:\CLITesting\CSNC11xUnitTest>dotnet test
Build started, please wait...
Build completed.
 
Test run for c:\CLITesting\CSNC11xUnitTest\bin\Debug\netcoreapp1.1\CSNC11xUnitTest.dll(.NETCoreApp,Version=v1.1)
Microsoft (R) 娴嬭瘯鎵ц鍛戒护琛屽伐鍏风増鏈?15.0.0.0
鐗堟潈鎵€鏈?(C) Microsoft Corporation銆備繚鐣欐墍鏈夋潈鍒┿€?
 
姝ｅ湪鍚姩娴嬭瘯鎵ц锛岃绋嶅€?..
[xUnit.net 00:00:00.5464481]   Discovering: CSNC11xUnitTest
[xUnit.net 00:00:01.1067203]   Discovered:  CSNC11xUnitTest
[xUnit.net 00:00:01.1429434]   Starting:    CSNC11xUnitTest
[xUnit.net 00:00:01.2631716]   Finished:    CSNC11xUnitTest
 
鎬绘祴璇? 1銆傚凡閫氳繃: 1銆傚け璐? 0銆傚凡璺宠繃: 0銆?
娴嬭瘯杩愯鎴愬姛銆?
娴嬭瘯鎵ц鏃堕棿: 1.9587 绉?

```
## Environment
> OS: windows 10 enterprise RTM Chinese-PRC x64 
> Install d15rel.26730.00 for Chinese language 
> vstest.console: 15.0.0
> dotnet --info
```
.NET Command Line Tools (1.1.0)

Product Information:
 Version:            1.1.0
 Commit SHA-1 hash:  d6f4336106

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.10240
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\1.1.0
```

**Comment by singhsarab** [comment]
Unable to reproduce this is the latest bits

Microsoft (R) 测试执行命令行工具版本 15.6.0-preview-20180109-01
版权所有 (C) Microsoft Corporation。保留所有权利。

正在启动测试执行，请稍候...

总测试: 1。已通过: 1。失败: 0。已跳过: 0。
测试运行成功。
测试执行时间: 1.8383 秒
