### ISSUE TITLE
Show total tests as "Unknown" when test run is aborted.

### ISSUE THREAD

**Issue by smadala** [Microsoft/vstest#979]
## Description
- When test were aborted the total number of tests shown as number of tests ran till that point of time. 
- Stdout won't show any tests failed , where as stderr show as `Test Run Failed`
- Having no error or failure message in stdout confuses the customer who redirect the stderr and stdout different files. 

## Steps to reproduce
- Create a test project with 3 tests with one as stackoverflow test.
- Run the tests.

## Expected behavior
-  `Total tests: Unknown. Passed: 2. Failed: 0. Skipped: 0.`?

## Actual behavior
- Stdout show as `Total tests: 2. Passed: 2. Failed: 0. Skipped: 0.`
- Actual number tests are 3. and one is failed.

**Comment by pvlakshm** [comment]
This would be nice to have. However, any resulting confusion is because of an intentional action by the user to redirect stdout and stderr. Therefore I am inclined to wait for more feedback on this issue to come in before we decide on the next steps.

**Comment by harshjain2** [comment]
@Faizan2304 @pvlakshm It would be good, if we can explicitly display that the test run is aborted or cancelled by user.
To me, Unknown sounds a bit incorrect.

Displaying `Total tests` as unknown with `Test run aborted/cancelled` message would be more meaningful.

**Comment by Faizan2304** [comment]
@harshjain2 
>Displaying Total tests as unknown with Test run aborted/cancelled message would be more meaningful.

We are displaying `Total tests: Unknown` and then displaying aborted/cancelled message.
Please see attached screen shot below

![image](https://user-images.githubusercontent.com/19184362/29260063-f90db482-80e4-11e7-9a02-a088db6ea77e.png)
