### ISSUE TITLE
trx logger does not include Description attribute

### ISSUE THREAD

**Issue by AbhitejJohn** [microsoft/vstest#98]
## Description

 Test description attributes like Description, CssIteration, WorkItem, CssProjectStructure do not show up in the trx log. Only Owner and Priority are part of the log.
## Steps to reproduce
1. Create an MSTest V1 based project.
2. Add a DescriptionAttribute on top of the test method.
3. Run tests with trx turned on.
## Expected behavior

> The trx should have the description string associated with the test in the log.
## Actual behavior

> The description string does not show up in the log.
## Environment

> I'm trying this on Dev15 prev-5 and on Windows 10.

**Comment by dotMorten** [comment]
It's already in the TRX schema:
```xml
    <xs:element name="Properties" minOccurs="0">
        <xs:complexType>
          <xs:sequence>
            <xs:element name="Property" minOccurs="0" maxOccurs="unbounded">
              <xs:complexType>
                <xs:sequence>
                  <xs:element name="Key" />
                  <xs:element name="Value" />
                </xs:sequence>
              </xs:complexType>
            </xs:element>
          </xs:sequence>
        </xs:complexType>
      </xs:element>
      <xs:element name="WorkItemIDs" type="WorkItemIDsType" minOccurs="0">
        <xs:annotation>
          <xs:documentation>References to workitems (bugs, issues) related to this test on the team server.</xs:documentation>
        </xs:annotation>
      </xs:element>
```

Essentially any use of `[TestProperty]` should go in here. I was able to use it in my own TRX logger, and it passes schema validation

**Comment by smadala** [comment]
@dotMorten Thanks for info. Do you like to patch your own TRX logger changes to vstest TRX logger?

**Comment by dotMorten** [comment]
@smadala [My logger](https://github.com/dotMorten/MSTestX/blob/master/src/TestAppRunner/TestAppRunner/TrxWriter.cs) is completely different from yours. I would have preferred being able to reuse the TRX logger you have (a .NET Standard version that can serialize an `IEnumerable<TestResult>` would be appreciated !), but found it overly complex to deal with and would need a lot of forking.

I could try and take a stab at it, but yours is so much more complex :-)

**Comment by DmitryNaumovA1qa** [comment]
Is there a fix for the issue?  
If so which version of .net core should I use to be able to include description attribute?

**Comment by dotMorten** [comment]
@dmitryNaumovA1qa no 😒

**Comment by dotMorten** [comment]
Just submitted a PR that ensures Description, WorkItemIDs and TestProperties gets written to the TRX

**Comment by OsirisTerje** [comment]
The Trx logger does not write out categories from NUnit, because the category type name is hardcoded to "MSTestDiscoverer.TestCategory", whereas the NUnit name is "NUnit.TestCategory".  The idea back in 2012 was that categories should be Traits that where not hardcoded to anything in particular.  Can we a) get this fixed so that any trait show up in the trx file?  or b) Add in the NUnit category type name ?

See issue https://github.com/nunit/nunit3-vs-adapter/issues/506  

We [NUnit] accepted a PR to include the MSTest name as a temporary workaround until this was fixed, but it turns out this results in duplicate categories in the Test Explorer.  https://github.com/nunit/nunit3-vs-adapter/issues/559

**Comment by dotMorten** [comment]
@OsirisTerje I'm not sure about the relevance wrt writing a TRX report? The xsd schema has a generic Category field. How these categories are transported around with which trait name seems sort of irrelevant, but if you want to use a Microsoft trx defined standard, you sort of have to adhere to that, or request their loggers have a more abstract way to define the various traits and their meaning.,

**Comment by OsirisTerje** [comment]
@dotMorten  This code line https://github.com/Microsoft/vstest/blob/0341da456744f78bba8ff2a25c1cddfc89c87b08/src/Microsoft.TestPlatform.Extensions.TrxLogger/Utility/Converter.cs#L51  looks hardcoded to MSTest to me.  The NUnit3TestAdapter doesn't write to the trx file, that  is all up to vstest, it only provides the information, and the category *type* name is marking it as a category.  There is no generic type name for the category on that side .

**Comment by nohwnd** [comment]
This is a new feature and won't be implemented, we are focusing on adding new features to Testing.Platform instead. https://aka.ms/testingplatform
