### ISSUE TITLE
The custom test adapter search path provided was not found

### ISSUE THREAD

**Issue by prawalagarwal** [Microsoft/vstest#991]
## Description
> Running MSTestV2 tests with /testadapterpath flag. Came across an issue when path was present both in runsettings file and provided via the command line flag. The path in the settings file is incorrect and hence was not found. But the error message ends up showing the path provided via the cmd.

## Steps to reproduce
> Create a normal test project on mstestv2.
> Run like this: "C:\Program Files (x86)\Microsoft Visual Studio\Preview\Enterprise\Common7\IDE\Extensions\TestPlatform\vstest.console.exe" "C:\source\repos\SampleCalculatorNew\SampleCalculatorTests\bin\Debug\SampleCalculatorTests.dll" /collect:"Code Coverage" /Settings:"C:\source\repos\SampleCalculatorNew\TestSettings.runsettings"  /testadapterpath:"C:\source\repos\SampleCalculatorNew\SampleCalculatorTests\bin\Debug"

In the above runsettings provide some invalid path to test adapters.

## Expected behavior
> The run should fail stating that the invalid file given in the runsettings file

## Actual behavior
> The run fails stating the path provided in the cmd line.

**Comment by Faizan2304** [comment]
Fixed!!
