### ISSUE TITLE
The specified path, file name, or both are too long

### ISSUE THREAD

**Issue by wonix** [Microsoft/vstest#996]
## Description
Not able to run Live Unit Test due to having a long path and file name in a project in my sotluion. Need to increase the max limit of 260 characters.

## Steps to reproduce
Live Unit Test -> Starts results in the following error message in the output window

> [10:11:33.201 Info] Live Unit Testing started.
> [10:11:33.399 Error] - FatalError - Microsoft.Build.Exceptions.InvalidProjectFileException: The expression "[MSBuild]::NormalizePath(**LONG_PATH_HERE**)" cannot be evaluated. The specified path, file name, or both are too long. The fully qualified file name must be less than 260 characters, and the directory name must be less than 248 characters.  C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\MSBuild\15.0\Bin\Microsoft.Common.CurrentVersion.targets
>    at Microsoft.Build.Shared.ProjectErrorUtilities.ThrowInvalidProject(String errorSubCategoryResourceName, IElementLocation elementLocation, String resourceName, Object[] args)
>    at Microsoft.Build.Evaluation.Expander`2.Function`1.Execute(Object objectInstance, IPropertyProvider`1 properties, ExpanderOptions options, IElementLocation elementLocation)
>    at Microsoft.Build.Evaluation.Expander`2.PropertyExpander`1.ExpandPropertyBody(String propertyBody, Object propertyValue, IPropertyProvider`1 properties, ExpanderOptions options, IElementLocation elementLocation, UsedUninitializedProperties usedUninitializedProperties)
>    at Microsoft.Build.Evaluation.Expander`2.PropertyExpander`1.ExpandPropertiesLeaveTypedAndEscaped(String expression, IPropertyProvider`1 properties, ExpanderOptions options, IElementLocation elementLocation, UsedUninitializedProperties usedUninitializedProperties)
>    at Microsoft.Build.Evaluation.Expander`2.PropertyExpander`1.ExpandPropertiesLeaveEscaped(String expression, IPropertyProvider`1 properties, ExpanderOptions options, IElementLocation elementLocation, UsedUninitializedProperties usedUninitializedProperties)
>    at Microsoft.Build.Evaluation.Expander`2.ExpandIntoStringLeaveEscaped(String expression, ExpanderOptions options, IElementLocation elementLocation)
>    at Microsoft.Build.Evaluation.ItemSpec`2.BuildItemFragments(IElementLocation itemSpecLocation, Boolean expandProperties)
>    at Microsoft.Build.Evaluation.ItemSpec`2..ctor(String itemSpec, Expander`2 expander, IElementLocation itemSpecLocation, Boolean expandProperties)
>    at Microsoft.Build.Evaluation.LazyItemEvaluator`4.ProcessItemSpec(String itemSpec, IElementLocation itemSpecLocation, OperationBuilder builder)
>    at Microsoft.Build.Evaluation.LazyItemEvaluator`4.BuildIncludeOperation(String rootDirectory, ProjectItemElement itemElement, Boolean conditionResult)
>    at Microsoft.Build.Evaluation.LazyItemEvaluator`4.ProcessItemElement(String rootDirectory, ProjectItemElement itemElement, Boolean conditionResult)
>    at Microsoft.Build.Evaluation.Evaluator`4.EvaluateItemElement(Boolean itemGroupConditionResult, ProjectItemElement itemElement, LazyItemEvaluator`4 lazyEvaluator)
>    at Microsoft.Build.Evaluation.Evaluator`4.EvaluateItemGroupElement(ProjectItemGroupElement itemGroupElement, LazyItemEvaluator`4 lazyEvaluator)
>    at Microsoft.Build.Evaluation.Evaluator`4.Evaluate(ILoggingService loggingService, BuildEventContext buildEventContext)
>    at Microsoft.Build.Evaluation.Evaluator`4.Evaluate(IEvaluatorData`4 data, ProjectRootElement root, ProjectLoadSettings loadSettings, Int32 maxNodeCount, PropertyDictionary`1 environmentProperties, ILoggingService loggingService, IItemFactory`2 itemFactory, IToolsetProvider toolsetProvider, ProjectRootElementCache projectRootElementCache, BuildEventContext buildEventContext, ProjectInstance projectInstanceIfAnyForDebuggerOnly, SdkResolution sdkResolution)
>    at Microsoft.Build.Evaluation.Project.Reevaluate(ILoggingService loggingServiceForEvaluation, ProjectLoadSettings loadSettings)
>    at Microsoft.Build.Evaluation.Project.ReevaluateIfNecessary(ILoggingService loggingServiceForEvaluation, ProjectLoadSettings loadSettings)
>    at Microsoft.CodeAnalysis.LiveUnitTesting.BuildManagement.BuildManagerState.OverrideMSBuildProjectOutputPath(Project adjustedMSBuildProject, ProjectId projectId, Boolean projectConfigurationChanged)
>    at Microsoft.CodeAnalysis.LiveUnitTesting.BuildManagement.BuildManagerState.<LoadProjectInfoAsync>d__137.MoveNext()
> --- End of stack trace from previous location where exception was thrown ---
>    at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
>    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
>    at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
>    at Microsoft.CodeAnalysis.LiveUnitTesting.BuildManagement.BuildManagerState.<BuildRelatedProjectsAsync>d__119.MoveNext()
> --- End of stack trace from previous location where exception was thrown ---
>    at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
>    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
>    at Microsoft.CodeAnalysis.LiveUnitTesting.BuildManagement.BuildManagerState.<BuildAsync>d__89.MoveNext()
> [10:11:33.942 Info] Live Unit Testing stopped.

## Environment
Windows 10
Visual Studio Enterprise 2017 Version 15.3.0

**Comment by Faizan2304** [comment]
This seems an issue in LUT. Created a new issue in LUT repo https://github.com/dotnet/testimpact/issues/2132

**Comment by Cyberboss** [comment]
Any update on this?

**Comment by barry-hall** [comment]
I also have this issue on certain projects.

**Comment by smadala** [comment]
@ManishJayaswal FYI.

**Comment by Crono1981** [comment]
Having this issue as well.
