### ISSUE TITLE
.runsettings file does not affect

### ISSUE THREAD

**Issue by urasandesu** [Microsoft/vstest#999]
## Description
Visual Studio 2017 does not load .runsettings file.

## Steps to reproduce
I attached the minimum sample that can work fine in Visual Studio 2013. The procedure is the followings:
1. Select the "Build" menu -> open "Configuration Manager".
2. Change "Active solution configuration" to "Debug(.NET 3.5)".
3. Build the solution.
4. Select the "Test" menu -> "Windows" -> open "Test Explorer".
5. Select the "Test" menu again -> Select "Test Settings File" -> select "v3.5.runsettings" in the project.
6. Select the "Test" menu again -> "Default Processor Architecture" -> "x64".
7. Select the "Test" menu again -> uncheck "Keep Test Execution Engine Running".
8. Select the "Test" menu -> "Run" -> execute "All Tests". 

=> All tests are failed. This is the problem.

The same procedure works fine in Visual Studio 2013. Also, the combination of "Active solution configuration": "Debug(.NET 4.6.2)" and "v4.5.runsettings" works fine.

* VS2013 sample: https://drive.google.com/open?id=0B4s_gXgDJAgbVE5jeGJaM3BhUGs
* VS2017 sample: https://drive.google.com/open?id=0B4s_gXgDJAgbejJCaHpCQTRlQ0k

## Expected behavior
Pass all tests of the sample

## Actual behavior
Fail all tests of the sample

## Environment
* Visual Studio 2017 v15.3(26730.3)

**Comment by singhsarab** [comment]
@urasandesu 
Apologies for not being able to get back to you sooner.
Are you still hitting the issue in VS2017 v15.5 ?
With v15.5, VS uses the new TestPlatform to run the tests, in this case testhost.exe will run the tests instead if vstest.executionengine. For test projects targeting .net framework v3.5, testhost runs in compat mode and should be able to run the tests.

Tried switching back to older test platform for v3.5 test projects by modifying TestPlatform.config ("C:\Program Files (x86)\Microsoft Visual Studio\<InstallationFolder>\<SKU>\Common7\IDE\Extensions\TestPlatform\testplatform.config") file. 
```<add key="feature.net35" value="false" />```
I was able to successfully run the tests in the sample project you shared, as the process and runtime match the expectation.
